ROSS: ross/models/airport/other/3-simple-airport.c File Reference
3-simple-airport.c File Reference
#include <ross.h>
Data Structures
struct Msg_Data
struct Airport_State
Macros
#define AIR_LP 1
Enumerations
enum events {
ARRIVAL, LAND, DEPARTURE, ARRIVAL,
LAND, DEPARTURE, CIVILIAN = 1, BUILDING,
POWERLINE, SUBSTATION, GENERATOR, UPDATEDRAW,
UPDATEAVAILABLE, DAMAGE, REPAIR, UPDATEOCCUPANCY,
POWERON, POWEROFF, HOME, WORK,
TRAVELHOME, TRAVELWORK, TRAVELLEISURE, LEISURE,
CRISISLEVELRISES, CRISISLEVELFALLS, FINDFAMILY, EVACUATE,
SHELTER, FLIGHT, GROUP, SHOCK,
CURIOUS, TRAVELEVACUATE, RELEASEHOME, RELEASEWORK,
RELEASEHOSPITAL, HOSPITAL, TRAVELHOSPITAL, RELEASELEISURE,
ARIVAL, DEPARTURE, DIRECTION_SELECT
}
Functions
void Airport_StartUp (Airport_State *, tw_lp *)
void Airport_EventHandler (Airport_State *, tw_bf *, Msg_Data *, tw_lp *)
void Airport_RC_EventHandler (Airport_State *, tw_bf *, Msg_Data *, tw_lp *)
void Airport_Statistics_CollectStats (Airport_State *, tw_lp *)
int main (int argc, char *argv[])
Variables
int A = 60
int R = 10
int G = 45
int NumLanded = 0
tw_lptype airport_lps []
Macro Definition Documentation
#define AIR_LP 1
Definition at line 32 of file 3-simple-airport.c.
Referenced by main().
Enumeration Type Documentation
enum events
Enumerator
ARRIVAL
LAND
DEPARTURE
ARRIVAL
LAND
DEPARTURE
CIVILIAN
BUILDING
POWERLINE
SUBSTATION
GENERATOR
UPDATEDRAW
UPDATEAVAILABLE
DAMAGE
REPAIR
UPDATEOCCUPANCY
POWERON
POWEROFF
HOME
WORK
TRAVELHOME
TRAVELWORK
TRAVELLEISURE
LEISURE
CRISISLEVELRISES
CRISISLEVELFALLS
FINDFAMILY
EVACUATE
SHELTER
FLIGHT
GROUP
SHOCK
CURIOUS
TRAVELEVACUATE
RELEASEHOME
RELEASEWORK
RELEASEHOSPITAL
HOSPITAL
TRAVELHOSPITAL
RELEASELEISURE
ARIVAL
DEPARTURE
DIRECTION_SELECT
Definition at line 11 of file 3-simple-airport.c.
Function Documentation
void Airport_EventHandler (Airport_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 107 of file 3-simple-airport.c.
References A, ARRIVAL, tw_bf::c1, DEPARTURE, Msg_Data::event_type, G, tw_lp::id, Airport_State::InTheAir, LAND, Airport_State::NumLanded, Airport_State::OnTheGround, R, Airport_State::RunwayFree, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlp(), and tw_rand_exponential().
void Airport_RC_EventHandler (Airport_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 166 of file 3-simple-airport.c.
References ARRIVAL, tw_bf::c1, DEPARTURE, Msg_Data::event_type, tw_lp::id, Airport_State::InTheAir, LAND, Airport_State::NumLanded, Airport_State::OnTheGround, Airport_State::RunwayFree, and tw_rand_reverse_unif.
void Airport_StartUp (Airport_State * SV, tw_lp * lp)
Definition at line 87 of file 3-simple-airport.c.
References A, ARRIVAL, Msg_Data::event_type, tw_lp::id, Airport_State::InTheAir, Airport_State::NumLanded, Airport_State::OnTheGround, Airport_State::RunwayFree, tw_event_data(), tw_event_new(), tw_event_send(), and tw_rand_exponential().
void Airport_Statistics_CollectStats (Airport_State * SV, tw_lp * lp)
Definition at line 202 of file 3-simple-airport.c.
References NumLanded, and Airport_State::NumLanded.
int main (int argc, char * argv[])
Definition at line 46 of file 3-simple-airport.c.
References AIR_LP, g_tw_gvt_interval, g_tw_ts_end, NumLanded, tw_getkp(), tw_getlp(), tw_getpe(), tw_init(), tw_kp_onpe(), tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), and tw_run().
Variable Documentation
int A = 60
Definition at line 5 of file 3-simple-airport.c.
Referenced by Airport_EventHandler(), Airport_StartUp(), and init().
tw_lptype airport_lps[]
Initial value:
= {
  {
     1 , sizeof(Airport_State),
    (init_f) Airport_StartUp,
    (event_f) Airport_EventHandler,
    (revent_f) Airport_RC_EventHandler,
    (final_f) Airport_Statistics_CollectStats,
    (statecp_f) NULL
  },
  { 0 },
}
Definition at line 34 of file 3-simple-airport.c.
int G = 45
Definition at line 7 of file 3-simple-airport.c.
Referenced by Airport_EventHandler().
int NumLanded = 0
Definition at line 9 of file 3-simple-airport.c.
Referenced by Airport_Statistics_CollectStats(), and main().
int R = 10
Definition at line 6 of file 3-simple-airport.c.
Referenced by Airport_EventHandler(), and MultModM().