ROSS: core/clock/aarch64.h File Reference
aarch64.h File Reference
Typedefs
typedef uint64_t tw_clock
Functions
static tw_clock tw_clock_read (void)
Typedef Documentation
typedef uint64_t tw_clock
Definition at line 4 of file aarch64.h.
Function Documentation
static tw_clock tw_clock_read (void) inline static
Definition at line 6 of file aarch64.h.
Referenced by event_cancel(), io_event_grab(), recv_finish(), setup_pes(), st_buffer_write(), st_collect_engine_data(), st_collect_event_data(), st_collect_model_data(), st_inst_init(), tw_clock_init(), tw_clock_now(), tw_event_free(), tw_event_rollback(), tw_event_send(), tw_eventq_push_list(), tw_gvt_step1_realtime(), tw_gvt_step2(), tw_hash_insert(), tw_hash_remove(), tw_init(), tw_init_lps(), tw_kp_rollback_event(), tw_kp_rollback_to(), tw_run(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_cancel_q(), tw_sched_event_q(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_realtime(), tw_scheduler_sequential(), tw_snapshot_delta(), and tw_snapshot_restore().