ROSS: ross/models/airport/airport.c File Reference
airport.c File Reference
#include "airport.h"
Functions
tw_peid mapping (tw_lpid gid)
void init (airport_state *s, tw_lp *lp)
void event_handler (airport_state *s, tw_bf *bf, airport_message *msg, tw_lp *lp)
void rc_event_handler (airport_state *s, tw_bf *bf, airport_message *msg, tw_lp *lp)
void final (airport_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype airport_lps []
const tw_optdef app_opt []
Function Documentation
void event_handler (airport_state * s, tw_bf * bf, airport_message * msg, tw_lp * lp)
Definition at line 43 of file airport.c.
References ARRIVAL, DEPARTURE, airport_state::furthest_flight_landing, tw_lp::gid, LAND, airport_state::landings, max, MEAN_DEPARTURE, mean_flight_time, MEAN_LAND, airport_state::planes_on_the_ground, tw_lp::rng, airport_message::saved_furthest_flight_landing, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), airport_message::type, airport_state::waiting_time, and airport_message::waiting_time.
void final (airport_state * s, tw_lp * lp)
Definition at line 154 of file airport.c.
References airport_state::landings, nlp_per_pe, wait_time_avg, and airport_state::waiting_time.
void init (airport_state * s, tw_lp * lp)
Definition at line 21 of file airport.c.
References DEPARTURE, airport_state::furthest_flight_landing, tw_lp::gid, airport_state::landings, MEAN_DEPARTURE, airport_state::planes_in_the_sky, airport_state::planes_on_the_ground, planes_per_airport, tw_lp::rng, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), airport_message::type, and airport_state::waiting_time.
int main (int argc, char ** argv, char ** env)
Definition at line 183 of file airport.c.
References g_tw_events_per_pe, g_tw_nlp, g_tw_npe, nlp_per_pe, opt_mem, planes_per_airport, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_lp_settype(), tw_nnodes(), tw_opt_add(), tw_run(), and wait_time_avg.
tw_peid mapping (tw_lpid gid)
Definition at line 15 of file airport.c.
References g_tw_nlp.
void rc_event_handler (airport_state * s, tw_bf * bf, airport_message * msg, tw_lp * lp)
Definition at line 134 of file airport.c.
References ARRIVAL, DEPARTURE, airport_state::furthest_flight_landing, LAND, airport_state::landings, tw_lp::rng, airport_message::saved_furthest_flight_landing, tw_rand_reverse_unif, airport_message::type, airport_state::waiting_time, and airport_message::waiting_time.
Variable Documentation
tw_lptype airport_lps[]
Initial value:
=
{
        {
                (init_f) init,
                (event_f) event_handler,
                (revent_f) rc_event_handler,
                (final_f) final,
                (map_f) mapping,
                sizeof(airport_state),
        },
        {0},
}
Definition at line 159 of file airport.c.
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("Airport Model"),
        TWOPT_UINT("nplanes", planes_per_airport, "initial # of planes per airport(events)"),
        TWOPT_STIME("mean", mean_flight_time, "mean flight time for planes"),
        TWOPT_UINT("memory", opt_mem, "optimistic memory"),
}
Definition at line 172 of file airport.c.