ROSS: core/clock/amd64.c File Reference
core/clock/amd64.c File Reference
#include <ross.h>
Functions
const tw_optdef * tw_clock_setup (void)
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
Variables
static const tw_optdef clock_opts []
Function Documentation
void tw_clock_init (tw_pe * me)
Definition at line 29 of file amd64.c.
Referenced by tw_sched_init().
tw_clock tw_clock_now (tw_pe * me)
Definition at line 36 of file amd64.c.
Referenced by tw_gvt_inprogress(), and tw_gvt_step1().
const tw_optdef* tw_clock_setup (void)
Definition at line 21 of file amd64.c.
Referenced by tw_init().
Variable Documentation
const tw_optdef clock_opts[] [static]
Initial value:
{
        TWOPT_GROUP("ROSS Timing"),
        TWOPT_STIME("clock-rate", g_tw_clock_rate, "CPU Clock Rate"),
}
Definition at line 14 of file amd64.c.
Referenced by tw_clock_setup().