ROSS: core/instrumentation/ross-lps/analysis-lp.c File Reference
analysis-lp.c File Reference
#include "ross.h"
#include "analysis-lp.h"
#include <math.h>
#include <limits.h>
Functions
static void st_create_sample_event (tw_lp *lp)
void analysis_init (analysis_state *s, tw_lp *lp)
void analysis_event (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_event_rc (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_commit (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_finish (analysis_state *s, tw_lp *lp)
tw_peid analysis_map (tw_lpid gid)
void st_analysis_lp_settype (tw_lpid lpid)
Variables
tw_lptype analysis_lp []
Function Documentation
analysis_commit()
void analysis_commit (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 199 of file analysis-lp.c.
References ALL_STATS, ANALYSIS_LP, lp_metadata::flag, g_st_disable_out, g_st_model_stats, g_tw_synchronization_protocol, tw_lp::gid, tw_kp::id, tw_pe::id, tw_lp::kp, lp_metadata::kpid, model_sample_data::lp_data, analysis_state::lp_list, lp_metadata::lpid, analysis_state::model_samples_head, analysis_state::model_samples_tail, MODEL_TYPE, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, lp_metadata::peid, model_sample_data::prev, st_model_types::sample_struct_sz, lp_metadata::sample_sz, seq_analysis, SEQUENTIAL, st_buffer_push(), analysis_msg::timestamp, model_sample_data::timestamp, lp_metadata::ts, tw_getlocal_lp(), TW_STIME_CMP, TW_STIME_CRT, and VT_STATS.
analysis_event()
void analysis_event (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 94 of file analysis-lp.c.
References ALL_STATS, ANALYSIS_LP, tw_lp::cur_state, g_st_engine_stats, g_st_model_stats, g_tw_synchronization_protocol, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::model_samples_current, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, tw_statistics::s_alp_nevent_processed, st_model_types::sample_event_fn, st_model_types::sample_struct_sz, SEQUENTIAL, st_collect_engine_data(), st_create_sample_event(), tw_pe::stats, analysis_msg::timestamp, model_sample_data::timestamp, tw_getlocal_lp(), tw_now(), and VT_STATS.
analysis_event_rc()
void analysis_event_rc (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 146 of file analysis-lp.c.
References ALL_STATS, tw_lp::cur_state, g_st_model_stats, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::model_samples_current, analysis_state::model_samples_head, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, model_sample_data::prev, tw_statistics::s_alp_e_rbs, st_model_types::sample_revent_fn, st_model_types::sample_struct_sz, tw_pe::stats, analysis_msg::timestamp, model_sample_data::timestamp, tw_getlocal_lp(), TW_STIME_CMP, TW_STIME_CRT, and VT_STATS.
analysis_finish()
void analysis_finish (analysis_state * s, tw_lp * lp)
Definition at line 258 of file analysis-lp.c.
References analysis_state::model_samples_current, and analysis_state::model_samples_head.
analysis_init()
void analysis_init (analysis_state * s, tw_lp * lp)
Definition at line 13 of file analysis-lp.c.
References ALL_STATS, analysis_state::analysis_id, analysis_start_gid, g_st_model_stats, g_st_sample_count, g_tw_lp, g_tw_nkp, g_tw_nlp, tw_lp::gid, tw_kp::id, tw_lp::kp, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::lp_list_sim, analysis_state::model_samples_current, analysis_state::model_samples_head, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, analysis_state::num_lps_sim, model_sample_data::prev, st_model_types::sample_struct_sz, st_create_sample_event(), tw_calloc(), tw_error(), tw_getlocal_lp(), TW_LOC, and VT_STATS.
analysis_map()
tw_peid analysis_map (tw_lpid gid)
Definition at line 282 of file analysis-lp.c.
References analysis_start_gid, and g_tw_nkp.
st_analysis_lp_settype()
void st_analysis_lp_settype (tw_lpid lpid)
Definition at line 300 of file analysis-lp.c.
References analysis_lp, and tw_lp_settype().
Referenced by specialized_lp_init_mapping().
st_create_sample_event()
void st_create_sample_event (tw_lp * lp) static
Definition at line 267 of file analysis-lp.c.
References g_st_sampling_end, g_st_vt_interval, tw_lp::gid, analysis_msg::src, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), TW_STIME_CRT, and TW_STIME_DBL.
Referenced by analysis_event(), and analysis_init().
Variable Documentation
analysis_lp
tw_lptype analysis_lp[]
Initial value:
= {
        {(init_f) analysis_init,
     (pre_run_f) NULL,
         (event_f) analysis_event,
         (revent_f) analysis_event_rc,
         (commit_f) analysis_commit,
         (final_f) analysis_finish,
         (map_f) analysis_map,
        sizeof(analysis_state)},
        {0},
}
Definition at line 288 of file analysis-lp.c.
Referenced by st_analysis_lp_settype().