ROSS: ross/avl_tree.h File Reference
avl_tree.h File Reference
#include <ross.h>
Data Structures
struct avlNode
Macros
#define AVL_EMPTY (0)
Typedefs
typedef struct avlNode * AvlTree
Functions
void avlDestroy (AvlTree t)
int avlGetHeight (AvlTree t)
int avlSearch (AvlTree t, tw_event *key)
void avlInsert (AvlTree *t, tw_event *key)
void avlSanityCheck (AvlTree t)
void avlPrintKeys (AvlTree t)
tw_event * avlDeleteMin (AvlTree *t)
tw_event * avlDelete (AvlTree *t, tw_event *key)
AvlTree avl_alloc (void)
void avl_free (AvlTree t)
Macro Definition Documentation
#define AVL_EMPTY (0)
Definition at line 18 of file avl_tree.h.
Referenced by avl_free(), avlDelete(), avlDeleteMin(), avlDestroy(), avlFixHeight(), avlGetHeight(), avlInsert(), avlPrintKeys(), avlRebalance(), avlSanityCheck(), avlSearch(), and tw_hash_create().
Typedef Documentation
typedef struct avlNode* AvlTree
Definition at line 7 of file avl_tree.h.
Function Documentation
AvlTree avl_alloc (void)
Definition at line 307 of file avl_tree.c.
References avl_list_head, avlNode::next, tw_error(), and TW_LOC.
Referenced by avlInsert().
void avl_free (AvlTree t)
Definition at line 321 of file avl_tree.c.
References AVL_EMPTY.
Referenced by avlDelete(), avlDeleteMin(), and avlDestroy().
tw_event* avlDelete (AvlTree * t, tw_event * key)
Definition at line 255 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDelete(), avlDeleteMin(), avlRebalance(), avlNode::child, tw_event::event_id, tw_event::recv_ts, tw_event::send_pe, tw_error(), and TW_LOC.
Referenced by avlDelete(), and tw_hash_remove().
tw_event* avlDeleteMin (AvlTree * t)
Definition at line 230 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDeleteMin(), avlRebalance(), avlNode::child, and avlNode::key.
Referenced by avlDelete(), and avlDeleteMin().
void avlDestroy (AvlTree t)
Definition at line 15 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDestroy(), and avlNode::child.
Referenced by avlDestroy().
int avlGetHeight (AvlTree t)
Definition at line 28 of file avl_tree.c.
References AVL_EMPTY, and avlNode::height.
Referenced by avlFixHeight(), avlRebalance(), and avlSanityCheck().
void avlInsert (AvlTree * t, tw_event * key)
Definition at line 165 of file avl_tree.c.
References avl_alloc(), AVL_EMPTY, avlInsert(), avlRebalance(), tw_event::event_id, tw_event::recv_ts, tw_event::send_pe, tw_error(), and TW_LOC.
Referenced by avlInsert(), and tw_hash_insert().
void avlPrintKeys (AvlTree t)
Definition at line 218 of file avl_tree.c.
References AVL_EMPTY, avlPrintKeys(), and avlNode::child.
Referenced by avlPrintKeys().
void avlSanityCheck (AvlTree t)
Definition at line 74 of file avl_tree.c.
References AVL_EMPTY, avlGetHeight(), avlSanityCheck(), avlNode::child, avlNode::height, and Max.
Referenced by avlSanityCheck().
int avlSearch (AvlTree t, tw_event * key)
Definition at line 40 of file avl_tree.c.
References AVL_EMPTY, avlSearch(), avlNode::child, tw_event::event_id, avlNode::key, tw_event::recv_ts, and tw_event::send_pe.
Referenced by avlSearch().