ROSS: core/clock/bgl.c File Reference
bgl.c File Reference
#include <ross.h>
Functions
const tw_optdef * tw_clock_setup (void)
tw_clock tw_clock_read (void)
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
Variables
static const tw_optdef clock_opts []
Function Documentation
void tw_clock_init (tw_pe * me)
Definition at line 40 of file bgl.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
tw_clock tw_clock_now (tw_pe * me)
Definition at line 47 of file bgl.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
tw_clock tw_clock_read (void)
Definition at line 16 of file bgl.c.
Referenced by tw_clock_init(), and tw_clock_now().
const tw_optdef* tw_clock_setup (void)
Definition at line 10 of file bgl.c.
References clock_opts.
Variable Documentation
const tw_optdef clock_opts[] static
Initial value:
=
{
        TWOPT_GROUP("ROSS Timing"),
        TWOPT_ULONGLONG("clock-rate", g_tw_clock_rate, "CPU Clock Rate"),
}
Definition at line 3 of file bgl.c.
Referenced by tw_clock_setup().