ROSS: rnf/modules/network/bgp4/bgp-timer.c File Reference
bgp-timer.c File Reference
#include <bgp.h>
Functions
tw_event * bgp_timer_cancel (tw_event *tmr, tw_lp *lp)
tw_event * bgp_timer_start (bgp_nbr *nbr, tw_event *tmr, tw_stime ts, int type, tw_lp *lp)
Function Documentation
tw_event* bgp_timer_cancel (tw_event * tmr, tw_lp * lp)
Definition at line 4 of file bgp-timer.c.
References g_ospf_fd, tw_event::recv_ts, rn_timer_cancel(), tw_memory_free(), and tw_now().
tw_event* bgp_timer_start (bgp_nbr * nbr, tw_event * tmr, tw_stime ts, int type, tw_lp * lp)
Definition at line 29 of file bgp-timer.c.
References ospf_message::data, g_ospf_fd, tw_event::recv_ts, rn_timer_init(), rn_timer_reset(), tw_memory_alloc(), tw_now(), and ospf_message::type.