ROSS: rnf/modules/network/bgp4/bgp-main.c File Reference
bgp-main.c File Reference
#include <bgp.h>
Functions
void bgp_md_opts ()
void bgp_setup_options (int argc, char **argv)
void bgp_setup_ases ()
void bgp_main (int argc, char **argv, char **env)
void bgp_md_final ()
Function Documentation
void bgp_main (int argc, char ** argv, char ** env)
Definition at line 153 of file bgp-main.c.
References bgp_setup_ases(), bgp_setup_options(), g_bgp_fd, g_bgp_fd_asp, g_bgp_fd_rtes, g_bgp_rt_fd, g_rn_tools_dir, g_tw_nlp, tw_error(), TW_LOC, and tw_memory_init().
void bgp_md_final ()
Definition at line 207 of file bgp-main.c.
References bgp_stats::d_opens, g_bgp_as, g_bgp_rt_fd, g_bgp_stats, g_rn_nas, bgp_stats::s_cause_bgp, bgp_stats::s_cause_ospf, bgp_stats::s_nconnects, bgp_stats::s_nconnects_dropped, bgp_stats::s_ndec_aspath, bgp_stats::s_ndec_default, bgp_stats::s_ndec_existing, bgp_stats::s_ndec_hot_potato, bgp_stats::s_ndec_local_pref, bgp_stats::s_ndec_med, bgp_stats::s_ndec_next_hop, bgp_stats::s_ndec_origin, bgp_stats::s_nebgp_nbrs, bgp_stats::s_nebgp_nbrs_up, bgp_stats::s_nibgp_nbrs, bgp_stats::s_nibgp_nbrs_up, bgp_stats::s_nkeepalives, bgp_stats::s_nkeepalivetimers, bgp_stats::s_nmrai_timers, bgp_stats::s_nnotify_recv, bgp_stats::s_nnotify_sent, bgp_stats::s_nopens, bgp_stats::s_nroute_adds, bgp_stats::s_nroute_removes, bgp_stats::s_nunreachable, bgp_stats::s_nupdates_recv, and bgp_stats::s_nupdates_sent.
void bgp_md_opts ()
Definition at line 4 of file bgp-main.c.
void bgp_setup_ases ()
Definition at line 115 of file bgp-main.c.
References ctxt, g_bgp_as, g_bgp_ases, g_bgp_state, g_rn_nas, bgp_state::hold_interval, rn_as::hold_interval, rn_as::id, bgp_state::keepalive_interval, rn_as::keepalive_interval, bgp_as::local_pref, bgp_as::med, bgp_state::mrai_interval, rn_as::mrai_interval, bgp_as::path_padding, rn_nextas(), tw_error(), TW_LOC, and xpath().
Referenced by bgp_main().
void bgp_setup_options (int argc, char ** argv)
Definition at line 13 of file bgp-main.c.
References bgp_state::as_path, bgp_state::b, bgp_state::existing, g_bgp_as, g_bgp_init_file, g_bgp_state, g_rn_nas, bgp_state::hold_interval, bgp_state::hot_potato, bgp_state::keepalive_interval, bgp_state::local_pref, bgp_state::med, bgp_state::mrai_interval, bgp_state::next_hop, bgp_state::origin, tw_error(), and TW_LOC.
Referenced by bgp_main().