ROSS: rnf/modules/network/bgp4/bgp-ospf.c File Reference
bgp-ospf.c File Reference
#include <bgp.h>
#include <ospf.h>
Functions
int bgp_lsa_find (bgp_state *, ospf_state *state, bgp_route *, int id, tw_lp *lp)
void bgp_lsa_link_allocate (bgp_state *, ospf_state *, ospf_lsa *, int, tw_lp *)
void bgp_ospf_init (bgp_state *bs, bgp_route *r, tw_lp *lp)
void bgp_ospf_update (bgp_state *bs, rn_as *dest_as, bgp_route *r, int add, tw_lp *lp)
void bgp_ospf_flush (bgp_state *bs, rn_as *dest_as, bgp_route *r, int add, tw_lp *lp)
Function Documentation
int bgp_lsa_find (bgp_state * bstate, ospf_state * state, bgp_route * r, int id, tw_lp * lp)
Definition at line 203 of file bgp-ospf.c.
References ospf_lsa::adv_r, ospf_state::ar, bgp_state::as, rn_area::as, rn_link::cost, ospf_lsa_link::dst, g_ospf_ll_fd, rn_area::g_ospf_lsa, ospf_lsa::id, tw_lp::id, rn_machine::link, ospf_lsa::links, ospf_state::m, ospf_lsa_link::metric, rn_as::nareas, ospf_lsa::next, rn_area::nmachines, ospf_lsa_allocate(), ospf_lsa_as_ext, rn_getas(), rn_getlink(), rn_getmachine(), rn_route(), bgp_route::src, tw_error(), TW_LOC, tw_memory_alloc(), tw_memoryq_push(), and ospf_lsa::type.
Referenced by bgp_ospf_init(), and bgp_ospf_update().
void bgp_lsa_link_allocate (bgp_state * bstate, ospf_state * state, ospf_lsa * lsa, int x_id, tw_lp * lp)
Definition at line 296 of file bgp-ospf.c.
References rn_link::cost, ospf_lsa_link::dst, g_ospf_ll_fd, bgp_nbr::id, rn_as::id, ospf_lsa::length, rn_machine::link, ospf_lsa::links, ospf_state::m, ospf_lsa_link::metric, bgp_state::n_interfaces, bgp_state::nbr, OSPF_LSA_LINK_LENGTH, OSPF_LSA_UPDATE_HEADER, rn_getas(), rn_getmachine(), tw_memory_alloc(), and tw_memoryq_push().
void bgp_ospf_flush (bgp_state * bs, rn_as * dest_as, bgp_route * r, int add, tw_lp * lp)
Definition at line 330 of file bgp-ospf.c.
References tw_error(), and TW_LOC.
void bgp_ospf_init (bgp_state * bs, bgp_route * r, tw_lp * lp)
Definition at line 8 of file bgp-ospf.c.
References ospf_db_entry::age, rn_area::as, ospf_db_entry::b, bgp_lsa_find(), tw_lp::cur_state, ospf_state::db, bgp_route::dst, ospf_db_entry::entry, ospf_db_entry::free, tw_lp::id, rn_stream::layers, bgp_state::log, rn_layer::lp, ospf_db_entry::lsa, rn_as::nareas, rn_area::nmachines, ospf_db_remove(), ospf_db_route(), OSPF_MIN_LSA_SEQNUM, rn_stream::port, rn_getarea(), rn_getmachine(), rn_getstream_byport(), s, and ospf_db_entry::seqnum.
void bgp_ospf_update (bgp_state * bs, rn_as * dest_as, bgp_route * r, int add, tw_lp * lp)
Definition at line 70 of file bgp-ospf.c.
References ospf_lsa::adv_r, ospf_db_entry::age, rn_area::as, ospf_db_entry::b, bgp_lsa_find(), ospf_db_entry::cause_bgp, rn_lp_state::cur_lp, tw_lp::cur_state, rn_lp_state::cur_stream, ospf_state::db, ospf_lsa_link::dst, ospf_db_entry::free, getlsa(), ospf_nbr::id, rn_as::id, tw_lp::id, rn_stream::layers, ospf_lsa::links, bgp_state::log, rn_layer::lp, ospf_db_entry::lsa, ospf_state::lsa_seqnum, ospf_state::m, rn_as::nareas, rn_area::nmachines, ospf_lsa_create(), OSPF_LSA_MAX_AGE, ospf_nbr_full_st, rn_stream::port, rn_getarea(), rn_getmachine(), rn_getstream_byport(), s, ospf_statistics::s_cause_bgp, ospf_db_entry::seqnum, bgp_route::src, ospf_nbr::state, and ospf_state::stats.
Referenced by deal_with_timed_out_routers(), update_add(), and update_withdraw().