ROSS: rnf/modules/network/bgp4/bgp-stats.c File Reference
bgp-stats.c File Reference
#include <bgp.h>
Functions
void bgp_final (bgp_state *state, tw_lp *lp)
Function Documentation
void bgp_final (bgp_state * state, tw_lp * lp)
Definition at line 4 of file bgp-stats.c.
References bgp_state::as, bgp_rib_print(), bgp_route_print(), bgp_stats::d_opens, g_bgp_rt_fd, g_bgp_stats, g_rn_converge_ospf, g_rn_logs_dir, g_rn_nas, bgp_nbr::id, tw_lp::id, bgp_state::log, bgp_state::n_interfaces, bgp_state::nbr, bgp_state::rib, rn_getas(), rn_getmachine(), bgp_stats::s_cause_bgp, bgp_stats::s_cause_ospf, bgp_stats::s_nconnects, bgp_stats::s_nconnects_dropped, bgp_stats::s_nebgp_nbrs, bgp_stats::s_nebgp_nbrs_up, bgp_stats::s_nibgp_nbrs, bgp_stats::s_nibgp_nbrs_up, bgp_stats::s_nkeepalives, bgp_stats::s_nkeepalivetimers, bgp_stats::s_nmrai_timers, bgp_stats::s_nnotify_recv, bgp_stats::s_nnotify_sent, bgp_stats::s_nopens, bgp_stats::s_nroute_adds, bgp_stats::s_nroute_removes, bgp_stats::s_nunreachable, bgp_stats::s_nupdates_recv, bgp_stats::s_nupdates_sent, bgp_state::stats, tw_error(), TW_FALSE, TW_LOC, and bgp_nbr::up.