ROSS: rnf/modules/network/bgp4/bgp-update.c File Reference
bgp-update.c File Reference
#include <bgp.h>
Functions
void update_add (bgp_state *, tw_bf *, tw_memory *, bgp_message *, int, tw_lp *)
void update_withdraw (bgp_state *, tw_bf *, bgp_route *, bgp_message *, int, tw_lp *)
void bgp_update_send (bgp_state *state, bgp_nbr *n, bgp_route *r_send, bgp_message *msg, int cause, tw_lp *lp)
void bgp_update (bgp_state *state, tw_bf *bf, bgp_message *msg, int src, tw_lp *lp)
void bgp_update_all (bgp_state *state, bgp_message *msg, int src, bgp_route *r, tw_lp *lp)
Function Documentation
void bgp_update (bgp_state * state, tw_bf * bf, bgp_message * msg, int src, tw_lp * lp)
Definition at line 81 of file bgp-update.c.
References bgp_message::b, bgp_getnbr(), bgp_route_free(), bgp_update_send(), bgp_message::cause_ospf, bgp_route::dst, bgp_state::log, bgp_route::next_hop, bgp_state::rib, bgp_stats::s_nunreachable, bgp_route::src, bgp_state::stats, tw_error(), TW_LOC, bgp_message::unreachable, bgp_message::update, update_add(), and update_withdraw().
Referenced by bgp_event_handler().
void bgp_update_all (bgp_state * state, bgp_message * msg, int src, bgp_route * r, tw_lp * lp)
Definition at line 264 of file bgp-update.c.
References bgp_state::as, bgp_message::b, bgp_update_send(), bgp_message::cause_bgp, bgp_message::cause_ospf, bgp_route::dst, bgp_nbr::id, rn_as::id, bgp_state::nbr, rn_getas(), rn_getmachine(), bgp_route::src, tw_error(), TW_FALSE, TW_LOC, and bgp_nbr::up.
Referenced by bgp_mrai_timer(), update_add(), and update_withdraw().
void bgp_update_send (bgp_state * state, bgp_nbr * n, bgp_route * r_send, bgp_message * msg, int cause, tw_lp * lp)
Definition at line 7 of file bgp-update.c.
References tw_pe::abort_event, bgp_state::as, bgp_message::b, bgp_route_copy(), bgp_route_equals(), bgp_route_print(), BGP_UPDATE, bgp_message::cause_bgp, bgp_message::cause_ospf, DOWNSTREAM, bgp_route::dst, g_bgp_fd, g_bgp_fd_rtes, g_bgp_stats, bgp_nbr::id, bgp_state::log, tw_event::owner, tw_lp::pe, REMOVE, bgp_state::rib, rn_event_new(), rn_event_send(), rn_getas(), rn_getmachine(), bgp_stats::s_cause_bgp, bgp_stats::s_nupdates_sent, tw_event::state, bgp_state::stats, tw_error(), TW_FALSE, TW_LOC, tw_memory_alloc(), tw_now(), TW_pe_free_q, bgp_message::type, bgp_message::unreachable, UPDATE, and bgp_message::update.
Referenced by bgp_open(), bgp_update(), bgp_update_all(), and deal_with_timed_out_routers().
void update_add (bgp_state * state, tw_bf * bf, tw_memory * b_in, bgp_message * msg, int src, tw_lp * lp)
Definition at line 135 of file bgp-update.c.
References bgp_state::as, bgp_message::b, bgp_decision(), bgp_getroute(), bgp_ospf_update(), bgp_route_add(), bgp_route_aspath_print(), bgp_route_free(), bgp_route_inpath(), bgp_route_withdraw(), bgp_update_all(), tw_bf::c3, tw_bf::c4, bgp_route::dst, g_rn_as, rn_as::id, tw_lp::id, bgp_state::log, bgp_state::m, bgp_route::next_hop, rn_getas(), rn_getlink(), rn_getmachine(), rn_route(), bgp_route::src, tw_error(), TW_FALSE, TW_LOC, TW_TRUE, and bgp_message::update.
Referenced by bgp_update().
void update_withdraw (bgp_state * state, tw_bf * bf, bgp_route * r_in, bgp_message * msg, int src, tw_lp * lp)
Definition at line 229 of file bgp-update.c.
References bgp_state::as, bgp_getroute(), bgp_ospf_update(), bgp_route_equals(), bgp_route_free(), bgp_route_print(), bgp_route_withdraw(), bgp_update_all(), tw_bf::c5, bgp_route::dst, g_rn_as, bgp_state::log, rn_getas(), rn_getmachine(), TW_FALSE, and TW_TRUE.
Referenced by bgp_update().