ROSS: build/bin/include/instrumentation/ross-lps/analysis-lp.h File Reference
analysis-lp.h File Reference
#include "ross-types.h"
Data Structures
struct analysis_msg
struct lp_metadata
struct model_sample_data
struct analysis_state
Typedefs
typedef struct analysis_state analysis_state
typedef struct analysis_msg analysis_msg
typedef struct model_sample_data model_sample_data
typedef struct lp_metadata lp_metadata
Enumerations
enum analysis_type_flag {
ALP_NONE , ALP_FULL , ALP_KP , ALP_PE ,
ALP_MODEL
}
Functions
void analysis_init (analysis_state *s, tw_lp *lp)
void analysis_event (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_event_rc (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_commit (analysis_state *s, tw_bf *bf, analysis_msg *m, tw_lp *lp)
void analysis_finish (analysis_state *s, tw_lp *lp)
void collect_sim_engine_data (tw_pe *pe, tw_lp *lp, analysis_state *s, tw_stime current_rt)
tw_peid analysis_map (tw_lpid gid)
void st_analysis_lp_settype (tw_lpid lpid)
Variables
tw_lpid analysis_start_gid
Typedef Documentation
analysis_msg
typedef struct analysis_msg analysis_msg
Definition at line 7 of file analysis-lp.h.
analysis_state
typedef struct analysis_state analysis_state
Definition at line 6 of file analysis-lp.h.
lp_metadata
typedef struct lp_metadata lp_metadata
Definition at line 9 of file analysis-lp.h.
model_sample_data
typedef struct model_sample_data model_sample_data
Definition at line 8 of file analysis-lp.h.
Enumeration Type Documentation
analysis_type_flag
enum analysis_type_flag
Enumerator
ALP_NONE
ALP_FULL
ALP_KP
ALP_PE
ALP_MODEL
Definition at line 11 of file analysis-lp.h.
Function Documentation
analysis_commit()
void analysis_commit (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 199 of file analysis-lp.c.
References ALL_STATS, ANALYSIS_LP, lp_metadata::flag, g_st_disable_out, g_st_model_stats, g_tw_synchronization_protocol, tw_lp::gid, tw_kp::id, tw_pe::id, tw_lp::kp, lp_metadata::kpid, model_sample_data::lp_data, analysis_state::lp_list, lp_metadata::lpid, analysis_state::model_samples_head, analysis_state::model_samples_tail, MODEL_TYPE, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, lp_metadata::peid, model_sample_data::prev, st_model_types::sample_struct_sz, lp_metadata::sample_sz, seq_analysis, SEQUENTIAL, st_buffer_push(), analysis_msg::timestamp, model_sample_data::timestamp, lp_metadata::ts, tw_getlocal_lp(), TW_STIME_CMP, TW_STIME_CRT, and VT_STATS.
analysis_event()
void analysis_event (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 94 of file analysis-lp.c.
References ALL_STATS, ANALYSIS_LP, tw_lp::cur_state, g_st_engine_stats, g_st_model_stats, g_tw_synchronization_protocol, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::model_samples_current, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, tw_statistics::s_alp_nevent_processed, st_model_types::sample_event_fn, st_model_types::sample_struct_sz, SEQUENTIAL, st_collect_engine_data(), st_create_sample_event(), tw_pe::stats, analysis_msg::timestamp, model_sample_data::timestamp, tw_getlocal_lp(), tw_now(), and VT_STATS.
analysis_event_rc()
void analysis_event_rc (analysis_state * s, tw_bf * bf, analysis_msg * m, tw_lp * lp)
Definition at line 146 of file analysis-lp.c.
References ALL_STATS, tw_lp::cur_state, g_st_model_stats, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::model_samples_current, analysis_state::model_samples_head, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, tw_lp::pe, model_sample_data::prev, tw_statistics::s_alp_e_rbs, st_model_types::sample_revent_fn, st_model_types::sample_struct_sz, tw_pe::stats, analysis_msg::timestamp, model_sample_data::timestamp, tw_getlocal_lp(), TW_STIME_CMP, TW_STIME_CRT, and VT_STATS.
analysis_finish()
void analysis_finish (analysis_state * s, tw_lp * lp)
Definition at line 258 of file analysis-lp.c.
References analysis_state::model_samples_current, and analysis_state::model_samples_head.
analysis_init()
void analysis_init (analysis_state * s, tw_lp * lp)
Definition at line 13 of file analysis-lp.c.
References ALL_STATS, analysis_state::analysis_id, analysis_start_gid, g_st_model_stats, g_st_sample_count, g_tw_lp, g_tw_nkp, g_tw_nlp, tw_lp::gid, tw_kp::id, tw_lp::kp, model_sample_data::lp_data, analysis_state::lp_list, analysis_state::lp_list_sim, analysis_state::model_samples_current, analysis_state::model_samples_head, analysis_state::model_samples_tail, tw_lp::model_types, model_sample_data::next, analysis_state::num_lps, analysis_state::num_lps_sim, model_sample_data::prev, st_model_types::sample_struct_sz, st_create_sample_event(), tw_calloc(), tw_error(), tw_getlocal_lp(), TW_LOC, and VT_STATS.
analysis_map()
tw_peid analysis_map (tw_lpid gid)
Definition at line 282 of file analysis-lp.c.
References analysis_start_gid, and g_tw_nkp.
collect_sim_engine_data()
void collect_sim_engine_data (tw_pe * pe, tw_lp * lp, analysis_state * s, tw_stime current_rt)
References analysis_start_gid, and pe.
st_analysis_lp_settype()
void st_analysis_lp_settype (tw_lpid lpid)
Definition at line 300 of file analysis-lp.c.
References analysis_lp, and tw_lp_settype().
Referenced by specialized_lp_init_mapping().
Variable Documentation
analysis_start_gid
tw_lpid analysis_start_gid extern
Definition at line 15 of file specialized-lps.c.
Referenced by analysis_init(), analysis_map(), collect_sim_engine_data(), specialized_lp_init_mapping(), and specialized_lp_setup().