ROSS: build/bin/include/rio/io.h File Reference
io.h File Reference
#include "ross-types.h"
#include "tw-opts.h"
Data Structures
struct io_lptype
struct io_partition
struct io_lp_store
struct io_event_store
Typedefs
typedef enum io_load_e io_load_type
typedef void(* serialize_f) (void *state, void *buffer, tw_lp *lp)
typedef void(* deserialize_f) (void *state, void *buffer, tw_lp *lp)
typedef size_t(* model_size_f) (void *state, tw_lp *lp)
Enumerations
enum io_load_e { NONE , PRE_INIT , INIT , POST_INIT }
Functions
void io_register_model_version (char *sha1)
void io_init ()
void io_load_checkpoint (char *master_filename, io_load_type load_at)
void io_store_checkpoint (char *master_filename, int data_file_number)
void io_appending_job ()
void io_load_events (tw_pe *me)
void io_event_cancel (tw_event *e)
void io_read_checkpoint ()
size_t io_lp_serialize (tw_lp *lp, void *buffer)
size_t io_lp_deserialize (tw_lp *lp, void *buffer)
size_t io_event_serialize (tw_event *e, void *buffer)
size_t io_event_deserialize (tw_event *e, void *buffer)
tw_event * io_event_grab (tw_pe *pe)
Variables
int g_io_number_of_files
const tw_optdef io_opts [3]
io_load_type g_io_load_at
char g_io_checkpoint_name [1024]
int g_io_events_buffered_per_rank
io_lptype * g_io_lp_types
static int io_partition_field_count = 6
io_partition * g_io_partitions
tw_eventq g_io_buffered_events
tw_eventq g_io_free_events
Typedef Documentation
deserialize_f
typedef void(* deserialize_f) (void *state, void *buffer, tw_lp *lp)
Definition at line 45 of file io.h.
io_load_type
typedef enum io_load_e io_load_type
Definition at line 26 of file io.h.
model_size_f
typedef size_t(* model_size_f) (void *state, tw_lp *lp)
Definition at line 46 of file io.h.
serialize_f
typedef void(* serialize_f) (void *state, void *buffer, tw_lp *lp)
Definition at line 44 of file io.h.
Enumeration Type Documentation
io_load_e
enum io_load_e
Enumerator
NONE
PRE_INIT
INIT
POST_INIT
Definition at line 20 of file io.h.
Function Documentation
io_appending_job()
void io_appending_job ()
Definition at line 101 of file io-mpi.c.
References l_io_append_flag, and l_io_init_flag.
io_event_cancel()
void io_event_cancel (tw_event * e)
Definition at line 70 of file io-mpi.c.
References g_io_buffered_events, g_io_free_events, tw_eventq_delete_any(), and tw_eventq_push().
Referenced by event_cancel().
io_event_deserialize()
size_t io_event_deserialize (tw_event * e, void * buffer)
Definition at line 68 of file io-serialize.c.
References io_event_store::critical_path, tw_event::critical_path, CUSTOM, io_event_store::cv, tw_event::cv, io_event_store::dest_lp, tw_event::dest_lp, g_tw_custom_lp_global_to_local_map, g_tw_lp, g_tw_lp_offset, g_tw_mapping, LINEAR, io_event_store::recv_ts, tw_event::recv_ts, io_event_store::src_lp, tw_event::src_lp, tw_error(), and TW_LOC.
Referenced by io_read_checkpoint().
io_event_grab()
tw_event * io_event_grab (tw_pe * pe) extern
Definition at line 42 of file io-mpi.c.
References tw_event::cancel_next, tw_event::cause_next, tw_event::caused_by_me, tw_event::event_id, g_io_buffered_events, g_io_events_buffered_per_rank, g_io_free_events, l_io_init_flag, tw_event::next, tw_event::owner, pe, tw_event::prev, tw_event::state, tw_clock_read(), tw_eventq_pop(), and tw_eventq_push().
Referenced by tw_event_new_user_prio().
io_event_serialize()
size_t io_event_serialize (tw_event * e, void * buffer)
Definition at line 52 of file io-serialize.c.
References io_event_store::critical_path, tw_event::critical_path, io_event_store::cv, tw_event::cv, io_event_store::dest_lp, tw_event::dest_lp, g_tw_ts_end, tw_lp::gid, io_event_store::recv_ts, tw_event::recv_ts, io_event_store::src_lp, and tw_event::src_lp.
Referenced by io_store_checkpoint().
io_init()
void io_init ()
Definition at line 75 of file io-mpi.c.
References g_io_buffered_events, g_io_free_events, g_io_number_of_files, g_tw_mynode, g_tw_nkp, g_tw_nlp, l0_io_total_kp, l0_io_total_lp, l_io_init_flag, l_io_kp_offset, l_io_lp_offset, and l_io_min_parts.
io_load_checkpoint()
void io_load_checkpoint (char * master_filename, io_load_type load_at)
Definition at line 107 of file io-mpi.c.
References g_io_checkpoint_name, and g_io_load_at.
io_load_events()
void io_load_events (tw_pe * me)
Definition at line 227 of file io-mpi.c.
References tw_pe::abort_event, tw_event::caused_by_me, tw_pe::cev_abort, tw_pe::cur_event, tw_event::cv, tw_event::dest_lp, g_io_buffered_events, g_io_free_events, g_tw_lookahead, g_tw_msg_sz, tw_event::recv_ts, tw_event::src_lp, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_eventq_pop(), tw_eventq_push(), and TW_LOC.
Referenced by tw_sched_init().
io_lp_deserialize()
size_t io_lp_deserialize (tw_lp * lp, void * buffer)
Definition at line 27 of file io-serialize.c.
References tw_rng_stream::Cg, io_lp_store::critical_path, tw_lp::critical_path, g_tw_nRNG_per_lp, io_lp_store::gid, tw_lp::gid, tw_rng_stream::Ig, tw_rng_stream::Lg, io_lp_store::rng, tw_lp::rng, io_lp_store::tw_normal_flipflop, tw_rng_stream::tw_normal_flipflop, io_lp_store::tw_normal_u1, tw_rng_stream::tw_normal_u1, io_lp_store::tw_normal_u2, and tw_rng_stream::tw_normal_u2.
Referenced by io_read_checkpoint().
io_lp_serialize()
size_t io_lp_serialize (tw_lp * lp, void * buffer)
Definition at line 3 of file io-serialize.c.
References tw_rng_stream::Cg, io_lp_store::critical_path, tw_lp::critical_path, g_tw_nRNG_per_lp, io_lp_store::gid, tw_lp::gid, tw_rng_stream::Ig, tw_rng_stream::Lg, io_lp_store::rng, tw_lp::rng, io_lp_store::tw_normal_flipflop, tw_rng_stream::tw_normal_flipflop, io_lp_store::tw_normal_u1, tw_rng_stream::tw_normal_u1, io_lp_store::tw_normal_u2, and tw_rng_stream::tw_normal_u2.
Referenced by io_store_checkpoint().
io_read_checkpoint()
void io_read_checkpoint ()
Definition at line 112 of file io-mpi.c.
References g_io_buffered_events, g_io_checkpoint_name, g_io_free_events, g_io_lp_types, g_io_number_of_files, g_tw_lp, g_tw_msg_sz, g_tw_mynode, g_tw_nkp, g_tw_nlp, io_event_deserialize(), io_lp_deserialize(), io_partition_field_count, l_io_kp_offset, l_io_lp_offset, l_io_min_parts, io_partition::lp_count, io_partition::size, tw_event_data(), tw_eventq_pop(), tw_eventq_push(), and tw_nnodes().
Referenced by tw_init_lps().
io_register_model_version()
void io_register_model_version (char * sha1)
Definition at line 38 of file io-mpi.c.
References model_version.
io_store_checkpoint()
void io_store_checkpoint (char * master_filename, int data_file_number)
Definition at line 255 of file io-mpi.c.
References io_partition::ev_count, io_partition::file, g_io_buffered_events, g_io_free_events, g_io_lp_types, g_io_number_of_files, g_tw_kp, g_tw_lp, g_tw_lp_typemap, g_tw_msg_sz, g_tw_mynode, g_tw_nkp, g_tw_nlp, io_event_serialize(), io_lp_serialize(), io_partition_field_count, l0_io_total_kp, l0_io_total_lp, l_io_append_flag, l_io_kp_offset, l_io_lp_offset, l_io_min_parts, io_partition::lp_count, model_version, io_partition::offset, io_partition::part, ROSS_VERSION, io_partition::size, tw_event_data(), tw_eventq_pop(), tw_eventq_push(), tw_nnodes(), and tw_opt_settings().
Variable Documentation
g_io_buffered_events
tw_eventq g_io_buffered_events extern
Definition at line 24 of file io-mpi.c.
Referenced by io_event_cancel(), io_event_grab(), io_init(), io_load_events(), io_read_checkpoint(), and io_store_checkpoint().
g_io_checkpoint_name
char g_io_checkpoint_name[1024] extern
Definition at line 22 of file io-mpi.c.
Referenced by io_load_checkpoint(), and io_read_checkpoint().
g_io_events_buffered_per_rank
int g_io_events_buffered_per_rank extern
Definition at line 23 of file io-mpi.c.
Referenced by io_event_grab(), and setup_pes().
g_io_free_events
tw_eventq g_io_free_events extern
Definition at line 25 of file io-mpi.c.
Referenced by io_event_cancel(), io_event_grab(), io_init(), io_load_events(), io_read_checkpoint(), io_store_checkpoint(), and setup_pes().
g_io_load_at
io_load_type g_io_load_at extern
Definition at line 21 of file io-mpi.c.
Referenced by io_load_checkpoint(), and tw_init_lps().
g_io_lp_types
io_lptype* g_io_lp_types extern
Definition at line 20 of file io-mpi.c.
Referenced by io_read_checkpoint(), and io_store_checkpoint().
g_io_number_of_files
int g_io_number_of_files extern
Definition at line 11 of file io-mpi.c.
Referenced by io_init(), io_read_checkpoint(), and io_store_checkpoint().
g_io_partitions
io_partition* g_io_partitions extern
Definition at line 19 of file io-mpi.c.
io_opts
const tw_optdef io_opts[3] extern
Definition at line 12 of file io-mpi.c.
Referenced by tw_init().
io_partition_field_count
int io_partition_field_count = 6 static
Definition at line 66 of file io.h.
Referenced by io_read_checkpoint(), and io_store_checkpoint().