ROSS: build/bin/include/ross-kernel-inline.h File Reference
ross-kernel-inline.h File Reference
#include "instrumentation/st-instrumentation.h"
#include "ross-extern.h"
#include "ross-gvt-internal.h"
#include "ross-network.h"
Macros
#define ROSS_MAX(a, b)
#define ROSS_MIN(a, b)
Functions
static tw_lp * tw_getlocal_lp (tw_lpid gid)
static tw_lp * tw_getlp (tw_lpid id)
static tw_kp * tw_getkp (tw_kpid id)
static int tw_ismaster (void)
static void * tw_getstate (tw_lp *lp)
static tw_stime tw_now (tw_lp const *lp)
static tw_event_sig tw_now_sig (tw_lp const *lp)
Macro Definition Documentation
ROSS_MAX
#define ROSS_MAX (a, b)
Value:
((a) > (b) ? (a) : (b))
Definition at line 8 of file ross-kernel-inline.h.
Referenced by avlFixHeight(), avlSanityCheck(), tw_eventq_alloc(), tw_get_stats(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
ROSS_MIN
#define ROSS_MIN (a, b)
Value:
((a) < (b) ? (a) : (b))
Definition at line 9 of file ross-kernel-inline.h.
Referenced by gvt_print().
Function Documentation
tw_getkp()
tw_kp * tw_getkp (tw_kpid id) inline static
Definition at line 56 of file ross-kernel-inline.h.
References g_tw_kp, g_tw_nkp, tw_error(), and TW_LOC.
Referenced by late_sanity_check(), st_collect_engine_data(), tw_get_stats(), tw_init_kps(), and tw_pe_fossil_collect().
tw_getlocal_lp()
tw_lp * tw_getlocal_lp (tw_lpid gid) inline static
Definition at line 12 of file ross-kernel-inline.h.
References CUSTOM, g_st_total_model_lps, g_st_use_analysis_lps, g_tw_custom_lp_global_to_local_map, g_tw_lp, g_tw_lp_offset, g_tw_mapping, g_tw_nkp, g_tw_nlp, LINEAR, ROUND_ROBIN, tw_error(), TW_LOC, and tw_nnodes().
Referenced by analysis_commit(), analysis_event(), analysis_event_rc(), analysis_init(), recv_finish(), and tw_event_send().
tw_getlp()
tw_lp * tw_getlp (tw_lpid id) inline static
Definition at line 44 of file ross-kernel-inline.h.
References g_st_analysis_nlp, g_tw_lp, g_tw_nlp, tw_error(), and TW_LOC.
Referenced by st_collect_engine_data(), tw_all_lp_stats(), and tw_stats().
tw_getstate()
void * tw_getstate (tw_lp * lp) inline static
Definition at line 77 of file ross-kernel-inline.h.
References tw_lp::cur_state.
tw_ismaster()
int tw_ismaster (void) inline static
Definition at line 71 of file ross-kernel-inline.h.
References g_tw_masternode, and g_tw_mynode.
Referenced by apply_opt(), match_opt(), need_argument(), tw_end(), tw_init(), tw_opt_print(), and tw_stats().
tw_now()
tw_stime tw_now (tw_lp const * lp) inline static
Definition at line 84 of file ross-kernel-inline.h.
References tw_lp::kp, tw_kp::last_sig, and tw_event_sig::recv_ts.
Referenced by analysis_event(), st_buffer_push(), st_collect_model_data(), st_create_sample_event(), tw_event_new_user_prio(), tw_event_send(), and tw_lp_suspend().
tw_now_sig()
tw_event_sig tw_now_sig (tw_lp const * lp) inline static
Definition at line 90 of file ross-kernel-inline.h.
References tw_lp::kp, and tw_kp::last_sig.
Referenced by tw_lp_suspend().