ROSS: build/bin/include/ross-gvt-internal.h File Reference
ross-gvt-internal.h File Reference
#include "ross-types.h"
#include "tw-opts.h"
#include "stdbool.h"
Data Structures
struct gvt_hook_trigger
Enumerations
enum GVT_HOOK_STATUS { GVT_HOOK_STATUS_disabled = 0 , GVT_HOOK_STATUS_timestamp , GVT_HOOK_STATUS_every_n_gvt }
Functions
const tw_optdef * tw_gvt_setup (void)
void tw_gvt_start (void)
void tw_gvt_finish (void)
void tw_gvt_step1 (tw_pe *)
void tw_gvt_step1_realtime (tw_pe *)
void tw_gvt_step2 (tw_pe *)
void tw_gvt_force_update (void)
void tw_gvt_force_update_realtime (void)
int tw_gvt_set (tw_pe *pe, tw_stime LVT)
static int tw_gvt_inprogress (tw_pe *pe)
void tw_gvt_stats (FILE *F)
void tw_trigger_gvt_hook_at (tw_stime time)
void tw_trigger_gvt_hook_at_event_sig (tw_event_sig time)
void tw_trigger_gvt_hook_every (int num_gvt_calls)
Variables
void(* g_tw_gvt_hook)(tw_pe *pe, bool is_queue_empty)
struct gvt_hook_trigger g_tw_gvt_hook_trigger
Enumeration Type Documentation
GVT_HOOK_STATUS
enum GVT_HOOK_STATUS
Enumerator
GVT_HOOK_STATUS_disabled
GVT_HOOK_STATUS_timestamp
GVT_HOOK_STATUS_every_n_gvt
Definition at line 60 of file ross-gvt-internal.h.
Function Documentation
tw_gvt_finish()
void tw_gvt_finish (void) extern
Definition at line 89 of file mpi_allreduce.c.
Referenced by tw_end().
tw_gvt_force_update()
void tw_gvt_force_update (void) extern
Definition at line 98 of file mpi_allreduce.c.
References g_tw_gvt_interval, gvt_cnt, and gvt_force.
Referenced by tw_sched_batch(), and tw_scheduler_conservative().
tw_gvt_force_update_realtime()
void tw_gvt_force_update_realtime (void) extern
Definition at line 105 of file mpi_allreduce.c.
References g_tw_gvt_interval_start_cycles, and gvt_force.
Referenced by tw_sched_batch_realtime().
tw_gvt_inprogress()
int tw_gvt_inprogress (tw_pe * pe) inline static
References g_tw_gvt_hook, and pe.
tw_gvt_set()
int tw_gvt_set (tw_pe * pe, tw_stime LVT) extern
References pe.
tw_gvt_setup()
const tw_optdef * tw_gvt_setup (void) extern
Definition at line 61 of file mpi_allreduce.c.
References gvt_cnt, and gvt_opts.
Referenced by tw_init().
tw_gvt_start()
void tw_gvt_start (void) extern
Definition at line 69 of file mpi_allreduce.c.
References tw_event_sig::event_tiebreaker, tw_event_sig::priority, tw_event_sig::recv_ts, and tw_event_sig::tie_lineage_length.
Referenced by tw_init().
tw_gvt_stats()
void tw_gvt_stats (FILE * F) extern
Definition at line 112 of file mpi_allreduce.c.
References all_reduce_cnt, g_tw_clock_rate, g_tw_gvt_done, g_tw_gvt_interval, g_tw_gvt_realtime_interval, g_tw_mblock, and gvt_force.
Referenced by tw_stats().
tw_gvt_step1()
void tw_gvt_step1 (tw_pe * me) extern
Definition at line 141 of file mpi_allreduce.c.
References g_tw_gvt_interval, gvt_cnt, tw_pe::gvt_status, NOT_PAST_LOOKAHEAD, PAST_GVT_HOOK_ACTIVATION, and TW_GVT_COMPUTE.
Referenced by tw_scheduler_conservative(), and tw_scheduler_optimistic().
tw_gvt_step1_realtime()
void tw_gvt_step1_realtime (tw_pe * me) extern
Definition at line 156 of file mpi_allreduce.c.
References g_tw_gvt_interval_start_cycles, g_tw_gvt_realtime_interval, tw_pe::gvt_status, NOT_PAST_LOOKAHEAD, PAST_GVT_HOOK_ACTIVATION, tw_clock_read(), and TW_GVT_COMPUTE.
Referenced by tw_scheduler_optimistic_realtime().
tw_gvt_step2()
void tw_gvt_step2 (tw_pe * me) extern
Definition at line 325 of file mpi_allreduce.c.
References all_reduce_cnt, ALL_STATS, g_st_engine_stats, g_st_model_stats, g_st_num_gvt, g_tw_clock_rate, g_tw_gvt_done, g_tw_gvt_interval_start_cycles, g_tw_gvt_max_no_change, g_tw_gvt_no_change, g_tw_masternode, g_tw_mynode, g_tw_synchronization_protocol, g_tw_ts_end, tw_pe::GVT, gvt_cnt, GVT_COL, tw_pe::GVT_prev, gvt_print(), GVT_STATS, tw_pe::gvt_status, tw_pe::id, MPI_COMM_ROSS, MPI_TYPE_TW_STIME, OPTIMISTIC, OPTIMISTIC_REALTIME, percent_complete, tw_pe::pq, RT_STATS, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_statistics::s_net_read, tw_pe::s_nwhite_recv, tw_pe::s_nwhite_sent, st_collect_engine_data(), st_collect_model_data(), st_inst_dump(), tw_pe::stats, tw_pe::trans_msg_ts, tw_clock_read(), tw_error(), TW_GVT_COMPUTE, TW_GVT_NORMAL, TW_LOC, tw_net_minimum(), tw_net_read(), tw_pe_fossil_collect(), tw_pq_minimum(), TW_STIME_CMP, TW_STIME_DBL, TW_STIME_MAX, and VT_STATS.
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_realtime(), and tw_scheduler_rollback_and_cancel_events_pe().
tw_trigger_gvt_hook_at()
void tw_trigger_gvt_hook_at (tw_stime time)
Definition at line 488 of file mpi_allreduce.c.
References g_tw_gvt_hook_trigger, g_tw_pe, GVT_HOOK_STATUS_timestamp, TW_LOC, and tw_warning().
Referenced by gvt_hook(), and main().
tw_trigger_gvt_hook_at_event_sig()
void tw_trigger_gvt_hook_at_event_sig (tw_event_sig time)
tw_trigger_gvt_hook_every()
void tw_trigger_gvt_hook_every (int num_gvt_calls)
Definition at line 514 of file mpi_allreduce.c.
References g_tw_gvt_done, g_tw_gvt_hook_trigger, GVT_HOOK_STATUS_every_n_gvt, tw_error(), and TW_LOC.
Referenced by main().
Variable Documentation
g_tw_gvt_hook
void(* g_tw_gvt_hook) (tw_pe *pe, bool is_queue_empty) (tw_pe * pe, bool is_queue_empty) extern
Definition at line 12 of file mpi_allreduce.c.
Referenced by main(), tw_gvt_hook_step(), tw_gvt_hook_step_seq(), tw_gvt_inprogress(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), and tw_scheduler_optimistic_debug().
g_tw_gvt_hook_trigger
struct gvt_hook_trigger g_tw_gvt_hook_trigger extern
Definition at line 14 of file mpi_allreduce.c.
Referenced by is_gvt_past_hook_threshold(), tw_gvt_hook_step(), tw_gvt_hook_step_seq(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_trigger_gvt_hook_at(), tw_trigger_gvt_hook_every(), tw_trigger_gvt_hook_now(), tw_trigger_gvt_hook_now_rev(), and tw_trigger_gvt_hook_when_model_calls().