ROSS: build/bin/include/gvt/mpi_allreduce.h File Reference
mpi_allreduce.h File Reference
#include "ross-extern.h"
#include "ross-kernel-inline.h"
#include "ross-types.h"
#include "queue/tw-queue.h"
#include <math.h>
#include <sys/time.h>
#include <time.h>
Functions
static int tw_gvt_inprogress (tw_pe *pe)
static void gvt_print (tw_stime gvt)
tw_stat st_get_allreduce_count ()
Variables
static double gvt_print_interval = 0.01
static double percent_complete = 0.0
Function Documentation
gvt_print()
void gvt_print (tw_stime gvt) inline static
Definition at line 22 of file mpi_allreduce.h.
References g_tw_gvt_done, g_tw_pe, g_tw_ts_end, gvt_print_interval, percent_complete, ROSS_MIN, tw_pq_max_size(), and TW_STIME_DBL.
Referenced by tw_gvt_step2(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
st_get_allreduce_count()
tw_stat st_get_allreduce_count () extern
Definition at line 55 of file mpi_allreduce.c.
References all_reduce_cnt.
Referenced by st_collect_engine_data_pes().
tw_gvt_inprogress()
int tw_gvt_inprogress (tw_pe * pe) inline static
Definition at line 16 of file mpi_allreduce.h.
References pe.
Referenced by event_cancel(), recv_begin(), recv_finish(), and tw_event_send().
Variable Documentation
gvt_print_interval
double gvt_print_interval = 0.01 static
Definition at line 12 of file mpi_allreduce.h.
Referenced by gvt_print().
percent_complete
double percent_complete = 0.0 static
Definition at line 13 of file mpi_allreduce.h.
Referenced by gvt_print(), tw_gvt_step2(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().