ROSS: build/bin/include/hash-quadratic.h File Reference
hash-quadratic.h File Reference
#include "ross-types.h"
Data Structures
struct tw_hash
Macros
#define MAX_FRACTION 0.50
Typedefs
typedef struct tw_hash tw_hash
Functions
void * tw_hash_create ()
void tw_hash_insert (void *h, tw_event *event, long pe)
tw_event * tw_hash_remove (void *h, tw_event *event, long pe)
Variables
unsigned int g_tw_hash_size
Macro Definition Documentation
MAX_FRACTION
#define MAX_FRACTION 0.50
Definition at line 6 of file hash-quadratic.h.
Referenced by tw_hash_insert().
Typedef Documentation
tw_hash
typedef struct tw_hash tw_hash
Definition at line 10 of file hash-quadratic.h.
Function Documentation
tw_hash_create()
void * tw_hash_create () extern
Definition at line 32 of file hash-quadratic.c.
References g_tw_avl_node_count, g_tw_hash_size, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, is_prime(), ncpu, avlNode::next, next_prime(), tw_hash::num_stored, tw_calloc(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by tw_pe_init().
tw_hash_insert()
void tw_hash_insert (void * h, tw_event * event, long pe) extern
Definition at line 80 of file hash-quadratic.c.
References tw_kp::avl_tree, avlInsert(), tw_event::dest_lp, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, tw_lp::kp, MAX_FRACTION, tw_hash::num_stored, pe, and tw_clock_read().
Referenced by recv_finish().
tw_hash_remove()
tw_event * tw_hash_remove (void * h, tw_event * event, long pe) extern
Definition at line 206 of file hash-quadratic.c.
References tw_kp::avl_tree, avlDelete(), tw_event::dest_lp, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, tw_lp::kp, tw_hash::num_stored, pe, tw_clock_read(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by recv_finish(), and tw_eventq_push_list().
Variable Documentation
g_tw_hash_size
unsigned int g_tw_hash_size extern
Definition at line 21 of file hash-quadratic.c.
Referenced by tw_hash_create().