ROSS: build/bin/include/instrumentation/st-instrumentation.h File Reference
st-instrumentation.h File Reference
#include "tw-opts.h"
#include "ross-types.h"
Data Structures
struct st_stats_buffer
struct sample_metadata
struct st_pe_stats
struct st_kp_stats
struct st_lp_stats
struct st_event_data
struct st_model_types
struct model_metadata
Macros
#define INST_MAX_LENGTH 4096
#define st_buffer_free_space(buf)
#define st_buffer_write_ptr(buf)
#define st_buffer_read_ptr(buf)
Typedefs
typedef struct sample_metadata sample_metadata
typedef struct st_pe_stats st_pe_stats
typedef struct st_kp_stats st_kp_stats
typedef struct st_lp_stats st_lp_stats
typedef void(* ev_trace_f) (void *msg, tw_lp *lp, char *buffer, int *collect_flag)
typedef void(* sample_event_f) (void *state, tw_bf *b, tw_lp *lp, void *sample)
typedef void(* sample_revent_f) (void *state, tw_bf *b, tw_lp *lp, void *sample)
typedef void(* model_stat_f) (void *sv, tw_lp *lp, char *buffer)
typedef struct st_model_types st_model_types
Enumerations
enum collection_types {
GVT_COL , RT_COL , ANALYSIS_LP , EV_TRACE ,
MODEL_COL , NUM_COL_TYPES
}
enum inst_data_types { PE_TYPE , KP_TYPE , LP_TYPE , MODEL_TYPE }
enum granularity_types { GRAN_PE , GRAN_KP , GRAN_LP , GRAN_ALL }
enum traces_enum { NO_TRACE , FULL_TRACE , RB_TRACE , COMMIT_TRACE }
enum stats_types_enum {
NO_STATS , GVT_STATS , RT_STATS , VT_STATS ,
ALL_STATS
}
Functions
void st_buffer_allocate ()
void st_buffer_init (int type)
void st_buffer_push (int type, char *data, int size)
void st_buffer_write (int end_of_sim, int type)
void st_buffer_finalize (int type)
const tw_optdef * st_inst_opts ()
void st_inst_init (void)
void st_inst_dump ()
void st_inst_finalize (tw_pe *me)
void st_collect_engine_data (tw_pe *me, int col_type)
void st_collect_engine_data_pes (tw_pe *pe, sample_metadata *sample_md, tw_statistics *s, int col_type)
void st_collect_engine_data_kps (tw_pe *me, tw_kp *kp, sample_metadata *sample_md, int col_type)
void st_collect_engine_data_lps (tw_lp *lp, sample_metadata *sample_md, int col_type)
void st_collect_event_data (tw_event *cev, double recv_rt)
void specialized_lp_setup ()
void specialized_lp_init_mapping ()
void specialized_lp_run ()
const tw_optdef * st_special_lp_opts (void)
void st_model_setup_types (tw_lp *lp)
void st_model_settype (tw_lpid i, st_model_types *model_types)
void st_collect_model_data (tw_pe *pe, double current_rt, int stats_type)
Variables
char stats_directory [4096]
int g_st_buffer_size
int g_st_buffer_free_percent
FILE * seq_ev_trace
FILE * seq_model
FILE * seq_analysis
char g_st_stats_out [4096]
char g_st_stats_path [4096]
int g_st_pe_data
int g_st_kp_data
int g_st_lp_data
int g_st_disable_out
int g_st_model_stats
int g_st_engine_stats
int g_st_gvt_sampling
int g_st_num_gvt
int g_st_rt_sampling
tw_clock g_st_rt_interval
tw_clock g_st_rt_samp_start_cycles
int g_st_ev_trace
int g_st_use_analysis_lps
tw_lpid g_st_analysis_nlp
double g_st_vt_interval
double g_st_sampling_end
tw_lpid g_st_total_model_lps
int g_st_sample_count
st_model_types * g_st_model_types
Macro Definition Documentation
INST_MAX_LENGTH
#define INST_MAX_LENGTH 4096
Definition at line 11 of file st-instrumentation.h.
Referenced by st_buffer_allocate(), and st_buffer_init().
st_buffer_free_space
#define st_buffer_free_space (buf)
Value:
(buf->size - buf->count)
Definition at line 14 of file st-instrumentation.h.
Referenced by st_buffer_push().
st_buffer_read_ptr
#define st_buffer_read_ptr (buf)
Value:
(buf->buffer + buf->read_pos)
Definition at line 16 of file st-instrumentation.h.
Referenced by st_buffer_write().
st_buffer_write_ptr
#define st_buffer_write_ptr (buf)
Value:
(buf->buffer + buf->write_pos)
Definition at line 15 of file st-instrumentation.h.
Referenced by st_buffer_push().
Typedef Documentation
ev_trace_f
typedef void(* ev_trace_f) (void *msg, tw_lp *lp, char *buffer, int *collect_flag)
Definition at line 189 of file st-instrumentation.h.
model_stat_f
typedef void(* model_stat_f) (void *sv, tw_lp *lp, char *buffer)
Definition at line 215 of file st-instrumentation.h.
sample_event_f
typedef void(* sample_event_f) (void *state, tw_bf *b, tw_lp *lp, void *sample)
Definition at line 198 of file st-instrumentation.h.
sample_metadata
typedef struct sample_metadata sample_metadata
Definition at line 38 of file st-instrumentation.h.
sample_revent_f
typedef void(* sample_revent_f) (void *state, tw_bf *b, tw_lp *lp, void *sample)
Definition at line 199 of file st-instrumentation.h.
st_kp_stats
typedef struct st_kp_stats st_kp_stats
Definition at line 98 of file st-instrumentation.h.
st_lp_stats
typedef struct st_lp_stats st_lp_stats
Definition at line 99 of file st-instrumentation.h.
st_model_types
typedef struct st_model_types st_model_types
Definition at line 216 of file st-instrumentation.h.
st_pe_stats
typedef struct st_pe_stats st_pe_stats
Definition at line 97 of file st-instrumentation.h.
Enumeration Type Documentation
collection_types
enum collection_types
Enumerator
GVT_COL
RT_COL
ANALYSIS_LP
EV_TRACE
MODEL_COL
NUM_COL_TYPES
Definition at line 40 of file st-instrumentation.h.
granularity_types
enum granularity_types
Enumerator
GRAN_PE
GRAN_KP
GRAN_LP
GRAN_ALL
Definition at line 56 of file st-instrumentation.h.
inst_data_types
enum inst_data_types
Enumerator
PE_TYPE
KP_TYPE
LP_TYPE
MODEL_TYPE
Definition at line 49 of file st-instrumentation.h.
stats_types_enum
enum stats_types_enum
Enumerator
NO_STATS
GVT_STATS
RT_STATS
VT_STATS
ALL_STATS
Definition at line 231 of file st-instrumentation.h.
traces_enum
enum traces_enum
Enumerator
NO_TRACE
FULL_TRACE
RB_TRACE
COMMIT_TRACE
Definition at line 172 of file st-instrumentation.h.
Function Documentation
specialized_lp_init_mapping()
void specialized_lp_init_mapping () extern
Definition at line 41 of file specialized-lps.c.
References analysis_start_gid, g_st_analysis_nlp, g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nlp, g_tw_pe, st_analysis_lp_settype(), tw_lp_onkp(), and tw_lp_onpe().
Referenced by tw_define_lps().
specialized_lp_run()
void specialized_lp_run () extern
Definition at line 52 of file specialized-lps.c.
References g_st_sampling_end, and g_tw_ts_end.
Referenced by st_inst_init().
specialized_lp_setup()
void specialized_lp_setup () extern
Definition at line 18 of file specialized-lps.c.
References ALL_STATS, ANALYSIS_LP, analysis_start_gid, g_st_analysis_nlp, g_st_engine_stats, g_st_model_stats, g_st_total_model_lps, g_st_use_analysis_lps, g_tw_nkp, g_tw_nlp, g_tw_synchronization_protocol, MPI_COMM_ROSS, SEQUENTIAL, st_buffer_init(), and VT_STATS.
Referenced by tw_define_lps().
st_buffer_allocate()
void st_buffer_allocate ()
Definition at line 16 of file st-stats-buffer.c.
References buffer_fh, g_st_buffer, g_st_engine_stats, g_st_ev_trace, g_st_model_stats, g_st_stats_path, g_st_use_analysis_lps, g_tw_masternode, g_tw_mynode, INST_MAX_LENGTH, MPI_COMM_ROSS, NUM_COL_TYPES, prev_offsets, stats_directory, tw_calloc(), and TW_LOC.
Referenced by tw_define_lps().
st_buffer_finalize()
void st_buffer_finalize (int type)
Definition at line 200 of file st-stats-buffer.c.
References buffer_fh, g_st_disable_out, g_tw_mynode, missed_bytes, and st_buffer_write().
Referenced by st_inst_finalize().
st_buffer_init()
void st_buffer_init (int type)
Definition at line 68 of file st-stats-buffer.c.
References ANALYSIS_LP, buffer_fh, file_suffix, g_st_buffer, g_st_buffer_size, g_st_disable_out, g_st_stats_out, g_tw_synchronization_protocol, INST_MAX_LENGTH, MPI_COMM_ROSS, seq_analysis, seq_ev_trace, seq_model, SEQUENTIAL, stats_directory, tw_calloc(), and TW_LOC.
Referenced by specialized_lp_setup(), and st_inst_init().
st_buffer_push()
void st_buffer_push (int type, char * data, int size)
Definition at line 112 of file st-stats-buffer.c.
References buffer_overflow_warned, g_st_buffer, g_st_disable_out, g_tw_lp, g_tw_mynode, missed_bytes, st_buffer_free_space, st_buffer_write_ptr, tw_now(), and TW_STIME_DBL.
Referenced by analysis_commit(), st_collect_engine_data_kps(), st_collect_engine_data_lps(), st_collect_engine_data_pes(), st_collect_event_data(), and st_collect_model_data().
st_buffer_write()
void st_buffer_write (int end_of_sim, int type)
Definition at line 149 of file st-stats-buffer.c.
References buffer_fh, buffer_overflow_warned, g_st_buffer, g_st_buffer_free_percent, g_st_buffer_size, g_tw_mynode, g_tw_pe, MPI_COMM_ROSS, prev_offsets, st_buffer_read_ptr, tw_clock_read(), and tw_nnodes().
Referenced by st_inst_dump().
st_collect_engine_data()
void st_collect_engine_data (tw_pe * me, int col_type)
Definition at line 10 of file st-sim-engine.c.
References g_st_kp_data, g_st_lp_data, g_st_pe_data, g_tw_clock_rate, g_tw_nkp, g_tw_nlp, pe, sample_metadata::real_time, st_collect_engine_data_kps(), st_collect_engine_data_lps(), st_collect_engine_data_pes(), sample_metadata::ts, tw_clock_read(), tw_get_stats(), tw_getkp(), and tw_getlp().
Referenced by analysis_event(), st_inst_finalize(), tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), and tw_scheduler_conservative().
st_collect_engine_data_kps()
void st_collect_engine_data_kps (tw_pe * me, tw_kp * kp, sample_metadata * sample_md, int col_type)
Definition at line 106 of file st-sim-engine.c.
References st_kp_stats::efficiency, sample_metadata::flag, g_tw_mynode, tw_kp::id, tw_kp::kp_stats, KP_TYPE, st_kp_stats::kpid, tw_kp::last_sig, tw_kp::last_stats, tw_kp::last_time, pe, st_kp_stats::peid, tw_event_sig::recv_ts, st_kp_stats::s_e_rbs, st_kp_stats::s_nevent_abort, st_kp_stats::s_nevent_processed, st_kp_stats::s_nread_network, st_kp_stats::s_nsend_network, st_kp_stats::s_rb_secondary, st_kp_stats::s_rb_total, sample_metadata::sample_sz, st_buffer_push(), st_kp_stats::time_ahead_gvt, tw_error(), TW_LOC, and TW_STIME_DBL.
st_collect_engine_data_lps()
void st_collect_engine_data_lps (tw_lp * lp, sample_metadata * sample_md, int col_type)
Definition at line 153 of file st-sim-engine.c.
References st_lp_stats::efficiency, sample_metadata::flag, g_tw_mynode, tw_lp::gid, tw_kp::id, tw_lp::kp, st_lp_stats::kpid, tw_lp::last_stats, tw_lp::lp_stats, LP_TYPE, st_lp_stats::lpid, st_lp_stats::peid, st_lp_stats::s_e_rbs, st_lp_stats::s_nevent_abort, st_lp_stats::s_nevent_processed, st_lp_stats::s_nread_network, st_lp_stats::s_nsend_network, sample_metadata::sample_sz, st_buffer_push(), tw_error(), and TW_LOC.
st_collect_engine_data_pes()
void st_collect_engine_data_pes (tw_pe * pe, sample_metadata * sample_md, tw_statistics * s, int col_type)
Definition at line 49 of file st-sim-engine.c.
References all_reduce_cnt, st_pe_stats::all_reduce_count, st_pe_stats::efficiency, sample_metadata::flag, g_tw_clock_rate, g_tw_gvt_done, g_tw_mynode, last_all_reduce_cnt, last_pe_stats, pe, PE_TYPE, st_pe_stats::peid, st_pe_stats::s_avl, st_pe_stats::s_buddy, st_pe_stats::s_cancel_q, st_pe_stats::s_e_rbs, tw_statistics::s_e_rbs, st_pe_stats::s_event_abort, st_pe_stats::s_event_process, st_pe_stats::s_fc_attempts, tw_statistics::s_fc_attempts, st_pe_stats::s_fossil_collect, st_pe_stats::s_gvt, st_pe_stats::s_lz4, st_pe_stats::s_net_other, st_pe_stats::s_net_read, st_pe_stats::s_nevent_abort, tw_statistics::s_nevent_abort, st_pe_stats::s_nevent_processed, tw_statistics::s_nevent_processed, st_pe_stats::s_ngvts, st_pe_stats::s_nread_network, tw_statistics::s_nread_network, st_pe_stats::s_nsend_network, tw_statistics::s_nsend_network, st_pe_stats::s_pe_event_ties, tw_statistics::s_pe_event_ties, st_pe_stats::s_pq, st_pe_stats::s_pq_qsize, st_pe_stats::s_rb_secondary, tw_statistics::s_rb_secondary, st_pe_stats::s_rb_total, tw_statistics::s_rb_total, st_pe_stats::s_rollback, sample_metadata::sample_sz, st_buffer_push(), st_get_allreduce_count(), and tw_pq_get_size().
st_collect_event_data()
void st_collect_event_data (tw_event * cev, double recv_rt)
Definition at line 9 of file st-event-trace.c.
References st_event_data::dest_lp, tw_event::dest_lp, st_model_types::ev_sz, EV_TRACE, st_model_types::ev_trace, evtype_warned, g_st_disable_out, g_tw_masternode, g_tw_mynode, g_tw_pe, g_tw_synchronization_protocol, tw_lp::gid, st_event_data::model_data_sz, tw_lp::model_types, st_event_data::real_ts, tw_event::recv_ts, st_event_data::recv_vts, tw_event::send_lp, tw_event::send_ts, st_event_data::send_vts, seq_ev_trace, SEQUENTIAL, st_event_data::src_lp, st_buffer_push(), tw_clock_read(), tw_event_data(), and TW_STIME_DBL.
Referenced by tw_eventq_push_list(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
st_collect_model_data()
void st_collect_model_data (tw_pe * pe, double current_rt, int stats_type)
Definition at line 45 of file st-model-data.c.
References tw_lp::cur_state, sample_metadata::flag, g_st_disable_out, g_tw_lp, g_tw_mynode, g_tw_nlp, g_tw_synchronization_protocol, tw_lp::gid, model_metadata::gvt, tw_kp::id, tw_lp::kp, model_metadata::kpid, model_metadata::lpid, MODEL_COL, st_model_types::model_stat_fn, model_metadata::model_sz, MODEL_TYPE, tw_lp::model_types, st_model_types::mstat_sz, pe, model_metadata::peid, sample_metadata::real_time, sample_metadata::sample_sz, seq_model, SEQUENTIAL, st_buffer_push(), model_metadata::stats_type, sample_metadata::ts, tw_clock_read(), tw_now(), and TW_STIME_DBL.
Referenced by tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
st_inst_dump()
void st_inst_dump () extern
Definition at line 88 of file st-instrumentation.c.
References ALL_STATS, ANALYSIS_LP, EV_TRACE, g_st_disable_out, g_st_engine_stats, g_st_ev_trace, g_st_model_stats, g_st_use_analysis_lps, GVT_COL, GVT_STATS, MODEL_COL, RT_COL, RT_STATS, and st_buffer_write().
Referenced by tw_gvt_step2().
st_inst_finalize()
void st_inst_finalize (tw_pe * me) extern
Definition at line 105 of file st-instrumentation.c.
References ALL_STATS, ANALYSIS_LP, EV_TRACE, g_st_engine_stats, g_st_ev_trace, g_st_model_stats, g_st_use_analysis_lps, GVT_COL, GVT_STATS, MODEL_COL, RT_COL, RT_STATS, st_buffer_finalize(), and st_collect_engine_data().
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_optimistic_realtime().
st_inst_init()
void st_inst_init (void) extern
Definition at line 51 of file st-instrumentation.c.
References ALL_STATS, EV_TRACE, g_st_engine_stats, g_st_ev_trace, g_st_gvt_sampling, g_st_model_stats, g_st_rt_interval, g_st_rt_samp_start_cycles, g_st_rt_sampling, g_tw_clock_rate, GVT_COL, GVT_STATS, MODEL_COL, RT_COL, RT_STATS, specialized_lp_run(), st_buffer_init(), and tw_clock_read().
Referenced by tw_run().
st_inst_opts()
const tw_optdef * st_inst_opts () extern
Definition at line 46 of file st-instrumentation.c.
References inst_options.
Referenced by tw_init().
st_model_settype()
void st_model_settype (tw_lpid i, st_model_types * model_types)
Definition at line 25 of file st-model-data.c.
References g_tw_lp, g_tw_masternode, g_tw_mynode, model_type_warned, model_types, and tw_lp::model_types.
Referenced by main().
st_model_setup_types()
void st_model_setup_types (tw_lp * lp)
Definition at line 10 of file st-model-data.c.
References g_st_model_types, g_tw_lp_typemap, g_tw_masternode, g_tw_mynode, tw_lp::gid, model_type_warned, and tw_lp::model_types.
Referenced by tw_lp_setup_types().
st_special_lp_opts()
const tw_optdef * st_special_lp_opts (void) extern
Definition at line 67 of file specialized-lps.c.
References special_lp_opt.
Referenced by tw_init().
Variable Documentation
g_st_analysis_nlp
tw_lpid g_st_analysis_nlp extern
Definition at line 12 of file specialized-lps.c.
Referenced by late_sanity_check(), specialized_lp_init_mapping(), specialized_lp_setup(), tw_all_lp_stats(), tw_define_lps(), tw_getlp(), tw_init_lps(), tw_lp_onpe(), tw_lp_settype(), tw_pre_run_lps(), and tw_stats().
g_st_buffer_free_percent
int g_st_buffer_free_percent extern
Definition at line 10 of file st-stats-buffer.c.
Referenced by st_buffer_write().
g_st_buffer_size
int g_st_buffer_size extern
Definition at line 9 of file st-stats-buffer.c.
Referenced by st_buffer_init(), and st_buffer_write().
g_st_disable_out
int g_st_disable_out extern
Definition at line 9 of file st-instrumentation.c.
Referenced by analysis_commit(), st_buffer_finalize(), st_buffer_init(), st_buffer_push(), st_collect_event_data(), st_collect_model_data(), and st_inst_dump().
g_st_engine_stats
int g_st_engine_stats extern
Definition at line 12 of file st-instrumentation.c.
Referenced by analysis_event(), specialized_lp_setup(), st_buffer_allocate(), st_inst_dump(), st_inst_finalize(), st_inst_init(), tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), and tw_scheduler_conservative().
g_st_ev_trace
int g_st_ev_trace extern
Definition at line 3 of file st-event-trace.c.
Referenced by st_buffer_allocate(), st_inst_dump(), st_inst_finalize(), st_inst_init(), tw_eventq_push_list(), tw_lp_setup_types(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
g_st_gvt_sampling
int g_st_gvt_sampling extern
Definition at line 14 of file st-instrumentation.c.
Referenced by st_inst_init().
g_st_kp_data
int g_st_kp_data extern
Definition at line 7 of file st-instrumentation.c.
Referenced by st_collect_engine_data().
g_st_lp_data
int g_st_lp_data extern
Definition at line 8 of file st-instrumentation.c.
Referenced by st_collect_engine_data().
g_st_model_stats
int g_st_model_stats extern
Definition at line 11 of file st-instrumentation.c.
Referenced by analysis_commit(), analysis_event(), analysis_event_rc(), analysis_init(), specialized_lp_setup(), st_buffer_allocate(), st_inst_dump(), st_inst_finalize(), st_inst_init(), tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
g_st_model_types
st_model_types* g_st_model_types extern
Definition at line 3 of file st-model-data.c.
Referenced by st_model_setup_types().
g_st_num_gvt
int g_st_num_gvt extern
Definition at line 15 of file st-instrumentation.c.
Referenced by tw_gvt_step2().
g_st_pe_data
int g_st_pe_data extern
Definition at line 6 of file st-instrumentation.c.
Referenced by st_collect_engine_data().
g_st_rt_interval
tw_clock g_st_rt_interval extern
Definition at line 18 of file st-instrumentation.c.
Referenced by st_inst_init(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
g_st_rt_samp_start_cycles
tw_clock g_st_rt_samp_start_cycles extern
Definition at line 19 of file st-instrumentation.c.
Referenced by st_inst_init(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
g_st_rt_sampling
int g_st_rt_sampling extern
Definition at line 17 of file st-instrumentation.c.
Referenced by st_inst_init(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
g_st_sample_count
int g_st_sample_count extern
Definition at line 13 of file specialized-lps.c.
Referenced by analysis_init().
g_st_sampling_end
double g_st_sampling_end extern
Definition at line 22 of file st-instrumentation.c.
Referenced by specialized_lp_run(), and st_create_sample_event().
g_st_stats_out
char g_st_stats_out[4096] extern
Definition at line 4 of file st-instrumentation.c.
Referenced by st_buffer_init().
g_st_stats_path
char g_st_stats_path[4096] extern
Definition at line 5 of file st-instrumentation.c.
Referenced by st_buffer_allocate().
g_st_total_model_lps
tw_lpid g_st_total_model_lps extern
Definition at line 16 of file specialized-lps.c.
Referenced by specialized_lp_setup(), and tw_getlocal_lp().
g_st_use_analysis_lps
int g_st_use_analysis_lps extern
Definition at line 11 of file specialized-lps.c.
Referenced by specialized_lp_setup(), st_buffer_allocate(), st_inst_dump(), st_inst_finalize(), tw_getlocal_lp(), tw_init(), and tw_stats().
g_st_vt_interval
double g_st_vt_interval extern
Definition at line 21 of file st-instrumentation.c.
Referenced by st_create_sample_event().
seq_analysis
FILE * seq_analysis
Definition at line 29 of file st-instrumentation.h.
Referenced by analysis_commit(), and st_buffer_init().
seq_ev_trace
FILE* seq_ev_trace extern
Definition at line 13 of file st-stats-buffer.c.
Referenced by st_buffer_init(), and st_collect_event_data().
seq_model
FILE * seq_model
Definition at line 29 of file st-instrumentation.h.
Referenced by st_buffer_init(), and st_collect_model_data().
stats_directory
char stats_directory[4096] extern
Definition at line 8 of file st-stats-buffer.c.
Referenced by st_buffer_allocate(), and st_buffer_init().