ROSS: build/bin/include/avl_tree.h File Reference
avl_tree.h File Reference
#include "ross-types.h"
Data Structures
struct avlNode
Macros
#define AVL_EMPTY (0)
Functions
void avlDestroy (AvlTree t)
int avlGetHeight (AvlTree t)
int avlSearch (AvlTree t, tw_event *key)
void avlInsert (AvlTree *t, tw_event *key)
void avlSanityCheck (AvlTree t)
void avlPrintKeys (AvlTree t)
tw_event * avlDeleteMin (AvlTree *t)
tw_event * avlDelete (AvlTree *t, tw_event *key)
AvlTree avl_alloc (void)
void avl_free (AvlTree t)
Macro Definition Documentation
AVL_EMPTY
#define AVL_EMPTY (0)
Definition at line 19 of file avl_tree.h.
Referenced by avl_free(), avlDelete(), avlDeleteMin(), avlDestroy(), avlFixHeight(), avlGetHeight(), avlInsert(), avlPrintKeys(), avlRebalance(), avlSanityCheck(), and avlSearch().
Function Documentation
avl_alloc()
AvlTree avl_alloc (void)
Definition at line 330 of file avl_tree.c.
References g_tw_avl_node_count, g_tw_pe, avlNode::next, tw_error(), and TW_LOC.
avl_free()
void avl_free (AvlTree t)
Definition at line 346 of file avl_tree.c.
References AVL_EMPTY, and g_tw_pe.
avlDelete()
tw_event * avlDelete (AvlTree * t, tw_event * key)
Definition at line 270 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDelete(), avlDeleteMin(), avlRebalance(), avlNode::child, tw_event::event_id, tw_event_sig::event_tiebreaker, tw_event::recv_ts, tw_event::send_pe, tw_event::sig, tw_error(), TW_LOC, and TW_STIME_CMP.
Referenced by tw_hash_remove().
avlDeleteMin()
tw_event * avlDeleteMin (AvlTree * t)
Definition at line 245 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDeleteMin(), avlRebalance(), avlNode::child, and avlNode::key.
avlDestroy()
void avlDestroy (AvlTree t)
Definition at line 14 of file avl_tree.c.
References AVL_EMPTY, avl_free(), avlDestroy(), and avlNode::child.
avlGetHeight()
int avlGetHeight (AvlTree t)
Definition at line 27 of file avl_tree.c.
References AVL_EMPTY, and avlNode::height.
Referenced by avlFixHeight(), avlRebalance(), and avlSanityCheck().
avlInsert()
void avlInsert (AvlTree * t, tw_event * key)
Definition at line 172 of file avl_tree.c.
References avl_alloc(), AVL_EMPTY, avlInsert(), avlRebalance(), tw_event::event_id, tw_event_sig::event_tiebreaker, g_tw_avl_node_count, tw_event::recv_ts, tw_event::send_pe, tw_event::sig, tw_error(), TW_LOC, tw_printf(), and TW_STIME_CMP.
Referenced by tw_hash_insert().
avlPrintKeys()
void avlPrintKeys (AvlTree t)
Definition at line 233 of file avl_tree.c.
References AVL_EMPTY, avlPrintKeys(), and avlNode::child.
avlSanityCheck()
void avlSanityCheck (AvlTree t)
Definition at line 81 of file avl_tree.c.
References AVL_EMPTY, avlGetHeight(), avlSanityCheck(), avlNode::child, avlNode::height, and ROSS_MAX.
avlSearch()
int avlSearch (AvlTree t, tw_event * key)
Definition at line 39 of file avl_tree.c.
References AVL_EMPTY, avlSearch(), avlNode::child, tw_event::event_id, tw_event_sig::event_tiebreaker, avlNode::key, tw_event::recv_ts, tw_event::send_pe, tw_event::sig, and TW_STIME_CMP.