ROSS: build/bin/include/ross-inline.h File Reference
ross-inline.h File Reference
#include "ross-types.h"
#include "tw-eventq.h"
Functions
static tw_event * tw_event_grab (tw_pe *pe)
static void tw_free_output_messages (tw_event *e, int print_message)
static tw_event * tw_event_new_user_prio (tw_lpid dest_gid, tw_stime offset_ts, tw_lp *sender, tw_stime prio)
static tw_event * tw_event_new (tw_lpid dest_gid, tw_stime offset_ts, tw_lp *sender)
static void tw_event_free (tw_pe *pe, tw_event *e)
static void * tw_event_data (tw_event *event)
Function Documentation
tw_event_data()
void * tw_event_data (tw_event * event) inline static
Definition at line 164 of file ross-inline.h.
tw_event_free()
void tw_event_free (tw_pe * pe, tw_event * e) inline static
Definition at line 141 of file ross-inline.h.
References buddy_free(), tw_event::delta_buddy, g_tw_pe, tw_event::owner, pe, tw_event::state, tw_clock_read(), tw_eventq_unshift(), tw_free_output_messages(), and TW_pe_free_q.
tw_event_grab()
tw_event * tw_event_grab (tw_pe * pe) inline static
Definition at line 11 of file ross-inline.h.
References tw_event::cancel_next, tw_event::cause_next, tw_event::caused_by_me, tw_event::event_id, tw_event::next, pe, tw_event::prev, tw_event::state, and tw_eventq_pop().
Referenced by recv_begin(), and tw_event_new_user_prio().
tw_event_new()
tw_event * tw_event_new (tw_lpid dest_gid, tw_stime offset_ts, tw_lp * sender) inline static
Bug
There's a bug in this function. We put dest_gid, which is a 64-bit value, into dest_lp which may be a 32-bit pointer.
Definition at line 134 of file ross-inline.h.
References tw_event_new_user_prio().
Referenced by io_load_events(), phold_event_handler(), phold_init(), phold_pre_run(), and st_create_sample_event().
tw_event_new_user_prio()
tw_event * tw_event_new_user_prio (tw_lpid dest_gid, tw_stime offset_ts, tw_lp * sender, tw_stime prio) inline static
Creates an event with a given priority in range [0,1], lower value is higher priority
Bug
There's a bug in this function. We put dest_gid, which is a 64-bit value, into dest_lp which may be a 32-bit pointer.
Definition at line 48 of file ross-inline.h.
References tw_pe::abort_event, tw_event::aborted_total, CONSERVATIVE, tw_lp::core_rng, tw_event::critical_path, tw_lp::critical_path, tw_pe::cur_event, tw_event::dest_lp, tw_event::dest_lpid, tw_event_sig::event_tiebreaker, g_tw_min_detected_offset, g_tw_synchronization_protocol, g_tw_ts_end, tw_lp::gid, tw_pe::id, io_event_grab(), MAX_TIE_CHAIN, tw_lp::pe, tw_event_sig::priority, tw_event::recv_ts, tw_event_sig::recv_ts, tw_statistics::s_events_past_end, tw_event::send_pe, tw_event::send_ts, SEQUENTIAL, tw_event::sig, tw_event::src_lp, tw_pe::stats, tw_event_sig::tie_lineage_length, tw_error(), tw_event_grab(), tw_free_output_messages(), TW_LOC, tw_now(), tw_rand_unif, TW_STIME_ADD, and TW_STIME_DBL.
Referenced by tw_event_new().
tw_free_output_messages()
void tw_free_output_messages (tw_event * e, int print_message) inline static
Definition at line 29 of file ross-inline.h.
References tw_out::message, tw_out::next, tw_event::out_msgs, and tw_kp_put_back_output_buffer().
Referenced by tw_event_free(), and tw_event_new_user_prio().