ROSS: build/bin/include/queue/tw-queue.h File Reference
tw-queue.h File Reference
#include "ross-types.h"
Functions
tw_pq * tw_pq_create (void)
void tw_pq_enqueue (tw_pq *, tw_event *)
tw_event * tw_pq_dequeue (tw_pq *)
tw_stime tw_pq_minimum (tw_pq *)
void tw_pq_delete_any (tw_pq *, tw_event *)
unsigned int tw_pq_get_size (tw_pq *)
unsigned int tw_pq_max_size (tw_pq *)
Function Documentation
tw_pq_create()
tw_pq * tw_pq_create (void)
Definition at line 56 of file splay.c.
References tw_pq::least, tw_pq::nitems, tw_pq::root, tw_calloc(), and TW_LOC.
Referenced by setup_pes().
tw_pq_delete_any()
void tw_pq_delete_any (tw_pq * st, tw_event * r)
Definition at line 341 of file splay.c.
References tw_pq::least, LEFT, tw_pq::nitems, tw_event::owner, RIGHT, tw_pq::root, splay(), tw_event::state, tw_error(), TW_LOC, tw_pq_dequeue(), and UP.
Referenced by event_cancel(), and tw_sched_cancel_q().
tw_pq_dequeue()
tw_event * tw_pq_dequeue (tw_pq * st)
Definition at line 298 of file splay.c.
References tw_pq::least, LEFT, tw_pq::nitems, tw_event::owner, RIGHT, tw_pq::root, tw_event::state, and UP.
Referenced by tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
tw_pq_enqueue()
void tw_pq_enqueue (tw_pq * st, tw_event * e)
Definition at line 245 of file splay.c.
References tw_pq::least, LEFT, tw_pq::max_size, tw_pq::nitems, tw_event::owner, RIGHT, tw_pq::root, splay(), tw_event::state, TW_pe_pq, tw_pq_compare_less_than(), and UP.
Referenced by recv_finish(), tw_event_send(), tw_kp_rollback_event(), tw_kp_rollback_to(), tw_sched_batch(), tw_sched_batch_realtime(), and tw_sched_event_q().
tw_pq_get_size()
unsigned int tw_pq_get_size (tw_pq * st)
Definition at line 418 of file splay.c.
References tw_pq::nitems.
Referenced by st_collect_engine_data_pes(), tw_get_stats(), and tw_gvt_hook_step_seq().
tw_pq_max_size()
unsigned int tw_pq_max_size (tw_pq * pq)
Definition at line 424 of file splay.c.
References tw_pq::max_size.
Referenced by gvt_print().
tw_pq_minimum()
tw_stime tw_pq_minimum (tw_pq * pq)
Definition at line 398 of file splay.c.
References tw_pq::least, tw_event::recv_ts, and TW_STIME_MAX.
Referenced by tw_gvt_hook_step(), tw_gvt_hook_step_seq(), tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().