ROSS: build/bin/include/lz4.h File Reference
lz4.h File Reference
Data Structures
struct LZ4_stream_t
struct LZ4_streamDecode_t
Macros
#define LZ4_VERSION_MAJOR 1 /* for breaking interface changes */
#define LZ4_VERSION_MINOR 7 /* for new (non-breaking) interface capabilities */
#define LZ4_VERSION_RELEASE 0 /* for tweaks, bug-fixes, or development */
#define LZ4_VERSION_NUMBER (LZ4_VERSION_MAJOR *100*100 + LZ4_VERSION_MINOR *100 + LZ4_VERSION_RELEASE)
#define LZ4_MEMORY_USAGE 14
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
#define LZ4_COMPRESSBOUND(isize)
#define LZ4_STREAMSIZE_U64 ((1 << (LZ4_MEMORY_USAGE-3)) + 4)
#define LZ4_STREAMSIZE (LZ4_STREAMSIZE_U64 * sizeof(long long))
#define LZ4_STREAMDECODESIZE_U64 4
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
#define LZ4_DEPRECATED(message)
Functions
int LZ4_versionNumber (void)
int LZ4_compress_default (const char *source, char *dest, int sourceSize, int maxDestSize)
int LZ4_decompress_safe (const char *source, char *dest, int compressedSize, int maxDecompressedSize)
int LZ4_compressBound (int inputSize)
int LZ4_compress_fast (const char *source, char *dest, int sourceSize, int maxDestSize, int acceleration)
int LZ4_sizeofState (void)
int LZ4_compress_fast_extState (void *state, const char *source, char *dest, int inputSize, int maxDestSize, int acceleration)
int LZ4_compress_destSize (const char *source, char *dest, int *sourceSizePtr, int targetDestSize)
int LZ4_decompress_fast (const char *source, char *dest, int originalSize)
int LZ4_decompress_safe_partial (const char *source, char *dest, int compressedSize, int targetOutputSize, int maxDecompressedSize)
void LZ4_resetStream (LZ4_stream_t *streamPtr)
LZ4_stream_t * LZ4_createStream (void)
int LZ4_freeStream (LZ4_stream_t *streamPtr)
int LZ4_loadDict (LZ4_stream_t *streamPtr, const char *dictionary, int dictSize)
int LZ4_compress_fast_continue (LZ4_stream_t *streamPtr, const char *src, char *dst, int srcSize, int maxDstSize, int acceleration)
int LZ4_saveDict (LZ4_stream_t *streamPtr, char *safeBuffer, int dictSize)
LZ4_streamDecode_t * LZ4_createStreamDecode (void)
int LZ4_freeStreamDecode (LZ4_streamDecode_t *LZ4_stream)
int LZ4_setStreamDecode (LZ4_streamDecode_t *LZ4_streamDecode, const char *dictionary, int dictSize)
int LZ4_decompress_safe_continue (LZ4_streamDecode_t *LZ4_streamDecode, const char *source, char *dest, int compressedSize, int maxDecompressedSize)
int LZ4_decompress_fast_continue (LZ4_streamDecode_t *LZ4_streamDecode, const char *source, char *dest, int originalSize)
int LZ4_decompress_safe_usingDict (const char *source, char *dest, int compressedSize, int maxDecompressedSize, const char *dictStart, int dictSize)
int LZ4_decompress_fast_usingDict (const char *source, char *dest, int originalSize, const char *dictStart, int dictSize)
int LZ4_compress (const char *source, char *dest, int sourceSize)
int LZ4_compress_limitedOutput (const char *source, char *dest, int sourceSize, int maxOutputSize)
int LZ4_compress_withState (void *state, const char *source, char *dest, int inputSize)
int LZ4_compress_limitedOutput_withState (void *state, const char *source, char *dest, int inputSize, int maxOutputSize)
int LZ4_compress_continue (LZ4_stream_t *LZ4_streamPtr, const char *source, char *dest, int inputSize)
int LZ4_compress_limitedOutput_continue (LZ4_stream_t *LZ4_streamPtr, const char *source, char *dest, int inputSize, int maxOutputSize)
void * LZ4_create (char *inputBuffer)
int LZ4_sizeofStreamState (void)
int LZ4_resetStreamState (void *state, char *inputBuffer)
char * LZ4_slideInputBuffer (void *state)
int LZ4_decompress_safe_withPrefix64k (const char *src, char *dst, int compressedSize, int maxDstSize)
int LZ4_decompress_fast_withPrefix64k (const char *src, char *dst, int originalSize)
Macro Definition Documentation
LZ4_COMPRESSBOUND
#define LZ4_COMPRESSBOUND (isize)
Value:
((unsigned)(isize) > (unsigned)LZ4_MAX_INPUT_SIZE ? 0 : (isize) + ((isize)/255) + 16)
Definition at line 106 of file lz4.h.
Referenced by LZ4_compressBound().
LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
Definition at line 314 of file lz4.h.
LZ4_DEPRECATED
#define LZ4_DEPRECATED (message)
Definition at line 324 of file lz4.h.
LZ4_GCC_VERSION
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
Definition at line 315 of file lz4.h.
LZ4_MAX_INPUT_SIZE
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
Definition at line 105 of file lz4.h.
Referenced by LZ4_compress_destSize_generic(), and LZ4_compress_generic().
LZ4_MEMORY_USAGE
#define LZ4_MEMORY_USAGE 14
Definition at line 66 of file lz4.h.
LZ4_STREAMDECODESIZE
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
Definition at line 248 of file lz4.h.
LZ4_STREAMDECODESIZE_U64
#define LZ4_STREAMDECODESIZE_U64 4
Definition at line 247 of file lz4.h.
LZ4_STREAMSIZE
#define LZ4_STREAMSIZE (LZ4_STREAMSIZE_U64 * sizeof(long long))
Definition at line 188 of file lz4.h.
Referenced by LZ4_createStream(), LZ4_init(), LZ4_sizeofState(), and LZ4_sizeofStreamState().
LZ4_STREAMSIZE_U64
#define LZ4_STREAMSIZE_U64 ((1 << (LZ4_MEMORY_USAGE-3)) + 4)
Definition at line 187 of file lz4.h.
Referenced by LZ4_create(), and LZ4_createStream().
LZ4_VERSION_MAJOR
#define LZ4_VERSION_MAJOR 1 /* for breaking interface changes */
Definition at line 50 of file lz4.h.
LZ4_VERSION_MINOR
#define LZ4_VERSION_MINOR 7 /* for new (non-breaking) interface capabilities */
Definition at line 51 of file lz4.h.
LZ4_VERSION_NUMBER
#define LZ4_VERSION_NUMBER (LZ4_VERSION_MAJOR *100*100 + LZ4_VERSION_MINOR *100 + LZ4_VERSION_RELEASE)
Definition at line 53 of file lz4.h.
Referenced by LZ4_versionNumber().
LZ4_VERSION_RELEASE
#define LZ4_VERSION_RELEASE 0 /* for tweaks, bug-fixes, or development */
Definition at line 52 of file lz4.h.
Function Documentation
LZ4_compress()
int LZ4_compress (const char * source, char * dest, int sourceSize)
Definition at line 1456 of file lz4.c.
References LZ4_compress_default(), and LZ4_compressBound().
LZ4_compress_continue()
int LZ4_compress_continue (LZ4_stream_t * LZ4_streamPtr, const char * source, char * dest, int inputSize)
Definition at line 1460 of file lz4.c.
References LZ4_compress_fast_continue(), and LZ4_compressBound().
LZ4_compress_default()
int LZ4_compress_default (const char * source, char * dest, int sourceSize, int maxDestSize)
Definition at line 697 of file lz4.c.
References LZ4_compress_fast().
LZ4_compress_destSize()
int LZ4_compress_destSize (const char * source, char * dest, int * sourceSizePtr, int targetDestSize)
Definition at line 912 of file lz4.c.
References ALLOCATOR, FREEMEM, and LZ4_compress_destSize_extState().
LZ4_compress_fast()
int LZ4_compress_fast (const char * source, char * dest, int sourceSize, int maxDestSize, int acceleration)
Definition at line 679 of file lz4.c.
References ALLOCATOR, FREEMEM, and LZ4_compress_fast_extState().
LZ4_compress_fast_continue()
int LZ4_compress_fast_continue (LZ4_stream_t * streamPtr, const char * src, char * dst, int srcSize, int maxDstSize, int acceleration)
Definition at line 1011 of file lz4.c.
References ACCELERATION_DEFAULT, byU32, LZ4_stream_t_internal::currentOffset, LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, dictSmall, LZ4_stream_t_internal::initCheck, KB, limitedOutput, LZ4_compress_generic(), LZ4_renormDictT(), noDictIssue, usingExtDict, and withPrefix64k.
LZ4_compress_fast_extState()
int LZ4_compress_fast_extState (void * state, const char * source, char * dest, int inputSize, int maxDestSize, int acceleration)
Definition at line 657 of file lz4.c.
References ACCELERATION_DEFAULT, byPtr, byU16, byU32, limitedOutput, LZ4_64bits(), LZ4_64Klimit, LZ4_compress_generic(), LZ4_compressBound(), LZ4_resetStream(), noDict, noDictIssue, and notLimited.
Referenced by tw_snapshot_delta().
LZ4_compress_limitedOutput()
int LZ4_compress_limitedOutput (const char * source, char * dest, int sourceSize, int maxOutputSize)
Definition at line 1455 of file lz4.c.
References LZ4_compress_default().
LZ4_compress_limitedOutput_continue()
int LZ4_compress_limitedOutput_continue (LZ4_stream_t * LZ4_streamPtr, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 1459 of file lz4.c.
References LZ4_compress_fast_continue().
LZ4_compress_limitedOutput_withState()
int LZ4_compress_limitedOutput_withState (void * state, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 1457 of file lz4.c.
References LZ4_compress_fast_extState().
LZ4_compress_withState()
int LZ4_compress_withState (void * state, const char * source, char * dest, int inputSize)
Definition at line 1458 of file lz4.c.
References LZ4_compress_fast_extState(), and LZ4_compressBound().
LZ4_compressBound()
int LZ4_compressBound (int inputSize)
Definition at line 372 of file lz4.c.
References LZ4_COMPRESSBOUND.
Referenced by tw_delta_alloc().
LZ4_create()
void * LZ4_create (char * inputBuffer)
Definition at line 1489 of file lz4.c.
References ALLOCATOR, LZ4_init(), and LZ4_STREAMSIZE_U64.
LZ4_createStream()
LZ4_stream_t * LZ4_createStream (void)
Definition at line 935 of file lz4.c.
References ALLOCATOR, LZ4_resetStream(), LZ4_STATIC_ASSERT, LZ4_STREAMSIZE, and LZ4_STREAMSIZE_U64.
LZ4_createStreamDecode()
LZ4_streamDecode_t * LZ4_createStreamDecode (void)
Definition at line 1319 of file lz4.c.
References ALLOCATOR.
LZ4_decompress_fast()
int LZ4_decompress_fast (const char * source, char * dest, int originalSize)
Definition at line 1298 of file lz4.c.
References endOnOutputSize, full, KB, LZ4_decompress_generic(), and withPrefix64k.
Referenced by tw_snapshot_restore().
LZ4_decompress_fast_continue()
int LZ4_decompress_fast_continue (LZ4_streamDecode_t * LZ4_streamDecode, const char * source, char * dest, int originalSize)
Definition at line 1384 of file lz4.c.
References endOnOutputSize, LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, full, LZ4_decompress_generic(), LZ4_streamDecode_t_internal::prefixEnd, LZ4_streamDecode_t_internal::prefixSize, and usingExtDict.
LZ4_decompress_fast_usingDict()
int LZ4_decompress_fast_usingDict (const char * source, char * dest, int originalSize, const char * dictStart, int dictSize)
Definition at line 1439 of file lz4.c.
References LZ4_decompress_usingDict_generic().
LZ4_decompress_fast_withPrefix64k()
int LZ4_decompress_fast_withPrefix64k (const char * src, char * dst, int originalSize)
Definition at line 1510 of file lz4.c.
References endOnOutputSize, full, KB, LZ4_decompress_generic(), and withPrefix64k.
LZ4_decompress_safe()
int LZ4_decompress_safe (const char * source, char * dest, int compressedSize, int maxDecompressedSize)
Definition at line 1288 of file lz4.c.
References endOnInputSize, full, LZ4_decompress_generic(), and noDict.
LZ4_decompress_safe_continue()
int LZ4_decompress_safe_continue (LZ4_streamDecode_t * LZ4_streamDecode, const char * source, char * dest, int compressedSize, int maxDecompressedSize)
Definition at line 1355 of file lz4.c.
References endOnInputSize, LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, full, LZ4_decompress_generic(), LZ4_streamDecode_t_internal::prefixEnd, LZ4_streamDecode_t_internal::prefixSize, and usingExtDict.
LZ4_decompress_safe_partial()
int LZ4_decompress_safe_partial (const char * source, char * dest, int compressedSize, int targetOutputSize, int maxDecompressedSize)
Definition at line 1293 of file lz4.c.
References endOnInputSize, LZ4_decompress_generic(), noDict, and partial.
LZ4_decompress_safe_usingDict()
int LZ4_decompress_safe_usingDict (const char * source, char * dest, int compressedSize, int maxDecompressedSize, const char * dictStart, int dictSize)
Definition at line 1434 of file lz4.c.
References LZ4_decompress_usingDict_generic().
LZ4_decompress_safe_withPrefix64k()
int LZ4_decompress_safe_withPrefix64k (const char * src, char * dst, int compressedSize, int maxDstSize)
Definition at line 1505 of file lz4.c.
References endOnInputSize, full, KB, LZ4_decompress_generic(), and withPrefix64k.
LZ4_freeStream()
int LZ4_freeStream (LZ4_stream_t * streamPtr)
Definition at line 948 of file lz4.c.
References FREEMEM.
LZ4_freeStreamDecode()
int LZ4_freeStreamDecode (LZ4_streamDecode_t * LZ4_stream)
Definition at line 1325 of file lz4.c.
References FREEMEM.
LZ4_loadDict()
int LZ4_loadDict (LZ4_stream_t * streamPtr, const char * dictionary, int dictSize)
Definition at line 956 of file lz4.c.
References byU32, LZ4_stream_t_internal::currentOffset, LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, GB, HASH_UNIT, LZ4_stream_t_internal::hashTable, LZ4_stream_t_internal::initCheck, KB, LZ4_putPosition(), and LZ4_resetStream().
LZ4_resetStream()
void LZ4_resetStream (LZ4_stream_t * streamPtr)
Definition at line 943 of file lz4.c.
References MEM_INIT.
LZ4_resetStreamState()
int LZ4_resetStreamState (void * state, char * inputBuffer)
Definition at line 1482 of file lz4.c.
References LZ4_init().
LZ4_saveDict()
int LZ4_saveDict (LZ4_stream_t * streamPtr, char * safeBuffer, int dictSize)
Definition at line 1083 of file lz4.c.
References LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, and KB.
LZ4_setStreamDecode()
int LZ4_setStreamDecode (LZ4_streamDecode_t * LZ4_streamDecode, const char * dictionary, int dictSize)
Definition at line 1338 of file lz4.c.
References LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, LZ4_streamDecode_t_internal::prefixEnd, and LZ4_streamDecode_t_internal::prefixSize.
LZ4_sizeofState()
int LZ4_sizeofState (void)
Definition at line 373 of file lz4.c.
References LZ4_STREAMSIZE.
LZ4_sizeofStreamState()
int LZ4_sizeofStreamState (void)
Definition at line 1474 of file lz4.c.
References LZ4_STREAMSIZE.
LZ4_slideInputBuffer()
char * LZ4_slideInputBuffer (void * state)
Definition at line 1496 of file lz4.c.
References LZ4_stream_t_internal::bufferStart, KB, and LZ4_saveDict().
LZ4_versionNumber()
int LZ4_versionNumber (void)
Definition at line 371 of file lz4.c.
References LZ4_VERSION_NUMBER.