ROSS: core/queue/calendar.c File Reference
core/queue/calendar.c File Reference
#include <ross.h>
Data Structures
struct tw_event_head
struct tw_pq
Typedefs
typedef struct tw_event_head tw_event_head
Functions
static tw_event * Delete (tw_pq *p_ptr, int index)
static void Insert (tw_pq *p_ptr, int bucketindex, tw_event *NewE)
static void LocalInit (tw_pq *p_ptr, int qbase, int nbuck, double bwidth, double startprio)
static double NewWidth (tw_pq *p_ptr)
static void ReSize (tw_pq *p_ptr, int)
tw_event * tw_pq_dequeue (tw_pq *p_ptr)
void tw_pq_enqueue (tw_pq *p_ptr, tw_event *NewE)
tw_pq * tw_pq_create (void)
tw_stime tw_pq_minimum (tw_pq *p_ptr)
void tw_pq_delete_any (tw_pq *p_ptr, tw_event *q)
unsigned int tw_pq_get_size (tw_pq *p_ptr)
Variables
static int MAX_EVENTS_PER_PE
Typedef Documentation
typedef struct tw_event_head tw_event_head
Definition at line 3 of file calendar.c.
Function Documentation
static tw_event * Delete (tw_pq * p_ptr, int index) [static]
Definition at line 121 of file calendar.c.
References tw_pq::Bucket, tw_event_head::next, tw_event::next, and tw_event::prev.
Referenced by tw_pq_dequeue().
static void Insert (tw_pq * p_ptr, int bucketindex, tw_event * NewE) [static]
Definition at line 176 of file calendar.c.
References tw_pq::Bucket, tw_event_head::next, tw_event::next, tw_event::prev, and tw_event::recv_ts.
Referenced by tw_pq_enqueue().
static void LocalInit (tw_pq * p_ptr, int qbase, int nbuck, double bwidth, double startprio) [static]
Definition at line 217 of file calendar.c.
References tw_pq::BottomThreshold, tw_pq::Bucket, tw_pq::BucketTop, tw_pq::FirstSub, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Nbuckets, tw_event_head::next, tw_pq::OrigBucket, tw_pq::Qsize, tw_pq::TopThreshold, and tw_pq::Width.
Referenced by ReSize(), and tw_pq_create().
static double NewWidth (tw_pq * p_ptr) [static]
Definition at line 253 of file calendar.c.
References tw_pq::BucketTop, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Qsize, tw_event::recv_ts, tw_pq::ResizeEnabled, tw_pq_dequeue(), and tw_pq_enqueue().
Referenced by ReSize().
static void ReSize (tw_pq * p_ptr, int newsize) [static]
Definition at line 333 of file calendar.c.
References tw_pq::Bucket, tw_pq::FirstSub, tw_pq::LastPriority, LocalInit(), MAX_EVENTS_PER_PE, tw_pq::Nbuckets, NewWidth(), tw_event_head::next, tw_event_head::prev, tw_event::prev, tw_pq::ResizeEnabled, and tw_pq_enqueue().
Referenced by tw_pq_dequeue(), and tw_pq_enqueue().
tw_pq* tw_pq_create (void)
Definition at line 425 of file calendar.c.
Referenced by setup_pes().
void tw_pq_delete_any (tw_pq * p_ptr, tw_event * q)
Definition at line 542 of file calendar.c.
Referenced by event_cancel(), and tw_sched_cancel_q().
tw_event* tw_pq_dequeue (tw_pq * p_ptr)
Definition at line 40 of file calendar.c.
Referenced by NewWidth(), tw_pq_delete_any(), tw_sched_batch(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), and tw_scheduler_sequential().
void tw_pq_enqueue (tw_pq * p_ptr, tw_event * NewE)
Definition at line 142 of file calendar.c.
Referenced by NewWidth(), recv_finish(), ReSize(), tw_event_send(), tw_kp_rollback_event(), tw_kp_rollback_to(), tw_sched_batch(), and tw_sched_event_q().
unsigned int tw_pq_get_size (tw_pq * p_ptr)
Definition at line 555 of file calendar.c.
Referenced by tw_stats().
tw_stime tw_pq_minimum (tw_pq * p_ptr)
Definition at line 486 of file calendar.c.
Referenced by tw_gvt_compute(), tw_gvt_step2(), tw_sched_batch(), tw_scheduler_conservative(), and tw_scheduler_sequential().
Variable Documentation
int MAX_EVENTS_PER_PE [static]
Definition at line 15 of file calendar.c.
Referenced by ReSize(), and tw_pq_create().