ROSS: ross/clock-amd64.h File Reference
clock-amd64.h File Reference
Typedefs
typedef uint64_t tw_clock
Functions
static tw_clock tw_clock_read (void)
Typedef Documentation
typedef uint64_t tw_clock
Definition at line 4 of file clock-amd64.h.
Function Documentation
static tw_clock tw_clock_read (void) inline static
Definition at line 6 of file clock-amd64.h.
References d.
Referenced by tw_clock_init(), tw_clock_now(), tw_gvt_step2(), tw_hash_insert(), tw_hash_remove(), tw_sched_batch(), tw_sched_cancel_q(), tw_sched_event_q(), tw_scheduler_conservative(), and tw_scheduler_optimistic().