ROSS: core/ross-gvt-internal.h File Reference
ross-gvt-internal.h File Reference
#include "ross-types.h"
#include "tw-opts.h"
#include "stdbool.h"
Data Structures
struct gvt_hook_trigger
Enumerations
enum GVT_HOOK_STATUS { GVT_HOOK_STATUS_disabled = 0 , GVT_HOOK_STATUS_timestamp , GVT_HOOK_STATUS_every_n_gvt , GVT_HOOK_STATUS_model_call }
Functions
const tw_optdef * tw_gvt_setup (void)
void tw_gvt_start (void)
void tw_gvt_finish (void)
void tw_gvt_step1 (tw_pe *)
void tw_gvt_step1_realtime (tw_pe *)
void tw_gvt_step2 (tw_pe *)
void tw_gvt_force_update (void)
void tw_gvt_force_update_realtime (void)
int tw_gvt_set (tw_pe *pe, tw_stime LVT)
static int tw_gvt_inprogress (tw_pe *pe)
void tw_gvt_stats (FILE *F)
void tw_trigger_gvt_hook_at (tw_stime time)
void tw_trigger_gvt_hook_every (int num_gvt_calls)
void tw_trigger_gvt_hook_when_model_calls (void)
void tw_trigger_gvt_hook_now (tw_lp *)
void tw_trigger_gvt_hook_now_rev (tw_lp *)
Variables
void(* g_tw_gvt_hook)(tw_pe *pe, bool is_queue_empty)
struct gvt_hook_trigger g_tw_gvt_hook_trigger
Enumeration Type Documentation
GVT_HOOK_STATUS
enum GVT_HOOK_STATUS
Enumerator
GVT_HOOK_STATUS_disabled
GVT_HOOK_STATUS_timestamp
GVT_HOOK_STATUS_every_n_gvt
GVT_HOOK_STATUS_model_call
Definition at line 76 of file ross-gvt-internal.h.
Function Documentation
tw_gvt_finish()
void tw_gvt_finish (void) extern
Definition at line 89 of file mpi_allreduce.c.
tw_gvt_force_update()
void tw_gvt_force_update (void) extern
Definition at line 98 of file mpi_allreduce.c.
tw_gvt_force_update_realtime()
void tw_gvt_force_update_realtime (void) extern
Definition at line 105 of file mpi_allreduce.c.
tw_gvt_inprogress()
int tw_gvt_inprogress (tw_pe * pe) inline static
References g_tw_gvt_hook, and pe.
tw_gvt_set()
int tw_gvt_set (tw_pe * pe, tw_stime LVT) extern
References pe.
tw_gvt_setup()
const tw_optdef * tw_gvt_setup (void) extern
Definition at line 61 of file mpi_allreduce.c.
tw_gvt_start()
void tw_gvt_start (void) extern
Definition at line 69 of file mpi_allreduce.c.
tw_gvt_stats()
void tw_gvt_stats (FILE * F) extern
Definition at line 112 of file mpi_allreduce.c.
tw_gvt_step1()
void tw_gvt_step1 (tw_pe * me) extern
Definition at line 141 of file mpi_allreduce.c.
tw_gvt_step1_realtime()
void tw_gvt_step1_realtime (tw_pe * me) extern
Definition at line 156 of file mpi_allreduce.c.
tw_gvt_step2()
void tw_gvt_step2 (tw_pe * me) extern
Definition at line 325 of file mpi_allreduce.c.
tw_trigger_gvt_hook_at()
void tw_trigger_gvt_hook_at (tw_stime time)
Definition at line 488 of file mpi_allreduce.c.
tw_trigger_gvt_hook_every()
void tw_trigger_gvt_hook_every (int num_gvt_calls)
Definition at line 514 of file mpi_allreduce.c.
tw_trigger_gvt_hook_now()
void tw_trigger_gvt_hook_now (tw_lp * lp)
Definition at line 529 of file mpi_allreduce.c.
References CONSERVATIVE, g_tw_gvt_hook_trigger, g_tw_synchronization_protocol, GVT_HOOK_STATUS_model_call, tw_pe::gvt_status, tw_lp::kp, tw_kp::last_sig, OPTIMISTIC_DEBUG, tw_lp::pe, tw_lp::triggered_gvt_hook, tw_copy_event_sig(), tw_error(), TW_GVT_COMPUTE, and TW_LOC.
Referenced by phold_event_handler().
tw_trigger_gvt_hook_now_rev()
void tw_trigger_gvt_hook_now_rev (tw_lp * lp)
Definition at line 544 of file mpi_allreduce.c.
References g_tw_gvt_hook_trigger, g_tw_max_sig, tw_lp::triggered_gvt_hook, and tw_copy_event_sig().
Referenced by phold_event_handler_rc().
tw_trigger_gvt_hook_when_model_calls()
void tw_trigger_gvt_hook_when_model_calls (void)
Definition at line 523 of file mpi_allreduce.c.
References g_tw_gvt_hook_trigger, g_tw_max_sig, GVT_HOOK_STATUS_model_call, and tw_copy_event_sig().
Referenced by main().
Variable Documentation
g_tw_gvt_hook
void(* g_tw_gvt_hook) (tw_pe *pe, bool is_queue_empty) (tw_pe * pe, bool is_queue_empty) extern
Definition at line 12 of file mpi_allreduce.c.
g_tw_gvt_hook_trigger
struct gvt_hook_trigger g_tw_gvt_hook_trigger extern
Definition at line 14 of file mpi_allreduce.c.