ROSS: core/ross-random-internal.h File Reference
ross-random-internal.h File Reference
#include "ross-base.h"
Macros
#define tw_opi 6.28318530718
#define tw_rand_unif(G)
#define tw_rand_reverse_unif(G)
Functions
tw_rng * tw_rand_init (uint32_t v, uint32_t w)
tw_rng * tw_rand_core_init (uint32_t v, uint32_t w)
void tw_rand_initial_seed (tw_rng_stream *g, tw_lpid id, tw_rng *the_rng)
long tw_rand_integer (tw_rng_stream *g, long low, long high)
unsigned long tw_rand_ulong (tw_rng_stream *g, unsigned long low, unsigned long high)
long tw_rand_binomial (tw_rng_stream *g, long N, double P)
double tw_rand_exponential (tw_rng_stream *g, double Lambda)
double tw_rand_pareto (tw_rng_stream *g, double scale, double shape)
double tw_rand_gamma (tw_rng_stream *g, double shape, double scale)
long tw_rand_geometric (tw_rng_stream *g, double P)
double tw_rand_normal01 (tw_rng_stream *g, unsigned int *rng_calls)
double tw_rand_normal_sd (tw_rng_stream *g, double Mu, double Sd, unsigned int *rng_calls)
long tw_rand_poisson (tw_rng_stream *g, double Lambda)
double tw_rand_weibull (tw_rng_stream *g, double mean, double shape)
Macro Definition Documentation
tw_opi
#define tw_opi 6.28318530718
Definition at line 6 of file ross-random-internal.h.
tw_rand_reverse_unif
#define tw_rand_reverse_unif (G)
Value:
rng_gen_reverse_val(G)
Definition at line 8 of file ross-random-internal.h.
tw_rand_unif
#define tw_rand_unif (G)
Value:
rng_gen_val(G)
Definition at line 7 of file ross-random-internal.h.
Function Documentation
tw_rand_binomial()
long tw_rand_binomial (tw_rng_stream * g, long N, double P) extern
Definition at line 62 of file ross-random-internal.c.
tw_rand_core_init()
tw_rng * tw_rand_core_init (uint32_t v, uint32_t w) extern
Definition at line 16 of file ross-random-internal.c.
tw_rand_exponential()
double tw_rand_exponential (tw_rng_stream * g, double Lambda) extern
Definition at line 78 of file ross-random-internal.c.
Referenced by tw_rand_gamma().
tw_rand_gamma()
double tw_rand_gamma (tw_rng_stream * g, double shape, double scale) extern
Definition at line 90 of file ross-random-internal.c.
tw_rand_geometric()
long tw_rand_geometric (tw_rng_stream * g, double P) extern
Definition at line 150 of file ross-random-internal.c.
tw_rand_init()
tw_rng * tw_rand_init (uint32_t v, uint32_t w) extern
Definition at line 7 of file ross-random-internal.c.
tw_rand_initial_seed()
void tw_rand_initial_seed (tw_rng_stream * g, tw_lpid id, tw_rng * the_rng) extern
Definition at line 268 of file rand-clcg4.c.
Referenced by tw_rand_init_streams().
tw_rand_integer()
long tw_rand_integer (tw_rng_stream * g, long low, long high) extern
NOTE: Don't pass negative values to low!
Definition at line 30 of file ross-random-internal.c.
tw_rand_normal01()
double tw_rand_normal01 (tw_rng_stream * g, unsigned int * rng_calls) extern
Definition at line 161 of file ross-random-internal.c.
Referenced by tw_rand_lognormal(), and tw_rand_normal_sd().
tw_rand_normal_sd()
double tw_rand_normal_sd (tw_rng_stream * g, double Mu, double Sd, unsigned int * rng_calls) extern
Definition at line 191 of file ross-random-internal.c.
tw_rand_pareto()
double tw_rand_pareto (tw_rng_stream * g, double scale, double shape) extern
Definition at line 84 of file ross-random-internal.c.
tw_rand_poisson()
long tw_rand_poisson (tw_rng_stream * g, double Lambda) extern
Definition at line 197 of file ross-random-internal.c.
tw_rand_ulong()
unsigned long tw_rand_ulong (tw_rng_stream * g, unsigned long low, unsigned long high) extern
Definition at line 46 of file ross-random-internal.c.
tw_rand_weibull()
double tw_rand_weibull (tw_rng_stream * g, double mean, double shape) extern
Definition at line 224 of file ross-random-internal.c.