ROSS: core/check-revent/crv-state.c File Reference
crv-state.c File Reference
#include "ross.h"
Data Structures
struct llist_chptr
Functions
void crv_add_custom_state_checkpoint (crv_checkpointer *state_checkpoint)
static void crv_clean_linkedlist (void)
size_t crv_init_checkpoints (void)
static crv_checkpointer * get_chkpntr (tw_lpid id)
static void print_event (crv_checkpointer const *chkptr, tw_lp *clp, tw_event *cev)
void crv_check_lpstates (tw_lp *clp, tw_event *cev, crv_lpstate_checkpoint_internal const *before_state, char const *before_msg, char const *after_msg)
void crv_copy_lpstate (crv_lpstate_checkpoint_internal *into, tw_lp const *clp)
void crv_clean_lpstate (crv_lpstate_checkpoint_internal *state, tw_lp const *clp)
Variables
struct llist_chptr * head_linked_list = NULL
struct llist_chptr * tail_linked_list = NULL
struct crv_checkpointer ** checkpointer_for_lps = NULL
Function Documentation
crv_add_custom_state_checkpoint()
void crv_add_custom_state_checkpoint (crv_checkpointer * state_checkpoint)
Definition at line 14 of file crv-state.c.
References head_linked_list, llist_chptr::next, tail_linked_list, tw_error(), TW_LOC, and llist_chptr::val.
Referenced by main().
crv_check_lpstates()
void crv_check_lpstates (tw_lp * clp, tw_event * cev, crv_lpstate_checkpoint_internal const * before_state, char const * before_msg, char const * after_msg)
Definition at line 105 of file crv-state.c.
References crv_checkpointer::check_lps, crv_lpstate_checkpoint_internal::core_rng, tw_lp::core_rng, tw_lp::cur_state, get_chkpntr(), tw_lp::gid, tw_lp::id, crv_checkpointer::print_checkpoint, print_event(), crv_checkpointer::print_lp, crv_lpstate_checkpoint_internal::rng, tw_lp::rng, crv_lpstate_checkpoint_internal::state, tw_lptype::state_sz, crv_lpstate_checkpoint_internal::triggered_gvt_hook, tw_lp::triggered_gvt_hook, tw_fprint_binary_array(), tw_net_abort(), and tw_lp::type.
Referenced by tw_scheduler_sequential_rollback_check().
crv_clean_linkedlist()
void crv_clean_linkedlist (void) static
Definition at line 30 of file crv-state.c.
References head_linked_list, llist_chptr::next, and tail_linked_list.
Referenced by crv_init_checkpoints().
crv_clean_lpstate()
void crv_clean_lpstate (crv_lpstate_checkpoint_internal * state, tw_lp const * clp)
Definition at line 189 of file crv-state.c.
References crv_checkpointer::clean_lp, get_chkpntr(), tw_lp::id, and crv_lpstate_checkpoint_internal::state.
Referenced by tw_scheduler_sequential_rollback_check().
crv_copy_lpstate()
void crv_copy_lpstate (crv_lpstate_checkpoint_internal * into, tw_lp const * clp)
Definition at line 176 of file crv-state.c.
References crv_lpstate_checkpoint_internal::core_rng, tw_lp::core_rng, tw_lp::cur_state, get_chkpntr(), tw_lp::id, crv_lpstate_checkpoint_internal::rng, tw_lp::rng, crv_checkpointer::save_lp, crv_lpstate_checkpoint_internal::state, tw_lptype::state_sz, crv_lpstate_checkpoint_internal::triggered_gvt_hook, tw_lp::triggered_gvt_hook, and tw_lp::type.
Referenced by tw_scheduler_sequential_rollback_check().
crv_init_checkpoints()
size_t crv_init_checkpoints (void)
Definition at line 47 of file crv-state.c.
References checkpointer_for_lps, crv_clean_linkedlist(), g_tw_lp, g_tw_nlp, head_linked_list, crv_checkpointer::sz_storage, and tw_lp::type.
Referenced by tw_scheduler_sequential_rollback_check().
get_chkpntr()
crv_checkpointer * get_chkpntr (tw_lpid id) static
Definition at line 81 of file crv-state.c.
References checkpointer_for_lps.
Referenced by crv_check_lpstates(), crv_clean_lpstate(), and crv_copy_lpstate().
print_event()
void print_event (crv_checkpointer const * chkptr, tw_lp * clp, tw_event * cev) static
Definition at line 88 of file crv-state.c.
References tw_bf::c0, tw_bf::c1, tw_bf::c10, tw_bf::c11, tw_bf::c12, tw_bf::c13, tw_bf::c14, tw_bf::c15, tw_bf::c16, tw_bf::c17, tw_bf::c18, tw_bf::c19, tw_bf::c2, tw_bf::c20, tw_bf::c21, tw_bf::c22, tw_bf::c23, tw_bf::c24, tw_bf::c25, tw_bf::c26, tw_bf::c27, tw_bf::c28, tw_bf::c29, tw_bf::c3, tw_bf::c30, tw_bf::c31, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c8, tw_bf::c9, tw_lp::cur_state, tw_event::cv, g_tw_msg_sz, crv_checkpointer::print_event, tw_event_data(), and tw_fprint_binary_array().
Referenced by crv_check_lpstates(), and main().
Variable Documentation
checkpointer_for_lps
struct crv_checkpointer** checkpointer_for_lps = NULL
Definition at line 12 of file crv-state.c.
Referenced by crv_init_checkpoints(), and get_chkpntr().
head_linked_list
struct llist_chptr* head_linked_list = NULL
Definition at line 9 of file crv-state.c.
Referenced by crv_add_custom_state_checkpoint(), crv_clean_linkedlist(), and crv_init_checkpoints().
tail_linked_list
struct llist_chptr* tail_linked_list = NULL
Definition at line 10 of file crv-state.c.
Referenced by crv_add_custom_state_checkpoint(), and crv_clean_linkedlist().