ROSS: ross/models/disksim/disksim.c File Reference
disksim.c File Reference
#include "disksim.h"
Functions
tw_peid disksim_map (tw_lpid gid)
void disksim_ras_init (disksim_ras_state *s, tw_lp *lp)
void disksim_ras_event_handler (disksim_ras_state *s, tw_bf *bf, disksim_message *m, tw_lp *lp)
void disksim_ras_event_handler_rc (disksim_ras_state *s, tw_bf *bf, disksim_message *m, tw_lp *lp)
void disksim_ras_finish (disksim_ras_state *s, tw_lp *lp)
void disksim_init (disksim_state *s, tw_lp *lp)
void disksim_event_handler (disksim_state *s, tw_bf *bf, disksim_message *m, tw_lp *lp)
void disksim_event_handler_rc (disksim_state *s, tw_bf *bf, disksim_message *m, tw_lp *lp)
void disksim_finish (disksim_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
void disksim_event_handler (disksim_state * s, tw_bf * bf, disksim_message * m, tw_lp * lp)
Definition at line 78 of file disksim.c.
References tw_bf::c0, disksim_message::disk_that_failed, disksim_distribution, disksim_map(), g_tw_nlp, tw_lp::gid, MAX_HOURS, MTTF, disksim_state::number_of_failures, tw_lp::rng, disksim_message::time_of_failure, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_weibull().
Referenced by disksim_init().
void disksim_event_handler_rc (disksim_state * s, tw_bf * bf, disksim_message * m, tw_lp * lp)
Definition at line 139 of file disksim.c.
References tw_bf::c0, disksim_state::number_of_failures, tw_lp::rng, and tw_rand_reverse_unif.
void disksim_finish (disksim_state * s, tw_lp * lp)
Definition at line 146 of file disksim.c.
void disksim_init (disksim_state * s, tw_lp * lp)
Definition at line 72 of file disksim.c.
References disksim_event_handler().
tw_peid disksim_map (tw_lpid gid)
Definition at line 33 of file disksim.c.
References g_tw_nlp.
Referenced by disksim_event_handler().
void disksim_ras_event_handler (disksim_ras_state * s, tw_bf * bf, disksim_message * m, tw_lp * lp)
Definition at line 45 of file disksim.c.
References disksim_ras_state::disk_failure_per_hour, MAX_HOURS, and disksim_message::time_of_failure.
void disksim_ras_event_handler_rc (disksim_ras_state * s, tw_bf * bf, disksim_message * m, tw_lp * lp)
Definition at line 51 of file disksim.c.
References disksim_ras_state::disk_failure_per_hour, MAX_HOURS, and disksim_message::time_of_failure.
void disksim_ras_finish (disksim_ras_state * s, tw_lp * lp)
Definition at line 57 of file disksim.c.
References disksim_ras_state::disk_failure_per_hour, tw_lp::gid, and MAX_HOURS.
void disksim_ras_init (disksim_ras_state * s, tw_lp * lp)
Definition at line 38 of file disksim.c.
References disksim_ras_state::disk_failure_per_hour, and MAX_HOURS.
int main (int argc, char ** argv, char ** env)
Definition at line 167 of file disksim.c.
References g_disksim_start_events, g_tw_events_per_pe, g_tw_lookahead, g_tw_memory_nqueues, g_tw_mynode, g_tw_nlp, g_tw_npe, lookahead, mult, nlp_per_pe, offset_lpid, optimistic_memory, ttl_lps, tw_define_lps(), tw_end(), tw_init(), tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("DISKSIM Model"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of Disk LPs per processor"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_STIME("lookahead", lookahead, "lookahead for events"),
        TWOPT_UINT("start-events", g_disksim_start_events, "number of initial messages per LP"),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 153 of file disksim.c.
tw_lptype mylps[]
Initial value:
=
  {
    {(init_f) disksim_ras_init,
     (event_f) disksim_ras_event_handler,
     (revent_f) disksim_ras_event_handler_rc,
     (final_f) disksim_ras_finish,
     (map_f) disksim_map,
     sizeof(disksim_ras_state)},
    {(init_f) disksim_init,
     (event_f) disksim_event_handler,
     (revent_f) disksim_event_handler_rc,
     (final_f) disksim_finish,
     (map_f) disksim_map,
     sizeof(disksim_state)},
    {0},
}
Definition at line 15 of file disksim.c.