ROSS: ross/models/civilian_power/dissim-main.c File Reference
dissim-main.c File Reference
#include "civilian.h"
#include "powerline.h"
#include "substation.h"
#include "generator.h"
#include "building.h"
#include "dissim-main.h"
#include <stdio.h>
#include <stdlib.h>
Functions
tw_peid mapping (tw_lpid gid)
void init (Dissim_State *d, tw_lp *lp)
void event_handler (Dissim_State *d, tw_bf *bf, Msg_Data *msg, tw_lp *lp)
void rc_event_handler (Dissim_State *d, tw_bf *bf, Msg_Data *msg, tw_lp *lp)
void final (Dissim_State *d, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype disaster_lps []
const tw_optdef app_opt []
Function Documentation
void event_handler (Dissim_State * d, tw_bf * bf, Msg_Data * msg, tw_lp * lp)
Definition at line 348 of file dissim-main.c.
References Powerline_State::available, Generator_State::available, Substation_State::available, Dissim_State::b, BUILDING, Dissim_State::c, tw_bf::c1, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, Building_State::capacity, CIVILIAN, Civilian_State::CrisisLevel, CRISISLEVELFALLS, CRISISLEVELRISES, Civilian_State::CrisisLevelStart, CURIOUS, Civilian_State::curTravelNode, DAMAGE, Dissim_State::dissimType, Powerline_State::draw, Generator_State::draw, Substation_State::draw, Building_State::draw, Civilian_State::escapeLength, Civilian_State::escapePath, Civilian_State::evacuated, Msg_Data::event_type, Civilian_State::familyPresent, Civilian_State::familySize, Dissim_State::g, GENERATOR, tw_lp::gid, Building_State::hasPower, Powerline_State::health, Generator_State::health, Substation_State::health, Building_State::health, Civilian_State::health, HOME, Civilian_State::Home, Civilian_State::homeID, Civilian_State::homeLength, Civilian_State::homePath, Civilian_State::homePowerUsage, HOSPITAL, Civilian_State::Hospital, Civilian_State::hospitalID, Civilian_State::hospitalLength, Civilian_State::hospitalPath, Civilian_State::hospitalPowerUsage, Msg_Data::InfoBlock1, Msg_Data::InfoBlock2, Generator_State::jumpArrayLength, LEISURE, Civilian_State::Leisure, Civilian_State::leisureID, Civilian_State::leisureLength, Civilian_State::leisurePath, Civilian_State::leisurePowerUsage, Civilian_State::MyCoordsX, Civilian_State::MyCoordsY, Substation_State::nextIDEnd, Powerline_State::nextJumpID, Substation_State::nextJumpIDs, Generator_State::nextJumpIDs, Building_State::occupancy, Building_State::occupantPresent, Building_State::occupants, Dissim_State::p, POWERLINE, Building_State::powerlineServicing, POWEROFF, POWERON, Powerline_State::prevJumpID, Substation_State::prevJumpID, RELEASEHOME, RELEASEHOSPITAL, RELEASELEISURE, RELEASEWORK, REPAIR, tw_lp::rng, Dissim_State::s, Civilian_State::Stubbornness, SUBSTATION, Civilian_State::TimeInCrisisLevel, TRAVELEVACUATE, TRAVELHOME, TRAVELHOSPITAL, Civilian_State::Traveling, TRAVELLEISURE, TRAVELWORK, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_reverse_unif, tw_rand_unif, UPDATEAVAILABLE, UPDATEDRAW, UPDATEOCCUPANCY, WORK, Civilian_State::workID, Civilian_State::Working, Civilian_State::workLength, Civilian_State::workPath, and Civilian_State::workPowerUsage.
void final (Dissim_State * d, tw_lp * lp)
Definition at line 1702 of file dissim-main.c.
void init (Dissim_State * d, tw_lp * lp)
Definition at line 20 of file dissim-main.c.
References A, Powerline_State::available, Generator_State::available, Substation_State::available, Dissim_State::b, BUILDING, Dissim_State::c, Building_State::capacity, CIVILIAN, Civilian_State::CrisisLevel, CRISISLEVELRISES, DAMAGE, Dissim_State::dissimType, Powerline_State::draw, Generator_State::draw, Substation_State::draw, Building_State::draw, Civilian_State::escapeLength, Civilian_State::escapePath, Civilian_State::evacuated, Msg_Data::event_type, Civilian_State::familyPresent, Civilian_State::familySize, Dissim_State::g, GENERATOR, tw_lp::gid, Building_State::hasPower, Powerline_State::health, Generator_State::health, Substation_State::health, Building_State::health, Civilian_State::Home, Civilian_State::HomeCoordsX, Civilian_State::HomeCoordsY, Civilian_State::homeID, Civilian_State::homeLength, Civilian_State::homePath, Civilian_State::homePowerUsage, Civilian_State::hospitalLength, Civilian_State::hospitalPath, Civilian_State::hospitalPowerUsage, Msg_Data::InfoBlock1, Generator_State::jumpArrayLength, Civilian_State::Leisure, Civilian_State::leisureLength, Civilian_State::leisurePath, Civilian_State::leisurePowerUsage, Civilian_State::Money, Building_State::MyCoordsX, Substation_State::MyCoordsX, Generator_State::MyCoordsX, Powerline_State::MyCoordsX, Civilian_State::MyCoordsX, Building_State::MyCoordsY, Substation_State::MyCoordsY, Generator_State::MyCoordsY, Powerline_State::MyCoordsY, Civilian_State::MyCoordsY, Substation_State::nextIDEnd, Powerline_State::nextJumpID, Substation_State::nextJumpIDs, Generator_State::nextJumpIDs, Building_State::occupancy, Building_State::occupantPresent, Building_State::occupants, Dissim_State::p, POWERLINE, Building_State::powerlineServicing, Substation_State::prevJumpID, Powerline_State::prevJumpID, RELEASEHOME, tw_lp::rng, Dissim_State::s, Civilian_State::Stubbornness, SUBSTATION, Civilian_State::Traveling, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), UPDATEAVAILABLE, UPDATEDRAW, Civilian_State::workID, Civilian_State::Working, Civilian_State::workLength, Civilian_State::workPath, and Civilian_State::workPowerUsage.
int main (int argc, char ** argv, char ** env)
Definition at line 1729 of file dissim-main.c.
References g_tw_events_per_pe, g_tw_nlp, g_tw_npe, nlp_per_pe, opt_mem, planes_per_airport, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_lp_settype(), tw_nnodes(), and tw_run().
tw_peid mapping (tw_lpid gid)
Definition at line 14 of file dissim-main.c.
References g_tw_nlp.
void rc_event_handler (Dissim_State * d, tw_bf * bf, Msg_Data * msg, tw_lp * lp)
Definition at line 1198 of file dissim-main.c.
References Powerline_State::available, Generator_State::available, Substation_State::available, Dissim_State::b, BUILDING, Dissim_State::c, tw_bf::c1, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, CIVILIAN, Civilian_State::CrisisLevel, CRISISLEVELFALLS, CRISISLEVELRISES, Civilian_State::CrisisLevelStart, CURIOUS, Civilian_State::curTravelNode, DAMAGE, Dissim_State::dissimType, Powerline_State::draw, Generator_State::draw, Substation_State::draw, Building_State::draw, Civilian_State::escapePath, Civilian_State::evacuated, Msg_Data::event_type, Civilian_State::familyPresent, Dissim_State::g, GENERATOR, Building_State::hasPower, Powerline_State::health, Generator_State::health, Substation_State::health, Building_State::health, Civilian_State::health, HOME, Civilian_State::Home, Civilian_State::homePath, HOSPITAL, Civilian_State::Hospital, Civilian_State::hospitalPath, Msg_Data::InfoBlock1, Msg_Data::InfoBlock2, Generator_State::jumpArrayLength, LEISURE, Civilian_State::Leisure, Civilian_State::leisurePath, Civilian_State::MyCoordsX, Civilian_State::MyCoordsY, Substation_State::nextIDEnd, Building_State::occupancy, Building_State::occupantPresent, Building_State::occupants, Dissim_State::p, POWERLINE, POWEROFF, POWERON, RELEASEHOME, RELEASEHOSPITAL, RELEASELEISURE, RELEASEWORK, REPAIR, tw_lp::rng, Dissim_State::s, SUBSTATION, Civilian_State::TimeInCrisisLevel, TRAVELEVACUATE, TRAVELHOME, TRAVELHOSPITAL, Civilian_State::Traveling, TRAVELLEISURE, TRAVELWORK, tw_rand_reverse_unif, UPDATEAVAILABLE, UPDATEDRAW, UPDATEOCCUPANCY, WORK, Civilian_State::Working, and Civilian_State::workPath.
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
 {
         TWOPT_GROUP("Civilian Model"),
 }
Definition at line 1718 of file dissim-main.c.
tw_lptype disaster_lps[]
Initial value:
=
 {
         {
                 (init_f) init,
                 (event_f) event_handler,
                 (revent_f) rc_event_handler,
                 (final_f) final,
                 (map_f) mapping,
                 sizeof(Dissim_State),
         },
         {0},
 }
Definition at line 1706 of file dissim-main.c.