ROSS: ross/models/dragonfly/dragonfly.c File Reference
dragonfly.c File Reference
#include "dragonfly.h"
Functions
int get_terminal_rem ()
int get_router_rem ()
int get_inv_router_rem ()
int getTerminalID (tw_lpid lpid)
int getProcID (tw_lpid lpid)
int getRouterID (tw_lpid terminal_id)
tw_peid mapping (tw_lpid gid)
tw_lpid getRouterFromGroupID (int gid, router_state *r)
void mpi_init (process_state *s, tw_lp *lp)
void mpi_msg_send (process_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void mpi_msg_recv (process_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void mpi_event (process_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void router_credit_send (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void packet_generate (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void packet_send (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void packet_arrive (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void packet_finish (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void waiting_terminal_packet_free (terminal_state *s, int loc)
void update_terminal_waiting_list (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void schedule_terminal_waiting_msg (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void terminal_init (terminal_state *s, tw_lp *lp)
void terminal_buf_update (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void terminal_event (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void final (terminal_state *s, tw_lp *lp)
void router_reschedule_event (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
tw_lpid get_next_stop (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp, int path)
int get_output_port (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp, int next_stop)
void router_packet_send (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void router_packet_receive (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void router_setup (router_state *r, tw_lp *lp)
void update_router_waiting_list (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void waiting_router_packet_free (router_state *s, int loc)
void schedule_router_waiting_msg (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp, int chan)
void router_buf_update (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void router_event (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void terminal_rc_event_handler (terminal_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void router_rc_event_handler (router_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
void mpi_rc_event_handler (process_state *s, tw_bf *bf, terminal_message *msg, tw_lp *lp)
tw_lp * dragonfly_mapping_to_lp (tw_lpid lpid)
void dragonfly_mapping (void)
int main (int argc, char **argv)
Variables
FILE * dragonfly_event_log =NULL
tw_lptype dragonfly_lps []
const tw_optdef app_opt []
Function Documentation
void dragonfly_mapping (void)
Definition at line 1545 of file dragonfly.c.
References g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nkp, g_tw_npe, g_tw_pe, get_router_rem(), get_terminal_rem(), nkp_per_pe, nlp_mpi_procs_per_pe, nlp_router_per_pe, nlp_terminal_per_pe, pe, total_routers, total_terminals, tw_getpe(), tw_kp_onpe(), tw_lp_onkp(), tw_lp_onpe(), and tw_lp_settype().
Referenced by main().
tw_lp* dragonfly_mapping_to_lp (tw_lpid lpid)
Definition at line 1530 of file dragonfly.c.
References g_tw_lp, g_tw_mynode, get_router_rem(), get_terminal_rem(), nlp_mpi_procs_per_pe, nlp_router_per_pe, nlp_terminal_per_pe, total_routers, and total_terminals.
Referenced by main().
void final (terminal_state * s, tw_lp * lp)
Definition at line 780 of file dragonfly.c.
int get_inv_router_rem ()
Definition at line 29 of file dragonfly.c.
References g_tw_mynode, and router_rem.
tw_lpid get_next_stop (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp, int path)
Definition at line 820 of file dragonfly.c.
References tw_bf::c2, terminal_message::dest_terminal_id, getRouterFromGroupID(), getRouterID(), tw_lp::gid, router_state::global_channel, GLOBAL_CHANNELS, router_state::group_id, terminal_message::intm_group_id, terminal_message::last_hop, NON_MINIMAL, num_groups, NUM_ROUTER, tw_lp::rng, TERMINAL, and tw_rand_integer().
Referenced by router_packet_send().
int get_output_port (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp, int next_stop)
Definition at line 882 of file dragonfly.c.
References terminal_message::dest_terminal_id, getTerminalID(), router_state::global_channel, GLOBAL_CHANNELS, router_state::group_id, NUM_ROUTER, and NUM_TERMINALS.
Referenced by router_packet_send().
int get_router_rem ()
Definition at line 20 of file dragonfly.c.
References g_tw_mynode, and router_rem.
Referenced by dragonfly_mapping(), and dragonfly_mapping_to_lp().
int get_terminal_rem ()
Definition at line 11 of file dragonfly.c.
References g_tw_mynode, and terminal_rem.
Referenced by dragonfly_mapping(), and dragonfly_mapping_to_lp().
int getProcID (tw_lpid lpid)
Definition at line 43 of file dragonfly.c.
References total_routers, and total_terminals.
Referenced by mapping(), mpi_init(), and mpi_msg_send().
tw_lpid getRouterFromGroupID (int gid, router_state * r)
Definition at line 123 of file dragonfly.c.
References GLOBAL_CHANNELS, router_state::group_id, and NUM_ROUTER.
Referenced by get_next_stop().
int getRouterID (tw_lpid terminal_id)
Definition at line 49 of file dragonfly.c.
References getTerminalID(), and NUM_TERMINALS.
Referenced by get_next_stop(), router_packet_send(), and terminal_init().
int getTerminalID (tw_lpid lpid)
Definition at line 37 of file dragonfly.c.
References total_routers.
Referenced by get_output_port(), getRouterID(), and mapping().
int main (int argc, char ** argv)
Definition at line 1605 of file dragonfly.c.
References ADAPTIVE, CHUNK_SIZE, CUSTOM, dragonfly_event_log, dragonfly_mapping(), dragonfly_mapping_to_lp(), g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_mapping, g_tw_mynode, g_tw_nlp, g_tw_npe, g_tw_ts_end, INJECTION_INTERVAL, max_latency, max_packets, MEAN_INTERVAL, mem_factor, MESSAGE_SIZE, minimal_count, N_COLLECT_POINTS, N_finished, N_finished_storage, N_generated_storage, nlp_mpi_procs_per_pe, nlp_router_per_pe, nlp_terminal_per_pe, nonmin_count, num_chunks, num_groups, num_packets, NUM_ROUTER, NUM_TERMINALS, opt_mem, packet_offset, PACKET_SIZE, range_start, router_rem, ROUTING, terminal_rem, total_hops, total_mpi_procs, total_routers, total_terminals, total_time, tw_define_lps(), tw_end(), tw_error(), tw_init(), tw_ismaster(), TW_LOC, tw_nnodes(), tw_opt_add(), and tw_run().
tw_peid mapping (tw_lpid gid)
Definition at line 57 of file dragonfly.c.
References g_tw_mynode, getProcID(), getTerminalID(), N_nodes, nlp_mpi_procs_per_pe, nlp_per_pe, nlp_router_per_pe, nlp_terminal_per_pe, router_rem, terminal_rem, total_mpi_procs, total_routers, total_terminals, and tw_nnodes().
void mpi_event (process_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 347 of file dragonfly.c.
References mpi_msg_recv(), mpi_msg_send(), MPI_RECV, MPI_SEND, and terminal_message::type.
void mpi_init (process_state * s, tw_lp * lp)
Start a GENERATE event on each LP
Definition at line 153 of file dragonfly.c.
References process_state::col, getProcID(), tw_lp::gid, process_state::group_id, MEAN_INTERVAL, process_state::message_counter, MPI_SEND, NUM_COLS, NUM_ROUTER, NUM_ROWS, NUM_TERMINALS, tw_lp::rng, process_state::router_id, process_state::row, total_routers, total_terminals, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), and terminal_message::type.
void mpi_msg_recv (process_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 337 of file dragonfly.c.
References g_tw_ts_end, N_COLLECT_POINTS, and tw_now().
Referenced by mpi_event(), and mpi_event_handler().
void mpi_msg_send (process_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 179 of file dragonfly.c.
References process_state::available_time, BISECTION, tw_bf::c1, tw_bf::c2, tw_bf::c3, terminal_message::chunk_id, process_state::col, terminal_message::dest_terminal_id, tw_lp::gid, process_state::group_id, max, max_packets, MEAN_INTERVAL, process_state::message_counter, MPI_SEND, NEAREST_NEIGHBOR, NEAREST_ROUTER, num_chunks, num_groups, num_packets, NUM_ROUTER, NUM_ROWS, NUM_TERMINALS, terminal_message::packet_ID, packet_offset, tw_lp::rng, process_state::router_id, process_state::row, terminal_message::saved_available_time, T_GENERATE, total_mpi_procs, total_routers, total_terminals, TRACK, TRANSPOSE, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), terminal_message::type, UNIFORM_RANDOM, and WORST_CASE.
Referenced by mpi_event(), and mpi_event_handler().
void mpi_rc_event_handler (process_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1453 of file dragonfly.c.
References process_state::available_time, tw_bf::c1, tw_bf::c2, tw_bf::c3, process_state::message_counter, MPI_RECV, MPI_SEND, num_packets, tw_lp::rng, terminal_message::saved_available_time, tw_rand_reverse_unif, and terminal_message::type.
void packet_arrive (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 542 of file dragonfly.c.
References BUFFER, tw_bf::c1, terminal_message::chunk_id, credit_delay, CREDIT_SIZE, FINISH, tw_lp::gid, terminal_message::last_hop, max, MEAN_PROCESS, terminal_message::my_N_hop, terminal_state::next_credit_available_time, NODE_BANDWIDTH, num_chunks, terminal_message::packet_ID, tw_lp::rng, terminal_state::router_id, terminal_message::saved_available_time, terminal_message::saved_vc, TERMINAL, TRACK, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), terminal_message::type, and terminal_message::vc_index.
Referenced by event_handler(), and terminal_event().
void packet_finish (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 597 of file dragonfly.c.
References tw_bf::c3, g_tw_ts_end, max_latency, terminal_message::my_N_hop, N_COLLECT_POINTS, N_finished, N_finished_storage, terminal_message::saved_available_time, total_hops, total_time, terminal_message::travel_start_time, and tw_now().
Referenced by terminal_event().
void packet_generate (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 419 of file dragonfly.c.
References terminal_message::chunk_id, terminal_message::dest_terminal_id, tw_lp::gid, terminal_message::intm_group_id, MEAN_INTERVAL, terminal_message::my_N_hop, num_chunks, NUM_VC, terminal_message::output_chan, terminal_message::packet_ID, tw_lp::rng, terminal_message::saved_vc, T_SEND, TERMINAL_VC_SIZE, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), terminal_message::type, terminal_state::vc_occupancy, terminal_message::wait_loc, and terminal_message::wait_type.
Referenced by event_handler(), and terminal_event().
void packet_send (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 478 of file dragonfly.c.
References tw_bf::c3, terminal_message::chunk_id, CHUNK_SIZE, terminal_message::dest_terminal_id, g_tw_mynode, g_tw_ts_end, tw_lp::gid, head_delay, terminal_message::intm_group_id, terminal_message::last_hop, max, terminal_message::my_N_hop, N_COLLECT_POINTS, N_generated_storage, NODE_BANDWIDTH, num_chunks, terminal_state::output_vc_state, terminal_state::packet_counter, terminal_message::packet_ID, R_ARRIVE, tw_lp::rng, terminal_state::router_id, terminal_message::saved_available_time, terminal_message::saved_vc, terminal_message::src_terminal_id, TERMINAL, terminal_state::terminal_available_time, TERMINAL_VC_SIZE, total_routers, TRACK, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), terminal_message::type, VC_CREDIT, terminal_state::vc_occupancy, and terminal_message::wait_type.
Referenced by event_handler(), and terminal_event().
void router_buf_update (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1235 of file dragonfly.c.
References router_state::output_vc_state, schedule_router_waiting_msg(), VC_IDLE, terminal_message::vc_index, and router_state::vc_occupancy.
Referenced by router_event().
void router_credit_send (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 370 of file dragonfly.c.
References BUFFER, credit_delay, CREDIT_SIZE, GLOBAL, GLOBAL_BANDWIDTH, terminal_message::intm_lp_id, terminal_message::last_hop, LOCAL, LOCAL_BANDWIDTH, max, router_state::next_credit_available_time, NODE_BANDWIDTH, NUM_VC, terminal_message::packet_ID, tw_lp::rng, terminal_message::saved_available_time, terminal_message::saved_vc, terminal_message::src_terminal_id, TERMINAL, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), terminal_message::type, and terminal_message::vc_index.
Referenced by router_packet_receive().
void router_event (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1245 of file dragonfly.c.
References BUFFER, terminal_message::dest_terminal_id, tw_lp::gid, terminal_message::packet_ID, R_ARRIVE, R_SEND, router_buf_update(), router_packet_receive(), router_packet_send(), tw_now(), terminal_message::type, update_router_waiting_list(), and WAIT.
void router_packet_receive (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1041 of file dragonfly.c.
References terminal_message::chunk_id, terminal_message::dest_terminal_id, tw_lp::gid, terminal_message::intm_group_id, terminal_message::intm_lp_id, terminal_message::last_hop, MEAN_INTERVAL, terminal_message::my_N_hop, num_chunks, terminal_message::packet_ID, R_SEND, tw_lp::rng, router_credit_send(), terminal_message::saved_vc, terminal_message::src_terminal_id, TRACK, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), terminal_message::type, and terminal_message::wait_type.
Referenced by router_event().
void router_packet_send (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 915 of file dragonfly.c.
References tw_bf::c2, tw_bf::c3, terminal_message::chunk_id, CHUNK_SIZE, terminal_message::dest_terminal_id, get_next_stop(), get_output_port(), getRouterID(), tw_lp::gid, GLOBAL, GLOBAL_BANDWIDTH, GLOBAL_CHANNELS, GLOBAL_VC_SIZE, terminal_message::intm_group_id, terminal_message::intm_lp_id, terminal_message::last_hop, LOCAL, LOCAL_BANDWIDTH, LOCAL_VC_SIZE, max, terminal_message::my_N_hop, router_state::next_output_available_time, num_chunks, NUM_ROUTER, NUM_VC, terminal_message::old_vc, router_state::output_vc_state, terminal_message::packet_ID, R_ARRIVE, R_SEND, tw_lp::rng, router_reschedule_event(), ROUTING, terminal_message::saved_available_time, terminal_message::saved_vc, terminal_message::src_terminal_id, T_ARRIVE, TERMINAL, TERMINAL_VC_SIZE, TRACK, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), terminal_message::type, VC_CREDIT, terminal_message::vc_index, router_state::vc_occupancy, and terminal_message::wait_type.
Referenced by router_event().
void router_rc_event_handler (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1370 of file dragonfly.c.
References BUFFER, tw_bf::c2, tw_bf::c3, waiting_packet::chan, GLOBAL, GLOBAL_VC_SIZE, terminal_message::last_hop, LOCAL_VC_SIZE, terminal_message::my_N_hop, router_state::next_credit_available_time, router_state::next_output_available_time, num_chunks, NUM_VC, terminal_message::old_vc, router_state::output_vc_state, waiting_packet::packet, R_ARRIVE, R_SEND, tw_lp::rng, terminal_message::saved_available_time, terminal_message::saved_vc, TERMINAL, TERMINAL_VC_SIZE, tw_rand_reverse_unif, terminal_message::type, VC_CREDIT, VC_IDLE, terminal_message::vc_index, router_state::vc_occupancy, WAIT, router_state::wait_count, terminal_message::wait_loc, and router_state::waiting_list.
void router_reschedule_event (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 789 of file dragonfly.c.
References terminal_message::dest_terminal_id, tw_lp::gid, terminal_message::intm_group_id, terminal_message::intm_lp_id, terminal_message::last_hop, terminal_message::my_N_hop, terminal_message::output_chan, terminal_message::packet_ID, RESCHEDULE_DELAY, tw_lp::rng, terminal_message::saved_vc, terminal_message::src_terminal_id, terminal_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), terminal_message::type, WAIT, and terminal_message::wait_type.
Referenced by router_packet_send().
void router_setup (router_state * r, tw_lp * lp)
Definition at line 1080 of file dragonfly.c.
References waiting_packet::chan, tw_lp::gid, router_state::global_channel, GLOBAL_CHANNELS, router_state::group_id, router_state::head, waiting_packet::next, router_state::next_credit_available_time, router_state::next_output_available_time, NUM_ROUTER, router_state::output_vc_state, waiting_packet::packet, RADIX, router_state::router_id, ROUTER_WAITING_PACK_COUNT, total_routers, tw_calloc(), TW_LOC, VC_IDLE, router_state::vc_occupancy, router_state::wait_count, and router_state::waiting_list.
void schedule_router_waiting_msg (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp, int chan)
Definition at line 1192 of file dragonfly.c.
References BUFFER, tw_bf::c3, waiting_packet::chan, tw_lp::gid, MEAN_INTERVAL, waiting_packet::packet, R_SEND, tw_lp::rng, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), terminal_message::type, router_state::wait_count, terminal_message::wait_loc, router_state::waiting_list, and waiting_router_packet_free().
Referenced by router_buf_update().
void schedule_terminal_waiting_msg (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 658 of file dragonfly.c.
References BUFFER, tw_bf::c3, tw_lp::gid, MEAN_INTERVAL, waiting_packet::packet, tw_lp::rng, T_SEND, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), terminal_message::type, terminal_state::wait_count, terminal_message::wait_loc, terminal_state::waiting_list, and waiting_terminal_packet_free().
Referenced by terminal_buf_update().
void terminal_buf_update (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 728 of file dragonfly.c.
References terminal_state::output_vc_state, schedule_terminal_waiting_msg(), VC_IDLE, terminal_message::vc_index, and terminal_state::vc_occupancy.
Referenced by terminal_event().
void terminal_event (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 742 of file dragonfly.c.
References BUFFER, FINISH, tw_lp::gid, packet_arrive(), packet_finish(), packet_generate(), packet_send(), T_ARRIVE, T_GENERATE, T_SEND, terminal_buf_update(), terminal_message::type, update_terminal_waiting_list(), and WAIT.
void terminal_init (terminal_state * s, tw_lp * lp)
Definition at line 688 of file dragonfly.c.
References waiting_packet::chan, getRouterID(), tw_lp::gid, terminal_state::head, waiting_packet::next, NUM_VC, terminal_state::output_vc_state, waiting_packet::packet, terminal_state::packet_counter, terminal_state::router_id, terminal_state::terminal_available_time, terminal_state::terminal_id, TERMINAL_WAITING_PACK_COUNT, tw_calloc(), TW_LOC, VC_IDLE, terminal_state::vc_occupancy, terminal_state::wait_count, and terminal_state::waiting_list.
void terminal_rc_event_handler (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1275 of file dragonfly.c.
References BUFFER, tw_bf::c1, tw_bf::c3, waiting_packet::chan, FINISH, g_tw_ts_end, max_latency, terminal_message::my_N_hop, N_COLLECT_POINTS, N_finished, N_finished_storage, N_generated_storage, terminal_state::next_credit_available_time, num_chunks, terminal_state::output_vc_state, waiting_packet::packet, terminal_state::packet_counter, tw_lp::rng, terminal_message::saved_available_time, terminal_message::saved_vc, T_ARRIVE, T_GENERATE, T_SEND, terminal_state::terminal_available_time, TERMINAL_VC_SIZE, total_hops, total_time, terminal_message::travel_start_time, tw_now(), tw_rand_reverse_unif, terminal_message::type, VC_CREDIT, VC_IDLE, terminal_message::vc_index, terminal_state::vc_occupancy, WAIT, terminal_state::wait_count, terminal_message::wait_loc, and terminal_state::waiting_list.
void update_router_waiting_list (router_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 1144 of file dragonfly.c.
References tw_bf::c3, waiting_packet::chan, waiting_packet::packet, ROUTER_WAITING_PACK_COUNT, terminal_message::vc_index, router_state::wait_count, and router_state::waiting_list.
Referenced by router_event().
void update_terminal_waiting_list (terminal_state * s, tw_bf * bf, terminal_message * msg, tw_lp * lp)
Definition at line 635 of file dragonfly.c.
References tw_bf::c3, waiting_packet::chan, waiting_packet::packet, terminal_message::saved_vc, TERMINAL_WAITING_PACK_COUNT, terminal_state::wait_count, and terminal_state::waiting_list.
Referenced by terminal_event().
void waiting_router_packet_free (router_state * s, int loc)
Definition at line 1175 of file dragonfly.c.
References waiting_packet::chan, waiting_packet::packet, router_state::wait_count, and router_state::waiting_list.
Referenced by schedule_router_waiting_msg().
void waiting_terminal_packet_free (terminal_state * s, int loc)
Definition at line 618 of file dragonfly.c.
References waiting_packet::chan, waiting_packet::packet, terminal_state::wait_count, and terminal_state::waiting_list.
Referenced by schedule_terminal_waiting_msg().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
   TWOPT_GROUP("Dragonfly Model"),
   TWOPT_UINT("memory", opt_mem, "optimistic memory"),
   TWOPT_UINT("traffic", traffic, "UNIFORM RANDOM=1, DRAGONFLY ZONES=2, TRANSPOSE=3, NEAREST NEIGHBOR=4 "),
   TWOPT_UINT("routing", ROUTING, "MINIMAL=0, NON_MINIMAL=1, ADAPTIVE=2(ADAPTIVE ROUTING QUEUE CONGESTION SENSING FEATURE's DEVELOPMENT IN PROGRESS)"),
   TWOPT_UINT("mem_factor", mem_factor, "mem_factor"),
   TWOPT_STIME("arrive_rate", MEAN_INTERVAL, "packet inter-arrival rate"),
}
Definition at line 1519 of file dragonfly.c.
FILE* dragonfly_event_log =NULL
Definition at line 9 of file dragonfly.c.
Referenced by main().
tw_lptype dragonfly_lps[]
Initial value:
=
{
   {
    (init_f)terminal_init,
    (event_f) terminal_event,
    (revent_f) terminal_rc_event_handler,
    (final_f) final,
    (map_f) mapping,
    },
   {
     (init_f) router_setup,
     (event_f) router_event,
     (revent_f) router_rc_event_handler,
     (final_f) final,
     (map_f) mapping,
     sizeof(router_state),
   },
   {
     (init_f) mpi_init,
     (event_f) mpi_event,
     (revent_f) mpi_rc_event_handler,
     (final_f) final,
     (map_f) mapping,
     sizeof(process_state),
   },
   {0},
}
Definition at line 1489 of file dragonfly.c.