ROSS: rnf/modules/application/epi/epi-init.c File Reference
epi-init.c File Reference
#include <epi.h>
Macros
#define EPI_RANGE 50
Functions
void init_default_ic_stages ()
void init_ic_stages_from_file ()
void epi_init_scenario ()
Macro Definition Documentation
#define EPI_RANGE 50
Definition at line 4 of file epi-init.c.
Function Documentation
void epi_init_scenario ()
Definition at line 225 of file epi-init.c.
void init_default_ic_stages ()
Definition at line 7 of file epi-init.c.
References epi_ic_stage::days_in_hospital, epi_ic_stage::eligible_for_inoculation, g_epi_stages, epi_ic_stage::hospital_treatment, epi_ic_stage::is_symptomatic, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_ic_stage::progress_trumps_inoculation, s, epi_ic_stage::stage_index, epi_ic_stage::stage_name, epi_ic_stage::start_multiplier, epi_ic_stage::stop_multiplier, tw_calloc(), TW_FALSE, TW_LOC, and TW_TRUE.
Referenced by epi_init_scenario().
void init_ic_stages_from_file ()
Definition at line 38 of file epi-init.c.
References epi_ic_stage::days_in_hospital, epi_ic_stage::eligible_for_inoculation, EPSILON, f, g_epi_ic_fn, g_epi_nstages, g_epi_stages, epi_ic_stage::hospital_treatment, epi_ic_stage::is_symptomatic, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_ic_stage::progress_trumps_inoculation, s, epi_ic_stage::stage_index, epi_ic_stage::stage_name, epi_ic_stage::start_multiplier, epi_ic_stage::stop_multiplier, tw_calloc(), tw_error(), TW_FALSE, TW_LOC, and TW_TRUE.
Referenced by epi_init_scenario().