ROSS: ross/models/epi/epi-model.c File Reference
epi-model.c File Reference
#include <epi.h>
Functions
void epi_init_disease ()
void epi_init_disease_default ()
void epi_init_agent (void)
void epi_init_agent_default (void)
void epi_init_hospital ()
void epi_disease_init ()
void epi_agent_init ()
void epi_model_final ()
Function Documentation
void epi_agent_init ()
Definition at line 633 of file epi-model.c.
References epi_init_agent(), epi_init_agent_default(), and g_epi_agent_fn.
Referenced by main().
void epi_disease_init ()
Definition at line 614 of file epi-model.c.
References epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), g_epi_ic_fn, g_epi_stats, tw_calloc(), and TW_LOC.
Referenced by main().
void epi_init_agent (void)
Definition at line 362 of file epi-model.c.
References epi_agent::behavior_flags, epi_agent::curr, epi_agent::dur, EPI_SUSCEPTIBLE, f, g_epi_agents, g_epi_diseases, g_epi_nagents, g_epi_ndiseases, g_epi_nregions, g_epi_pq, g_epi_regions, g_tw_nlp, epi_agent::id, epi_agent::loc, waiting_packet::next, epi_agent::nloc, nlp, epi_agent::pathogens, pq_create(), pq_enqueue(), epi_agent::region, epi_agent::stage, epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_calloc(), tw_error(), TW_LOC, and tw_memory_allocate().
Referenced by epi_agent_init().
void epi_init_agent_default (void)
Definition at line 510 of file epi-model.c.
References epi_agent::curr, epi_agent::dur, g_epi_diseases, g_epi_fd, g_epi_mean, g_epi_nagents, g_epi_ndiseases, g_epi_nregions, g_epi_pq, g_epi_regions, g_tw_lp, g_tw_nlp, ga, epi_agent::id, epi_agent::loc, epi_agent::nloc, epi_agent::pathogens, pq_create(), pq_enqueue(), epi_agent::region, rng, epi_agent::ts_next, epi_agent::ts_remove, tw_calloc(), tw_error(), TW_LOC, tw_memory_alloc(), tw_nnodes(), tw_rand_exponential(), and tw_rand_integer().
Referenced by epi_agent_init().
void epi_init_disease ()
Definition at line 4 of file epi-model.c.
References d, epi_ic_stage::days_in_hospital, epi_ic_stage::eligible_for_inoculation, EPSILON, f, g_epi_diseases, g_epi_exposed_today, g_epi_ic_fn, g_epi_log_f, g_epi_ndiseases, g_epi_sick_init_pop, epi_ic_stage::hospital_treatment, epi_ic_stage::index, epi_ic_stage::is_symptomatic, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_disease::name, epi_ic_stage::name, epi_disease::nstages, epi_ic_stage::progress_trumps_inoculation, s, epi_disease::stages, epi_ic_stage::start_multiplier, epi_ic_stage::stop_multiplier, tw_calloc(), tw_error(), TW_FALSE, TW_LOC, and TW_TRUE.
Referenced by epi_disease_init().
void epi_init_disease_default ()
Definition at line 227 of file epi-model.c.
References d, epi_ic_stage::days_in_hospital, epi_ic_stage::eligible_for_inoculation, EPSILON, g_epi_diseases, g_epi_exposed_today, g_epi_log_f, g_epi_ndiseases, g_epi_sick_init_pop, epi_ic_stage::hospital_treatment, epi_ic_stage::index, epi_ic_stage::is_symptomatic, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_disease::name, epi_ic_stage::name, epi_disease::nstages, epi_ic_stage::progress_trumps_inoculation, s, epi_disease::stages, epi_ic_stage::start_multiplier, epi_ic_stage::stop_multiplier, tw_calloc(), tw_error(), and TW_LOC.
Referenced by epi_disease_init().
void epi_init_hospital ()
Definition at line 593 of file epi-model.c.
References g_epi_hospital, g_epi_hospital_f, g_epi_hospital_fn, g_epi_hospital_ww, g_epi_hospital_wws, g_epi_nhospital, tw_calloc(), tw_error(), and TW_LOC.
Referenced by epi_disease_init().
void epi_model_final ()
Definition at line 643 of file epi-model.c.
References g_epi_log_f, g_epi_nagents, g_epi_ndiseases, g_epi_sick_init_pop, g_epi_sick_rate, g_epi_stats, g_epi_ww_init_pop, g_epi_ww_rate, g_epi_wws_init_pop, g_epi_wws_rate, epi_statistics::s_move_ev, epi_statistics::s_nchecked, epi_statistics::s_ndead, epi_statistics::s_ndraws, epi_statistics::s_ninfected, and tw_ismaster().
Referenced by main().