ROSS: rnf/modules/network/multicast/formula.c File Reference
formula.c File Reference
#include <stdio.h>
#include <math.h>
#include "formula.h"
Functions
double p_to_b (double p, double rtt, double tzero, int psize, int bval)
double b_to_p (double b, double rtt, double tzero, int psize, int bval)
double simple_p_to_b (double p, double rtt, int psize)
double simple_b_to_p (double b, double rtt, int psize)
Function Documentation
double b_to_p (double b, double rtt, double tzero, int psize, int bval)
Definition at line 63 of file formula.c.
References p, and p_to_b().
Referenced by TfmccRcvAdjustHistory().
double p_to_b (double p, double rtt, double tzero, int psize, int bval)
Definition at line 40 of file formula.c.
References MAXRATE, p, and SAMLLFLOAT.
Referenced by b_to_p(), and TfmccRcvPktHandler().
double simple_b_to_p (double b, double rtt, int psize)
Definition at line 94 of file formula.c.
double simple_p_to_b (double p, double rtt, int psize)
Definition at line 89 of file formula.c.