ROSS: rnf/modules/network/multicast/gmcc-rcv.h File Reference
gmcc-rcv.h File Reference
#include "gmcc-snd.h"
#include "gmcc-util.h"
Data Structures
struct GmccRcvInfoStruct
Macros
#define GMCC_CI_PKT_SIZE 40
#define GMCC_RCV_TAF_EWMA 0.125
#define GMCC_RCV_JUMP_FACTOR 2.58
#define GMCC_RCV_JUMP_FACTOR2 2
#define GMCC_RCV_LESS_CG2_CO 1.1
#define GMCC_RCV_MORE_CG_FACTOR 3.5
#define GMCC_RCV_CHANGE_CR_FACTOR 1.64
#define GMCC_RCV_CHANGE_CR_FACTOR2 1.25
#define GMCC_RCV_DEF_OS_TOLERENCE 1.64
#define GMCC_RCV_SAMPLE_SIZE 30
#define GMCC_RCV_REQD_SAMPLE_SIZE 30
#define GMCC_RCV_REQD_SAMPLE_SIZE2 10
#define GMCC_RCV_CG_ITVL_SAMPLE_SIZE 30
#define GMCC_RCV_CONFIDENT_NUM 30
#define GMCC_RCV_CONFIDENT_NUM2 30
#define GMCC_RCV_CONFIDENT_NUM3 10
#define GMCC_RCV_TTL_RATE_SAMPLE_ITVL 0.5
#define GMCC_RCV_OVS_TOLR_DECR_FACTOR 0.98
#define GMCC_RCV_OVS_TOLR_INCR_FACTOR 1.02
Typedefs
typedef struct GmccRcvInfoStruct GmccRcvInfo
Functions
Agent * GmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr, int8 trackStat)
void GmccRcvStart (Agent *agent)
void GmccRcvStop (Agent *agent)
void GmccRcvPktHandler (Agent *agent, Packet *p)
void GmccRcvTimer (Agent *agent, int timerId)
void GmccRcvPrintStat (Agent *agent)
void GmccRcvProcCtrlPkt (Agent *agent, Packet *p)
void GmccRcvProcDataPkt (Agent *agent, Packet *p)
void GmccRcvInitLayer (Agent *agent, int layer)
void GmccRcvInitLayer2 (Agent *agent, int layer, int refLayer)
int GmccRcvJump (Agent *agent, double timestamp, int reason)
int GmccRcvLeave (Agent *agent, int layer, int reason)
void GmccRcvCheckGoodJoin (Agent *agent)
void GmccRcvUpdateCgCmp (Agent *agent, int i)
void GmccRcvSendCiPkt (Agent *agent, double timestamp, int layer, double rcvRate, short mature, short keepalive)
Macro Definition Documentation
#define GMCC_CI_PKT_SIZE 40
Definition at line 8 of file gmcc-rcv.h.
Referenced by GmccRcvSendCiPkt().
#define GMCC_RCV_CG_ITVL_SAMPLE_SIZE 30
Definition at line 20 of file gmcc-rcv.h.
Referenced by GmccRcvInitLayer().
#define GMCC_RCV_CHANGE_CR_FACTOR 1.64
Definition at line 14 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_CHANGE_CR_FACTOR2 1.25
Definition at line 15 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_CONFIDENT_NUM 30
Definition at line 21 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt().
#define GMCC_RCV_CONFIDENT_NUM2 30
Definition at line 22 of file gmcc-rcv.h.
Referenced by GmccRcvCheckGoodJoin(), and GmccRcvProcCtrlPkt().
#define GMCC_RCV_CONFIDENT_NUM3 10
Definition at line 23 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt().
#define GMCC_RCV_DEF_OS_TOLERENCE 1.64
Definition at line 16 of file gmcc-rcv.h.
Referenced by GmccRcvStart().
#define GMCC_RCV_JUMP_FACTOR 2.58
Definition at line 10 of file gmcc-rcv.h.
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_JUMP_FACTOR2 2
Definition at line 11 of file gmcc-rcv.h.
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_LESS_CG2_CO 1.1
Definition at line 12 of file gmcc-rcv.h.
Referenced by GmccRcvProcCtrlPkt().
#define GMCC_RCV_MORE_CG_FACTOR 3.5
Definition at line 13 of file gmcc-rcv.h.
Referenced by GmccRcvUpdateCgCmp().
#define GMCC_RCV_OVS_TOLR_DECR_FACTOR 0.98
Definition at line 25 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt().
#define GMCC_RCV_OVS_TOLR_INCR_FACTOR 1.02
Definition at line 26 of file gmcc-rcv.h.
Referenced by GmccRcvCheckGoodJoin().
#define GMCC_RCV_REQD_SAMPLE_SIZE 30
Definition at line 18 of file gmcc-rcv.h.
Referenced by GmccRcvCheckGoodJoin(), GmccRcvProcCtrlPkt(), GmccRcvProcDataPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_REQD_SAMPLE_SIZE2 10
Definition at line 19 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt().
#define GMCC_RCV_SAMPLE_SIZE 30
Definition at line 17 of file gmcc-rcv.h.
Referenced by GmccRcvInitLayer(), GmccRcvInitLayer2(), GmccRcvProcCtrlPkt(), GmccRcvProcDataPkt(), and GmccRcvUpdateCgCmp().
#define GMCC_RCV_TAF_EWMA 0.125
Definition at line 9 of file gmcc-rcv.h.
Referenced by GmccRcvInitLayer(), and GmccRcvProcCtrlPkt().
#define GMCC_RCV_TTL_RATE_SAMPLE_ITVL 0.5
Definition at line 24 of file gmcc-rcv.h.
Referenced by GmccRcvProcDataPkt().
Typedef Documentation
typedef struct GmccRcvInfoStruct GmccRcvInfo
Function Documentation
void GmccRcvCheckGoodJoin (Agent * agent)
Definition at line 732 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::activeLayer_, NodeStruct::addr_, GmccRcvInfoStruct::cr_, GMCC_RCV_CONFIDENT_NUM2, GMCC_RCV_OVS_TOLR_INCR_FACTOR, GMCC_RCV_REQD_SAMPLE_SIZE, AgentStruct::info_, GmccRcvInfoStruct::joinResult_, GmccRcvInfoStruct::lastJoinedLayer_, GmccRcvInfoStruct::lastJoinFrom_, GmccRcvInfoStruct::lastJoinOsTolr_, GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::osTolr_, GmccRcvInfoStruct::ovsdSampleNum_, GmccRcvInfoStruct::sampleNum_, and GmccRcvInfoStruct::topJoinedLayer_.
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvProcDataPkt().
Agent* GmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr, int8 trackStat)
Definition at line 5 of file gmcc-rcv.c.
References GmccRcvInfoStruct::ciSent_, GetAgent(), GmccRcvPktHandler(), GmccRcvPrintStat(), GmccRcvStart(), GmccRcvStop(), GmccRcvTimer(), AgentStruct::info_, IsMcastAddr, RegisterAgent(), GmccRcvInfoStruct::trackStat_, and tw_exit().
Referenced by ReadAgentAct().
void GmccRcvInitLayer (Agent * agent, int layer)
Definition at line 80 of file gmcc-rcv.c.
References AvgCalcInit(), GmccRcvInfoStruct::cgItvlAvgCalc_, GmccRcvInfoStruct::contPktNum_, GMCC_RCV_CG_ITVL_SAMPLE_SIZE, GMCC_RCV_SAMPLE_SIZE, GMCC_RCV_TAF_EWMA, GmccRcvInfoStruct::grttAvg_, AgentStruct::info_, GmccRcvInfoStruct::itafAvg2_, GmccRcvInfoStruct::itafAvg_, GmccRcvInfoStruct::itafEst2_, GmccRcvInfoStruct::itafEst_, GmccRcvInfoStruct::lastCongTime_, GmccRcvInfoStruct::lastCor_, GmccRcvInfoStruct::lastRcvTime_, GmccRcvInfoStruct::lastResetTime_, GmccRcvInfoStruct::lastSndRate_, GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::lessCgNum_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::ovsdSampleNum_, RateAvgrInit(), GmccRcvInfoStruct::rcvRateAvg_, GmccRcvInfoStruct::sampleNum_, GmccRcvInfoStruct::srtt_, StatEstimatorInit(), GmccRcvInfoStruct::tafEst_, tw_getlp(), and tw_now().
Referenced by GmccRcvInitLayer2(), GmccRcvLeave(), and GmccRcvStart().
void GmccRcvInitLayer2 (Agent * agent, int layer, int refLayer)
Definition at line 108 of file gmcc-rcv.c.
References GmccRcvInfoStruct::activeLayer_, AvgCalcAddSample(), AvgCalcGetMean(), GmccRcvInfoStruct::cgItvlAvgCalc_, GMCC_RCV_SAMPLE_SIZE, GmccRcvInitLayer(), AgentStruct::info_, StatEstimatorDataStruct::mean_, s, AvgCalcDataStruct::sampleNum_, StatEstimatorDataStruct::sampleNum_, StatEstimatorAddSample(), and GmccRcvInfoStruct::tafEst_.
Referenced by GmccRcvJump(), and GmccRcvProcCtrlPkt().
int GmccRcvJump (Agent * agent, double timestamp, int reason)
Definition at line 617 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::activeLayer_, NodeStruct::addr_, GmccRcvInfoStruct::cr_, GmccRcvInfoStruct::crTafAvg_, GmccRcvInfoStruct::crTafDev_, GmccRcvInitLayer2(), GmccRcvSendCiPkt(), GmccRcvInfoStruct::grpAddrs_, AgentStruct::info_, GmccRcvInfoStruct::joinedLayer_, JoinGroup(), GmccRcvInfoStruct::joinResult_, GmccRcvInfoStruct::lastJoinedLayer_, GmccRcvInfoStruct::lastResetTime_, GmccRcvInfoStruct::layerNum_, GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::lessCgNum_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::ovsdSampleNum_, RegisterAgentCopy(), GmccRcvInfoStruct::sampleNum_, GmccRcvInfoStruct::topJoinedLayer_, tw_getlp(), and tw_now().
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvProcDataPkt().
int GmccRcvLeave (Agent * agent, int layer, int reason)
Definition at line 693 of file gmcc-rcv.c.
References GmccRcvInfoStruct::activeLayer_, GmccRcvInitLayer(), GmccRcvInfoStruct::grpAddrs_, AgentStruct::info_, GmccRcvInfoStruct::joinedLayer_, GmccRcvInfoStruct::lastResetTime_, GmccRcvInfoStruct::layerNum_, LeaveGroup(), GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::lessCgNum_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::ovsdSampleNum_, GmccRcvInfoStruct::sampleNum_, GmccRcvInfoStruct::topJoinedLayer_, tw_getlp(), tw_now(), and UnregisterAgentCopy().
Referenced by GmccRcvProcDataPkt().
void GmccRcvPktHandler (Agent * agent, Packet * p)
Definition at line 143 of file gmcc-rcv.c.
References GmccRcvInfoStruct::active_, GMCC_CTRL, GMCC_DATA, GmccRcvProcCtrlPkt(), GmccRcvProcDataPkt(), AgentStruct::info_, tw_exit(), and PacketStruct::type_.
Referenced by GmccRcvInit().
void GmccRcvPrintStat (Agent * agent)
Definition at line 833 of file gmcc-rcv.c.
Referenced by GmccRcvInit().
void GmccRcvProcCtrlPkt (Agent * agent, Packet * p)
Definition at line 163 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::activeLayer_, GmccCtrlExtStruct::activeLayer_, NodeStruct::addr_, AvgCalcInit(), AvgCalcTest(), GmccRcvInfoStruct::cgItvlAvgCalc_, GmccRcvInfoStruct::confidentNum2_, GmccCtrlExtStruct::cr_, GmccRcvInfoStruct::cr_, GmccRcvInfoStruct::crTafAvg_, GmccCtrlExtStruct::crTafAvg_, GmccRcvInfoStruct::crTafDev_, GmccCtrlExtStruct::crTafDev_, d, GetExtPkt(), GMCC_RCV_CONFIDENT_NUM2, GMCC_RCV_JUMP_FACTOR, GMCC_RCV_JUMP_FACTOR2, GMCC_RCV_LESS_CG2_CO, GMCC_RCV_REQD_SAMPLE_SIZE, GMCC_RCV_SAMPLE_SIZE, GMCC_RCV_TAF_EWMA, GmccRcvCheckGoodJoin(), GmccRcvInitLayer2(), GmccRcvJump(), GmccRcvSendCiPkt(), GmccRcvUpdateCgCmp(), GmccCtrlExtStruct::grpAddrs_, GmccRcvInfoStruct::grpAddrs_, GmccCtrlExtStruct::grttAvg_, GmccRcvInfoStruct::grttAvg_, GmccCtrlExtStruct::grttDev_, GmccRcvInfoStruct::grttDev_, PacketStruct::id_, AgentStruct::info_, GmccRcvInfoStruct::itafAvg2_, GmccRcvInfoStruct::itafEst2_, GmccRcvInfoStruct::itafEst_, GmccRcvInfoStruct::joinedLayer_, GmccRcvInfoStruct::joinResult_, GmccRcvInfoStruct::lastCongTime_, GmccRcvInfoStruct::lastJoinedLayer_, GmccRcvInfoStruct::lastJoinFrom_, GmccRcvInfoStruct::lastJoinOsTolr_, GmccCtrlExtStruct::layer_, GmccRcvInfoStruct::layerNum_, GmccCtrlExtStruct::layerNum_, GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::lessCgNum_, StatEstimatorDataStruct::mean_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::ovsdSampleNum_, RateAvgrGetMean(), GmccRcvInfoStruct::rcvRateAvg_, StatEstimatorDataStruct::sampleNum_, GmccRcvInfoStruct::sampleNum_, GmccRcvInfoStruct::senderAddr_, GmccRcvInfoStruct::senderAgent_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, GmccCtrlExtStruct::srtt_, GmccRcvInfoStruct::srtt_, StatEstimatorInit(), StatEstimatorTest(), GmccRcvInfoStruct::tafEst_, GmccCtrlExtStruct::timestamp_, GmccRcvInfoStruct::topActLayer_, GmccRcvInfoStruct::topJoinedActLayer_, GmccRcvInfoStruct::topJoinedLayer_, tw_exit(), tw_getlp(), and tw_now().
Referenced by GmccRcvPktHandler().
void GmccRcvProcDataPkt (Agent * agent, Packet * p)
Definition at line 302 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::activeLayer_, NodeStruct::addr_, AvgCalcAddSample(), GmccRcvInfoStruct::begTime_, GmccRcvInfoStruct::cgItvlAvgCalc_, GmccRcvInfoStruct::confidentNum3_, GmccRcvInfoStruct::contPktNum_, GmccRcvInfoStruct::cr_, GmccRcvInfoStruct::crTafAvg_, GmccRcvInfoStruct::crTafDev_, d, StatEstimatorDataStruct::dev_, PacketStruct::gd_, GetGrpAddr4Print, GMCC_RCV_CHANGE_CR_FACTOR, GMCC_RCV_CHANGE_CR_FACTOR2, GMCC_RCV_CONFIDENT_NUM, GMCC_RCV_CONFIDENT_NUM3, GMCC_RCV_OVS_TOLR_DECR_FACTOR, GMCC_RCV_REQD_SAMPLE_SIZE, GMCC_RCV_REQD_SAMPLE_SIZE2, GMCC_RCV_SAMPLE_SIZE, GMCC_RCV_TTL_RATE_SAMPLE_ITVL, GmccRcvCheckGoodJoin(), GmccRcvJump(), GmccRcvLeave(), GmccRcvSendCiPkt(), GmccRcvUpdateCgCmp(), GmccRcvInfoStruct::grpAddrs_, GmccRcvInfoStruct::grttAvg_, AgentStruct::info_, GmccRcvInfoStruct::itafAvg2_, GmccRcvInfoStruct::itafAvg_, GmccRcvInfoStruct::itafEst2_, GmccRcvInfoStruct::itafEst_, GmccRcvInfoStruct::itvlRcvd_, GmccRcvInfoStruct::joinedLayer_, GmccRcvInfoStruct::joinResult_, GmccRcvInfoStruct::lastCiTime_, GmccRcvInfoStruct::lastCongTime_, GmccRcvInfoStruct::lastContSqn_, GmccRcvInfoStruct::lastJoinedLayer_, GmccRcvInfoStruct::lastJoinFrom_, GmccRcvInfoStruct::lastJoinOsTolr_, GmccRcvInfoStruct::lastRateRecTime_, GmccRcvInfoStruct::lastRcvTime_, GmccRcvInfoStruct::lastSndRate_, GmccDataStruct::layer_, GmccRcvInfoStruct::lessCgNum_, StatEstimatorDataStruct::mean_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::osTolr_, GmccDataStruct::oversend_, GmccRcvInfoStruct::ovsdSampleNum_, GmccDataStruct::rate_, RateAvgrAddSample(), RateAvgrGetMean(), GmccRcvInfoStruct::rcvRateAvg_, StatEstimatorDataStruct::sampleNum_, GmccRcvInfoStruct::sampleNum_, GmccRcvInfoStruct::senderAddr_, GmccRcvInfoStruct::senderAgent_, PacketStruct::size_, GmccDataStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, StatEstimatorAddSample(), GmccRcvInfoStruct::tafEst_, GmccDataStruct::timestamp_, GmccRcvInfoStruct::topActLayer_, GmccRcvInfoStruct::topJoinedActLayer_, GmccRcvInfoStruct::topJoinedLayer_, GmccRcvInfoStruct::totalRcvd_, GmccRcvInfoStruct::trackStat_, tw_getlp(), tw_now(), and PacketStruct::type.
Referenced by GmccRcvPktHandler().
void GmccRcvSendCiPkt (Agent * agent, double timestamp, int layer, double rcvRate, short mature, short keepalive)
Definition at line 578 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::active_, NodeStruct::addr_, GmccRcvInfoStruct::ciSent_, StatEstimatorDataStruct::dev_, GMCC_CI, GMCC_CI_PKT_SIZE, AgentStruct::id_, AgentStruct::info_, StatEstimatorDataStruct::mean_, AgentStruct::nodeId_, p, StatEstimatorDataStruct::sampleNum_, GmccRcvInfoStruct::senderAddr_, GmccRcvInfoStruct::senderAgent_, SendPacket(), GmccRcvInfoStruct::tafEst_, and tw_getlp().
Referenced by GmccRcvJump(), GmccRcvProcCtrlPkt(), and GmccRcvProcDataPkt().
void GmccRcvStart (Agent * agent)
Definition at line 44 of file gmcc-rcv.c.
References GmccRcvInfoStruct::active_, GmccRcvInfoStruct::activeLayer_, GmccRcvInfoStruct::begTime_, GmccRcvInfoStruct::cr_, GMCC_MAX_LAYER_NUM, GMCC_RCV_DEF_OS_TOLERENCE, GmccRcvInitLayer(), GmccRcvInfoStruct::grttAvg_, GmccRcvInfoStruct::grttDev_, AgentStruct::info_, GmccRcvInfoStruct::itvlRcvd_, GmccRcvInfoStruct::joinedLayer_, GmccRcvInfoStruct::joinResult_, GmccRcvInfoStruct::lastCiTime_, GmccRcvInfoStruct::lastJoinedLayer_, GmccRcvInfoStruct::lastRateRecTime_, GmccRcvInfoStruct::layerNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::osTolr_, GmccRcvInfoStruct::topActLayer_, GmccRcvInfoStruct::topJoinedActLayer_, GmccRcvInfoStruct::topJoinedLayer_, GmccRcvInfoStruct::totalRcvd_, tw_getlp(), and tw_now().
Referenced by GmccRcvInit().
void GmccRcvStop (Agent * agent)
Definition at line 72 of file gmcc-rcv.c.
References GmccRcvInfoStruct::active_, and AgentStruct::info_.
Referenced by GmccRcvInit().
void GmccRcvTimer (Agent * agent, int timerId)
Definition at line 825 of file gmcc-rcv.c.
References GmccRcvInfoStruct::active_, and AgentStruct::info_.
Referenced by GmccRcvInit().
void GmccRcvUpdateCgCmp (Agent * agent, int i)
Definition at line 764 of file gmcc-rcv.c.
References _nodeTable, GmccRcvInfoStruct::activeLayer_, NodeStruct::addr_, GmccRcvInfoStruct::cr_, GmccRcvInfoStruct::crTafAvg_, GmccRcvInfoStruct::crTafDev_, StatEstimatorDataStruct::dev_, GMCC_RCV_CHANGE_CR_FACTOR, GMCC_RCV_CHANGE_CR_FACTOR2, GMCC_RCV_JUMP_FACTOR, GMCC_RCV_JUMP_FACTOR2, GMCC_RCV_MORE_CG_FACTOR, GMCC_RCV_REQD_SAMPLE_SIZE, GMCC_RCV_SAMPLE_SIZE, AgentStruct::info_, GmccRcvInfoStruct::lessCgNum2_, GmccRcvInfoStruct::lessCgNum_, mean, StatEstimatorDataStruct::mean_, GmccRcvInfoStruct::moreCgNum_, AgentStruct::nodeId_, GmccRcvInfoStruct::ovsdSampleNum_, StatEstimatorDataStruct::sampleNum_, GmccRcvInfoStruct::sampleNum_, and GmccRcvInfoStruct::tafEst_.
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvProcDataPkt().