ROSS: rnf/modules/network/multicast/gmcc-snd.h File Reference
gmcc-snd.h File Reference
#include "Packet.h"
#include "Transport.h"
#include "gmcc-util.h"
Data Structures
struct GmccSrcInfoStruct
Macros
#define GMCC_DATA_PKT_SIZE 1000
#define GMCC_CTRL_PKT_SIZE 40
#define GMCC_INIT_CONG_ITVL 1
#define GMCC_TRAC_EWMA 0.1
#define GMCC_CR_CHECK_EWMA 0.1
#define GMCC_SRC_MIN_RATE GMCC_DATA_PKT_SIZE
#define GMCC_SRC_INIT_RTT 0.1
#define GMCC_SRC_RTT_EWMA 0.125
#define GMCC_SRC_GRTT_EWMA 0.02
#define GMCC_SRC_SAMPLE_SIZE 30
#define GMCC_SRC_LAYER_NUM 16
#define GMCC_SRC_RATE_INCR_RTT_FACTOR 2
#define GMCC_SRC_RATE_CUT_FACTOR 0.75
#define GMCC_SRC_CHANGE_CR_FACTOR 1.64
#define GMCC_SRC_CHANGE_CR_FACTOR2 1.25
#define GMCC_SRC_OVERSEND_FRAC 0.1
#define GMCC_SRC_OVERSEND_PROB 0
#define GMCC_SRC_CR_EXT_SEARCH_SPAN 4
#define GMCC_SRC_KEEPALIVE_SPAN 20
Typedefs
typedef struct GmccSrcInfoStruct GmccSrcInfo
Enumerations
enum {
GMCC_SRC_RATE_INCR_TIMER, GMCC_SRC_SEND_PKT_TIMER, GMCC_SRC_CONG_EPOCH_TIMER, GMCC_SRC_CR_CHECK_TIMER,
GMCC_SRC_CR_EXT_SEARCH_TIMER, GMCC_SRC_KEEPALIVE_TIMER
}
Functions
Agent * GmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId)
void GmccSrcStart (Agent *agent)
void GmccSrcStop (Agent *agent)
void GmccSrcPktHandler (Agent *agent, Packet *p)
void GmccSrcTimer (Agent *agent, int timerId, int serial)
void GmccSrcPrintStat (Agent *agent)
void GmccSrcInitLayer (Agent *agent, int layer)
void GmccSrcResetLayer (Agent *agent, int layer)
void GmccSrcSendCtrlPkt (Agent *agent, int layer)
void GmccSrcSendDataPkt (Agent *agent, int layer)
Macro Definition Documentation
#define GMCC_CR_CHECK_EWMA 0.1
Definition at line 13 of file gmcc-snd.h.
#define GMCC_CTRL_PKT_SIZE 40
Definition at line 9 of file gmcc-snd.h.
Referenced by GmccSrcSendCtrlPkt().
#define GMCC_DATA_PKT_SIZE 1000
Definition at line 8 of file gmcc-snd.h.
Referenced by GmccSrcInitLayer(), GmccSrcPktHandler(), GmccSrcSendDataPkt(), GmccSrcStart(), and GmccSrcTimer().
#define GMCC_INIT_CONG_ITVL 1
Definition at line 11 of file gmcc-snd.h.
#define GMCC_SRC_CHANGE_CR_FACTOR 1.64
Definition at line 23 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_SRC_CHANGE_CR_FACTOR2 1.25
Definition at line 24 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_SRC_CR_EXT_SEARCH_SPAN 4
Definition at line 28 of file gmcc-snd.h.
Referenced by GmccSrcTimer().
#define GMCC_SRC_GRTT_EWMA 0.02
Definition at line 18 of file gmcc-snd.h.
#define GMCC_SRC_INIT_RTT 0.1
Definition at line 16 of file gmcc-snd.h.
Referenced by GmccSrcStart().
#define GMCC_SRC_KEEPALIVE_SPAN 20
Definition at line 29 of file gmcc-snd.h.
Referenced by GmccSrcTimer().
#define GMCC_SRC_LAYER_NUM 16
Definition at line 20 of file gmcc-snd.h.
Referenced by GmccSrcInit().
#define GMCC_SRC_MIN_RATE GMCC_DATA_PKT_SIZE
Definition at line 15 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_SRC_OVERSEND_FRAC 0.1
Definition at line 25 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler(), GmccSrcSendDataPkt(), and GmccSrcTimer().
#define GMCC_SRC_OVERSEND_PROB 0
Definition at line 27 of file gmcc-snd.h.
Referenced by GmccSrcTimer().
#define GMCC_SRC_RATE_CUT_FACTOR 0.75
Definition at line 22 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_SRC_RATE_INCR_RTT_FACTOR 2
Definition at line 21 of file gmcc-snd.h.
Referenced by GmccSrcSendCtrlPkt(), and GmccSrcTimer().
#define GMCC_SRC_RTT_EWMA 0.125
Definition at line 17 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_SRC_SAMPLE_SIZE 30
Definition at line 19 of file gmcc-snd.h.
Referenced by GmccSrcPktHandler().
#define GMCC_TRAC_EWMA 0.1
Definition at line 12 of file gmcc-snd.h.
Typedef Documentation
typedef struct GmccSrcInfoStruct GmccSrcInfo
Enumeration Type Documentation
anonymous enum
Enumerator
GMCC_SRC_RATE_INCR_TIMER
GMCC_SRC_SEND_PKT_TIMER
GMCC_SRC_CONG_EPOCH_TIMER
GMCC_SRC_CR_CHECK_TIMER
GMCC_SRC_CR_EXT_SEARCH_TIMER
GMCC_SRC_KEEPALIVE_TIMER
Definition at line 32 of file gmcc-snd.h.
Function Documentation
Agent* GmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId)
Definition at line 5 of file gmcc-snd.c.
References _nodeTable, GetAgent(), GMCC_SRC_LAYER_NUM, GmccSrcPktHandler(), GmccSrcPrintStat(), GmccSrcStart(), GmccSrcStop(), GmccSrcTimer(), AgentStruct::info_, GmccSrcInfoStruct::layerNum_, GmccSrcInfoStruct::pktDstAddr_, GmccSrcInfoStruct::pktDstAgentId_, RegisterAgent(), and tw_exit().
Referenced by ReadAgentAct().
void GmccSrcInitLayer (Agent * agent, int layer)
Definition at line 37 of file gmcc-snd.c.
References GmccSrcInfoStruct::activeLayer_, GmccSrcInfoStruct::cr_, GmccSrcInfoStruct::crTafAvg_, GmccSrcInfoStruct::crTafDev_, GmccSrcInfoStruct::debtNextLayer_, GMCC_DATA_PKT_SIZE, GmccSrcInfoStruct::grttAvg_, AgentStruct::info_, GmccSrcInfoStruct::rate_, RateAvgrInit(), GmccSrcInfoStruct::rttAvg_, GmccSrcInfoStruct::rttDev_, GmccSrcInfoStruct::sndRateAvg_, and GmccSrcInfoStruct::sqn_.
Referenced by GmccSrcPktHandler(), and GmccSrcStart().
void GmccSrcPktHandler (Agent * agent, Packet * p)
Definition at line 235 of file gmcc-snd.c.
References GmccSrcInfoStruct::active_, GmccSrcInfoStruct::activeLayer_, GmccSrcInfoStruct::congEpochTimerEvnt_, GmccSrcInfoStruct::cr_, GmccSrcInfoStruct::crCheckTimerEvnt_, GmccSrcInfoStruct::crExtSearchTimerEvnt_, GmccSrcInfoStruct::crTafAvg_, GmccSrcInfoStruct::crTafDev_, d, StatEstimatorDataStruct::dev_, PacketStruct::gci_, GMCC_DATA_PKT_SIZE, GMCC_SRC_CHANGE_CR_FACTOR, GMCC_SRC_CHANGE_CR_FACTOR2, GMCC_SRC_CONG_EPOCH_TIMER, GMCC_SRC_CR_CHECK_TIMER, GMCC_SRC_MIN_RATE, GMCC_SRC_OVERSEND_FRAC, GMCC_SRC_RATE_CUT_FACTOR, GMCC_SRC_RATE_INCR_TIMER, GMCC_SRC_RTT_EWMA, GMCC_SRC_SAMPLE_SIZE, GMCC_SRC_SEND_PKT_TIMER, GmccSrcInitLayer(), GmccSrcSendCtrlPkt(), GmccSrcSendDataPkt(), GmccSrcInfoStruct::grttAvg_, GmccSrcInfoStruct::grttDev_, GmccSrcInfoStruct::grttEst_, AgentStruct::id_, AgentStruct::info_, GmccSrcInfoStruct::keepaliveTimerEvnt_, GmccCiStruct::layer_, GmccSrcInfoStruct::layerNum_, StatEstimatorDataStruct::mean_, AgentStruct::nodeId_, GmccSrcInfoStruct::oversendLayer_, GmccSrcInfoStruct::rate_, GmccSrcInfoStruct::rateIncrTimerEvnt_, ReschedTimerWithSn(), GmccSrcInfoStruct::rttAvg_, GmccSrcInfoStruct::rttDev_, ScheduleTimerWithSn(), GmccSrcInfoStruct::sendPktTimerEvnt_, PacketStruct::srcAddr_, StatEstimatorAddSample(), GmccSrcInfoStruct::topActLayer_, tw_exit(), tw_getlp(), tw_now(), tw_timer_cancel(), and PacketStruct::type.
Referenced by GmccSrcInit().
void GmccSrcPrintStat (Agent * agent)
Definition at line 537 of file gmcc-snd.c.
Referenced by GmccSrcInit().
void GmccSrcResetLayer (Agent * agent, int layer)
Definition at line 56 of file gmcc-snd.c.
References GmccSrcInfoStruct::congEpochTimerEvnt_, GmccSrcInfoStruct::crCheckTimerEvnt_, GmccSrcInfoStruct::crExtSearchTimerEvnt_, AgentStruct::info_, GmccSrcInfoStruct::keepaliveTimerEvnt_, AgentStruct::nodeId_, RateAvgrReset(), GmccSrcInfoStruct::rateIncrTimerEvnt_, GmccSrcInfoStruct::sendPktTimerEvnt_, GmccSrcInfoStruct::sndRateAvg_, tw_getlp(), and tw_timer_cancel().
Referenced by GmccSrcTimer().
void GmccSrcSendCtrlPkt (Agent * agent, int layer)
Definition at line 141 of file gmcc-snd.c.
References _nodeTable, GmccSrcInfoStruct::active_, GmccSrcInfoStruct::activeLayer_, NodeStruct::addr_, GmccSrcInfoStruct::cr_, GmccSrcInfoStruct::crTafAvg_, GmccSrcInfoStruct::crTafDev_, GmccSrcInfoStruct::ctrlPktId_, GMCC_CTRL, GMCC_CTRL_PKT_SIZE, GMCC_SRC_RATE_INCR_RTT_FACTOR, GmccSrcInfoStruct::grpAddrs_, GmccSrcInfoStruct::grttAvg_, GmccSrcInfoStruct::grttDev_, AgentStruct::id_, AgentStruct::info_, GmccSrcInfoStruct::layerNum_, AgentStruct::nodeId_, p, GmccSrcInfoStruct::rttAvg_, GmccSrcInfoStruct::rttDev_, SendExtPkt(), tw_getlp(), and tw_now().
Referenced by GmccSrcPktHandler(), GmccSrcSendDataPkt(), GmccSrcStart(), and GmccSrcTimer().
void GmccSrcSendDataPkt (Agent * agent, int layer)
Definition at line 188 of file gmcc-snd.c.
References _nodeTable, GmccSrcInfoStruct::active_, NodeStruct::addr_, GmccSrcInfoStruct::debtNextLayer_, GMCC_DATA, GMCC_DATA_PKT_SIZE, GMCC_SRC_OVERSEND_FRAC, GmccSrcSendCtrlPkt(), GmccSrcInfoStruct::grpAddrs_, AgentStruct::id_, AgentStruct::info_, GmccSrcInfoStruct::lastCtrlPktTime_, GmccDataStruct::layer_, AgentStruct::nodeId_, GmccDataStruct::oversend_, GmccSrcInfoStruct::oversendLayer_, p, GmccDataStruct::rate_, RateAvgrAddSample(), GmccSrcInfoStruct::rttAvg_, SendPacket(), GmccSrcInfoStruct::sndRateAvg_, GmccDataStruct::sqn_, GmccSrcInfoStruct::sqn_, GmccDataStruct::timestamp_, tw_getlp(), and tw_now().
Referenced by GmccSrcPktHandler(), GmccSrcStart(), and GmccSrcTimer().
void GmccSrcStart (Agent * agent)
Definition at line 71 of file gmcc-snd.c.
References GmccSrcInfoStruct::active_, GmccSrcInfoStruct::activeLayer_, AddGroup(), AllocGroupAddr(), GmccSrcInfoStruct::congEpochTimerEvnt_, GmccSrcInfoStruct::crCheckTimerEvnt_, GmccSrcInfoStruct::crExtSearchTimerEvnt_, GmccSrcInfoStruct::ctrlPktId_, GMCC_DATA_PKT_SIZE, GMCC_MAX_LAYER_NUM, GMCC_SRC_INIT_RTT, GMCC_SRC_RATE_INCR_TIMER, GMCC_SRC_SEND_PKT_TIMER, GmccSrcInitLayer(), GmccSrcSendCtrlPkt(), GmccSrcSendDataPkt(), GmccSrcInfoStruct::grpAddrs_, GmccSrcInfoStruct::grttAvg_, GmccSrcInfoStruct::grttDev_, GmccSrcInfoStruct::grttEst_, AgentStruct::info_, GmccSrcInfoStruct::keepaliveTimerEvnt_, GmccSrcInfoStruct::lastCtrlPktTime_, GmccSrcInfoStruct::layerNum_, AgentStruct::nodeId_, GmccSrcInfoStruct::oversendLayer_, GmccSrcInfoStruct::pktDstAddr_, GmccSrcInfoStruct::rate_, GmccSrcInfoStruct::rateIncrTimerEvnt_, GmccSrcInfoStruct::rttAvg_, ScheduleTimerWithSn(), GmccSrcInfoStruct::sendPktTimerEvnt_, StatEstimatorInit(), GmccSrcInfoStruct::topActLayer_, tw_getlp(), and tw_now().
Referenced by GmccSrcInit().
void GmccSrcStop (Agent * agent)
Definition at line 122 of file gmcc-snd.c.
References GmccSrcInfoStruct::active_, GmccSrcInfoStruct::congEpochTimerEvnt_, GmccSrcInfoStruct::crCheckTimerEvnt_, GmccSrcInfoStruct::crExtSearchTimerEvnt_, AgentStruct::info_, GmccSrcInfoStruct::keepaliveTimerEvnt_, GmccSrcInfoStruct::layerNum_, AgentStruct::nodeId_, GmccSrcInfoStruct::rateIncrTimerEvnt_, GmccSrcInfoStruct::sendPktTimerEvnt_, tw_getlp(), and tw_timer_cancel().
Referenced by GmccSrcInit().
void GmccSrcTimer (Agent * agent, int timerId, int serial)
Definition at line 420 of file gmcc-snd.c.
References GmccSrcInfoStruct::active_, GmccSrcInfoStruct::activeLayer_, GmccSrcInfoStruct::congEpochTimerEvnt_, GmccSrcInfoStruct::cr_, GmccSrcInfoStruct::crCheckTimerEvnt_, GmccSrcInfoStruct::crExtSearchTimerEvnt_, GmccSrcInfoStruct::debtNextLayer_, GMCC_DATA_PKT_SIZE, GMCC_SRC_CONG_EPOCH_TIMER, GMCC_SRC_CR_CHECK_TIMER, GMCC_SRC_CR_EXT_SEARCH_SPAN, GMCC_SRC_CR_EXT_SEARCH_TIMER, GMCC_SRC_KEEPALIVE_SPAN, GMCC_SRC_KEEPALIVE_TIMER, GMCC_SRC_OVERSEND_FRAC, GMCC_SRC_OVERSEND_PROB, GMCC_SRC_RATE_INCR_RTT_FACTOR, GMCC_SRC_RATE_INCR_TIMER, GMCC_SRC_SEND_PKT_TIMER, GmccSrcResetLayer(), GmccSrcSendCtrlPkt(), GmccSrcSendDataPkt(), GmccSrcInfoStruct::grttAvg_, GmccSrcInfoStruct::grttDev_, AgentStruct::id_, AgentStruct::info_, GmccSrcInfoStruct::keepaliveTimerEvnt_, GmccSrcInfoStruct::layerNum_, AgentStruct::nodeId_, GmccSrcInfoStruct::oversendLayer_, GmccSrcInfoStruct::rate_, GmccSrcInfoStruct::rateIncrTimerEvnt_, ReschedTimerWithSn(), GmccSrcInfoStruct::rttAvg_, GmccSrcInfoStruct::rttDev_, ScheduleTimerWithSn(), GmccSrcInfoStruct::sendPktTimerEvnt_, GmccSrcInfoStruct::topActLayer_, tw_exit(), tw_getlp(), tw_now(), and tw_timer_cancel().
Referenced by GmccSrcInit().