ROSS: rnf/modules/network/multicast/gmcc-util.c File Reference
gmcc-util.c File Reference
#include "gmcc-util.h"
Functions
void RateAvgrInit (RateAvgrData *data, int sampleSize)
void RateAvgrReset (RateAvgrData *data)
double RateAvgrAddSample (RateAvgrData *data, double t, int pktSize)
double RateAvgrGetMean (RateAvgrData *data)
void AvgCalcInit (AvgCalcData *data, int sampleSize)
void AvgCalcReset (AvgCalcData *data)
double AvgCalcAddSample (AvgCalcData *data, double s)
double AvgCalcTest (AvgCalcData *data, double s)
double AvgCalcGetMean (AvgCalcData *data)
void StatEstimatorInit (StatEstimatorData *data, int sampleSize, double ewma)
void StatEstimatorReset (StatEstimatorData *data)
void StatEstimatorAddSample (StatEstimatorData *data, double s)
double StatEstimatorTest (StatEstimatorData *data, double s)
Function Documentation
double AvgCalcAddSample (AvgCalcData * data, double s)
Definition at line 74 of file gmcc-util.c.
References AvgCalcDataStruct::head_, AvgCalcDataStruct::maxSampleSize_, s, AvgCalcDataStruct::sampleNum_, AvgCalcDataStruct::samples_, AvgCalcDataStruct::sum_, and AvgCalcDataStruct::tail_.
Referenced by GmccRcvInitLayer2(), and GmccRcvProcDataPkt().
double AvgCalcGetMean (AvgCalcData * data) inline
Definition at line 103 of file gmcc-util.c.
References AvgCalcDataStruct::sampleNum_, and AvgCalcDataStruct::sum_.
Referenced by GmccRcvInitLayer2().
void AvgCalcInit (AvgCalcData * data, int sampleSize) inline
Definition at line 57 of file gmcc-util.c.
References AvgCalcDataStruct::maxSampleSize_, and AvgCalcDataStruct::samples_.
Referenced by GmccRcvInitLayer(), and GmccRcvProcCtrlPkt().
void AvgCalcReset (AvgCalcData * data) inline
Definition at line 67 of file gmcc-util.c.
References AvgCalcDataStruct::samples_.
double AvgCalcTest (AvgCalcData * data, double s) inline
Definition at line 97 of file gmcc-util.c.
References AvgCalcDataStruct::sampleNum_, and AvgCalcDataStruct::sum_.
Referenced by GmccRcvProcCtrlPkt().
double RateAvgrAddSample (RateAvgrData * data, double t, int pktSize)
Definition at line 21 of file gmcc-util.c.
References RateAvgrDataStruct::head_, RateAvgrDataStruct::maxSampleSize_, PacketSizeAndTimeStruct::pktSize_, RateAvgrDataStruct::samples_, RateAvgrDataStruct::tail_, PacketSizeAndTimeStruct::time_, and RateAvgrDataStruct::totalPktSize_.
Referenced by GmccRcvProcDataPkt(), and GmccSrcSendDataPkt().
double RateAvgrGetMean (RateAvgrData * data) inline
Definition at line 43 of file gmcc-util.c.
References RateAvgrDataStruct::head_, RateAvgrDataStruct::maxSampleSize_, RateAvgrDataStruct::samples_, RateAvgrDataStruct::tail_, PacketSizeAndTimeStruct::time_, and RateAvgrDataStruct::totalPktSize_.
Referenced by GmccRcvProcCtrlPkt(), and GmccRcvProcDataPkt().
void RateAvgrInit (RateAvgrData * data, int sampleSize) inline
Definition at line 4 of file gmcc-util.c.
References RateAvgrDataStruct::maxSampleSize_, and RateAvgrDataStruct::samples_.
Referenced by GmccRcvInitLayer(), and GmccSrcInitLayer().
void RateAvgrReset (RateAvgrData * data) inline
Definition at line 14 of file gmcc-util.c.
References RateAvgrDataStruct::samples_.
Referenced by GmccSrcResetLayer().
void StatEstimatorAddSample (StatEstimatorData * data, double s)
Definition at line 127 of file gmcc-util.c.
References d, StatEstimatorDataStruct::dev_, StatEstimatorDataStruct::maxSampleSize_, StatEstimatorDataStruct::mean_, s, StatEstimatorDataStruct::sample_, StatEstimatorDataStruct::sampleHead_, StatEstimatorDataStruct::sampleNum_, StatEstimatorDataStruct::sampleSum_, and StatEstimatorDataStruct::sampleTail_.
Referenced by GmccRcvInitLayer2(), GmccRcvProcDataPkt(), and GmccSrcPktHandler().
void StatEstimatorInit (StatEstimatorData * data, int sampleSize, double ewma) inline
Definition at line 109 of file gmcc-util.c.
References StatEstimatorDataStruct::ewma_, StatEstimatorDataStruct::maxSampleSize_, and StatEstimatorDataStruct::sample_.
Referenced by GmccRcvInitLayer(), GmccRcvProcCtrlPkt(), and GmccSrcStart().
void StatEstimatorReset (StatEstimatorData * data) inline
Definition at line 120 of file gmcc-util.c.
References StatEstimatorDataStruct::sample_.
double StatEstimatorTest (StatEstimatorData * data, double s) inline
Definition at line 159 of file gmcc-util.c.
References s, StatEstimatorDataStruct::sampleNum_, and StatEstimatorDataStruct::sampleSum_.
Referenced by GmccRcvProcCtrlPkt().