ROSS: ross/gvt-7oclock.c File Reference
gvt-7oclock.c File Reference
#include <ross.h>
Macros
#define TW_GVT_NORMAL 0
#define TW_GVT_COMPUTE_LGVT 1
#define TW_GVT_WAIT 2
#define TW_GVT_COMPUTE 3
#define TW_GVT_WAIT_REMOTE 4
Functions
void tw_gvt_stats (FILE *f)
static void tw_gvt_compute (tw_pe *pe)
void tw_gvt_wait (tw_pe *pe)
int tw_gvt_set (tw_pe *pe, tw_stime GVT)
const tw_optdef * tw_gvt_setup (void)
void tw_gvt_start (void)
void tw_gvt_force_update (tw_pe *me)
void tw_gvt_step1 (tw_pe *me)
void tw_gvt_step2 (tw_pe *me)
Variables
static unsigned int g_tw_gvt_interval = 16
static unsigned int g_tw_gvt_max_no_change = 1000
static unsigned int g_tw_gvt_no_change = 0
static tw_mutex g_tw_gvt_lck = TW_MUTEX_INIT
static tw_volatile tw_stime sim_gvt
static tw_stime node_lvt
static unsigned int gvt_cnt
static tw_stime secs = 0.1
static tw_stime delta_t = 0.01
static unsigned int CPU = 1998
static int TW_PARALLEL = 0
static int TW_DISTRIBUTED = 0
static const tw_optdef gvt_opts []
Macro Definition Documentation
#define TW_GVT_COMPUTE 3
Definition at line 8 of file gvt-7oclock.c.
Referenced by tw_gvt_step1(), and tw_gvt_step2().
#define TW_GVT_COMPUTE_LGVT 1
Definition at line 6 of file gvt-7oclock.c.
Referenced by tw_gvt_step1(), and tw_gvt_step2().
#define TW_GVT_NORMAL 0
Definition at line 5 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), tw_gvt_set(), tw_gvt_step1(), and tw_gvt_wait().
#define TW_GVT_WAIT 2
Definition at line 7 of file gvt-7oclock.c.
#define TW_GVT_WAIT_REMOTE 4
Definition at line 9 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), and tw_gvt_step2().
Function Documentation
static void tw_gvt_compute (tw_pe * pe) static
Definition at line 60 of file gvt-7oclock.c.
References g_tw_7oclock_node_flag, g_tw_gvt_done, g_tw_gvt_lck, g_tw_gvt_max_no_change, g_tw_gvt_no_change, g_tw_masternode, g_tw_ts_end, tw_pe::GVT, tw_pe::gvt_status, tw_pe::id, tw_pe::LVT, min, tw_pe::node, node_lvt, p, tw_pe::pq, sim_gvt, tw_pe::trans_msg_ts, TW_DISTRIBUTED, tw_error(), TW_GVT_NORMAL, TW_GVT_WAIT_REMOTE, TW_LOC, tw_net_onnode(), tw_net_send_lvt(), tw_node_eq(), TW_PARALLEL, tw_pe_fossil_collect(), tw_pe_next(), and tw_pq_minimum().
Referenced by tw_gvt_step2().
void tw_gvt_force_update (tw_pe * me)
Definition at line 252 of file gvt-7oclock.c.
Referenced by tw_sched_batch(), and tw_scheduler_conservative().
int tw_gvt_set (tw_pe * pe, tw_stime GVT)
Definition at line 188 of file gvt-7oclock.c.
References g_tw_7oclock_node_flag, g_tw_gvt_done, g_tw_gvt_lck, g_tw_gvt_max_no_change, g_tw_gvt_no_change, g_tw_mynode, g_tw_ts_end, tw_pe::GVT, gvt_print(), tw_pe::gvt_status, tw_pe::id, percent_complete, sim_gvt, tw_pe::trans_msg_ts, tw_error(), TW_GVT_NORMAL, TW_LOC, and tw_pe_fossil_collect().
Referenced by tw_net_gvt_compute().
const tw_optdef* tw_gvt_setup (void)
Definition at line 231 of file gvt-7oclock.c.
Referenced by tw_init().
void tw_gvt_start (void)
Definition at line 237 of file gvt-7oclock.c.
Referenced by tw_init().
void tw_gvt_stats (FILE * f)
Definition at line 48 of file gvt-7oclock.c.
Referenced by tw_stats().
void tw_gvt_step1 (tw_pe * me)
Definition at line 262 of file gvt-7oclock.c.
Referenced by tw_scheduler_conservative(), and tw_scheduler_optimistic().
void tw_gvt_step2 (tw_pe * me)
Definition at line 331 of file gvt-7oclock.c.
Referenced by tw_scheduler_conservative(), and tw_scheduler_optimistic().
void tw_gvt_wait (tw_pe * pe)
Definition at line 161 of file gvt-7oclock.c.
References g_tw_7oclock_node_flag, g_tw_gvt_lck, tw_pe::GVT, tw_pe::gvt_status, tw_pe::id, sim_gvt, tw_pe::trans_msg_ts, TW_GVT_NORMAL, tw_net_onnode(), and tw_pe_fossil_collect().
Referenced by tw_gvt_step2().
Variable Documentation
unsigned int CPU = 1998 static
Definition at line 30 of file gvt-7oclock.c.
Referenced by tw_gvt_start().
tw_stime delta_t = 0.01 static
Definition at line 29 of file gvt-7oclock.c.
Referenced by epi_seir_compute(), and tw_gvt_start().
unsigned int g_tw_gvt_interval = 16 static
Definition at line 20 of file gvt-7oclock.c.
Referenced by main(), tw_gvt_force_update(), tw_gvt_stats(), and tw_gvt_step1().
tw_mutex g_tw_gvt_lck = TW_MUTEX_INIT static
Definition at line 24 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), tw_gvt_set(), tw_gvt_step1(), and tw_gvt_wait().
unsigned int g_tw_gvt_max_no_change = 1000 static
Definition at line 21 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), and tw_gvt_set().
unsigned int g_tw_gvt_no_change = 0 static
Definition at line 22 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), and tw_gvt_set().
unsigned int gvt_cnt static
Definition at line 27 of file gvt-7oclock.c.
Referenced by tw_gvt_force_update(), and tw_gvt_step1().
const tw_optdef gvt_opts[] static
Initial value:
=
{
        TWOPT_GROUP("ROSS 7 O'clock GVT"),
        TWOPT_STIME("report-interval", gvt_print_interval,
                        "percent of runtime to print GVT"),
        TWOPT_STIME("delta_t", delta_t, "Max event send time (secs)"),
        TWOPT_STIME("clock-interval", secs, "GVT clock interval (in secs)"),
        TWOPT_UINT("clock-speed", CPU, "CPU clock speed (in MHz)"),
        TWOPT_UINT("gvt-interval", g_tw_gvt_interval, "GVT interval (shm only)"),
}
Definition at line 35 of file gvt-7oclock.c.
Referenced by tw_gvt_setup().
tw_stime node_lvt static
Definition at line 26 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), and tw_gvt_step2().
tw_stime secs = 0.1 static
Definition at line 28 of file gvt-7oclock.c.
Referenced by tw_gvt_start(), and tw_gvt_stats().
tw_volatile tw_stime sim_gvt static
Definition at line 25 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), tw_gvt_set(), and tw_gvt_wait().
int TW_DISTRIBUTED = 0 static
Definition at line 33 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), tw_gvt_start(), and tw_gvt_step1().
int TW_PARALLEL = 0 static
Definition at line 32 of file gvt-7oclock.c.
Referenced by tw_gvt_compute(), tw_gvt_start(), tw_gvt_step1(), and tw_gvt_step2().