ROSS: ross/gvt-mpi_allreduce.c File Reference
gvt-mpi_allreduce.c File Reference
#include <ross.h>
Macros
#define TW_GVT_NORMAL 0
#define TW_GVT_COMPUTE 1
Functions
const tw_optdef * tw_gvt_setup (void)
void tw_gvt_start (void)
void tw_gvt_force_update (tw_pe *me)
void tw_gvt_stats (FILE *f)
void tw_gvt_step1 (tw_pe *me)
void tw_gvt_step2 (tw_pe *me)
Variables
static unsigned int g_tw_gvt_max_no_change = 10000
static unsigned int g_tw_gvt_no_change = 0
static tw_stat all_reduce_cnt = 0
static unsigned int gvt_cnt = 0
static unsigned int gvt_force = 0
static const tw_optdef gvt_opts []
Macro Definition Documentation
#define TW_GVT_COMPUTE 1
Definition at line 4 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_step1(), and tw_gvt_step2().
#define TW_GVT_NORMAL 0
Definition at line 3 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_step2().
Function Documentation
void tw_gvt_force_update (tw_pe * me)
Definition at line 35 of file gvt-mpi_allreduce.c.
References g_tw_gvt_interval, gvt_cnt, gvt_force, and tw_nnodes().
const tw_optdef* tw_gvt_setup (void)
Definition at line 22 of file gvt-mpi_allreduce.c.
References gvt_cnt, and gvt_opts.
void tw_gvt_start (void)
Definition at line 30 of file gvt-mpi_allreduce.c.
References CPU, delta_t, g_tw_7oclock_node_flag, g_tw_clock_gvt_interval, g_tw_clock_gvt_window_size, g_tw_clock_max_send_delta_t, g_tw_npe, secs, TW_DISTRIBUTED, TW_MHZ, tw_nnodes(), and TW_PARALLEL.
void tw_gvt_stats (FILE * f)
Definition at line 42 of file gvt-mpi_allreduce.c.
References all_reduce_cnt, g_tw_gvt_done, g_tw_gvt_interval, g_tw_mblock, gvt_force, and secs.
void tw_gvt_step1 (tw_pe * me)
Definition at line 56 of file gvt-mpi_allreduce.c.
References g_tw_7oclock_node_flag, g_tw_clock_gvt_interval, g_tw_clock_gvt_window_size, g_tw_gvt_interval, g_tw_gvt_lck, g_tw_npe, gvt_cnt, tw_pe::gvt_status, tw_pe::id, tw_pe::local_master, tw_pe::master, tw_clock_now(), TW_DISTRIBUTED, TW_GVT_COMPUTE, TW_GVT_COMPUTE_LGVT, TW_GVT_NORMAL, tw_net_onnode(), and TW_PARALLEL.
void tw_gvt_step2 (tw_pe * me)
Definition at line 66 of file gvt-mpi_allreduce.c.
References all_reduce_cnt, g_tw_7oclock_node_flag, g_tw_gvt_done, g_tw_gvt_max_no_change, g_tw_gvt_no_change, g_tw_masternode, g_tw_mynode, g_tw_synchronization_protocol, g_tw_ts_end, tw_pe::GVT, gvt_cnt, tw_pe::GVT_prev, gvt_print(), tw_pe::gvt_status, tw_pe::id, min, node_lvt, OPTIMISTIC, percent_complete, tw_pe::pq, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_pe::s_nwhite_recv, tw_pe::s_nwhite_sent, tw_pe::stats, tw_pe::trans_msg_ts, tw_clock_read(), tw_error(), TW_GVT_COMPUTE, tw_gvt_compute(), TW_GVT_COMPUTE_LGVT, TW_GVT_NORMAL, tw_gvt_wait(), TW_GVT_WAIT_REMOTE, TW_LOC, tw_net_gvt_compute(), tw_net_minimum(), tw_net_read(), tw_node_eq(), TW_PARALLEL, tw_pe_fossil_collect(), and tw_pq_minimum().
Variable Documentation
tw_stat all_reduce_cnt = 0 static
Definition at line 8 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_stats(), and tw_gvt_step2().
unsigned int g_tw_gvt_max_no_change = 10000 static
Definition at line 6 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_step2().
unsigned int g_tw_gvt_no_change = 0 static
Definition at line 7 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_step2().
unsigned int gvt_cnt = 0 static
Definition at line 9 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_force_update(), tw_gvt_setup(), tw_gvt_step1(), and tw_gvt_step2().
unsigned int gvt_force = 0 static
Definition at line 10 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_force_update(), and tw_gvt_stats().
const tw_optdef gvt_opts[] static
Initial value:
=
{
        TWOPT_GROUP("ROSS MPI GVT"),
        TWOPT_UINT("gvt-interval", g_tw_gvt_interval, "GVT Interval"),
        TWOPT_STIME("report-interval", gvt_print_interval,
                        "percent of runtime to print GVT"),
}
Definition at line 12 of file gvt-mpi_allreduce.c.
Referenced by tw_gvt_setup().