ROSS: ross/hash-quadratic.h File Reference
hash-quadratic.h File Reference
Data Structures
struct tw_hash
Macros
#define MAX_FRACTION 0.50
Typedefs
typedef struct tw_hash tw_hash
Functions
void * tw_hash_create ()
void tw_hash_insert (void *h, tw_event *event, long pe)
tw_event * tw_hash_remove (void *h, tw_event *event, long pe)
Variables
unsigned int g_tw_hash_size
Macro Definition Documentation
#define MAX_FRACTION 0.50
Definition at line 4 of file hash-quadratic.h.
Referenced by tw_hash_insert().
Typedef Documentation
typedef struct tw_hash tw_hash
Definition at line 8 of file hash-quadratic.h.
Function Documentation
void* tw_hash_create ()
Definition at line 28 of file hash-quadratic.c.
References allocate_table(), tw_pe::avl_list, tw_pe::avl_list_head, tw_pe::avl_tree_size, g_tw_hash_size, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, is_prime(), ncpu, avlNode::next, next_prime(), tw_hash::num_stored, tw_calloc(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by tw_net_start().
void tw_hash_insert (void * h, tw_event * event, long pe)
Definition at line 74 of file hash-quadratic.c.
References tw_kp::avl_tree, tw_pe::avl_tree_size, avlInsert(), tw_event::dest_lp, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, insert(), tw_lp::kp, MAX_FRACTION, tw_hash::num_stored, pe, rehash(), tw_statistics::s_avl, tw_pe::stats, and tw_clock_read().
Referenced by recv_finish(), and tw_socket_read_event().
tw_event* tw_hash_remove (void * h, tw_event * event, long pe)
Definition at line 196 of file hash-quadratic.c.
References tw_kp::avl_tree, tw_pe::avl_tree_size, avlDelete(), tw_event::dest_lp, find_entry(), g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, tw_lp::kp, tw_hash::num_stored, pe, tw_statistics::s_avl, tw_pe::stats, tw_clock_read(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by recv_finish(), tw_eventq_push_list(), and tw_socket_read_event().
Variable Documentation
unsigned int g_tw_hash_size
Definition at line 19 of file hash-quadratic.c.
Referenced by tw_hash_create().