ROSS: core/hash-quadratic.c File Reference
core/hash-quadratic.c File Reference
#include <ross.h>
#include "avl_tree.h"
Functions
static void rehash (tw_hash *hash_t, int pe)
static int find_empty (tw_event **hash_t, tw_event *event, int hash_size)
static int find_entry (tw_event **hash_t, tw_event *event, int hash_size, int pe)
static void insert (tw_event **hash_t, tw_event *event, int hash_size)
static tw_event ** allocate_table (int hash_size)
static int hash_ (tw_eventid event_id, int hash_size)
static int next_prime (int ptst)
static int is_prime (int ptst)
tw_event * hash_search (tw_event **hash_t, tw_event *evt, int size)
void hash_print (tw_hash *h)
void * tw_hash_create ()
void tw_hash_insert (void *h, tw_event *event, long pe)
tw_event * tw_hash_remove (void *h, tw_event *event, long pe)
Variables
static unsigned int ncpu = 1
unsigned int g_tw_hash_size = 31
Function Documentation
tw_event ** allocate_table (int hash_size) [static]
Definition at line 192 of file hash-quadratic.c.
References tw_calloc(), and TW_LOC.
Referenced by rehash(), and tw_hash_create().
int find_empty (tw_event ** hash_t, tw_event * event, int hash_size) [static]
Definition at line 145 of file hash-quadratic.c.
References tw_event::event_id, hash_(), tw_error(), and TW_LOC.
Referenced by insert().
int find_entry (tw_event ** hash_t, tw_event * event, int hash_size, int pe) [static]
Definition at line 167 of file hash-quadratic.c.
References tw_event::event_id, hash_(), tw_error(), and TW_LOC.
Referenced by tw_hash_remove().
int hash_ (tw_eventid event_id, int hash_size) [static]
Definition at line 22 of file hash-quadratic.c.
Referenced by find_empty(), and find_entry().
void hash_print (tw_hash * h)
Definition at line 296 of file hash-quadratic.c.
References tw_hash::hash_sizes, tw_hash::incoming, ncpu, and tw_hash::num_stored.
tw_event * hash_search (tw_event ** hash_t, tw_event * evt, int size)
Definition at line 273 of file hash-quadratic.c.
References tw_event::event_id, and g_tw_mynode.
void insert (tw_event ** hash_t, tw_event * event, int hash_size) [static]
Definition at line 102 of file hash-quadratic.c.
References find_empty().
Referenced by rehash(), and tw_hash_insert().
int is_prime (int ptst) [static]
Definition at line 249 of file hash-quadratic.c.
Referenced by next_prime(), and tw_hash_create().
int next_prime (int ptst) [static]
Definition at line 229 of file hash-quadratic.c.
References is_prime().
Referenced by rehash(), and tw_hash_create().
void rehash (tw_hash * hash_t, int pe) [static]
Definition at line 111 of file hash-quadratic.c.
References allocate_table(), tw_hash::hash_sizes, tw_hash::incoming, insert(), next_prime(), tw_hash::num_stored, pe, tw_error(), and TW_LOC.
Referenced by tw_hash_insert().
void* tw_hash_create ()
Definition at line 28 of file hash-quadratic.c.
References allocate_table(), tw_pe::avl_list_head, tw_pe::avl_tree_size, g_tw_avl_node_count, g_tw_hash_size, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, is_prime(), ncpu, avlNode::next, next_prime(), tw_hash::num_stored, tw_calloc(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by tw_net_start().
void tw_hash_insert (void * h, tw_event * event, long pe)
Definition at line 76 of file hash-quadratic.c.
References tw_kp::avl_tree, tw_pe::avl_tree_size, avlInsert(), tw_event::dest_lp, g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, insert(), tw_lp::kp, MAX_FRACTION, tw_hash::num_stored, pe, rehash(), tw_statistics::s_avl, tw_pe::stats, and tw_clock_read().
Referenced by recv_finish().
tw_event* tw_hash_remove (void * h, tw_event * event, long pe)
Definition at line 198 of file hash-quadratic.c.
References tw_kp::avl_tree, tw_pe::avl_tree_size, avlDelete(), tw_event::dest_lp, find_entry(), g_tw_pe, tw_hash::hash_sizes, tw_hash::incoming, tw_lp::kp, tw_hash::num_stored, pe, tw_statistics::s_avl, tw_pe::stats, tw_clock_read(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by recv_finish(), and tw_eventq_push_list().
Variable Documentation
unsigned int g_tw_hash_size = 31
Definition at line 19 of file hash-quadratic.c.
Referenced by tw_hash_create().
unsigned int ncpu = 1 [static]
Definition at line 18 of file hash-quadratic.c.
Referenced by hash_print(), and tw_hash_create().