ROSS: core/queue/heap.c File Reference
core/queue/heap.c File Reference
#include <ross.h>
Data Structures
struct tw_pq
Defines
#define KEY(e) (e->recv_ts)
#define SWAP(heap, x, y, t)
Typedefs
typedef tw_event * ELEMENT_TYPE
typedef double KEY_TYPE
Functions
void * tw_unsafe_realloc (const char *file, int line, const char *for_who, void *addr, size_t len)
static ELEMENT_TYPE HeapPeekTop (tw_pq *h)
static void sift_down (tw_pq *h, int i)
static void percolate_up (tw_pq *h, int i)
void tw_pq_enqueue (tw_pq *h, ELEMENT_TYPE e)
ELEMENT_TYPE tw_pq_dequeue (tw_pq *h)
void tw_pq_delete_any (tw_pq *h, tw_event *victim)
tw_pq * tw_pq_create (void)
tw_stime tw_pq_minimum (tw_pq *pq)
unsigned int tw_pq_get_size (tw_pq *pq)
Define Documentation
#define KEY (e) (e->recv_ts)
Definition at line 13 of file heap.c.
Referenced by percolate_up(), sift_down(), tw_pq_delete_any(), and tw_pq_minimum().
#define SWAP (heap, x, y, t)
Value:
{ \
    t = heap->elems[x]; \
    heap->elems[x] = heap->elems[y]; \
    heap->elems[y] = t; \
    heap->elems[x]->heap_index = x; \
    heap->elems[y]->heap_index = y; \
    }
Definition at line 22 of file heap.c.
Referenced by percolate_up(), and sift_down().
Typedef Documentation
typedef tw_event* ELEMENT_TYPE
Definition at line 11 of file heap.c.
typedef double KEY_TYPE
Definition at line 12 of file heap.c.
Function Documentation
static ELEMENT_TYPE HeapPeekTop (tw_pq * h) [inline, static]
Definition at line 52 of file heap.c.
References tw_pq::elems, and tw_pq::nelems.
Referenced by tw_pq_minimum().
static void percolate_up (tw_pq * h, int i) [static]
Definition at line 77 of file heap.c.
References tw_pq::elems, KEY, tw_pq::nelems, and SWAP.
Referenced by tw_pq_delete_any(), and tw_pq_enqueue().
static void sift_down (tw_pq * h, int i) [static]
Definition at line 58 of file heap.c.
References tw_pq::elems, KEY, tw_pq::nelems, and SWAP.
Referenced by tw_pq_delete_any(), and tw_pq_dequeue().
tw_pq* tw_pq_create (void)
Definition at line 181 of file heap.c.
References tw_pq::curr_max, tw_pq::elems, g_tw_events_per_pe, tw_pq::nelems, tw_calloc(), TW_LOC, and tw_unsafe_realloc().
void tw_pq_delete_any (tw_pq * h, tw_event * victim)
Definition at line 156 of file heap.c.
References tw_pq::elems, KEY, tw_pq::nelems, tw_event::owner, percolate_up(), sift_down(), and tw_event::state.
ELEMENT_TYPE tw_pq_dequeue (tw_pq * h)
Definition at line 123 of file heap.c.
References tw_pq::elems, tw_pq::nelems, tw_event::owner, sift_down(), and tw_event::state.
void tw_pq_enqueue (tw_pq * h, ELEMENT_TYPE e)
Definition at line 98 of file heap.c.
References tw_pq::curr_max, tw_pq::elems, tw_pq::nelems, tw_event::next, tw_event::owner, percolate_up(), tw_event::prev, tw_event::state, TW_LOC, TW_pe_pq, and tw_unsafe_realloc().
unsigned int tw_pq_get_size (tw_pq * pq)
Definition at line 205 of file heap.c.
References tw_pq::nelems.
tw_stime tw_pq_minimum (tw_pq * pq)
Definition at line 197 of file heap.c.
References HeapPeekTop(), and KEY.
void* tw_unsafe_realloc (const char * file, int line, const char * for_who, void * addr, size_t len)
Definition at line 32 of file heap.c.
References malloc_calls, total_allocated, and tw_error().
Referenced by tw_pq_create(), and tw_pq_enqueue().