ROSS: core/clock/ia64.c File Reference
ia64.c File Reference
#include <ross.h>
Functions
static tw_clock tw_clock_read (void)
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
Function Documentation
void tw_clock_init (tw_pe * me)
Definition at line 20 of file ia64.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
tw_clock tw_clock_now (tw_pe * me)
Definition at line 27 of file ia64.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
static tw_clock tw_clock_read (void) static
Definition at line 10 of file ia64.c.
Referenced by tw_clock_init(), and tw_clock_now().