ROSS: ross/models/traffic/Intersection.c File Reference
Intersection.c File Reference
#include <ross.h>
Data Structures
struct a_car
struct Msg_Data
struct Intersection_State
Macros
#define INTERSECTION_LPS 0
#define MAX_CARS_ON_ROAD 5
#define NUM_CELLS_X 1024
#define NUM_CELLS_Y 1024
#define NUM_VP_X 32
#define NUM_VP_Y 32
Enumerations
enum events {
ARRIVAL, LAND, DEPARTURE, ARRIVAL,
LAND, DEPARTURE, CIVILIAN = 1, BUILDING,
POWERLINE, SUBSTATION, GENERATOR, UPDATEDRAW,
UPDATEAVAILABLE, DAMAGE, REPAIR, UPDATEOCCUPANCY,
POWERON, POWEROFF, HOME, WORK,
TRAVELHOME, TRAVELWORK, TRAVELLEISURE, LEISURE,
CRISISLEVELRISES, CRISISLEVELFALLS, FINDFAMILY, EVACUATE,
SHELTER, FLIGHT, GROUP, SHOCK,
CURIOUS, TRAVELEVACUATE, RELEASEHOME, RELEASEWORK,
RELEASEHOSPITAL, HOSPITAL, TRAVELHOSPITAL, RELEASELEISURE,
ARIVAL, DEPARTURE, DIRECTION_SELECT
}
enum abs_directions {
WEST_LEFT = 0, WEST_STRAIGHT, WEST_RIGHT, EAST_LEFT,
EAST_STRAIGHT, EAST_RIGHT, NORTH_LEFT, NORTH_STRAIGHT,
NORTH_RIGHT, SOUTH_LEFT, SOUTH_STRAIGHT, SOUTH_RIGHT
}
enum ariv_dept { IN, OUT }
Functions
void Intersection_StartUp (Intersection_State *, tw_lp *)
void Intersection_EventHandler (Intersection_State *, tw_bf *, Msg_Data *, tw_lp *)
void Intersection_RC_EventHandler (Intersection_State *, tw_bf *, Msg_Data *, tw_lp *)
void Intersection_Statistics_CollectStats (Intersection_State *, tw_lp *)
tw_lpid Cell_ComputeMove (tw_lpid lpid, int direction)
tw_peid CellMapping_lp_to_pe (tw_lpid lpid)
tw_lp * CellMapping_to_lp (tw_lpid lpid)
tw_lpid CellMapping_to_local_index (tw_lpid lpid)
void traffic_grid_mapping ()
int main (int argc, char *argv[])
Variables
tw_lpid g_vp_per_proc =0
tw_lpid g_cells_per_vp_x = 1024 / 32
tw_lpid g_cells_per_vp_y = 1024 / 32
tw_lpid g_cells_per_vp = (1024 / 32)*(1024 / 32)
tw_lptype mylps []
tw_stime MEAN_SERVICE =1.0
tw_stime lookahead = 1.0
static unsigned int stagger = 0
static unsigned int offset_lpid = 0
static tw_stime mult = 1.6
static tw_stime percent_remote = 0.25
static unsigned int ttl_lps = 0
static unsigned int nlp_per_pe = 8
static int g_traffic_start_events = 15
static int optimistic_memory = 65536
static tw_stime mean = 1.0
static unsigned long long totalCars =0
static unsigned long long carsFinished =0
tw_lpid num_cells_per_kp =0
tw_lpid vp_per_proc =0
Macro Definition Documentation
#define INTERSECTION_LPS 0
Definition at line 3 of file Intersection.c.
#define MAX_CARS_ON_ROAD 5
Definition at line 5 of file Intersection.c.
Referenced by Intersection_EventHandler(), and Intersection_RC_EventHandler().
#define NUM_CELLS_X 1024
Definition at line 7 of file Intersection.c.
Referenced by Cell_ComputeMove(), CellMapping_lp_to_pe(), CellMapping_to_local_index(), CellMapping_to_lp(), main(), and traffic_grid_mapping().
#define NUM_CELLS_Y 1024
Definition at line 8 of file Intersection.c.
Referenced by Cell_ComputeMove(), main(), and traffic_grid_mapping().
#define NUM_VP_X 32
Definition at line 10 of file Intersection.c.
Referenced by CellMapping_lp_to_pe(), CellMapping_to_local_index(), CellMapping_to_lp(), main(), and traffic_grid_mapping().
#define NUM_VP_Y 32
Definition at line 11 of file Intersection.c.
Referenced by main(), and traffic_grid_mapping().
Enumeration Type Documentation
enum abs_directions
Enumerator
WEST_LEFT
WEST_STRAIGHT
WEST_RIGHT
EAST_LEFT
EAST_STRAIGHT
EAST_RIGHT
NORTH_LEFT
NORTH_STRAIGHT
NORTH_RIGHT
SOUTH_LEFT
SOUTH_STRAIGHT
SOUTH_RIGHT
Definition at line 15 of file Intersection.c.
enum ariv_dept
Enumerator
IN
OUT
Definition at line 16 of file Intersection.c.
enum events
Enumerator
ARRIVAL
LAND
DEPARTURE
ARRIVAL
LAND
DEPARTURE
CIVILIAN
BUILDING
POWERLINE
SUBSTATION
GENERATOR
UPDATEDRAW
UPDATEAVAILABLE
DAMAGE
REPAIR
UPDATEOCCUPANCY
POWERON
POWEROFF
HOME
WORK
TRAVELHOME
TRAVELWORK
TRAVELLEISURE
LEISURE
CRISISLEVELRISES
CRISISLEVELFALLS
FINDFAMILY
EVACUATE
SHELTER
FLIGHT
GROUP
SHOCK
CURIOUS
TRAVELEVACUATE
RELEASEHOME
RELEASEWORK
RELEASEHOSPITAL
HOSPITAL
TRAVELHOSPITAL
RELEASELEISURE
ARIVAL
DEPARTURE
DIRECTION_SELECT
Definition at line 13 of file Intersection.c.
Function Documentation
tw_lpid Cell_ComputeMove (tw_lpid lpid, int direction)
Definition at line 71 of file Intersection.c.
References NUM_CELLS_X, NUM_CELLS_Y, tw_error(), and TW_LOC.
tw_peid CellMapping_lp_to_pe (tw_lpid lpid)
Definition at line 116 of file Intersection.c.
References g_cells_per_vp_x, g_cells_per_vp_y, g_vp_per_proc, NUM_CELLS_X, and NUM_VP_X.
tw_lpid CellMapping_to_local_index (tw_lpid lpid)
Definition at line 148 of file Intersection.c.
References g_cells_per_vp, g_cells_per_vp_x, g_cells_per_vp_y, g_tw_nlp, g_vp_per_proc, NUM_CELLS_X, NUM_VP_X, tw_error(), and TW_LOC.
tw_lp* CellMapping_to_lp (tw_lpid lpid)
Definition at line 127 of file Intersection.c.
References g_cells_per_vp, g_cells_per_vp_x, g_cells_per_vp_y, g_tw_lp, g_tw_nlp, g_vp_per_proc, NUM_CELLS_X, NUM_VP_X, tw_error(), and TW_LOC.
void Intersection_EventHandler (Intersection_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 355 of file Intersection.c.
References ARIVAL, a_car::arrived_from, Msg_Data::car, Cell_ComputeMove(), a_car::current_lane, DEPARTURE, DIRECTION_SELECT, EAST_LEFT, EAST_RIGHT, EAST_STRAIGHT, Msg_Data::event_type, tw_lp::gid, IN, a_car::in_out, MAX_CARS_ON_ROAD, NORTH_LEFT, NORTH_RIGHT, NORTH_STRAIGHT, Intersection_State::num_in_east_left, Intersection_State::num_in_east_right, Intersection_State::num_in_east_straight, Intersection_State::num_in_north_left, Intersection_State::num_in_north_right, Intersection_State::num_in_north_straight, Intersection_State::num_in_south_left, Intersection_State::num_in_south_right, Intersection_State::num_in_south_straight, Intersection_State::num_in_west_left, Intersection_State::num_in_west_right, Intersection_State::num_in_west_straight, Intersection_State::num_out_east_left, Intersection_State::num_out_east_right, Intersection_State::num_out_east_straight, Intersection_State::num_out_north_left, Intersection_State::num_out_north_right, Intersection_State::num_out_north_straight, Intersection_State::num_out_south_left, Intersection_State::num_out_south_right, Intersection_State::num_out_south_straight, Intersection_State::num_out_west_left, Intersection_State::num_out_west_right, Intersection_State::num_out_west_straight, OUT, tw_lp::rng, a_car::sent_back, SOUTH_LEFT, SOUTH_RIGHT, SOUTH_STRAIGHT, Intersection_State::total_cars_arrived, Intersection_State::total_cars_finished, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), WEST_LEFT, WEST_RIGHT, WEST_STRAIGHT, a_car::x_to_go, and a_car::y_to_go.
void Intersection_RC_EventHandler (Intersection_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 1000 of file Intersection.c.
References ARIVAL, a_car::arrived_from, Msg_Data::car, a_car::current_lane, DEPARTURE, DIRECTION_SELECT, EAST_LEFT, EAST_RIGHT, EAST_STRAIGHT, Msg_Data::event_type, MAX_CARS_ON_ROAD, NORTH_LEFT, NORTH_RIGHT, NORTH_STRAIGHT, Intersection_State::num_in_east_left, Intersection_State::num_in_east_right, Intersection_State::num_in_east_straight, Intersection_State::num_in_north_left, Intersection_State::num_in_north_right, Intersection_State::num_in_north_straight, Intersection_State::num_in_south_left, Intersection_State::num_in_south_right, Intersection_State::num_in_south_straight, Intersection_State::num_in_west_left, Intersection_State::num_in_west_right, Intersection_State::num_in_west_straight, Intersection_State::num_out_east_left, Intersection_State::num_out_east_right, Intersection_State::num_out_east_straight, Intersection_State::num_out_north_left, Intersection_State::num_out_north_right, Intersection_State::num_out_north_straight, Intersection_State::num_out_south_left, Intersection_State::num_out_south_right, Intersection_State::num_out_south_straight, Intersection_State::num_out_west_left, Intersection_State::num_out_west_right, Intersection_State::num_out_west_straight, tw_lp::rng, SOUTH_LEFT, SOUTH_RIGHT, SOUTH_STRAIGHT, Intersection_State::total_cars_arrived, Intersection_State::total_cars_finished, tw_rand_reverse_unif, WEST_LEFT, WEST_RIGHT, WEST_STRAIGHT, a_car::x_to_go, and a_car::y_to_go.
void Intersection_StartUp (Intersection_State * SV, tw_lp * lp)
Definition at line 306 of file Intersection.c.
References ARIVAL, Msg_Data::car, a_car::current_lane, Msg_Data::event_type, g_traffic_start_events, tw_lp::gid, IN, a_car::in_out, Intersection_State::num_in_east_left, Intersection_State::num_in_east_right, Intersection_State::num_in_east_straight, Intersection_State::num_in_north_left, Intersection_State::num_in_north_right, Intersection_State::num_in_north_straight, Intersection_State::num_in_south_left, Intersection_State::num_in_south_right, Intersection_State::num_in_south_straight, Intersection_State::num_in_west_left, Intersection_State::num_in_west_right, Intersection_State::num_in_west_straight, Intersection_State::num_out_east_left, Intersection_State::num_out_east_right, Intersection_State::num_out_east_straight, Intersection_State::num_out_north_left, Intersection_State::num_out_north_right, Intersection_State::num_out_north_straight, Intersection_State::num_out_south_left, Intersection_State::num_out_south_right, Intersection_State::num_out_south_straight, Intersection_State::num_out_west_left, Intersection_State::num_out_west_right, Intersection_State::num_out_west_straight, tw_lp::rng, a_car::sent_back, Intersection_State::total_cars_arrived, Intersection_State::total_cars_finished, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), a_car::x_to_go, and a_car::y_to_go.
void Intersection_Statistics_CollectStats (Intersection_State * SV, tw_lp * lp)
Definition at line 1401 of file Intersection.c.
References Intersection_State::total_cars_arrived, and Intersection_State::total_cars_finished.
int main (int argc, char * argv[])
Definition at line 239 of file Intersection.c.
References CellMapping_to_lp(), CUSTOM, g_traffic_start_events, g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_gvt_interval, g_tw_lookahead, g_tw_mapping, g_tw_memory_nqueues, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_ts_end, g_vp_per_proc, lookahead, nlp_per_pe, NUM_CELLS_X, NUM_CELLS_Y, NUM_VP_X, NUM_VP_Y, traffic_grid_mapping(), tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_run(), and vp_per_proc.
void traffic_grid_mapping ()
Definition at line 201 of file Intersection.c.
References CellMapping_lp_to_pe(), CellMapping_to_local_index(), g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_pe, lpid, nlp_per_pe, num_cells_per_kp, NUM_CELLS_X, NUM_CELLS_Y, NUM_VP_X, NUM_VP_Y, tw_error(), tw_kp_onpe(), TW_LOC, tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_nnodes(), vp_per_proc, and x.
Referenced by main().
Variable Documentation
unsigned long long carsFinished =0 static
Definition at line 196 of file Intersection.c.
tw_lpid g_cells_per_vp = (1024 / 32)*(1024 / 32)
Definition at line 69 of file Intersection.c.
tw_lpid g_cells_per_vp_x = 1024 / 32
Definition at line 67 of file Intersection.c.
tw_lpid g_cells_per_vp_y = 1024 / 32
Definition at line 68 of file Intersection.c.
int g_traffic_start_events = 15 static
Definition at line 188 of file Intersection.c.
Referenced by Intersection_StartUp(), and main().
tw_lpid g_vp_per_proc =0
Definition at line 66 of file Intersection.c.
tw_stime lookahead = 1.0
Definition at line 181 of file Intersection.c.
tw_stime mean = 1.0 static
Definition at line 192 of file Intersection.c.
tw_stime MEAN_SERVICE =1.0
Definition at line 180 of file Intersection.c.
tw_stime mult = 1.6 static
Definition at line 184 of file Intersection.c.
tw_lptype mylps[]
Initial value:
= {
        {
                (init_f) Intersection_StartUp,
                        (event_f) Intersection_EventHandler,
                        (revent_f) Intersection_RC_EventHandler,
                        (final_f) Intersection_Statistics_CollectStats,
                        (map_f) CellMapping_lp_to_pe,
                        sizeof(Intersection_State)
        },
        { 0 },
}
Definition at line 167 of file Intersection.c.
unsigned int nlp_per_pe = 8 static
Definition at line 187 of file Intersection.c.
tw_lpid num_cells_per_kp =0
Definition at line 198 of file Intersection.c.
Referenced by main(), pcs_grid_mapping(), and traffic_grid_mapping().
unsigned int offset_lpid = 0 static
Definition at line 183 of file Intersection.c.
int optimistic_memory = 65536 static
Definition at line 189 of file Intersection.c.
tw_stime percent_remote = 0.25 static
Definition at line 185 of file Intersection.c.
unsigned int stagger = 0 static
Definition at line 182 of file Intersection.c.
unsigned long long totalCars =0 static
Definition at line 195 of file Intersection.c.
unsigned int ttl_lps = 0 static
Definition at line 186 of file Intersection.c.
tw_lpid vp_per_proc =0
Definition at line 199 of file Intersection.c.
Referenced by main(), olsr_grid_mapping(), pcs_grid_mapping(), and traffic_grid_mapping().