ROSS: core/rio/io-mpi.c File Reference
io-mpi.c File Reference
#include <assert.h>
#include "ross.h"
Functions
void io_register_model_version (char *sha1)
tw_event * io_event_grab (tw_pe *pe)
void io_event_cancel (tw_event *e)
void io_init ()
void io_appending_job ()
void io_load_checkpoint (char *master_filename, io_load_type load_at)
void io_read_checkpoint ()
void io_load_events (tw_pe *me)
void io_store_checkpoint (char *master_filename, int data_file_number)
Variables
int g_io_number_of_files = 1
const tw_optdef io_opts []
io_partition * g_io_partitions
io_lptype * g_io_lp_types = NULL
io_load_type g_io_load_at = NONE
char g_io_checkpoint_name [1024]
int g_io_events_buffered_per_rank = 0
tw_eventq g_io_buffered_events
tw_eventq g_io_free_events
static unsigned long l_io_kp_offset = 0
static unsigned long l_io_lp_offset = 0
static unsigned long l0_io_total_kp = 0
static unsigned long l0_io_total_lp = 0
static unsigned long l_io_min_parts = 0
static int l_io_init_flag = 0
static int l_io_append_flag = 0
char model_version [41]
Function Documentation
io_appending_job()
void io_appending_job ()
Definition at line 101 of file io-mpi.c.
References l_io_append_flag, and l_io_init_flag.
io_event_cancel()
void io_event_cancel (tw_event * e)
Definition at line 70 of file io-mpi.c.
References g_io_buffered_events, g_io_free_events, tw_eventq_delete_any(), and tw_eventq_push().
Referenced by event_cancel().
io_event_grab()
tw_event * io_event_grab (tw_pe * pe)
Definition at line 42 of file io-mpi.c.
References tw_event::cancel_next, tw_event::cause_next, tw_event::caused_by_me, tw_event::event_id, g_io_buffered_events, g_io_events_buffered_per_rank, g_io_free_events, l_io_init_flag, tw_event::next, tw_event::owner, pe, tw_event::prev, tw_event::state, tw_clock_read(), tw_eventq_pop(), and tw_eventq_push().
Referenced by tw_event_new_user_prio().
io_init()
void io_init ()
Definition at line 75 of file io-mpi.c.
References g_io_buffered_events, g_io_free_events, g_io_number_of_files, g_tw_mynode, g_tw_nkp, g_tw_nlp, l0_io_total_kp, l0_io_total_lp, l_io_init_flag, l_io_kp_offset, l_io_lp_offset, and l_io_min_parts.
io_load_checkpoint()
void io_load_checkpoint (char * master_filename, io_load_type load_at)
Definition at line 107 of file io-mpi.c.
References g_io_checkpoint_name, and g_io_load_at.
io_load_events()
void io_load_events (tw_pe * me)
Definition at line 227 of file io-mpi.c.
References tw_pe::abort_event, tw_event::caused_by_me, tw_pe::cev_abort, tw_pe::cur_event, tw_event::cv, tw_event::dest_lp, g_io_buffered_events, g_io_free_events, g_tw_lookahead, g_tw_msg_sz, tw_event::recv_ts, tw_event::src_lp, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_eventq_pop(), tw_eventq_push(), and TW_LOC.
Referenced by tw_sched_init().
io_read_checkpoint()
void io_read_checkpoint ()
Definition at line 112 of file io-mpi.c.
References g_io_buffered_events, g_io_checkpoint_name, g_io_free_events, g_io_lp_types, g_io_number_of_files, g_tw_lp, g_tw_msg_sz, g_tw_mynode, g_tw_nkp, g_tw_nlp, io_event_deserialize(), io_lp_deserialize(), io_partition_field_count, l_io_kp_offset, l_io_lp_offset, l_io_min_parts, io_partition::lp_count, io_partition::size, tw_event_data(), tw_eventq_pop(), tw_eventq_push(), and tw_nnodes().
Referenced by tw_init_lps().
io_register_model_version()
void io_register_model_version (char * sha1)
Definition at line 38 of file io-mpi.c.
References model_version.
io_store_checkpoint()
void io_store_checkpoint (char * master_filename, int data_file_number)
Definition at line 255 of file io-mpi.c.
References io_partition::ev_count, io_partition::file, g_io_buffered_events, g_io_free_events, g_io_lp_types, g_io_number_of_files, g_tw_kp, g_tw_lp, g_tw_lp_typemap, g_tw_msg_sz, g_tw_mynode, g_tw_nkp, g_tw_nlp, io_event_serialize(), io_lp_serialize(), io_partition_field_count, l0_io_total_kp, l0_io_total_lp, l_io_append_flag, l_io_kp_offset, l_io_lp_offset, l_io_min_parts, io_partition::lp_count, model_version, io_partition::offset, io_partition::part, ROSS_VERSION, io_partition::size, tw_event_data(), tw_eventq_pop(), tw_eventq_push(), tw_nnodes(), and tw_opt_settings().
Variable Documentation
g_io_buffered_events
tw_eventq g_io_buffered_events
Definition at line 24 of file io-mpi.c.
Referenced by io_event_cancel(), io_event_grab(), io_init(), io_load_events(), io_read_checkpoint(), and io_store_checkpoint().
g_io_checkpoint_name
char g_io_checkpoint_name[1024]
Definition at line 22 of file io-mpi.c.
Referenced by io_load_checkpoint(), and io_read_checkpoint().
g_io_events_buffered_per_rank
int g_io_events_buffered_per_rank = 0
Definition at line 23 of file io-mpi.c.
Referenced by io_event_grab(), and setup_pes().
g_io_free_events
tw_eventq g_io_free_events
Definition at line 25 of file io-mpi.c.
Referenced by io_event_cancel(), io_event_grab(), io_init(), io_load_events(), io_read_checkpoint(), io_store_checkpoint(), and setup_pes().
g_io_load_at
io_load_type g_io_load_at = NONE
Definition at line 21 of file io-mpi.c.
Referenced by io_load_checkpoint(), and tw_init_lps().
g_io_lp_types
io_lptype* g_io_lp_types = NULL
Definition at line 20 of file io-mpi.c.
Referenced by io_read_checkpoint(), and io_store_checkpoint().
g_io_number_of_files
int g_io_number_of_files = 1
Definition at line 11 of file io-mpi.c.
Referenced by io_init(), io_read_checkpoint(), and io_store_checkpoint().
g_io_partitions
io_partition* g_io_partitions
Definition at line 19 of file io-mpi.c.
io_opts
const tw_optdef io_opts[]
Initial value:
= {
    TWOPT_GROUP("RIO"),
    TWOPT_UINT("io-files", g_io_number_of_files, "io files"),
}
Definition at line 12 of file io-mpi.c.
Referenced by tw_init().
l0_io_total_kp
unsigned long l0_io_total_kp = 0 static
Definition at line 30 of file io-mpi.c.
Referenced by io_init(), and io_store_checkpoint().
l0_io_total_lp
unsigned long l0_io_total_lp = 0 static
Definition at line 31 of file io-mpi.c.
Referenced by io_init(), and io_store_checkpoint().
l_io_append_flag
int l_io_append_flag = 0 static
Definition at line 34 of file io-mpi.c.
Referenced by io_appending_job(), and io_store_checkpoint().
l_io_init_flag
int l_io_init_flag = 0 static
Definition at line 33 of file io-mpi.c.
Referenced by io_appending_job(), io_event_grab(), and io_init().
l_io_kp_offset
unsigned long l_io_kp_offset = 0 static
Definition at line 28 of file io-mpi.c.
Referenced by io_init(), io_read_checkpoint(), and io_store_checkpoint().
l_io_lp_offset
unsigned long l_io_lp_offset = 0 static
Definition at line 29 of file io-mpi.c.
Referenced by io_init(), io_read_checkpoint(), and io_store_checkpoint().
l_io_min_parts
unsigned long l_io_min_parts = 0 static
Definition at line 32 of file io-mpi.c.
Referenced by io_init(), io_read_checkpoint(), and io_store_checkpoint().
model_version
char model_version[41]
Definition at line 36 of file io-mpi.c.
Referenced by io_register_model_version(), and io_store_checkpoint().