ROSS: core/rio/io-serialize.c File Reference
io-serialize.c File Reference
#include "ross.h"
Functions
size_t io_lp_serialize (tw_lp *lp, void *buffer)
size_t io_lp_deserialize (tw_lp *lp, void *buffer)
size_t io_event_serialize (tw_event *e, void *buffer)
size_t io_event_deserialize (tw_event *e, void *buffer)
Function Documentation
io_event_deserialize()
size_t io_event_deserialize (tw_event * e, void * buffer)
Definition at line 68 of file io-serialize.c.
References io_event_store::critical_path, tw_event::critical_path, CUSTOM, io_event_store::cv, tw_event::cv, io_event_store::dest_lp, tw_event::dest_lp, g_tw_custom_lp_global_to_local_map, g_tw_lp, g_tw_lp_offset, g_tw_mapping, LINEAR, io_event_store::recv_ts, tw_event::recv_ts, io_event_store::src_lp, tw_event::src_lp, tw_error(), and TW_LOC.
Referenced by io_read_checkpoint().
io_event_serialize()
size_t io_event_serialize (tw_event * e, void * buffer)
Definition at line 52 of file io-serialize.c.
References io_event_store::critical_path, tw_event::critical_path, io_event_store::cv, tw_event::cv, io_event_store::dest_lp, tw_event::dest_lp, g_tw_ts_end, tw_lp::gid, io_event_store::recv_ts, tw_event::recv_ts, io_event_store::src_lp, and tw_event::src_lp.
Referenced by io_store_checkpoint().
io_lp_deserialize()
size_t io_lp_deserialize (tw_lp * lp, void * buffer)
Definition at line 27 of file io-serialize.c.
References tw_rng_stream::Cg, io_lp_store::critical_path, tw_lp::critical_path, g_tw_nRNG_per_lp, io_lp_store::gid, tw_lp::gid, tw_rng_stream::Ig, tw_rng_stream::Lg, io_lp_store::rng, tw_lp::rng, io_lp_store::tw_normal_flipflop, tw_rng_stream::tw_normal_flipflop, io_lp_store::tw_normal_u1, tw_rng_stream::tw_normal_u1, io_lp_store::tw_normal_u2, and tw_rng_stream::tw_normal_u2.
Referenced by io_read_checkpoint().
io_lp_serialize()
size_t io_lp_serialize (tw_lp * lp, void * buffer)
Definition at line 3 of file io-serialize.c.
References tw_rng_stream::Cg, io_lp_store::critical_path, tw_lp::critical_path, g_tw_nRNG_per_lp, io_lp_store::gid, tw_lp::gid, tw_rng_stream::Ig, tw_rng_stream::Lg, io_lp_store::rng, tw_lp::rng, io_lp_store::tw_normal_flipflop, tw_rng_stream::tw_normal_flipflop, io_lp_store::tw_normal_u1, tw_rng_stream::tw_normal_u1, io_lp_store::tw_normal_u2, and tw_rng_stream::tw_normal_u2.
Referenced by io_store_checkpoint().