ROSS: ross/models/tcp-ip/ip-main.c File Reference
ip-main.c File Reference
#include <ip.h>
Functions
void ip_setup_options (int argc, char **argv)
void ip_main (int argc, char **argv, char **env)
void ip_md_final ()
Function Documentation
void ip_main (int argc, char ** argv, char ** env)
Definition at line 29 of file ip-main.c.
References g_ip_fd, g_ip_stats, g_tw_nkp, ip_setup_options(), and tw_getkp().
Referenced by main().
void ip_md_final ()
Definition at line 42 of file ip-main.c.
References g_ip_stats, g_tw_masternode, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, stats, tw_error(), tw_ismaster(), and TW_LOC.
Referenced by main().
void ip_setup_options (int argc, char ** argv)
Definition at line 4 of file ip-main.c.
References g_ip_routing_simple, g_ip_write, and ip_routing_init().
Referenced by ip_main().