ROSS: rnf/modules/application/ip-traffic/ip-traffic.c File Reference
ip-traffic.c File Reference
#include <ip-traffic.h>
Functions
void ftp_init (ftp_lp_state *state, tw_lp *lp)
void ftp_event_handler (ftp_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ftp_rc_event_handler (ftp_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ftp_final (ftp_lp_state *state, tw_lp *lp)
void ftp_statistics_print ()
Function Documentation
void ftp_event_handler (ftp_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 34 of file ip-traffic.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, tw_bf::c1, COMPLETE, DOWNSTREAM, ftp_lp_state::files_read, ftp_lp_state::files_sent, FTP_READ, FTP_SEND_TIME, g_ftp_buffer_size, g_ftp_chunk_size, g_ftp_fd, tw_lp::id, rn_event_new(), rn_event_send(), tw_lp::rng, ftp_message::size, rn_message::size, tw_error(), tw_getlp(), TW_LOC, tw_memory_alloc(), tw_memory_free(), tw_now(), tw_rand_exponential(), ftp_message::type, rn_message::type, and UPSTREAM.
void ftp_final (ftp_lp_state * state, tw_lp * lp)
Definition at line 142 of file ip-traffic.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, ftp_lp_state::files_read, ftp_lp_state::files_sent, g_ftp_stats, ftp_statistics::s_bytes_read, ftp_statistics::s_bytes_sent, ftp_statistics::s_files_read, and ftp_statistics::s_files_sent.
void ftp_init (ftp_lp_state * state, tw_lp * lp)
Definition at line 7 of file ip-traffic.c.
References ftp_lp_state::bytes_sent, DOWNSTREAM, FTP_SEND, g_ftp_chunk_size, g_ftp_fd, tw_lp::gid, tw_lp::id, rn_event_new(), rn_event_send(), tw_memory_alloc(), and ftp_message::type.
void ftp_rc_event_handler (ftp_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 111 of file ip-traffic.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, tw_bf::c1, DOWNSTREAM, ftp_lp_state::files_read, ftp_lp_state::files_sent, g_ftp_buffer_size, g_ftp_chunk_size, g_ftp_fd, tw_lp::id, tw_lp::rng, rn_message::size, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, rn_message::type, and UPSTREAM.
void ftp_statistics_print ()
Definition at line 152 of file ip-traffic.c.
References g_ftp_stats, ftp_statistics::s_bytes_read, ftp_statistics::s_bytes_sent, ftp_statistics::s_files_read, and ftp_statistics::s_files_sent.