ROSS: rnf/modules/application/ip-traffic/ip-traffic-extern.h File Reference
ip-traffic-extern.h File Reference
Functions
void ftp_statistics_print ()
void ftp_init (ftp_lp_state *state, tw_lp *lp)
void ftp_event_handler (ftp_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ftp_rc_event_handler (ftp_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ftp_final (ftp_lp_state *state, tw_lp *lp)
Variables
char * g_ftp_buffer
unsigned int g_ftp_buffer_size
unsigned int g_ftp_chunk_size
ftp_statistics g_ftp_stats
Function Documentation
void ftp_event_handler (ftp_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 37 of file ftp.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, tw_bf::c1, COMPLETE, DOWNSTREAM, ftp_lp_state::files_read, ftp_lp_state::files_sent, FTP_READ, FTP_SEND_TIME, g_ftp_buffer_size, g_ftp_chunk_size, g_ftp_fd, tw_lp::id, rn_event_new(), rn_event_send(), tw_lp::rng, ftp_message::size, rn_message::size, tw_error(), tw_getlp(), TW_LOC, tw_memory_alloc(), tw_memory_free(), tw_now(), tw_rand_exponential(), ftp_message::type, rn_message::type, and UPSTREAM.
void ftp_final (ftp_lp_state * state, tw_lp * lp)
Definition at line 157 of file ftp.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, ftp_lp_state::files_read, ftp_lp_state::files_sent, g_ftp_stats, ftp_statistics::s_bytes_read, ftp_statistics::s_bytes_sent, ftp_statistics::s_files_read, and ftp_statistics::s_files_sent.
void ftp_init (ftp_lp_state * state, tw_lp * lp)
Definition at line 7 of file ftp.c.
References ftp_lp_state::bytes_sent, DOWNSTREAM, FTP_SEND, g_ftp_chunk_size, g_ftp_fd, tw_lp::gid, tw_lp::id, rn_event_new(), rn_event_send(), tw_memory_alloc(), and ftp_message::type.
void ftp_rc_event_handler (ftp_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 119 of file ftp.c.
References ftp_lp_state::bytes_read, ftp_lp_state::bytes_sent, tw_bf::c1, DOWNSTREAM, ftp_lp_state::files_read, ftp_lp_state::files_sent, g_ftp_buffer_size, g_ftp_chunk_size, g_ftp_fd, tw_lp::id, tw_lp::rng, rn_message::size, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, rn_message::type, and UPSTREAM.
void ftp_statistics_print ()
Definition at line 167 of file ftp.c.
References g_ftp_stats, ftp_statistics::s_bytes_read, ftp_statistics::s_bytes_sent, ftp_statistics::s_files_read, and ftp_statistics::s_files_sent.
Variable Documentation
char* g_ftp_buffer
Definition at line 7 of file ftp-global.c.
unsigned int g_ftp_buffer_size
Definition at line 8 of file ftp-global.c.
unsigned int g_ftp_chunk_size
Definition at line 9 of file ftp-global.c.
ftp_statistics g_ftp_stats
Definition at line 16 of file ftp-global.c.