ROSS: ross/models/tcp-ip/tcp-main.c File Reference
tcp-main.c File Reference
#include <tcp.h>
Functions
void tcp_setup_options (int argc, char **argv)
void tcp_main (int argc, char **argv, char **env)
void tcp_md_final ()
Function Documentation
void tcp_main (int argc, char ** argv, char ** env)
Definition at line 12 of file tcp-main.c.
References g_tcp_fd, g_tcp_stats, g_tw_nkp, tcp_setup_options(), and tw_getkp().
Referenced by main().
void tcp_md_final ()
Definition at line 26 of file tcp-main.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::dropped_packets, g_tcp_f, g_tcp_stats, tcp_statistics::recv, tcp_statistics::sent, tcp_statistics::throughput, tcp_statistics::tout, and tw_ismaster().
Referenced by main().
void tcp_setup_options (int argc, char ** argv)
Definition at line 7 of file tcp-main.c.
Referenced by tcp_main().