ROSS: core/queue/kp_splay.c File Reference
core/queue/kp_splay.c File Reference
#include <ross.h>
Data Structures
struct tw_pq
struct tw_eventpq
Defines
#define UP(t) ((t)->up)
#define UPUP(t) ((t)->up->up)
#define LEFT(t) ((t)->next)
#define RIGHT(t) ((t)->prev)
#define KEY(t) ((t)->recv_ts)
#define KPKEY(t) (((tw_event *)(t)->pq->least)->recv_ts)
#define ROTATE_R(n, p, g)
#define ROTATE_L(n, p, g)
Typedefs
typedef tw_eventpq splay_tree
Functions
tw_eventpq * tw_eventpq_create (void)
tw_pq * tw_pq_create (void)
static void event_splay (tw_event *node)
static void kp_splay (tw_kp *node)
void tw_eventpq_enqueue (splay_tree *st, tw_event *e)
void tw_kp_pq_enqueue (tw_pq *st, tw_kp *e)
tw_event * tw_eventpq_dequeue (splay_tree *st)
tw_kp * tw_kp_pq_dequeue (tw_pq *st)
void tw_eventpq_delete_any (splay_tree *st, tw_event *r)
void tw_kp_pq_delete_any (tw_pq *st, tw_kp *r)
double tw_eventpq_minimum (splay_tree *pq)
double tw_pq_minimum (tw_pq *pq)
unsigned int tw_eventpq_get_size (splay_tree *st)
unsigned int tw_pq_get_size (tw_pq *st)
unsigned int tw_eventpq_max_size (splay_tree *pq)
unsigned int tw_pq_max_size (tw_pq *pq)
void tw_pq_enqueue (tw_pq *st, tw_event *e)
tw_event * tw_pq_dequeue (tw_pq *st)
void tw_pq_delete_any (tw_pq *st, tw_event *r)
Define Documentation
#define KEY (t) ((t)->recv_ts)
Definition at line 34 of file kp_splay.c.
Referenced by tw_eventpq_enqueue().
#define KPKEY (t) (((tw_event *)(t)->pq->least)->recv_ts)
Definition at line 35 of file kp_splay.c.
Referenced by tw_kp_pq_enqueue().
#define LEFT (t) ((t)->next)
Definition at line 32 of file kp_splay.c.
Referenced by event_splay(), kp_splay(), tw_eventpq_delete_any(), tw_eventpq_dequeue(), tw_eventpq_enqueue(), tw_kp_pq_delete_any(), tw_kp_pq_dequeue(), and tw_kp_pq_enqueue().
#define RIGHT (t) ((t)->prev)
Definition at line 33 of file kp_splay.c.
Referenced by event_splay(), kp_splay(), tw_eventpq_delete_any(), tw_eventpq_dequeue(), tw_eventpq_enqueue(), tw_kp_pq_delete_any(), tw_kp_pq_dequeue(), and tw_kp_pq_enqueue().
#define ROTATE_L (n, p, g)
Value:
if((RIGHT(p) = LEFT(n))) UP(LEFT(n)) = p;  LEFT(n) = p; \
  UP(n) = g;  UP(p) = n;
Definition at line 57 of file kp_splay.c.
Referenced by event_splay(), and kp_splay().
#define ROTATE_R (n, p, g)
Value:
if((LEFT(p) = RIGHT(n))) UP(RIGHT(n)) = p;  RIGHT(n) = p; \
  UP(n) = g;  UP(p) = n;
Definition at line 53 of file kp_splay.c.
Referenced by event_splay(), and kp_splay().
#define UP (t) ((t)->up)
Definition at line 30 of file kp_splay.c.
Referenced by event_splay(), kp_splay(), tw_eventpq_delete_any(), tw_eventpq_dequeue(), tw_eventpq_enqueue(), tw_kp_pq_delete_any(), tw_kp_pq_dequeue(), and tw_kp_pq_enqueue().
#define UPUP (t) ((t)->up->up)
Definition at line 31 of file kp_splay.c.
Referenced by event_splay(), and kp_splay().
Typedef Documentation
typedef tw_eventpq splay_tree
Definition at line 51 of file kp_splay.c.
Function Documentation
static void event_splay (tw_event * node) [static]
Definition at line 85 of file kp_splay.c.
References LEFT, RIGHT, ROTATE_L, ROTATE_R, UP, and UPUP.
Referenced by tw_eventpq_delete_any(), and tw_eventpq_enqueue().
static void kp_splay (tw_kp * node) [static]
Definition at line 183 of file kp_splay.c.
References LEFT, RIGHT, ROTATE_L, ROTATE_R, UP, and UPUP.
Referenced by tw_kp_pq_delete_any(), and tw_kp_pq_enqueue().
tw_eventpq* tw_eventpq_create (void)
Definition at line 62 of file kp_splay.c.
References tw_eventpq::least, tw_eventpq::nitems, tw_eventpq::root, tw_calloc(), and TW_LOC.
Referenced by tw_kp_onpe().
void tw_eventpq_delete_any (splay_tree * st, tw_event * r)
Definition at line 465 of file kp_splay.c.
References event_splay(), tw_eventpq::least, LEFT, tw_eventpq::nitems, tw_event::owner, RIGHT, tw_eventpq::root, tw_event::state, tw_error(), tw_eventpq_dequeue(), TW_LOC, and UP.
Referenced by tw_pq_delete_any().
tw_event* tw_eventpq_dequeue (splay_tree * st)
Definition at line 379 of file kp_splay.c.
References tw_eventpq::least, LEFT, tw_eventpq::nitems, tw_event::owner, RIGHT, tw_eventpq::root, tw_event::state, and UP.
Referenced by tw_eventpq_delete_any(), and tw_pq_dequeue().
void tw_eventpq_enqueue (splay_tree * st, tw_event * e)
Definition at line 280 of file kp_splay.c.
References event_splay(), KEY, tw_eventpq::least, LEFT, tw_eventpq::max_size, tw_eventpq::nitems, tw_event::owner, RIGHT, tw_eventpq::root, tw_event::state, TW_pe_pq, and UP.
Referenced by tw_pq_enqueue().
unsigned int tw_eventpq_get_size (splay_tree * st)
Definition at line 590 of file kp_splay.c.
References tw_eventpq::nitems.
unsigned int tw_eventpq_max_size (splay_tree * pq)
Definition at line 601 of file kp_splay.c.
References tw_eventpq::max_size.
double tw_eventpq_minimum (splay_tree * pq)
Definition at line 577 of file kp_splay.c.
References tw_eventpq::least, and tw_event::recv_ts.
void tw_kp_pq_delete_any (tw_pq * st, tw_kp * r)
Definition at line 522 of file kp_splay.c.
References kp_splay(), tw_pq::least, LEFT, tw_pq::nitems, RIGHT, tw_pq::root, tw_error(), tw_kp_pq_dequeue(), TW_LOC, and UP.
Referenced by tw_pq_delete_any(), and tw_pq_enqueue().
tw_kp* tw_kp_pq_dequeue (tw_pq * st)
Definition at line 422 of file kp_splay.c.
References tw_pq::least, LEFT, tw_pq::nitems, RIGHT, tw_pq::root, and UP.
Referenced by tw_kp_pq_delete_any(), and tw_pq_dequeue().
void tw_kp_pq_enqueue (tw_pq * st, tw_kp * e)
Definition at line 329 of file kp_splay.c.
References kp_splay(), KPKEY, tw_pq::least, LEFT, tw_pq::max_size, tw_pq::nitems, RIGHT, tw_pq::root, and UP.
Referenced by tw_pq_delete_any(), tw_pq_dequeue(), and tw_pq_enqueue().
tw_pq* tw_pq_create (void)
Definition at line 74 of file kp_splay.c.
References tw_pq::least, tw_pq::nitems, tw_pq::root, tw_calloc(), and TW_LOC.
void tw_pq_delete_any (tw_pq * st, tw_event * r)
Definition at line 648 of file kp_splay.c.
References tw_event::dest_lp, tw_lp::kp, tw_event::next, tw_event::owner, tw_event::prev, tw_pq::Qsize, tw_event::state, tw_eventpq_delete_any(), tw_kp_pq_delete_any(), and tw_kp_pq_enqueue().
tw_event* tw_pq_dequeue (tw_pq * st)
Definition at line 625 of file kp_splay.c.
References tw_pq::BottomThreshold, tw_pq::Bucket, tw_pq::BucketTop, Delete(), tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Nbuckets, tw_event_head::next, tw_pq::nitems, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, tw_event::state, tw_error(), tw_eventpq_dequeue(), tw_kp_pq_dequeue(), tw_kp_pq_enqueue(), TW_LOC, and tw_pq::Width.
void tw_pq_enqueue (tw_pq * st, tw_event * e)
Definition at line 611 of file kp_splay.c.
References tw_pq::BucketTop, tw_event::dest_lp, Insert(), tw_lp::kp, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Nbuckets, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, tw_event::state, tw_pq::TopThreshold, tw_eventpq_enqueue(), tw_kp_pq_delete_any(), tw_kp_pq_enqueue(), TW_pe_pq, and tw_pq::Width.
unsigned int tw_pq_get_size (tw_pq * st)
Definition at line 595 of file kp_splay.c.
References tw_pq::nitems, and tw_pq::Qsize.
unsigned int tw_pq_max_size (tw_pq * pq)
Definition at line 606 of file kp_splay.c.
References tw_pq::max_size.
Referenced by gvt_print().
double tw_pq_minimum (tw_pq * pq)
Definition at line 582 of file kp_splay.c.
References tw_pq::Bucket, tw_pq::BucketTop, tw_pq::LastBucket, tw_pq::least, tw_pq::Nbuckets, tw_event_head::next, tw_pq::Qsize, tw_event::recv_ts, tw_error(), TW_LOC, and tw_pq::Width.