ROSS: ross/models/mem-test/memory.c File Reference
memory.c File Reference
#include "memory.h"
Functions
void mem_stats_print ()
void mem_fill (tw_memory *m)
void mem_verify (tw_memory *m)
tw_memory * mem_alloc (tw_lp *lp)
tw_peid mem_map (tw_lpid gid)
void mem_init (mem_state *s, tw_lp *lp)
void mem_event_handler (mem_state *s, tw_bf *bf, mem_message *m, tw_lp *lp)
void mem_event_handler_rc (mem_state *s, tw_bf *bf, mem_message *m, tw_lp *lp)
void mem_finish (mem_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 249 of file memory.c.
References g_mem_start_events, g_tw_events_per_pe, g_tw_memory_nqueues, g_tw_mynode, g_tw_npe, mem_stats_print(), mult, my_fd, nbufs, nlp_per_pe, offset_lpid, optimistic_memory, ttl_lps, tw_define_lps(), tw_end(), tw_init(), tw_lp_settype(), tw_memory_init(), tw_nnodes(), tw_opt_add(), and tw_run().
tw_memory* mem_alloc (tw_lp * lp)
Definition at line 61 of file memory.c.
References my_fd, tw_error(), TW_LOC, and tw_memory_alloc().
Referenced by mem_event_handler(), and mem_init().
void mem_event_handler (mem_state * s, tw_bf * bf, mem_message * m, tw_lp * lp)
Definition at line 109 of file memory.c.
References tw_bf::c1, tw_lp::gid, mean, mem_alloc(), mem_fill(), mem_verify(), my_fd, nbufs, offset_lpid, percent_remote, tw_lp::rng, mem_statistics::s_mem_alloc, mem_statistics::s_mem_free, mem_statistics::s_mem_get, mem_statistics::s_recv, mem_state::stats, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_memory_free(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
void mem_event_handler_rc (mem_state * s, tw_bf * bf, mem_message * m, tw_lp * lp)
Definition at line 169 of file memory.c.
References tw_bf::c1, my_fd, nbufs, tw_lp::rng, mem_statistics::s_mem_free_rc, mem_statistics::s_mem_get_rc, mem_statistics::s_rb, mem_statistics::s_recv, mem_state::stats, tw_error(), TW_LOC, tw_memory_free_rc(), and tw_rand_reverse_unif.
void mem_fill (tw_memory * m)
Definition at line 41 of file memory.c.
References mem_packet::bytes, p, and test_string.
Referenced by mem_event_handler(), and mem_init().
void mem_finish (mem_state * s, tw_lp * lp)
Definition at line 205 of file memory.c.
References g_stats, mem_statistics::s_mem_alloc, mem_statistics::s_mem_alloc_rc, mem_statistics::s_mem_free, mem_statistics::s_mem_free_rc, mem_statistics::s_mem_get, mem_statistics::s_mem_get_rc, mem_statistics::s_rb, mem_statistics::s_recv, mem_statistics::s_sent, and mem_state::stats.
void mem_init (mem_state * s, tw_lp * lp)
Definition at line 83 of file memory.c.
References g_mem_start_events, tw_lp::gid, mean, mem_alloc(), mem_fill(), my_fd, nbufs, tw_lp::rng, mem_statistics::s_mem_alloc, mem_statistics::s_sent, mem_state::stats, tw_event_new(), tw_event_send(), and tw_rand_exponential().
tw_peid mem_map (tw_lpid gid)
Definition at line 77 of file memory.c.
References nlp_per_pe.
void mem_stats_print ()
Definition at line 4 of file memory.c.
References g_stats, g_tw_masternode, mem_statistics::s_mem_alloc, mem_statistics::s_mem_alloc_rc, mem_statistics::s_mem_free, mem_statistics::s_mem_free_rc, mem_statistics::s_mem_get, mem_statistics::s_mem_get_rc, mem_statistics::s_rb, mem_statistics::s_recv, mem_statistics::s_sent, stats, tw_error(), tw_ismaster(), and TW_LOC.
Referenced by main().
void mem_verify (tw_memory * m)
Definition at line 50 of file memory.c.
References mem_packet::bytes, p, test_string, tw_error(), and TW_LOC.
Referenced by mem_event_handler().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("Memory Model"),
        TWOPT_UINT("nbuffers", nbufs, "number of memory buffers per event"),
        TWOPT_STIME("remote", percent_remote, "desired remote event rate"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_UINT("start-events", g_mem_start_events, "number of initial messages per LP"),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 234 of file memory.c.
tw_lptype mylps[]
Initial value:
=
{
        {
                (init_f) mem_init,
                (event_f) mem_event_handler,
                (revent_f) mem_event_handler_rc,
                (final_f) mem_finish,
                (map_f) mem_map,
                sizeof(mem_state)
        },
        {0},
}
Definition at line 221 of file memory.c.