ROSS: core/gvt/mpi_allreduce.h File Reference
mpi_allreduce.h File Reference
Functions
static int tw_gvt_inprogress (tw_pe *pe)
static void gvt_print (tw_stime gvt)
tw_stat st_get_allreduce_count ()
Variables
static tw_stime gvt_print_interval = 0.01
static tw_stime percent_complete = 0.0
Function Documentation
static void gvt_print (tw_stime gvt) inline static
Definition at line 14 of file mpi_allreduce.h.
References tw_pe::avl_tree_size, g_tw_gvt_done, g_tw_pe, g_tw_ts_end, gvt_print_interval, percent_complete, tw_pe::pq, ROSS_MIN, and tw_pq_max_size().
Referenced by tw_gvt_step2(), and tw_scheduler_sequential().
tw_stat st_get_allreduce_count ()
Definition at line 21 of file mpi_allreduce.c.
References all_reduce_cnt.
Referenced by st_collect_engine_data_pes().
static int tw_gvt_inprogress (tw_pe * pe) inline static
Definition at line 8 of file mpi_allreduce.h.
References tw_pe::gvt_status.
Referenced by event_cancel(), recv_begin(), recv_finish(), and tw_event_send().
Variable Documentation
tw_stime gvt_print_interval = 0.01 static
Definition at line 4 of file mpi_allreduce.h.
Referenced by gvt_print().
tw_stime percent_complete = 0.0 static
Definition at line 5 of file mpi_allreduce.h.
Referenced by gvt_print(), tw_gvt_step2(), and tw_scheduler_sequential().