ROSS: rnf/modules/network/multicast/Multicast.h File Reference
Multicast.h File Reference
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <rossnet.h>
#include "Util.h"
#include "Topo.h"
#include "Routing.h"
#include "Packet.h"
Data Structures
struct AgentStruct
struct AgentHashStruct
struct StatAgentListStruct
struct GroupOpStruct
struct TimeOutStruct
struct EventMsgStruct
struct NodeStateStruct
Macros
#define EXTRA_EVENT_PER_NODE 20 /* include timers etc */
#define KP_NUM_PER_PE 1
#define AGENT_TABLE_SIZE 100109
#define SMALL_FLOAT ((double) 0.0000000001)
#define TW_MCAST 1
Typedefs
typedef void(* PktHandler)(void *agent, void *packet)
typedef void(* StartFunc)(void *agent)
typedef void(* StopFunc)(void *agent)
typedef void(* TimerFunc)(void *agent, int timerId, int serial)
typedef void(* AgentFunc)(void *agent)
typedef struct AgentStruct Agent
typedef struct AgentHashStruct AgentHash
typedef struct StatAgentListStruct StatAgentList
typedef struct GroupOpStruct GroupOp
typedef struct TimeOutStruct TimeOut
typedef struct EventMsgStruct EventMsg
typedef struct NodeStateStruct NodeState
Enumerations
enum MessageType {
GROUP_OP = 0, DATA_PKT = 1, SEND_PKT, START_AGENT,
STOP_AGENT, AGENT_TIMER
}
enum GroupOpType { CREATE = -1, LEAVE = 0, JOIN = 1 }
Functions
void McastStartUp (NodeState *sv, tw_lp *lp)
void McastCollectStats (NodeState *sv, tw_lp *lp)
void McastEventHandler (NodeState *sv, tw_bf *cv, EventMsg *em, tw_lp *lp)
void McastRcEventHandler (NodeState *sv, tw_bf *cv, EventMsg *em, tw_lp *lp)
void ReadGroupOp (char *fileName)
int ForwardPacket (tw_lp *srcLp, tw_lp *dstLp, Packet *p, tw_stime t)
int ForwardPktOnLink (tw_lp *srcLp, Link *lnk, Packet *p)
int ForwardMulticastPkt (tw_lp *lp, Packet *p, MapUnitType *portMap)
int ForwardUnicastPkt (tw_lp *lp, Packet *p)
void PassPktToUpperLayer (tw_lp *lp, Packet *p)
Agent * RegisterAgent (int nodeId, uint32 agentId, uint32 listenAddr, PktHandler h, StartFunc startf, StopFunc stopf, TimerFunc timerf, AgentFunc statf, void *info)
void RegisterAgentCopy (Agent *agent, uint32 listenAddr)
Agent * GetAgent (int nodeId, uint32 agentId)
void UnregisterAgent (int nodeId, uint32 agentId)
void UnregisterAgentCopy (int nodeId, uint32 agentId)
Variables
tw_lptype _mylps []
AgentHash _agentTable []
char * _groupOpFileName
StatAgentList * statAgentListHead_
StatAgentList * statAgentListTail_
Macro Definition Documentation
#define AGENT_TABLE_SIZE 100109
Definition at line 20 of file Multicast.h.
Referenced by GetAgent(), RegisterAgent(), RegisterAgentCopy(), UnregisterAgent(), and UnregisterAgentCopy().
#define EXTRA_EVENT_PER_NODE 20 /* include timers etc */
Definition at line 17 of file Multicast.h.
#define KP_NUM_PER_PE 1
Definition at line 18 of file Multicast.h.
#define SMALL_FLOAT ((double) 0.0000000001)
Definition at line 22 of file Multicast.h.
Referenced by ForwardPktOnLink(), OrmccRcvPktHandler(), OrmccSrcPktHandler(), and RateSmoothAddSample().
#define TW_MCAST 1
Definition at line 117 of file Multicast.h.
Typedef Documentation
typedef struct AgentStruct Agent
typedef void(* AgentFunc)(void *agent)
Definition at line 28 of file Multicast.h.
typedef struct AgentHashStruct AgentHash
typedef struct EventMsgStruct EventMsg
typedef struct GroupOpStruct GroupOp
typedef struct NodeStateStruct NodeState
typedef void(* PktHandler)(void *agent, void *packet)
Definition at line 24 of file Multicast.h.
typedef void(* StartFunc)(void *agent)
Definition at line 25 of file Multicast.h.
typedef struct StatAgentListStruct StatAgentList
typedef void(* StopFunc)(void *agent)
Definition at line 26 of file Multicast.h.
typedef struct TimeOutStruct TimeOut
typedef void(* TimerFunc)(void *agent, int timerId, int serial)
Definition at line 27 of file Multicast.h.
Enumeration Type Documentation
enum GroupOpType
Enumerator
CREATE
LEAVE
JOIN
Definition at line 33 of file Multicast.h.
enum MessageType
Enumerator
GROUP_OP
DATA_PKT
SEND_PKT
START_AGENT
STOP_AGENT
AGENT_TIMER
Definition at line 30 of file Multicast.h.
Function Documentation
int ForwardMulticastPkt (tw_lp * lp, Packet * p, MapUnitType * portMap)
Definition at line 528 of file Multicast.c.
References _nodeTable, ForwardPktOnLink(), tw_lp::id, PacketStruct::inPort_, IsBitSet(), NodeStruct::linkNum_, NodeStruct::links_, and MAP_UNIT_SIZE.
Referenced by McastEventHandler(), SendExtPkt(), and SendPacket().
int ForwardPacket (tw_lp * srcLp, tw_lp * dstLp, Packet * p, tw_stime t) inline
Definition at line 456 of file Multicast.c.
References _addrToIdx, EventMsgStruct::content_, DATA_PKT, g_tw_ts_end, tw_lp::id, PacketStruct::inPort_, PacketStruct::od_, EventMsgStruct::pkt_, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), and tw_now().
Referenced by ForwardPktOnLink().
int ForwardPktOnLink (tw_lp * srcLp, Link * lnk, Packet * p) inline
Definition at line 489 of file Multicast.c.
References _addrToIdx, LinkStruct::bufSize_, LinkStruct::bw_, ForwardPacket(), tw_lp::id, PacketStruct::inPort_, LinkStruct::lastPktOutTime_, LinkStruct::latency_, LinkStruct::nbPort_, LinkStruct::neighbour_, PacketStruct::od_, PacketStruct::size_, SMALL_FLOAT, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, tw_getlp(), and tw_now().
Referenced by ForwardMulticastPkt(), and ForwardUnicastPkt().
int ForwardUnicastPkt (tw_lp * lp, Packet * p)
Definition at line 554 of file Multicast.c.
References PacketStruct::dstAddr_, ForwardPktOnLink(), GetFwdLink(), tw_lp::id, and tw_exit().
Referenced by McastEventHandler(), SendExtPkt(), and SendPacket().
Agent* GetAgent (int nodeId, uint32 agentId) inline
Definition at line 376 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
Referenced by GmccRcvInit(), GmccSrcInit(), OrmccRcvInit(), OrmccSrcInit(), PassPktToUpperLayer(), PgmccRcvInit(), PgmccSrcInit(), TfmccRcvInit(), and TfmccSrcInit().
void McastCollectStats (NodeState * sv, tw_lp * lp)
Definition at line 135 of file Multicast.c.
References _nodeNum, StatAgentListStruct::agent_, tw_lp::id, StatAgentListStruct::next_, and AgentStruct::statf_.
void McastEventHandler (NodeState * sv, tw_bf * cv, EventMsg * em, tw_lp * lp)
Definition at line 20 of file Multicast.c.
References _nodeTable, AddGroup(), TimeOutStruct::agent_, EventMsgStruct::agent_, AGENT_TIMER, EventMsgStruct::content_, CREATE, DATA_PKT, DelExtPkt(), PacketStruct::dstAddr_, ForwardMulticastPkt(), ForwardUnicastPkt(), GetExtPktRef(), GetFwdPortMap(), GroupOpStruct::group_, GROUP_OP, EventMsgStruct::grpOp_, HIGHEST_BIT_TEST, tw_lp::id, PacketStruct::id_, IsEmptyMap(), IsMcastAddr, JOIN, JoinGroup(), LEAVE, LeaveGroup(), GroupOpStruct::op_, p, PassPktToUpperLayer(), EventMsgStruct::pkt_, PORT_MAP_SIZE, TimeOutStruct::serial_, SetExtPktRef(), PacketStruct::srcAddr_, PacketStruct::srcAgent_, START_AGENT, AgentStruct::startf_, STOP_AGENT, AgentStruct::stopf_, EventMsgStruct::timeOut_, AgentStruct::timerf_, TimeOutStruct::timerId_, tw_exit(), and EventMsgStruct::type_.
void McastRcEventHandler (NodeState * sv, tw_bf * cv, EventMsg * em, tw_lp * lp)
Definition at line 119 of file Multicast.c.
void McastStartUp (NodeState * sv, tw_lp * lp)
Definition at line 123 of file Multicast.c.
References _AgentActFileName, _groupOpFileName, _nodeNum, tw_lp::id, ReadAgentAct(), and ReadGroupOp().
void PassPktToUpperLayer (tw_lp * lp, Packet * p)
Definition at line 568 of file Multicast.c.
References PacketStruct::dstAddr_, PacketStruct::dstAgent_, GetAgent(), GetGrpAddr4Print, AgentStruct::handler_, tw_lp::id, IsMcastAddr, and tw_exit().
Referenced by McastEventHandler().
void ReadGroupOp (char * fileName)
Definition at line 157 of file Multicast.c.
References AddGroup(), EventMsgStruct::content_, CREATE, g_tw_ts_end, GroupOpStruct::group_, GROUP_OP, EventMsgStruct::grpOp_, JOIN, JoinGroup(), LEAVE, LeaveGroup(), MAX_LINE_LEN, GroupOpStruct::op_, ReadLine(), SetGrpAddr4Prog, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlp(), and EventMsgStruct::type_.
Referenced by McastStartUp().
Agent* RegisterAgent (int nodeId, uint32 agentId, uint32 listenAddr, PktHandler h, StartFunc startf, StopFunc stopf, TimerFunc timerf, AgentFunc statf, void * info)
Definition at line 248 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, AgentStruct::handler_, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::listenAddr_, AgentStruct::nodeId_, AgentStruct::startf_, AgentStruct::statf_, AgentStruct::stopf_, AgentHashStruct::tail_, AgentStruct::timerf_, tw_exit(), and AgentStruct::used_.
Referenced by GmccRcvInit(), GmccSrcInit(), OrmccRcvInit(), OrmccSrcInit(), PgmccRcvInit(), PgmccSrcInit(), TfmccRcvInit(), and TfmccSrcInit().
void RegisterAgentCopy (Agent * agent, uint32 listenAddr)
Definition at line 321 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, AgentStruct::id_, AgentStruct::listenAddr_, AgentStruct::nodeId_, AgentHashStruct::tail_, tw_exit(), and AgentStruct::used_.
Referenced by GmccRcvJump().
void UnregisterAgent (int nodeId, uint32 agentId)
Definition at line 400 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
void UnregisterAgentCopy (int nodeId, uint32 agentId)
Definition at line 430 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
Referenced by GmccRcvLeave().
Variable Documentation
AgentHash _agentTable[]
Definition at line 4 of file Multicast.c.
char* _groupOpFileName
Definition at line 5 of file Multicast.c.
Referenced by McastStartUp().
tw_lptype _mylps[]
Definition at line 8 of file Multicast.c.
StatAgentList* statAgentListHead_
Definition at line 6 of file Multicast.c.
Referenced by ReadAgentAct().
StatAgentList * statAgentListTail_
Definition at line 6 of file Multicast.c.
Referenced by ReadAgentAct().