ROSS: rnf/modules/network/multicast/Multicast.c File Reference
Multicast.c File Reference
#include "Multicast.h"
#include "Transport.h"
Functions
void McastEventHandler (NodeState *sv, tw_bf *cv, EventMsg *em, tw_lp *lp)
void McastRcEventHandler (NodeState *sv, tw_bf *cv, EventMsg *em, tw_lp *lp)
void McastStartUp (NodeState *sv, tw_lp *lp)
void McastCollectStats (NodeState *sv, tw_lp *lp)
void ReadGroupOp (char *fileName)
Agent * RegisterAgent (int nodeId, uint32 agentId, uint32 listenAddr, PktHandler h, StartFunc startf, StopFunc stopf, TimerFunc timerf, AgentFunc statf, void *info)
void RegisterAgentCopy (Agent *agent, uint32 listenAddr)
Agent * GetAgent (int nodeId, uint32 agentId)
void UnregisterAgent (int nodeId, uint32 agentId)
void UnregisterAgentCopy (int nodeId, uint32 agentId)
int ForwardPacket (tw_lp *srcLp, tw_lp *dstLp, Packet *p, tw_stime t)
int ForwardPktOnLink (tw_lp *lp, Link *lnk, Packet *p)
int ForwardMulticastPkt (tw_lp *lp, Packet *p, MapUnitType *portMap)
int ForwardUnicastPkt (tw_lp *lp, Packet *p)
void PassPktToUpperLayer (tw_lp *lp, Packet *p)
Variables
AgentHash _agentTable [100109]
char * _groupOpFileName = NULL
StatAgentList * statAgentListHead_ = NULL
StatAgentList * statAgentListTail_ = NULL
tw_lptype _mylps []
Function Documentation
int ForwardMulticastPkt (tw_lp * lp, Packet * p, MapUnitType * portMap)
Definition at line 528 of file Multicast.c.
References _nodeTable, ForwardPktOnLink(), tw_lp::id, PacketStruct::inPort_, IsBitSet(), NodeStruct::linkNum_, NodeStruct::links_, and MAP_UNIT_SIZE.
Referenced by McastEventHandler(), SendExtPkt(), and SendPacket().
int ForwardPacket (tw_lp * srcLp, tw_lp * dstLp, Packet * p, tw_stime t) inline
Definition at line 456 of file Multicast.c.
References _addrToIdx, EventMsgStruct::content_, DATA_PKT, g_tw_ts_end, tw_lp::id, PacketStruct::inPort_, PacketStruct::od_, EventMsgStruct::pkt_, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), and tw_now().
Referenced by ForwardPktOnLink().
int ForwardPktOnLink (tw_lp * lp, Link * lnk, Packet * p) inline
Definition at line 489 of file Multicast.c.
References _addrToIdx, LinkStruct::bufSize_, LinkStruct::bw_, ForwardPacket(), tw_lp::id, PacketStruct::inPort_, LinkStruct::lastPktOutTime_, LinkStruct::latency_, LinkStruct::nbPort_, LinkStruct::neighbour_, PacketStruct::od_, PacketStruct::size_, SMALL_FLOAT, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, tw_getlp(), and tw_now().
Referenced by ForwardMulticastPkt(), and ForwardUnicastPkt().
int ForwardUnicastPkt (tw_lp * lp, Packet * p)
Definition at line 554 of file Multicast.c.
References PacketStruct::dstAddr_, ForwardPktOnLink(), GetFwdLink(), tw_lp::id, and tw_exit().
Referenced by McastEventHandler(), SendExtPkt(), and SendPacket().
Agent* GetAgent (int nodeId, uint32 agentId) inline
Definition at line 376 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
Referenced by GmccRcvInit(), GmccSrcInit(), OrmccRcvInit(), OrmccSrcInit(), PassPktToUpperLayer(), PgmccRcvInit(), PgmccSrcInit(), TfmccRcvInit(), and TfmccSrcInit().
void McastCollectStats (NodeState * sv, tw_lp * lp)
Definition at line 135 of file Multicast.c.
References _nodeNum, StatAgentListStruct::agent_, tw_lp::id, StatAgentListStruct::next_, and AgentStruct::statf_.
void McastEventHandler (NodeState * sv, tw_bf * cv, EventMsg * em, tw_lp * lp)
Definition at line 20 of file Multicast.c.
References _nodeTable, AddGroup(), TimeOutStruct::agent_, EventMsgStruct::agent_, AGENT_TIMER, EventMsgStruct::content_, CREATE, DATA_PKT, DelExtPkt(), PacketStruct::dstAddr_, ForwardMulticastPkt(), ForwardUnicastPkt(), GetExtPktRef(), GetFwdPortMap(), GroupOpStruct::group_, GROUP_OP, EventMsgStruct::grpOp_, HIGHEST_BIT_TEST, tw_lp::id, PacketStruct::id_, IsEmptyMap(), IsMcastAddr, JOIN, JoinGroup(), LEAVE, LeaveGroup(), GroupOpStruct::op_, p, PassPktToUpperLayer(), EventMsgStruct::pkt_, PORT_MAP_SIZE, TimeOutStruct::serial_, SetExtPktRef(), PacketStruct::srcAddr_, PacketStruct::srcAgent_, START_AGENT, AgentStruct::startf_, STOP_AGENT, AgentStruct::stopf_, EventMsgStruct::timeOut_, AgentStruct::timerf_, TimeOutStruct::timerId_, tw_exit(), and EventMsgStruct::type_.
void McastRcEventHandler (NodeState * sv, tw_bf * cv, EventMsg * em, tw_lp * lp)
Definition at line 119 of file Multicast.c.
void McastStartUp (NodeState * sv, tw_lp * lp)
Definition at line 123 of file Multicast.c.
References _AgentActFileName, _groupOpFileName, _nodeNum, tw_lp::id, ReadAgentAct(), and ReadGroupOp().
void PassPktToUpperLayer (tw_lp * lp, Packet * p)
Definition at line 568 of file Multicast.c.
References PacketStruct::dstAddr_, PacketStruct::dstAgent_, GetAgent(), GetGrpAddr4Print, AgentStruct::handler_, tw_lp::id, IsMcastAddr, and tw_exit().
Referenced by McastEventHandler().
void ReadGroupOp (char * fileName)
Definition at line 157 of file Multicast.c.
References AddGroup(), EventMsgStruct::content_, CREATE, g_tw_ts_end, GroupOpStruct::group_, GROUP_OP, EventMsgStruct::grpOp_, JOIN, JoinGroup(), LEAVE, LeaveGroup(), MAX_LINE_LEN, GroupOpStruct::op_, ReadLine(), SetGrpAddr4Prog, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlp(), and EventMsgStruct::type_.
Referenced by McastStartUp().
Agent* RegisterAgent (int nodeId, uint32 agentId, uint32 listenAddr, PktHandler h, StartFunc startf, StopFunc stopf, TimerFunc timerf, AgentFunc statf, void * info)
Definition at line 248 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, AgentStruct::handler_, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::listenAddr_, AgentStruct::nodeId_, AgentStruct::startf_, AgentStruct::statf_, AgentStruct::stopf_, AgentHashStruct::tail_, AgentStruct::timerf_, tw_exit(), and AgentStruct::used_.
Referenced by GmccRcvInit(), GmccSrcInit(), OrmccRcvInit(), OrmccSrcInit(), PgmccRcvInit(), PgmccSrcInit(), TfmccRcvInit(), and TfmccSrcInit().
void RegisterAgentCopy (Agent * agent, uint32 listenAddr)
Definition at line 321 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, AgentStruct::id_, AgentStruct::listenAddr_, AgentStruct::nodeId_, AgentHashStruct::tail_, tw_exit(), and AgentStruct::used_.
Referenced by GmccRcvJump().
void UnregisterAgent (int nodeId, uint32 agentId)
Definition at line 400 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
void UnregisterAgentCopy (int nodeId, uint32 agentId)
Definition at line 430 of file Multicast.c.
References AgentHashStruct::agent_, AGENT_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, AgentHashStruct::head_, and AgentHashStruct::tail_.
Referenced by GmccRcvLeave().
Variable Documentation
AgentHash _agentTable[100109]
Definition at line 4 of file Multicast.c.
char* _groupOpFileName = NULL
Definition at line 5 of file Multicast.c.
Referenced by McastStartUp().
tw_lptype _mylps[]
Initial value:
=
{
        { 1 , sizeof (NodeState),
        (init_f) McastStartUp,
        (event_f) McastEventHandler,
        (revent_f) McastRcEventHandler,
        (final_f) McastCollectStats,
        (statecp_f) NULL},
        {0},
}
Definition at line 8 of file Multicast.c.
StatAgentList* statAgentListHead_ = NULL
Definition at line 6 of file Multicast.c.
Referenced by ReadAgentAct().
StatAgentList * statAgentListTail_ = NULL
Definition at line 6 of file Multicast.c.
Referenced by ReadAgentAct().