ROSS: ross/old/network-tcp.c File Reference
network-tcp.c File Reference
#include <ross.h>
#include "socket-tcp.h"
Functions
void network_spawn (char *next_node)
const tw_optdef * tw_net_init (int *argc, char ***argv)
void init_socket (int i, int node_index, char **temp_hostname, int node_id)
void tw_net_start (void)
void tw_net_cancel (tw_event *event)
unsigned int tw_nnodes (void)
void tw_net_send_lvt (tw_pe *pe, tw_stime LVT)
void tw_net_gvt_compute (tw_pe *pe, tw_stime *LVT)
void tw_net_read (tw_pe *pe)
void tw_net_send (tw_event *event)
void tw_net_barrier (tw_pe *pe)
void tw_net_stop (void)
void send_stats (tw_statistics *s)
void recv_stats (tw_statistics *s)
void tw_net_abort (void)
tw_statistics * tw_net_statistics (tw_pe *me, tw_statistics *s)
Function to output the statistics.
Variables
unsigned short int * pe_map
int pid
tw_port g_tw_port = 9000
unsigned int * g_tw_node_ids = NULL
char ** g_tw_hosts = 0
char ** g_tw_hostname = 0
char g_tw_dist_logdir [1024] = "logs/"
char g_tw_net_config [1024] = ".ross_network"
tw_net_node * g_tw_gvt_node = 0
tw_net_node * g_tw_barrier_node = 0
tw_net_node ** g_tw_net_node = 0
tw_net_stats overall
char my_hostname [256]
static char ross [4096]
static uintptr_t read_buffer
int nnodes = 0
int npe = 0
int nnet_nodes = 0
static unsigned int g_tw_net_barrier_flag = 0
static const tw_optdef tcp_opts []
static int client = 0
Function Documentation
void init_socket (int i, int node_index, char ** temp_hostname, int node_id)
Definition at line 75 of file network-tcp.c.
References tw_net_node::clients, g_tw_npe, g_tw_pe, g_tw_port, tw_net_node::hostname, tw_net_node::id, tw_pe::id, MAX_NODES, nnet_nodes, tw_pe::node, pe, tw_net_node::port, tw_net_node::servers, tw_net_node::socket, tw_net_node::socket_fd, tw_net_node::socket_sz, tw_calloc(), TW_LOC, and tw_server_socket_create().
Referenced by tw_net_start().
void network_spawn (char * next_node)
Definition at line 767 of file network-tcp.c.
References g_tw_dist_logdir, pid, ross, tw_error(), and TW_LOC.
Referenced by tw_net_start().
void recv_stats (tw_statistics * s)
Definition at line 813 of file network-tcp.c.
References client, tw_net_node::clients, and tw_socket_read().
Referenced by tw_net_statistics().
void send_stats (tw_statistics * s)
Definition at line 805 of file network-tcp.c.
References tw_net_node::socket_fd, and tw_socket_send().
Referenced by tw_net_statistics().
void tw_net_abort (void)
Definition at line 820 of file network-tcp.c.
void tw_net_barrier (tw_pe * pe)
Definition at line 678 of file network-tcp.c.
References tw_net_node::clients, g_tw_mynode, g_tw_net_barrier_flag, tw_pe::id, tw_pe::local_master, nnodes, tw_net_node::socket_fd, tw_error(), TW_LOC, tw_socket_read(), and tw_socket_send().
void tw_net_cancel (tw_event * event)
Definition at line 439 of file network-tcp.c.
References tw_event::cancel_asend, tw_event::cancel_q, tw_event::dest_lp, tw_lp::id, tw_event::owner, tw_lp::pe, service_queues(), tw_pe::sevent_q, tw_event::src_lp, tw_event::state, tw_error(), tw_event_free(), tw_eventq_debug(), tw_eventq_delete_any(), tw_eventq_unshift(), TW_LOC, TW_net_acancel, TW_net_asend, TW_net_outq, tw_net_send(), and TW_pe_sevent_q.
void tw_net_gvt_compute (tw_pe * pe, tw_stime * LVT)
Definition at line 509 of file network-tcp.c.
References tw_net_node::clients, g_tw_npe, g_tw_pe, tw_pe::GVT, tw_net_stats::lgvt, tw_pe::local_master, tw_pe::master, min, nnodes, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, tw_net_node::socket_fd, stats, tw_gvt_set(), tw_socket_read(), and tw_socket_send().
Referenced by tw_gvt_step2().
const tw_optdef* tw_net_init (int * argc, char *** argv)
Definition at line 49 of file network-tcp.c.
References g_tw_masternode, g_tw_mynode, g_tw_net_device_size, mpi_opts, read_buffer, ross, tcp_opts, tw_error(), and TW_LOC.
void tw_net_read (tw_pe * pe)
Definition at line 596 of file network-tcp.c.
References tw_event::cancel_q, tw_event::dest_lp, tw_pe::event_q, tw_lp::kp, tw_kp::last_time, min, tw_event::owner, tw_lp::pe, tw_pe::pq, tw_event::recv_ts, service_queues(), tw_event::state, tw_pe::trans_msg_ts, tw_eventq_unshift(), tw_gvt_inprogress(), TW_pe_event_q, tw_pq_enqueue(), and tw_socket_read_event().
void tw_net_send (tw_event * event)
Definition at line 646 of file network-tcp.c.
References tw_event::cancel_q, tw_event::dest_lp, tw_event::event_id, tw_lp::id, tw_event::owner, tw_lp::pe, posted_sends, tw_event::remote, send_begin(), send_finish(), tw_pe::seq_num, tw_pe::sevent_q, tw_event::src_lp, tw_event::state, test_q(), tw_error(), tw_eventq_unshift(), TW_LOC, TW_net_asend, TW_net_outq, and tw_socket_send_event().
void tw_net_send_lvt (tw_pe * pe, tw_stime LVT)
Definition at line 473 of file network-tcp.c.
References g_tw_npe, g_tw_pe, tw_pe::id, tw_net_stats::lgvt, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, tw_net_node::socket_fd, stats, tw_net_onnode(), and tw_socket_send().
Referenced by tw_gvt_compute().
void tw_net_start (void)
Definition at line 109 of file network-tcp.c.
References tw_net_node::clients, g_tw_master, g_tw_masternode, g_tw_mynode, g_tw_net_barrier_flag, g_tw_net_config, g_tw_net_device_size, g_tw_node_ids, g_tw_npe, g_tw_pe, g_tw_port, g_tw_synchronization_protocol, tw_pe::hash_t, tw_net_node::hostname, tw_net_node::id, init_q(), init_socket(), MAX_NODES, my_hostname, network_spawn(), nnet_nodes, nnodes, npe, OPTIMISTIC, OPTIMISTIC_DEBUG, pe_map, tw_net_node::port, posted_recvs, posted_sends, read_buffer, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, send_buffer, tw_pe::seq_num, tw_net_node::socket, socket_accept(), tw_net_node::socket_fd, tw_net_node::socket_sz, tw_calloc(), tw_client_socket_create(), tw_error(), tw_hash_create(), TW_LOC, tw_pe_create(), tw_pe_init(), tw_server_socket_create(), tw_socket_create_mesh(), tw_socket_create_onport(), and world_size.
tw_statistics* tw_net_statistics (tw_pe * me, tw_statistics * s)
tw_net_statistics
Attention
Notice that the MPI_Reduce "count" parameter is greater than one. We are reducing on multiple variables simultaneously so if you change this function or the struct tw_statistics, you must update the other.
Definition at line 826 of file network-tcp.c.
References g_tw_masternode, max, tw_pe::node, recv_stats(), s, tw_statistics::s_avl, tw_statistics::s_max_run_time, tw_statistics::s_min_detected_offset, tw_statistics::s_net_events, tw_statistics::s_pe_event_ties, tw_statistics::s_total, send_stats(), tw_pe::stats, tw_calloc(), tw_error(), TW_LOC, tw_nnodes(), and tw_node_eq().
void tw_net_stop (void)
Definition at line 737 of file network-tcp.c.
References nnet_nodes, tw_error(), TW_LOC, and tw_socket_close().
unsigned int tw_nnodes (void)
Definition at line 464 of file network-tcp.c.
References nnodes, and world_size.
Variable Documentation
int client = 0 static
Definition at line 811 of file network-tcp.c.
Referenced by recv_stats().
tw_net_node* g_tw_barrier_node = 0
Definition at line 18 of file network-tcp.c.
char g_tw_dist_logdir[1024] = "logs/"
Definition at line 14 of file network-tcp.c.
Referenced by network_spawn().
tw_net_node* g_tw_gvt_node = 0
Definition at line 17 of file network-tcp.c.
char** g_tw_hostname = 0
Definition at line 13 of file network-tcp.c.
char** g_tw_hosts = 0
Definition at line 12 of file network-tcp.c.
unsigned int g_tw_net_barrier_flag = 0 static
Definition at line 33 of file network-tcp.c.
Referenced by tw_net_barrier(), and tw_net_start().
char g_tw_net_config[1024] = ".ross_network"
Definition at line 15 of file network-tcp.c.
Referenced by tw_net_start().
tw_net_node** g_tw_net_node = 0
Definition at line 19 of file network-tcp.c.
Referenced by tw_net_onnode(), tw_socket_create_mesh(), tw_socket_create_onport(), tw_socket_read_event(), and tw_socket_send_event().
unsigned int* g_tw_node_ids = NULL
Definition at line 8 of file network-tcp.c.
Referenced by tw_net_start().
tw_port g_tw_port = 9000
Definition at line 7 of file network-tcp.c.
Referenced by init_socket(), and tw_net_start().
char my_hostname[256]
Definition at line 24 of file network-tcp.c.
Referenced by tw_net_start().
int nnet_nodes = 0
Definition at line 31 of file network-tcp.c.
Referenced by init_socket(), tw_net_start(), tw_net_stop(), tw_socket_create_mesh(), and tw_socket_read_event().
int nnodes = 0
Definition at line 29 of file network-tcp.c.
Referenced by tw_net_barrier(), tw_net_gvt_compute(), tw_net_start(), tw_nnodes(), tw_socket_close(), and tw_socket_create_onport().
int npe = 0
Definition at line 30 of file network-tcp.c.
Referenced by FindMostSquare(), rm_getelevation(), rm_grid_terrain(), tlm_getelevation(), tlm_grid_init(), and tw_net_start().
tw_net_stats overall
Definition at line 21 of file network-tcp.c.
unsigned short int* pe_map
Definition at line 4 of file network-tcp.c.
Referenced by tw_net_pemap(), and tw_net_start().
int pid
Definition at line 6 of file network-tcp.c.
Referenced by network_spawn().
uintptr_t read_buffer static
Definition at line 27 of file network-tcp.c.
Referenced by tw_net_init().
char ross[4096] static
Definition at line 26 of file network-tcp.c.
Referenced by network_spawn(), and tw_net_init().
const tw_optdef tcp_opts[] static
Initial value:
= {
        TWOPT_GROUP("ROSS TCP Kernel"),
        TWOPT_UINT("port", g_tw_port, "Starting port offset"),
        TWOPT_UINT(
                "read-buffer",
                read_buffer,
                "network read buffer size in BYTES"),
}
Definition at line 35 of file network-tcp.c.