ROSS: ross/network-mpi2.h File Reference
network-mpi2.h File Reference
Functions
static tw_node * tw_net_onnode (tw_peid gid)
static int tw_node_eq (tw_node *a, tw_node *b)
static tw_peid tw_net_pemap (tw_peid gid)
Variables
static long id_tmp
Function Documentation
static tw_node* tw_net_onnode (tw_peid gid) inline static
Definition at line 7 of file network-mpi2.h.
References id_tmp.
Referenced by event_cancel(), rm_pe_init(), send_begin(), tw_event_send(), tw_gvt_compute(), tw_gvt_step1(), tw_gvt_wait(), and tw_net_send_lvt().
static tw_peid tw_net_pemap (tw_peid gid) inline static
Definition at line 20 of file network-mpi2.h.
static int tw_node_eq (tw_node * a, tw_node * b) inline static
Definition at line 14 of file network-mpi2.h.
Referenced by event_cancel(), recv_finish(), rm_initialize(), rm_run(), setup_pes(), tw_event_send(), tw_gvt_compute(), tw_gvt_step2(), tw_ismaster(), tw_net_statistics(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_sequential().
Variable Documentation
long id_tmp static
Definition at line 4 of file network-mpi2.h.
Referenced by tw_net_onnode().