ROSS: rnf/modules/application/num/num-init.c File Reference
num-init.c File Reference
#include <num.h>
Functions
void init_default_profiles ()
void init_profiles_from_file ()
void num_init_scenario ()
Function Documentation
void init_default_profiles ()
Definition at line 4 of file num-init.c.
References num_profile::bitrate, g_num_nprofiles, g_num_profiles, p, tw_calloc(), and TW_LOC.
Referenced by num_init_scenario().
void init_profiles_from_file ()
Definition at line 35 of file num-init.c.
References num_profile::bitrate, f, g_num_nprofiles, g_num_profiles, g_num_profiles_fn, p, tw_calloc(), tw_error(), and TW_LOC.
Referenced by num_init_scenario().
void num_init_scenario ()
Definition at line 73 of file num-init.c.