ROSS: ross/models/olsr-c/coding-error.h File Reference
coding-error.h File Reference
#include <ross.h>
Macros
#define WLAN_SIR_PERFECT 10
#define WLAN_SIR_IMPOSSIBLE 0.1
Functions
double OLSR_80211b_DsssDqpskCck11_SuccessRate (double sinr, uint32_t nbits)
Model the error rate for different modulations.
Macro Definition Documentation
#define WLAN_SIR_IMPOSSIBLE 0.1
Definition at line 4 of file coding-error.h.
#define WLAN_SIR_PERFECT 10
Definition at line 3 of file coding-error.h.
Function Documentation
double OLSR_80211b_DsssDqpskCck11_SuccessRate (double sinr, uint32_t nbits)
A packet of interest (e.g., a packet can potentially be received by the MAC) is divided into chunks. Each chunk is related to an start/end receiving event. For each chunk, it calculates the ratio (SINR) between received power of packet of interest and summation of noise and interfering power of all the other incoming packets. Then, it will calculate the success rate of the chunk based on BER of the modulation. The success reception rate of the packet is derived from the success rate of all chunks.
The 802.11b modulations:
1 Mbps mode is based on DBPSK. BER is from equation 5.2-69 from John G. Proakis Digitial Communications, 2001 edition
2 Mbps model is based on DQPSK. Equation 8 from "Tight bounds and accurate approximations for dqpsk transmission bit error rate", G. Ferrari and G.E. Corazza ELECTRONICS LETTERS, 40(20):1284-1285, September 2004
5.5 Mbps and 11 Mbps are based on equations (18) and (17) from "Properties and performance of the ieee 802.11b complementarycode-key signal sets", Michael B. Pursley and Thomas C. Royster. IEEE TRANSACTIONS ON COMMUNICATIONS, 57(2):440-449, February 2009.
More detailed description and validation can be found in http://www.nsnam.org/~pei/80211b.pdf
Definition at line 78 of file coding-error.c.
References WLAN_SIR_IMPOSSIBLE, and WLAN_SIR_PERFECT.
Referenced by olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().