ROSS: ross/models/olsr-j/olsr-test.c File Reference
olsr-test.c File Reference
#include <ross.h>
#include "unity.h"
Functions
void tearDown (void)
void setUp (void)
void test_region (void)
Function Documentation
void setUp (void)
Definition at line 8 of file olsr-test.c.
Referenced by resetTest(), and UnityDefaultTestRun().
void tearDown (void)
Definition at line 4 of file olsr-test.c.
Referenced by resetTest(), and UnityDefaultTestRun().
void test_region (void)
Definition at line 12 of file olsr-test.c.
References region(), and TEST_ASSERT_EQUAL.