ROSS: ross/models/olsr-j/olsr-driver.c File Reference
olsr-driver.c File Reference
OLSR Driver.
#include "ross.h"
#include "olsr.h"
#include <assert.h>
Macros
#define GRID_MAX 100
#define STAGGER_MAX 10
#define HELLO_DELTA 0.0001
#define OLSR_NO_FINAL_OUTPUT 1
#define USE_RADIO_DISTANCE 1
#define RWALK_INTERVAL 20
#define RANGE 60.0
Functions
unsigned region (o_addr a)
o_addr sa_master_for_level (o_addr lpid)
o_addr master_hierarchy (o_addr lpid, int level)
void olsr_init (node_state *s, tw_lp *lp)
void sa_master_init (node_state *s, tw_lp *lp)
double DoCalcRxPower (double txPowerDbm, node_state *s, olsr_msg_data *m)
static int out_of_radio_range (node_state *s, olsr_msg_data *m)
static unsigned Dy (node_state *s, o_addr target)
static void remove_node_from_n2 (o_addr n)
void mpr_set_uniq (node_state *s)
void mpr_sel_set_uniq (node_state *s)
top_tuple * FindNewerTopologyTuple (o_addr last, uint16_t ansn, node_state *s)
void EraseOlderTopologyTuples (o_addr last, uint16_t ansn, node_state *s)
top_tuple * FindTopologyTuple (o_addr destAddr, o_addr lastAddr, node_state *s)
neigh_tuple * FindSymNeighborTuple (node_state *s, o_addr mainAddr)
RT_entry * Lookup (node_state *s, o_addr dest)
void RoutingTableComputation (node_state *s)
dup_tuple * FindDuplicateTuple (o_addr addr, uint16_t seq_num, node_state *s)
void AddDuplicate (o_addr originator, uint16_t seq_num, Time ts, int retransmitted, node_state *s, tw_lp *lp)
void printTC (olsr_msg_data *m, node_state *s)
void ForwardDefault (olsr_msg_data *olsrMessage, dup_tuple *duplicated, o_addr localIface, o_addr senderAddress, node_state *s, tw_lp *lp)
OLSR's default forwarding algorithm.
void route_packet (node_state *s, tw_event *e)
void process_sa (node_state *s, olsr_msg_data *m)
void olsr_event (node_state *s, tw_bf *bf, olsr_msg_data *m, tw_lp *lp)
tw_peid olsr_map (tw_lpid gid)
void sa_master_event (node_state *s, tw_bf *bf, olsr_msg_data *m, tw_lp *lp)
void olsr_event_reverse (node_state *s, tw_bf *bf, olsr_msg_data *m, tw_lp *lp)
void sa_master_event_reverse (node_state *s, tw_bf *bf, olsr_msg_data *m, tw_lp *lp)
void olsr_final (node_state *s, tw_lp *lp)
void olsr_custom_mapping (void)
tw_lp * olsr_mapping_to_lp (tw_lpid lpid)
void null (void)
Variables
double g_X [16]
double g_Y [16]
unsigned int nlp_per_pe = 16
unsigned g_Dy [16]
unsigned g_num_one_hop
neigh_tuple g_mpr_one_hop [16]
unsigned g_num_two_hop
two_hop_neigh_tuple g_mpr_two_hop [(16 *16)]
unsigned g_reachability [16]
neigh_tuple g_mpr_neigh_to_add
unsigned g_mpr_num_add_nodes
char g_covered [((16+CHAR_BIT-1)/CHAR_BIT)]
char g_olsr_mobility = 'N'
unsigned long long g_olsr_event_stats [OLSR_END_EVENT]
unsigned long long g_olsr_root_event_stats [OLSR_END_EVENT]
char * event_names [OLSR_END_EVENT]
FILE * olsr_event_log =NULL
unsigned int SA_range_start
unsigned int nkp_per_pe
tw_lptype olsr_lps []
Detailed Description
Simple driver to test out various functionalities in the OLSR impl.
Definition in file olsr-driver.c.
Macro Definition Documentation
#define GRID_MAX 100
Definition at line 15 of file olsr-driver.c.
Referenced by olsr_event(), and olsr_init().
#define HELLO_DELTA 0.0001
Definition at line 17 of file olsr-driver.c.
Referenced by ForwardDefault(), and olsr_event().
#define OLSR_NO_FINAL_OUTPUT 1
Definition at line 18 of file olsr-driver.c.
Referenced by olsr_final().
#define RANGE 60.0
Definition at line 283 of file olsr-driver.c.
Referenced by out_of_radio_range().
#define RWALK_INTERVAL 20
Definition at line 20 of file olsr-driver.c.
Referenced by olsr_event(), and olsr_init().
#define STAGGER_MAX 10
Definition at line 16 of file olsr-driver.c.
Referenced by olsr_init().
#define USE_RADIO_DISTANCE 1
Definition at line 19 of file olsr-driver.c.
Function Documentation
void AddDuplicate (o_addr originator, uint16_t seq_num, Time ts, int retransmitted, node_state * s, tw_lp * lp)
Had to add this function to minimize our dupe array
Definition at line 626 of file olsr-driver.c.
References dup_tuple::address, node_state::dupSet, dup_tuple::expirationTime, node_state::num_dupes, OLSR_MAX_DUPES, dup_tuple::retransmitted, dup_tuple::sequenceNumber, and tw_now().
Referenced by ForwardDefault().
double DoCalcRxPower (double txPowerDbm, node_state * s, olsr_msg_data * m)
Copied from ns3 - propogation-loss-model.cc
Definition at line 219 of file olsr-driver.c.
References distance, node_state::lat, olsr_msg_data::lat, node_state::lng, olsr_msg_data::lng, node_state::local_address, olsr_msg_data::originator, and region().
Referenced by out_of_radio_range().
static unsigned Dy (node_state * s, o_addr target) inline static
Compute D(y) as described in the "MPR Computation" section. Description:
The degree of an one hop neighbor node y (where y is a member of N), is defined as the number of symmetric neighbors of node y, EXCLUDING all the members of N and EXCLUDING the node performing the computation.
N is the subset of neighbors of the node, which are neighbors of the interface I.
Definition at line 328 of file olsr-driver.c.
References neigh_tuple::neighborMainAddr, two_hop_neigh_tuple::neighborMainAddr, node_state::neighSet, node_state::num_neigh, node_state::num_two_hop, OLSR_MAX_NEIGHBORS, two_hop_neigh_tuple::twoHopNeighborAddr, and node_state::twoHopSet.
Referenced by olsr_event(), and olsr_final().
void EraseOlderTopologyTuples (o_addr last, uint16_t ansn, node_state * s)
Direct ripoff of corresponding ns3 function
Definition at line 452 of file olsr-driver.c.
References top_tuple::destAddr, top_tuple::expirationTime, top_tuple::lastAddr, node_state::num_top_set, top_tuple::sequenceNumber, and node_state::topSet.
Referenced by olsr_event().
dup_tuple* FindDuplicateTuple (o_addr addr, uint16_t seq_num, node_state * s)
Definition at line 610 of file olsr-driver.c.
References dup_tuple::address, node_state::dupSet, node_state::num_dupes, and dup_tuple::sequenceNumber.
Referenced by olsr_event().
top_tuple* FindNewerTopologyTuple (o_addr last, uint16_t ansn, node_state * s)
Direct ripoff of corresponding ns3 function
Definition at line 437 of file olsr-driver.c.
References top_tuple::lastAddr, node_state::num_top_set, top_tuple::sequenceNumber, and node_state::topSet.
Referenced by olsr_event().
neigh_tuple* FindSymNeighborTuple (node_state * s, o_addr mainAddr)
Definition at line 492 of file olsr-driver.c.
References neigh_tuple::neighborMainAddr, node_state::neighSet, and node_state::num_neigh.
Referenced by ForwardDefault(), and RoutingTableComputation().
top_tuple* FindTopologyTuple (o_addr destAddr, o_addr lastAddr, node_state * s)
Direct ripoff of corresponding ns3 function
Definition at line 479 of file olsr-driver.c.
References top_tuple::destAddr, top_tuple::lastAddr, node_state::num_top_set, and node_state::topSet.
Referenced by olsr_event().
void ForwardDefault (olsr_msg_data * olsrMessage, dup_tuple * duplicated, o_addr localIface, o_addr senderAddress, node_state * s, tw_lp * lp)
See RFC 3626 for details.
Parameters
p the OLSR packet which has been received.
msg the OLSR message which must be forwarded.
dup_tuple NULL if the message has never been considered for forwarding, or a duplicate tuple in other case.
local_iface the address of the interface where the message was received from.
Definition at line 717 of file olsr-driver.c.
References AddDuplicate(), TC::ansn, dup_tuple::expirationTime, FindSymNeighborTuple(), g_tw_lookahead, tw_lp::gid, HELLO_DELTA, node_state::lat, olsr_msg_data::lat, node_state::lng, olsr_msg_data::lng, node_state::local_address, mpr_sel_tuple::mainAddr, node_state::mprSelSet, olsr_msg_data::mt, TC::neighborAddresses, node_state::num_mpr_sel, TC::num_neighbors, OLSR_DUP_HOLD_TIME, OLSR_MAX_NEIGHBORS, olsr_msg_data::originator, region(), dup_tuple::retransmitted, tw_lp::rng, olsr_msg_data::sender, olsr_msg_data::seq_num, message_type::t, olsr_msg_data::target, TC_RX, olsr_msg_data::ttl, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlocal_lp(), tw_now(), tw_rand_unif, and olsr_msg_data::type.
Referenced by olsr_event().
RT_entry* Lookup (node_state * s, o_addr dest)
Definition at line 505 of file olsr-driver.c.
References RT_entry::destAddr, node_state::num_routes, and node_state::route_table.
Referenced by olsr_event(), route_packet(), and RoutingTableComputation().
o_addr master_hierarchy (o_addr lpid, int level)
Definition at line 77 of file olsr-driver.c.
References lpid, SA_range_start, and tw_nnodes().
Referenced by sa_master_event().
void mpr_sel_set_uniq (node_state * s)
Ensure that all nodes in MPR selector set are unique (hence "set")
Definition at line 416 of file olsr-driver.c.
References node_state::ansn, mpr_sel_tuple::mainAddr, node_state::mprSelSet, and node_state::num_mpr_sel.
Referenced by olsr_event().
void mpr_set_uniq (node_state * s)
Ensure that all nodes in MPR set are unique (hence "set")
Definition at line 397 of file olsr-driver.c.
References node_state::mprSet, and node_state::num_mpr.
Referenced by olsr_event().
void null (void)
Definition at line 2032 of file olsr-driver.c.
void olsr_custom_mapping (void)
Definition at line 1922 of file olsr-driver.c.
References g_tw_kp, g_tw_lp, g_tw_lp_offset, g_tw_mynode, g_tw_nkp, g_tw_nlp, tw_pe::id, lpid, nkp_per_pe, OLSR_MAX_NEIGHBORS, pe, region(), SA_range_start, tw_error(), tw_kp_onpe(), TW_LOC, tw_lp_onkp(), tw_lp_onpe(), tw_nnodes(), and tw_pe_next().
Referenced by main().
void olsr_event (node_state * s, tw_bf * bf, olsr_msg_data * m, tw_lp * lp)
Event handler. Basically covers two events at the moment:
HELLO_TX: HELLO transmit required now, so package up all of our neighbors into a message and send it. Also schedule our next TX
HELLO_RX: HELLO received so we just pull the neighbor's address from the message. HELLO_RX messages are generated by the last HELLO_RX message until we have exhausted all neighbors.
TC_TX: Similar to HELLO_TX but for Topology Control
TC_RX: Similar to HELLO_RX but for Topology Control
Definition at line 840 of file olsr-driver.c.
References TC::ansn, node_state::ansn, BITNSLOTS, BITSET, BITTEST, top_tuple::destAddr, olsr_msg_data::destination, Dy(), EraseOlderTopologyTuples(), top_tuple::expirationTime, FindDuplicateTuple(), FindNewerTopologyTuple(), FindTopologyTuple(), ForwardDefault(), g_covered, g_Dy, g_num_one_hop, g_num_two_hop, g_olsr_event_stats, g_reachability, g_tw_lookahead, g_tw_mynode, g_tw_synchronization_protocol, tw_lp::gid, GRID_MAX, message_type::h, HELLO_DELTA, HELLO_INTERVAL, HELLO_RX, HELLO_TX, hello::is_mpr, top_tuple::lastAddr, node_state::lat, olsr_msg_data::lat, olsr_msg_data::level, node_state::lng, olsr_msg_data::lng, node_state::local_address, Lookup(), mpr_sel_tuple::mainAddr, MASTER_NODE, MASTER_SA_INTERVAL, max, mpr_sel_set_uniq(), mpr_set_uniq(), node_state::mprSelSet, node_state::mprSet, olsr_msg_data::mt, hello::neighbor_addrs, TC::neighborAddresses, neigh_tuple::neighborMainAddr, two_hop_neigh_tuple::neighborMainAddr, node_state::neighSet, node_state::num_mpr, node_state::num_mpr_sel, node_state::num_neigh, hello::num_neighbors, TC::num_neighbors, node_state::num_top_set, node_state::num_two_hop, olsr_event_log, OLSR_MAX_2_HOP, OLSR_MAX_NEIGHBORS, OLSR_MAX_TOP_TUPLES, OPTIMISTIC, olsr_msg_data::originator, out_of_radio_range(), printTC(), process_sa(), region(), remove_node_from_n2(), tw_lp::rng, rng_write_state(), route_packet(), RoutingTableComputation(), RWALK_CHANGE, RWALK_INTERVAL, SA_INTERVAL, sa_master_for_level(), SA_MASTER_RX, SA_MASTER_TX, SA_range_start, SA_RX, SA_TX, olsr_msg_data::sender, olsr_msg_data::seq_num, top_tuple::sequenceNumber, olsr_msg_data::state_copy, message_type::t, olsr_msg_data::target, TC_INTERVAL, TC_RX, TC_TX, TOP_HOLD_TIME, node_state::topSet, olsr_msg_data::ttl, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlocal_lp(), tw_nnodes(), tw_now(), tw_rand_unif, two_hop_neigh_tuple::twoHopNeighborAddr, node_state::twoHopSet, and olsr_msg_data::type.
void olsr_event_reverse (node_state * s, tw_bf * bf, olsr_msg_data * m, tw_lp * lp)
Definition at line 1823 of file olsr-driver.c.
References g_olsr_event_stats, g_tw_synchronization_protocol, OPTIMISTIC, olsr_msg_data::state_copy, and olsr_msg_data::type.
void olsr_final (node_state * s, tw_lp * lp)
Definition at line 1845 of file olsr-driver.c.
References top_tuple::destAddr, RT_entry::destAddr, RT_entry::distance, Dy(), top_tuple::lastAddr, node_state::lat, node_state::lng, node_state::local_address, node_state::mprSet, neigh_tuple::neighborMainAddr, two_hop_neigh_tuple::neighborMainAddr, node_state::neighSet, RT_entry::nextAddr, node_state::num_mpr, node_state::num_mpr_sel, node_state::num_neigh, node_state::num_routes, node_state::num_top_set, node_state::num_two_hop, OLSR_MAX_NEIGHBORS, OLSR_NO_FINAL_OUTPUT, node_state::route_table, node_state::SA_per_node, top_tuple::sequenceNumber, node_state::topSet, two_hop_neigh_tuple::twoHopNeighborAddr, and node_state::twoHopSet.
void olsr_init (node_state * s, tw_lp * lp)
Initializer for OLSR
Definition at line 107 of file olsr-driver.c.
References olsr_msg_data::destination, g_olsr_mobility, g_tw_lookahead, tw_lp::gid, GRID_MAX, message_type::h, HELLO_TX, node_state::lat, olsr_msg_data::lat, node_state::lng, olsr_msg_data::lng, node_state::local_address, MASTER_NODE, MASTER_SA_INTERVAL, olsr_msg_data::mt, node_state::num_dupes, node_state::num_mpr, node_state::num_mpr_sel, node_state::num_neigh, hello::num_neighbors, TC::num_neighbors, node_state::num_top_set, node_state::num_two_hop, olsr_event_log, OLSR_MAX_NEIGHBORS, olsr_msg_data::originator, tw_lp::rng, rng_write_state(), RWALK_CHANGE, RWALK_INTERVAL, SA_INTERVAL, sa_master_for_level(), SA_MASTER_TX, node_state::SA_per_node, SA_TX, STAGGER_MAX, message_type::t, TC_TX, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_unif, and olsr_msg_data::type.
tw_peid olsr_map (tw_lpid gid)
tw_lp* olsr_mapping_to_lp (tw_lpid lpid)
Definition at line 2002 of file olsr-driver.c.
References g_tw_lp, g_tw_nlp, lpid, OLSR_MAX_NEIGHBORS, SA_range_start, and tw_nnodes().
Referenced by main().
static int out_of_radio_range (node_state * s, olsr_msg_data * m) inline static
Definition at line 285 of file olsr-driver.c.
References DoCalcRxPower(), node_state::lat, olsr_msg_data::lat, node_state::lng, olsr_msg_data::lng, node_state::local_address, OLSR_MPR_POWER, olsr_msg_data::originator, RANGE, and region().
Referenced by olsr_event().
void printTC (olsr_msg_data * m, node_state * s)
Definition at line 685 of file olsr-driver.c.
References node_state::local_address, olsr_msg_data::mt, TC::neighborAddresses, neigh_tuple::neighborMainAddr, node_state::neighSet, node_state::num_neigh, TC::num_neighbors, olsr_msg_data::originator, and message_type::t.
Referenced by olsr_event().
void process_sa (node_state * s, olsr_msg_data * m)
Definition at line 825 of file olsr-driver.c.
References OLSR_MAX_NEIGHBORS, olsr_msg_data::originator, and node_state::SA_per_node.
Referenced by olsr_event().
unsigned region (o_addr a)
Definition at line 53 of file olsr-driver.c.
References OLSR_MAX_NEIGHBORS.
Referenced by DoCalcRxPower(), ForwardDefault(), olsr_custom_mapping(), olsr_event(), out_of_radio_range(), sa_master_for_level(), and test_region().
static void remove_node_from_n2 (o_addr n) inline static
Remove "n" from N2 (stored in g_mpr_two_hop)
Definition at line 370 of file olsr-driver.c.
References two_hop_neigh_tuple::expirationTime, g_num_two_hop, two_hop_neigh_tuple::neighborMainAddr, and two_hop_neigh_tuple::twoHopNeighborAddr.
Referenced by olsr_event().
void route_packet (node_state * s, tw_event * e)
Definition at line 807 of file olsr-driver.c.
References olsr_msg_data::destination, node_state::local_address, Lookup(), RT_entry::nextAddr, olsr_msg_data::sender, olsr_msg_data::ttl, tw_event_data(), and tw_event_send().
Referenced by olsr_event().
void RoutingTableComputation (node_state * s)
Trying to ripoff the corresponding ns3 function :) Fortunately we don't need steps 4 or 5 since we don't support multiple interfaces or HNA.
Definition at line 523 of file olsr-driver.c.
References top_tuple::destAddr, RT_entry::destAddr, RT_entry::distance, FindSymNeighborTuple(), top_tuple::lastAddr, node_state::local_address, Lookup(), neigh_tuple::neighborMainAddr, two_hop_neigh_tuple::neighborMainAddr, node_state::neighSet, RT_entry::nextAddr, node_state::num_neigh, node_state::num_routes, node_state::num_top_set, node_state::num_two_hop, OLSR_MAX_ROUTES, node_state::route_table, node_state::topSet, two_hop_neigh_tuple::twoHopNeighborAddr, and node_state::twoHopSet.
Referenced by olsr_event().
void sa_master_event (node_state * s, tw_bf * bf, olsr_msg_data * m, tw_lp * lp)
Definition at line 1729 of file olsr-driver.c.
References olsr_msg_data::destination, g_olsr_event_stats, g_tw_synchronization_protocol, tw_lp::gid, olsr_msg_data::level, node_state::local_address, master_hierarchy(), nlp_per_pe, olsr_event_log, olsr_map(), OPTIMISTIC, olsr_msg_data::originator, tw_lp::rng, rng_write_state(), SA_MASTER_RX, SA_MASTER_TX, SA_range_start, olsr_msg_data::sender, olsr_msg_data::state_copy, tw_event_data(), tw_event_new(), tw_event_send(), tw_nnodes(), tw_now(), tw_rand_unif, olsr_msg_data::type, and x.
void sa_master_event_reverse (node_state * s, tw_bf * bf, olsr_msg_data * m, tw_lp * lp)
Definition at line 1834 of file olsr-driver.c.
References g_olsr_event_stats, g_tw_synchronization_protocol, OPTIMISTIC, olsr_msg_data::state_copy, and olsr_msg_data::type.
o_addr sa_master_for_level (o_addr lpid)
Returns the lpid of the master SA aggregator for the region containing lpid. For example, if OMN = 16 then we have 16 OLSR nodes followed by one master on each pe.
Definition at line 65 of file olsr-driver.c.
References region(), SA_range_start, and tw_nnodes().
Referenced by olsr_event(), and olsr_init().
void sa_master_init (node_state * s, tw_lp * lp)
Definition at line 204 of file olsr-driver.c.
References tw_lp::gid, node_state::local_address, olsr_event_log, tw_lp::rng, and rng_write_state().
Variable Documentation
char* event_names[OLSR_END_EVENT]
Initial value:
= {
    "HELLO_RX",
    "HELLO_TX",
    "TC_RX",
    "TC_TX",
    "SA_RX",
    "SA_TX",
    "SA_MASTER_TX",
    "SA_MASTER_RX",
    "RWALK_CHANGE"
}
Definition at line 39 of file olsr-driver.c.
Referenced by main().
char g_covered[((16+CHAR_BIT-1)/CHAR_BIT)]
Definition at line 33 of file olsr-driver.c.
Referenced by olsr_event().
unsigned g_Dy[16]
Definition at line 25 of file olsr-driver.c.
Referenced by olsr_event().
neigh_tuple g_mpr_neigh_to_add
Definition at line 31 of file olsr-driver.c.
unsigned g_mpr_num_add_nodes
Definition at line 32 of file olsr-driver.c.
neigh_tuple g_mpr_one_hop[16]
Definition at line 27 of file olsr-driver.c.
two_hop_neigh_tuple g_mpr_two_hop[(16 *16)]
Definition at line 29 of file olsr-driver.c.
unsigned g_num_one_hop
Definition at line 26 of file olsr-driver.c.
Referenced by olsr_event().
unsigned g_num_two_hop
Definition at line 28 of file olsr-driver.c.
Referenced by olsr_event(), and remove_node_from_n2().
unsigned long long g_olsr_event_stats[OLSR_END_EVENT]
Definition at line 36 of file olsr-driver.c.
Referenced by main(), olsr_event(), olsr_event_reverse(), sa_master_event(), and sa_master_event_reverse().
char g_olsr_mobility = 'N'
Definition at line 34 of file olsr-driver.c.
Referenced by olsr_init().
unsigned long long g_olsr_root_event_stats[OLSR_END_EVENT]
Definition at line 37 of file olsr-driver.c.
Referenced by main().
unsigned g_reachability[16]
Definition at line 30 of file olsr-driver.c.
Referenced by olsr_event().
double g_X[16]
Definition at line 12 of file olsr-driver.c.
double g_Y[16]
Definition at line 13 of file olsr-driver.c.
unsigned int nkp_per_pe
Definition at line 14 of file tw-setup.c.
Referenced by early_sanity_check(), map_linear(), olsr_custom_mapping(), and tw_define_lps().
unsigned int nlp_per_pe = 16
Definition at line 22 of file olsr-driver.c.
FILE* olsr_event_log =NULL
Definition at line 51 of file olsr-driver.c.
Referenced by main(), olsr_event(), olsr_init(), sa_master_event(), and sa_master_init().
tw_lptype olsr_lps[]
Initial value:
= {
    {
        (init_f) olsr_init,
        (event_f) olsr_event,
        (revent_f) olsr_event_reverse,
        (final_f) olsr_final,
        (map_f) olsr_map,
        sizeof(node_state)
    },
    {
        (init_f) sa_master_init,
        (event_f) sa_master_event,
        (revent_f) sa_master_event_reverse,
        (final_f) null,
        (map_f) olsr_map,
        sizeof(node_state)
    },
    { 0 },
}
Definition at line 2037 of file olsr-driver.c.
Referenced by main().
unsigned int SA_range_start
Definition at line 58 of file olsr-driver.c.
Referenced by main(), master_hierarchy(), olsr_custom_mapping(), olsr_event(), olsr_mapping_to_lp(), sa_master_event(), and sa_master_for_level().