ROSS: ross/models/olsr-j/olsr-main.c File Reference
olsr-main.c File Reference
#include "olsr.h"
Macros
#define olsr_main main
Functions
int main (int argc, char *argv[])
Variables
const tw_optdef olsr_opts []
Macro Definition Documentation
#define olsr_main main
Definition at line 13 of file olsr-main.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 15 of file olsr-main.c.
References CUSTOM, event_names, g_olsr_event_stats, g_olsr_root_event_stats, g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_mapping, g_tw_mynode, g_tw_nlp, g_tw_synchronization_protocol, nlp_per_pe, olsr_custom_mapping(), OLSR_END_EVENT, olsr_event_log, olsr_lps, olsr_mapping_to_lp(), OLSR_MAX_NEIGHBORS, SA_range_start, tw_define_lps(), tw_end(), tw_error(), tw_init(), tw_ismaster(), TW_LOC, tw_lp_settype(), tw_opt_add(), and tw_run().
Variable Documentation
const tw_optdef olsr_opts[]
Initial value:
= {
    TWOPT_GROUP("OLSR Model"),
    TWOPT_UINT("lp_per_pe", nlp_per_pe, "number of LPs per processor"),
    TWOPT_STIME("lookahead", g_tw_lookahead, "lookahead for the simulation"),
    TWOPT_CHAR("rwalk", g_olsr_mobility, "random walk [Y/N]"),
    TWOPT_END(),
}
Definition at line 3 of file olsr-main.c.