ROSS: ross/models/olsr-c/prop-loss.c File Reference
prop-loss.c File Reference
#include "prop-loss.h"
Functions
double calcRxPower (double txPowerDbm, double distance, double lambda)
A Friis propagation loss model.
double dbmFromW (double w)
double wFromDbm (double dbm)
double ratioToDb (double ratio)
double calculateSnr (rf_signal rf)
Function Documentation
double calcRxPower (double txPowerDbm, double distance, double lambda)
The Friis propagation loss model was first described in "A Note on a Simple Transmission Formula", by "Harald T. Friis".
The original equation was described as: with the following equation for the case of an isotropic antenna with no heat loss:
The final equation becomes:
Modern extensions to this original equation are:
Here, we ignore tx and rx gain and the input and output values are in dB or dBm:
With:
: reception power (W)
: transmission power (W)
: transmission gain (unit-less)
: reception gain (unit-less)
: wavelength (m)
: distance (m)
: system loss (unit-less)
This model is invalid for small distance values. The current implementation returns the txpower as the rxpower for any distance smaller than MinDistance.
MinDistance is defined as follows: (Paul, Whites, Nasir, Intro. to Electromagnetic Fields) Picking a typical value of 16 for k, and assuming a 1/4 wavelength antenna MinDistance becomes:
Definition at line 9 of file prop-loss.c.
Referenced by main(), olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().
double calculateSnr (rf_signal rf)
< thermal noise at 290K in J/s = W
Definition at line 37 of file prop-loss.c.
Referenced by olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().
double dbmFromW (double w)
Definition at line 23 of file prop-loss.c.
double ratioToDb (double ratio)
Definition at line 33 of file prop-loss.c.
double wFromDbm (double dbm)
Definition at line 28 of file prop-loss.c.