ROSS: ross/models/olsr-c/olsr.c File Reference
olsr.c File Reference
#include <ross.h>
#include "olsr.h"
Functions
tw_peid olsr_map (tw_lpid gid)
double olsr_hello_time (olsr_region_state *s)
void olsr_region_init (olsr_region_state *s, tw_lp *lp)
void olsr_region_event_handler (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_region_event_handler_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_station_to_mpr (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_station_to_mpr_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_arrival_to_mpr (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_arrival_to_mpr_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_departure_from_mpr (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_departure_from_mpr_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_change_mpr (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_change_mpr_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_change_region (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_change_region_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_region_finish (olsr_region_state *s, tw_lp *lp)
tw_lp * olsr_map_to_lp (tw_lpid lpid)
tw_lpid olsr_map_to_local_index (tw_lpid lpid)
void olsr_grid_mapping ()
void olsr_move (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
void olsr_move_rc (olsr_region_state *s, tw_bf *bf, olsr_message *m, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 888 of file olsr.c.
References CUSTOM, g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_lookahead, g_tw_mapping, g_tw_memory_nqueues, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_vp_per_proc, lookahead, mult, nlp_per_pe, NUM_REGIONS_X, NUM_REGIONS_Y, NUM_VP_X, NUM_VP_Y, offset_lpid, olsr_grid_mapping(), olsr_map_to_lp(), OLSR_MAX_STATIONS_PER_REGION, optimistic_memory, ttl_lps, tw_define_lps(), tw_end(), tw_init(), tw_nnodes(), tw_opt_add(), tw_run(), and vp_per_proc.
void olsr_arrival_to_mpr (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 415 of file olsr.c.
References tw_bf::c1, olsr_message::contention_window, tw_lp::gid, olsr_message::hop_count, olsr_message::max_hop_count, olsr_region_state::mpr, olsr_message::mpr, OLSR_DEPARTURE_FROM_MPR, OLSR_MPR_PACKET_SERVICE_TIME, olsr_mpr_station_state::packets_delivered, tw_lp::rng, olsr_region_state::slot_busy, olsr_message::station, tw_event_data(), tw_event_new(), tw_rand_exponential(), olsr_message::type, and olsr_mpr_station_state::waiting_packets.
Referenced by olsr_region_event_handler().
void olsr_arrival_to_mpr_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 447 of file olsr.c.
References olsr_message::hop_count, olsr_message::max_hop_count, olsr_region_state::mpr, olsr_message::mpr, olsr_mpr_station_state::packets_delivered, tw_lp::rng, tw_rand_reverse_unif, and olsr_mpr_station_state::waiting_packets.
Referenced by olsr_region_event_handler_rc().
void olsr_change_mpr (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 630 of file olsr.c.
Referenced by olsr_region_event_handler().
void olsr_change_mpr_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 635 of file olsr.c.
Referenced by olsr_region_event_handler_rc().
void olsr_change_region (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 640 of file olsr.c.
References rf_signal::bandwidth, calcRxPower(), calculateGridDistance(), calculateSnr(), olsr_message::contention_window, DATA_PACKET_SIZE, distance, tw_lp::gid, LAMBDA, olsr_mpr_station_state::location, MEAN_TIME_BETWEEN_DATA_PACKETS, MEAN_TIME_BETWEEN_MOVES, olsr_region_state::mpr, olsr_message::mpr, olsr_mpr_station_state::my_mpr, olsr_mpr_station_state::next_move_time, olsr_message::next_move_time, rf_signal::noiseFigure, rf_signal::noiseInterference, NUM_REGIONS_X, NUM_REGIONS_Y, olsr_region_state::num_stations, OLSR_80211b_DsssDqpskCck11_SuccessRate(), OLSR_CHANGE_REGION, OLSR_EAST, OLSR_MAX_MPRS_PER_REGION, OLSR_MAX_STATIONS_PER_REGION, OLSR_MPR_POWER, OLSR_NORTH, OLSR_SOUTH, OLSR_STATION_TO_MPR, OLSR_WEST, olsr_region_state::region_location, REGION_SIZE, tw_lp::rng, rf_signal::signal, olsr_mpr_station_state::snr, olsr_region_state::station, olsr_message::station, olsr_region_state::station_drops, STATION_SLOT_BUSY, STATION_SLOT_FREE, olsr_region_state::station_status, olsr_mpr_station_state::success_rate, olsr_message::success_rate, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, olsr_mpr_station_state::tx_power, olsr_message::type, WIFIB_BW, tw_grid_pt::x, tw_integer_grid_pt::x, tw_grid_pt::y, and tw_integer_grid_pt::y.
Referenced by olsr_region_event_handler().
void olsr_change_region_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 766 of file olsr.c.
References olsr_mpr_station_state::next_move_time, olsr_message::next_move_time, olsr_region_state::num_stations, OLSR_MAX_STATIONS_PER_REGION, tw_lp::rng, olsr_region_state::station, olsr_region_state::station_drops, STATION_SLOT_FREE, olsr_region_state::station_status, olsr_mpr_station_state::success_rate, olsr_message::success_rate, and tw_rand_reverse_unif.
Referenced by olsr_region_event_handler_rc().
void olsr_departure_from_mpr (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 458 of file olsr.c.
References rf_signal::bandwidth, tw_bf::c1, calcRxPower(), calculateGridDistance(), calculateSnr(), olsr_message::contention_window, DATA_PACKET_SIZE, DATA_PACKET_TIME, distance, olsr_mpr_station_state::failed_packets, tw_lp::gid, olsr_message::hop_count, LAMBDA, olsr_mpr_station_state::location, olsr_message::max_hop_count, olsr_region_state::mpr, olsr_message::mpr, rf_signal::noiseFigure, rf_signal::noiseInterference, NUM_REGIONS_X, NUM_REGIONS_Y, OLSR_80211b_DsssDqpskCck11_SuccessRate(), OLSR_ARRIVAL_TO_MPR, OLSR_EAST, OLSR_NORTH, OLSR_SOUTH, OLSR_WEST, olsr_region_state::region_location, tw_lp::rng, rf_signal::signal, olsr_region_state::station, olsr_message::station, olsr_mpr_station_state::success_rate, success_rate, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_rand_integer(), tw_rand_unif, olsr_mpr_station_state::tx_power, olsr_message::type, WIFIB_BW, tw_integer_grid_pt::x, and tw_integer_grid_pt::y.
Referenced by olsr_region_event_handler().
void olsr_departure_from_mpr_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 606 of file olsr.c.
References tw_bf::c1, olsr_mpr_station_state::failed_packets, olsr_region_state::mpr, olsr_message::mpr, tw_lp::rng, and tw_rand_reverse_unif.
Referenced by olsr_region_event_handler_rc().
void olsr_grid_mapping ()
Definition at line 97 of file olsr.c.
References g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_pe, lpid, nlp_per_pe, NUM_REGIONS_X, NUM_REGIONS_Y, NUM_VP_X, NUM_VP_Y, olsr_map(), olsr_map_to_local_index(), tw_error(), tw_kp_onpe(), TW_LOC, tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_nnodes(), vp_per_proc, and x.
Referenced by main().
double olsr_hello_time (olsr_region_state * s)
Definition at line 292 of file olsr.c.
References HELLO_PACKET_TIME, olsr_region_state::num_mprs, and olsr_region_state::num_stations.
tw_peid olsr_map (tw_lpid gid)
Definition at line 43 of file olsr.c.
References g_regions_per_vp_x, g_regions_per_vp_y, g_vp_per_proc, NUM_REGIONS_X, and NUM_VP_X.
Referenced by olsr_grid_mapping(), and sa_master_event().
tw_lpid olsr_map_to_local_index (tw_lpid lpid)
Definition at line 77 of file olsr.c.
References g_regions_per_vp, g_regions_per_vp_x, g_regions_per_vp_y, g_tw_nlp, g_vp_per_proc, NUM_REGIONS_X, NUM_VP_X, tw_error(), and TW_LOC.
Referenced by olsr_grid_mapping().
tw_lp* olsr_map_to_lp (tw_lpid lpid)
Definition at line 55 of file olsr.c.
References g_regions_per_vp, g_regions_per_vp_x, g_regions_per_vp_y, g_tw_lp, g_tw_nlp, g_vp_per_proc, NUM_REGIONS_X, NUM_VP_X, tw_error(), and TW_LOC.
Referenced by main().
void olsr_move (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 620 of file olsr.c.
void olsr_move_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 625 of file olsr.c.
void olsr_region_event_handler (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 797 of file olsr.c.
References olsr_arrival_to_mpr(), OLSR_ARRIVAL_TO_MPR, olsr_change_mpr(), OLSR_CHANGE_MPR, olsr_change_region(), OLSR_CHANGE_REGION, olsr_departure_from_mpr(), OLSR_DEPARTURE_FROM_MPR, olsr_station_to_mpr(), OLSR_STATION_TO_MPR, tw_error(), TW_LOC, and olsr_message::type.
void olsr_region_event_handler_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 827 of file olsr.c.
References OLSR_ARRIVAL_TO_MPR, olsr_arrival_to_mpr_rc(), OLSR_CHANGE_MPR, olsr_change_mpr_rc(), OLSR_CHANGE_REGION, olsr_change_region_rc(), OLSR_DEPARTURE_FROM_MPR, olsr_departure_from_mpr_rc(), OLSR_STATION_TO_MPR, olsr_station_to_mpr_rc(), tw_error(), TW_LOC, and olsr_message::type.
void olsr_region_finish (olsr_region_state * s, tw_lp * lp)
Definition at line 857 of file olsr.c.
References olsr_mpr_station_state::failed_packets, tw_lp::gid, olsr_region_state::mpr, OLSR_MAX_MPRS_PER_REGION, OLSR_MAX_STATIONS_PER_REGION, olsr_mpr_station_state::packets_delivered, olsr_mpr_station_state::sent_packets, and olsr_region_state::station.
void olsr_region_init (olsr_region_state * s, tw_lp * lp)
Definition at line 135 of file olsr.c.
References rf_signal::bandwidth, calcRxPower(), calculateGridDistance(), calculateSnr(), olsr_message::contention_window, DATA_PACKET_SIZE, distance, olsr_mpr_station_state::failed_packets, tw_lp::gid, LAMBDA, olsr_mpr_station_state::location, MEAN_TIME_BETWEEN_DATA_PACKETS, MEAN_TIME_BETWEEN_MOVES, olsr_region_state::mpr, olsr_message::mpr, olsr_mpr_station_state::my_mpr, olsr_mpr_station_state::next_move_time, rf_signal::noiseFigure, rf_signal::noiseInterference, olsr_region_state::num_mprs, NUM_REGIONS_X, NUM_REGIONS_Y, olsr_region_state::num_stations, OLSR_80211b_DsssDqpskCck11_SuccessRate(), OLSR_CHANGE_REGION, OLSR_EAST, OLSR_MAX_MPRS_PER_REGION, OLSR_MAX_STATIONS_PER_REGION, OLSR_MPR_POWER, OLSR_NORTH, OLSR_SOUTH, OLSR_STATION_TO_MPR, OLSR_WEST, olsr_region_state::region_location, REGION_SIZE, tw_lp::rng, olsr_mpr_station_state::sent_packets, rf_signal::signal, olsr_region_state::slot_busy, olsr_mpr_station_state::snr, olsr_region_state::station, olsr_message::station, olsr_region_state::station_drops, STATION_SLOT_BUSY, olsr_region_state::station_status, olsr_mpr_station_state::success_rate, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, olsr_mpr_station_state::tx_power, olsr_message::type, olsr_mpr_station_state::waiting_packets, WIFIB_BW, tw_grid_pt::x, tw_integer_grid_pt::x, tw_grid_pt::y, and tw_integer_grid_pt::y.
void olsr_station_to_mpr (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 311 of file olsr.c.
References tw_bf::c1, olsr_message::contention_window, DATA_PACKET_TIME, olsr_mpr_station_state::failed_packets, tw_lp::gid, olsr_message::hop_count, olsr_message::max_hop_count, MEAN_TIME_BETWEEN_DATA_PACKETS, min, olsr_message::mpr, olsr_mpr_station_state::next_move_time, olsr_region_state::num_stations, OLSR_ARRIVAL_TO_MPR, OLSR_MAX_HOPS, OLSR_STATION_TO_MPR, tw_lp::rng, olsr_mpr_station_state::sent_packets, olsr_region_state::slot_busy, olsr_region_state::station, olsr_message::station, STATION_SLOT_FREE, olsr_region_state::station_status, olsr_mpr_station_state::success_rate, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, olsr_message::type, WIFI_CW_MIN, and WIFI_SLOT_TIME.
Referenced by olsr_region_event_handler().
void olsr_station_to_mpr_rc (olsr_region_state * s, tw_bf * bf, olsr_message * m, tw_lp * lp)
Definition at line 390 of file olsr.c.
References tw_bf::c1, olsr_mpr_station_state::failed_packets, olsr_mpr_station_state::next_move_time, olsr_region_state::num_stations, tw_lp::rng, olsr_mpr_station_state::sent_packets, olsr_region_state::slot_busy, olsr_region_state::station, olsr_message::station, STATION_SLOT_BUSY, olsr_region_state::station_status, tw_now(), and tw_rand_reverse_unif.
Referenced by olsr_region_event_handler_rc().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
  {
    TWOPT_GROUP("802.11b OLSR Model"),
    TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
    TWOPT_CHAR("run", run_id, "user supplied run name"),
  }
Definition at line 878 of file olsr.c.
tw_lptype mylps[]
Initial value:
=
  {
    {   (init_f) olsr_region_init,
        (event_f) olsr_region_event_handler,
        (revent_f) olsr_region_event_handler_rc,
        (final_f) olsr_region_finish,
        (map_f) olsr_map,
        sizeof(olsr_region_state)},
    {0},
  }
Definition at line 32 of file olsr.c.