ROSS: ross/models/olsr-c/mobility.h File Reference
mobility.h File Reference
Data Structures
struct tw_geo_pt
struct tw_grid_pt
struct tw_integer_grid_pt
Functions
double calculateGridDistance (tw_grid_pt pt1, tw_grid_pt pt2)
Calculate Distance on a plain grid.
Function Documentation
double calculateGridDistance (tw_grid_pt pt1, tw_grid_pt pt2)
calculateGridDistance We calculate distance on the grid using the Pythagorean theorem
Definition at line 43 of file mobility.c.
References tw_grid_pt::x, tw_grid_pt::y, and tw_grid_pt::z.
Referenced by olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().