ROSS: rnf/modules/network/multicast/ormcc.h File Reference
ormcc.h File Reference
#include "Transport.h"
#include <math.h>
Data Structures
struct RateSampleStruct
struct RateSmoothDataStruct
struct OrmccSrcInfoStruct
struct OrmccRcvInfoStruct
Macros
#define ORMCC_TEST_CR_SWITCH 1
#define ORMCC_SRC_DATA_PKT_SIZE 1000
#define ORMCC_SRC_MIN_RATE ORMCC_SRC_DATA_PKT_SIZE
#define ORMCC_SRC_INIT_RTT 0.1
#define ORMCC_SRC_INIT_RATE (2 * ORMCC_SRC_DATA_PKT_SIZE / ORMCC_SRC_INIT_RTT)
#define TRACE_ORMCC_RTT 1
#define TRACE_ORMCC_THROUGHPUT 1
#define ORMCC_THROUGHPUT_SAMPLE_ITVL 0.5
#define ORMCC_TRAC_EWMA_FACTOR 0.05
#define ORMCC_COMPARE_TRAC_FACTOR 1
#define ORMCC_RCV_CI_PKT_SIZE 40
#define RATE_SMOOTH_RING_SIZE 11
#define RATE_SMOOTH_TIME 1
Typedefs
typedef struct RateSampleStruct RateSample
typedef struct RateSmoothDataStruct RateSmoothData
typedef struct OrmccSrcInfoStruct OrmccSrcInfo
typedef struct OrmccRcvInfoStruct OrmccRcvInfo
Enumerations
enum OrmccSrcTimerType { ORMCC_SRC_TIMER_SEND_PKT, ORMCC_SRC_TIMER_RATE_INC, ORMCC_SRC_TIMER_CR_RESP, ORMCC_SRC_TIMER_CONG_EPOCH }
enum { ORMCC_RCV_CI_BACKOFF_TIMER }
Functions
Agent * OrmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
void OrmccSrcStart (Agent *agent)
void OrmccSrcStop (Agent *agent)
void OrmccSrcPktHandler (Agent *agent, Packet *p)
void OrmccSrcSendPkt (Agent *agent)
void OrmccSrcTimer (Agent *agent, int timerId, int serial)
void OrmccSrcUpdateRtt (Agent *agent, double sample)
void OrmccSrcPrintStat (Agent *agent)
Agent * OrmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
void OrmccRcvStart (Agent *agent)
void OrmccRcvStop (Agent *agent)
void OrmccRcvPktHandler (Agent *agent, Packet *p)
void OrmccRcvSendPkt (Agent *agent)
void OrmccRcvTimer (Agent *agent, int timerId, int serial)
void OrmccRcvPrintStat (Agent *agent)
void RateSmoothInit (RateSmoothData *rsd, double span)
double RateSmoothAddSample (RateSmoothData *rsd, double rate, double time)
Macro Definition Documentation
#define ORMCC_COMPARE_TRAC_FACTOR 1
Definition at line 29 of file ormcc.h.
Referenced by OrmccRcvPktHandler(), and OrmccSrcPktHandler().
#define ORMCC_RCV_CI_PKT_SIZE 40
Definition at line 31 of file ormcc.h.
Referenced by OrmccRcvSendPkt().
#define ORMCC_SRC_DATA_PKT_SIZE 1000
Definition at line 11 of file ormcc.h.
Referenced by OrmccSrcStart().
#define ORMCC_SRC_INIT_RATE (2 * ORMCC_SRC_DATA_PKT_SIZE / ORMCC_SRC_INIT_RTT)
Definition at line 15 of file ormcc.h.
Referenced by OrmccSrcStart().
#define ORMCC_SRC_INIT_RTT 0.1
Definition at line 14 of file ormcc.h.
Referenced by OrmccSrcStart().
#define ORMCC_SRC_MIN_RATE ORMCC_SRC_DATA_PKT_SIZE
Definition at line 12 of file ormcc.h.
Referenced by OrmccSrcPktHandler().
#define ORMCC_TEST_CR_SWITCH 1
Definition at line 7 of file ormcc.h.
#define ORMCC_THROUGHPUT_SAMPLE_ITVL 0.5
Definition at line 24 of file ormcc.h.
Referenced by OrmccSrcSendPkt().
#define ORMCC_TRAC_EWMA_FACTOR 0.05
Definition at line 28 of file ormcc.h.
Referenced by OrmccRcvPktHandler(), and OrmccSrcPktHandler().
#define RATE_SMOOTH_RING_SIZE 11
Definition at line 33 of file ormcc.h.
Referenced by RateSmoothAddSample(), and RateSmoothInit().
#define RATE_SMOOTH_TIME 1
Definition at line 34 of file ormcc.h.
Referenced by OrmccRcvStart().
#define TRACE_ORMCC_RTT 1
Definition at line 19 of file ormcc.h.
#define TRACE_ORMCC_THROUGHPUT 1
Definition at line 21 of file ormcc.h.
Typedef Documentation
typedef struct OrmccRcvInfoStruct OrmccRcvInfo
typedef struct OrmccSrcInfoStruct OrmccSrcInfo
typedef struct RateSampleStruct RateSample
typedef struct RateSmoothDataStruct RateSmoothData
Enumeration Type Documentation
anonymous enum
Enumerator
ORMCC_RCV_CI_BACKOFF_TIMER
Definition at line 101 of file ormcc.h.
enum OrmccSrcTimerType
Enumerator
ORMCC_SRC_TIMER_SEND_PKT
ORMCC_SRC_TIMER_RATE_INC
ORMCC_SRC_TIMER_CR_RESP
ORMCC_SRC_TIMER_CONG_EPOCH
Definition at line 55 of file ormcc.h.
Function Documentation
Agent* OrmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
Definition at line 408 of file ormcc.c.
References GetAgent(), AgentStruct::info_, IsMcastAddr, OrmccRcvPktHandler(), OrmccRcvPrintStat(), OrmccRcvStart(), OrmccRcvStop(), OrmccRcvTimer(), RegisterAgent(), and tw_exit().
Referenced by ReadAgentAct().
void OrmccRcvPktHandler (Agent * agent, Packet * p)
Definition at line 471 of file ormcc.c.
References _addrToIdx, _nodeTable, _totalOrmccCiSupp, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::ciBackoffTimerEvnt_, OrmccRcvInfoStruct::ciSchedTime_, OrmccRcvInfoStruct::ciSqn_, OrmccRcvInfoStruct::ciSupp_, OrmccRcvInfoStruct::ciTsEcho_, OrmccDataStruct::crAddr_, OrmccRcvInfoStruct::crAddr_, OrmccRcvInfoStruct::crBegTime_, OrmccDataStruct::crTracAvg_, OrmccRcvInfoStruct::crTracAvg_, OrmccDataStruct::crTracDev_, OrmccRcvInfoStruct::crTracDev_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, OrmccRcvInfoStruct::lastContSqn_, OrmccRcvInfoStruct::lastPktTime_, AgentStruct::listenAddr_, OrmccDataStruct::maxRtt_, AgentStruct::nodeId_, PacketStruct::od_, ORMCC_COMPARE_TRAC_FACTOR, ORMCC_DATA, ORMCC_RCV_CI_BACKOFF_TIMER, ORMCC_TRAC_EWMA_FACTOR, OrmccRcvSendPkt(), OrmccRcvInfoStruct::rate_, RateSmoothAddSample(), OrmccRcvInfoStruct::rsd_, ScheduleTimer(), OrmccRcvInfoStruct::senderAddr_, OrmccRcvInfoStruct::senderAgent_, PacketStruct::size_, SMALL_FLOAT, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccRcvInfoStruct::tracAvg_, OrmccDataStruct::ts_, tw_exit(), tw_getlp(), tw_now(), tw_timer_cancel(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccRcvInit().
void OrmccRcvPrintStat (Agent * agent)
Definition at line 639 of file ormcc.c.
References _totalOrmccCiSent, _totalOrmccCiSupp, OrmccRcvInfoStruct::ciSent_, OrmccRcvInfoStruct::ciSupp_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, and AgentStruct::nodeId_.
Referenced by OrmccRcvInit().
void OrmccRcvSendPkt (Agent * agent)
Definition at line 597 of file ormcc.c.
References _nodeTable, _totalOrmccCiSent, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::ciSchedTime_, OrmccRcvInfoStruct::ciSent_, OrmccRcvInfoStruct::ciSqn_, OrmccRcvInfoStruct::ciTsEcho_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, IsMcastAddr, AgentStruct::listenAddr_, AgentStruct::nodeId_, PacketStruct::oc_, ORMCC_CI, ORMCC_RCV_CI_PKT_SIZE, p, OrmccRcvInfoStruct::rate_, OrmccRcvInfoStruct::senderAddr_, OrmccRcvInfoStruct::senderAgent_, SendPacket(), PacketStruct::size_, OrmccCiStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccCiStruct::trac_, OrmccCiStruct::tsEcho_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccRcvPktHandler(), and OrmccRcvTimer().
void OrmccRcvStart (Agent * agent)
Definition at line 444 of file ormcc.c.
References _nodeTable, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::crAddr_, OrmccRcvInfoStruct::crTracAvg_, OrmccRcvInfoStruct::crTracDev_, AgentStruct::info_, OrmccRcvInfoStruct::lastContSqn_, OrmccRcvInfoStruct::lastPktTime_, AgentStruct::nodeId_, OrmccRcvInfoStruct::rate_, RATE_SMOOTH_TIME, RateSmoothInit(), OrmccRcvInfoStruct::rsd_, and OrmccRcvInfoStruct::tracAvg_.
Referenced by OrmccRcvInit().
void OrmccRcvStop (Agent * agent)
Definition at line 458 of file ormcc.c.
References OrmccRcvInfoStruct::active_, CancelTimer(), OrmccRcvInfoStruct::ciBackoffTimerEvnt_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, and IsMcastAddr.
Referenced by OrmccRcvInit().
void OrmccRcvTimer (Agent * agent, int timerId, int serial)
Definition at line 623 of file ormcc.c.
References OrmccRcvInfoStruct::ciBackoffTimerEvnt_, AgentStruct::info_, ORMCC_RCV_CI_BACKOFF_TIMER, OrmccRcvSendPkt(), and tw_exit().
Referenced by OrmccRcvInit().
Agent* OrmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
Definition at line 12 of file ormcc.c.
References _nodeTable, GetAgent(), AgentStruct::info_, OrmccSrcPktHandler(), OrmccSrcPrintStat(), OrmccSrcStart(), OrmccSrcStop(), OrmccSrcTimer(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktDstAgentId_, RegisterAgent(), OrmccSrcInfoStruct::trackStat_, and tw_exit().
Referenced by ReadAgentAct().
void OrmccSrcPktHandler (Agent * agent, Packet * p)
Definition at line 147 of file ormcc.c.
References _addrToIdx, OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::ciFromCr_, OrmccSrcInfoStruct::ciRcvd_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::nodeId_, OrmccSrcInfoStruct::notCut_, PacketStruct::oc_, ORMCC_CI, ORMCC_COMPARE_TRAC_FACTOR, ORMCC_SRC_MIN_RATE, ORMCC_SRC_TIMER_CONG_EPOCH, ORMCC_TRAC_EWMA_FACTOR, OrmccSrcUpdateRtt(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), SMALL_FLOAT, OrmccCiStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccCiStruct::trac_, OrmccSrcInfoStruct::trackStat_, OrmccCiStruct::tsEcho_, tw_exit(), tw_getlp(), tw_now(), tw_timer_cancel(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccSrcInit().
void OrmccSrcPrintStat (Agent * agent)
Definition at line 393 of file ormcc.c.
References OrmccSrcInfoStruct::ciFromCr_, OrmccSrcInfoStruct::ciRcvd_, AgentStruct::info_, and OrmccSrcInfoStruct::notCut_.
Referenced by OrmccSrcInit().
void OrmccSrcSendPkt (Agent * agent)
Definition at line 102 of file ormcc.c.
References _nodeTable, OrmccSrcInfoStruct::active_, NodeStruct::addr_, OrmccDataStruct::crAddr_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crGone_, OrmccDataStruct::crTracAvg_, OrmccSrcInfoStruct::crTracAvg_, OrmccDataStruct::crTracDev_, OrmccSrcInfoStruct::crTracDev_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, OrmccDataStruct::maxRtt_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, PacketStruct::od_, ORMCC_DATA, ORMCC_THROUGHPUT_SAMPLE_ITVL, p, OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktDstAgentId_, OrmccSrcInfoStruct::pktSize_, SendPacket(), PacketStruct::size_, OrmccDataStruct::sqn_, OrmccSrcInfoStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccSrcInfoStruct::thruSampleTime_, OrmccSrcInfoStruct::totalSentBytes_, OrmccSrcInfoStruct::trackStat_, OrmccDataStruct::ts_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccSrcStart(), and OrmccSrcTimer().
void OrmccSrcStart (Agent * agent)
Definition at line 44 of file ormcc.c.
References OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::ciRcvd_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, AgentStruct::info_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, ORMCC_SRC_DATA_PKT_SIZE, ORMCC_SRC_INIT_RATE, ORMCC_SRC_INIT_RTT, ORMCC_SRC_TIMER_RATE_INC, ORMCC_SRC_TIMER_SEND_PKT, OrmccSrcSendPkt(), OrmccSrcInfoStruct::pktSize_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), OrmccSrcInfoStruct::sendPktTimerEvnt_, OrmccSrcInfoStruct::sqn_, OrmccSrcInfoStruct::thruSampleTime_, OrmccSrcInfoStruct::totalSentBytes_, tw_getlp(), and tw_now().
Referenced by OrmccSrcInit().
void OrmccSrcStop (Agent * agent)
Definition at line 77 of file ormcc.c.
References OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crRespTimerEvnt_, AgentStruct::info_, AgentStruct::nodeId_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::sendPktTimerEvnt_, tw_getlp(), and tw_timer_cancel().
Referenced by OrmccSrcInit().
void OrmccSrcTimer (Agent * agent, int timerId, int serial)
Definition at line 307 of file ormcc.c.
References OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::nodeId_, ORMCC_SRC_TIMER_CONG_EPOCH, ORMCC_SRC_TIMER_CR_RESP, ORMCC_SRC_TIMER_RATE_INC, ORMCC_SRC_TIMER_SEND_PKT, OrmccSrcSendPkt(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktSize_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), OrmccSrcInfoStruct::sendPktTimerEvnt_, OrmccSrcInfoStruct::trackStat_, tw_exit(), tw_getlp(), and tw_now().
Referenced by OrmccSrcInit().
void OrmccSrcUpdateRtt (Agent * agent, double sample) inline
Definition at line 373 of file ormcc.c.
References AgentStruct::id_, AgentStruct::info_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, OrmccSrcInfoStruct::trackStat_, tw_getlp(), and tw_now().
Referenced by OrmccSrcPktHandler().
double RateSmoothAddSample (RateSmoothData * rsd, double rate, double time)
Definition at line 667 of file ormcc.c.
References RateSmoothDataStruct::head_, RateSampleStruct::rate_, RATE_SMOOTH_RING_SIZE, RateSmoothDataStruct::sample_, SMALL_FLOAT, RateSmoothDataStruct::span_, RateSmoothDataStruct::tail_, RateSampleStruct::time_, and RateSmoothDataStruct::totalData_.
Referenced by OrmccRcvPktHandler().
void RateSmoothInit (RateSmoothData * rsd, double span)
Definition at line 657 of file ormcc.c.
References RateSmoothDataStruct::head_, RATE_SMOOTH_RING_SIZE, RateSmoothDataStruct::sample_, RateSmoothDataStruct::span_, RateSmoothDataStruct::tail_, and RateSmoothDataStruct::totalData_.
Referenced by OrmccRcvStart().