ROSS: rnf/modules/network/multicast/ormcc.c File Reference
ormcc.c File Reference
#include "ormcc.h"
Functions
Agent * OrmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
void OrmccSrcStart (Agent *agent)
void OrmccSrcStop (Agent *agent)
void OrmccSrcSendPkt (Agent *agent)
void OrmccSrcPktHandler (Agent *agent, Packet *p)
void OrmccSrcTimer (Agent *agent, int timerId, int serial)
void OrmccSrcUpdateRtt (Agent *agent, double sample)
void OrmccSrcPrintStat (Agent *agent)
Agent * OrmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
void OrmccRcvStart (Agent *agent)
void OrmccRcvStop (Agent *agent)
void OrmccRcvPktHandler (Agent *agent, Packet *p)
void OrmccRcvSendPkt (Agent *agent)
void OrmccRcvTimer (Agent *agent, int timerId, int serial)
void OrmccRcvPrintStat (Agent *agent)
void RateSmoothInit (RateSmoothData *rsd, double span)
double RateSmoothAddSample (RateSmoothData *rsd, double rate, double time)
Variables
uint32 _totalOrmccCiSent = 0
uint32 _totalOrmccCiSupp = 0
Function Documentation
Agent* OrmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
Definition at line 408 of file ormcc.c.
References GetAgent(), AgentStruct::info_, IsMcastAddr, OrmccRcvPktHandler(), OrmccRcvPrintStat(), OrmccRcvStart(), OrmccRcvStop(), OrmccRcvTimer(), RegisterAgent(), and tw_exit().
Referenced by ReadAgentAct().
void OrmccRcvPktHandler (Agent * agent, Packet * p)
Definition at line 471 of file ormcc.c.
References _addrToIdx, _nodeTable, _totalOrmccCiSupp, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::ciBackoffTimerEvnt_, OrmccRcvInfoStruct::ciSchedTime_, OrmccRcvInfoStruct::ciSqn_, OrmccRcvInfoStruct::ciSupp_, OrmccRcvInfoStruct::ciTsEcho_, OrmccDataStruct::crAddr_, OrmccRcvInfoStruct::crAddr_, OrmccRcvInfoStruct::crBegTime_, OrmccDataStruct::crTracAvg_, OrmccRcvInfoStruct::crTracAvg_, OrmccDataStruct::crTracDev_, OrmccRcvInfoStruct::crTracDev_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, OrmccRcvInfoStruct::lastContSqn_, OrmccRcvInfoStruct::lastPktTime_, AgentStruct::listenAddr_, OrmccDataStruct::maxRtt_, AgentStruct::nodeId_, PacketStruct::od_, ORMCC_COMPARE_TRAC_FACTOR, ORMCC_DATA, ORMCC_RCV_CI_BACKOFF_TIMER, ORMCC_TRAC_EWMA_FACTOR, OrmccRcvSendPkt(), OrmccRcvInfoStruct::rate_, RateSmoothAddSample(), OrmccRcvInfoStruct::rsd_, ScheduleTimer(), OrmccRcvInfoStruct::senderAddr_, OrmccRcvInfoStruct::senderAgent_, PacketStruct::size_, SMALL_FLOAT, OrmccDataStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccRcvInfoStruct::tracAvg_, OrmccDataStruct::ts_, tw_exit(), tw_getlp(), tw_now(), tw_timer_cancel(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccRcvInit().
void OrmccRcvPrintStat (Agent * agent)
Definition at line 639 of file ormcc.c.
References _totalOrmccCiSent, _totalOrmccCiSupp, OrmccRcvInfoStruct::ciSent_, OrmccRcvInfoStruct::ciSupp_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, and AgentStruct::nodeId_.
Referenced by OrmccRcvInit().
void OrmccRcvSendPkt (Agent * agent)
Definition at line 597 of file ormcc.c.
References _nodeTable, _totalOrmccCiSent, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::ciSchedTime_, OrmccRcvInfoStruct::ciSent_, OrmccRcvInfoStruct::ciSqn_, OrmccRcvInfoStruct::ciTsEcho_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, IsMcastAddr, AgentStruct::listenAddr_, AgentStruct::nodeId_, PacketStruct::oc_, ORMCC_CI, ORMCC_RCV_CI_PKT_SIZE, p, OrmccRcvInfoStruct::rate_, OrmccRcvInfoStruct::senderAddr_, OrmccRcvInfoStruct::senderAgent_, SendPacket(), PacketStruct::size_, OrmccCiStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccCiStruct::trac_, OrmccCiStruct::tsEcho_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccRcvPktHandler(), and OrmccRcvTimer().
void OrmccRcvStart (Agent * agent)
Definition at line 444 of file ormcc.c.
References _nodeTable, OrmccRcvInfoStruct::active_, NodeStruct::addr_, OrmccRcvInfoStruct::crAddr_, OrmccRcvInfoStruct::crTracAvg_, OrmccRcvInfoStruct::crTracDev_, AgentStruct::info_, OrmccRcvInfoStruct::lastContSqn_, OrmccRcvInfoStruct::lastPktTime_, AgentStruct::nodeId_, OrmccRcvInfoStruct::rate_, RATE_SMOOTH_TIME, RateSmoothInit(), OrmccRcvInfoStruct::rsd_, and OrmccRcvInfoStruct::tracAvg_.
Referenced by OrmccRcvInit().
void OrmccRcvStop (Agent * agent)
Definition at line 458 of file ormcc.c.
References OrmccRcvInfoStruct::active_, CancelTimer(), OrmccRcvInfoStruct::ciBackoffTimerEvnt_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, and IsMcastAddr.
Referenced by OrmccRcvInit().
void OrmccRcvTimer (Agent * agent, int timerId, int serial)
Definition at line 623 of file ormcc.c.
References OrmccRcvInfoStruct::ciBackoffTimerEvnt_, AgentStruct::info_, ORMCC_RCV_CI_BACKOFF_TIMER, OrmccRcvSendPkt(), and tw_exit().
Referenced by OrmccRcvInit().
Agent* OrmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
Definition at line 12 of file ormcc.c.
References _nodeTable, GetAgent(), AgentStruct::info_, OrmccSrcPktHandler(), OrmccSrcPrintStat(), OrmccSrcStart(), OrmccSrcStop(), OrmccSrcTimer(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktDstAgentId_, RegisterAgent(), OrmccSrcInfoStruct::trackStat_, and tw_exit().
Referenced by ReadAgentAct().
void OrmccSrcPktHandler (Agent * agent, Packet * p)
Definition at line 147 of file ormcc.c.
References _addrToIdx, OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::ciFromCr_, OrmccSrcInfoStruct::ciRcvd_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::nodeId_, OrmccSrcInfoStruct::notCut_, PacketStruct::oc_, ORMCC_CI, ORMCC_COMPARE_TRAC_FACTOR, ORMCC_SRC_MIN_RATE, ORMCC_SRC_TIMER_CONG_EPOCH, ORMCC_TRAC_EWMA_FACTOR, OrmccSrcUpdateRtt(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), SMALL_FLOAT, OrmccCiStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccCiStruct::trac_, OrmccSrcInfoStruct::trackStat_, OrmccCiStruct::tsEcho_, tw_exit(), tw_getlp(), tw_now(), tw_timer_cancel(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccSrcInit().
void OrmccSrcPrintStat (Agent * agent)
Definition at line 393 of file ormcc.c.
References OrmccSrcInfoStruct::ciFromCr_, OrmccSrcInfoStruct::ciRcvd_, AgentStruct::info_, and OrmccSrcInfoStruct::notCut_.
Referenced by OrmccSrcInit().
void OrmccSrcSendPkt (Agent * agent)
Definition at line 102 of file ormcc.c.
References _nodeTable, OrmccSrcInfoStruct::active_, NodeStruct::addr_, OrmccDataStruct::crAddr_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crGone_, OrmccDataStruct::crTracAvg_, OrmccSrcInfoStruct::crTracAvg_, OrmccDataStruct::crTracDev_, OrmccSrcInfoStruct::crTracDev_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, OrmccDataStruct::maxRtt_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, PacketStruct::od_, ORMCC_DATA, ORMCC_THROUGHPUT_SAMPLE_ITVL, p, OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktDstAgentId_, OrmccSrcInfoStruct::pktSize_, SendPacket(), PacketStruct::size_, OrmccDataStruct::sqn_, OrmccSrcInfoStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, OrmccSrcInfoStruct::thruSampleTime_, OrmccSrcInfoStruct::totalSentBytes_, OrmccSrcInfoStruct::trackStat_, OrmccDataStruct::ts_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by OrmccSrcStart(), and OrmccSrcTimer().
void OrmccSrcStart (Agent * agent)
Definition at line 44 of file ormcc.c.
References OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::ciRcvd_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crAddr_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, AgentStruct::info_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, ORMCC_SRC_DATA_PKT_SIZE, ORMCC_SRC_INIT_RATE, ORMCC_SRC_INIT_RTT, ORMCC_SRC_TIMER_RATE_INC, ORMCC_SRC_TIMER_SEND_PKT, OrmccSrcSendPkt(), OrmccSrcInfoStruct::pktSize_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), OrmccSrcInfoStruct::sendPktTimerEvnt_, OrmccSrcInfoStruct::sqn_, OrmccSrcInfoStruct::thruSampleTime_, OrmccSrcInfoStruct::totalSentBytes_, tw_getlp(), and tw_now().
Referenced by OrmccSrcInit().
void OrmccSrcStop (Agent * agent)
Definition at line 77 of file ormcc.c.
References OrmccSrcInfoStruct::active_, OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crRespTimerEvnt_, AgentStruct::info_, AgentStruct::nodeId_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::sendPktTimerEvnt_, tw_getlp(), and tw_timer_cancel().
Referenced by OrmccSrcInit().
void OrmccSrcTimer (Agent * agent, int timerId, int serial)
Definition at line 307 of file ormcc.c.
References OrmccSrcInfoStruct::congEpochTimerEvnt_, OrmccSrcInfoStruct::crChkBegTime_, OrmccSrcInfoStruct::crGone_, OrmccSrcInfoStruct::crRespTimeAvg_, OrmccSrcInfoStruct::crRespTimeDev_, OrmccSrcInfoStruct::crRespTimerEvnt_, OrmccSrcInfoStruct::crTracAvg_, OrmccSrcInfoStruct::crTracDev_, AgentStruct::id_, AgentStruct::info_, IsMcastAddr, AgentStruct::nodeId_, ORMCC_SRC_TIMER_CONG_EPOCH, ORMCC_SRC_TIMER_CR_RESP, ORMCC_SRC_TIMER_RATE_INC, ORMCC_SRC_TIMER_SEND_PKT, OrmccSrcSendPkt(), OrmccSrcInfoStruct::pktDstAddr_, OrmccSrcInfoStruct::pktSize_, OrmccSrcInfoStruct::rate_, OrmccSrcInfoStruct::rateIncrTimerEvnt_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, ScheduleTimer(), OrmccSrcInfoStruct::sendPktTimerEvnt_, OrmccSrcInfoStruct::trackStat_, tw_exit(), tw_getlp(), and tw_now().
Referenced by OrmccSrcInit().
void OrmccSrcUpdateRtt (Agent * agent, double sample) inline
Definition at line 373 of file ormcc.c.
References AgentStruct::id_, AgentStruct::info_, OrmccSrcInfoStruct::maxRtt_, AgentStruct::nodeId_, OrmccSrcInfoStruct::rttAvg_, OrmccSrcInfoStruct::rttDev_, OrmccSrcInfoStruct::trackStat_, tw_getlp(), and tw_now().
Referenced by OrmccSrcPktHandler().
double RateSmoothAddSample (RateSmoothData * rsd, double rate, double time)
Definition at line 667 of file ormcc.c.
References RateSmoothDataStruct::head_, RateSampleStruct::rate_, RATE_SMOOTH_RING_SIZE, RateSmoothDataStruct::sample_, SMALL_FLOAT, RateSmoothDataStruct::span_, RateSmoothDataStruct::tail_, RateSampleStruct::time_, and RateSmoothDataStruct::totalData_.
Referenced by OrmccRcvPktHandler().
void RateSmoothInit (RateSmoothData * rsd, double span)
Definition at line 657 of file ormcc.c.
References RateSmoothDataStruct::head_, RATE_SMOOTH_RING_SIZE, RateSmoothDataStruct::sample_, RateSmoothDataStruct::span_, RateSmoothDataStruct::tail_, and RateSmoothDataStruct::totalData_.
Referenced by OrmccRcvStart().
Variable Documentation
uint32 _totalOrmccCiSent = 0
Definition at line 4 of file ormcc.c.
Referenced by OrmccRcvPrintStat(), and OrmccRcvSendPkt().
uint32 _totalOrmccCiSupp = 0
Definition at line 4 of file ormcc.c.
Referenced by OrmccRcvPktHandler(), and OrmccRcvPrintStat().