ROSS: rnf/modules/network/ospfv2/ospf-timer-aging.c File Reference
ospf-timer-aging.c File Reference
#include <ospf.h>
Functions
void ospf_aging_timer_set (ospf_state *state, ospf_db_entry *dbe, int age, tw_lp *lp)
int can_be_removed (ospf_state *state, ospf_db_entry *dbe, tw_lp *lp)
void ospf_aging_timer (ospf_state *state, tw_bf *bf, tw_lp *lp)
Function Documentation
int can_be_removed (ospf_state * state, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 115 of file ospf-timer-aging.c.
References ospf_db_entry::age, ospf_db_entry::b, ospf_state::n_interfaces, ospf_state::nbr, OSPF_LSA_MAX_AGE, ospf_nbr_exchange_st, ospf_nbr_loading_st, ospf_nbr::state, TW_FALSE, and TW_TRUE.
Referenced by ospf_aging_timer().
void ospf_aging_timer (ospf_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 147 of file ospf-timer-aging.c.
References ospf_lsa::adv_r, ospf_db_entry::age, ospf_state::aging_timer, ospf_state::ar, ospf_db_entry::b, can_be_removed(), ospf_state::db, ospf_state::db_last_ts, ospf_db_entry::entry, ospf_db_entry::free, rn_area::g_ospf_nlsa, getlsa(), tw_lp::gid, ospf_lsa::id, ospf_db_entry::lsa, ospf_state::lsa_seqnum, ospf_state::lsa_wrapping, ospf_state::m, min, OSPF_AGING_INTERVAL, OSPF_AGING_TIMER, ospf_lsa_flood(), OSPF_LSA_MAX_AGE, ospf_lsa_refresh(), OSPF_LSA_REFRESH_AGE, OSPF_MIN_LSA_SEQNUM, ospf_rt_build(), ospf_timer_start(), tw_event::recv_ts, tw_now(), and TW_TRUE.
Referenced by ospf_event_handler().
void ospf_aging_timer_set (ospf_state * state, ospf_db_entry * dbe, int age, tw_lp * lp)
Definition at line 24 of file ospf-timer-aging.c.
References ospf_db_entry::age, ospf_state::aging_timer, ospf_state::ar, ospf_db_entry::b, ospf_state::db, ospf_state::db_last_ts, ospf_db_entry::entry, ospf_db_entry::free, rn_area::g_ospf_nlsa, tw_lp::gid, OSPF_AGING_INTERVAL, OSPF_AGING_TIMER, ospf_lsa_age(), OSPF_LSA_MAX_AGE, OSPF_LSA_REFRESH_AGE, ospf_timer_start(), tw_event::recv_ts, and tw_now().
Referenced by ospf_db_update(), ospf_lsa_create(), ospf_lsa_refresh(), and ospf_lsa_start_flood().