ROSS: rnf/modules/network/ospfv2/ospf-timer-retransmit.c File Reference
ospf-timer-retransmit.c File Reference
#include <ospf.h>
Functions
void ospf_retrans_timed_out (ospf_state *state, tw_bf *bf, ospf_message *msg, tw_lp *lp)
Function Documentation
void ospf_retrans_timed_out (ospf_state * state, tw_bf * bf, ospf_message * msg, tw_lp * lp)
Definition at line 9 of file ospf-timer-retransmit.c.
References ospf_message::area, tw_lp::gid, ospf_nbr::id, OSPF_DD_MSG, OSPF_LS_REQUEST, OSPF_RETRANS_INTERVAL, OSPF_RETRANS_TIMEOUT, ospf_timer_start(), ospf_nbr::retrans_dd, ospf_nbr::retrans_timer, tw_lp::rng, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), and ospf_message::type.