ROSS: rnf/modules/network/ospfv2/ospf-flood.c File Reference
ospf-flood.c File Reference
#include <ospf.h>
Functions
void ospf_flood_recv (ospf_state *state, ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
Function Documentation
void ospf_flood_recv (ospf_state * state, ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 8 of file ospf-flood.c.
References ospf_db_entry::age, ospf_message::area, ospf_state::db, ospf_nbr::flood, tw_lp::gid, ospf_nbr::id, ospf_db_entry::lsa, ospf_nbr::m, OSPF_FLOOD_TIMEOUT, OSPF_LS_UPDATE, ospf_nbr_exstart_st, ospf_timer_cancel(), ospf_timer_start(), tw_lp::rng, ospf_statistics::s_sent_ls_updates, ospf_nbr::state, ospf_state::stats, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), and ospf_message::type.