ROSS: rnf/modules/network/ospfv2/ospf-lsa.c File Reference
ospf-lsa.c File Reference
#include <ospf.h>
Functions
void ospf_lsa_print (FILE *log, ospf_lsa *lsa)
int ospf_lsa_equals (ospf_lsa *old, ospf_lsa *lsa)
int ospf_lsa_find (ospf_state *state, ospf_nbr *n, int id, tw_lp *lp)
unsigned int ospf_lsa_age (ospf_state *state, ospf_db_entry *dbe, tw_lp *lp)
ospf_lsa * getlsa (rn_machine *m, int index, int id)
char lsa_create (ospf_state *state, int entry, tw_lp *lp)
tw_memory * ospf_lsa_allocate (tw_lp *lp)
void ospf_lsa_link_allocate (ospf_state *state, ospf_lsa *lsa, tw_lp *lp)
void ospf_lsa_refresh (ospf_state *state, ospf_db_entry *dbe, tw_lp *lp)
void ospf_lsa_create (ospf_state *state, ospf_nbr *nbr, int entry, tw_lp *lp)
void ospf_lsa_start_flood (ospf_nbr *nbr, ospf_db_entry *dbe, tw_lp *lp)
void ospf_lsa_flood (ospf_state *state, ospf_db_entry *dbe, int from, tw_lp *lp)
int ospf_lsa_isnewer (ospf_state *state, ospf_db_entry *old, ospf_db_entry *new, tw_lp *lp)
void ospf_lsa_flush (ospf_state *state, ospf_nbr *nbr, ospf_db_entry *r_dbe, tw_lp *lp)
Function Documentation
ospf_lsa* getlsa (rn_machine * m, int index, int id)
Definition at line 247 of file ospf-lsa.c.
References g_ospf_lsa, ospf_lsa::next, rn_getarea(), tw_error(), and TW_LOC.
Referenced by bgp_ospf_update(), dd_process(), flood_summary(), ls_update_process(), ospf_aging_timer(), ospf_db_init(), ospf_db_print(), ospf_db_route(), ospf_db_update(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_create(), ospf_lsa_flood(), ospf_lsa_flush(), ospf_lsa_refresh(), ospf_lsa_start_flood(), ospf_nbr_reset(), ospf_rt_print(), ospf_rt_timer(), and process_lsa_recv().
char lsa_create (ospf_state * state, int entry, tw_lp * lp)
Definition at line 278 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_state::ar, ospf_nbr::ar, rn_area::as, ospf_lsa_link::dst, rn_area::g_ospf_lsa, tw_lp::gid, ospf_lsa::id, rn_area::id, rn_as::id, ospf_nbr::istate, ospf_lsa::links, rn_as::low, ospf_state::m, ospf_state::n_interfaces, rn_as::nareas, ospf_state::nbr, ospf_lsa::next, rn_area::nmachines, ospf_getnbr(), ospf_int_point_to_point_st, ospf_lsa_allocate(), ospf_lsa_as_ext, ospf_lsa_link_allocate(), ospf_lsa_router, ospf_lsa_summary3, ospf_nbr_full_st, rn_getarea(), ospf_nbr::state, and ospf_lsa::type.
unsigned int ospf_lsa_age (ospf_state * state, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 231 of file ospf-lsa.c.
References ospf_db_entry::age, ospf_db_entry::b, ospf_state::db_last_ts, ospf_db_entry::free, OSPF_LSA_MAX_AGE, tw_now(), and x.
Referenced by dd_exchange(), ospf_aging_timer_set(), ospf_db_update(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_isnewer(), ospf_lsa_start_flood(), and process_lsa_recv().
tw_memory* ospf_lsa_allocate (tw_lp * lp)
Definition at line 387 of file ospf-lsa.c.
References g_ospf_lsa_fd, tw_error(), TW_LOC, and tw_memory_alloc().
Referenced by bgp_lsa_find(), lsa_create(), and ospf_lsa_find().
void ospf_lsa_create (ospf_state * state, ospf_nbr * nbr, int entry, tw_lp * lp)
Definition at line 527 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_state::ar, ospf_db_entry::b, ospf_db_entry::cause_bgp, ospf_state::db, ospf_db_entry::entry, ospf_db_entry::free, getlsa(), tw_lp::gid, ospf_lsa::id, ospf_nbr::id, rn_machine::id, ospf_lsa::links, ospf_db_entry::lsa, ospf_state::lsa_seqnum, ospf_state::lsa_wrapping, ospf_state::m, ospf_state::nbr, rn_area::nmachines, ospf_aging_timer_set(), ospf_db_insert(), ospf_db_remove(), ospf_lsa_equals(), ospf_lsa_find(), ospf_lsa_flood(), OSPF_LSA_MAX_AGE, OSPF_MAX_LSA_SEQNUM, rn_getarea(), rn_getlink(), rn_getmachine(), rn_route(), ospf_db_entry::seqnum, tw_error(), TW_FALSE, TW_LOC, TW_TRUE, and rn_link::wire.
Referenced by bgp_ospf_update(), ospf_lsa_flush(), ospf_nbr_exchange_done(), ospf_nbr_inactivity_timer(), and process_lsa_recv().
int ospf_lsa_equals (ospf_lsa * old, ospf_lsa * lsa)
Definition at line 30 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_lsa_link::dst, ospf_lsa::length, ospf_lsa::links, ospf_lsa_link::metric, TW_FALSE, and TW_TRUE.
Referenced by ospf_lsa_create().
int ospf_lsa_find (ospf_state * state, ospf_nbr * n, int id, tw_lp * lp)
Definition at line 76 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_state::ar, ospf_nbr::ar, rn_area::as, rn_link::cost, ospf_lsa_link::dst, g_ospf_ll_fd, rn_area::g_ospf_lsa, tw_lp::gid, ospf_lsa::id, ospf_nbr::id, rn_area::id, rn_as::id, ospf_nbr::istate, ospf_lsa::links, rn_as::low, ospf_state::m, ospf_lsa_link::metric, ospf_state::n_interfaces, rn_as::nareas, ospf_state::nbr, ospf_lsa::next, rn_area::nmachines, ospf_getnbr(), ospf_int_point_to_point_st, ospf_lsa_allocate(), ospf_lsa_as_ext, ospf_lsa_link_allocate(), ospf_lsa_router, ospf_lsa_summary3, ospf_nbr_full_st, rn_getlink(), ospf_nbr::state, tw_error(), TW_LOC, tw_memory_alloc(), tw_memoryq_push(), and ospf_lsa::type.
Referenced by ospf_db_init(), ospf_experiment_weights(), ospf_ls_update_recv(), and ospf_lsa_create().
void ospf_lsa_flood (ospf_state * state, ospf_db_entry * dbe, int from, tw_lp * lp)
Definition at line 731 of file ospf-lsa.c.
References ospf_state::ar, ospf_nbr::ar, rn_area::as, ospf_db_entry::b, ospf_db_entry::entry, getlsa(), tw_lp::gid, ospf_nbr::id, rn_area::id, ospf_db_entry::lsa, ospf_state::m, ospf_state::n_interfaces, ospf_state::nbr, rn_area::nmachines, ospf_lsa_print(), ospf_lsa_start_flood(), ospf_nbr_exchange_st, ospf_nbr_loading_st, ospf_db_entry::seqnum, ospf_nbr::state, tw_error(), and TW_LOC.
Referenced by ospf_aging_timer(), ospf_lsa_create(), ospf_lsa_flush(), ospf_lsa_refresh(), and process_lsa_recv().
void ospf_lsa_flush (ospf_state * state, ospf_nbr * nbr, ospf_db_entry * r_dbe, tw_lp * lp)
Definition at line 850 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_db_entry::age, ospf_state::ar, ospf_nbr::ar, ospf_db_entry::b, ospf_state::db, ospf_db_entry::entry, ospf_db_entry::free, g_ospf_fd, getlsa(), tw_lp::gid, ospf_nbr::id, rn_area::id, ospf_lsa::length, ospf_db_entry::lsa, ospf_state::m, ospf_state::n_interfaces, ospf_state::nbr, rn_area::nmachines, ospf_ack_direct(), ospf_db_remove(), ospf_lsa_create(), ospf_lsa_flood(), OSPF_LSA_MAX_AGE, ospf_lsa_router, ospf_lsa_summary3, ospf_nbr_full_st, ospf_nbr::state, tw_memory_alloc(), and ospf_lsa::type.
Referenced by ospf_nbr_reset(), and process_lsa_recv().
int ospf_lsa_isnewer (ospf_state * state, ospf_db_entry * old, ospf_db_entry * new, tw_lp * lp)
Definition at line 793 of file ospf-lsa.c.
References ospf_db_entry::b, ospf_db_entry::free, ospf_lsa_age(), OSPF_LSA_MAX_AGE, OSPF_LSA_MAX_AGE_DIFF, and ospf_db_entry::seqnum.
Referenced by dd_process(), and process_lsa_recv().
void ospf_lsa_link_allocate (ospf_state * state, ospf_lsa * lsa, tw_lp * lp)
Definition at line 406 of file ospf-lsa.c.
References ospf_state::ar, ospf_nbr::ar, rn_area::as, rn_link::cost, ospf_lsa_link::dst, g_ospf_ll_fd, ospf_lsa::id, ospf_nbr::id, rn_area::id, ospf_nbr::istate, ospf_lsa::length, rn_machine::link, ospf_lsa::links, rn_as::low, ospf_state::m, ospf_lsa_link::metric, ospf_state::n_interfaces, rn_as::nareas, ospf_state::nbr, rn_area::nmachines, ospf_int_point_to_point_st, OSPF_LSA_LINK_LENGTH, OSPF_LSA_UPDATE_HEADER, ospf_nbr_full_st, ospf_nbr::state, tw_memory_alloc(), and tw_memoryq_push().
Referenced by lsa_create(), and ospf_lsa_find().
void ospf_lsa_print (FILE * log, ospf_lsa * lsa)
Definition at line 4 of file ospf-lsa.c.
References ospf_lsa::adv_r, ospf_lsa_link::dst, ospf_lsa::id, ospf_lsa::links, and ospf_lsa_link::metric.
Referenced by flood_summary(), main_setup_areas(), ospf_db_print(), ospf_db_read(), ospf_lsa_flood(), and ospf_statistics_collection().
void ospf_lsa_refresh (ospf_state * state, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 481 of file ospf-lsa.c.
References ospf_db_entry::b, ospf_state::db, ospf_db_entry::entry, ospf_db_entry::free, getlsa(), tw_lp::gid, ospf_lsa::id, ospf_db_entry::lsa, ospf_state::lsa_seqnum, ospf_state::lsa_wrapping, ospf_state::m, ospf_aging_timer_set(), ospf_lsa_flood(), OSPF_LSA_MAX_AGE, OSPF_MAX_LSA_SEQNUM, and ospf_db_entry::seqnum.
Referenced by ospf_aging_timer(), and ospf_experiment_weights().
void ospf_lsa_start_flood (ospf_nbr * nbr, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 646 of file ospf-lsa.c.
References ospf_db_entry::age, ospf_state::ar, ospf_db_entry::b, ospf_db_entry::cause_bgp, ospf_db_entry::cause_ospf, ospf_db_entry::entry, ospf_nbr::flood, ospf_global_state::flood_timer, ospf_db_entry::free, g_ospf_fd, getlsa(), tw_lp::gid, ospf_state::gstate, ospf_nbr::id, rn_area::id, ospf_lsa::length, ospf_db_entry::lsa, ospf_state::m, ospf_nbr::next_flood, ospf_aging_timer_set(), ospf_event_new(), ospf_event_send(), OSPF_LS_UPDATE, ospf_lsa_age(), OSPF_LSA_MAX_AGE, tw_event::recv_ts, ospf_nbr::router, ospf_db_entry::seqnum, tw_memory_alloc(), and tw_now().
Referenced by flood_summary(), and ospf_lsa_flood().