ROSS: rnf/modules/network/ospfv2/ospf-util.c File Reference
ospf-util.c File Reference
#include <ospf.h>
Functions
tw_event * ospf_event_new (ospf_state *state, tw_lpid dest, tw_stime ts, tw_lp *srclp)
tw_event * ospf_event_send (ospf_state *state, tw_event *event, int type, tw_lp *src, int size, tw_memory *mem, int area)
Function Documentation
tw_event* ospf_event_new (ospf_state * state, tw_lpid dest, tw_stime ts, tw_lp * srclp)
Definition at line 4 of file ospf-util.c.
References tw_pe::abort_event, DOWNSTREAM, tw_lp::gid, tw_lp::pe, rn_event_new(), ospf_statistics::s_sent_lost, and ospf_state::stats.
Referenced by dd_exchange(), ospf_ack_direct(), ospf_ack_timed_out(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_h_send(), ospf_ip_route(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_start_flood(), ospf_nbr_neg_done(), ospf_nbr_two_way_recv(), and process_lsa_recv().
tw_event* ospf_event_send (ospf_state * state, tw_event * event, int type, tw_lp * src, int size, tw_memory * mem, int area)
Definition at line 23 of file ospf-util.c.
References ospf_message::area, tw_event::dest_lp, g_ospf_fd, tw_lp::id, OSPF_DD_MSG, OSPF_HEADER, OSPF_HELLO_MSG, OSPF_LS_ACK, OSPF_LS_REQUEST, OSPF_LS_UPDATE, tw_event::recv_ts, rn_event_send(), rn_message_setsize(), ospf_statistics::s_sent_dds, ospf_statistics::s_sent_hellos, ospf_statistics::s_sent_ls_acks, ospf_statistics::s_sent_ls_requests, ospf_statistics::s_sent_ls_updates, ospf_statistics::s_sent_unknown, ospf_state::stats, tw_event_data(), tw_memory_alloc(), and ospf_message::type.
Referenced by dd_exchange(), ospf_ack_direct(), ospf_ack_timed_out(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_h_send(), ospf_ip_route(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_start_flood(), ospf_nbr_neg_done(), ospf_nbr_two_way_recv(), and process_lsa_recv().