ROSS: rnf/modules/network/ospfv2/ospf-hello.c File Reference
ospf-hello.c File Reference
#include <ospf.h>
Functions
void ospf_h_send (ospf_state *state, ospf_nbr *nbr, tw_lp *src, tw_lpid dst)
void ospf_hello_send (ospf_state *state, ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_hello_packet (ospf_state *state, ospf_nbr *nbr, ospf_hello *r, tw_bf *bf, tw_lp *lp)
Function Documentation
void ospf_h_send (ospf_state * state, ospf_nbr * nbr, tw_lp * src, tw_lpid dst)
Definition at line 10 of file ospf-hello.c.
References ospf_state::ar, ospf_hello::b_designated_r, ospf_state::b_designated_r, ospf_message::data, ospf_hello::designated_r, ospf_state::designated_r, ospf_hello::end, g_ospf_fd, g_tw_ts_end, ospf_state::gstate, ospf_nbr::hello, ospf_hello::hello_interval, ospf_global_state::hello_sendnext, ospf_nbr::id, rn_area::id, tw_lp::id, ospf_nbr::m, ospf_global_state::mtu, ospf_state::n_interfaces, ospf_state::nbr, ospf_hello::neighbors, ospf_hello::offset, ospf_event_new(), ospf_event_send(), OSPF_HEADER, OSPF_HELLO_HEADER, OSPF_HELLO_MSG, ospf_nbr_init_st, ospf_hello::poll_interval, ospf_global_state::poll_interval, ospf_hello::priority, ospf_state::priority, tw_event::recv_ts, ospf_statistics::s_e_hello_out, ospf_nbr::state, ospf_state::stats, tw_memory_alloc(), and tw_now().
Referenced by ospf_hello_send().
void ospf_hello_packet (ospf_state * state, ospf_nbr * nbr, ospf_hello * r, tw_bf * bf, tw_lp * lp)
Definition at line 115 of file ospf-hello.c.
References ospf_hello::b_designated_r, ospf_state::b_designated_r, ospf_nbr::b_designated_r, tw_bf::c1, tw_bf::c2, ospf_message::data, ospf_hello::designated_r, ospf_state::designated_r, ospf_nbr::designated_r, g_ospf_fd, tw_lp::gid, ospf_state::gstate, ospf_hello::hello_interval, ospf_global_state::hello_sendnext, ospf_nbr::id, ospf_nbr::istate, ospf_nbr::m, ospf_hello::neighbors, ospf_hello::offset, ospf_int_backupseen_ev, ospf_int_nbrchange_ev, ospf_int_waiting_st, ospf_interface_event_handler(), ospf_nbr_event_handler(), ospf_nbr_hello_recv_ev, ospf_nbr_one_way_ev, ospf_nbr_two_way_recv_ev, ospf_hello::poll_interval, ospf_global_state::poll_interval, ospf_hello::priority, ospf_nbr::priority, ospf_statistics::s_drop_hello_int, ospf_statistics::s_drop_poll_int, ospf_state::stats, tw_error(), TW_LOC, tw_memory_free(), and tw_now().
Referenced by ospf_event_handler().
void ospf_hello_send (ospf_state * state, ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 101 of file ospf-hello.c.
References ospf_nbr::hello_interval, ospf_nbr::hello_timer, ospf_nbr::id, ospf_nbr::istate, ospf_h_send(), OSPF_HELLO_SEND, ospf_int_loopback_st, and ospf_timer_start().
Referenced by ospf_event_handler().