ROSS: rnf/modules/network/ospfv2/ospf-timer.c File Reference
ospf-timer.c File Reference
#include <ospf.h>
Functions
tw_event * ospf_timer_cancel (tw_event *tmr, tw_lp *lp)
tw_event * ospf_timer_start (ospf_nbr *nbr, tw_event *tmr, tw_stime ts, int type, tw_lp *lp)
Function Documentation
tw_event* ospf_timer_cancel (tw_event * tmr, tw_lp * lp)
Definition at line 4 of file ospf-timer.c.
References g_ospf_fd, tw_event::recv_ts, rn_timer_cancel(), tw_memory_free(), and tw_now().
Referenced by ospf_ack_timed_out(), ospf_flood_recv(), ospf_interface_reset(), ospf_nbr_exchange_done(), and ospf_nbr_reset().
tw_event* ospf_timer_start (ospf_nbr * nbr, tw_event * tmr, tw_stime ts, int type, tw_lp * lp)
Definition at line 29 of file ospf-timer.c.
References ospf_message::data, g_ospf_fd, tw_event::recv_ts, rn_timer_init(), rn_timer_reset(), tw_memory_alloc(), tw_now(), and ospf_message::type.
Referenced by dd_exchange(), neighbor_init(), ospf_ack_delayed(), ospf_aging_timer(), ospf_aging_timer_set(), ospf_dd_retransmit(), ospf_flood_recv(), ospf_hello_send(), ospf_interface_up(), ospf_ls_request(), ospf_nbr_hello_recv(), ospf_nbr_neg_done(), ospf_nbr_start(), ospf_nbr_two_way_recv(), ospf_rc_event_handler(), ospf_retrans_timed_out(), ospf_rt_build(), and ospf_startup().