ROSS: rnf/modules/network/multicast/Packet.h File Reference
Packet.h File Reference
#include "Routing.h"
Data Structures
struct OrmccDataStruct
struct OrmccCiStruct
struct GmccDataStruct
struct GmccCtrlStruct
struct GmccCtrlExtStruct
struct GmccCiStruct
struct PgmccDataStruct
struct PgmccAckStruct
struct PgmccNakStruct
struct TfmccDataStruct
struct TfmccNakStruct
struct PacketStruct
struct ExtPacketStruct
struct ExtPacketHashStruct
Macros
#define EXT_PACKET_TABLE_SIZE 10111
#define GMCC_MAX_LAYER_NUM 16
Typedefs
typedef struct OrmccDataStruct OrmccData
typedef struct OrmccCiStruct OrmccCi
typedef struct GmccDataStruct GmccData
typedef struct GmccCtrlStruct GmccCtrl
typedef struct GmccCtrlExtStruct GmccCtrlExt
typedef struct GmccCiStruct GmccCi
typedef struct PgmccDataStruct PgmccData
typedef struct PgmccAckStruct PgmccAck
typedef struct PgmccNakStruct PgmccNak
typedef struct TfmccDataStruct TfmccData
typedef struct TfmccNakStruct TfmccNak
typedef struct PacketStruct Packet
typedef struct ExtPacketStruct ExtPacket
typedef struct ExtPacketHashStruct ExtPacketHash
Enumerations
enum {
ORMCC_DATA, ORMCC_CI, GMCC_DATA, GMCC_CTRL,
GMCC_CI, PGMCC_DATA, PGMCC_ACK, PGMCC_NAK,
TFMCC_DATA, TFMCC_NAK
}
Functions
void InitExtPktTable ()
void AddExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId, void *data, int dataSize, uint32 ref)
void SetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId, uint32 ref)
uint32 GetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
void DelExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
void * GetExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
Variables
ExtPacketHash _extPktTable []
Macro Definition Documentation
#define EXT_PACKET_TABLE_SIZE 10111
Definition at line 6 of file Packet.h.
Referenced by AddExtPkt(), DelExtPkt(), GetExtPkt(), GetExtPktRef(), InitExtPktTable(), and SetExtPktRef().
#define GMCC_MAX_LAYER_NUM 16
Definition at line 49 of file Packet.h.
Referenced by GmccRcvStart(), and GmccSrcStart().
Typedef Documentation
typedef struct ExtPacketStruct ExtPacket
typedef struct ExtPacketHashStruct ExtPacketHash
typedef struct GmccCiStruct GmccCi
typedef struct GmccCtrlStruct GmccCtrl
typedef struct GmccCtrlExtStruct GmccCtrlExt
typedef struct GmccDataStruct GmccData
typedef struct OrmccCiStruct OrmccCi
typedef struct OrmccDataStruct OrmccData
typedef struct PacketStruct Packet
typedef struct PgmccAckStruct PgmccAck
typedef struct PgmccDataStruct PgmccData
typedef struct PgmccNakStruct PgmccNak
typedef struct TfmccDataStruct TfmccData
typedef struct TfmccNakStruct TfmccNak
Enumeration Type Documentation
anonymous enum
Enumerator
ORMCC_DATA
ORMCC_CI
GMCC_DATA
GMCC_CTRL
GMCC_CI
PGMCC_DATA
PGMCC_ACK
PGMCC_NAK
TFMCC_DATA
TFMCC_NAK
Definition at line 9 of file Packet.h.
Function Documentation
void AddExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId, void * data, int dataSize, uint32 ref)
Definition at line 15 of file Packet.c.
References ExtPacketStruct::data_, ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by SendExtPkt().
void DelExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 114 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, and ExtPacketStruct::used_.
Referenced by McastEventHandler().
void* GetExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 138 of file Packet.c.
References ExtPacketStruct::data_, ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, and ExtPacketStruct::used_.
Referenced by GmccRcvProcCtrlPkt().
uint32 GetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 69 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by McastEventHandler().
void InitExtPktTable ()
Definition at line 8 of file Packet.c.
References EXT_PACKET_TABLE_SIZE.
void SetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId, uint32 ref) inline
Definition at line 92 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by McastEventHandler().
Variable Documentation
ExtPacketHash _extPktTable[]
Definition at line 5 of file Packet.c.