ROSS: rnf/modules/network/multicast/Packet.c File Reference
Packet.c File Reference
#include "Packet.h"
#include "ross.h"
Functions
void InitExtPktTable ()
void AddExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId, void *data, int dataSize, uint32 ref)
uint32 GetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
void SetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId, uint32 ref)
void DelExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
void * GetExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId)
Variables
ExtPacketHash _extPktTable [10111]
Function Documentation
void AddExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId, void * data, int dataSize, uint32 ref)
Definition at line 15 of file Packet.c.
References ExtPacketStruct::data_, ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by SendExtPkt().
void DelExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 114 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, and ExtPacketStruct::used_.
Referenced by McastEventHandler().
void* GetExtPkt (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 138 of file Packet.c.
References ExtPacketStruct::data_, ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, and ExtPacketStruct::used_.
Referenced by GmccRcvProcCtrlPkt().
uint32 GetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId) inline
Definition at line 69 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by McastEventHandler().
void InitExtPktTable ()
Definition at line 8 of file Packet.c.
References EXT_PACKET_TABLE_SIZE.
void SetExtPktRef (uint32 srcAddr, uint32 srcAgent, uint32 pktId, uint32 ref) inline
Definition at line 92 of file Packet.c.
References ExtPacketHashStruct::ep_, EXT_PACKET_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, ExtPacketHashStruct::head_, ExtPacketStruct::id_, ExtPacketStruct::srcAddr_, ExtPacketStruct::srcAgent_, ExtPacketHashStruct::tail_, tw_exit(), and ExtPacketStruct::used_.
Referenced by McastEventHandler().
Variable Documentation
ExtPacketHash _extPktTable[10111]
Definition at line 5 of file Packet.c.