ROSS: ross/models/pcs/pcs.h File Reference
pcs.h File Reference
#include "ross.h"
Data Structures
struct State
struct RC
struct Msg_Data
struct CellStatistics
Macros
#define TW_MAX_NAME_LEN 31
#define NUM_CELLS_X 1024
#define NUM_CELLS_Y 1024
#define NUM_VP_X 512
#define NUM_VP_Y 512
#define MAX_NORMAL_CHANNELS 10
#define MAX_RESERVE_CHANNELS 0
#define MOVE_CALL_MEAN 4500.0
#define NEXT_CALL_MEAN 360.0
#define CALL_TIME_MEAN 180.0
#define BIG_N (double)16.0
#define NORM_CH_BUSY (!(SV->Normal_Channels & 0xffffffff))
#define RESERVE_CH_BUSY (!(SV->Reserve_Channels & 0xffffffff))
#define NONE 0
#define NORMAL_CH 1
#define RESERVE 2
#define COMPLETECALL 3
#define NEXTCALL 4
#define MOVECALL 5
#define NEXTCALL_METHOD 6
#define COMPLETIONCALL_METHOD 7
#define MOVECALLIN_METHOD 8
#define MOVECALLOUT_METHOD 9
Typedefs
typedef int Channel_t
typedef int Min_t
typedef int MethodName_t
Functions
void Cell_EventHandler (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
Min_t Cell_MinTS (struct Msg_Data *M)
void Cell_StartUp (struct State *SV, tw_lp *lp)
void Cell_NextCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_CompletionCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_MoveCallIn (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_MoveCallOut (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_EventHandler (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_NextCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_CompletionCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_MoveCallIn (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_MoveCallOut (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void CellStatistics_CollectStats (struct State *, tw_lp *lp)
void CellStatistics_Compute ()
void CellStatistics_Print ()
Variables
struct CellStatistics TWAppStats
tw_lpid nlp_per_pe = 0
Macro Definition Documentation
#define BIG_N (double)16.0
Definition at line 21 of file pcs.h.
Referenced by GenInitPortables(), and main().
#define CALL_TIME_MEAN 180.0
Definition at line 19 of file pcs.h.
Referenced by Cell_NextCall(), and main().
#define COMPLETECALL 3
Definition at line 41 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MinTS(), Cell_MoveCallIn(), Cell_NextCall(), and Cell_StartUp().
#define COMPLETIONCALL_METHOD 7
Definition at line 46 of file pcs.h.
Referenced by Cell_EventHandler(), Cell_MoveCallIn(), Cell_NextCall(), and RC_Cell_EventHandler().
#define MAX_NORMAL_CHANNELS 10
Definition at line 11 of file pcs.h.
Referenced by Cell_CompletionCall(), and Cell_StartUp().
#define MAX_RESERVE_CHANNELS 0
Definition at line 12 of file pcs.h.
Referenced by Cell_CompletionCall(), and Cell_StartUp().
#define MOVE_CALL_MEAN 4500.0
Definition at line 17 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_NextCall(), Cell_StartUp(), and main().
#define MOVECALL 5
Definition at line 43 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MinTS(), Cell_MoveCallIn(), Cell_NextCall(), and Cell_StartUp().
#define MOVECALLIN_METHOD 8
Definition at line 47 of file pcs.h.
Referenced by Cell_EventHandler(), Cell_MoveCallOut(), and RC_Cell_EventHandler().
#define MOVECALLOUT_METHOD 9
Definition at line 48 of file pcs.h.
Referenced by Cell_EventHandler(), Cell_MoveCallIn(), Cell_NextCall(), and RC_Cell_EventHandler().
#define NEXT_CALL_MEAN 360.0
Definition at line 18 of file pcs.h.
Referenced by Cell_MoveCallIn(), Cell_NextCall(), Cell_StartUp(), and main().
#define NEXTCALL 4
Definition at line 42 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MinTS(), Cell_MoveCallIn(), Cell_NextCall(), and Cell_StartUp().
#define NEXTCALL_METHOD 6
Definition at line 45 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_NextCall(), Cell_StartUp(), and RC_Cell_EventHandler().
#define NONE 0
Definition at line 37 of file pcs.h.
Referenced by Cell_CompletionCall(), and Cell_MoveCallOut().
#define NORM_CH_BUSY (!(SV->Normal_Channels & 0xffffffff))
Definition at line 26 of file pcs.h.
Referenced by Cell_MoveCallIn(), and Cell_NextCall().
#define NORMAL_CH 1
Definition at line 38 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), and Cell_NextCall().
#define NUM_CELLS_X 1024
Definition at line 5 of file pcs.h.
Referenced by Cell_ComputeMove(), Cell_StartUp(), CellMapping_lp_to_pe(), CellMapping_to_local_index(), CellMapping_to_lp(), main(), and pcs_grid_mapping().
#define NUM_CELLS_Y 1024
Definition at line 6 of file pcs.h.
Referenced by Cell_ComputeMove(), Cell_StartUp(), main(), and pcs_grid_mapping().
#define NUM_VP_X 512
Definition at line 8 of file pcs.h.
#define NUM_VP_Y 512
Definition at line 9 of file pcs.h.
#define RESERVE 2
Definition at line 39 of file pcs.h.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), and Cell_MoveCallOut().
#define RESERVE_CH_BUSY (!(SV->Reserve_Channels & 0xffffffff))
Definition at line 31 of file pcs.h.
Referenced by Cell_MoveCallIn().
#define TW_MAX_NAME_LEN 31
Definition at line 3 of file pcs.h.
Typedef Documentation
typedef int Channel_t
Definition at line 33 of file pcs.h.
typedef int MethodName_t
Definition at line 35 of file pcs.h.
typedef int Min_t
Definition at line 34 of file pcs.h.
Function Documentation
void Cell_CompletionCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 347 of file pcs.c.
References tw_bf::c1, tw_bf::c2, Cell_ComputeMove(), Cell_MinTS(), Msg_Data::ChannelType, COMPLETECALL, Msg_Data::CompletionCallTS, tw_lp::gid, max, MAX_NORMAL_CHANNELS, MAX_RESERVE_CHANNELS, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, Msg_Data::MoveCallTS, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NONE, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, RESERVE, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
void Cell_EventHandler (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 622 of file pcs.c.
References Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), COMPLETIONCALL_METHOD, tw_lp::id, Msg_Data::MethodName, MOVECALLIN_METHOD, MOVECALLOUT_METHOD, NEXTCALL_METHOD, Msg_Data::RC, rng_get_state(), tw_error(), tw_exit(), TW_LOC, tw_now(), and RC::wl1.
Min_t Cell_MinTS (struct Msg_Data * M)
Definition at line 121 of file pcs.c.
References COMPLETECALL, Msg_Data::CompletionCallTS, MOVECALL, Msg_Data::MoveCallTS, NEXTCALL, and Msg_Data::NextCallTS.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_NextCall(), and Cell_StartUp().
void Cell_MoveCallIn (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 433 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, tw_bf::c2, tw_bf::c3, State::Call_Attempts, Cell_ComputeMove(), Cell_MinTS(), Msg_Data::ChannelType, COMPLETECALL, COMPLETIONCALL_METHOD, Msg_Data::CompletionCallTS, tw_lp::gid, State::Handoff_Blocks, max, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, MOVECALLOUT_METHOD, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NORM_CH_BUSY, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, RESERVE, RESERVE_CH_BUSY, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
void Cell_MoveCallOut (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 571 of file pcs.c.
References tw_bf::c1, tw_bf::c2, Cell_ComputeMove(), Msg_Data::ChannelType, Msg_Data::CompletionCallTS, tw_lp::gid, max, Msg_Data::MethodName, MOVECALLIN_METHOD, Msg_Data::MoveCallTS, Msg_Data::NextCallTS, NONE, NORMAL_CH, State::Normal_Channels, RESERVE, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), and tw_rand_integer().
Referenced by Cell_EventHandler().
void Cell_NextCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 221 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, State::Call_Attempts, CALL_TIME_MEAN, Cell_ComputeMove(), Cell_MinTS(), State::Channel_Blocks, Msg_Data::ChannelType, COMPLETECALL, COMPLETIONCALL_METHOD, Msg_Data::CompletionCallTS, tw_lp::gid, max, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, MOVECALLOUT_METHOD, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NORM_CH_BUSY, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
void Cell_StartUp (struct State * SV, tw_lp * lp)
Definition at line 139 of file pcs.c.
References State::Busy_Lines, State::Call_Attempts, Cell_ComputeMove(), Cell_MinTS(), State::CellLocationX, State::CellLocationY, State::Channel_Blocks, COMPLETECALL, Msg_Data::CompletionCallTS, GenInitPortables(), tw_lp::gid, State::Handoff_Blocks, tw_lp::id, max, MAX_NORMAL_CHANNELS, MAX_RESERVE_CHANNELS, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, State::Normal_Channels, NUM_CELLS_X, NUM_CELLS_Y, State::Portables_In, State::Portables_Out, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_rand_exponential(), and tw_rand_integer().
void CellStatistics_CollectStats (struct State * , tw_lp * lp)
Definition at line 781 of file pcs.c.
References State::Busy_Lines, CellStatistics::Busy_Lines, State::Call_Attempts, CellStatistics::Call_Attempts, State::Channel_Blocks, CellStatistics::Channel_Blocks, State::Handoff_Blocks, CellStatistics::Handoff_Blocks, State::Portables_In, CellStatistics::Portables_In, State::Portables_Out, CellStatistics::Portables_Out, and TWAppStats.
void CellStatistics_Compute ()
void CellStatistics_Print ()
void RC_Cell_CompletionCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 687 of file pcs.c.
References tw_bf::c1, tw_bf::c2, State::Normal_Channels, Msg_Data::RC, State::Reserve_Channels, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
void RC_Cell_EventHandler (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 751 of file pcs.c.
References COMPLETIONCALL_METHOD, tw_lp::id, Msg_Data::MethodName, MOVECALLIN_METHOD, MOVECALLOUT_METHOD, NEXTCALL_METHOD, RC_Cell_CompletionCall(), RC_Cell_MoveCallIn(), RC_Cell_MoveCallOut(), RC_Cell_NextCall(), and rng_get_state().
void RC_Cell_MoveCallIn (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 704 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, tw_bf::c2, tw_bf::c3, State::Call_Attempts, State::Handoff_Blocks, State::Normal_Channels, Msg_Data::RC, State::Reserve_Channels, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
void RC_Cell_MoveCallOut (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 737 of file pcs.c.
References tw_bf::c1, tw_bf::c2, State::Normal_Channels, State::Reserve_Channels, tw_lp::rng, and tw_rand_reverse_unif.
Referenced by RC_Cell_EventHandler().
void RC_Cell_NextCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 658 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, State::Call_Attempts, State::Channel_Blocks, State::Normal_Channels, Msg_Data::RC, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
Variable Documentation
tw_lpid nlp_per_pe = 0
Definition at line 112 of file pcs.h.
struct CellStatistics TWAppStats
Definition at line 111 of file pcs.h.
Referenced by CellStatistics_CollectStats(), main(), tcp_host_Statistics_CollectStats(), and tcp_router_Statistics_CollectStats().