ROSS: ross/models/pcs/pcs.c File Reference
pcs.c File Reference
#include "pcs.h"
Macros
#define TW_CELL 1
Functions
double Pi_Distribution (double n, double N)
int GenInitPortables (tw_lp *lp)
tw_lpid Cell_ComputeMove (tw_lpid lpid, int direction)
tw_peid CellMapping_lp_to_pe (tw_lpid lpid)
tw_lp * CellMapping_to_lp (tw_lpid lpid)
tw_lpid CellMapping_to_local_index (tw_lpid lpid)
Min_t Cell_MinTS (struct Msg_Data *M)
void Cell_StartUp (struct State *SV, tw_lp *lp)
void Cell_NextCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_CompletionCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_MoveCallIn (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_MoveCallOut (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void Cell_EventHandler (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_NextCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_CompletionCall (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_MoveCallIn (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_MoveCallOut (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void RC_Cell_EventHandler (struct State *SV, tw_bf *CV, struct Msg_Data *M, tw_lp *lp)
void CellStatistics_CollectStats (struct State *SV, tw_lp *lp)
void CellStatistics_Compute (struct CellStatistics *CS)
void CellStatistics_Print (struct CellStatistics *CS)
void FindMostSquare (int *xpe, int *ype)
void pcs_grid_mapping ()
int main (int argc, char **argv)
Variables
tw_lpid g_vp_per_proc =0
tw_lpid g_cells_per_vp_x = 1024 / 512
tw_lpid g_cells_per_vp_y = 1024 / 512
tw_lpid g_cells_per_vp = (1024 / 512)*(1024 / 512)
tw_lptype mylps []
Macro Definition Documentation
#define TW_CELL 1
Definition at line 858 of file pcs.c.
Function Documentation
void Cell_CompletionCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 347 of file pcs.c.
References tw_bf::c1, tw_bf::c2, Cell_ComputeMove(), Cell_MinTS(), Msg_Data::ChannelType, COMPLETECALL, Msg_Data::CompletionCallTS, tw_lp::gid, max, MAX_NORMAL_CHANNELS, MAX_RESERVE_CHANNELS, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, Msg_Data::MoveCallTS, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NONE, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, RESERVE, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
tw_lpid Cell_ComputeMove (tw_lpid lpid, int direction)
Definition at line 26 of file pcs.c.
References NUM_CELLS_X, NUM_CELLS_Y, tw_error(), and TW_LOC.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), and Intersection_EventHandler().
void Cell_EventHandler (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 622 of file pcs.c.
References Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), COMPLETIONCALL_METHOD, tw_lp::id, Msg_Data::MethodName, MOVECALLIN_METHOD, MOVECALLOUT_METHOD, NEXTCALL_METHOD, Msg_Data::RC, rng_get_state(), tw_error(), tw_exit(), TW_LOC, tw_now(), and RC::wl1.
Min_t Cell_MinTS (struct Msg_Data * M)
Definition at line 121 of file pcs.c.
References COMPLETECALL, Msg_Data::CompletionCallTS, MOVECALL, Msg_Data::MoveCallTS, NEXTCALL, and Msg_Data::NextCallTS.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_NextCall(), and Cell_StartUp().
void Cell_MoveCallIn (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 433 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, tw_bf::c2, tw_bf::c3, State::Call_Attempts, Cell_ComputeMove(), Cell_MinTS(), Msg_Data::ChannelType, COMPLETECALL, COMPLETIONCALL_METHOD, Msg_Data::CompletionCallTS, tw_lp::gid, State::Handoff_Blocks, max, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, MOVECALLOUT_METHOD, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NORM_CH_BUSY, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, RESERVE, RESERVE_CH_BUSY, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
void Cell_MoveCallOut (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 571 of file pcs.c.
References tw_bf::c1, tw_bf::c2, Cell_ComputeMove(), Msg_Data::ChannelType, Msg_Data::CompletionCallTS, tw_lp::gid, max, Msg_Data::MethodName, MOVECALLIN_METHOD, Msg_Data::MoveCallTS, Msg_Data::NextCallTS, NONE, NORMAL_CH, State::Normal_Channels, RESERVE, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), tw_exit(), TW_LOC, tw_now(), and tw_rand_integer().
Referenced by Cell_EventHandler().
void Cell_NextCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 221 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, State::Call_Attempts, CALL_TIME_MEAN, Cell_ComputeMove(), Cell_MinTS(), State::Channel_Blocks, Msg_Data::ChannelType, COMPLETECALL, COMPLETIONCALL_METHOD, Msg_Data::CompletionCallTS, tw_lp::gid, max, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, MOVECALLOUT_METHOD, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, NORM_CH_BUSY, NORMAL_CH, State::Normal_Channels, Msg_Data::RC, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_rand_exponential(), tw_rand_integer(), and RC::wl1.
Referenced by Cell_EventHandler().
void Cell_StartUp (struct State * SV, tw_lp * lp)
Definition at line 139 of file pcs.c.
References State::Busy_Lines, State::Call_Attempts, Cell_ComputeMove(), Cell_MinTS(), State::CellLocationX, State::CellLocationY, State::Channel_Blocks, COMPLETECALL, Msg_Data::CompletionCallTS, GenInitPortables(), tw_lp::gid, State::Handoff_Blocks, tw_lp::id, max, MAX_NORMAL_CHANNELS, MAX_RESERVE_CHANNELS, Msg_Data::MethodName, MOVE_CALL_MEAN, MOVECALL, Msg_Data::MoveCallTS, NEXT_CALL_MEAN, NEXTCALL, NEXTCALL_METHOD, Msg_Data::NextCallTS, State::Normal_Channels, NUM_CELLS_X, NUM_CELLS_Y, State::Portables_In, State::Portables_Out, State::Reserve_Channels, tw_lp::rng, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_rand_exponential(), and tw_rand_integer().
tw_peid CellMapping_lp_to_pe (tw_lpid lpid)
Definition at line 67 of file pcs.c.
References g_cells_per_vp_x, g_cells_per_vp_y, g_vp_per_proc, NUM_CELLS_X, and NUM_VP_X.
Referenced by pcs_grid_mapping(), and traffic_grid_mapping().
tw_lpid CellMapping_to_local_index (tw_lpid lpid)
Definition at line 99 of file pcs.c.
References g_cells_per_vp, g_cells_per_vp_x, g_cells_per_vp_y, g_tw_nlp, g_vp_per_proc, NUM_CELLS_X, NUM_VP_X, tw_error(), and TW_LOC.
Referenced by pcs_grid_mapping(), and traffic_grid_mapping().
tw_lp* CellMapping_to_lp (tw_lpid lpid)
Definition at line 78 of file pcs.c.
References g_cells_per_vp, g_cells_per_vp_x, g_cells_per_vp_y, g_tw_lp, g_tw_nlp, g_vp_per_proc, NUM_CELLS_X, NUM_VP_X, tw_error(), and TW_LOC.
Referenced by main().
void CellStatistics_CollectStats (struct State * SV, tw_lp * lp)
Definition at line 781 of file pcs.c.
References State::Busy_Lines, CellStatistics::Busy_Lines, State::Call_Attempts, CellStatistics::Call_Attempts, State::Channel_Blocks, CellStatistics::Channel_Blocks, State::Handoff_Blocks, CellStatistics::Handoff_Blocks, State::Portables_In, CellStatistics::Portables_In, State::Portables_Out, CellStatistics::Portables_Out, and TWAppStats.
void CellStatistics_Compute (struct CellStatistics * CS)
Definition at line 792 of file pcs.c.
References CellStatistics::Blocking_Probability, CellStatistics::Busy_Lines, CellStatistics::Call_Attempts, CellStatistics::Channel_Blocks, and CellStatistics::Handoff_Blocks.
Referenced by main().
void CellStatistics_Print (struct CellStatistics * CS)
Definition at line 799 of file pcs.c.
References CellStatistics::Blocking_Probability, CellStatistics::Busy_Lines, CellStatistics::Call_Attempts, CellStatistics::Channel_Blocks, CellStatistics::Handoff_Blocks, CellStatistics::Portables_In, and CellStatistics::Portables_Out.
Referenced by main().
void FindMostSquare (int * xpe, int * ype)
Definition at line 818 of file pcs.c.
References g_tw_npe, npe, and x.
int GenInitPortables (tw_lp * lp)
Definition at line 16 of file pcs.c.
References BIG_N.
Referenced by Cell_StartUp().
int main (int argc, char ** argv)
Definition at line 913 of file pcs.c.
References BIG_N, CellStatistics::Blocking_Probability, CellStatistics::Busy_Lines, CellStatistics::Call_Attempts, CALL_TIME_MEAN, CellMapping_to_lp(), CellStatistics_Compute(), CellStatistics_Print(), CellStatistics::Channel_Blocks, CUSTOM, g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_gvt_interval, g_tw_mapping, g_tw_mblock, g_tw_nkp, g_tw_nlp, g_tw_npe, g_vp_per_proc, CellStatistics::Handoff_Blocks, MOVE_CALL_MEAN, NEXT_CALL_MEAN, nlp_per_pe, num_cells_per_kp, NUM_CELLS_X, NUM_CELLS_Y, NUM_VP_X, NUM_VP_Y, pcs_grid_mapping(), CellStatistics::Portables_In, CellStatistics::Portables_Out, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_nnodes(), tw_run(), TWAppStats, and vp_per_proc.
void pcs_grid_mapping ()
Definition at line 873 of file pcs.c.
References CellMapping_lp_to_pe(), CellMapping_to_local_index(), g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_pe, lpid, nlp_per_pe, num_cells_per_kp, NUM_CELLS_X, NUM_CELLS_Y, NUM_VP_X, NUM_VP_Y, tw_error(), tw_kp_onpe(), TW_LOC, tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_nnodes(), vp_per_proc, and x.
Referenced by main().
double Pi_Distribution (double n, double N)
Definition at line 4 of file pcs.c.
void RC_Cell_CompletionCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 687 of file pcs.c.
References tw_bf::c1, tw_bf::c2, State::Normal_Channels, Msg_Data::RC, State::Reserve_Channels, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
void RC_Cell_EventHandler (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 751 of file pcs.c.
References COMPLETIONCALL_METHOD, tw_lp::id, Msg_Data::MethodName, MOVECALLIN_METHOD, MOVECALLOUT_METHOD, NEXTCALL_METHOD, RC_Cell_CompletionCall(), RC_Cell_MoveCallIn(), RC_Cell_MoveCallOut(), RC_Cell_NextCall(), and rng_get_state().
void RC_Cell_MoveCallIn (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 704 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, tw_bf::c2, tw_bf::c3, State::Call_Attempts, State::Handoff_Blocks, State::Normal_Channels, Msg_Data::RC, State::Reserve_Channels, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
void RC_Cell_MoveCallOut (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 737 of file pcs.c.
References tw_bf::c1, tw_bf::c2, State::Normal_Channels, State::Reserve_Channels, tw_lp::rng, and tw_rand_reverse_unif.
Referenced by RC_Cell_EventHandler().
void RC_Cell_NextCall (struct State * SV, tw_bf * CV, struct Msg_Data * M, tw_lp * lp)
Definition at line 658 of file pcs.c.
References State::Busy_Lines, tw_bf::c1, State::Call_Attempts, State::Channel_Blocks, State::Normal_Channels, Msg_Data::RC, tw_lp::rng, tw_rand_reverse_unif, and RC::wl1.
Referenced by RC_Cell_EventHandler().
Variable Documentation
tw_lpid g_cells_per_vp = (1024 / 512)*(1024 / 512)
Definition at line 24 of file pcs.c.
Referenced by CellMapping_to_local_index(), and CellMapping_to_lp().
tw_lpid g_cells_per_vp_x = 1024 / 512
Definition at line 22 of file pcs.c.
Referenced by CellMapping_lp_to_pe(), CellMapping_to_local_index(), and CellMapping_to_lp().
tw_lpid g_cells_per_vp_y = 1024 / 512
Definition at line 23 of file pcs.c.
Referenced by CellMapping_lp_to_pe(), CellMapping_to_local_index(), and CellMapping_to_lp().
tw_lpid g_vp_per_proc =0
Definition at line 21 of file pcs.c.
tw_lptype mylps[]
Initial value:
=
  {
    {
      (init_f) Cell_StartUp,
      (event_f) Cell_EventHandler,
      (revent_f) RC_Cell_EventHandler,
      (final_f) CellStatistics_CollectStats,
      (map_f) CellMapping_lp_to_pe,
      sizeof(struct State)
    },
    {0},
  }
Definition at line 860 of file pcs.c.