ROSS: rnf/modules/network/multicast/pgmcc.h File Reference
pgmcc.h File Reference
#include "Transport.h"
#include <math.h>
Data Structures
struct PgmccSrcInfoStruct
struct PgmccRcvInfoStruct
Macros
#define TRACE_PGMCC_THROUGHPUT 1
#define PGMCC_THROUGHPUT_SAMPLE_ITVL 0.5
#define PGMCC_SRC_DATA_PKT_SIZE 1000
#define PGMCC_RCV_FDBK_PKT_SIZE 40
#define PGMCC_OPT_LOSSRATE 0x00010000
#define PGMCC_OPT_SEND_NAK 0x00020000
#define PGMCC_OPT_ELECT 0x00040000
#define PGMCC_OPT_TIMESTAMP 0x00080000
#define PGMCC_SRC_SS_THRESH 6
#define PGMCC_SRC_DUP_THRESH 3
#define PGMCC_SRC_WEIGHT 0.992
#define PGMCC_SRC_CC_TIMEOUT 4.0
#define PGMCC_SRC_HYST 1.5
#define PGMCC_RCV_WEIGHT 0.992
Typedefs
typedef struct PgmccSrcInfoStruct PgmccSrcInfo
typedef struct PgmccRcvInfoStruct PgmccRcvInfo
Enumerations
enum { PGMCC_SRC_TIMER_CC }
Functions
Agent * PgmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
void PgmccSrcStart (Agent *agent)
void PgmccSrcStop (Agent *agent)
void PgmccSrcSendPkt (Agent *agent)
void PgmccSrcTimer (Agent *agent, int timerId, int serial)
void PgmccSrcPktHandler (Agent *agent, Packet *p)
void PgmccSrcAckProc (Agent *agent, Packet *p)
void PgmccSrcNakProc (Agent *agent, Packet *p)
void PgmccSrcStall (Agent *agent)
void PgmccSrcPrintStat (Agent *agent)
Agent * PgmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
void PgmccRcvStart (Agent *agent)
void PgmccRcvStop (Agent *agent)
void PgmccRcvPktHandler (Agent *agent, Packet *p)
void PgmccRcvSendPkt (Agent *agent, Packet *srcPkt, int16 type)
void PgmccRcvTimer (Agent *agent, int timerId, int serial)
void PgmccRcvPrintStat (Agent *agent)
Macro Definition Documentation
#define PGMCC_OPT_ELECT 0x00040000
Definition at line 20 of file pgmcc.h.
#define PGMCC_OPT_LOSSRATE 0x00010000
Definition at line 18 of file pgmcc.h.
#define PGMCC_OPT_SEND_NAK 0x00020000
Definition at line 19 of file pgmcc.h.
#define PGMCC_OPT_TIMESTAMP 0x00080000
Definition at line 21 of file pgmcc.h.
#define PGMCC_RCV_FDBK_PKT_SIZE 40
Definition at line 15 of file pgmcc.h.
Referenced by PgmccRcvSendPkt().
#define PGMCC_RCV_WEIGHT 0.992
Definition at line 29 of file pgmcc.h.
Referenced by PgmccRcvPktHandler().
#define PGMCC_SRC_CC_TIMEOUT 4.0
Definition at line 26 of file pgmcc.h.
Referenced by PgmccSrcAckProc(), PgmccSrcStall(), and PgmccSrcStart().
#define PGMCC_SRC_DATA_PKT_SIZE 1000
Definition at line 14 of file pgmcc.h.
Referenced by PgmccSrcStart().
#define PGMCC_SRC_DUP_THRESH 3
Definition at line 24 of file pgmcc.h.
Referenced by PgmccSrcAckProc().
#define PGMCC_SRC_HYST 1.5
Definition at line 27 of file pgmcc.h.
Referenced by PgmccSrcNakProc().
#define PGMCC_SRC_SS_THRESH 6
Definition at line 23 of file pgmcc.h.
Referenced by PgmccSrcAckProc(), and PgmccSrcNakProc().
#define PGMCC_SRC_WEIGHT 0.992
Definition at line 25 of file pgmcc.h.
#define PGMCC_THROUGHPUT_SAMPLE_ITVL 0.5
Definition at line 10 of file pgmcc.h.
Referenced by PgmccSrcSendPkt().
#define TRACE_PGMCC_THROUGHPUT 1
Definition at line 7 of file pgmcc.h.
Typedef Documentation
typedef struct PgmccRcvInfoStruct PgmccRcvInfo
typedef struct PgmccSrcInfoStruct PgmccSrcInfo
Enumeration Type Documentation
anonymous enum
Enumerator
PGMCC_SRC_TIMER_CC
Definition at line 32 of file pgmcc.h.
Function Documentation
Agent* PgmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
Definition at line 334 of file pgmcc.c.
References GetAgent(), AgentStruct::info_, IsMcastAddr, PgmccRcvPktHandler(), PgmccRcvPrintStat(), PgmccRcvStart(), PgmccRcvStop(), PgmccRcvTimer(), RegisterAgent(), and tw_exit().
Referenced by ReadAgentAct().
void PgmccRcvPktHandler (Agent * agent, Packet * p)
Definition at line 390 of file pgmcc.c.
References _nodeTable, PgmccRcvInfoStruct::ackBitMask_, PgmccRcvInfoStruct::active_, NodeStruct::addr_, tw_lp::id, AgentStruct::id_, AgentStruct::info_, AgentStruct::nodeId_, PacketStruct::pd_, PGMCC_ACK, PGMCC_DATA, PGMCC_NAK, PGMCC_RCV_WEIGHT, PgmccRcvSendPkt(), PgmccRcvInfoStruct::rxDoAck_, PgmccRcvInfoStruct::rxLoss_, PgmccRcvInfoStruct::rxwLead_, tw_exit(), tw_getlp(), PacketStruct::type, and PacketStruct::type_.
Referenced by PgmccRcvInit().
void PgmccRcvPrintStat (Agent * agent)
Definition at line 498 of file pgmcc.c.
References _totalPgmccAck, _totalPgmccNak, PgmccRcvInfoStruct::ackSent_, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, PgmccRcvInfoStruct::nakSent_, and AgentStruct::nodeId_.
Referenced by PgmccRcvInit().
void PgmccRcvSendPkt (Agent * agent, Packet * srcPkt, int16 type)
Definition at line 447 of file pgmcc.c.
References _nodeTable, _totalPgmccAck, _totalPgmccNak, PgmccRcvInfoStruct::ackBitMask_, PgmccRcvInfoStruct::ackSent_, PgmccRcvInfoStruct::active_, NodeStruct::addr_, PgmccAckStruct::bitmask_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, IsMcastAddr, AgentStruct::listenAddr_, PgmccRcvInfoStruct::nakSent_, AgentStruct::nodeId_, p, PacketStruct::pa_, PGMCC_ACK, PGMCC_NAK, PGMCC_RCV_FDBK_PKT_SIZE, PacketStruct::pn_, PgmccRcvInfoStruct::rxLoss_, PgmccAckStruct::rxLoss_, PgmccNakStruct::rxLoss_, PgmccRcvInfoStruct::rxwLead_, PgmccAckStruct::rxwLead_, PgmccNakStruct::rxwLead_, SendPacket(), PacketStruct::size_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, tw_exit(), tw_getlp(), PacketStruct::type, and PacketStruct::type_.
Referenced by PgmccRcvPktHandler().
void PgmccRcvStart (Agent * agent)
Definition at line 370 of file pgmcc.c.
References PgmccRcvInfoStruct::ackBitMask_, PgmccRcvInfoStruct::active_, AgentStruct::info_, PgmccRcvInfoStruct::rxDoAck_, PgmccRcvInfoStruct::rxLoss_, and PgmccRcvInfoStruct::rxwLead_.
Referenced by PgmccRcvInit().
void PgmccRcvStop (Agent * agent)
Definition at line 382 of file pgmcc.c.
References PgmccRcvInfoStruct::active_, and AgentStruct::info_.
Referenced by PgmccRcvInit().
void PgmccRcvTimer (Agent * agent, int timerId, int serial)
Definition at line 494 of file pgmcc.c.
Referenced by PgmccRcvInit().
void PgmccSrcAckProc (Agent * agent, Packet * p)
Definition at line 158 of file pgmcc.c.
References PgmccSrcInfoStruct::ackBitMask_, PgmccSrcInfoStruct::ackerAddr_, PgmccSrcInfoStruct::ackerLoss_, PgmccSrcInfoStruct::ackerMrtt_, PgmccSrcInfoStruct::ackLead_, PgmccSrcInfoStruct::ccTimerEvnt_, PgmccSrcInfoStruct::dupAcks_, PgmccSrcInfoStruct::ignoreCong_, AgentStruct::info_, PacketStruct::pa_, PGMCC_SRC_CC_TIMEOUT, PGMCC_SRC_DUP_THRESH, PGMCC_SRC_SS_THRESH, PGMCC_SRC_TIMER_CC, PgmccSrcSendPkt(), ReschedTimer(), PacketStruct::srcAddr_, PgmccSrcInfoStruct::token_, PgmccSrcInfoStruct::txwLead_, PacketStruct::type, and PgmccSrcInfoStruct::window_.
Referenced by PgmccSrcPktHandler().
Agent* PgmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
Definition at line 9 of file pgmcc.c.
References _nodeTable, GetAgent(), AgentStruct::info_, PgmccSrcPktHandler(), PgmccSrcPrintStat(), PgmccSrcStart(), PgmccSrcStop(), PgmccSrcTimer(), PgmccSrcInfoStruct::pktDstAddr_, PgmccSrcInfoStruct::pktDstAgentId_, RegisterAgent(), PgmccSrcInfoStruct::trackStat_, and tw_exit().
Referenced by ReadAgentAct().
void PgmccSrcNakProc (Agent * agent, Packet * p)
Definition at line 267 of file pgmcc.c.
References _addrToIdx, PgmccSrcInfoStruct::ackBitMask_, PgmccSrcInfoStruct::ackerAddr_, PgmccSrcInfoStruct::ackerLoss_, PgmccSrcInfoStruct::ackerMrtt_, PgmccSrcInfoStruct::ackLead_, AgentStruct::id_, AgentStruct::info_, AgentStruct::nodeId_, PGMCC_SRC_HYST, PGMCC_SRC_SS_THRESH, PgmccSrcSendPkt(), PacketStruct::pn_, PgmccNakStruct::rxLoss_, PgmccNakStruct::rxwLead_, PacketStruct::srcAddr_, PgmccSrcInfoStruct::token_, tw_getlp(), tw_now(), PgmccSrcInfoStruct::txwLead_, PacketStruct::type, and PgmccSrcInfoStruct::window_.
Referenced by PgmccSrcPktHandler().
void PgmccSrcPktHandler (Agent * agent, Packet * p)
Definition at line 138 of file pgmcc.c.
References PgmccSrcInfoStruct::active_, AgentStruct::info_, PGMCC_ACK, PGMCC_NAK, PgmccSrcAckProc(), PgmccSrcNakProc(), tw_exit(), and PacketStruct::type_.
Referenced by PgmccSrcInit().
void PgmccSrcPrintStat (Agent * agent)
Definition at line 325 of file pgmcc.c.
Referenced by PgmccSrcInit().
void PgmccSrcSendPkt (Agent * agent)
Definition at line 80 of file pgmcc.c.
References _nodeTable, PgmccSrcInfoStruct::ackerAddr_, PgmccDataStruct::ackerAddr_, PgmccSrcInfoStruct::active_, NodeStruct::addr_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, AgentStruct::nodeId_, p, PacketStruct::pd_, PGMCC_DATA, PGMCC_THROUGHPUT_SAMPLE_ITVL, PgmccSrcInfoStruct::pktDstAddr_, PgmccSrcInfoStruct::pktDstAgentId_, PgmccSrcInfoStruct::pktSize_, SendPacket(), PacketStruct::size_, PgmccDataStruct::sqn_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, PgmccSrcInfoStruct::thruSampleTime_, PgmccSrcInfoStruct::token_, PgmccSrcInfoStruct::totalSentBytes_, PgmccSrcInfoStruct::trackStat_, tw_getlp(), tw_now(), PgmccSrcInfoStruct::txwLead_, PacketStruct::type, and PacketStruct::type_.
Referenced by PgmccSrcAckProc(), PgmccSrcNakProc(), PgmccSrcStall(), and PgmccSrcStart().
void PgmccSrcStall (Agent * agent) inline
Definition at line 308 of file pgmcc.c.
References PgmccSrcInfoStruct::ackBitMask_, PgmccSrcInfoStruct::ackLead_, PgmccSrcInfoStruct::ccTimerEvnt_, PgmccSrcInfoStruct::dupAcks_, PgmccSrcInfoStruct::ignoreCong_, AgentStruct::info_, PGMCC_SRC_CC_TIMEOUT, PGMCC_SRC_TIMER_CC, PgmccSrcSendPkt(), ScheduleTimer(), PgmccSrcInfoStruct::token_, PgmccSrcInfoStruct::txwLead_, and PgmccSrcInfoStruct::window_.
Referenced by PgmccSrcTimer().
void PgmccSrcStart (Agent * agent)
Definition at line 41 of file pgmcc.c.
References PgmccSrcInfoStruct::ackBitMask_, PgmccSrcInfoStruct::ackerAddr_, PgmccSrcInfoStruct::ackerLoss_, PgmccSrcInfoStruct::ackerMrtt_, PgmccSrcInfoStruct::ackLead_, PgmccSrcInfoStruct::active_, PgmccSrcInfoStruct::ccTimerEvnt_, PgmccSrcInfoStruct::dupAcks_, PgmccSrcInfoStruct::ignoreCong_, AgentStruct::info_, AgentStruct::nodeId_, PGMCC_SRC_CC_TIMEOUT, PGMCC_SRC_DATA_PKT_SIZE, PGMCC_SRC_TIMER_CC, PgmccSrcSendPkt(), PgmccSrcInfoStruct::pktSize_, ScheduleTimer(), PgmccSrcInfoStruct::thruSampleTime_, PgmccSrcInfoStruct::token_, PgmccSrcInfoStruct::totalSentBytes_, tw_getlp(), tw_now(), PgmccSrcInfoStruct::txwLead_, and PgmccSrcInfoStruct::window_.
Referenced by PgmccSrcInit().
void PgmccSrcStop (Agent * agent)
Definition at line 71 of file pgmcc.c.
References PgmccSrcInfoStruct::active_, CancelTimer(), PgmccSrcInfoStruct::ccTimerEvnt_, and AgentStruct::info_.
Referenced by PgmccSrcInit().
void PgmccSrcTimer (Agent * agent, int timerId, int serial)
Definition at line 125 of file pgmcc.c.
References PGMCC_SRC_TIMER_CC, PgmccSrcStall(), and tw_exit().
Referenced by PgmccSrcInit().