ROSS: models/phold/phold.c File Reference
phold.c File Reference
#include "phold.h"
Functions
tw_peid phold_map (tw_lpid gid)
void phold_init (phold_state *s, tw_lp *lp)
void phold_pre_run (phold_state *s, tw_lp *lp)
void phold_event_handler (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_event_handler_rc (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_commit (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_finish (phold_state *s, tw_lp *lp)
void rb_event_trace (phold_message *m, tw_lp *lp, char *buffer, int *collect_flag)
void phold_stats_collect (phold_state *s, tw_lp *lp, char *buffer)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
st_model_types model_types []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 151 of file phold.c.
References g_phold_start_events, g_tw_events_per_pe, g_tw_lookahead, g_tw_memory_nqueues, g_tw_mynode, g_tw_nlp, g_tw_npe, lookahead, mean, mult, nlp_per_pe, offset_lpid, optimistic_memory, percent_remote, st_model_settype(), stagger, ttl_lps, tw_comm_set(), tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
void phold_commit (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 91 of file phold.c.
void phold_event_handler (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 57 of file phold.c.
References tw_bf::c1, g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
void phold_event_handler_rc (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 82 of file phold.c.
References tw_bf::c1, tw_lp::rng, and tw_rand_reverse_unif.
void phold_finish (phold_state * s, tw_lp * lp)
Definition at line 96 of file phold.c.
void phold_init (phold_state * s, tw_lp * lp)
Definition at line 11 of file phold.c.
References g_phold_start_events, g_tw_ts_end, tw_lp::gid, lookahead, mean, tw_lp::rng, stagger, tw_event_new(), tw_event_send(), and tw_rand_exponential().
tw_peid phold_map (tw_lpid gid)
Definition at line 5 of file phold.c.
References g_tw_nlp.
void phold_pre_run (phold_state * s, tw_lp * lp)
Definition at line 38 of file phold.c.
References g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
void phold_stats_collect (phold_state * s, tw_lp * lp, char * buffer)
Definition at line 118 of file phold.c.
void rb_event_trace (phold_message * m, tw_lp * lp, char * buffer, int * collect_flag)
Definition at line 113 of file phold.c.
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("PHOLD Model"),
        TWOPT_STIME("remote", percent_remote, "desired remote event rate"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_STIME("lookahead", lookahead, "lookahead for events"),
        TWOPT_UINT("start-events", g_phold_start_events, "number of initial messages per LP"),
        TWOPT_UINT("stagger", stagger, "Set to 1 to stagger event uniformly across 0 to end time."),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 135 of file phold.c.
st_model_types model_types[]
Initial value:
= {
    {(rbev_trace_f) rb_event_trace,
     0,
     (ev_trace_f) rb_event_trace,
     0,
    (model_stat_f) phold_stats_collect,
    sizeof(int)},
    {0}
}
Definition at line 125 of file phold.c.
Referenced by st_model_settype().
tw_lptype mylps[]
Initial value:
= {
        {(init_f) phold_init,
     (pre_run_f) NULL,
         (event_f) phold_event_handler,
         (revent_f) phold_event_handler_rc,
         (commit_f) phold_commit,
         (final_f) phold_finish,
         (map_f) phold_map,
        sizeof(phold_state)},
        {0},
}
Definition at line 100 of file phold.c.