ROSS: models/phold/phold-gvt-hook.main.c File Reference
phold-gvt-hook.main.c File Reference
#include "phold.h"
Functions
tw_peid phold_map (tw_lpid gid)
void phold_init (phold_state *s, tw_lp *lp)
void phold_pre_run (phold_state *s, tw_lp *lp)
void phold_event_handler (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_event_handler_rc (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_commit (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_finish (phold_state *s, tw_lp *lp)
void gvt_hook (tw_pe *pe, bool past_end_time)
int main (int argc, char **argv)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
gvt_hook()
void gvt_hook (tw_pe * pe, bool past_end_time)
Definition at line 111 of file phold-gvt-hook.main.c.
References g_tw_mynode, pe, tw_event_sig::recv_ts, and tw_trigger_gvt_hook_at().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 146 of file phold-gvt-hook.main.c.
References app_opt, g_phold_start_events, g_tw_events_per_pe, g_tw_gvt_hook, g_tw_lookahead, g_tw_mynode, g_tw_nlp, gvt_hook(), lookahead, mean, mult, mylps, nlp_per_pe, offset_lpid, optimistic_memory, percent_remote, stagger, ttl_lps, tw_comm_set(), tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_opt_add(), tw_run(), tw_trigger_gvt_hook_at(), tw_trigger_gvt_hook_every(), and tw_trigger_gvt_hook_when_model_calls().
phold_commit()
void phold_commit (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 90 of file phold-gvt-hook.main.c.
phold_event_handler()
void phold_event_handler (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 37 of file phold-gvt-hook.main.c.
References tw_bf::c1, tw_bf::c2, g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, and tw_trigger_gvt_hook_now().
phold_event_handler_rc()
void phold_event_handler_rc (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 71 of file phold-gvt-hook.main.c.
References tw_bf::c1, tw_bf::c2, tw_lp::rng, tw_rand_reverse_unif, and tw_trigger_gvt_hook_now_rev().
phold_finish()
void phold_finish (phold_state * s, tw_lp * lp)
Definition at line 97 of file phold-gvt-hook.main.c.
phold_init()
void phold_init (phold_state * s, tw_lp * lp)
Definition at line 5 of file phold-gvt-hook.main.c.
References g_phold_start_events, g_tw_ts_end, tw_lp::gid, lookahead, mean, tw_lp::rng, stagger, tw_event_new(), tw_event_send(), and tw_rand_exponential().
phold_map()
tw_peid phold_map (tw_lpid gid)
Definition at line 3 of file phold-gvt-hook.main.c.
References g_tw_nlp.
phold_pre_run()
void phold_pre_run (phold_state * s, tw_lp * lp)
Definition at line 19 of file phold-gvt-hook.main.c.
References g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
Variable Documentation
app_opt
const tw_optdef app_opt[]
Initial value:
= {
    TWOPT_GROUP("PHOLD Model"),
    TWOPT_DOUBLE("remote", percent_remote, "desired remote event rate"),
    TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
    TWOPT_DOUBLE("mean", mean, "exponential distribution mean for timestamps"),
    TWOPT_DOUBLE("mult", mult, "multiplier for event memory allocation"),
    TWOPT_DOUBLE("lookahead", lookahead, "lookahead for events"),
    TWOPT_UINT("start-events", g_phold_start_events,
               "number of initial messages per LP"),
    TWOPT_UINT("stagger", stagger,
               "Set to 1 to stagger event uniformly across 0 to end time."),
    TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
    TWOPT_CHAR("run", run_id, "user supplied run name"),
    TWOPT_END()}
Definition at line 131 of file phold-gvt-hook.main.c.
Referenced by main().
mylps
tw_lptype mylps[]
Initial value:
= {
    {(init_f)phold_init,
     (pre_run_f)NULL, (event_f)phold_event_handler,
     (revent_f)phold_event_handler_rc, (commit_f)phold_commit,
     (final_f)phold_finish, (map_f)phold_map, sizeof(phold_state)},
    {0},
}
Definition at line 102 of file phold-gvt-hook.main.c.
Referenced by main().