ROSS: models/phold/phold.main.c File Reference
phold.main.c File Reference
#include "phold.h"
Data Structures
struct phold_state_checkpoint
Functions
tw_peid phold_map (tw_lpid gid)
void phold_init (phold_state *s, tw_lp *lp)
void phold_pre_run (phold_state *s, tw_lp *lp)
void phold_event_handler (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_event_handler_rc (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_commit (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_finish (phold_state *s, tw_lp *lp)
void event_trace (phold_message *m, tw_lp *lp, char *buffer, int *collect_flag)
void phold_stats_collect (phold_state *s, tw_lp *lp, char *buffer)
void save_state (struct phold_state_checkpoint *into, struct phold_state const *from)
void clean_state (struct phold_state_checkpoint *into)
void print_state (FILE *out, char const *prefix, struct phold_state *state)
void print_state_saved (FILE *out, char const *prefix, struct phold_state_checkpoint *state)
void print_event (FILE *out, char const *prefix, struct phold_state *state, struct phold_message *message)
bool check_state (struct phold_state *before, struct phold_state *after)
int main (int argc, char **argv)
Variables
tw_lptype mylps []
st_model_types model_types []
const tw_optdef app_opt []
Function Documentation
check_state()
bool check_state (struct phold_state * before, struct phold_state * after)
Definition at line 195 of file phold.main.c.
References phold_state::dummy_state.
Referenced by main().
clean_state()
void clean_state (struct phold_state_checkpoint * into)
Definition at line 177 of file phold.main.c.
Referenced by main().
event_trace()
void event_trace (phold_message * m, tw_lp * lp, char * buffer, int * collect_flag)
Definition at line 125 of file phold.main.c.
main()
int main (int argc, char ** argv)
Definition at line 201 of file phold.main.c.
References app_opt, check_state(), clean_state(), crv_add_custom_state_checkpoint(), g_phold_start_events, g_tw_events_per_pe, g_tw_lookahead, g_tw_mynode, g_tw_nlp, lookahead, mean, model_types, mult, mylps, nlp_per_pe, offset_lpid, optimistic_memory, percent_remote, print_event(), print_state(), print_state_saved(), save_state(), st_model_settype(), stagger, ttl_lps, tw_comm_set(), tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
phold_commit()
void phold_commit (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 97 of file phold.main.c.
phold_event_handler()
void phold_event_handler (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 59 of file phold.main.c.
References tw_bf::c1, g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
phold_event_handler_rc()
void phold_event_handler_rc (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 86 of file phold.main.c.
References tw_bf::c1, tw_lp::rng, and tw_rand_reverse_unif.
phold_finish()
void phold_finish (phold_state * s, tw_lp * lp)
Definition at line 106 of file phold.main.c.
phold_init()
void phold_init (phold_state * s, tw_lp * lp)
Definition at line 11 of file phold.main.c.
References g_phold_start_events, g_tw_ts_end, tw_lp::gid, lookahead, mean, tw_lp::rng, stagger, tw_event_new(), tw_event_send(), and tw_rand_exponential().
phold_map()
tw_peid phold_map (tw_lpid gid)
Definition at line 5 of file phold.main.c.
References g_tw_nlp.
phold_pre_run()
void phold_pre_run (phold_state * s, tw_lp * lp)
Definition at line 39 of file phold.main.c.
References g_tw_nlp, tw_lp::gid, lookahead, mean, percent_remote, tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
phold_stats_collect()
void phold_stats_collect (phold_state * s, tw_lp * lp, char * buffer)
Definition at line 134 of file phold.main.c.
print_event()
void print_event (FILE * out, char const * prefix, struct phold_state * state, struct phold_message * message)
Definition at line 190 of file phold.main.c.
References phold_message::dummy_data.
print_state()
void print_state (FILE * out, char const * prefix, struct phold_state * state)
Definition at line 182 of file phold.main.c.
References phold_state::dummy_state.
Referenced by main().
print_state_saved()
void print_state_saved (FILE * out, char const * prefix, struct phold_state_checkpoint * state)
Definition at line 186 of file phold.main.c.
References phold_state_checkpoint::saved_dummy_data.
Referenced by main().
save_state()
void save_state (struct phold_state_checkpoint * into, struct phold_state const * from)
Definition at line 173 of file phold.main.c.
References phold_state::dummy_state, and phold_state_checkpoint::saved_dummy_data.
Referenced by main().
Variable Documentation
app_opt
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("PHOLD Model"),
        TWOPT_DOUBLE("remote", percent_remote, "desired remote event rate"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
        TWOPT_DOUBLE("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_DOUBLE("mult", mult, "multiplier for event memory allocation"),
        TWOPT_DOUBLE("lookahead", lookahead, "lookahead for events"),
        TWOPT_UINT("start-events", g_phold_start_events, "number of initial messages per LP"),
        TWOPT_UINT("stagger", stagger, "Set to 1 to stagger event uniformly across 0 to end time."),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 153 of file phold.main.c.
model_types
st_model_types model_types[]
Initial value:
= {
    {(ev_trace_f) event_trace,
     0,
    (model_stat_f) phold_stats_collect,
    sizeof(int),
    NULL,
    NULL,
    0},
    {0}
}
Definition at line 142 of file phold.main.c.
Referenced by main(), and st_model_settype().
mylps
tw_lptype mylps[]
Initial value:
= {
        {(init_f) phold_init,
     (pre_run_f) NULL,
         (event_f) phold_event_handler,
         (revent_f) phold_event_handler_rc,
         (commit_f) phold_commit,
         (final_f) phold_finish,
         (map_f) phold_map,
        sizeof(phold_state)},
        {0},
}
Definition at line 112 of file phold.main.c.