ROSS: core/clock/ppc64le.c File Reference
ppc64le.c File Reference
#include <ross.h>
Functions
const tw_optdef * tw_clock_setup (void)
tw_clock tw_clock_read (void)
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
Variables
unsigned long long g_tw_clock_rate
static const tw_optdef clock_opts []
Function Documentation
tw_clock_init()
void tw_clock_init (tw_pe * me)
Definition at line 34 of file ppc64le.c.
References tw_pe::clock_offset, tw_pe::clock_time, tw_clock_read(), and tw_clock_read().
Referenced by tw_sched_init().
tw_clock_now()
tw_clock tw_clock_now (tw_pe * me)
Definition at line 41 of file ppc64le.c.
References tw_pe::clock_offset, tw_pe::clock_time, tw_clock_read(), and tw_clock_read().
tw_clock_read()
tw_clock tw_clock_read (void)
Definition at line 20 of file ppc64le.c.
Referenced by tw_clock_init(), and tw_clock_now().
tw_clock_setup()
const tw_optdef * tw_clock_setup (void)
Definition at line 12 of file ppc64le.c.
References clock_opts, and g_tw_clock_rate.
Referenced by tw_init().
Variable Documentation
clock_opts
const tw_optdef clock_opts[] static
Initial value:
=
{
 TWOPT_GROUP("ROSS Timing"),
 TWOPT_ULONGLONG("clock-rate", g_tw_clock_rate, "CPU Clock Rate"),
}
Definition at line 5 of file ppc64le.c.
g_tw_clock_rate
unsigned long long g_tw_clock_rate extern
Definition at line 102 of file ross-global.c.