ROSS: core/clock/ppc.c File Reference
ppc.c File Reference
#include <ross.h>
Functions
tw_clock tw_clock_read (void)
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
Function Documentation
tw_clock_init()
void tw_clock_init (tw_pe * me)
Definition at line 28 of file ppc.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
tw_clock_now()
tw_clock tw_clock_now (tw_pe * me)
Definition at line 35 of file ppc.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
tw_clock_read()
tw_clock tw_clock_read (void)
Definition at line 10 of file ppc.c.
Referenced by tw_clock_init(), and tw_clock_now().