ROSS: ross/models/propagation/tlm/rm/rm-cell.c File Reference
rm-cell.c File Reference
#include <rm.h>
Macros
#define PLOT 0
#define VERIFY_RM_CELL 0
Functions
void rm_cell_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_cell_scatter (rm_state *state, rm_message *m, tw_bf *bf, tw_lp *lp)
void rm_cell_gather (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
Macro Definition Documentation
#define PLOT 0
Definition at line 3 of file rm-cell.c.
#define VERIFY_RM_CELL 0
Definition at line 4 of file rm-cell.c.
Function Documentation
void rm_cell_gather (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 128 of file rm-cell.c.
Referenced by rm_cell_handler().
void rm_cell_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 14 of file rm-cell.c.
Referenced by _rm_event_handler().
void rm_cell_scatter (rm_state * state, rm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 49 of file rm-cell.c.
Referenced by rm_cell_handler().