ROSS: ross/models/propagation/tlm/rm/rc-rm-cell.c File Reference
rc-rm-cell.c File Reference
#include <rm.h>
Macros
#define VERIFY_RM_CELL 0
Functions
void rm_rc_cell_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_rc_scatter (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_rc_gather (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
Macro Definition Documentation
#define VERIFY_RM_CELL 0
Definition at line 3 of file rc-rm-cell.c.
Referenced by rm_rc_scatter().
Function Documentation
void rm_rc_cell_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 12 of file rc-rm-cell.c.
Referenced by _rm_rc_event_handler().
void rm_rc_gather (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 53 of file rc-rm-cell.c.
Referenced by rm_rc_cell_handler().
void rm_rc_scatter (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 37 of file rc-rm-cell.c.
Referenced by rm_rc_cell_handler().