ROSS: ross/models/propagation/tlm/pm/pm.c File Reference
pm.c File Reference
#include <pm.h>
Functions
tw_peid pm_map (tw_lpid gid)
void pm_init (pm_state *state, tw_lp *lp)
void pm_event_handler (pm_state *state, tw_bf *bf, pm_message *m, tw_lp *lp)
void pm_rc_event_handler (pm_state *state, tw_bf *bf, pm_message *m, tw_lp *lp)
void pm_final (pm_state *state, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_petype my_pes []
tw_lptype my_lps []
static const tw_optdef pm_options []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 220 of file pm.c.
References g_pm_dimensions, g_pm_nnodes, g_pm_stats, g_tw_nkp, g_tw_npe, grid, pm_init_scenario(), pm_stats_print(), rm_end(), rm_init(), rm_initialize(), rm_initialize_terrain(), rm_run(), spacing, tw_calloc(), tw_error(), TW_LOC, and tw_opt_add().
void pm_event_handler (pm_state * state, tw_bf * bf, pm_message * m, tw_lp * lp)
Definition at line 98 of file pm.c.
void pm_final (pm_state * state, tw_lp * lp)
Definition at line 172 of file pm.c.
void pm_init (pm_state * state, tw_lp * lp)
Definition at line 21 of file pm.c.
tw_peid pm_map (tw_lpid gid)
Definition at line 4 of file pm.c.
References nlp_per_pe.
void pm_rc_event_handler (pm_state * state, tw_bf * bf, pm_message * m, tw_lp * lp)
Definition at line 141 of file pm.c.
Variable Documentation
tw_lptype my_lps[]
Initial value:
=
{
        {
                (init_f) pm_init,
                (event_f) pm_event_handler,
                (revent_f) pm_rc_event_handler,
                (final_f) pm_final,
                (map_f) pm_map,
                sizeof(pm_state)
        },
        {0},
}
Definition at line 191 of file pm.c.
tw_petype my_pes[]
Initial value:
=
{
        {
                (pe_init_f) pm_pe_init,
                (pe_init_f) pm_pe_post_init,
                (pe_gvt_f) pm_pe_gvt,
                (pe_final_f) pm_pe_final
        },
        {0},
}
Definition at line 180 of file pm.c.
const tw_optdef pm_options[] static
Initial value:
=
{
        TWOPT_UINT("the-one", the_one, "single radio to model"),
        TWOPT_UINT("nradios", g_pm_nnodes, "number of radios"),
        TWOPT_UINT("rw-min", g_pm_mu, "random walk min change dir"),
        TWOPT_UINT("rw-max", g_pm_distr_sd, "random walk max change dir"),
        TWOPT_STIME("wave-percent", percent_wave, "percentage of waves per move"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 204 of file pm.c.