ROSS: ross/models/propagation/free-space/prop-loss.h File Reference
prop-loss.h File Reference
#include <ross.h>
Data Structures
struct rf_signal
Macros
#define BOLTZMANN 1.3803e-23
#define PI 3.1415926535
#define PI_SQ 9.8696043785
#define FREQ 2400000000
#define LAMBDA 0.125
#define MIN_DISTANCE 0.0001
Functions
double calcRxPower (double txPowerDbm, double distance, double lambda)
A Friis propagation loss model.
double dbmFromW (double w)
double wFromDbm (double dbm)
double calculateSnr (rf_signal rf)
Macro Definition Documentation
#define BOLTZMANN 1.3803e-23
thermal noise at 290K in J/s = W
Definition at line 8 of file prop-loss.h.
#define FREQ 2400000000
Definition at line 11 of file prop-loss.h.
#define LAMBDA 0.125
Definition at line 12 of file prop-loss.h.
#define MIN_DISTANCE 0.0001
Definition at line 13 of file prop-loss.h.
#define PI 3.1415926535
mmm, Pi.
Definition at line 9 of file prop-loss.h.
#define PI_SQ 9.8696043785
Definition at line 10 of file prop-loss.h.
Function Documentation
double calcRxPower (double txPowerDbm, double distance, double lambda)
The Friis propagation loss model was first described in "A Note on a Simple Transmission Formula", by "Harald T. Friis".
The original equation was described as: with the following equation for the case of an isotropic antenna with no heat loss:
The final equation becomes:
Modern extensions to this original equation are:
Here, we ignore tx and rx gain and the input and output values are in dB or dBm:
With:
: reception power (W)
: transmission power (W)
: transmission gain (unit-less)
: reception gain (unit-less)
: wavelength (m)
: distance (m)
: system loss (unit-less)
This model is invalid for small distance values. The current implementation returns the txpower as the rxpower for any distance smaller than MinDistance.
MinDistance is defined as follows: (Paul, Whites, Nasir, Intro. to Electromagnetic Fields) Picking a typical value of 16 for k, and assuming a 1/4 wavelength antenna MinDistance becomes:
Definition at line 9 of file prop-loss.c.
References distance, and PI_SQ.
Referenced by main(), olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().
double calculateSnr (rf_signal rf)
< thermal noise at 290K in J/s = W
< thermal noise at 290K in J/s = W
< thermal noise at 290K in J/s = W
Definition at line 37 of file prop-loss.c.
References rf_signal::bandwidth, BOLTZMANN, rf_signal::noiseFigure, rf_signal::noiseInterference, and rf_signal::signal.
Referenced by olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().
double dbmFromW (double w)
Definition at line 23 of file prop-loss.c.
double wFromDbm (double dbm)
Definition at line 28 of file prop-loss.c.