ROSS: ross/models/qhold/qhold_main.c File Reference
qhold_main.c File Reference
#include <ross.h>
#include "qhold.h"
Macros
#define qhold_main main
Functions
int main (int argc, char *argv[])
Variables
const tw_optdef qhold_opts []
Macro Definition Documentation
#define qhold_main main
Definition at line 18 of file qhold_main.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 20 of file qhold_main.c.
References g_tw_events_per_pe, g_tw_nlp, g_tw_synchronization_protocol, globalEvents, globalEventsR, globalEventsScheduled, globalEventsScheduledR, globalHash, globalHashR, globalTies, globalTiesR, globalZeroDelays, globalZeroDelaysR, nlp_per_pe, nLPs, optimistic_memory, percent_remote, population, qhold_lps, remoteFractDenominator, remoteFractNumerator, remoteThreshold, SEQUENTIAL, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_lp_settype(), tw_opt_add(), and tw_run().
Variable Documentation
const tw_optdef qhold_opts[]
Initial value:
= {
        TWOPT_GROUP("ROSS Model"),
    TWOPT_UINT("nlp_per_pe", nlp_per_pe, "Number of LPs per PE"),
    TWOPT_UINT("population", population, "number of initial messages per LP"),
    TWOPT_STIME("lookahead", g_tw_lookahead, "Lookahead for qhold"),
    TWOPT_ULONG("RSV", randomSeedVariation, "Random seed variation"),
    TWOPT_STIME("remote", percent_remote, "desired remote event rate"),
    TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_END(),
}
Definition at line 5 of file qhold_main.c.