ROSS: ross/models/qhold/qhold_driver.c File Reference
qhold_driver.c File Reference
#include "qhold.h"
Functions
void qhold_init (q_state *s, tw_lp *lp)
void qhold_event (q_state *s, tw_bf *bf, q_message *msg, tw_lp *lp)
void qhold_event_reverse (q_state *s, tw_bf *bf, q_message *msg, tw_lp *lp)
void qhold_final (q_state *s, tw_lp *lp)
tw_peid qhold_map (tw_lpid gid)
Variables
unsigned nlp_per_pe = 16
unsigned long int nLPs
unsigned population = 16
unsigned long int remoteThreshold
unsigned long int randomSeedVariation
unsigned long int globalHash = 0
unsigned long int globalEvents = 0
unsigned long int globalEventsScheduled = 0
unsigned long int globalTies = 0
unsigned long int globalZeroDelays = 0
unsigned long int globalHashR = 0
unsigned long int globalEventsR = 0
unsigned long int globalEventsScheduledR = 0
unsigned long int globalTiesR = 0
unsigned long int globalZeroDelaysR = 0
double percent_remote = 0.1
unsigned optimistic_memory = 1024
unsigned int remoteFractNumerator = 1
unsigned int remoteFractDenominator = 1
tw_lptype qhold_lps []
Function Documentation
void qhold_event (q_state * s, tw_bf * bf, q_message * msg, tw_lp * lp)
Definition at line 85 of file qhold_driver.c.
References tw_bf::c0, tw_bf::c1, tw_bf::c2, g_tw_lookahead, tw_lp::gid, globalEvents, globalEventsScheduled, globalHash, globalTies, globalZeroDelays, q_message::lastvtime, q_state::lastvtime, q_message::msgValue, nLPs, q_message::oldStateValue, q_message::RC, remoteThreshold, tw_lp::rng, q_message::rngLoopCount, q_state::stateValue, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and tw_rand_ulong().
void qhold_event_reverse (q_state * s, tw_bf * bf, q_message * msg, tw_lp * lp)
Definition at line 162 of file qhold_driver.c.
References tw_bf::c0, tw_bf::c1, tw_bf::c2, globalEvents, globalEventsScheduled, globalHash, globalTies, globalZeroDelays, q_message::lastvtime, q_state::lastvtime, q_message::oldStateValue, q_message::RC, tw_lp::rng, q_message::rngLoopCount, q_state::stateValue, and tw_rand_reverse_unif.
void qhold_final (q_state * s, tw_lp * lp)
Definition at line 202 of file qhold_driver.c.
void qhold_init (q_state * s, tw_lp * lp)
Definition at line 33 of file qhold_driver.c.
References g_tw_lookahead, tw_lp::gid, globalEventsScheduled, globalHash, q_state::lastvtime, q_message::msgValue, nlp_per_pe, nLPs, population, tw_lp::rng, q_state::stateValue, tw_event_data(), tw_event_new(), tw_event_send(), tw_nnodes(), and tw_rand_ulong().
tw_peid qhold_map (tw_lpid gid)
Definition at line 207 of file qhold_driver.c.
References g_tw_nlp.
Variable Documentation
unsigned long int globalEvents = 0
Definition at line 10 of file qhold_driver.c.
unsigned long int globalEventsR = 0
Definition at line 17 of file qhold_driver.c.
unsigned long int globalEventsScheduled = 0
Definition at line 11 of file qhold_driver.c.
unsigned long int globalEventsScheduledR = 0
Definition at line 18 of file qhold_driver.c.
unsigned long int globalHash = 0
Definition at line 9 of file qhold_driver.c.
unsigned long int globalHashR = 0
Definition at line 16 of file qhold_driver.c.
unsigned long int globalTies = 0
Definition at line 12 of file qhold_driver.c.
unsigned long int globalTiesR = 0
Definition at line 19 of file qhold_driver.c.
unsigned long int globalZeroDelays = 0
Definition at line 13 of file qhold_driver.c.
unsigned long int globalZeroDelaysR = 0
Definition at line 20 of file qhold_driver.c.
unsigned nlp_per_pe = 16
Definition at line 3 of file qhold_driver.c.
unsigned long int nLPs
Definition at line 4 of file qhold_driver.c.
unsigned optimistic_memory = 1024
Definition at line 23 of file qhold_driver.c.
double percent_remote = 0.1
Definition at line 22 of file qhold_driver.c.
unsigned population = 16
Definition at line 5 of file qhold_driver.c.
tw_lptype qhold_lps[]
Initial value:
= {
    {
        (init_f) qhold_init,
        (event_f) qhold_event,
        (revent_f) qhold_event_reverse,
        (final_f) qhold_final,
        (map_f) qhold_map,
        sizeof(q_state)
    },
    { 0 },
}
Definition at line 214 of file qhold_driver.c.
unsigned long int randomSeedVariation
Definition at line 7 of file qhold_driver.c.
unsigned int remoteFractDenominator = 1
Definition at line 28 of file qhold_driver.c.
unsigned int remoteFractNumerator = 1
Definition at line 27 of file qhold_driver.c.
unsigned long int remoteThreshold
Definition at line 6 of file qhold_driver.c.