ROSS: ross/queue-splay.c File Reference
queue-splay.c File Reference
#include <ross.h>
Data Structures
struct tw_pq
Macros
#define UP(t) ((t)->up)
#define UPUP(t) ((t)->up->up)
#define LEFT(t) ((t)->next)
#define RIGHT(t) ((t)->prev)
#define KEY(t) ((t)->recv_ts)
#define ROTATE_R(n, p, g)
#define ROTATE_L(n, p, g)
Typedefs
typedef tw_pq splay_tree
Functions
tw_pq * tw_pq_create (void)
static void splay (tw_event *node)
void tw_pq_enqueue (splay_tree *st, tw_event *e)
tw_event * tw_pq_dequeue (splay_tree *st)
void tw_pq_delete_any (splay_tree *st, tw_event *r)
double tw_pq_minimum (splay_tree *pq)
unsigned int tw_pq_get_size (splay_tree *st)
unsigned int tw_pq_max_size (splay_tree *pq)
Macro Definition Documentation
#define KEY (t) ((t)->recv_ts)
Definition at line 34 of file queue-splay.c.
Referenced by tw_pq_enqueue().
#define LEFT (t) ((t)->next)
Definition at line 32 of file queue-splay.c.
Referenced by splay(), tw_pq_delete_any(), tw_pq_dequeue(), and tw_pq_enqueue().
#define RIGHT (t) ((t)->prev)
Definition at line 33 of file queue-splay.c.
Referenced by splay(), tw_pq_delete_any(), tw_pq_dequeue(), and tw_pq_enqueue().
#define ROTATE_L (n, p, g)
Value:
if((RIGHT(p) = LEFT(n))) UP(LEFT(n)) = p;  LEFT(n) = p; \
  UP(n) = g;  UP(p) = n;
Definition at line 49 of file queue-splay.c.
Referenced by splay().
#define ROTATE_R (n, p, g)
Value:
if((LEFT(p) = RIGHT(n))) UP(RIGHT(n)) = p;  RIGHT(n) = p; \
  UP(n) = g;  UP(p) = n;
Definition at line 45 of file queue-splay.c.
Referenced by splay().
#define UP (t) ((t)->up)
Definition at line 30 of file queue-splay.c.
Referenced by splay(), tw_pq_delete_any(), tw_pq_dequeue(), and tw_pq_enqueue().
#define UPUP (t) ((t)->up->up)
Definition at line 31 of file queue-splay.c.
Referenced by splay().
Typedef Documentation
typedef tw_pq splay_tree
Definition at line 43 of file queue-splay.c.
Function Documentation
static void splay (tw_event * node) static
Definition at line 70 of file queue-splay.c.
References LEFT, p, RIGHT, ROTATE_L, ROTATE_R, UP, UPUP, and x.
Referenced by tw_pq_delete_any(), and tw_pq_enqueue().
tw_pq* tw_pq_create (void)
Definition at line 54 of file queue-splay.c.
References g_tw_events_per_pe, tw_pq::least, LocalInit(), MAX_EVENTS_PER_PE, tw_pq::nitems, tw_pq::OrigBucket, tw_pq::ResizeEnabled, tw_pq::root, tw_calloc(), and TW_LOC.
void tw_pq_delete_any (splay_tree * st, tw_event * r)
Definition at line 260 of file queue-splay.c.
References tw_pq::least, LEFT, tw_event::next, tw_pq::nitems, tw_event::owner, p, tw_event::prev, tw_pq::Qsize, RIGHT, tw_pq::root, splay(), tw_event::state, tw_error(), TW_LOC, tw_pq_dequeue(), and UP.
tw_event* tw_pq_dequeue (splay_tree * st)
Definition at line 217 of file queue-splay.c.
References tw_pq::BottomThreshold, tw_pq::Bucket, tw_pq::BucketTop, Delete(), tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::least, LEFT, tw_pq::Nbuckets, tw_event_head::next, tw_pq::nitems, tw_event::owner, p, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, RIGHT, tw_pq::root, tw_event::state, tw_error(), TW_LOC, UP, and tw_pq::Width.
void tw_pq_enqueue (splay_tree * st, tw_event * e)
Definition at line 168 of file queue-splay.c.
References tw_pq::BucketTop, Insert(), KEY, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::least, LEFT, tw_pq::max_size, tw_pq::Nbuckets, tw_pq::nitems, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, RIGHT, tw_pq::root, splay(), tw_event::state, tw_pq::TopThreshold, TW_pe_pq, UP, and tw_pq::Width.
unsigned int tw_pq_get_size (splay_tree * st)
Definition at line 323 of file queue-splay.c.
References tw_pq::nitems, and tw_pq::Qsize.
unsigned int tw_pq_max_size (splay_tree * pq)
Definition at line 329 of file queue-splay.c.
References tw_pq::max_size.
Referenced by gvt_print().
double tw_pq_minimum (splay_tree * pq)
Definition at line 317 of file queue-splay.c.
References tw_pq::Bucket, tw_pq::BucketTop, tw_pq::LastBucket, tw_pq::least, tw_pq::Nbuckets, tw_event_head::next, tw_pq::Qsize, tw_event::recv_ts, tw_error(), TW_LOC, and tw_pq::Width.