ROSS: ross/models/raid/raid-controller.c File Reference
raid-controller.c File Reference
#include "raid.h"
Functions
void raid_controller_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_lpid raid_controller_find_server (tw_lp *lp)
void raid_controller_init (ContState *s, tw_lp *lp)
void raid_controller_eventhandler (ContState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_controller_eventhandler_rc (ContState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_controller_finish (ContState *s, tw_lp *lp)
Function Documentation
void raid_controller_eventhandler (ContState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 35 of file raid-controller.c.
References _controller_state::condition, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, FAILED, tw_lp::gid, HEALTHY, _controller_state::m_server, message_error(), _controller_state::num_rebuilds, raid_controller_gen_send(), RAID_FAILURE, _message_data::rc, REBUILD, REBUILD_FINISH, REBUILD_START, REBUILD_TIME, tw_lp::rng, STD_DEV, tw_rand_normal_sd(), and WAIT.
void raid_controller_eventhandler_rc (ContState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 88 of file raid-controller.c.
References _controller_state::condition, DISK_REPLACED, _message_data::event_type, FAILED, _controller_state::num_rebuilds, _message_data::rc, tw_lp::rng, and tw_rand_reverse_unif.
tw_lpid raid_controller_find_server (tw_lp * lp)
Definition at line 20 of file raid-controller.c.
References FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_controller_init().
void raid_controller_finish (ContState * s, tw_lp * lp)
Definition at line 101 of file raid-controller.c.
References _controller_state::condition, FAILED, g_stats, and _controller_state::num_rebuilds.
void raid_controller_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-controller.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-controller.c.
References _message_data::event_type, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_controller_eventhandler().
void raid_controller_init (ContState * s, tw_lp * lp)
Definition at line 26 of file raid-controller.c.
References _controller_state::condition, HEALTHY, _controller_state::m_server, _controller_state::num_rebuilds, and raid_controller_find_server().