ROSS: ross/models/raid/raid-disk.c File Reference
raid-disk.c File Reference
#include "raid.h"
Functions
void raid_disk_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_stime raid_disk_fail_time (tw_lp *lp)
tw_lpid raid_disk_find_controller (tw_lp *lp)
void raid_disk_init (DiskState *s, tw_lp *lp)
void raid_disk_eventhandler (DiskState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_disk_eventhandler_rc (DiskState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_disk_finish (DiskState *s, tw_lp *lp)
Function Documentation
void raid_disk_eventhandler (DiskState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 83 of file raid-disk.c.
References tw_bf::c0, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, tw_lp::gid, _disk_state::m_controller, MAX_HOURS, message_error(), _disk_state::num_failures, raid_disk_fail_time(), raid_disk_gen_send(), _message_data::rc, REPLACE_TIME, tw_lp::rng, STD_DEV, tw_now(), and tw_rand_normal_sd().
Referenced by raid_disk_init().
void raid_disk_eventhandler_rc (DiskState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 116 of file raid-disk.c.
References tw_bf::c0, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, message_error(), _disk_state::num_failures, _message_data::rc, tw_lp::rng, and tw_rand_reverse_unif.
tw_stime raid_disk_fail_time (tw_lp * lp)
Definition at line 20 of file raid-disk.c.
References g_disk_distro, MTTF, tw_lp::rng, tw_rand_exponential(), tw_rand_integer(), and tw_rand_weibull().
Referenced by raid_disk_eventhandler().
tw_lpid raid_disk_find_controller (tw_lp * lp)
Definition at line 62 of file raid-disk.c.
References CONT_PER_FS, DISK_PER_RC, FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_disk_init().
void raid_disk_finish (DiskState * s, tw_lp * lp)
Definition at line 137 of file raid-disk.c.
References g_stats, and _disk_state::num_failures.
void raid_disk_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-disk.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-disk.c.
References _message_data::event_type, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_disk_eventhandler().
void raid_disk_init (DiskState * s, tw_lp * lp)
Definition at line 69 of file raid-disk.c.
References DISK_REPLACED, _message_data::event_type, _disk_state::m_controller, _disk_state::num_failures, raid_disk_eventhandler(), and raid_disk_find_controller().