ROSS: ross/models/raid/raid.c File Reference
raid.c File Reference
#include "raid.h"
Functions
void message_error (Event event_type)
tw_peid raid_mapping (tw_lpid gid)
int main (int argc, char **argv)
Variables
tw_lptype mylps []
const tw_optdef app_opts []
Function Documentation
int main (int argc, char ** argv)
Definition at line 72 of file raid.c.
References CONT_PER_FS, DISK_PER_RC, FS_PER_IO, g_add_mem, g_nfs_per_pe, g_nlp_per_pe, g_raid_start_events, g_stats, g_ttl_fs, g_tw_events_per_pe, g_tw_masternode, g_tw_memory_nqueues, g_tw_npe, LPS_PER_FS, _aggregate_stats::ttl_blocks_wr, _aggregate_stats::ttl_busy_time, _aggregate_stats::ttl_controller_failures, _aggregate_stats::ttl_controller_rebuilds, _aggregate_stats::ttl_disk_failures, _aggregate_stats::ttl_idle_time, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
void message_error (Event event_type)
RAID File Server Farm Simulation
FILE: raid.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid.c.
Referenced by raid_controller_eventhandler(), raid_disk_eventhandler(), raid_disk_eventhandler_rc(), raid_io_eventhandler(), raid_io_eventhandler_rc(), raid_server_eventhandler(), and raid_server_eventhandler_rc().
tw_peid raid_mapping (tw_lpid gid)
Definition at line 17 of file raid.c.
References g_tw_nlp.
Variable Documentation
const tw_optdef app_opts[]
Initial value:
=
{
    TWOPT_GROUP( "RAIDSIM Model" ),
    TWOPT_UINT( "disk-distro", g_disk_distro, "Failure probability distribution" ),
    TWOPT_UINT( "nfs", g_ttl_fs, "Number of file server clusters" ),
    TWOPT_UINT( "memory", g_add_mem, "Additional memory buffers" ),
}
Definition at line 63 of file raid.c.
tw_lptype mylps[]
Definition at line 22 of file raid.c.