ROSS: ross/models/raid/raid-server.c File Reference
raid-server.c File Reference
#include "raid.h"
Functions
void raid_server_calculate_bandwidth (ServerState *s)
long raid_server_num_blocks (ServerState *s, tw_lp *lp)
void raid_server_init (ServerState *s, tw_lp *lp)
void raid_server_eventhandler (ServerState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_server_eventhandler_rc (ServerState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_server_finish (ServerState *s, tw_lp *lp)
Function Documentation
void raid_server_calculate_bandwidth (ServerState * s)
RAID File Server Farm Simulation
FILE: raid-server.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-server.c.
References _server_state::bandwidth, CONT_FS_BW, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, and THROTTLE.
Referenced by raid_server_eventhandler(), and raid_server_eventhandler_rc().
void raid_server_eventhandler (ServerState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 37 of file raid-server.c.
References BUSY, DISK_FAILURE, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, RAID_FAILURE, raid_server_calculate_bandwidth(), raid_server_num_blocks(), _message_data::rc, REBUILD_FINISH, REBUILD_START, and tw_now().
void raid_server_eventhandler_rc (ServerState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 80 of file raid-server.c.
References BUSY, DISK_FAILURE, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, RAID_FAILURE, raid_server_calculate_bandwidth(), _message_data::rc, REBUILD_FINISH, REBUILD_START, tw_lp::rng, and tw_rand_reverse_unif.
void raid_server_finish (ServerState * s, tw_lp * lp)
Definition at line 124 of file raid-server.c.
References g_stats, and _server_state::num_blocks_wr.
void raid_server_init (ServerState * s, tw_lp * lp)
Definition at line 25 of file raid-server.c.
References CONT_PER_FS, IDLE, _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, and tw_now().
long raid_server_num_blocks (ServerState * s, tw_lp * lp)
Definition at line 17 of file raid-server.c.
References _server_state::bandwidth, BLOCK_SIZE, _server_state::mode_change_timestamp, and tw_now().
Referenced by raid_server_eventhandler().