ROSS: ross/models/raid/raid-io.c File Reference
raid-io.c File Reference
#include "raid.h"
Functions
void raid_io_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_lpid raid_io_find_server (tw_lp *lp)
void raid_io_init (IOState *s, tw_lp *lp)
void raid_io_eventhandler (IOState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_io_eventhandler_rc (IOState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_io_finish (IOState *s, tw_lp *lp)
Function Documentation
void raid_io_eventhandler (IOState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 41 of file raid-io.c.
References BUSY, BUSY_TIME, _message_data::event_type, tw_lp::gid, IDLE, IDLE_TIME, IO_BUSY, IO_IDLE, _io_state::m_server, message_error(), _io_state::mode, raid_io_gen_send(), _message_data::rc, tw_lp::rng, STD_DEV, _io_state::ttl_busy, _io_state::ttl_idle, and tw_rand_normal_sd().
Referenced by raid_io_init().
void raid_io_eventhandler_rc (IOState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 76 of file raid-io.c.
References BUSY, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _io_state::mode, _message_data::rc, tw_lp::rng, _io_state::ttl_busy, _io_state::ttl_idle, and tw_rand_reverse_unif.
tw_lpid raid_io_find_server (tw_lp * lp)
Definition at line 21 of file raid-io.c.
References FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_io_init().
void raid_io_finish (IOState * s, tw_lp * lp)
Definition at line 99 of file raid-io.c.
References g_stats, _io_state::ttl_busy, and _io_state::ttl_idle.
void raid_io_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-io.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-io.c.
References _message_data::event_type, _message_data::rc, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_io_eventhandler().
void raid_io_init (IOState * s, tw_lp * lp)
Definition at line 27 of file raid-io.c.
References _message_data::event_type, IO_IDLE, _io_state::m_server, raid_io_eventhandler(), raid_io_find_server(), _io_state::ttl_busy, and _io_state::ttl_idle.