ROSS: ross/models/raid/raid-extern.h File Reference
raid-extern.h File Reference
#include "raid.h"
Functions
void message_error (Event event_type)
void raid_server_calculate_bandwidth (ServerState *s)
long raid_server_num_blocks (ServerState *s, tw_lp *lp)
void raid_server_init (ServerState *s, tw_lp *lp)
void raid_server_eventhandler (ServerState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_server_eventhandler_rc (ServerState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_server_finish (ServerState *s, tw_lp *lp)
void raid_controller_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_lpid raid_controller_find_server (tw_lp *lp)
void raid_controller_init (ContState *s, tw_lp *lp)
void raid_controller_eventhandler (ContState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_controller_eventhandler_rc (ContState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_controller_finish (ContState *s, tw_lp *lp)
void raid_disk_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_stime raid_disk_fail_time (tw_lp *lp)
tw_lpid raid_disk_find_controller (tw_lp *lp)
void raid_disk_init (DiskState *s, tw_lp *lp)
void raid_disk_eventhandler (DiskState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_disk_eventhandler_rc (DiskState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_disk_finish (DiskState *s, tw_lp *lp)
void raid_io_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp *lp)
tw_lpid raid_io_find_server (tw_lp *lp)
void raid_io_init (IOState *s, tw_lp *lp)
void raid_io_eventhandler (IOState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_io_eventhandler_rc (IOState *s, tw_bf *cv, MsgData *m, tw_lp *lp)
void raid_io_finish (IOState *s, tw_lp *lp)
Variables
int g_disk_distro
int g_ttl_fs
int g_nfs_per_pe
tw_lpid g_nlp_per_pe
int g_raid_start_events
int g_add_mem
Stats g_stats
Function Documentation
void message_error (Event event_type)
RAID File Server Farm Simulation
FILE: raid-extern.h AUTHOR: Matt Perry DATE: Apr 27 2011
RAID File Server Farm Simulation
FILE: raid.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid.c.
Referenced by raid_controller_eventhandler(), raid_disk_eventhandler(), raid_disk_eventhandler_rc(), raid_io_eventhandler(), raid_io_eventhandler_rc(), raid_server_eventhandler(), and raid_server_eventhandler_rc().
void raid_controller_eventhandler (ContState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 35 of file raid-controller.c.
References _controller_state::condition, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, FAILED, tw_lp::gid, HEALTHY, _controller_state::m_server, message_error(), _controller_state::num_rebuilds, raid_controller_gen_send(), RAID_FAILURE, _message_data::rc, REBUILD, REBUILD_FINISH, REBUILD_START, REBUILD_TIME, tw_lp::rng, STD_DEV, tw_rand_normal_sd(), and WAIT.
void raid_controller_eventhandler_rc (ContState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 88 of file raid-controller.c.
References _controller_state::condition, DISK_REPLACED, _message_data::event_type, FAILED, _controller_state::num_rebuilds, _message_data::rc, tw_lp::rng, and tw_rand_reverse_unif.
tw_lpid raid_controller_find_server (tw_lp * lp)
Definition at line 20 of file raid-controller.c.
References FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_controller_init().
void raid_controller_finish (ContState * s, tw_lp * lp)
Definition at line 101 of file raid-controller.c.
References _controller_state::condition, FAILED, g_stats, and _controller_state::num_rebuilds.
void raid_controller_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-controller.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-controller.c.
References _message_data::event_type, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_controller_eventhandler().
void raid_controller_init (ContState * s, tw_lp * lp)
Definition at line 26 of file raid-controller.c.
References _controller_state::condition, HEALTHY, _controller_state::m_server, _controller_state::num_rebuilds, and raid_controller_find_server().
void raid_disk_eventhandler (DiskState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 83 of file raid-disk.c.
References tw_bf::c0, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, tw_lp::gid, _disk_state::m_controller, MAX_HOURS, message_error(), _disk_state::num_failures, raid_disk_fail_time(), raid_disk_gen_send(), _message_data::rc, REPLACE_TIME, tw_lp::rng, STD_DEV, tw_now(), and tw_rand_normal_sd().
Referenced by raid_disk_init().
void raid_disk_eventhandler_rc (DiskState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 116 of file raid-disk.c.
References tw_bf::c0, DISK_FAILURE, DISK_REPLACED, _message_data::event_type, message_error(), _disk_state::num_failures, _message_data::rc, tw_lp::rng, and tw_rand_reverse_unif.
tw_stime raid_disk_fail_time (tw_lp * lp)
Definition at line 20 of file raid-disk.c.
References g_disk_distro, MTTF, tw_lp::rng, tw_rand_exponential(), tw_rand_integer(), and tw_rand_weibull().
Referenced by raid_disk_eventhandler().
tw_lpid raid_disk_find_controller (tw_lp * lp)
Definition at line 62 of file raid-disk.c.
References CONT_PER_FS, DISK_PER_RC, FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_disk_init().
void raid_disk_finish (DiskState * s, tw_lp * lp)
Definition at line 137 of file raid-disk.c.
References g_stats, and _disk_state::num_failures.
void raid_disk_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-disk.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-disk.c.
References _message_data::event_type, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_disk_eventhandler().
void raid_disk_init (DiskState * s, tw_lp * lp)
Definition at line 69 of file raid-disk.c.
References DISK_REPLACED, _message_data::event_type, _disk_state::m_controller, _disk_state::num_failures, raid_disk_eventhandler(), and raid_disk_find_controller().
void raid_io_eventhandler (IOState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 41 of file raid-io.c.
References BUSY, BUSY_TIME, _message_data::event_type, tw_lp::gid, IDLE, IDLE_TIME, IO_BUSY, IO_IDLE, _io_state::m_server, message_error(), _io_state::mode, raid_io_gen_send(), _message_data::rc, tw_lp::rng, STD_DEV, _io_state::ttl_busy, _io_state::ttl_idle, and tw_rand_normal_sd().
Referenced by raid_io_init().
void raid_io_eventhandler_rc (IOState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 76 of file raid-io.c.
References BUSY, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _io_state::mode, _message_data::rc, tw_lp::rng, _io_state::ttl_busy, _io_state::ttl_idle, and tw_rand_reverse_unif.
tw_lpid raid_io_find_server (tw_lp * lp)
Definition at line 21 of file raid-io.c.
References FS_PER_IO, tw_lp::gid, and LPS_PER_FS.
Referenced by raid_io_init().
void raid_io_finish (IOState * s, tw_lp * lp)
Definition at line 99 of file raid-io.c.
References g_stats, _io_state::ttl_busy, and _io_state::ttl_idle.
void raid_io_gen_send (tw_lpid dest, Event event_type, tw_stime event_time, tw_lp * lp)
RAID File Server Farm Simulation
FILE: raid-io.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-io.c.
References _message_data::event_type, _message_data::rc, tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by raid_io_eventhandler().
void raid_io_init (IOState * s, tw_lp * lp)
Definition at line 27 of file raid-io.c.
References _message_data::event_type, IO_IDLE, _io_state::m_server, raid_io_eventhandler(), raid_io_find_server(), _io_state::ttl_busy, and _io_state::ttl_idle.
void raid_server_calculate_bandwidth (ServerState * s)
RAID File Server Farm Simulation
FILE: raid-server.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 11 of file raid-server.c.
References _server_state::bandwidth, CONT_FS_BW, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, and THROTTLE.
Referenced by raid_server_eventhandler(), and raid_server_eventhandler_rc().
void raid_server_eventhandler (ServerState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 37 of file raid-server.c.
References BUSY, DISK_FAILURE, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, RAID_FAILURE, raid_server_calculate_bandwidth(), raid_server_num_blocks(), _message_data::rc, REBUILD_FINISH, REBUILD_START, and tw_now().
void raid_server_eventhandler_rc (ServerState * s, tw_bf * cv, MsgData * m, tw_lp * lp)
Definition at line 80 of file raid-server.c.
References BUSY, DISK_FAILURE, _message_data::event_type, IDLE, IO_BUSY, IO_IDLE, message_error(), _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, RAID_FAILURE, raid_server_calculate_bandwidth(), _message_data::rc, REBUILD_FINISH, REBUILD_START, tw_lp::rng, and tw_rand_reverse_unif.
void raid_server_finish (ServerState * s, tw_lp * lp)
Definition at line 124 of file raid-server.c.
References g_stats, and _server_state::num_blocks_wr.
void raid_server_init (ServerState * s, tw_lp * lp)
Definition at line 25 of file raid-server.c.
References CONT_PER_FS, IDLE, _server_state::mode, _server_state::mode_change_timestamp, _server_state::num_blocks_wr, _server_state::num_controllers_failure, _server_state::num_controllers_good_health, _server_state::num_controllers_rebuilding, and tw_now().
long raid_server_num_blocks (ServerState * s, tw_lp * lp)
Definition at line 17 of file raid-server.c.
References _server_state::bandwidth, BLOCK_SIZE, _server_state::mode_change_timestamp, and tw_now().
Referenced by raid_server_eventhandler().
Variable Documentation
int g_add_mem
Definition at line 15 of file raid-globals.c.
Referenced by main().
int g_disk_distro
RAID File Server Farm Simulation
FILE: raid-globals.c AUTHOR: Matt Perry DATE: Apr 27 2011
Definition at line 10 of file raid-globals.c.
Referenced by raid_disk_fail_time().
int g_nfs_per_pe
Definition at line 12 of file raid-globals.c.
Referenced by main().
tw_lpid g_nlp_per_pe
Definition at line 13 of file raid-globals.c.
Referenced by main().
int g_raid_start_events
Definition at line 14 of file raid-globals.c.
Referenced by main().
Stats g_stats
Definition at line 16 of file raid-globals.c.
int g_ttl_fs
Definition at line 11 of file raid-globals.c.
Referenced by main().