ROSS: rnf/tools/parsers/rf_to_ross.c File Reference
rf_to_ross.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <stdarg.h>
Data Structures
struct rocket_fuel_link
struct rocket_fuel_node
Macros
#define MAX_NODES 32000
#define MAX_LINKS_PER_NODE 128
#define MAX_LINE_WIDTH 2048
#define MAX_BUFFER_SIZE 80
#define MAX_LEVELS 16
#define MAX_KPS 256
#define MAX_PES 4
Functions
void init ()
void print_node_list ()
int read_rocketfuel_file (char *filename)
void parse_rocketfuel_line (char *buffer)
char * get_rocketfuel_item (char *item, char *buffer)
void color_topology (int levels)
void map_nodes_to_ross ()
int main (int argc, char *argv[])
Variables
int bandwith_classes [16]
struct rocket_fuel_node g_node_list [32000]
unsigned long g_node_count = 0
FILE * g_rocketfuel_file = NULL
unsigned long g_max_links = 0
int g_level_count [16]
int g_kp_count [256]
Macro Definition Documentation
#define MAX_BUFFER_SIZE 80
Definition at line 19 of file rf_to_ross.c.
#define MAX_KPS 256
Definition at line 23 of file rf_to_ross.c.
Referenced by map_nodes_to_ross().
#define MAX_LEVELS 16
Definition at line 21 of file rf_to_ross.c.
Referenced by main().
#define MAX_LINE_WIDTH 2048
Definition at line 18 of file rf_to_ross.c.
Referenced by read_rocketfuel_file().
#define MAX_LINKS_PER_NODE 128
Definition at line 16 of file rf_to_ross.c.
#define MAX_NODES 32000
Definition at line 15 of file rf_to_ross.c.
Referenced by init(), and read_rocketfuel_file().
#define MAX_PES 4
Definition at line 24 of file rf_to_ross.c.
Referenced by map_nodes_to_ross().
Function Documentation
void color_topology (int levels)
Definition at line 107 of file convert.c.
char* get_rocketfuel_item (char * item, char * buffer)
void init ()
Definition at line 82 of file rf_to_ross.c.
References g_node_list, rocket_fuel_node::is_bb, rocket_fuel_node::kp, rocket_fuel_node::level, MAX_NODES, rocket_fuel_node::num_in_level, rocket_fuel_node::num_links, rocket_fuel_node::pe, and rocket_fuel_node::used.
Referenced by main(), and tcp_layer_xml().
int main (int argc, char * argv[])
Definition at line 461 of file rf_to_ross.c.
References color_topology(), init(), map_nodes_to_ross(), MAX_LEVELS, number_of_nodes, print_node_list(), and read_rocketfuel_file().
void map_nodes_to_ross ()
Definition at line 391 of file rf_to_ross.c.
References g_kp_count, g_level_count, g_node_count, g_node_list, rocket_fuel_node::kp, rocket_fuel_node::level, MAX_KPS, MAX_PES, rocket_fuel_node::num_in_level, rocket_fuel_node::num_links, and rocket_fuel_node::pe.
Referenced by main().
void parse_rocketfuel_line (char * buffer)
void print_node_list ()
int read_rocketfuel_file (char * filename)
Definition at line 125 of file rf_to_ross.c.
Variable Documentation
int bandwith_classes[16]
Initial value:
=
        { 9920, 2480, 620, 155, 45, 45, 45, 45 }
Definition at line 49 of file rf_to_ross.c.
int g_kp_count[256]
Definition at line 73 of file rf_to_ross.c.
Referenced by map_nodes_to_ross().
int g_level_count[16]
Definition at line 72 of file rf_to_ross.c.
unsigned long g_max_links = 0
Definition at line 71 of file rf_to_ross.c.
unsigned long g_node_count = 0
Definition at line 69 of file rf_to_ross.c.
struct rocket_fuel_node g_node_list[32000]
Definition at line 68 of file rf_to_ross.c.
FILE* g_rocketfuel_file = NULL
Definition at line 70 of file rf_to_ross.c.