ROSS: rnf/kernel/rn-event.c File Reference
rn-event.c File Reference
#include <rossnet.h>
Functions
tw_event * rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp *src)
tw_event * rn_event_new (tw_lpid dst, tw_stime ts, tw_lp *src, rn_message_type dir, unsigned long int size)
void rn_event_send (tw_event *new_event)
Function Documentation
tw_event* rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp * src)
Definition at line 8 of file rn-event.c.
References rn_stream::cur_layer, rn_lp_state::cur_lp, tw_lp::cur_state, DIRECT, rn_message::dst, tw_lp::gid, rn_message::port, rn_stream::port, rn_getstream(), s, rn_message::size, rn_message::src, rn_message::timer, tw_event_data(), tw_event_new(), and rn_message::type.
Referenced by epi_agent_remove(), epi_num_add(), epi_num_check_report(), epi_num_remove(), rp_init(), rp_move(), rw_init(), and rw_move().
tw_event* rn_event_new (tw_lpid dst, tw_stime ts, tw_lp * src, rn_message_type dir, unsigned long int size)
inter-lp: events which will be sent to a remote lp
    inter-lp events are handled as usual
intra-lp: events which are sent to another layer on the same lp
 intra-lp events are immediately scheduled and processed, because their
    destination is the local machine, and have a zero timestamp offset, which
 means the following:
 the next layer is responsible for handling packet data, ie, from TCP
 to IP.  The IP layer must re-create the TCP packect on the dest
    LP.
abort events: should not let them traverse layers.. first layer to get abort is then the only one to get rolled back
NOTE: We should probably base the timestamp off of the network characteristics, rather than make the model do it. When the model calls this function, and is the last layer, we should know the proper link to use, and can inform the model if this event will fail if sent, over the network.
Definition at line 60 of file rn-event.c.
References tw_pe::abort_event, rn_lp_state::cev, tw_pe::cev_abort, tw_pe::cur_event, rn_stream::cur_layer, tw_lp::cur_state, tw_event::dest_lp, DOWNSTREAM, rn_message::dst, g_rn_ttl, g_tw_ts_end, tw_lp::gid, tw_lp::pe, rn_message::port, rn_stream::port, tw_event::recv_ts, rn_getmachine(), rn_getstream(), s, rn_message::size, rn_message::src, rn_message::timer, rn_message::ttl, tw_event_data(), tw_event_new(), rn_message::type, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), forward(), ftp_event_handler(), ftp_init(), ip_packet_drop(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_new(), phold_event_handler(), phold_init(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().
void rn_event_send (tw_event * new_event)
Definition at line 146 of file rn-event.c.
References rn_lp_state::cev, tw_pe::cev_abort, tw_pe::cur_event, rn_stream::cur_layer, rn_lp_state::cur_lp, tw_lp::cur_state, tw_event::cv, tw_event::dest_lp, DIRECT, DOWNSTREAM, tw_lptype::event, g_tw_mynode, tw_lp::gid, rn_lp_state::l_stats, rn_stream::layers, rn_layer::lp, tw_event::next, rn_stream::nlayers, tw_lp::pe, rn_message::port, tw_event::recv_ts, rn_getstream(), rn_getstream_byport(), tw_lp::rng, s, rn_statistics::s_nevents_processed, tw_event::src_lp, TIMER, tw_error(), tw_event_data(), tw_event_send(), TW_LOC, tw_now(), rn_message::type, tw_lp::type, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), epi_agent_remove(), epi_num_add(), epi_num_check_report(), epi_num_remove(), ftp_event_handler(), ftp_init(), ip_downstream_forward(), ip_downstream_source(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_send(), phold_event_handler(), phold_init(), rp_init(), rw_init(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().