ROSS: rnf/kernel/rn-init.c File Reference
rn-init.c File Reference
#include <rossnet.h>
#include <rn_config.h>
Functions
void init_stream (rn_lp_state *state, rn_stream *stream, int i, tw_lp *lp)
void rn_init_streams (rn_lp_state *state, tw_lp *lp)
void rn_init_environment ()
Function Documentation
void init_stream (rn_lp_state * state, rn_stream * stream, int i, tw_lp * lp)
Definition at line 5 of file rn-init.c.
References rn_stream::cur_layer, rn_lp_state::cur_lp, tw_lp::cur_state, rn_lp_state::cur_stream, tw_lp::gid, tw_lptype::init, rn_stream::layers, rn_layer::lp, rn_stream::nlayers, rn_stream::port, tw_lp::rng, tw_error(), TW_LOC, and tw_lp::type.
Referenced by rn_init_streams().
void rn_init_environment (void)
Definition at line 67 of file rn-init.c.
References g_rn_environment, g_rn_lptypes, rn_lptype::sname, xml_getprop(), and rn_lptype::xml_init.
Referenced by main().
void rn_init_streams (rn_lp_state * state, tw_lp * lp)
This function calls the INIT routines of the star model layers
Definition at line 46 of file rn-init.c.
References tw_lp::gid, init_stream(), rn_lp_state::mobility, rn_lp_state::nmobility, rn_lp_state::nstreams, and rn_lp_state::streams.
Referenced by rn_startup().