ROSS: rnf/kernel/rn-reverse.c File Reference
rn-reverse.c File Reference
#include <rossnet.h>
Functions
void rn_reverse_event_send (tw_lpid dst, tw_lp *src, rn_message_type dir, unsigned long int size)
Function Documentation
void rn_reverse_event_send (tw_lpid dst, tw_lp * src, rn_message_type dir, unsigned long int size)
Definition at line 4 of file rn-reverse.c.
References tw_pe::cur_event, rn_stream::cur_layer, rn_lp_state::cur_lp, tw_lp::cur_state, tw_event::cv, DIRECT, DOWNSTREAM, rn_message::dst, tw_lp::gid, rn_lp_state::l_stats, rn_stream::layers, rn_layer::lp, rn_stream::nlayers, tw_lp::pe, rn_message::port, tw_lptype::revent, rn_getstream(), s, rn_statistics::s_nevents_rollback, rn_message::size, rn_message::src, rn_message::ttl, tw_error(), tw_event_data(), TW_LOC, tw_printf(), rn_message::type, tw_lp::type, and UPSTREAM.
Referenced by ip_rc_downstream(), ip_rc_packet_drop(), ip_rc_upstream(), tcp_rc_process_ack(), tcp_rc_process_data(), and tcp_rc_timeout().