ROSS: rnf/kernel/rn-setup.c File Reference
rn-setup.c File Reference
#include <rossnet.h>
Macros
#define RN_VERIFY_SETUP 0
Functions
void rn_setup_layers (rn_lp_state *state, int cur_stream, rn_layer *layer, rn_lptype *types, xmlNodePtr x_layer, tw_lp *me)
void rn_setup_mobility (rn_lp_state *state, rn_lptype *types, tw_lp *lp)
void rn_setup_streams (rn_lp_state *state, rn_lptype *types, tw_lp *lp)
void rn_setup_links (rn_lp_state *state, tw_lp *lp)
void rn_setup ()
Macro Definition Documentation
#define RN_VERIFY_SETUP 0
Definition at line 3 of file rn-setup.c.
Function Documentation
void rn_setup ()
If the global variable g_rn_tools_dir is set, look for the xml topology, link topology, and routing table configuration in that directory. Should not interfere with NetDMF configuration regardless of the value of g_rn_tools_dir
Definition at line 286 of file rn-setup.c.
References g_rn_rt_table, g_rn_tools_dir, g_rn_xml_link_topology, g_rn_xml_topology, and tw_ismaster().
Referenced by main().
void rn_setup_layers (rn_lp_state * state, int cur_stream, rn_layer * layer, rn_lptype * types, xmlNodePtr x_layer, tw_lp * me)
Definition at line 6 of file rn-setup.c.
References rn_lp_state::cur_lp, tw_lp::cur_state, rn_lp_state::cur_stream, tw_lp::gid, tw_lp::id, rn_lptype::init, tw_lp::kp, rn_layer::lp, tw_lp::pe, rn_lp_gettype(), rn_lptype::sname, tw_lp::state_qh, tw_error(), TW_LOC, tw_state_alloc(), tw_lp::type, xml_getprop(), and rn_lptype::xml_init.
Referenced by rn_setup_mobility(), and rn_setup_streams().
void rn_setup_links (rn_lp_state * state, tw_lp * lp)
Definition at line 239 of file rn-setup.c.
References rn_message::dst, g_rn_nlink_status, tw_lp::gid, rn_machine::link, LINK_STATUS_DOWN, LINK_STATUS_UP, rn_machine::nlinks, rn_message::port, rn_getmachine(), rn_link_up, rn_message::src, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and rn_message::type.
Referenced by rn_startup().
void rn_setup_mobility (rn_lp_state * state, rn_lptype * types, tw_lp * lp)
Definition at line 81 of file rn-setup.c.
References tw_lp::gid, rn_stream::layers, rn_lp_state::mobility, rn_stream::nlayers, rn_lp_state::nmobility, rn_getmachine(), rn_setup_layers(), tw_calloc(), TW_LOC, and rn_machine::xml.
Referenced by rn_startup().
void rn_setup_streams (rn_lp_state * state, rn_lptype * types, tw_lp * lp)
This function sets up the star model for the different layers
Definition at line 151 of file rn-setup.c.
References tw_lp::gid, rn_stream::layers, rn_stream::nlayers, rn_lp_state::nstreams, rn_stream::port, rn_getmachine(), rn_setup_layers(), rn_lp_state::streams, tw_calloc(), tw_error(), TW_LOC, rn_machine::xml, and xml_getprop().
Referenced by rn_startup().