ROSS: rnf/kernel/rn-subnet.c File Reference
rn-subnet.c File Reference
#include <rossnet.h>
Functions
rn_subnet * rn_nextsn_onarea (rn_subnet *sn, rn_area *ar)
rn_machine * rn_nextmachine_onsn (rn_machine *m, rn_subnet *sn)
Function Documentation
rn_machine* rn_nextmachine_onsn (rn_machine * m, rn_subnet * sn)
Definition at line 13 of file rn-subnet.c.
References rn_subnet::machines, tw_error(), and TW_LOC.
Referenced by verify_topology().
rn_subnet* rn_nextsn_onarea (rn_subnet * sn, rn_area * ar)
Definition at line 4 of file rn-subnet.c.
References rn_subnet::next, and rn_area::subnets.
Referenced by verify_topology().