ROSS: rnf/modules/application/phold/phold.h File Reference
phold.h File Reference
#include <rossnet.h>
Data Structures
struct phold_state
struct phold_message
Typedefs
typedef struct phold_state phold_state
typedef struct phold_message phold_message
Functions
void phold_init (phold_state *s, tw_lp *lp)
void phold_event_handler (phold_state *, tw_bf *, phold_message *, tw_lp *)
void phold_event_handler_rc (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_finish (phold_state *s, tw_lp *lp)
void phold_xml (phold_state *state, const xmlNodePtr node, tw_lp *lp)
Typedef Documentation
typedef struct phold_message phold_message
Definition at line 11 of file phold.h.
typedef struct phold_state phold_state
Definition at line 10 of file phold.h.
Function Documentation
void phold_event_handler (phold_state * , tw_bf * , phold_message * , tw_lp *)
Definition at line 49 of file phold.c.
References tw_bf::c1, DOWNSTREAM, g_tw_nlp, tw_lp::gid, lookahead, mean, offset_lpid, percent_remote, rn_event_new(), rn_event_send(), tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
void phold_event_handler_rc (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 74 of file phold.c.
References tw_bf::c1, tw_lp::rng, and tw_rand_reverse_unif.
void phold_finish (phold_state * s, tw_lp * lp)
Definition at line 84 of file phold.c.
void phold_init (phold_state * s, tw_lp * lp)
Definition at line 35 of file phold.c.
References DOWNSTREAM, g_phold_start_events, g_tw_ts_end, tw_lp::gid, lookahead, mean, rn_event_new(), rn_event_send(), tw_lp::rng, stagger, tw_event_new(), tw_event_send(), and tw_rand_exponential().
void phold_xml (phold_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 4 of file phold-xml.c.