ROSS: rnf/modules/application/epi/epi-seir.c File Reference
epi-seir.c File Reference
#include <epi.h>
Functions
void epi_seir_compute (epi_state *state, tw_bf *bf, tw_lp *lp)
Function Documentation
void epi_seir_compute (epi_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 18 of file epi-seir.c.
References epi_agent::ct, delta_t, EPI_SUSCEPTIBLE, g_epi_ct, g_epi_stages, tw_lp::id, epi_state::last_event, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_state::pq, pq_get_size(), pq_next(), tw_lp::rng, s, epi_statistics::s_nchecked, epi_statistics::s_ndraws, epi_agent::stage, epi_ic_stage::start_multiplier, epi_state::stats, epi_ic_stage::stop_multiplier, epi_agent::ts_stage_tran, tw_now(), tw_rand_geometric(), and tw_rand_unif.
Referenced by epi_event_handler().