ROSS: rnf/modules/application/epi/save/epi-num.c File Reference
epi-num.c File Reference
#include <epi.h>
Functions
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
Function Documentation
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 4 of file epi-num.c.
References epi_agent::curr, epi_agent::dur, tw_lp::id, epi_agent::loc, NINE_OCLOCK, epi_agent::nloc, epi_agent::num, rn_event_direct(), rn_event_send(), rn_message::ttl, tw_event_data(), tw_now(), and TWENTY_FOUR_HOURS.
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 50 of file epi-num.c.
References tw_lp::id, epi_agent::loc, epi_agent::num, rn_event_direct(), rn_event_send(), rn_message::ttl, and tw_event_data().