ROSS: rnf/modules/network/ip/save/ip-downstream.c File Reference
ip-downstream.c File Reference
#include <ip.h>
Functions
rn_link * getroute (ip_state *state, rn_message *msg, tw_lp *lp)
tw_event * forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
Function Documentation
tw_event* forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 32 of file ip-downstream.c.
References tw_pe::abort_event, rn_link::addr, rn_link::avg_delay, rn_link::bandwidth, tw_bf::c31, rn_link::delay, DOWNSTREAM, g_tw_ts_end, getroute(), tw_lp::gid, rn_link::last_sent, tw_lp::pe, tw_event::recv_ts, rn_event_new(), ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::size, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, and tw_now().
rn_link* getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-downstream.c.
References rn_message::dst, tw_lp::gid, ip_packet_drop(), ip_route(), rn_machine::link, rn_machine::nlinks, rn_getlink(), rn_getmachine(), ip_stats::s_nnet_failures, rn_message::src, and ip_state::stats.
void ip_downstream_forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 95 of file ip-downstream.c.
References tw_pe::abort_event, tw_pe::cur_event, rn_message::dst, forward(), ip_packet_drop(), tw_lp::pe, rn_message::port, rn_event_send(), ip_stats::s_ndropped_ttl, rn_message::src, ip_state::stats, rn_message::ttl, tw_error(), tw_event_data(), and TW_LOC.
void ip_downstream_source (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 84 of file ip-downstream.c.
References forward(), g_ip_header, rn_event_send(), and rn_message::size.