ROSS: rnf/modules/transport/tcp/tcp-util.c File Reference
tcp-util.c File Reference
#include <tcp.h>
Functions
void tcp_event_send (tcp_state *state, tw_lpid src, tw_stime ts, tw_lpid dst, int size, int seq_num, int ack, tw_lp *lp)
Function Documentation
void tcp_event_send (tcp_state * state, tw_lpid src, tw_stime ts, tw_lpid dst, int size, int seq_num, int ack, tw_lp * lp)
Definition at line 4 of file tcp-util.c.
References tcp_message::ack, tcp_state::connection, tcp_state::cwnd, DOWNSTREAM, g_tcp_f, g_tcp_fd, tw_lp::gid, tw_lp::id, tcp_state::mss, tcp_state::recv_wnd, rn_event_new(), rn_event_send(), rn_message_setsize(), tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tw_event_data(), tw_memory_alloc(), and tw_now().
Referenced by start_transfer(), tcp_host_process_ack(), tcp_host_process_data(), tcp_host_timeout(), tcp_lp_init(), tcp_process_ack(), tcp_process_data(), and tcp_timeout().