ROSS: rnf/modules/application/epi/save/epi.c File Reference
epi.c File Reference
#include <epi.h>
Macros
#define EPI_MAP_LINEAR 1
#define TWENTY_FOUR_HOURS 86400
Functions
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void epi_rc_event_handler (epi_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
Macro Definition Documentation
#define EPI_MAP_LINEAR 1
Definition at line 3 of file epi.c.
#define TWENTY_FOUR_HOURS 86400
Definition at line 10 of file epi.c.
Referenced by epi_event_handler().
Function Documentation
void epi_event_handler (epi_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 63 of file epi.c.
References tw_pe::cur_event, epi_agent::e_type, EPI_ADD, epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_location_timer(), epi_num_add(), epi_num_remove(), EPI_REMOVE, epi_report_census_tract(), epi_seir_compute(), EPI_STAGE_TRANSITION, EPSILON, g_epi_complete, g_epi_day, g_epi_next_report_day, g_epi_nreport_days, g_epi_report_days, epi_state::last_event, epi_state::ncontagious, tw_lp::pe, tw_error(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 142 of file epi.c.
References epi_report_census_tract(), g_epi_day, g_epi_stats, epi_statistics::s_move_ev, epi_statistics::s_nchecked, epi_statistics::s_ndead, epi_statistics::s_ndraws, epi_statistics::s_ninfected, and epi_state::stats.
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file epi.c.
References epi_agent::dur, epi_agent::e_type, EPI_GRID_HOME, EPI_GRID_OFFICE_1, EPI_REMOVE, EPI_STAGE_TRANSITION, epi_state::grid_type, epi_state::pq, pq_top(), rn_timer_init(), epi_state::tmr_remove, epi_agent::ts_remove, and epi_agent::ts_stage_tran.
void epi_rc_event_handler (epi_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 131 of file epi.c.