ROSS: rnf/modules/transport/tcp/save/tcp-extern.h File Reference
tcp-extern.h File Reference
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
tw_event * tcp_rc_timer_reset (tw_event *, tw_bf *bf, tcp_message *old, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
void tcp_xml (tcp_state *, const xmlNodePtr node, tw_lp *)
void tcp_md_init (int argc, char **argv, char **env)
void tcp_md_final ()
void tcp_init (tcp_state *, tw_lp *)
void tcp_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_final (tcp_state *, tw_lp *)
void tcp_rc_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_process (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_cwnd (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_rtt (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_event_send (tcp_state *, tw_lpid, tw_stime, tw_lpid, int, int, int, tw_lp *)
Variables
tcp_state * g_state
tw_fd g_tcp_fd
tcp_statistics * g_tcp_stats
int g_tcp_mss
int g_tcp_rwd
FILE * g_tcp_f
Function Documentation
void tcp_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 118 of file tcp.c.
void tcp_event_send (tcp_state * , tw_lpid , tw_stime , tw_lpid , int , int , int , tw_lp *)
Definition at line 4 of file tcp-util.c.
Referenced by start_transfer(), tcp_host_process_ack(), tcp_host_process_data(), tcp_host_timeout(), tcp_lp_init(), tcp_process_ack(), tcp_process_data(), and tcp_timeout().
void tcp_final (tcp_state * , tw_lp *)
Definition at line 209 of file tcp.c.
void tcp_init (tcp_state * , tw_lp *)
Definition at line 80 of file tcp.c.
void tcp_md_final ()
Definition at line 27 of file tcp-model.c.
Referenced by main().
void tcp_md_init (int argc, char ** argv, char ** env)
Definition at line 4 of file tcp-model.c.
void tcp_process (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
void tcp_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-process.c.
Referenced by tcp_event_handler().
void tcp_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 144 of file tcp-process.c.
Referenced by tcp_event_handler().
void tcp_rc_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 168 of file tcp.c.
void tcp_rc_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-process.c.
Referenced by tcp_rc_event_handler().
void tcp_rc_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 94 of file tcp-rc-process.c.
Referenced by tcp_rc_event_handler().
void tcp_rc_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-timeout.c.
Referenced by tcp_rc_event_handler().
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 135 of file tcp-timer.c.
Referenced by tcp_rc_process_ack().
tw_event* tcp_rc_timer_reset (tw_event * , tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 61 of file tcp-timer.c.
Referenced by tcp_rc_process_ack(), and tcp_rc_timeout().
void tcp_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 4 of file tcp-timeout.c.
Referenced by tcp_event_handler().
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 114 of file tcp-timer.c.
Referenced by tcp_update_rtt().
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
Referenced by tcp_process_ack(), tcp_timeout(), and tcp_update_rtt().
void tcp_update_cwnd (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-update.c.
Referenced by tcp_host_process_ack(), and tcp_process_ack().
void tcp_update_rtt (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 25 of file tcp-update.c.
Referenced by tcp_host_process_ack(), and tcp_process_ack().
void tcp_xml (tcp_state * , const xmlNodePtr node, tw_lp *)
Definition at line 4 of file tcp-xml.c.
Variable Documentation
tcp_state* g_state
Definition at line 3 of file tcp-global.c.
Referenced by tcp_init().
FILE* g_tcp_f
Definition at line 12 of file tcp-global.c.
Referenced by tcp_event_send(), tcp_md_final(), and tcp_md_init().
tw_fd g_tcp_fd
Definition at line 9 of file tcp-global.c.
Referenced by start_transfer(), stop_transfer(), tcp_event_handler(), tcp_event_send(), tcp_host_process_ack(), tcp_host_timeout(), tcp_host_update_rtt(), tcp_main(), tcp_md_init(), tcp_rc_event_handler(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_timer_cancel(), and tcp_timer_reset().
int g_tcp_mss
Definition at line 5 of file tcp-global.c.
Referenced by tcp_init(), and tcp_xml().
int g_tcp_rwd
Definition at line 7 of file tcp-global.c.
Referenced by tcp_init(), tcp_process_data(), tcp_rc_process_data(), and tcp_xml().
tcp_statistics* g_tcp_stats
Definition at line 10 of file tcp-global.c.
Referenced by tcp_final(), tcp_lp_final(), tcp_main(), tcp_md_final(), and tcp_md_init().