ROSS: rnf/modules/transport/tcp/tcp-timer.c File Reference
tcp-timer.c File Reference
#include <tcp.h>
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
Function Documentation
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 57 of file tcp-timer.c.
References tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), RC::timer_ts, tw_error(), TW_LOC, tw_memory_free(), and tw_now().
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
References tw_bf::c13, tw_bf::c14, tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_init(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, and tw_memory_alloc().