ROSS: rnf/modules/transport/tcp/tcp-extern.h File Reference
tcp-extern.h File Reference
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
tw_event * tcp_rc_timer_reset (tw_event *, tw_bf *bf, tcp_message *old, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
void tcp_xml (tcp_state *, const xmlNodePtr node, tw_lp *)
void tcp_md_opts ()
void tcp_md_init (int argc, char **argv, char **env)
void tcp_md_final ()
void tcp_init (tcp_state *, tw_lp *)
void tcp_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_final (tcp_state *, tw_lp *)
void tcp_rc_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_process (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_cwnd (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_rtt (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_event_send (tcp_state *, tw_lpid, tw_stime, tw_lpid, int, int, int, tw_lp *)
Variables
tcp_state * g_state
tw_fd g_tcp_fd
tcp_statistics * g_tcp_stats
int g_tcp_mss
int g_tcp_rwd
Function Documentation
void tcp_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 118 of file tcp.c.
References tcp_state::connection, tw_pe::cur_event, DOWNSTREAM, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::RC, rn_message::size, tcp_message::src, start_transfer(), stop_transfer(), tcp_process_ack(), tcp_process_data(), tcp_timeout(), TIMER, tw_error(), TW_LOC, tw_memory_free(), tw_now(), and rn_message::type.
void tcp_event_send (tcp_state * , tw_lpid , tw_stime , tw_lpid , int , int , int , tw_lp *)
Definition at line 4 of file tcp-util.c.
References tcp_message::ack, tcp_state::connection, tcp_state::cwnd, DOWNSTREAM, g_tcp_f, g_tcp_fd, tw_lp::gid, tw_lp::id, tcp_state::mss, tcp_state::recv_wnd, rn_event_new(), rn_event_send(), rn_message_setsize(), tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tw_event_data(), tw_memory_alloc(), and tw_now().
void tcp_final (tcp_state * , tw_lp *)
Definition at line 209 of file tcp.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_state::connection, tcp_state::cwnd, tcp_statistics::dropped_packets, tcp_statistics::final_time, g_rn_logs_dir, g_tcp_stats, tw_lp::gid, tw_lp::id, tcp_state::len, tcp_statistics::recv, rn_getmachine(), tcp_statistics::sent, tcp_statistics::start_time, tcp_state::stats, tcp_statistics::throughput, tcp_statistics::tout, and tw_now().
void tcp_init (tcp_state * , tw_lp *)
Definition at line 80 of file tcp.c.
References rn_machine::conn, tcp_state::connection, tcp_state::cwnd, g_state, g_tcp_mss, g_tcp_rwd, tw_lp::gid, tw_lp::id, tcp_state::len, tcp_state::mss, tcp_state::recv_wnd, rn_getmachine(), tcp_state::rto, rn_message::size, tcp_state::ssthresh, start_transfer(), tcp_state::stats, TCP_SND_WND, tw_calloc(), TW_LOC, and tcp_state::unack.
void tcp_md_final ()
Definition at line 27 of file tcp-model.c.
void tcp_md_init (int argc, char ** argv, char ** env)
Definition at line 4 of file tcp-model.c.
References g_tcp_f, g_tcp_fd, g_tcp_stats, g_tw_nkp, nbufs, tw_calloc(), tw_error(), tw_getkp(), tw_ismaster(), TW_LOC, and tw_memory_init().
void tcp_md_opts ()
Definition at line 10 of file tcp-model.c.
References tw_opt_add().
void tcp_process (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
void tcp_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-process.c.
void tcp_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 144 of file tcp-process.c.
void tcp_rc_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 168 of file tcp.c.
References tcp_state::connection, tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::src, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), TIMER, tw_error(), TW_LOC, tw_memory_free_rc(), tw_now(), and rn_message::type.
void tcp_rc_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-process.c.
void tcp_rc_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 94 of file tcp-rc-process.c.
void tcp_rc_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-timeout.c.
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 135 of file tcp-timer.c.
tw_event* tcp_rc_timer_reset (tw_event * , tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 61 of file tcp-timer.c.
void tcp_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 4 of file tcp-timeout.c.
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 114 of file tcp-timer.c.
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
void tcp_update_cwnd (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-update.c.
void tcp_update_rtt (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 25 of file tcp-update.c.
void tcp_xml (tcp_state * , const xmlNodePtr node, tw_lp *)
Definition at line 4 of file tcp-xml.c.
References g_tcp_mss, g_tcp_rwd, tcp_state::mss, and tcp_state::recv_wnd.
Variable Documentation
tcp_state* g_state
Definition at line 3 of file tcp-global.c.
tw_fd g_tcp_fd
Definition at line 9 of file tcp-global.c.
int g_tcp_mss
Definition at line 5 of file tcp-global.c.
int g_tcp_rwd
Definition at line 7 of file tcp-global.c.
tcp_statistics* g_tcp_stats
Definition at line 10 of file tcp-global.c.