ROSS: rnf/modules/application/epi/save/epi-extern.h File Reference
epi-extern.h File Reference
Functions
void epi_report_census_tract ()
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_timer_cancel (tw_event *tmr, tw_lp *lp)
tw_event * epi_timer_start (epi_agent *a, tw_event *t, tw_stime ts, tw_lp *lp)
tw_memory * epi_timer_update (epi_state *state, tw_lp *lp)
void * pq_create (void)
void pq_enqueue (void *pq, epi_agent *)
void * pq_dequeue (void *pq)
void * pq_top (void *pq)
void * pq_next (void *pq, int next)
tw_stime pq_minimum (void *pq)
void pq_delete_any (void *pq, epi_agent **)
unsigned int pq_get_size (void *q)
unsigned int pq_max_size (void *q)
void epi_seir_compute (epi_state *state, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_rc_seir_compute (epi_state *state, tw_bf *bf, epi_agent *, tw_lp *lp)
epi_agent * epi_getagent (int id)
void epi_agent_add (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_rc_agent_add (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
int epi_agent_remove (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_rc_agent_remove (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_agent_stage_tran (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_report_census_track ()
void epi_setup_options (int argc, char **argv)
void epi_init_scenario ()
void epi_main (int argc, char **argv, char **env)
void epi_xml (epi_state *state, const xmlNodePtr node, tw_lp *lp)
void epi_md_final ()
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_rc_event_handler (epi_state *, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
void epi_stats_print ()
Variables
double g_epi_psick
double g_epi_work_while_sick_p
unsigned int g_epi_nagents
unsigned int g_epi_nsick
unsigned int g_epi_nstages
epi_ic_stage * g_epi_stages
char * g_epi_ic_fn
char * g_epi_position_fn
char * g_epi_log_fn
FILE * g_epi_position_f
FILE * g_epi_log_f
epi_statistics * g_epi_stats
unsigned int ** g_epi_ct
unsigned int g_epi_nct
unsigned int g_epi_day
double g_epi_worried_well_rate
double g_epi_worried_well_threshold
unsigned int g_epi_worried_well_duration
tw_fd g_epi_fd
double EPSILON
Function Documentation
void epi_agent_add (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 112 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::curr, epi_agent::days_remaining, epi_agent::dur, EPI_AGENT_WORRIED_WELL, EPSILON, g_epi_stages, g_epi_worried_well_duration, g_epi_worried_well_threshold, epi_agent::id, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::max_queue_size, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_enqueue(), pq_get_size(), epi_agent::stage, timer_helper(), epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_error(), TW_LOC, and tw_now().
Referenced by epi_event_handler().
int epi_agent_remove (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 216 of file epi-agent.c.
References epi_agent::curr, epi_agent::days_remaining, epi_agent::e_type, EPI_ADD, epi_agent_add_back(), EPSILON, g_epi_stages, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_dequeue(), rn_event_direct(), rn_event_send(), epi_statistics::s_move_ev, epi_agent::stage, epi_state::stats, timer_helper(), tw_error(), tw_getlp(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
void epi_agent_stage_tran (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 20 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::ct, epi_agent::days_remaining, EPI_AGENT_WORK_WHILE_SICK, EPI_AGENT_WORRIED_WELL, EPSILON, g_epi_ct, g_epi_hospital, g_epi_nstages, g_epi_stages, tw_lp::id, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_state::ncontagious, epi_state::pq, pq_dequeue(), pq_enqueue(), tw_lp::rng, s, epi_statistics::s_ndead, epi_statistics::s_ninfected, epi_agent::stage, epi_state::stats, timer_helper(), epi_agent::ts_last_tran, epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_error(), TW_LOC, tw_now(), tw_rand_unif, and TWENTY_FOUR_HOURS.
Referenced by epi_agent_remove(), and epi_event_handler().
void epi_event_handler (epi_state * state, tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 44 of file epi.c.
References tw_pe::cur_event, epi_agent::e_type, EPI_ADD, epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_location_timer(), epi_num_add(), epi_num_remove(), EPI_REMOVE, epi_report_census_tract(), epi_seir_compute(), EPI_STAGE_TRANSITION, EPSILON, g_epi_complete, g_epi_day, g_epi_next_report_day, g_epi_nreport_days, g_epi_report_days, epi_state::last_event, epi_state::ncontagious, tw_lp::pe, tw_error(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 121 of file epi.c.
epi_agent* epi_getagent (int id)
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file epi.c.
void epi_init_scenario ()
Definition at line 225 of file epi-init.c.
void epi_main (int argc, char ** argv, char ** env)
Definition at line 14 of file epi-main.c.
void epi_md_final ()
Definition at line 26 of file epi-main.c.
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 21 of file epi-num.c.
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 63 of file epi-num.c.
void epi_rc_agent_add (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
void epi_rc_agent_remove (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
void epi_rc_event_handler (epi_state * , tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 110 of file epi.c.
void epi_rc_seir_compute (epi_state * state, tw_bf * bf, epi_agent * , tw_lp * lp)
void epi_report_census_track ()
void epi_report_census_tract ()
Definition at line 29 of file epi-report.c.
References g_epi_complete, g_epi_ct, g_epi_day, g_epi_hospital, g_epi_hospital_f, g_epi_log_f, g_epi_nct, and g_epi_nstages.
void epi_seir_compute (epi_state * state, tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 18 of file epi-seir.c.
References epi_agent::ct, delta_t, EPI_INCUBATING, EPI_SUSCEPTIBLE, EPSILON, g_epi_ct, g_epi_position_f, g_epi_stages, epi_agent::id, tw_lp::id, epi_state::last_event, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_state::pq, pq_get_size(), pq_next(), s, epi_statistics::s_nchecked, epi_statistics::s_ninfected, epi_agent::stage, epi_state::stats, epi_agent::ts_infected, epi_agent::ts_last_tran, epi_agent::ts_stage_tran, tw_now(), and tw_rand_unif.
void epi_setup_options (int argc, char ** argv)
Definition at line 30 of file epi-setup.c.
void epi_stats_print ()
Definition at line 4 of file epi-stats.c.
void epi_timer_cancel (tw_event * tmr, tw_lp * lp)
Definition at line 8 of file epi-timer.c.
References g_epi_fd, rn_timer_cancel(), tw_error(), TW_LOC, and tw_memory_free().
tw_event* epi_timer_start (epi_agent * a, tw_event * t, tw_stime ts, tw_lp * lp)
Definition at line 20 of file epi-timer.c.
References rn_timer_init(), rn_timer_reset(), tw_event::state, tw_error(), and TW_LOC.
Referenced by timer_helper().
tw_memory* epi_timer_update (epi_state * state, tw_lp * lp)
void epi_xml (epi_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 8 of file epi-xml.c.
References epi_agent::a_type, epi_agent::behavior_flags, epi_agent::ct, epi_agent::curr, epi_agent::dur, EPI_INCUBATING, EPI_SUSCEPTIBLE, EPSILON, g_epi_ct, g_epi_nagents, g_epi_nct, g_epi_nsick, g_epi_nstages, g_epi_psick, g_epi_stages, g_epi_work_while_sick_p, g_epi_worried_well_rate, epi_agent::id, rn_subnet::id, tw_lp::id, epi_agent::loc, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_agent::n_infected, epi_agent::nloc, rn_area::nsubnets, epi_agent::num, epi_state::pq, pq_create(), pq_enqueue(), rn_getarea(), rn_getmachine(), rn_getsubnet(), tw_lp::rng, s, epi_agent::stage, epi_ic_stage::stage_index, epi_state::stats, rn_area::subnets, epi_agent::ts_infected, epi_agent::ts_last_tran, epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_calloc(), tw_error(), tw_getlp(), TW_LOC, tw_rand_integer(), tw_rand_unif, rn_machine::uid, x, and xml_getprop().
void* pq_create (void)
Definition at line 159 of file queue-heap.c.
void pq_delete_any (void * pq, epi_agent **)
Definition at line 133 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, KEY, CHeap::nelems, percolate_up(), and sift_down().
void* pq_dequeue (void * pq)
Definition at line 101 of file queue-heap.c.
void pq_enqueue (void * pq, epi_agent *)
Definition at line 78 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, epi_agent::heap_index, CHeap::nelems, epi_agent::next, percolate_up(), and epi_agent::prev.
unsigned int pq_get_size (void * q)
Definition at line 197 of file queue-heap.c.
unsigned int pq_max_size (void * q)
tw_stime pq_minimum (void * pq)
Definition at line 174 of file queue-heap.c.
void* pq_next (void * pq, int next)
Definition at line 192 of file queue-heap.c.
void* pq_top (void * pq)
Definition at line 183 of file queue-heap.c.
Variable Documentation
double EPSILON
Definition at line 40 of file epi-global.c.
unsigned int** g_epi_ct
Definition at line 20 of file epi-global.c.
unsigned int g_epi_day
Definition at line 22 of file epi-global.c.
tw_fd g_epi_fd
Definition at line 37 of file epi-global.c.
char* g_epi_ic_fn
Definition at line 10 of file epi-global.c.
FILE* g_epi_log_f
Definition at line 13 of file epi-global.c.
char* g_epi_log_fn
Definition at line 10 of file epi-global.c.
unsigned int g_epi_nagents
Definition at line 18 of file epi-global.c.
unsigned int g_epi_nct
Definition at line 21 of file epi-global.c.
unsigned int g_epi_nsick
Definition at line 19 of file epi-global.c.
unsigned int g_epi_nstages
Definition at line 24 of file epi-global.c.
FILE* g_epi_position_f
Definition at line 12 of file epi-global.c.
char* g_epi_position_fn
Definition at line 11 of file epi-global.c.
double g_epi_psick
Definition at line 16 of file epi-global.c.
epi_ic_stage* g_epi_stages
Definition at line 31 of file epi-global.c.
epi_statistics* g_epi_stats
Definition at line 8 of file epi-global.c.
double g_epi_work_while_sick_p
Definition at line 17 of file epi-global.c.
unsigned int g_epi_worried_well_duration
Definition at line 30 of file epi-global.c.
double g_epi_worried_well_rate
Definition at line 28 of file epi-global.c.
double g_epi_worried_well_threshold
Definition at line 29 of file epi-global.c.