ROSS: rnf/modules/transport/tcp/save/tcp.c File Reference
tcp.c File Reference
#include <tcp.h>
Functions
void stop_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void start_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_init (tcp_state *state, tw_lp *lp)
void tcp_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_rc_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_final (tcp_state *state, tw_lp *lp)
Function Documentation
void start_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 25 of file tcp.c.
References tcp_state::connection, tcp_state::cwnd, rn_message::dst, g_tcp_fd, tw_lp::id, tcp_state::len, tcp_state::mss, tw_event::recv_ts, rn_timer_init(), tcp_state::rto, tcp_state::rtt_seq, tcp_state::rtt_time, tcp_statistics::sent, tcp_state::seq_num, tcp_message::seq_num, rn_message::size, tcp_message::src, rn_message::src, tcp_state::ssthresh, tcp_state::stats, tcp_event_send(), TCP_MTU, TCP_SND_WND, tcp_state::timer, tw_error(), TW_LOC, tw_memory_alloc(), tw_now(), and tcp_state::unack.
Referenced by tcp_event_handler(), and tcp_init().
void stop_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 4 of file tcp.c.
References g_tcp_fd, tw_lp::id, tcp_state::len, rn_timer_cancel(), tcp_state::timer, tw_memory_free(), tw_now(), and tcp_state::unack.
Referenced by tcp_event_handler().
void tcp_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 118 of file tcp.c.
void tcp_final (tcp_state * state, tw_lp * lp)
Definition at line 209 of file tcp.c.
void tcp_init (tcp_state * state, tw_lp * lp)
Definition at line 80 of file tcp.c.
void tcp_rc_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 168 of file tcp.c.