ROSS: rnf/modules/transport/tcp/tcp-process.c File Reference
tcp-process.c File Reference
#include <tcp.h>
Functions
void tcp_process_ack (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
void tcp_process_data (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
Function Documentation
void tcp_process_ack (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 7 of file tcp-process.c.
References tcp_message::ack, tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tw_bf::c2, tw_bf::c3, tw_bf::c4, tcp_state::connection, tcp_state::cwnd, RC::cwnd, tcp_state::dup_count, RC::dup_count, tw_lp::gid, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tcp_state::recv_wnd, tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, RC::sent, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_state::ssthresh, RC::ssthresh, tcp_statistics::start_time, tcp_state::stats, tcp_event_send(), TCP_MTU, tcp_timer_reset(), tcp_update_cwnd(), tcp_update_rtt(), tcp_state::timer, tw_error(), TW_LOC, tw_now(), tcp_state::unack, and RC::unack.
void tcp_process_data (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 138 of file tcp-process.c.
References tcp_statistics::ack_sent, tw_bf::c16, tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::cwnd, RC::dup_count, g_tcp_rwd, tw_lp::gid, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, RC::out_of_order, tcp_message::RC, tcp_statistics::recv, tcp_state::recv_wnd, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::stats, tcp_event_send(), TCP_HEADER_SIZE, TCP_SND_WND, tw_error(), and TW_LOC.