ROSS: rnf/modules/network/ip/save/ip-extern.h File Reference
ip-extern.h File Reference
Functions
void ip_init (ip_state *, tw_lp *)
void ip_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_final (ip_state *state, tw_lp *lp)
void ip_upstream (ip_state *, rn_message *, tw_lp *lp)
void ip_rc_upstream (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_downstream_forward (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_downstream (ip_state *, rn_message *, tw_lp *)
void ip_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_routing_init ()
void ip_rt_print (ip_state *state, tw_lp *lp, FILE *log)
rn_link * ip_route (rn_machine *me, rn_message *msg)
tw_lpid ip_getroute (ip_state *state, tw_lpid dst)
void ip_xml (tw_lp *lp, xmlNodePtr node)
void ip_md_init (int argc, char **argv, char **env)
void ip_md_final ()
Variables
tw_stime g_ip_major_interval
tw_stime g_ip_minor_interval
ip_stats * g_ip_stats
int g_ip_header
tw_fd g_ip_fd
int g_ip_routing_simple
FILE * g_ip_log
FILE * g_ip_routing_file
int ** g_ip_rt
unsigned int g_ip_log_on
short int * g_ip_front
short int * g_ip_p
short int * g_ip_f
short int * g_ip_s
short int * g_ip_d
Function Documentation
void ip_downstream_forward (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 97 of file ip-downstream.c.
References tw_pe::abort_event, tw_pe::cur_event, rn_message::dst, forward(), ip_packet_drop(), tw_event::next, tw_lp::pe, rn_message::port, rn_event_send(), ip_stats::s_ndropped_ttl, rn_message::size, rn_message::src, tw_event::state, ip_state::stats, rn_message::ttl, tw_error(), tw_event_data(), tw_event_send(), TW_LOC, and rn_message::type.
Referenced by ip_event_handler().
void ip_downstream_source (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 86 of file ip-downstream.c.
References forward(), g_ip_header, rn_event_send(), rn_message::size, and tw_event_send().
Referenced by ip_event_handler().
void ip_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 27 of file ip.c.
References rn_link::avg_delay, c_ha_router, c_router, ip_state::capacity, DOWNSTREAM, rn_message::dst, g_ip_fd, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, tw_lp::gid, tw_lp::id, ip_downstream_forward(), ip_downstream_source(), ip_upstream(), rn_machine::link, ip_state::major, max, ip_state::max_delay, ip_state::minor, rn_machine::nlinks, rn_getmachine(), rn_message::src, tw_error(), TW_LOC, tw_memory_free(), tw_now(), rn_message::type, rn_machine::type, and rn_machine::uid.
void ip_final (ip_state * state, tw_lp * lp)
Definition at line 74 of file ip.c.
References g_ip_stats, max, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, and ip_state::stats.
tw_lpid ip_getroute (ip_state * state, tw_lpid dst)
void ip_init (ip_state * , tw_lp *)
Definition at line 7 of file ip.c.
References rn_link::bandwidth, ip_state::capacity, g_ip_major_interval, g_ip_minor_interval, tw_lp::gid, rn_machine::link, ip_state::link_q, ip_state::major, ip_state::minor, rn_machine::nlinks, rn_getmachine(), ip_state::stats, tw_calloc(), TW_LOC, and tw_memoryq_init().
void ip_md_final ()
Definition at line 53 of file ip-model.c.
void ip_md_init (int argc, char ** argv, char ** env)
Definition at line 17 of file ip-model.c.
References g_ip_fd, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, g_ip_stats, g_rn_logs_dir, g_tw_nkp, ip_routing_init(), nbufs, tw_calloc(), tw_error(), tw_getkp(), tw_ismaster(), TW_LOC, tw_memory_init(), and tw_opt_add().
void ip_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-packet.c.
References tw_pe::abort_event, DOWNSTREAM, rn_message::dst, tw_lp::gid, tw_lp::id, tw_lp::pe, rn_message::port, rn_event_new(), ip_stats::s_ndropped, ip_stats::s_ndropped_source, rn_message::size, rn_message::src, ip_state::stats, and tw_event_free().
void ip_rc_downstream (ip_state * , rn_message * , tw_lp *)
Definition at line 42 of file ip-rc-downstream.c.
References ip_link::addr, rn_link::addr, rn_message::dst, g_ip_fd, tw_lp::gid, tw_lp::id, ip_rc_packet_drop(), ip_link::last_sent, rc_getroute(), ip_message::rc_lastsent, ip_message::rc_link, ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::src, ip_state::stats, rn_message::ttl, and tw_memory_alloc_rc().
void ip_rc_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 46 of file ip.c.
References DOWNSTREAM, rn_message::dst, g_ip_fd, g_ip_header, tw_lp::gid, tw_lp::id, ip_rc_downstream(), ip_rc_packet_drop(), ip_rc_upstream(), ip_link::last_sent, ip_message::rc_lastsent, ip_message::rc_link, ip_stats::s_ndropped_ttl, rn_message::size, rn_message::src, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_free_rc(), and rn_message::type.
void ip_rc_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 26 of file ip-packet.c.
References DOWNSTREAM, rn_message::dst, tw_lp::gid, tw_lp::id, rn_reverse_event_send(), ip_stats::s_ndropped, ip_stats::s_ndropped_source, rn_message::size, rn_message::src, and ip_state::stats.
void ip_rc_upstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 23 of file ip-upstream.c.
References rn_message::dst, g_ip_header, g_rn_ttl, tw_lp::gid, max, rn_reverse_event_send(), ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, rn_message::size, rn_message::src, ip_state::stats, rn_message::ttl, tw_now(), and UPSTREAM.
rn_link* ip_route (rn_machine * me, rn_message * msg)
Definition at line 9 of file ip-routing.c.
References g_ip_rt, rn_machine::id, rn_getlink(), and rn_message::src.
void ip_routing_init ()
Definition at line 125 of file ip-routing.c.
void ip_rt_print (ip_state * state, tw_lp * lp, FILE * log)
Definition at line 50 of file ip-routing.c.
void ip_upstream (ip_state * , rn_message * , tw_lp * lp)
Definition at line 4 of file ip-upstream.c.
References rn_message::dst, g_ip_header, g_rn_ttl, tw_lp::gid, tw_lp::id, max, rn_event_new(), rn_event_send(), ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, rn_message::size, rn_message::src, ip_state::stats, rn_message::ttl, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), rn_message::type, and UPSTREAM.
void ip_xml (tw_lp * lp, xmlNodePtr node)
Definition at line 4 of file ip-xml.c.
Variable Documentation
short int* g_ip_d
Definition at line 34 of file ip-global.c.
short int* g_ip_f
Definition at line 32 of file ip-global.c.
tw_fd g_ip_fd
Definition at line 14 of file ip-global.c.
short int* g_ip_front
Definition at line 30 of file ip-global.c.
int g_ip_header
Definition at line 12 of file ip-global.c.
FILE* g_ip_log
Definition at line 20 of file ip-global.c.
unsigned int g_ip_log_on
Definition at line 25 of file ip-global.c.
tw_stime g_ip_major_interval
Definition at line 23 of file ip-global.c.
tw_stime g_ip_minor_interval
Definition at line 24 of file ip-global.c.
short int* g_ip_p
Definition at line 31 of file ip-global.c.
FILE* g_ip_routing_file
Definition at line 17 of file ip-global.c.
int g_ip_routing_simple
Definition at line 15 of file ip-global.c.
int** g_ip_rt
Definition at line 18 of file ip-global.c.
short int* g_ip_s
Definition at line 33 of file ip-global.c.
ip_stats* g_ip_stats
Definition at line 11 of file ip-global.c.