ROSS: rnf/modules/application/epi/save/epi-timer.c File Reference
epi-timer.c File Reference
#include <epi.h>
Functions
void epi_timer_cancel (tw_event *timer, tw_lp *lp)
tw_event * epi_timer_start (epi_agent *a, tw_event *timer, tw_stime ts, tw_lp *lp)
Function Documentation
void epi_timer_cancel (tw_event * timer, tw_lp * lp)
Definition at line 8 of file epi-timer.c.
References g_epi_fd, rn_timer_cancel(), tw_error(), TW_LOC, and tw_memory_free().
tw_event* epi_timer_start (epi_agent * a, tw_event * timer, tw_stime ts, tw_lp * lp)
Definition at line 20 of file epi-timer.c.
References rn_timer_init(), rn_timer_reset(), tw_event::state, tw_error(), and TW_LOC.
Referenced by timer_helper().