ROSS: rnf/kernel/hash-quadratic.c File Reference
hash-quadratic.c File Reference
#include <rossnet.h>
Data Structures
struct rn_hash
Macros
#define RN_MAX_FRACTION 0.75
Functions
static int rn_find_empty (rn_link **hash_t, rn_link *event, int capacity)
static int rn_find_entry (rn_link **hash_t, int, int capacity)
static int rn_hash_ (int, int capacity)
static int rn_next_prime (int ptst)
static int rn_is_prime (int ptst)
rn_link ** rn_allocate_table (int capacity)
void * rn_hash_create (unsigned int sz)
void h_insert (rn_link **hash_t, rn_link *event, int capacity)
void rn_hash_insert (void *h, rn_link *event)
rn_link * rn_hash_fetch (void *h, int id)
rn_link * rn_hash_remove (void *h, rn_link *event)
Macro Definition Documentation
#define RN_MAX_FRACTION 0.75
Definition at line 9 of file hash-quadratic.c.
Referenced by rn_hash_create(), and rn_hash_insert().
Function Documentation
void h_insert (rn_link ** hash_t, rn_link * event, int capacity)
Definition at line 58 of file hash-quadratic.c.
References rn_find_empty().
Referenced by rn_hash_insert().
rn_link** rn_allocate_table (int capacity)
Definition at line 25 of file hash-quadratic.c.
References tw_calloc(), and TW_LOC.
Referenced by rn_hash_create().
int rn_find_empty (rn_link ** hash_t, rn_link * event, int capacity) static
Definition at line 81 of file hash-quadratic.c.
References rn_link::addr, and rn_hash_().
Referenced by h_insert().
int rn_find_entry (rn_link ** hash_t, int id, int capacity) static
Definition at line 100 of file hash-quadratic.c.
References rn_hash_(), tw_error(), and TW_LOC.
Referenced by rn_hash_fetch(), and rn_hash_remove().
int rn_hash_ (int id, int capacity) static
Definition at line 19 of file hash-quadratic.c.
Referenced by rn_find_empty(), and rn_find_entry().
void* rn_hash_create (unsigned int sz)
Definition at line 31 of file hash-quadratic.c.
References rn_hash::capacity, rn_hash::nstored, rn_allocate_table(), rn_is_prime(), RN_MAX_FRACTION, rn_next_prime(), rn_hash::storage, tw_calloc(), tw_error(), and TW_LOC.
Referenced by rn_xml_topology().
rn_link* rn_hash_fetch (void * h, int id)
Definition at line 122 of file hash-quadratic.c.
References rn_hash::capacity, rn_find_entry(), rn_hash::storage, tw_error(), and TW_LOC.
Referenced by rn_getlink().
void rn_hash_insert (void * h, rn_link * event)
Definition at line 67 of file hash-quadratic.c.
References rn_hash::capacity, h_insert(), rn_hash::nstored, RN_MAX_FRACTION, rn_hash::storage, tw_error(), and TW_LOC.
Referenced by xml_link_topology().
rn_link* rn_hash_remove (void * h, rn_link * event)
Definition at line 144 of file hash-quadratic.c.
References rn_link::addr, rn_hash::capacity, rn_hash::nstored, rn_find_entry(), rn_hash::storage, tw_error(), and TW_LOC.
int rn_is_prime (int ptst) static
Definition at line 186 of file hash-quadratic.c.
Referenced by rn_hash_create(), and rn_next_prime().
int rn_next_prime (int ptst) static
Definition at line 165 of file hash-quadratic.c.
References rn_is_prime().
Referenced by rn_hash_create().