ROSS: rnf/modules/transport/tcp/tcp-timeout.c File Reference
tcp-timeout.c File Reference
#include <tcp.h>
Functions
void tcp_timeout (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
Function Documentation
void tcp_timeout (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 4 of file tcp-timeout.c.
References tw_bf::c1, tcp_state::connection, tcp_state::cwnd, RC::cwnd, RC::dup_count, g_tw_ts_end, tw_lp::gid, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tw_event::recv_ts, tcp_state::recv_wnd, rn_event_new(), rn_event_send(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_state::ssthresh, RC::ssthresh, tcp_state::stats, tcp_event_send(), TCP_MTU, tcp_timer_reset(), tcp_state::timer, tcp_statistics::tout, tw_now(), tcp_state::unack, and UPSTREAM.