ROSS: rnf/modules/network/ip/save/ip-routing.c File Reference
ip-routing.c File Reference
#include <ip.h>
Macros
#define IP_RT_DEBUG 0
#define IP_RT_BINARY 0
Functions
int routing_init_ft_write (rn_machine *m)
rn_link * ip_route (rn_machine *me, rn_message *msg)
int routing_read ()
void routing_write ()
void ip_routing_init ()
void routing_init_ft_read (ip_state *state, tw_lp *lp)
Variables
int * frontier
int * solution
int * previous
unsigned int * distance
Macro Definition Documentation
#define IP_RT_BINARY 0
Definition at line 4 of file ip-routing.c.
#define IP_RT_DEBUG 0
Definition at line 3 of file ip-routing.c.
Function Documentation
rn_link* ip_route (rn_machine * me, rn_message * msg)
Definition at line 9 of file ip-routing.c.
References g_ip_rt, rn_machine::id, rn_getlink(), and rn_message::src.
Referenced by getroute(), and rc_getroute().
void ip_routing_init ()
Definition at line 124 of file ip-routing.c.
References routing_read(), and routing_write().
void routing_init_ft_read (ip_state * state, tw_lp * lp)
Definition at line 131 of file ip-routing.c.
References rn_subnet::area, c_host, rn_machine::ft, g_ip_routing_file, rn_area::g_ospf_nlsa, tw_lp::gid, rn_getmachine(), rn_machine::subnet, tw_error(), TW_LOC, and rn_machine::type.
int routing_init_ft_write (rn_machine * m)
int routing_read ()
Definition at line 24 of file ip-routing.c.
References g_ip_routing_file, g_ip_rt, g_rn_nmachines, g_rn_tools_dir, tw_calloc(), tw_error(), and TW_LOC.
void routing_write ()
Definition at line 75 of file ip-routing.c.
References g_ip_routing_file, g_rn_machines, g_rn_nmachines, g_rn_tools_dir, rn_getmachine(), routing_init_ft_write(), routing_read(), tw_error(), tw_ismaster(), and TW_LOC.
Variable Documentation
unsigned int* distance
Definition at line 175 of file ip-routing.c.
int* frontier
Definition at line 171 of file ip-routing.c.
int* previous
Definition at line 173 of file ip-routing.c.
int* solution
Definition at line 172 of file ip-routing.c.