ROSS: rnf/modules/transport/tcp/tcp-update.c File Reference
tcp-update.c File Reference
#include <tcp.h>
Functions
void tcp_update_cwnd (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
void tcp_update_rtt (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
Function Documentation
void tcp_update_cwnd (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 7 of file tcp-update.c.
References tw_bf::c3, tw_bf::c4, tcp_state::cwnd, RC::cwnd, tcp_state::mss, tcp_message::RC, tcp_state::ssthresh, and TCP_SND_WND.
void tcp_update_rtt (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 25 of file tcp-update.c.
References tcp_message::ack, tw_bf::c16, tw_bf::c17, tw_bf::c5, tw_bf::c6, tw_bf::c7, tcp_state::len, min, tcp_message::RC, tcp_state::rto, RC::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_timer_cancel(), tcp_timer_reset(), tcp_state::timer, tw_now(), and tcp_state::unack.