ROSS: rnf/modules/network/ip/save/ip-rc-downstream.c File Reference
ip-rc-downstream.c File Reference
#include <ip.h>
Functions
rn_link * rc_getroute (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_downstream (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_rc_downstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 42 of file ip-rc-downstream.c.
References rn_link::addr, rn_message::dst, tw_lp::gid, ip_rc_packet_drop(), rc_getroute(), ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::src, ip_state::stats, and rn_message::ttl.
rn_link* rc_getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 20 of file ip-rc-downstream.c.
References rn_message::dst, tw_lp::gid, ip_route(), rn_machine::link, rn_machine::nlinks, rn_getlink(), rn_getmachine(), and rn_message::src.