ROSS: rnf/modules/network/ip/ip-downstream.c File Reference
ip-downstream.c File Reference
#include <ip.h>
Functions
rn_link * getroute (ip_state *state, rn_message *msg, tw_lp *lp)
tw_event * forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
Function Documentation
tw_event* forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 32 of file ip-downstream.c.
References tw_pe::abort_event, rn_link::addr, rn_link::avg_delay, rn_link::bandwidth, tw_bf::c31, rn_link::delay, DOWNSTREAM, g_ip_fd, g_tw_ts_end, getroute(), tw_lp::gid, ip_message::last_sent, rn_link::last_sent, ip_message::link, ip_state::link_q, tw_lp::pe, tw_event::recv_ts, rn_event_new(), ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::size, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_alloc(), tw_memoryq_push(), and tw_now().
Referenced by ip_downstream_forward(), and ip_downstream_source().
rn_link* getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-downstream.c.
References rn_message::dst, tw_lp::gid, ip_packet_drop(), ip_route(), rn_machine::link, rn_machine::nlinks, rn_getlink(), rn_getmachine(), ip_stats::s_nnet_failures, rn_message::src, and ip_state::stats.
Referenced by forward().
void ip_downstream_forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 97 of file ip-downstream.c.
Referenced by ip_event_handler().
void ip_downstream_source (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 86 of file ip-downstream.c.
Referenced by ip_event_handler().