ROSS: rnf/modules/application/epi/save/queue-heap.c File Reference
queue-heap.c File Reference
#include <epi.h>
Data Structures
struct CHeap
Macros
#define KEY(e) (e->ts_next)
#define SWAP(heap, x, y, t)
Typedefs
typedef double KEY_TYPE
typedef struct CHeap CHeap
Functions
epi_agent * HeapPeekTop (CHeap *h)
void sift_down (CHeap *h, int i)
void percolate_up (CHeap *h, int i)
void pq_enqueue (void *pq, epi_agent *e)
void * pq_dequeue (void *pq)
void DumpBucket (void *pq, FILE *fp)
void pq_delete_any (void *pq, epi_agent **q)
void * pq_create (void)
tw_stime pq_minimum (void *pq)
void * pq_top (void *pq)
void * pq_next (void *h, int next)
unsigned int pq_get_size (void *pq)
Macro Definition Documentation
#define KEY (e) (e->ts_next)
Definition at line 12 of file queue-heap.c.
Referenced by DumpBucket(), percolate_up(), pq_delete_any(), pq_minimum(), and sift_down().
#define SWAP (heap, x, y, t)
Value:
{ \
    t = heap->elems[x]; \
    heap->elems[x] = heap->elems[y]; \
    heap->elems[y] = t; \
    heap->elems[x]->heap_index = x; \
    heap->elems[y]->heap_index = y; \
    }
Definition at line 23 of file queue-heap.c.
Referenced by percolate_up(), and sift_down().
Typedef Documentation
typedef struct CHeap CHeap
Definition at line 14 of file queue-heap.c.
typedef double KEY_TYPE
Definition at line 11 of file queue-heap.c.
Function Documentation
void DumpBucket (void * pq, FILE * fp)
Definition at line 118 of file queue-heap.c.
References CHeap::elems, KEY, and CHeap::nelems.
epi_agent* HeapPeekTop (CHeap * h) inline
Definition at line 32 of file queue-heap.c.
References CHeap::elems, and CHeap::nelems.
void percolate_up (CHeap * h, int i)
Definition at line 57 of file queue-heap.c.
References CHeap::elems, KEY, CHeap::nelems, p, and SWAP.
void* pq_create (void)
Definition at line 159 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, and CHeap::nelems.
void pq_delete_any (void * pq, epi_agent ** q)
Definition at line 133 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, KEY, CHeap::nelems, percolate_up(), and sift_down().
Referenced by epi_init(), and pq_cleanup().
void* pq_dequeue (void * pq)
Definition at line 101 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, CHeap::nelems, and sift_down().
void pq_enqueue (void * pq, epi_agent * e)
Definition at line 78 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, epi_agent::heap_index, CHeap::nelems, epi_agent::next, percolate_up(), and epi_agent::prev.
Referenced by agent_stage_tran(), epi_agent_add(), epi_agent_add_back(), epi_agent_remove(), epi_agent_stage_tran(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_xml(), and pq_cleanup().
unsigned int pq_get_size (void * pq)
Definition at line 197 of file queue-heap.c.
tw_stime pq_minimum (void * pq)
Definition at line 174 of file queue-heap.c.
References HeapPeekTop(), and KEY.
void* pq_next (void * h, int next)
Definition at line 192 of file queue-heap.c.
void* pq_top (void * pq)
Definition at line 183 of file queue-heap.c.
References HeapPeekTop().
void sift_down (CHeap * h, int i)
Definition at line 38 of file queue-heap.c.
References CHeap::elems, KEY, CHeap::nelems, and SWAP.