ROSS: rnf/modules/application/epi/epi-num.c File Reference
epi-num.c File Reference
#include <epi.h>
Functions
void epi_num_check_report (epi_state *state, tw_lp *lp)
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
Function Documentation
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 21 of file epi-num.c.
void epi_num_check_report (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-num.c.
References epi_agent::num, epi_state::pq, pq_top(), rn_event_direct(), rn_event_send(), rn_message::ttl, tw_error(), tw_event_data(), and TW_LOC.
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 63 of file epi-num.c.