ROSS: rnf/modules/transport/tcp/save/tcp-host-rc.c File Reference
tcp-host-rc.c File Reference
#include "tcp.h"
Functions
void tcp_process_ack_rc (tcp_state *state, tw_bf *bf, tcp_message *M, tw_lp *lp)
void tcp_process_data_rc (tcp_state *state, tw_bf *bf, tcp_message *M, tw_lp *lp)
void tcp_timeout_rc (tcp_state *state, tw_bf *bf, tcp_message *M, tw_lp *lp)
Function Documentation
void tcp_process_ack_rc (tcp_state * state, tw_bf * bf, tcp_message * M, tw_lp * lp)
Definition at line 9 of file tcp-host-rc.c.
References tcp_message::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c9, tcp_state::cwnd, RC::cwnd, tcp_message::dst, tcp_state::dup_count, RC::dup_count, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_message::RC, tcp_state::rto, RTO, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tcp_state::timer, RC::timer_seq, RC::timer_ts, tw_event_data(), tw_timer_init(), tw_timer_reset(), and tcp_state::unack.
void tcp_process_data_rc (tcp_state * state, tw_bf * bf, tcp_message * M, tw_lp * lp)
Definition at line 116 of file tcp-host-rc.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::dup_count, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, tcp_message::RC, tcp_state::recv_wnd, tcp_state::seq_num, and tcp_message::seq_num.
void tcp_timeout_rc (tcp_state * state, tw_bf * bf, tcp_message * M, tw_lp * lp)
Definition at line 154 of file tcp-host-rc.c.
References tcp_message::ack, tw_bf::c1, tcp_state::cwnd, RC::cwnd, tcp_message::dst, RC::dup_count, tcp_state::lastsent, RC::lastsent, tcp_message::RC, tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_state::ssthresh, tcp_state::timer, RC::timer, and tw_timer_cancel().