ROSS: rnf/modules/transport/tcp/save/tcp-host.c File Reference
tcp-host.c File Reference
#include <tcp.h>
Macros
#define TCP_DEBUG 0
Functions
void tcp_host_process_ack (tcp_state *state, tw_bf *bf, tcp_message *msg, tw_lp *lp)
void tcp_host_process_data (tcp_state *state, tw_bf *bf, tcp_message *msg, tw_lp *lp)
void tcp_host_update_cwnd (tcp_state *state, tw_bf *bf, tcp_message *msg, tw_lp *lp)
void tcp_host_update_rtt (tcp_state *state, tw_bf *bf, tcp_message *msg, tw_lp *lp)
void tcp_host_timeout (tcp_state *state, tw_bf *bf, tcp_message *msg, tw_lp *lp)
Macro Definition Documentation
#define TCP_DEBUG 0
Definition at line 3 of file tcp-host.c.
Referenced by tcp_process_data().
Function Documentation
void tcp_host_process_ack (tcp_state * state, tw_bf * bf, tcp_message * msg, tw_lp * lp)
Definition at line 10 of file tcp-host.c.
References tcp_message::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c9, tcp_state::cwnd, RC::cwnd, tcp_message::dst, tcp_state::dup_count, RC::dup_count, FORWARD, g_tcp_fd, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tw_event::recv_ts, tcp_state::recv_wnd, rn_timer_reset(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tcp_event_send(), TCP_TRANSFER_SIZE, tcp_update_cwnd(), tcp_update_rtt(), tcp_state::timer, RC::timer_seq, RC::timer_ts, tw_memory_alloc(), tw_now(), and tcp_state::unack.
Referenced by tcp_host_process().
void tcp_host_process_data (tcp_state * state, tw_bf * bf, tcp_message * msg, tw_lp * lp)
Definition at line 156 of file tcp-host.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::dup_count, FORWARD, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, tcp_message::RC, tcp_state::recv_wnd, tcp_state::seq_num, tcp_message::seq_num, tcp_message::src, tcp_event_send(), TCP_HEADER_SIZE, TCP_SND_WND, TCP_TRANSFER_SIZE, tw_error(), TW_LOC, and tw_now().
Referenced by tcp_host_process().
void tcp_host_timeout (tcp_state * state, tw_bf * bf, tcp_message * msg, tw_lp * lp)
Definition at line 353 of file tcp-host.c.
References tcp_message::ack, tw_bf::c1, tw_bf::c13, tcp_state::cwnd, RC::cwnd, tcp_message::dst, RC::dup_count, FORWARD, g_tcp_fd, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tcp_state::recv_wnd, rn_timer_init(), tcp_state::rto, RTO, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tcp_event_send(), TCP_TRANSFER_SIZE, tcp_state::timer, RC::timer, tw_memory_alloc(), tw_now(), and tcp_state::unack.
Referenced by tcp_host_EventHandler().
void tcp_host_update_cwnd (tcp_state * state, tw_bf * bf, tcp_message * msg, tw_lp * lp)
Definition at line 243 of file tcp-host.c.
References tw_bf::c3, tw_bf::c4, tcp_state::cwnd, RC::cwnd, tcp_state::mss, tcp_message::RC, tcp_state::ssthresh, and TCP_SND_WND.
Referenced by tcp_host_process_ack().
void tcp_host_update_rtt (tcp_state * state, tw_bf * bf, tcp_message * msg, tw_lp * lp)
Definition at line 265 of file tcp-host.c.
References tcp_message::ack, tw_bf::c13, tw_bf::c5, tw_bf::c6, tw_bf::c7, tcp_message::dst, g_tcp_fd, tcp_state::len, tcp_message::RC, tw_event::recv_ts, rn_timer_reset(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_message::seq_num, tcp_state::timer, RC::timer_seq, RC::timer_ts, tw_memory_alloc(), tw_now(), and tcp_state::unack.
Referenced by tcp_host_process_ack().