ROSS: rnf/modules/application/epi/epi-agent.c File Reference
epi-agent.c File Reference
#include <epi.h>
Functions
void epi_agent_stage_tran (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_agent_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_agent_add_back (epi_state *state, tw_lp *lp, epi_agent *a)
void epi_agent_remove (epi_state *state, tw_bf *bf, tw_lp *lp)
Function Documentation
void epi_agent_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 112 of file epi-agent.c.
Referenced by epi_event_handler().
void epi_agent_add_back (epi_state * state, tw_lp * lp, epi_agent * a)
Definition at line 159 of file epi-agent.c.
References epi_agent::curr, epi_agent::dur, epi_num_add(), epi_agent::nloc, epi_state::pq, pq_enqueue(), epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, and tw_now().
Referenced by epi_agent_remove().
void epi_agent_remove (epi_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 195 of file epi-agent.c.
Referenced by epi_event_handler().
void epi_agent_stage_tran (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 20 of file epi-agent.c.
Referenced by epi_agent_remove(), and epi_event_handler().