ROSS: rnf/modules/network/ip/save/ip.c File Reference
ip.c File Reference
#include <ip.h>
Functions
void ip_init (ip_state *state, tw_lp *lp)
void ip_event_handler (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_rc_event_handler (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_final (ip_state *state, tw_lp *lp)
Function Documentation
void ip_event_handler (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 25 of file ip.c.
References rn_link::avg_delay, c_ha_router, c_router, ip_state::capacity, DOWNSTREAM, rn_message::dst, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, tw_lp::gid, ip_downstream_forward(), ip_downstream_source(), ip_upstream(), rn_machine::link, ip_state::major, max, ip_state::max_delay, ip_state::minor, rn_machine::nlinks, rn_getmachine(), rn_message::src, tw_error(), TW_LOC, tw_now(), rn_message::type, rn_machine::type, and rn_machine::uid.
void ip_final (ip_state * state, tw_lp * lp)
Definition at line 139 of file ip.c.
References g_ip_stats, max, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, and ip_state::stats.
void ip_init (ip_state * state, tw_lp * lp)
Definition at line 7 of file ip.c.
References rn_link::bandwidth, ip_state::capacity, g_ip_major_interval, g_ip_minor_interval, tw_lp::gid, rn_machine::link, ip_state::link_q, ip_state::major, ip_state::minor, rn_machine::nlinks, rn_getmachine(), ip_state::stats, tw_calloc(), TW_LOC, and tw_memoryq_init().
void ip_rc_event_handler (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 88 of file ip.c.
References DOWNSTREAM, rn_message::dst, g_ip_fd, g_ip_header, tw_lp::gid, ip_rc_downstream(), ip_rc_packet_drop(), ip_rc_upstream(), ip_stats::s_ndropped_ttl, rn_message::size, rn_message::src, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_free_rc(), and rn_message::type.