ROSS: rnf/modules/application/epi/epi-extern.h File Reference
epi-extern.h File Reference
Functions
void epi_report_census_tract ()
void epi_num_check_report (epi_state *state, tw_lp *lp)
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_location_timer (epi_state *, tw_lp *lp)
void * pq_create (void)
void pq_enqueue (void *pq, epi_agent *)
void * pq_dequeue (void *pq)
void * pq_top (void *pq)
void * pq_next (void *pq, int next)
tw_stime pq_minimum (void *pq)
void pq_delete_any (void *pq, epi_agent **)
unsigned int pq_get_size (void *q)
unsigned int pq_max_size (void *q)
void epi_seir_compute (epi_state *state, tw_bf *bf, tw_lp *lp)
epi_agent * epi_getagent (int id)
void epi_agent_add (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_agent_remove (epi_state *, tw_bf *bf, tw_lp *lp)
void epi_agent_stage_tran (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_report_census_track ()
void epi_setup_options (int argc, char **argv)
void epi_init_scenario ()
void epi_md_opts ()
void epi_main (int argc, char **argv, char **env)
void epi_xml (epi_state *state, const xmlNodePtr node, tw_lp *lp)
void epi_md_final ()
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_rc_event_handler (epi_state *, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
void epi_stats_print ()
Variables
unsigned int g_epi_complete
unsigned int g_epi_hospital
double g_epi_psick
double g_epi_work_while_sick_p
unsigned int g_epi_nagents
unsigned int g_epi_nsick
unsigned int g_epi_nstages
epi_ic_stage * g_epi_stages
char * g_epi_ic_fn
char * g_epi_position_fn
FILE * g_epi_position_f
FILE * g_epi_log_f
FILE * g_epi_hospital_f
epi_statistics * g_epi_stats
unsigned int ** g_epi_ct
unsigned int g_epi_nct
unsigned int g_epi_day
double g_epi_worried_well_rate
double g_epi_worried_well_threshold
unsigned int g_epi_worried_well_duration
int g_epi_mod
int g_epi_stay_home
int g_epi_nreport_days
int * g_epi_report_days
int g_epi_next_report_day
tw_fd g_epi_fd
double EPSILON
Function Documentation
void epi_agent_add (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 112 of file epi-agent.c.
void epi_agent_remove (epi_state * , tw_bf * bf, tw_lp * lp)
Definition at line 195 of file epi-agent.c.
void epi_agent_stage_tran (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 20 of file epi-agent.c.
void epi_event_handler (epi_state * state, tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 44 of file epi.c.
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 121 of file epi.c.
epi_agent* epi_getagent (int id)
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file epi.c.
void epi_init_scenario ()
Definition at line 225 of file epi-init.c.
Referenced by epi_main().
void epi_location_timer (epi_state * , tw_lp * lp)
Definition at line 4 of file epi-timer.c.
Referenced by epi_event_handler(), and epi_init().
void epi_main (int argc, char ** argv, char ** env)
Definition at line 14 of file epi-main.c.
void epi_md_final ()
Definition at line 26 of file epi-main.c.
void epi_md_opts ()
Definition at line 4 of file epi-main.c.
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 21 of file epi-num.c.
Referenced by epi_agent_add_back(), and epi_event_handler().
void epi_num_check_report (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-num.c.
References epi_agent::num, epi_state::pq, pq_top(), rn_event_direct(), rn_event_send(), rn_message::ttl, tw_error(), tw_event_data(), and TW_LOC.
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 63 of file epi-num.c.
Referenced by epi_agent_remove(), and epi_event_handler().
void epi_rc_event_handler (epi_state * , tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 110 of file epi.c.
void epi_report_census_track ()
void epi_report_census_tract ()
Definition at line 29 of file epi-report.c.
Referenced by epi_event_handler(), and epi_final().
void epi_seir_compute (epi_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 18 of file epi-seir.c.
References epi_agent::ct, delta_t, EPI_SUSCEPTIBLE, g_epi_ct, g_epi_stages, tw_lp::id, epi_state::last_event, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_state::pq, pq_get_size(), pq_next(), tw_lp::rng, s, epi_statistics::s_nchecked, epi_statistics::s_ndraws, epi_agent::stage, epi_ic_stage::start_multiplier, epi_state::stats, epi_ic_stage::stop_multiplier, epi_agent::ts_stage_tran, tw_now(), tw_rand_geometric(), and tw_rand_unif.
Referenced by epi_event_handler().
void epi_setup_options (int argc, char ** argv)
Definition at line 30 of file epi-setup.c.
Referenced by epi_main().
void epi_stats_print ()
Definition at line 4 of file epi-stats.c.
Referenced by epi_md_final().
void epi_xml (epi_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 8 of file epi-xml.c.
void* pq_create (void)
Definition at line 159 of file queue-heap.c.
Referenced by epi_init_agent(), epi_init_agent_default(), and epi_xml().
void pq_delete_any (void * pq, epi_agent **)
Definition at line 133 of file queue-heap.c.
Referenced by epi_init(), and pq_cleanup().
void* pq_dequeue (void * pq)
Definition at line 101 of file queue-heap.c.
Referenced by epi_agent_remove(), and epi_agent_stage_tran().
void pq_enqueue (void * pq, epi_agent *)
Definition at line 78 of file queue-heap.c.
Referenced by agent_stage_tran(), epi_agent_add(), epi_agent_add_back(), epi_agent_remove(), epi_agent_stage_tran(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_xml(), and pq_cleanup().
unsigned int pq_get_size (void * q)
Definition at line 197 of file queue-heap.c.
Referenced by epi_agent_add(), epi_event_handler(), epi_init(), epi_seir_compute(), and pq_cleanup().
unsigned int pq_max_size (void * q)
tw_stime pq_minimum (void * pq)
Definition at line 174 of file queue-heap.c.
Referenced by pq_cleanup().
void* pq_next (void * pq, int next)
Definition at line 192 of file queue-heap.c.
Referenced by epi_init(), epi_seir_compute(), and pq_cleanup().
void* pq_top (void * pq)
Definition at line 183 of file queue-heap.c.
Referenced by epi_agent_remove(), epi_init(), epi_location_timer(), epi_num_check_report(), and timer_helper().
Variable Documentation
double EPSILON
Definition at line 40 of file epi-global.c.
Referenced by agent_stage_tran(), epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_event_handler(), epi_init_disease(), epi_init_disease_default(), epi_seir_compute(), epi_xml(), and init_ic_stages_from_file().
unsigned int g_epi_complete
Definition at line 25 of file epi-global.c.
Referenced by epi_event_handler(), and epi_report_census_tract().
unsigned int** g_epi_ct
Definition at line 20 of file epi-global.c.
Referenced by epi_agent_stage_tran(), epi_report_census_tract(), epi_seir_compute(), and epi_xml().
unsigned int g_epi_day
Definition at line 22 of file epi-global.c.
Referenced by epi_event_handler(), epi_final(), and epi_report_census_tract().
tw_fd g_epi_fd
Definition at line 37 of file epi-global.c.
Referenced by epi_agent_send(), epi_init_agent_default(), epi_timer_cancel(), and main().
unsigned int g_epi_hospital
Definition at line 6 of file epi-global.c.
Referenced by agent_stage_tran(), epi_agent_stage_tran(), epi_init(), epi_init_hospital(), epi_report_census_tract(), and epi_report_hospitals().
FILE* g_epi_hospital_f
Definition at line 14 of file epi-global.c.
Referenced by epi_init(), epi_init_hospital(), epi_report_census_tract(), epi_report_hospitals(), and epi_setup_options().
char* g_epi_ic_fn
Definition at line 10 of file epi-global.c.
Referenced by epi_disease_init(), epi_init_disease(), epi_init_scenario(), epi_setup_options(), and init_ic_stages_from_file().
FILE* g_epi_log_f
Definition at line 13 of file epi-global.c.
Referenced by epi_init_disease(), epi_init_disease_default(), epi_main(), epi_md_final(), epi_model_final(), epi_report_census_tract(), and epi_setup_options().
int g_epi_mod
Definition at line 23 of file epi-global.c.
Referenced by epi_num_add(), and epi_setup_options().
unsigned int g_epi_nagents
Definition at line 18 of file epi-global.c.
Referenced by epi_init_agent(), epi_init_agent_default(), epi_md_final(), epi_model_final(), epi_xml(), and main().
unsigned int g_epi_nct
Definition at line 21 of file epi-global.c.
Referenced by epi_report_census_tract(), and epi_xml().
int g_epi_next_report_day
Definition at line 35 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
int g_epi_nreport_days
Definition at line 33 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
unsigned int g_epi_nsick
Definition at line 19 of file epi-global.c.
Referenced by epi_md_final(), epi_setup_options(), and epi_xml().
unsigned int g_epi_nstages
Definition at line 24 of file epi-global.c.
Referenced by epi_agent_stage_tran(), epi_report_census_tract(), epi_xml(), and init_ic_stages_from_file().
FILE* g_epi_position_f
Definition at line 12 of file epi-global.c.
Referenced by epi_seir_compute(), and epi_setup_options().
char* g_epi_position_fn
Definition at line 11 of file epi-global.c.
Referenced by epi_setup_options().
double g_epi_psick
Definition at line 16 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
int* g_epi_report_days
Definition at line 34 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
epi_ic_stage* g_epi_stages
Definition at line 31 of file epi-global.c.
Referenced by epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_seir_compute(), epi_xml(), init_default_ic_stages(), and init_ic_stages_from_file().
epi_statistics* g_epi_stats
Definition at line 8 of file epi-global.c.
Referenced by epi_disease_init(), epi_final(), epi_main(), epi_model_final(), and epi_stats_print().
int g_epi_stay_home
Definition at line 27 of file epi-global.c.
Referenced by epi_agent_remove(), and epi_setup_options().
double g_epi_work_while_sick_p
Definition at line 17 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
unsigned int g_epi_worried_well_duration
Definition at line 30 of file epi-global.c.
Referenced by epi_agent_add(), and epi_setup_options().
double g_epi_worried_well_rate
Definition at line 28 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
double g_epi_worried_well_threshold
Definition at line 29 of file epi-global.c.
Referenced by epi_agent_add(), and epi_setup_options().