ROSS: rnf/modules/network/ip/ip-rc-downstream.c File Reference
ip-rc-downstream.c File Reference
#include <ip.h>
Functions
rn_link * rc_getroute (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_downstream (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_rc_downstream (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 42 of file ip-rc-downstream.c.
References rn_link::addr, tw_bf::c31, DOWNSTREAM, g_ip_fd, g_ip_header, ip_rc_packet_drop(), ip_message::last_sent, rn_link::last_sent, ip_message::link, ip_state::link_q, rc_getroute(), rn_reverse_event_send(), ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::size, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_alloc_rc(), tw_memoryq_pop(), and tw_now().
Referenced by ip_rc_event_handler().
rn_link* rc_getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 20 of file ip-rc-downstream.c.
References rn_message::dst, tw_lp::gid, ip_route(), rn_machine::link, rn_machine::nlinks, rn_getlink(), rn_getmachine(), and rn_message::src.
Referenced by ip_rc_downstream().