ROSS: rnf/modules/transport/tcp/tcp.c File Reference
tcp.c File Reference
#include <tcp.h>
Functions
void stop_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void start_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_init (tcp_state *state, tw_lp *lp)
void tcp_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_rc_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_final (tcp_state *state, tw_lp *lp)
Function Documentation
void start_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 25 of file tcp.c.
References tcp_state::connection, tcp_state::cwnd, rn_message::dst, g_tcp_fd, g_tw_rng_default, g_tw_ts_end, tw_lp::gid, tcp_state::len, tcp_state::mss, tw_event::recv_ts, rn_timer_init(), tw_lp::rng, tcp_state::rto, tcp_state::rtt_seq, tcp_state::rtt_time, tcp_statistics::sent, tcp_state::seq_num, tcp_message::seq_num, rn_message::size, tcp_message::src, rn_message::src, tcp_state::ssthresh, tcp_state::stats, tcp_event_send(), TCP_MTU, TCP_SND_WND, tcp_state::timer, tw_error(), TW_FALSE, TW_LOC, tw_memory_alloc(), tw_now(), tw_rand_init_streams(), tw_rand_integer(), tw_rand_unif, and tcp_state::unack.
void stop_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 4 of file tcp.c.
References g_tcp_fd, tw_lp::gid, tcp_state::len, rn_timer_cancel(), tcp_state::timer, tw_memory_free(), tw_now(), and tcp_state::unack.
void tcp_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 118 of file tcp.c.
References tcp_state::connection, tw_pe::cur_event, DOWNSTREAM, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::RC, rn_message::size, tcp_message::src, start_transfer(), stop_transfer(), tcp_process_ack(), tcp_process_data(), tcp_timeout(), TIMER, tw_error(), TW_LOC, tw_memory_free(), tw_now(), and rn_message::type.
void tcp_final (tcp_state * state, tw_lp * lp)
Definition at line 207 of file tcp.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_state::connection, tcp_state::cwnd, tcp_statistics::dropped_packets, tcp_statistics::final_time, g_rn_logs_dir, g_tcp_stats, tw_lp::gid, tw_lp::id, tcp_state::len, tcp_statistics::recv, rn_getmachine(), tcp_statistics::sent, tcp_statistics::start_time, tcp_state::stats, tcp_statistics::throughput, tcp_statistics::tout, and tw_now().
void tcp_init (tcp_state * state, tw_lp * lp)
Definition at line 84 of file tcp.c.
References rn_machine::conn, tcp_state::connection, tcp_state::cwnd, g_state, g_tcp_mss, g_tcp_rwd, tw_lp::gid, tw_lp::id, tcp_state::len, tcp_state::mss, tcp_state::recv_wnd, rn_getmachine(), tcp_state::rto, rn_message::size, tcp_state::ssthresh, start_transfer(), tcp_state::stats, TCP_SND_WND, tw_calloc(), TW_LOC, and tcp_state::unack.
void tcp_rc_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 167 of file tcp.c.
References tcp_state::connection, tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::src, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), TIMER, tw_error(), TW_LOC, tw_memory_free_rc(), tw_now(), and rn_message::type.