ROSS: rnf/modules/network/ip/ip-routing.c File Reference
ip-routing.c File Reference
#include <ip.h>
Macros
#define IP_RT_DEBUG 0
#define IP_RT_BINARY 0
Functions
int routing_init_ft_write (rn_machine *m)
rn_link * ip_route (rn_machine *me, rn_message *msg)
int routing_read ()
void routing_write ()
void ip_routing_init ()
void routing_init_ft_read (ip_state *state, tw_lp *lp)
Variables
int * frontier
int * solution
int * previous
unsigned int * distance
Macro Definition Documentation
#define IP_RT_BINARY 0
Definition at line 4 of file ip-routing.c.
#define IP_RT_DEBUG 0
Definition at line 3 of file ip-routing.c.
Function Documentation
rn_link* ip_route (rn_machine * me, rn_message * msg)
Definition at line 9 of file ip-routing.c.
void ip_routing_init ()
Definition at line 125 of file ip-routing.c.
void routing_init_ft_read (ip_state * state, tw_lp * lp)
Definition at line 132 of file ip-routing.c.
References rn_subnet::area, c_host, rn_machine::ft, g_ip_routing_file, rn_area::g_ospf_nlsa, tw_lp::gid, rn_getmachine(), rn_machine::subnet, tw_error(), TW_LOC, and rn_machine::type.
Referenced by ip_routing_init_ft().
int routing_init_ft_write (rn_machine * m)
Definition at line 179 of file ip-routing.c.
References rn_link::addr, c_host, rn_machine::conn, distance, frontier, g_ip_routing_file, g_rn_nmachines, g_rn_ttl, rn_machine::id, rn_machine::link, previous, rn_getmachine(), solution, tw_calloc(), TW_LOC, rn_machine::type, and rn_link::wire.
Referenced by ip_routing_init_ft(), and routing_write().
int routing_read ()
Definition at line 24 of file ip-routing.c.
References g_ip_routing_file, g_ip_rt, g_rn_nmachines, g_rn_tools_dir, tw_calloc(), tw_error(), and TW_LOC.
Referenced by ip_routing_init(), and routing_write().
void routing_write ()
Definition at line 75 of file ip-routing.c.
References g_ip_routing_file, g_rn_machines, g_rn_nmachines, g_rn_tools_dir, rn_getmachine(), routing_init_ft_write(), routing_read(), tw_error(), tw_ismaster(), and TW_LOC.
Referenced by ip_routing_init().
Variable Documentation
unsigned int* distance
Definition at line 176 of file ip-routing.c.
Referenced by calcRxPower(), DoCalcRxPower(), main(), olsr_change_region(), olsr_departure_from_mpr(), olsr_region_init(), and routing_init_ft_write().
int* frontier
Definition at line 172 of file ip-routing.c.
Referenced by routing_init_ft_write().
int* previous
Definition at line 174 of file ip-routing.c.
Referenced by routing_init_ft_write().
int* solution
Definition at line 173 of file ip-routing.c.
Referenced by routing_init_ft_write().