ROSS: rnf/modules/application/epi/save/epi-xml.c File Reference
epi-xml.c File Reference
#include <epi.h>
Functions
void epi_xml (epi_state *state, const xmlNodePtr node, tw_lp *lp)
Function Documentation
void epi_xml (epi_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 8 of file epi-xml.c.
References epi_agent::a_type, epi_agent::behavior_flags, epi_agent::ct, epi_agent::curr, epi_agent::dur, EPI_INCUBATING, EPI_SUSCEPTIBLE, EPSILON, g_epi_ct, g_epi_nagents, g_epi_nct, g_epi_nsick, g_epi_nstages, g_epi_psick, g_epi_stages, g_epi_work_while_sick_p, g_epi_worried_well_rate, epi_agent::id, rn_subnet::id, tw_lp::id, epi_agent::loc, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_agent::n_infected, epi_agent::nloc, rn_area::nsubnets, epi_agent::num, epi_state::pq, pq_create(), pq_enqueue(), rn_getarea(), rn_getmachine(), rn_getsubnet(), tw_lp::rng, s, epi_agent::stage, epi_ic_stage::stage_index, epi_state::stats, rn_area::subnets, epi_agent::ts_infected, epi_agent::ts_last_tran, epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_calloc(), tw_error(), tw_getlp(), TW_LOC, tw_rand_integer(), tw_rand_unif, rn_machine::uid, x, and xml_getprop().