ROSS: rnf/modules/network/ip/ip-extern.h File Reference
ip-extern.h File Reference
Functions
void ip_init (ip_state *, tw_lp *)
void ip_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_final (ip_state *state, tw_lp *lp)
void ip_upstream (ip_state *, rn_message *, tw_lp *lp)
void ip_rc_upstream (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_downstream_forward (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_downstream (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_routing_init ()
void ip_rt_print (ip_state *state, tw_lp *lp, FILE *log)
rn_link * ip_route (rn_machine *me, rn_message *msg)
tw_lpid ip_getroute (ip_state *state, tw_lpid dst)
void ip_xml (tw_lp *lp, xmlNodePtr node)
void ip_md_opts ()
void ip_md_init (int argc, char **argv, char **env)
void ip_md_final ()
Variables
tw_stime g_ip_major_interval
tw_stime g_ip_minor_interval
ip_stats * g_ip_stats
int g_ip_header
tw_fd g_ip_fd
int g_ip_routing_simple
FILE * g_ip_log
FILE * g_ip_routing_file
int ** g_ip_rt
unsigned int g_ip_log_on
short int * g_ip_front
short int * g_ip_p
short int * g_ip_f
short int * g_ip_s
short int * g_ip_d
Function Documentation
void ip_downstream_forward (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 97 of file ip-downstream.c.
void ip_downstream_source (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 86 of file ip-downstream.c.
void ip_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 27 of file ip.c.
void ip_final (ip_state * state, tw_lp * lp)
Definition at line 74 of file ip.c.
tw_lpid ip_getroute (ip_state * state, tw_lpid dst)
void ip_init (ip_state * , tw_lp *)
Definition at line 7 of file ip.c.
void ip_md_final ()
Definition at line 53 of file ip-model.c.
Referenced by main().
void ip_md_init (int argc, char ** argv, char ** env)
Definition at line 17 of file ip-model.c.
void ip_md_opts ()
Definition at line 11 of file ip-model.c.
References tw_opt_add().
void ip_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-packet.c.
Referenced by getroute(), and ip_downstream_forward().
void ip_rc_downstream (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 42 of file ip-rc-downstream.c.
References rn_link::addr, tw_bf::c31, DOWNSTREAM, g_ip_fd, g_ip_header, ip_rc_packet_drop(), ip_message::last_sent, rn_link::last_sent, ip_message::link, ip_state::link_q, rc_getroute(), rn_reverse_event_send(), ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::size, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_alloc_rc(), tw_memoryq_pop(), and tw_now().
Referenced by ip_rc_event_handler().
void ip_rc_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 46 of file ip.c.
void ip_rc_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 26 of file ip-packet.c.
Referenced by ip_rc_downstream(), ip_rc_event_handler(), and rc_getroute().
void ip_rc_upstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 23 of file ip-upstream.c.
Referenced by ip_rc_event_handler().
rn_link* ip_route (rn_machine * me, rn_message * msg)
Definition at line 9 of file ip-routing.c.
Referenced by getroute(), and rc_getroute().
void ip_routing_init ()
Definition at line 125 of file ip-routing.c.
Referenced by ip_md_init(), and ip_setup_options().
void ip_rt_print (ip_state * state, tw_lp * lp, FILE * log)
Definition at line 50 of file ip-routing.c.
Referenced by routing_init_ft_write().
void ip_upstream (ip_state * , rn_message * , tw_lp * lp)
Definition at line 4 of file ip-upstream.c.
Referenced by ip_event_handler().
void ip_xml (tw_lp * lp, xmlNodePtr node)
Definition at line 4 of file ip-xml.c.
Variable Documentation
short int* g_ip_d
Definition at line 34 of file ip-global.c.
short int* g_ip_f
Definition at line 32 of file ip-global.c.
tw_fd g_ip_fd
Definition at line 14 of file ip-global.c.
Referenced by forward(), ip_event_handler(), ip_main(), ip_md_init(), ip_rc_downstream(), and ip_rc_event_handler().
short int* g_ip_front
Definition at line 30 of file ip-global.c.
int g_ip_header
Definition at line 12 of file ip-global.c.
Referenced by ip_downstream_source(), ip_rc_downstream(), ip_rc_event_handler(), ip_rc_upstream(), and ip_upstream().
FILE* g_ip_log
Definition at line 20 of file ip-global.c.
Referenced by ip_event_handler(), and ip_md_init().
unsigned int g_ip_log_on
Definition at line 25 of file ip-global.c.
Referenced by ip_event_handler(), and ip_md_init().
tw_stime g_ip_major_interval
Definition at line 23 of file ip-global.c.
Referenced by ip_event_handler(), ip_init(), and ip_md_init().
tw_stime g_ip_minor_interval
Definition at line 24 of file ip-global.c.
Referenced by ip_event_handler(), ip_init(), and ip_md_init().
short int* g_ip_p
Definition at line 31 of file ip-global.c.
FILE* g_ip_routing_file
Definition at line 17 of file ip-global.c.
Referenced by routing_init_ft_read(), routing_init_ft_write(), routing_read(), and routing_write().
int g_ip_routing_simple
Definition at line 15 of file ip-global.c.
Referenced by ip_lp_init(), and ip_setup_options().
int** g_ip_rt
Definition at line 18 of file ip-global.c.
Referenced by ip_route(), and routing_read().
short int* g_ip_s
Definition at line 33 of file ip-global.c.
ip_stats* g_ip_stats
Definition at line 11 of file ip-global.c.
Referenced by ip_final(), ip_lp_final(), ip_main(), ip_md_final(), and ip_md_init().