ROSS: rnf/modules/application/epi/save/epi-agent.c File Reference
epi-agent.c File Reference
#include <epi.h>
Functions
void timer_helper (epi_state *state, tw_lp *lp)
void epi_agent_stage_tran (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_agent_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_agent_add_back (epi_state *state, tw_lp *lp, epi_agent *a)
int epi_agent_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
Function Documentation
void epi_agent_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 124 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::curr, epi_agent::days_remaining, epi_agent::dur, EPI_AGENT_WORRIED_WELL, EPSILON, g_epi_stages, g_epi_worried_well_duration, g_epi_worried_well_threshold, epi_agent::id, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::max_queue_size, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_enqueue(), pq_get_size(), epi_agent::stage, timer_helper(), epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_error(), TW_LOC, and tw_now().
void epi_agent_add_back (epi_state * state, tw_lp * lp, epi_agent * a)
Definition at line 179 of file epi-agent.c.
References epi_agent::curr, epi_agent::dur, epi_num_add(), epi_agent::nloc, epi_state::pq, pq_enqueue(), timer_helper(), epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, and tw_now().
int epi_agent_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 216 of file epi-agent.c.
References epi_agent::curr, epi_agent::days_remaining, epi_agent::e_type, EPI_ADD, epi_agent_add_back(), EPSILON, g_epi_stages, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_dequeue(), rn_event_direct(), rn_event_send(), epi_statistics::s_move_ev, epi_agent::stage, epi_state::stats, timer_helper(), tw_error(), tw_getlp(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
void epi_agent_stage_tran (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 44 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::ct, epi_agent::days_remaining, EPI_AGENT_WORK_WHILE_SICK, EPI_AGENT_WORRIED_WELL, EPSILON, g_epi_ct, g_epi_hospital, g_epi_nstages, g_epi_stages, tw_lp::id, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_state::ncontagious, epi_state::pq, pq_dequeue(), pq_enqueue(), tw_lp::rng, s, epi_statistics::s_ndead, epi_statistics::s_ninfected, epi_agent::stage, epi_state::stats, timer_helper(), epi_agent::ts_last_tran, epi_agent::ts_next, epi_agent::ts_remove, epi_agent::ts_stage_tran, tw_error(), TW_LOC, tw_now(), tw_rand_unif, and TWENTY_FOUR_HOURS.
void timer_helper (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-agent.c.
References epi_agent::e_type, EPI_REMOVE, EPI_STAGE_TRANSITION, epi_timer_start(), epi_state::pq, pq_top(), epi_state::tmr_remove, epi_agent::ts_remove, and epi_agent::ts_stage_tran.
Referenced by epi_agent_add(), epi_agent_add_back(), epi_agent_remove(), and epi_agent_stage_tran().