ROSS: ross/models/rng/rng.c File Reference
rng.c File Reference
#include "ross.h"
Data Structures
struct message
struct state
Macros
#define rng_main main
Functions
void rngt_init (state *s, tw_lp *lp)
void rngt_event (state *s, tw_bf *bf, message *m, tw_lp *lp)
void rngt_final (state *s, tw_lp *lp)
tw_peid rngt_map (tw_lpid gid)
int main (int argc, char *argv[])
Variables
FILE * rng_event_log
tw_lptype rng_lps []
Macro Definition Documentation
#define rng_main main
Definition at line 52 of file rng.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 54 of file rng.c.
References g_tw_nlp, rng_event_log, tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), and tw_run().
void rngt_event (state * s, tw_bf * bf, message * m, tw_lp * lp)
Definition at line 20 of file rng.c.
References tw_lp::rng, rng_event_log, and tw_rand_unif.
void rngt_final (state * s, tw_lp * lp)
Definition at line 31 of file rng.c.
void rngt_init (state * s, tw_lp * lp)
Definition at line 11 of file rng.c.
References tw_lp::gid, tw_event_new(), and tw_event_send().
tw_peid rngt_map (tw_lpid gid)
Definition at line 35 of file rng.c.
References g_tw_nlp.
Variable Documentation
FILE* rng_event_log
Definition at line 3 of file rng.c.
Referenced by main(), and rngt_event().
tw_lptype rng_lps[]
Initial value:
= {
    {
        (init_f) rngt_init,
        (event_f) rngt_event,
        (revent_f) 0,
        (final_f) rngt_final,
        (map_f) rngt_map,
        sizeof(state)
    },
    { 0 },
}
Definition at line 40 of file rng.c.