ROSS: ross/models/tcp/tcp-host.c File Reference
tcp-host.c File Reference
#include "tcp.h"
Functions
void tcp_host_startup (Host_State *SV, tw_lp *lp)
void tcp_host_process (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_ack (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_data (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_update_cwnd (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_update_rtt (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_timeout (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_EventHandler (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_Statistics_CollectStats (Host_State *SV, tw_lp *lp)
Function Documentation
void tcp_host_EventHandler (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 593 of file tcp-host.c.
References RC::cwnd, FORWARD, tw_lp::id, Msg_Data::MethodName, Msg_Data::RC, RTO, tcp_host_process(), tcp_host_timeout(), tw_error(), tw_exit(), TW_LOC, and tw_now().
void tcp_host_process (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 100 of file tcp-host.c.
References tw_bf::c10, tw_bf::c11, Host_State::connection, g_hosts_info, g_routers, tw_lp::id, Msg_Data::source, tcp_host_process_ack(), tcp_host_process_data(), and Host_Info::type.
Referenced by tcp_host_EventHandler().
void tcp_host_process_ack (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 132 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c9, RC::cwnd, Host_State::cwnd, Host_Link::delay, Msg_Data::dest, RC::dup_count, Host_State::dup_count, FORWARD, g_frequency, g_hosts_links, g_iss, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_State::len, Host_Link::link_speed, min, Msg_Data::RC, tw_event::recv_ts, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, RC::seq_num, Msg_Data::seq_num, Msg_Data::source, Host_State::ssthresh, Host_State::start_time, tcp_host_update_cwnd(), tcp_host_update_rtt(), TCP_TRANSFER_SIZE, tcp_util_event(), RC::timer_seq, RC::timer_ts, tw_event_data(), tw_now(), tw_timer_reset(), and Host_State::unack.
void tcp_host_process_data (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 270 of file tcp-host.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, Host_Link::delay, RC::dup_count, FORWARD, g_hosts_info, g_hosts_links, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_Link::link_speed, max, Host_State::out_of_order, Msg_Data::RC, Host_State::received_packets, Host_State::seq_num, Msg_Data::seq_num, Msg_Data::source, TCP_HEADER_SIZE, TCP_SND_WND, TCP_TRANSFER_SIZE, tcp_util_event(), and tw_now().
void tcp_host_startup (Host_State * SV, tw_lp * lp)
Definition at line 13 of file tcp-host.c.
References Host_Info::connected, Host_State::connection, Host_State::cwnd, Host_Link::delay, Host_State::dev, Host_State::dup_count, FORWARD, g_frequency, g_hosts, g_hosts_info, g_hosts_links, g_mss, g_recv_wnd, g_routers, tw_lp::id, Host_State::lastsent, Host_State::len, Host_Link::link_speed, Msg_Data::MethodName, Host_State::out_of_order, Host_State::received_packets, tw_lp::rng, RTO, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, Host_State::rtt_seq, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, Msg_Data::seq_num, Host_Info::size, Host_State::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, Host_State::start_time, TCP_SND_WND, TCP_TRANSFER_SIZE, tcp_util_event(), Host_State::timedout_packets, tw_event_data(), tw_rand_exponential(), tw_rand_integer(), tw_timer_init(), and Host_State::unack.
void tcp_host_Statistics_CollectStats (Host_State * SV, tw_lp * lp)
Definition at line 627 of file tcp-host.c.
References g_frequency, Host_State::received_packets, Host_State::sent_packets, Host_State::start_time, Host_State::timedout_packets, tw_now(), TWAppStats, and Host_State::unack.
void tcp_host_timeout (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 512 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c1, tw_bf::c13, RC::cwnd, Host_State::cwnd, Msg_Data::dest, RC::dup_count, FORWARD, g_hosts_links, g_iss, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_State::len, Host_Link::link_speed, Msg_Data::MethodName, min, Msg_Data::RC, RTO, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, RC::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, TCP_TRANSFER_SIZE, tcp_util_event(), Host_State::timedout_packets, tw_event_data(), tw_now(), tw_timer_init(), and Host_State::unack.
void tcp_host_update_cwnd (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 377 of file tcp-host.c.
References tw_bf::c3, tw_bf::c4, RC::cwnd, Host_State::cwnd, g_mss, g_recv_wnd, g_routers, tw_lp::id, Msg_Data::RC, Host_State::ssthresh, TCP_SND_WND, and tw_now().
void tcp_host_update_rtt (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 405 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c5, tw_bf::c6, tw_bf::c7, Msg_Data::dest, Host_State::dev, RC::dev, g_frequency, g_routers, tw_lp::id, Host_State::len, Msg_Data::RC, tw_event::recv_ts, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, RC::timer_seq, RC::timer_ts, tw_event_data(), tw_now(), tw_timer_reset(), and Host_State::unack.