ROSS: ross/ross-kernel-inline.h File Reference
ross-kernel-inline.h File Reference
Macros
#define TW_TRUE 1
#define TW_FALSE 0
#define max(a, b) ((a) > (b) ? (a) : (b))
#define min(a, b) ((a) < (b) ? (a) : (b))
Functions
static tw_lp * tw_getlocal_lp (tw_lpid gid)
static tw_lp * tw_getlp (tw_lpid id)
static tw_kp * tw_getkp (tw_kpid id)
static tw_pe * tw_getpe (tw_peid id)
static int tw_ismaster (void)
static void * tw_getstate (tw_lp *lp)
static tw_stime tw_now (tw_lp *lp)
Macro Definition Documentation
#define max (a, b) ((a) > (b) ? (a) : (b))
Definition at line 7 of file ross-kernel-inline.h.
Referenced by Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), credit_send(), event_handler(), ip_event_handler(), ip_final(), ip_lp_final(), ip_rc_upstream(), ip_upstream(), mpi_msg_send(), olsr_event(), ospf_statistics_collection(), packet_arrive(), packet_send(), router_credit_send(), router_packet_send(), tcp_host_process_data(), tw_eventq_alloc(), tw_memory_allocate(), tw_net_statistics(), and tw_stats().
#define min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 8 of file ross-kernel-inline.h.
Referenced by epi_agent_update_ts(), epi_init(), event_cancel(), gvt_print(), olsr_station_to_mpr(), ospf_aging_timer(), ospf_db_init(), recv_finish(), rm_grid_init(), tcp_host_process_ack(), tcp_host_timeout(), tcp_layer_process_ack(), tcp_layer_timeout(), tcp_process_ack(), tcp_timeout(), tcp_update_rtt(), tlm_grid_init(), tw_event_send(), tw_gvt_compute(), tw_gvt_step2(), tw_net_gvt_compute(), and tw_net_read().
#define TW_FALSE 0
Definition at line 5 of file ross-kernel-inline.h.
Referenced by bgp_decision(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_keepalive_timer(), bgp_mrai_timer(), bgp_route_equals(), bgp_route_inpath(), bgp_update_all(), bgp_update_send(), bgp_xml(), can_be_removed(), deal_with_timed_out_routers(), epi_init_disease(), init_default_ic_stages(), init_ic_stages_from_file(), init_rib(), main(), ospf_list_contains(), ospf_lsa_create(), ospf_lsa_equals(), process_lsa_recv(), rm_initialize(), start_transfer(), update_add(), and update_withdraw().
#define TW_TRUE 1
Definition at line 4 of file ross-kernel-inline.h.
Referenced by bgp_decision(), bgp_init(), bgp_keepalive(), bgp_route_add(), bgp_route_equals(), bgp_route_inpath(), bgp_xml(), can_be_removed(), deal_with_timed_out_routers(), epi_init_disease(), init_default_ic_stages(), init_ic_stages_from_file(), ospf_aging_timer(), ospf_list_contains(), ospf_lsa_create(), ospf_lsa_equals(), r_deal_with_timed_out_bgp_routers(), tw_define_lps(), tw_pe_init(), update_add(), and update_withdraw().
Function Documentation
static tw_kp* tw_getkp (tw_kpid id) inline static
Definition at line 43 of file ross-kernel-inline.h.
References g_tw_kp, g_tw_nkp, tw_error(), and TW_LOC.
Referenced by ip_main(), ip_md_init(), late_sanity_check(), main(), tcp_main(), tcp_md_init(), tw_init_kps(), tw_pe_fossil_collect(), and tw_stats().
static tw_lp* tw_getlocal_lp (tw_lpid gid) inline static
Definition at line 11 of file ross-kernel-inline.h.
References g_tw_custom_lp_global_to_local_map, g_tw_lp, g_tw_lp_offset, g_tw_nlp, tw_error(), and TW_LOC.
Referenced by ForwardDefault(), olsr_event(), recv_finish(), rm_getlocation(), tlm_getlocation(), tw_event_send(), and tw_socket_read_event().
static tw_lp* tw_getlp (tw_lpid id) inline static
Definition at line 31 of file ross-kernel-inline.h.
References g_tw_lp, g_tw_nlp, tw_error(), and TW_LOC.
Referenced by Airport_EventHandler(), Application_Init(), Application_Next_Burst(), bgp_route_add(), CancelTimer(), epi_agent_remove(), epi_xml(), forward(), ForwardPktOnLink(), ftp_event_handler(), GmccRcvInitLayer(), GmccRcvJump(), GmccRcvLeave(), GmccRcvProcCtrlPkt(), GmccRcvProcDataPkt(), GmccRcvSendCiPkt(), GmccRcvStart(), GmccSrcPktHandler(), GmccSrcResetLayer(), GmccSrcSendCtrlPkt(), GmccSrcSendDataPkt(), GmccSrcStart(), GmccSrcStop(), GmccSrcTimer(), main(), OrmccRcvPktHandler(), OrmccRcvSendPkt(), OrmccSrcPktHandler(), OrmccSrcSendPkt(), OrmccSrcStart(), OrmccSrcStop(), OrmccSrcTimer(), OrmccSrcUpdateRtt(), PgmccRcvPktHandler(), PgmccRcvSendPkt(), PgmccSrcNakProc(), PgmccSrcSendPkt(), PgmccSrcStart(), ReadAgentAct(), ReadGroupOp(), ReschedTimer(), ReschedTimerWithSn(), ScheduleTimer(), ScheduleTimerWithSn(), tcp_layer_util_event(), tcp_util_nexthop(), TfmccRcvAddPktToHistory(), TfmccRcvPktHandler(), TfmccRcvSendPkt(), TfmccSrcDecrRate(), TfmccSrcIncrRate(), TfmccSrcPktHandler(), TfmccSrcSendPkt(), TfmccSrcSlowStart(), TfmccSrcStart(), TfmccSrcTimer(), and tw_stats().
static tw_pe* tw_getpe (tw_peid id) inline static
Definition at line 58 of file ross-kernel-inline.h.
References g_tw_npe, g_tw_pe, tw_error(), and TW_LOC.
Referenced by dragonfly_mapping(), main(), map_round_robin(), torus_mapping(), and tw_memory_init().
static void* tw_getstate (tw_lp * lp) inline static
Definition at line 89 of file ross-kernel-inline.h.
References tw_lp::cur_state.
static int tw_ismaster (void) inline static
Definition at line 83 of file ross-kernel-inline.h.
References g_tw_masternode, g_tw_mynode, and tw_node_eq().
Referenced by apply_opt(), epi_model_final(), ip_md_final(), ip_md_init(), main(), match_opt(), mem_stats_print(), need_argument(), rn_print_statistics(), rn_setup(), rn_xml_topology(), routing_write(), rp_md_final(), rp_md_init(), rw_md_final(), rw_md_init(), tcp_md_final(), tcp_md_init(), tlm_md_final(), tlm_md_init(), tw_end(), tw_init(), tw_opt_print(), and tw_stats().
static tw_stime tw_now (tw_lp * lp) inline static
Definition at line 95 of file ross-kernel-inline.h.
References tw_lp::kp, and tw_kp::last_time.
Referenced by _rm_event_handler(), AddDuplicate(), agent_stage_tran(), Application_Next_Burst(), Application_Recv(), bgp_event_handler(), bgp_keepalive(), bgp_mrai_tmr(), bgp_notify(), bgp_notify_send(), bgp_open_send(), bgp_timer_cancel(), bgp_timer_start(), bgp_update_send(), Cell_CompletionCall(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), change_direction(), credit_send(), deal_with_timed_out_routers(), disksim_event_handler(), epi_agent_add(), epi_agent_add_back(), epi_agent_remove(), epi_agent_send(), epi_agent_stage_tran(), epi_event_handler(), epi_num_add(), epi_seir_compute(), event_handler(), forward(), ForwardDefault(), ForwardPacket(), ForwardPktOnLink(), ftp_event_handler(), GmccRcvInitLayer(), GmccRcvJump(), GmccRcvLeave(), GmccRcvProcCtrlPkt(), GmccRcvProcDataPkt(), GmccRcvStart(), GmccSrcPktHandler(), GmccSrcSendCtrlPkt(), GmccSrcSendDataPkt(), GmccSrcStart(), GmccSrcTimer(), ip_event_handler(), ip_rc_downstream(), ip_rc_upstream(), ip_upstream(), Link_DeQueue(), Link_EnQueue(), mpi_event_rc_handler(), mpi_msg_recv(), mpi_msg_send(), node_rc_handler(), num_file_complete(), num_file_start(), num_file_stop(), num_final(), num_start(), num_timer_start(), num_update(), olsr_change_region(), olsr_event(), olsr_station_to_mpr(), olsr_station_to_mpr_rc(), OrmccRcvPktHandler(), OrmccRcvSendPkt(), OrmccSrcPktHandler(), OrmccSrcSendPkt(), OrmccSrcStart(), OrmccSrcTimer(), OrmccSrcUpdateRtt(), ospf_ack_direct(), ospf_aging_timer(), ospf_aging_timer_set(), ospf_db_update(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_event_handler(), ospf_h_send(), ospf_hello_packet(), ospf_lsa_age(), ospf_lsa_start_flood(), ospf_statistics_collection(), ospf_timer_cancel(), ospf_timer_start(), packet_arrive(), packet_finish(), packet_send(), PgmccSrcNakProc(), PgmccSrcSendPkt(), PgmccSrcStart(), pm_connection_print(), pm_move(), qhold_event(), r_deal_with_timed_out_bgp_routers(), raid_disk_eventhandler(), raid_server_eventhandler(), raid_server_init(), raid_server_num_blocks(), rm_cell_gather(), rm_cell_scatter(), rm_move2(), rm_particle_handler(), rm_rc_gather(), rm_rc_particle_handler(), rm_rc_scatter(), rn_event_handler(), rn_event_send(), rn_rc_event_handler(), rn_setup_links(), Router_Arrival(), router_credit_send(), router_event(), router_packet_send(), Router_Recv(), rp_move(), rw_move(), sa_master_event(), ScheduleTimer(), ScheduleTimerWithSn(), start_transfer(), stop_transfer(), tcp_event_handler(), tcp_event_send(), tcp_final(), tcp_host_EventHandler(), tcp_host_process_ack(), tcp_host_process_data(), tcp_host_Statistics_CollectStats(), tcp_host_timeout(), tcp_host_update_cwnd(), tcp_host_update_rtt(), tcp_layer_event_handler(), tcp_layer_final(), tcp_layer_process_ack(), tcp_layer_rc_event_handler(), tcp_layer_timeout(), tcp_layer_update_rtt(), tcp_lp_final(), tcp_process_ack(), tcp_rc_event_handler(), tcp_rc_process_ack(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_router_forward(), tcp_timeout(), tcp_timer_cancel(), tcp_update_rtt(), terminal_rc_event_handler(), TfmccRcvAddPktToHistory(), TfmccRcvPktHandler(), TfmccRcvSendPkt(), TfmccSrcDecrRate(), TfmccSrcIncrRate(), TfmccSrcPktHandler(), TfmccSrcSendPkt(), TfmccSrcSlowStart(), TfmccSrcStart(), TfmccSrcTimer(), tlm_cell_gather(), tlm_cell_scatter(), tlm_move2(), tlm_particle_handler(), tlm_rc_gather(), tlm_rc_particle_handler(), tlm_rc_scatter(), tmr_event_handler(), tmr_event_handler_rc(), tw_event_new(), tw_event_send(), and tw_memory_free().