ROSS: ross/models/tcp-ip/ip.c File Reference
ip.c File Reference
#include <ip.h>
Macros
#define VERIFY_IP 1
Functions
void ip_lp_init (ip_state *state, tw_lp *lp)
void ip_event_handler (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_rc_event_handler (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_lp_final (ip_state *state, tw_lp *lp)
Macro Definition Documentation
#define VERIFY_IP 1
Definition at line 3 of file ip.c.
Function Documentation
void ip_event_handler (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 19 of file ip.c.
References DOWNSTREAM, rn_message::dst, g_ip_fd, tw_lp::gid, tw_lp::id, ip_downstream_forward(), ip_downstream_source(), ip_upstream(), rn_message::src, tw_error(), TW_LOC, tw_memory_free(), and rn_message::type.
void ip_lp_final (ip_state * state, tw_lp * lp)
Definition at line 96 of file ip.c.
References g_ip_stats, max, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, and ip_state::stats.
void ip_lp_init (ip_state * state, tw_lp * lp)
Definition at line 9 of file ip.c.
References g_ip_routing_simple, ip_routing_init_ft(), ip_state::links, ip_state::nlinks, and ip_state::stats.
void ip_rc_event_handler (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 45 of file ip.c.
References DOWNSTREAM, rn_message::dst, g_ip_fd, g_ip_header, tw_lp::gid, tw_lp::id, ip_rc_downstream(), ip_rc_packet_drop(), ip_rc_upstream(), ip_link::last_sent, ip_message::rc_lastsent, ip_message::rc_link, ip_stats::s_ndropped_ttl, rn_message::size, rn_message::src, ip_state::stats, rn_message::ttl, tw_error(), TW_LOC, tw_memory_free_rc(), and rn_message::type.