ROSS: core/ross-random-internal.c File Reference
ross-random-internal.c File Reference
#include <ross.h>
Functions
tw_rng * tw_rand_init (uint32_t v, uint32_t w)
tw_rng * tw_rand_core_init (uint32_t v, uint32_t w)
long tw_rand_integer (tw_rng_stream *g, long low, long high)
unsigned long tw_rand_ulong (tw_rng_stream *g, unsigned long low, unsigned long high)
long tw_rand_binomial (tw_rng_stream *g, long N, double P)
double tw_rand_exponential (tw_rng_stream *g, double Lambda)
double tw_rand_pareto (tw_rng_stream *g, double shape, double scale)
double tw_rand_gamma (tw_rng_stream *g, double shape, double scale)
long tw_rand_geometric (tw_rng_stream *g, double P)
double tw_rand_normal01 (tw_rng_stream *g, unsigned int *rng_calls)
double tw_rand_normal_sd (tw_rng_stream *g, double Mu, double Sd, unsigned int *rng_calls)
long tw_rand_poisson (tw_rng_stream *g, double Lambda)
double tw_rand_lognormal (tw_rng_stream *g, double mean, double sd, unsigned int *rng_calls)
double tw_rand_weibull (tw_rng_stream *g, double mean, double shape)
Function Documentation
tw_rand_binomial()
long tw_rand_binomial (tw_rng_stream * g, long N, double P)
Definition at line 62 of file ross-random-internal.c.
References tw_rand_unif.
tw_rand_core_init()
tw_rng * tw_rand_core_init (uint32_t v, uint32_t w)
Definition at line 16 of file ross-random-internal.c.
References rng_core_init().
Referenced by tw_pe_init().
tw_rand_exponential()
double tw_rand_exponential (tw_rng_stream * g, double Lambda)
Definition at line 78 of file ross-random-internal.c.
References tw_rand_unif.
Referenced by phold_event_handler(), phold_init(), phold_pre_run(), and tw_rand_gamma().
tw_rand_gamma()
double tw_rand_gamma (tw_rng_stream * g, double shape, double scale)
Definition at line 90 of file ross-random-internal.c.
References tw_rand_exponential(), and tw_rand_unif.
tw_rand_geometric()
long tw_rand_geometric (tw_rng_stream * g, double P)
Definition at line 150 of file ross-random-internal.c.
References tw_rand_unif.
tw_rand_init()
tw_rng * tw_rand_init (uint32_t v, uint32_t w)
Definition at line 7 of file ross-random-internal.c.
References rng_init().
Referenced by tw_pe_init().
tw_rand_integer()
long tw_rand_integer (tw_rng_stream * g, long low, long high)
NOTE: Don't pass negative values to low!
Definition at line 30 of file ross-random-internal.c.
References tw_rand_unif.
Referenced by phold_event_handler(), and phold_pre_run().
tw_rand_lognormal()
double tw_rand_lognormal (tw_rng_stream * g, double mean, double sd, unsigned int * rng_calls)
Definition at line 218 of file ross-random-internal.c.
References mean, and tw_rand_normal01().
tw_rand_normal01()
double tw_rand_normal01 (tw_rng_stream * g, unsigned int * rng_calls)
Definition at line 161 of file ross-random-internal.c.
References tw_error(), TW_LOC, tw_rng_stream::tw_normal_flipflop, tw_rng_stream::tw_normal_u1, tw_rng_stream::tw_normal_u2, tw_opi, and tw_rand_unif.
Referenced by tw_rand_lognormal(), and tw_rand_normal_sd().
tw_rand_normal_sd()
double tw_rand_normal_sd (tw_rng_stream * g, double Mu, double Sd, unsigned int * rng_calls)
Definition at line 191 of file ross-random-internal.c.
References tw_rand_normal01().
tw_rand_pareto()
double tw_rand_pareto (tw_rng_stream * g, double shape, double scale)
Definition at line 84 of file ross-random-internal.c.
References tw_rand_unif.
tw_rand_poisson()
long tw_rand_poisson (tw_rng_stream * g, double Lambda)
Definition at line 197 of file ross-random-internal.c.
References tw_rand_unif.
tw_rand_ulong()
unsigned long tw_rand_ulong (tw_rng_stream * g, unsigned long low, unsigned long high)
Definition at line 46 of file ross-random-internal.c.
References tw_rand_unif.
tw_rand_weibull()
double tw_rand_weibull (tw_rng_stream * g, double mean, double shape)
Definition at line 224 of file ross-random-internal.c.
References mean, and tw_rand_unif.