ROSS: ross/models/tcp-ip/ip-routing.c File Reference
ip-routing.c File Reference
#include <ip.h>
Macros
#define IP_RT_DEBUG 0
Functions
int routing_read ()
void routing_write ()
void ip_routing_init ()
void routing_init_ft_read (ip_state *state, tw_lp *lp)
void ip_rt_print (ip_state *state, tw_lp *lp, FILE *log)
void routing_init_ft_write (ip_state *state, tw_lp *lp)
void ip_routing_init_ft (ip_state *state, tw_lp *lp)
Macro Definition Documentation
#define IP_RT_DEBUG 0
Definition at line 3 of file ip-routing.c.
Function Documentation
void ip_routing_init ()
Definition at line 38 of file ip-routing.c.
References routing_read(), and routing_write().
Referenced by ip_md_init(), and ip_setup_options().
void ip_routing_init_ft (ip_state * state, tw_lp * lp)
Definition at line 366 of file ip-routing.c.
References g_ip_write, routing_init_ft_read(), and routing_init_ft_write().
Referenced by ip_lp_init().
void ip_rt_print (ip_state * state, tw_lp * lp, FILE * log)
Definition at line 50 of file ip-routing.c.
References rn_link::addr, rn_area::as, rn_machine::ft, g_rn_nas, g_tw_nlp, rn_area::id, rn_as::id, tw_lp::id, rn_machine::link, rn_as::low, rn_as::nareas, rn_area::nmachines, rn_getarea(), rn_getmachine(), and rn_route().
Referenced by routing_init_ft_write().
void routing_init_ft_read (ip_state * state, tw_lp * lp)
Definition at line 45 of file ip-routing.c.
void routing_init_ft_write (ip_state * state, tw_lp * lp)
Definition at line 140 of file ip-routing.c.
References rn_link::addr, rn_area::as, c_router, rn_link::cost, d, f, frontier, rn_machine::ft, rn_area::g_ospf_nlsa, rn_area::high, rn_as::high, rn_machine::id, rn_area::id, rn_as::id, tw_lp::id, ip_rt_print(), rn_machine::link, rn_area::low, rn_as::low, rn_as::nareas, rn_machine::nhop, rn_machine::nlinks, rn_area::nmachines, p, rn_getarea(), rn_getas(), rn_getmachine(), rn_link_down, solution, tw_error(), TW_LOC, rn_machine::type, and rn_link::wire.
int routing_read ()
Definition at line 6 of file ip-routing.c.
References g_ip_routing_file, and g_rn_rt_table.
void routing_write ()
Definition at line 19 of file ip-routing.c.
References g_ip_routing_file, g_ip_write, g_rn_logs_dir, tw_error(), and TW_LOC.