ROSS: ross/ross-network.h File Reference
ross-network.h File Reference
Functions
const tw_optdef * tw_net_init (int *argc, char ***argv)
void tw_net_start (void)
void tw_net_stop (void)
void tw_net_abort (void) NORETURN
void tw_net_read (tw_pe *)
void tw_net_send (tw_event *)
void tw_net_cancel (tw_event *)
static tw_node * tw_net_onnode (tw_peid gid)
static tw_peid tw_net_pemap (tw_peid gid)
static int tw_node_eq (tw_node *a, tw_node *b)
unsigned tw_nnodes (void)
void tw_net_barrier (tw_pe *pe)
tw_stime tw_net_minimum (tw_pe *)
tw_statistics * tw_net_statistics (tw_pe *, tw_statistics *)
Function to output the statistics.
void tw_net_gvt_compute (tw_pe *, tw_stime *)
void tw_net_send_lvt (tw_pe *, tw_stime)
Function Documentation
void tw_net_abort (void)
Definition at line 124 of file network-mpi.c.
Referenced by tw_error(), tw_sigsegv(), and tw_sigterm().
void tw_net_barrier (tw_pe * pe)
Definition at line 138 of file network-mpi.c.
References tw_net_node::clients, g_tw_mynode, g_tw_net_barrier_flag, tw_pe::id, tw_pe::local_master, nnodes, tw_net_node::socket_fd, tw_error(), TW_LOC, tw_socket_read(), and tw_socket_send().
Referenced by tw_sched_init(), tw_scheduler_conservative(), and tw_scheduler_optimistic().
void tw_net_cancel (tw_event *)
Definition at line 648 of file network-mpi.c.
References tw_event::cancel_asend, tw_event::cancel_q, tw_event::dest_lp, tw_lp::id, tw_event::owner, tw_lp::pe, service_queues(), tw_pe::sevent_q, tw_event::src_lp, tw_event::state, tw_error(), tw_event_free(), tw_eventq_debug(), tw_eventq_delete_any(), tw_eventq_unshift(), TW_LOC, TW_net_acancel, TW_net_asend, TW_net_outq, tw_net_send(), and TW_pe_sevent_q.
Referenced by event_cancel().
void tw_net_gvt_compute (tw_pe * , tw_stime *)
Definition at line 509 of file network-tcp.c.
References tw_net_node::clients, g_tw_npe, g_tw_pe, tw_pe::GVT, tw_net_stats::lgvt, tw_pe::local_master, tw_pe::master, min, nnodes, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, tw_net_node::socket_fd, stats, tw_gvt_set(), tw_socket_read(), and tw_socket_send().
Referenced by tw_gvt_step2().
const tw_optdef* tw_net_init (int * argc, char *** argv)
Definition at line 49 of file network-mpi.c.
References g_tw_masternode, g_tw_mynode, g_tw_net_device_size, mpi_opts, read_buffer, ross, tcp_opts, tw_error(), and TW_LOC.
Referenced by tw_init().
tw_stime tw_net_minimum (tw_pe *)
Definition at line 145 of file network-mpi.c.
References act_q::cur, act_q::event_list, tw_eventq::head, tw_event::next, posted_sends, and tw_event::recv_ts.
Referenced by tw_gvt_step2().
static tw_node* tw_net_onnode (tw_peid gid) inline static
static tw_peid tw_net_pemap (tw_peid gid) inline static
void tw_net_read (tw_pe *)
Definition at line 625 of file network-mpi.c.
References tw_event::cancel_q, tw_event::dest_lp, tw_pe::event_q, tw_lp::kp, tw_kp::last_time, min, tw_event::owner, tw_lp::pe, tw_pe::pq, tw_event::recv_ts, service_queues(), tw_event::state, tw_pe::trans_msg_ts, tw_eventq_unshift(), tw_gvt_inprogress(), TW_pe_event_q, tw_pq_enqueue(), and tw_socket_read_event().
Referenced by tw_gvt_step2(), tw_sched_init(), tw_scheduler_conservative(), and tw_scheduler_optimistic().
void tw_net_send (tw_event *)
Definition at line 631 of file network-mpi.c.
References tw_event::cancel_q, tw_event::dest_lp, tw_event::event_id, tw_lp::id, tw_event::owner, tw_lp::pe, posted_sends, tw_event::remote, send_begin(), send_finish(), tw_pe::seq_num, tw_pe::sevent_q, tw_event::src_lp, tw_event::state, test_q(), tw_error(), tw_eventq_unshift(), TW_LOC, TW_net_asend, TW_net_outq, and tw_socket_send_event().
Referenced by tw_event_send(), and tw_net_cancel().
void tw_net_send_lvt (tw_pe * , tw_stime)
Definition at line 473 of file network-tcp.c.
References g_tw_npe, g_tw_pe, tw_pe::id, tw_net_stats::lgvt, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, tw_net_node::socket_fd, stats, tw_net_onnode(), and tw_socket_send().
Referenced by tw_gvt_compute().
void tw_net_start (void)
Definition at line 98 of file network-mpi.c.
References tw_net_node::clients, g_tw_master, g_tw_masternode, g_tw_mynode, g_tw_net_barrier_flag, g_tw_net_config, g_tw_net_device_size, g_tw_node_ids, g_tw_npe, g_tw_pe, g_tw_port, tw_pe::hash_t, tw_net_node::hostname, tw_net_node::id, init_q(), init_socket(), MAX_NODES, my_hostname, network_spawn(), nnet_nodes, nnodes, npe, pe_map, tw_net_node::port, posted_recvs, posted_sends, read_buffer, tw_net_stats::s_nrecv, tw_net_stats::s_nsend, send_buffer, tw_pe::seq_num, tw_net_node::socket, socket_accept(), tw_net_node::socket_fd, tw_net_node::socket_sz, tw_calloc(), tw_client_socket_create(), tw_error(), tw_hash_create(), TW_LOC, tw_pe_create(), tw_pe_init(), tw_server_socket_create(), tw_socket_create_mesh(), tw_socket_create_onport(), and world_size.
Referenced by tw_init().
tw_statistics* tw_net_statistics (tw_pe * me, tw_statistics * s)
tw_net_statistics
Attention
Notice that the MPI_Reduce "count" parameter is greater than one. We are reducing on multiple variables simultaneously so if you change this function or the struct tw_statistics, you must update the other.
Definition at line 709 of file network-mpi.c.
References g_tw_masternode, max, tw_pe::node, recv_stats(), s, tw_statistics::s_max_run_time, tw_statistics::s_min_detected_offset, tw_statistics::s_net_events, tw_statistics::s_pe_event_ties, tw_statistics::s_total, send_stats(), tw_pe::stats, tw_calloc(), tw_error(), TW_LOC, tw_nnodes(), and tw_node_eq().
Referenced by tw_stats().
void tw_net_stop (void)
Definition at line 131 of file network-mpi.c.
References nnet_nodes, tw_error(), TW_LOC, and tw_socket_close().
Referenced by apply_opt(), match_opt(), need_argument(), tw_end(), and tw_exit().
unsigned tw_nnodes (void)
Definition at line 92 of file network-mpi.c.
References nnodes, and world_size.
Referenced by epi_init_agent_default(), main(), master_hierarchy(), olsr_custom_mapping(), olsr_event(), olsr_grid_mapping(), olsr_mapping_to_lp(), pcs_grid_mapping(), phold_event_handler(), phold_main(), pm_stats_print(), qhold_init(), recv_finish(), rm_getelevation(), rm_grid_terrain(), rm_initialize(), rn_map(), rn_xml_topology(), sa_master_event(), sa_master_for_level(), setup_pes(), tlm_getelevation(), tlm_grid_init(), tlm_md_init(), traffic_grid_mapping(), tw_define_lps(), tw_gvt_force_update(), tw_gvt_start(), tw_hash_create(), tw_hash_remove(), tw_memory_free(), tw_net_statistics(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), and tw_stats().
static int tw_node_eq (tw_node * a, tw_node * b) inline static