ROSS: ross/models/phold/phold.c File Reference
phold.c File Reference
#include "phold.h"
Functions
tw_peid phold_map (tw_lpid gid)
void phold_init (phold_state *s, tw_lp *lp)
void phold_event_handler (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_event_handler_rc (phold_state *s, tw_bf *bf, phold_message *m, tw_lp *lp)
void phold_finish (phold_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 103 of file phold.c.
References g_phold_start_events, g_tw_events_per_pe, g_tw_lookahead, g_tw_memory_nqueues, g_tw_mynode, g_tw_nlp, g_tw_npe, lookahead, mean, mult, nlp_per_pe, offset_lpid, optimistic_memory, percent_remote, stagger, ttl_lps, tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
void phold_event_handler (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 38 of file phold.c.
References tw_bf::c1, DOWNSTREAM, g_tw_nlp, tw_lp::gid, lookahead, mean, offset_lpid, percent_remote, rn_event_new(), rn_event_send(), tw_lp::rng, ttl_lps, tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_nnodes(), tw_rand_exponential(), tw_rand_integer(), and tw_rand_unif.
void phold_event_handler_rc (phold_state * s, tw_bf * bf, phold_message * m, tw_lp * lp)
Definition at line 63 of file phold.c.
References tw_bf::c1, tw_lp::rng, and tw_rand_reverse_unif.
void phold_finish (phold_state * s, tw_lp * lp)
Definition at line 73 of file phold.c.
void phold_init (phold_state * s, tw_lp * lp)
Definition at line 11 of file phold.c.
References DOWNSTREAM, g_phold_start_events, g_tw_ts_end, tw_lp::gid, lookahead, mean, rn_event_new(), rn_event_send(), tw_lp::rng, stagger, tw_event_new(), tw_event_send(), and tw_rand_exponential().
tw_peid phold_map (tw_lpid gid)
Definition at line 5 of file phold.c.
References g_tw_nlp.
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("PHOLD Model"),
        TWOPT_STIME("remote", percent_remote, "desired remote event rate"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_STIME("lookahead", lookahead, "lookahead for events"),
        TWOPT_UINT("start-events", g_phold_start_events, "number of initial messages per LP"),
        TWOPT_UINT("stagger", stagger, "Set to 1 to stagger event uniformly across 0 to end time."),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 87 of file phold.c.
tw_lptype mylps[]
Initial value:
= {
        {(init_f) phold_init,
         (event_f) phold_event_handler,
         (revent_f) phold_event_handler_rc,
         (final_f) phold_finish,
         (map_f) phold_map,
        sizeof(phold_state)},
        {0},
}
Definition at line 77 of file phold.c.