ROSS: ross/models/tcp-ip/tcp-timer.c File Reference
tcp-timer.c File Reference
#include <tcp.h>
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
tw_event * tcp_rc_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
Function Documentation
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 120 of file tcp-timer.c.
References g_tcp_fd, tcp_message::RC, rn_timer_init(), tcp_message::src, RC::timer_ts, tw_error(), TW_LOC, and tw_memory_free_rc().
Referenced by tcp_rc_process_ack().
tw_event* tcp_rc_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 49 of file tcp-timer.c.
References tw_bf::c13, tw_bf::c14, g_tcp_fd, tw_lp::id, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, tw_memory_alloc(), tw_memory_alloc_rc(), and tw_now().
Referenced by tcp_rc_process_ack(), and tcp_rc_timeout().
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 102 of file tcp-timer.c.
References tw_pe::cur_event, g_tcp_fd, tw_lp::id, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), RC::timer_ts, tw_error(), TW_LOC, and tw_memory_free().
Referenced by tcp_update_rtt().
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
References tw_bf::c13, tw_bf::c14, tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_init(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, and tw_memory_alloc().
Referenced by tcp_process_ack(), tcp_timeout(), and tcp_update_rtt().