ROSS: ross/models/tcp-ip/ip-extern.h File Reference
ip-extern.h File Reference
Functions
void ip_lp_init (ip_state *, tw_lp *)
void ip_event_handler (ip_state *, tw_bf *, tcp_message *, tw_lp *)
void ip_rc_event_handler (ip_state *, tw_bf *, tcp_message *, tw_lp *)
void ip_lp_final (ip_state *state, tw_lp *lp)
void ip_upstream (ip_state *, tcp_message *, tw_lp *lp)
void ip_rc_upstream (ip_state *state, tcp_message *msg, tw_lp *lp)
ip_link * ip_getlink (ip_state *state, tw_lpid dst)
void ip_downstream_source (ip_state *, tw_bf *, tcp_message *, tw_lp *)
void ip_downstream_forward (ip_state *, tw_bf *, tcp_message *, tw_lp *)
void ip_rc_downstream (ip_state *, tcp_message *, tw_lp *)
void ip_packet_drop (ip_state *state, tcp_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, tcp_message *msg, tw_lp *lp)
void ip_routing_init ()
void ip_routing_init_ft (ip_state *state, tw_lp *lp)
void ip_rt_print (ip_state *state, tw_lp *lp, FILE *log)
tw_lpid ip_getroute (ip_state *state, tw_lpid dst)
void ip_init (tw_lp *lp, FILE *f)
void ip_main (int argc, char **argv, char **env)
void ip_md_final ()
Variables
ip_stats * g_ip_stats
int g_ip_header
tw_fd g_ip_fd
int g_ip_routing_simple
int g_ip_write
FILE * g_ip_routing_file
short int * g_ip_front
short int * g_ip_p
short int * g_ip_f
short int * g_ip_s
short int * g_ip_d
Function Documentation
void ip_downstream_forward (ip_state * , tw_bf * , tcp_message * , tw_lp *)
void ip_downstream_source (ip_state * , tw_bf * , tcp_message * , tw_lp *)
void ip_event_handler (ip_state * , tw_bf * , tcp_message * , tw_lp *)
ip_link* ip_getlink (ip_state * state, tw_lpid dst)
Definition at line 4 of file ip-downstream.c.
References ip_link::addr, ip_state::links, and ip_state::nlinks.
Referenced by getroute(), and rc_getroute().
tw_lpid ip_getroute (ip_state * state, tw_lpid dst)
void ip_init (tw_lp * lp, FILE * f)
Definition at line 4 of file ip-init.c.
void ip_lp_final (ip_state * state, tw_lp * lp)
Definition at line 96 of file ip.c.
References g_ip_stats, max, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, and ip_state::stats.
void ip_lp_init (ip_state * , tw_lp *)
Definition at line 9 of file ip.c.
References g_ip_routing_simple, ip_routing_init_ft(), ip_state::links, ip_state::nlinks, and ip_state::stats.
void ip_main (int argc, char ** argv, char ** env)
Definition at line 29 of file ip-main.c.
References g_ip_fd, g_ip_stats, g_tw_nkp, ip_setup_options(), and tw_getkp().
Referenced by main().
void ip_md_final ()
Definition at line 53 of file ip-model.c.
References g_ip_stats, g_tw_masternode, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, stats, tw_error(), tw_ismaster(), and TW_LOC.
void ip_packet_drop (ip_state * state, tcp_message * msg, tw_lp * lp)
void ip_rc_downstream (ip_state * , tcp_message * , tw_lp *)
void ip_rc_event_handler (ip_state * , tw_bf * , tcp_message * , tw_lp *)
void ip_rc_packet_drop (ip_state * state, tcp_message * msg, tw_lp * lp)
void ip_rc_upstream (ip_state * state, tcp_message * msg, tw_lp * lp)
void ip_routing_init ()
Definition at line 125 of file ip-routing.c.
References routing_read(), and routing_write().
void ip_routing_init_ft (ip_state * state, tw_lp * lp)
Definition at line 366 of file ip-routing.c.
References g_ip_write, routing_init_ft_read(), and routing_init_ft_write().
Referenced by ip_lp_init().
void ip_rt_print (ip_state * state, tw_lp * lp, FILE * log)
Definition at line 50 of file ip-routing.c.
References rn_link::addr, rn_area::as, rn_machine::ft, g_rn_nas, g_tw_nlp, rn_area::id, rn_as::id, tw_lp::id, rn_machine::link, rn_as::low, rn_as::nareas, rn_area::nmachines, rn_getarea(), rn_getmachine(), and rn_route().
void ip_upstream (ip_state * , tcp_message * , tw_lp * lp)
Variable Documentation
short int* g_ip_d
Definition at line 34 of file ip-global.c.
short int* g_ip_f
Definition at line 32 of file ip-global.c.
tw_fd g_ip_fd
Definition at line 14 of file ip-global.c.
short int* g_ip_front
Definition at line 30 of file ip-global.c.
int g_ip_header
Definition at line 12 of file ip-global.c.
short int* g_ip_p
Definition at line 31 of file ip-global.c.
FILE* g_ip_routing_file
Definition at line 17 of file ip-global.c.
int g_ip_routing_simple
Definition at line 15 of file ip-global.c.
short int* g_ip_s
Definition at line 33 of file ip-global.c.
ip_stats* g_ip_stats
Definition at line 11 of file ip-global.c.
int g_ip_write
Definition at line 16 of file ip-global.c.
Referenced by ip_routing_init_ft(), ip_setup_options(), and routing_write().