ROSS: ross/models/tcp-ip/tcp.c File Reference
tcp.c File Reference
#include <tcp.h>
Macros
#define TCP_LOG 0
Functions
void tcp_lp_init (tcp_state *state, tw_lp *lp)
void tcp_event_handler (tcp_state *state, tw_bf *bf, tcp_message *m, tw_lp *lp)
void tcp_rc_event_handler (tcp_state *state, tw_bf *bf, tcp_message *m, tw_lp *lp)
void tcp_lp_final (tcp_state *state, tw_lp *lp)
Macro Definition Documentation
#define TCP_LOG 0
Definition at line 3 of file tcp.c.
Function Documentation
void tcp_event_handler (tcp_state * state, tw_bf * bf, tcp_message * m, tw_lp * lp)
Definition at line 66 of file tcp.c.
References tcp_state::connection, tw_lp::id, tcp_message::src, tcp_process_ack(), tcp_process_data(), tcp_timeout(), and tw_now().
void tcp_lp_final (tcp_state * state, tw_lp * lp)
Definition at line 127 of file tcp.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_state::connection, tcp_state::cwnd, tcp_statistics::dropped_packets, tcp_statistics::final_time, g_rn_logs_dir, g_tcp_stats, tw_lp::id, tcp_state::len, tcp_statistics::recv, tcp_statistics::sent, tcp_statistics::start_time, tcp_state::stats, tcp_statistics::throughput, tcp_statistics::tout, and tw_now().
void tcp_lp_init (tcp_state * state, tw_lp * lp)
Definition at line 9 of file tcp.c.
References tcp_state::connection, tcp_state::cwnd, tw_lp::id, tcp_state::lastsent, tcp_state::len, tcp_state::mss, tw_event::recv_ts, tcp_state::rto, tcp_state::rtt_seq, tcp_state::rtt_time, tcp_statistics::sent, tcp_state::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tcp_statistics::start_time, tcp_state::stats, tcp_event_send(), TCP_MTU, TCP_SND_WND, tcp_state::timer, tw_event_data(), tw_rand_exponential(), and tw_timer_init().
void tcp_rc_event_handler (tcp_state * state, tw_bf * bf, tcp_message * m, tw_lp * lp)
Definition at line 97 of file tcp.c.
References tcp_state::connection, tw_lp::id, tcp_message::src, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), and tw_now().