ROSS: ross/models/tcp/tcp-host-rc.c File Reference
tcp-host-rc.c File Reference
#include "tcp.h"
Functions
void tcp_host_process_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_ack_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_data_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_timeout_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_rc_EventHandler (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
Function Documentation
void tcp_host_process_ack_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 50 of file tcp-host-rc.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c9, RC::cwnd, Host_State::cwnd, Msg_Data::dest, Host_State::dev, RC::dev, RC::dup_count, Host_State::dup_count, g_mss, RC::lastsent, Host_State::lastsent, Msg_Data::MethodName, Msg_Data::RC, RTO, Host_State::rto, Host_State::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, RC::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, RC::timer_seq, RC::timer_ts, tw_event_data(), tw_timer_init(), tw_timer_reset(), and Host_State::unack.
Referenced by tcp_host_process_rc().
void tcp_host_process_data_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 148 of file tcp-host-rc.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::dup_count, g_mss, g_recv_wnd, RC::lastsent, Host_State::lastsent, Host_State::out_of_order, Msg_Data::RC, Host_State::received_packets, Host_State::seq_num, and Msg_Data::seq_num.
Referenced by tcp_host_process_rc().
void tcp_host_process_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 13 of file tcp-host-rc.c.
References tw_bf::c10, tw_bf::c11, Host_State::connection, g_hosts_info, g_routers, tw_lp::id, tcp_host_process_ack_rc(), tcp_host_process_data_rc(), and Host_Info::type.
Referenced by tcp_host_rc_EventHandler().
void tcp_host_rc_EventHandler (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 212 of file tcp-host-rc.c.
References FORWARD, tw_lp::id, Msg_Data::MethodName, RTO, tcp_host_process_rc(), tcp_host_timeout_rc(), tw_error(), tw_exit(), and TW_LOC.
void tcp_host_timeout_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 182 of file tcp-host-rc.c.
References Msg_Data::ack, tw_bf::c1, RC::cwnd, Host_State::cwnd, Msg_Data::dest, RC::dup_count, RC::lastsent, Host_State::lastsent, Msg_Data::RC, Host_State::rto, Host_State::rto_timer, RC::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Host_State::ssthresh, Host_State::timedout_packets, and tw_timer_cancel().
Referenced by tcp_host_rc_EventHandler().