ROSS: ross/models/tcp/tcp-util.c File Reference
tcp-util.c File Reference
#include "tcp.h"
Functions
tw_lp * tcp_util_nexthop (tw_lp *lp, int dest)
int tcp_util_nexthop_link (tw_lp *lp, int dest)
void tcp_util_event (tw_lp *lp, int type, int source, int dest, int seq_num, int ack, double ts)
Function Documentation
void tcp_util_event (tw_lp * lp, int type, int source, int dest, int seq_num, int ack, double ts)
Definition at line 92 of file tcp-util.c.
References Msg_Data::ack, Msg_Data::dest, Msg_Data::MethodName, Msg_Data::seq_num, Msg_Data::source, tcp_util_nexthop(), tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by tcp_host_process_ack(), tcp_host_process_data(), tcp_host_startup(), tcp_host_timeout(), and tcp_router_forward().
tw_lp* tcp_util_nexthop (tw_lp * lp, int dest)
Definition at line 13 of file tcp-util.c.
References Router_Link::connected, Host_Link::connected, CORE_ROUTERS, g_hosts_links, g_new_routing_table, g_num_links, g_routers, g_routers_links, g_routing_table, g_type, tw_lp::id, and tw_getlp().
Referenced by tcp_router_forward(), and tcp_util_event().
int tcp_util_nexthop_link (tw_lp * lp, int dest)
Definition at line 57 of file tcp-util.c.
References CORE_ROUTERS, g_new_routing_table, g_num_links, g_routers, g_routing_table, g_type, and tw_lp::id.
Referenced by tcp_router_forward(), and tcp_router_forward_rc().