ROSS: ross/models/tcp-ip/tcp-util.c File Reference
tcp-util.c File Reference
#include <tcp.h>
Functions
void tcp_event_send (tcp_state *state, int src, tw_stime ts, int dst, int size, int seq_num, int ack, tw_lp *lp)
Function Documentation
void tcp_event_send (tcp_state * state, int src, tw_stime ts, int dst, int size, int seq_num, int ack, tw_lp * lp)
Definition at line 4 of file tcp-util.c.
References tcp_message::ack, tcp_state::connection, tcp_message::dst, tw_lp::id, tcp_state::lastsent, tcp_message::seq_num, tcp_message::size, tcp_message::src, tw_event_data(), tw_event_new(), tw_event_send(), and tw_now().