ROSS: ross/models/srw/rn-netdmf-wrapper.cpp File Reference
rn-netdmf-wrapper.cpp File Reference
NetDMF Wrappers.
#include <NetDMF.h>
#include <NetDMFDOM.h>
#include <NetDMFNode.h>
#include <NetDMFXmlNode.h>
#include <NetDMFPlatform.h>
#include <NetDMFEvent.h>
#include <NetDMFRoot.h>
#include <NetDMFScenario.h>
#include <NetDMFParameter.h>
#include <NetDMFDevice.h>
#include <NetDMFChannel.h>
#include <NetDMFConversation.h>
#include <NetDMFMovement.h>
#include <NetDMFArray.h>
#include <NetDMFTraffic.h>
#include <NetDMFAddressItem.h>
#include <NetDMFStack.h>
#include <libxml/tree.h>
#include <vector>
#include <sstream>
#include "srw.h"
Functions
void parseScenarios ()
void attach_node_to_lp (long lpnum, long nodeId)
NetDMFElement * FindNetDMFElementWithString (XdmfConstString foo)
void rnNetDMFInit ()
NetDMFNode * getNodeWithAddress (std::string address)
void parseTraffics (NetDMFConversation *parent, int &index)
void parseCommunications (NetDMFEvent *parent)
void parseMovements (NetDMFEvent *parent)
void parseEvents (NetDMFScenario *parent)
void parseParameters (NetDMFElement *el, std::vector< NetDMFParameter * > &params)
void parseDevices (NetDMFNode *node, std::vector< NetDMFDevice * > &dev)
void parseNodes (NetDMFElement *elmt)
void parseChannels (NetDMFElement *elmt)
void parsePlatforms (NetDMFScenario *scenario)
Variables
static NetDMFDOM * dom = 0
static NetDMFRoot * root = 0
char netdmf_config []
Detailed Description
This file provides wrappers for functions to enable C linkage. These functions will perform most of the actions and provide it to the C front-end. Almost all of this logic was stolen from Payton Oliveri's python script NetDMFtoOpNet.py.
Definition in file rn-netdmf-wrapper.cpp.
Function Documentation
void attach_node_to_lp (long lpnum, long nodeId)
Attach an srw_node_info struct to an LP.
Definition at line 43 of file rn-netdmf.c.
References tw_lp::cur_state, g_tw_lp, srw_node_info::node_id, srw_state::nodes, and srw_state::num_radios.
Referenced by parseNodes().
NetDMFElement* FindNetDMFElementWithString (XdmfConstString foo)
Definition at line 49 of file rn-netdmf-wrapper.cpp.
References dom.
Referenced by parseMovements().
NetDMFNode* getNodeWithAddress (std::string address)
Definition at line 150 of file rn-netdmf-wrapper.cpp.
References dom.
void parseChannels (NetDMFElement * elmt)
Parse the NetDMFChannel type, described below.
In a wired or wireless network, a channel specifies physical or logical connectivity to a particular network segment, such as a shared Ethernet or 802.11 network. The NetDMFChannel element contains a list of network devices that are considered to be 'connected' (either physically or logically). The network devices are specified by an XML reference to the definition within a NetDMFNode.
<Device Name="Cat6" DeviceType="Communication">
   <Parameter Name="MaxRate" Value="100E06" />
</Device>
<Channel Name="Cables" ChannelType="Duplex">
   <Device Reference="/NetDMF/Device[@Name='Cat6']" />
     /NetDMF/Scenario/Node[3]/Device
     /NetDMF/Scenario/Node[4]/Device[2]
     /NetDMF/Scenario/Node[@Name='Server']/Device[1]
</Channel>
Definition at line 723 of file rn-netdmf-wrapper.cpp.
References dom, and xpath().
void parseCommunications (NetDMFEvent * parent)
Parse the NetDMFConversation type, described below.
A NetDMFConversation defines conversations between nodes. It is the child of an event with EventType="Communication" and CommType="Conversation". A conversation can have 0 or 1 PacketItems. If present, the PacketItem lists the packets in the conversation. Additionally a Conversation can have 1 or 2 Traffic elements. These define the traffic in each direction.
<Event EventType="Comm" CommType="Conversation" StartTime="12345">
   <Conversation
       StartTime="12345"
       ConversationType="IPV4"
       EndPointA="10.11.102.23"
       EndPointB="10.11.104.23">
       <PacketItem
           NumberOfPackets="100"
           PacketType="Filter"
           Filter="src host 10.11.102.23 and dst host 10.11.104.23"
           Format="PCAP">
           test.pcap
        </PacketItem>
        <Traffic
           TrafficType="bin"
           Direction"AtoB"
           Units="bytes"
           Interval="0.1">
           <DataItem NumberType="Float" Dimensions="10" Format="XML">
                0.0 0.0 0.0 0.0 356.0 500.0 500.0 0.0 0.0 0.0
           </DataItem>
        </Traffic>
    </Conversation>
</Event>
Definition at line 303 of file rn-netdmf-wrapper.cpp.
References parseTraffics().
void parseDevices (NetDMFNode * node, std::vector< NetDMFDevice * > & dev)
Parse the NetDMFDevice type, described below.
Currently, there are two types of devices: Communications and Mobility. Devices can contain other devices (a mobility device can have two communication devices). Communication devices contain one or more protocol stacks. Devices have parameters that are only of importance to that particular device.
<Device Name="HMMWV" DeviceType="Communication">
   <Parameter ... >
   <Parameter ... >
</Device>
<Device Name="RadioType1" DeviceType="Communication">
  <Parameter Name="DataRate" Value="300000" />
  <Parameter Name="Delay" Value="2.5" />
</Device>
<Device Name="HMMWV" DeviceType="Mobility">
   <Parameter Name="Wheels" Value="4" />
   <Parameter Name="TopSpeed" Value="20.0" />
   <Device Reference="/NetDMF/Device[@Name='RadioType1']" >
      <Stack Reference="/NetDMF/Stack[@Name='SimpleOlsr']" />
      <Stack Reference="/NetDMF/Stack[@Name='MyExperimentalProtocol']" />
   </Device>
</Device>
Definition at line 582 of file rn-netdmf-wrapper.cpp.
void parseEvents (NetDMFScenario * parent)
Parse the NetDMFEvent type, described below.
An <Event> is the high level container for discrete events. In addition to StartTime and EndTime (from the Unix epoch) an <Event> has an EventType attribute. EventType corresponds to the child element type of the <Event>. Valid EventTypes are :
Collection - Events that should be grouped
Movement - Node Movement
Communication - two or more nodes communicating
Communication Event Types can be further defined in two different ways, as specified by CommunicationType. Valid CommunicationTypes are :
Conversation - Communication between two endpoints
EndPoint - Endpoints for communications
PacketCapture - Packets captured at a specific node:device
Application - A simulator-supported traffic generation application (e.g. ping)
<Result>
<Event EventType="Collection" CollectionType="Temporal"
Name="Simple OLSR Simulation" StartTime="0.0" Endtime="50.0">
<Event EventType="Collection" CollectionType="Temporal"
StartTime="0.0" Endtime="1.0">
<Event  EventType="Movement"
   NodeId="2"
       <Movement
           MovementType="Path"
           PathType="TimeLatLonHeight"
           PathLength="2">
       <DataItem  NumberType="Float" Dimensions="3 4" Format="XML">
   0.0        35.0   75.0  1.0
   1.0        35.15 75.0  1.0
       </DataItem>
       </Movement>
</Event>
<Event  EventType="Comm" CommType="EndPoints" EndPointType="IPV4">
<AddressItem
   AddressType="IPV4"
   NumberOfAddresses"4"
   Format="XML" >
       10.11.102.23
       10.11.104.23
       192.168.0.1
       192.168.0.12
</AddressItem>
</Event>
<Event EventType="Comm" CommType="Conversation">
<Conversation
ConversationType="IPV4"
EndPointA="10.11.102.23"
EndPointB="10.11.104.23">
<PacketItem
   NumberOfPackets="100"
   PacketType="Filter"
   Filter="src host 10.11.102.23 and dst host 10.11.104.23"
   Format="PCAP">
   test.pcap
</PacketItem>
<Traffic
   TrafficType="Bin"
   Units="Bytes"
   Interval="0.1">
<DataItem NumberType="Float" Dimensions="10" Format="XML">
0.0 0.0 0.0 0.0 356.0 500.0 500.0 0.0 0.0 0.0
</DataItem>
</Traffic>
</Conversation>
</Event>
<Event EventType="Comm" CommType="PacketCapture">
  <Parameter Name="NodeId" Value="1"/>
  <Parameter Name="DeviceId" Value="0"/>
  <PacketItem Format="PCAP">
    test1_n1d0.pcap
  </PacketItem>
</Event>
</Event>
<Event EventType="Collection" StartTime="1.0" Endtime="2.0">
   Events for time 1.0 2.0
</Event>
Etc.......
</Event>
</Result>
Definition at line 463 of file rn-netdmf-wrapper.cpp.
References parseCommunications(), and parseMovements().
void parseMovements (NetDMFEvent * parent)
Parse the NetDMFMovement type, described below.
Movment for a node can be in the Scenario or Result section. MovementType can be :
Model
Path If MovementType is Model, the ModelName and ModelData strings define a mobility model and its parameters respectively to define the movement.
If MovementType is Path, PathType can be :
Grid : XYZ in grid coordinates
GeoSpatial : Lat, Lon, Height
GridVelocity : Grid + Velocity
GeoSpatialVelocity : GeoSpatial + velocity
<Movement
   MovementType="Model"
   ModelName="RandomWalk"
   ModelData="interval=1.0s maxspeed=0.5m/s"
</Movement>
<Movement
   MovementType="Path"
   Interval="1.0"
   PathPositionType="GeoSpatial" >
   <DataItem  NumberType="Float" Dimensions="3 4" Format=XML>
      35.0  75.0  1.0
      35.15 75.0  1.0
      35.25 75.0  1.0
      35.35 75.0  1.0
   </DataItem>
</Movement>
Definition at line 349 of file rn-netdmf-wrapper.cpp.
References FindNetDMFElementWithString(), and x.
void parseNodes (NetDMFElement * elmt)
Parse the NetDMFNode type, described below.
The thing to keep in mind while examining an individual NetDMFNode is that ROSS (most likely) will not create a corresponding LP but rather attach it to another previously-defined LP via the LPID NetDMFParameter.
A NetDMFNode contains a single network node.
<Node Name="Person1" NodeId="1">
   <Device ... >
   <Stack... >
</Node>
Definition at line 608 of file rn-netdmf-wrapper.cpp.
References attach_node_to_lp(), parseDevices(), and parseParameters().
void parseParameters (NetDMFElement * el, std::vector< NetDMFParameter * > & params)
Parse the NetDMFParameter type, described below.
A NetDMFParameter contains a name and a value pair. It's is only meaningful to the end application; NetDMF does not interpret the data. WARNING: Terrible code below, but I don't know a better way to do it as each individual class implements its own (non-derived) Parameter support.
<Parameter Name="Wheels" Value="4"/>
<Parameter Name="TopSpeed" Value="45"/>
<Parameter Name="MaxConnections" Value="100000"/>
<Parameter Name="Manufacturer" Value="Acme"/>
Definition at line 496 of file rn-netdmf-wrapper.cpp.
void parsePlatforms (NetDMFScenario * scenario)
Parse the NetDMFPlatform type, described below.
A NetDMFPlatform contains a "platform" definition which is a collection of nodes. It has many of the properties of a node.
<Platform Name="Rack1">
   <Node/>
   <Node/>
   <Node/>
   <Parameter/>
</Platform>
Definition at line 848 of file rn-netdmf-wrapper.cpp.
References dom, parseChannels(), parseNodes(), and parseParameters().
void parseScenarios ()
Parse the NetDMFScenario type, described below.
A NetDMFScenario contains a "scenario" suitable for setting up a Network Simulation.
<Scenario Name="Simuation 1 Scenario">
   <Protocol/>
   <Node/>
   <Event/>
   <Parameter/>
   <Channel/>
   <Platform/>
</Scenario>
void parseTraffics (NetDMFConversation * parent, int & index)
Parse the NetDMFTraffic type, described below.
The <Traffic> specifies the data that flows in a conversation. It uses an XdmfDataItem to specify how many bytes/frames were transferred, in each direction or lists the raw packets using <PacketItem>. If the TrafficType is bin, a TrafficInterval is specified.
<Traffic
  TrafficType="Bin"
  Units="Bytes"
  Interval="0.1">
   <DataItem NumberType="Float" Dimensions="10" Format="XML">
     0.0 0.0 0.0 0.0 356.0 500.0 500.0 0.0 0.0 0.0
   </DataItem>
</Traffic>
Definition at line 236 of file rn-netdmf-wrapper.cpp.
References dom, getNodeWithAddress(), and values.
void rnNetDMFInit ()
This function handles initialization of the NetDMF description language.
Definition at line 110 of file rn-netdmf-wrapper.cpp.
References dom, g_rn_netdmf_config, netdmf_config, parseScenarios(), and root.
Variable Documentation
NetDMFDOM* dom = 0 static
The NetDMF Document Object Model, see NetDMF docs.
Definition at line 34 of file rn-netdmf-wrapper.cpp.
Referenced by FindNetDMFElementWithString(), getNodeWithAddress(), parseChannels(), parsePlatforms(), parseTraffics(), and rnNetDMFInit().
char netdmf_config[]
Definition at line 42 of file rn-netdmf-wrapper.cpp.
Referenced by main(), and rnNetDMFInit().
NetDMFRoot* root = 0 static
The root of the NetDMF file, i.e. <NetDMF Version="2.0" xmlns:xi="http://www.w3.org/2003/XInclude">
Definition at line 40 of file rn-netdmf-wrapper.cpp.
Referenced by rnNetDMFInit().