ROSS: ross/models/epi/epi-extern.h File Reference
epi-extern.h File Reference
Functions
void epi_report_census_tract (int today)
void epi_report_hospitals (int today)
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_location_timer (epi_state *, tw_lp *lp)
void * pq_create (void)
void pq_enqueue (void *pq, tw_memory *)
void * pq_dequeue (void *pq)
void * pq_top (void *pq)
void * pq_next (void *pq, int next)
tw_stime pq_minimum (void *pq)
void pq_delete_any (void *pq, tw_memory **)
unsigned int pq_get_size (void *q)
void pq_cleanup (void *h)
unsigned int pq_max_size (void *q)
void epi_seir_compute (epi_state *state, tw_bf *bf, int, tw_lp *lp)
void epi_agent_update_ts (epi_state *, tw_bf *, epi_agent *a, tw_lp *lp)
void epi_agent_send (tw_lp *src, tw_memory *buf, tw_stime offset, tw_lpid)
epi_ic_stage * epi_agent_infected (epi_agent *a, int disease)
epi_agent * epi_getagent (int id)
void epi_agent_add (epi_state *, tw_bf *bf, tw_memory *, tw_lp *lp)
void epi_agent_remove (epi_state *, tw_bf *bf, tw_lp *lp)
void epi_report_census_track ()
void epi_setup_options (int argc, char **argv)
void epi_init_scenario ()
void epi_main (int argc, char **argv, char **env)
void epi_md_final ()
tw_peid epi_map (tw_lpid gid)
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *cv, epi_message *message, tw_lp *lp)
void epi_rc_event_handler (epi_state *, tw_bf *cv, epi_message *message, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
void epi_stats_print ()
Variables
epi_agent * ga
unsigned int g_epi_complete
unsigned int g_epi_nagents
tw_memoryq * g_epi_agents
void ** g_epi_pq
unsigned int ** g_epi_hospital_wws
unsigned int ** g_epi_hospital_ww
unsigned int ** g_epi_hospital
unsigned int g_epi_nhospital
unsigned int * g_epi_sick_init_pop
unsigned int g_epi_wws_init_pop
unsigned int g_epi_ww_init_pop
unsigned int * g_epi_exposed_today
tw_stime g_epi_mean
double g_epi_sick_rate
double g_epi_ww_rate
double g_epi_wws_rate
double g_epi_ww_threshold
unsigned int g_epi_ww_duration
unsigned int g_epi_ndiseases
epi_disease * g_epi_diseases
char g_epi_ic_fn [1024]
char g_epi_agent_fn [1024]
char g_epi_position_fn [1024]
char g_epi_log_fn [1024]
char g_epi_hospital_fn [1024]
FILE * g_epi_position_f
FILE ** g_epi_log_f
FILE * g_epi_hospital_f
epi_statistics * g_epi_stats
unsigned int *** g_epi_regions
unsigned int g_epi_nregions
unsigned int g_epi_day
int g_epi_mod
tw_fd g_epi_fd
tw_fd g_epi_pathogen_fd
double EPSILON
Function Documentation
void epi_agent_add (epi_state * , tw_bf * bf, tw_memory * , tw_lp * lp)
Definition at line 261 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::curr, epi_agent::days_remaining, epi_agent::dur, epi_agent_contagious(), epi_agent_update_ts(), EPI_AGENT_WORRIED_WELL, g_epi_hospital_ww, g_epi_pq, g_epi_ww_duration, g_epi_ww_threshold, tw_lp::gid, epi_state::hospital, epi_agent::id, tw_lp::id, epi_agent::loc, epi_state::max_queue_size, epi_state::ncontagious_tot, epi_agent::nloc, pq_enqueue(), pq_get_size(), epi_agent::ts_remove, tw_error(), TW_LOC, and tw_now().
epi_ic_stage* epi_agent_infected (epi_agent * a, int disease)
Definition at line 79 of file epi-agent.c.
References g_epi_diseases, epi_pathogen::index, epi_ic_stage::ln_multiplier, p, epi_agent::pathogens, s, epi_pathogen::stage, and epi_disease::stages.
Referenced by epi_seir_compute().
void epi_agent_remove (epi_state * , tw_bf * bf, tw_lp * lp)
Definition at line 195 of file epi-agent.c.
References epi_agent::curr, epi_agent::days_remaining, epi_agent_add_back(), epi_agent_contagious(), epi_agent_send(), epi_agent_stage_tran(), epi_num_remove(), g_epi_pq, g_epi_stages, g_epi_stay_home, tw_lp::gid, epi_agent::id, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_dequeue(), pq_enqueue(), pq_top(), rn_event_direct(), rn_event_send(), epi_agent::stage, epi_agent::ts_next, epi_agent::ts_stage_tran, tw_error(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
Referenced by epi_event_handler().
void epi_agent_send (tw_lp * src, tw_memory * buf, tw_stime offset, tw_lpid)
Definition at line 50 of file epi-agent.c.
References epi_agent::curr, g_epi_fd, g_epi_pathogen_fd, tw_lp::id, epi_agent::loc, epi_agent::pathogens, tw_event_new(), tw_event_send(), and tw_now().
Referenced by epi_agent_remove().
void epi_agent_update_ts (epi_state * , tw_bf * , epi_agent * a, tw_lp * lp)
Definition at line 13 of file epi-agent.c.
References g_epi_diseases, g_epi_ndiseases, epi_pathogen::index, epi_ic_stage::ln_multiplier, min, p, epi_agent::pathogens, epi_pathogen::stage, epi_disease::stages, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, and epi_pathogen::ts_stage_tran.
Referenced by agent_stage_tran(), and epi_agent_add().
void epi_event_handler (epi_state * state, tw_bf * cv, epi_message * message, tw_lp * lp)
Definition at line 166 of file epi.c.
References epi_agent_add(), epi_agent_remove(), epi_location_timer(), epi_report_census_tract(), epi_report_hospitals(), epi_seir_compute(), g_epi_complete, g_epi_day, g_epi_ndiseases, g_epi_pq, epi_agent::id, tw_lp::id, epi_state::ncontagious, epi_agent::pathogens, population, pq_cleanup(), pq_get_size(), tw_now(), and TWENTY_FOUR_HOURS.
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 121 of file epi.c.
References epi_report_census_tract(), epi_report_hospitals(), g_epi_day, g_epi_stats, g_tw_nlp, tw_lp::id, epi_statistics::s_move_ev, epi_statistics::s_nchecked, epi_statistics::s_ndead, epi_statistics::s_ndraws, epi_statistics::s_ninfected, and epi_state::stats.
epi_agent* epi_getagent (int id)
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file epi.c.
References epi_agent::behavior_flags, epi_agent::dur, epi_agent::e_type, EPI_EXPOSED, EPI_GRID_HOME, EPI_GRID_OFFICE_1, epi_location_timer(), EPI_REMOVE, EPI_STAGE_TRANSITION, EPI_SUSCEPTIBLE, g_epi_diseases, g_epi_exposed_today, g_epi_hospital, g_epi_hospital_f, g_epi_hospital_ww, g_epi_hospital_wws, g_epi_ndiseases, g_epi_pathogen_fd, g_epi_pq, g_epi_regions, g_epi_sick_init_pop, g_epi_sick_rate, g_epi_ww_init_pop, g_epi_ww_rate, g_epi_wws_init_pop, g_epi_wws_rate, g_tw_nlp, epi_state::grid_type, epi_state::hospital, epi_agent::id, tw_lp::id, epi_pathogen::index, epi_ic_stage::max_duration, min, epi_ic_stage::min_duration, epi_disease::name, epi_state::ncontagious, epi_state::ncontagious_tot, p, epi_agent::pathogens, epi_state::pq, pq_delete_any(), pq_enqueue(), pq_get_size(), pq_next(), pq_top(), epi_agent::region, rn_timer_init(), tw_lp::rng, s, epi_pathogen::stage, epi_disease::stages, epi_state::stats, epi_state::tmr_remove, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, epi_agent::ts_stage_tran, epi_pathogen::ts_stage_tran, tw_calloc(), tw_error(), TW_LOC, tw_memory_alloc(), tw_rand_integer(), tw_rand_unif, and x.
void epi_init_scenario ()
Definition at line 225 of file epi-init.c.
References g_epi_ic_fn, init_default_ic_stages(), and init_ic_stages_from_file().
void epi_location_timer (epi_state * , tw_lp * lp)
Definition at line 4 of file epi-timer.c.
References tw_pe::cur_event, g_epi_pq, tw_lp::id, tw_lp::pe, epi_state::pq, pq_top(), rn_timer_init(), rn_timer_reset(), epi_state::tmr_remove, epi_agent::ts_next, tw_error(), TW_LOC, tw_timer_init(), and tw_timer_reset().
void epi_main (int argc, char ** argv, char ** env)
Definition at line 14 of file epi-main.c.
References epi_init_scenario(), epi_setup_options(), g_epi_log_f, g_epi_stats, g_rn_logs_dir, tw_calloc(), tw_error(), and TW_LOC.
tw_peid epi_map (tw_lpid gid)
Definition at line 11 of file epi.c.
References g_tw_nlp.
void epi_md_final ()
Definition at line 26 of file epi-main.c.
References epi_stats_print(), g_epi_log_f, g_epi_nagents, and g_epi_nsick.
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 21 of file epi-num.c.
References epi_agent::curr, epi_agent::dur, g_epi_mod, g_epi_next_report_day, g_epi_nreport_days, g_epi_report_days, tw_lp::id, epi_agent::loc, NINE_OCLOCK, epi_agent::nloc, epi_agent::num, rn_event_direct(), rn_event_send(), rn_message::ttl, tw_event_data(), tw_now(), and TWENTY_FOUR_HOURS.
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 63 of file epi-num.c.
References tw_lp::id, epi_agent::loc, epi_agent::num, rn_event_direct(), rn_event_send(), tw_event::state, rn_message::ttl, tw_error(), tw_event_data(), and TW_LOC.
void epi_rc_event_handler (epi_state * , tw_bf * cv, epi_message * message, tw_lp * lp)
Definition at line 252 of file epi.c.
void epi_report_census_track ()
void epi_report_census_tract (int today)
Definition at line 29 of file epi-report.c.
References g_epi_complete, g_epi_diseases, g_epi_exposed_today, g_epi_log_f, g_epi_ndiseases, g_epi_nregions, g_epi_regions, and epi_disease::nstages.
void epi_report_hospitals (int today)
Definition at line 78 of file epi-report.c.
References g_epi_hospital, g_epi_hospital_f, g_epi_hospital_ww, g_epi_hospital_wws, and g_epi_nhospital.
Referenced by epi_event_handler(), and epi_final().
void epi_seir_compute (epi_state * state, tw_bf * bf, int , tw_lp * lp)
Definition at line 54 of file epi-seir.c.
References agent_susceptible(), delta_t, epi_agent_infected(), EPI_SUSCEPTIBLE, g_epi_pathogen_fd, g_epi_pq, tw_lp::id, epi_pathogen::index, epi_ic_stage::ln_multiplier, epi_state::ncontagious, p, epi_agent::pathogens, pq_get_size(), pq_next(), tw_lp::rng, s, epi_pathogen::stage, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, epi_pathogen::ts_stage_tran, tw_error(), TW_LOC, tw_memory_alloc(), tw_now(), and tw_rand_unif.
void epi_setup_options (int argc, char ** argv)
Definition at line 30 of file epi-setup.c.
References g_epi_hospital_f, g_epi_ic_fn, g_epi_log_f, g_epi_mod, g_epi_nsick, g_epi_position_f, g_epi_position_fn, g_epi_psick, g_epi_stay_home, g_epi_work_while_sick_p, g_epi_worried_well_duration, g_epi_worried_well_rate, g_epi_worried_well_threshold, g_rn_logs_dir, g_rn_tools_dir, tw_calloc(), tw_error(), TW_LOC, and tw_printf().
void epi_stats_print ()
Definition at line 4 of file epi-stats.c.
References g_epi_ndiseases, g_epi_sick_init_pop, g_epi_sick_rate, g_epi_stats, g_epi_ww_init_pop, g_epi_ww_rate, g_epi_wws_init_pop, g_epi_wws_rate, g_tw_ts_end, epi_statistics::s_move_ev, epi_statistics::s_nchecked, epi_statistics::s_ndead, epi_statistics::s_ndraws, and epi_statistics::s_ninfected.
void pq_cleanup (void * h)
Definition at line 183 of file queue-heap.c.
References KEY, pq_delete_any(), pq_enqueue(), pq_get_size(), pq_minimum(), and pq_next().
Referenced by epi_event_handler().
void* pq_create (void)
Definition at line 159 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, and CHeap::nelems.
void pq_delete_any (void * pq, tw_memory **)
Definition at line 125 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, KEY, CHeap::nelems, percolate_up(), and sift_down().
void* pq_dequeue (void * pq)
Definition at line 101 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, CHeap::nelems, and sift_down().
void pq_enqueue (void * pq, tw_memory *)
Definition at line 70 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, CHeap::nelems, and percolate_up().
unsigned int pq_get_size (void * q)
Definition at line 197 of file queue-heap.c.
unsigned int pq_max_size (void * q)
tw_stime pq_minimum (void * pq)
Definition at line 174 of file queue-heap.c.
References HeapPeekTop(), and KEY.
void* pq_next (void * pq, int next)
Definition at line 192 of file queue-heap.c.
void* pq_top (void * pq)
Definition at line 183 of file queue-heap.c.
References HeapPeekTop().
Variable Documentation
double EPSILON
Definition at line 40 of file epi-global.c.
char g_epi_agent_fn[1024]
Definition at line 43 of file epi-global.c.
Referenced by epi_agent_init().
tw_memoryq* g_epi_agents
Definition at line 12 of file epi-global.c.
Referenced by epi_init_agent().
unsigned int g_epi_complete
Definition at line 25 of file epi-global.c.
unsigned int g_epi_day
Definition at line 22 of file epi-global.c.
epi_disease* g_epi_diseases
Definition at line 16 of file epi-global.c.
Referenced by agent_stage_tran(), epi_agent_contagious(), epi_agent_infected(), epi_agent_update_ts(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), and epi_report_census_tract().
unsigned int* g_epi_exposed_today
Definition at line 33 of file epi-global.c.
Referenced by epi_init(), epi_init_disease(), epi_init_disease_default(), and epi_report_census_tract().
tw_fd g_epi_fd
Definition at line 37 of file epi-global.c.
unsigned int** g_epi_hospital
Definition at line 6 of file epi-global.c.
FILE* g_epi_hospital_f
Definition at line 14 of file epi-global.c.
char g_epi_hospital_fn[1024]
Definition at line 47 of file epi-global.c.
Referenced by epi_init_hospital().
unsigned int** g_epi_hospital_ww
Definition at line 26 of file epi-global.c.
Referenced by epi_agent_add(), epi_init(), epi_init_hospital(), and epi_report_hospitals().
unsigned int** g_epi_hospital_wws
Definition at line 25 of file epi-global.c.
Referenced by epi_init(), epi_init_hospital(), and epi_report_hospitals().
char g_epi_ic_fn[1024]
Definition at line 10 of file epi-global.c.
FILE** g_epi_log_f
Definition at line 13 of file epi-global.c.
char g_epi_log_fn[1024]
Definition at line 10 of file epi-global.c.
tw_stime g_epi_mean
Definition at line 36 of file epi-global.c.
Referenced by epi_init_agent_default().
int g_epi_mod
Definition at line 23 of file epi-global.c.
unsigned int g_epi_nagents
Definition at line 18 of file epi-global.c.
unsigned int g_epi_ndiseases
Definition at line 15 of file epi-global.c.
Referenced by epi_agent_update_ts(), epi_event_handler(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_model_final(), epi_report_census_tract(), epi_stats_print(), and main().
unsigned int g_epi_nhospital
Definition at line 28 of file epi-global.c.
Referenced by epi_init_hospital(), and epi_report_hospitals().
unsigned int g_epi_nregions
Definition at line 20 of file epi-global.c.
Referenced by epi_init_agent(), epi_init_agent_default(), and epi_report_census_tract().
tw_fd g_epi_pathogen_fd
Definition at line 10 of file epi-global.c.
Referenced by agent_susceptible(), epi_agent_send(), epi_init(), epi_seir_compute(), and main().
FILE* g_epi_position_f
Definition at line 12 of file epi-global.c.
char g_epi_position_fn[1024]
Definition at line 11 of file epi-global.c.
void** g_epi_pq
Definition at line 13 of file epi-global.c.
Referenced by agent_stage_tran(), epi_agent_add(), epi_agent_add_back(), epi_agent_remove(), epi_event_handler(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_location_timer(), and epi_seir_compute().
unsigned int*** g_epi_regions
Definition at line 21 of file epi-global.c.
Referenced by agent_stage_tran(), epi_init(), epi_init_agent(), epi_init_agent_default(), and epi_report_census_tract().
unsigned int* g_epi_sick_init_pop
Definition at line 30 of file epi-global.c.
Referenced by epi_init(), epi_init_disease(), epi_init_disease_default(), epi_model_final(), and epi_stats_print().
double g_epi_sick_rate
Definition at line 37 of file epi-global.c.
Referenced by epi_init(), epi_model_final(), and epi_stats_print().
epi_statistics* g_epi_stats
Definition at line 8 of file epi-global.c.
unsigned int g_epi_ww_duration
Definition at line 41 of file epi-global.c.
Referenced by epi_agent_add().
unsigned int g_epi_ww_init_pop
Definition at line 31 of file epi-global.c.
Referenced by epi_init(), epi_model_final(), and epi_stats_print().
double g_epi_ww_rate
Definition at line 38 of file epi-global.c.
Referenced by epi_init(), epi_model_final(), and epi_stats_print().
double g_epi_ww_threshold
Definition at line 40 of file epi-global.c.
Referenced by epi_agent_add().
unsigned int g_epi_wws_init_pop
Definition at line 32 of file epi-global.c.
Referenced by epi_init(), epi_model_final(), and epi_stats_print().
double g_epi_wws_rate
Definition at line 39 of file epi-global.c.
Referenced by epi_init(), epi_model_final(), and epi_stats_print().
epi_agent* ga
Definition at line 3 of file epi-global.c.
Referenced by epi_init_agent_default().