ROSS: ross/models/tcp-ip/ip-rc-downstream.c File Reference
ip-rc-downstream.c File Reference
#include <ip.h>
Functions
ip_link * rc_getroute (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_downstream (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_rc_downstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 31 of file ip-rc-downstream.c.
References ip_link::addr, rn_message::dst, g_ip_fd, tw_lp::id, ip_rc_packet_drop(), ip_link::last_sent, rc_getroute(), ip_message::rc_lastsent, ip_message::rc_link, ip_stats::s_nforward, rn_message::src, ip_state::stats, and tw_memory_alloc_rc().
ip_link* rc_getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-rc-downstream.c.
References rn_message::dst, tw_lp::id, ip_getlink(), ip_rc_packet_drop(), ip_route(), ip_state::links, ip_state::nlinks, and rn_message::src.