ROSS: ross/models/epi/epi.c File Reference
epi.c File Reference
#include <epi.h>
Macros
#define TWENTY_FOUR_HOURS 86400
Functions
tw_peid epi_map (tw_lpid gid)
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *bf, epi_message *msg, tw_lp *lp)
void epi_rc_event_handler (epi_state *state, tw_bf *bf, epi_message *msg, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
int main (int argc, char **argv, char **env)
void epi_md_final ()
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Macro Definition Documentation
#define TWENTY_FOUR_HOURS 86400
Definition at line 8 of file epi.c.
Referenced by epi_event_handler().
Function Documentation
void epi_event_handler (epi_state * state, tw_bf * bf, epi_message * msg, tw_lp * lp)
Definition at line 166 of file epi.c.
References epi_agent_add(), epi_agent_remove(), epi_location_timer(), epi_report_census_tract(), epi_report_hospitals(), epi_seir_compute(), g_epi_complete, g_epi_day, g_epi_ndiseases, g_epi_pq, epi_agent::id, tw_lp::id, epi_state::ncontagious, epi_agent::pathogens, population, pq_cleanup(), pq_get_size(), tw_now(), and TWENTY_FOUR_HOURS.
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 263 of file epi.c.
References epi_report_census_tract(), epi_report_hospitals(), g_epi_day, g_epi_stats, g_tw_nlp, tw_lp::id, epi_statistics::s_ndead, epi_statistics::s_ninfected, and epi_state::stats.
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 23 of file epi.c.
References epi_agent::behavior_flags, EPI_EXPOSED, epi_location_timer(), EPI_SUSCEPTIBLE, g_epi_diseases, g_epi_exposed_today, g_epi_hospital, g_epi_hospital_f, g_epi_hospital_ww, g_epi_hospital_wws, g_epi_ndiseases, g_epi_pathogen_fd, g_epi_pq, g_epi_regions, g_epi_sick_init_pop, g_epi_sick_rate, g_epi_ww_init_pop, g_epi_ww_rate, g_epi_wws_init_pop, g_epi_wws_rate, g_tw_nlp, epi_state::hospital, epi_agent::id, tw_lp::id, epi_pathogen::index, epi_ic_stage::max_duration, min, epi_ic_stage::min_duration, epi_disease::name, epi_state::ncontagious, epi_state::ncontagious_tot, p, epi_agent::pathogens, epi_state::pq, pq_delete_any(), pq_enqueue(), pq_get_size(), pq_next(), pq_top(), epi_agent::region, tw_lp::rng, s, epi_pathogen::stage, epi_disease::stages, epi_state::stats, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, epi_agent::ts_stage_tran, epi_pathogen::ts_stage_tran, tw_calloc(), tw_error(), TW_LOC, tw_memory_alloc(), tw_rand_integer(), tw_rand_unif, and x.
tw_peid epi_map (tw_lpid gid)
Definition at line 11 of file epi.c.
References g_tw_nlp.
void epi_md_final ()
Definition at line 370 of file epi.c.
References epi_stats_print(), g_epi_log_f, g_epi_nagents, and g_epi_nsick.
void epi_rc_event_handler (epi_state * state, tw_bf * bf, epi_message * msg, tw_lp * lp)
Definition at line 252 of file epi.c.
int main (int argc, char ** argv, char ** env)
Definition at line 329 of file epi.c.
References epi_agent_init(), epi_disease_init(), epi_model_final(), g_epi_fd, g_epi_nagents, g_epi_ndiseases, g_epi_pathogen_fd, g_tw_events_per_pe, g_tw_memory_nqueues, g_tw_nkp, g_tw_nlp, g_tw_npe, tw_define_lps(), tw_getkp(), tw_init(), tw_lp_settype(), tw_opt_add(), and tw_run().
Variable Documentation
const tw_optdef app_opt[]
Definition at line 292 of file epi.c.
tw_lptype mylps[]
Initial value:
= {
        {(init_f) epi_init,
         (event_f) epi_event_handler,
         (revent_f) epi_rc_event_handler,
         (final_f) epi_final,
         (map_f) epi_map,
         sizeof(epi_state)},
        {0},
}
Definition at line 282 of file epi.c.