ROSS: ross/models/tcp/tcp-extern.h File Reference
tcp-extern.h File Reference
#include "tcp.h"
Functions
void tcp_finalize (tcpStatistics *Stat)
void tcp_host_startup (Host_State *SV, tw_lp *lp)
void tcp_host_process (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_ack (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_data (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_update_cwnd (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_update_rtt (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_timeout (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_eventhandler (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_statistics_collectStats (Host_State *SV, tw_lp *lp)
void tcp_router_startUp (Router_State *SV, tw_lp *lp)
void tcp_router_forward (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_eventhandler (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_statistics_collectStats (Router_State *SV, tw_lp *lp)
void tcp_host_process_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_ack_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_process_data_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_timeout_rc (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_host_rc_eventhandler (Host_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_forward_rc (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_rc_eventhandler (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
tw_lpid tcp_util_nexthop (tw_lp *lp, int dest)
int tcp_util_nexthop_link (tw_lp *lp, int dest)
void tcp_util_event (tw_lp *lp, int type, int source, int dest, int seq_num, int ack, double ts)
void tcp_init ()
void init_node_list ()
int read_rocketfuel_file (char *filename)
void color_topology (int levels)
Variables
Tcp_Statistics g_tcp_stats
int g_hosts
int g_routers
int g_npe
int g_nkp
int g_iss
int g_mss
int g_recv_wnd
int g_frequency
int number_of_nodes
int g_type
int g_num_links
char ** g_new_routing_table
Routing_Table ** g_routing_table
Router_Link ** g_routers_links
int * g_routers_info
Host_Link * g_hosts_links
Host_Info * g_hosts_info
Function Documentation
void color_topology (int levels)
Definition at line 107 of file convert.c.
References rocket_fuel_link::bandwidth, bandwidth_classes, rocket_fuel_link::delay, delay_classes, g_level_count, g_node_count, rocket_fuel_node::is_bb, rocket_fuel_node::level, rocket_fuel_node::link_list, max_levels, rocket_fuel_link::node_id, rocket_fuel_node::num_in_level, rocket_fuel_node::num_links, rocket_fuel_node::status, and rocket_fuel_node::used.
Referenced by gen_xml(), and main().
void init_node_list ()
Definition at line 65 of file new-rf-to-ross.c.
References rocket_fuel_node::is_bb, rocket_fuel_node::kp, rocket_fuel_node::level, MAX_NODES, rocket_fuel_node::num_in_level, rocket_fuel_node::num_links, rocket_fuel_node::pe, and rocket_fuel_node::used.
int read_rocketfuel_file (char * filename)
Definition at line 125 of file rf_to_ross.c.
References g_rocketfuel_file, MAX_LINE_WIDTH, MAX_NODES, number_of_nodes, and parse_rocketfuel_line().
void tcp_finalize (tcpStatistics * Stat)
Referenced by main().
void tcp_host_eventhandler (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
void tcp_host_process (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 100 of file tcp-host.c.
References tw_bf::c10, tw_bf::c11, Host_State::connection, g_hosts_info, g_routers, tw_lp::id, Msg_Data::source, tcp_host_process_ack(), tcp_host_process_data(), and Host_Info::type.
Referenced by tcp_host_EventHandler().
void tcp_host_process_ack (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 132 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c9, RC::cwnd, Host_State::cwnd, Host_Link::delay, Msg_Data::dest, RC::dup_count, Host_State::dup_count, FORWARD, g_frequency, g_hosts_links, g_iss, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_State::len, Host_Link::link_speed, min, Msg_Data::RC, tw_event::recv_ts, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, RC::seq_num, Msg_Data::seq_num, Msg_Data::source, Host_State::ssthresh, Host_State::start_time, tcp_host_update_cwnd(), tcp_host_update_rtt(), TCP_TRANSFER_SIZE, tcp_util_event(), RC::timer_seq, RC::timer_ts, tw_event_data(), tw_now(), tw_timer_reset(), and Host_State::unack.
void tcp_host_process_ack_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 50 of file tcp-host-rc.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c9, RC::cwnd, Host_State::cwnd, Msg_Data::dest, Host_State::dev, RC::dev, RC::dup_count, Host_State::dup_count, g_mss, RC::lastsent, Host_State::lastsent, Msg_Data::MethodName, Msg_Data::RC, RTO, Host_State::rto, Host_State::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, RC::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, RC::timer_seq, RC::timer_ts, tw_event_data(), tw_timer_init(), tw_timer_reset(), and Host_State::unack.
Referenced by tcp_host_process_rc().
void tcp_host_process_data (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 270 of file tcp-host.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, Host_Link::delay, RC::dup_count, FORWARD, g_hosts_info, g_hosts_links, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_Link::link_speed, max, Host_State::out_of_order, Msg_Data::RC, Host_State::received_packets, Host_State::seq_num, Msg_Data::seq_num, Msg_Data::source, TCP_HEADER_SIZE, TCP_SND_WND, TCP_TRANSFER_SIZE, tcp_util_event(), and tw_now().
void tcp_host_process_data_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 148 of file tcp-host-rc.c.
References tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::dup_count, g_mss, g_recv_wnd, RC::lastsent, Host_State::lastsent, Host_State::out_of_order, Msg_Data::RC, Host_State::received_packets, Host_State::seq_num, and Msg_Data::seq_num.
Referenced by tcp_host_process_rc().
void tcp_host_process_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 13 of file tcp-host-rc.c.
References tw_bf::c10, tw_bf::c11, Host_State::connection, g_hosts_info, g_routers, tw_lp::id, tcp_host_process_ack_rc(), tcp_host_process_data_rc(), and Host_Info::type.
Referenced by tcp_host_rc_EventHandler().
void tcp_host_rc_eventhandler (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
void tcp_host_startup (Host_State * SV, tw_lp * lp)
Definition at line 13 of file tcp-host.c.
References Host_Info::connected, Host_State::connection, Host_State::cwnd, Host_Link::delay, Host_State::dev, Host_State::dup_count, FORWARD, g_frequency, g_hosts, g_hosts_info, g_hosts_links, g_mss, g_recv_wnd, g_routers, tw_lp::id, Host_State::lastsent, Host_State::len, Host_Link::link_speed, Msg_Data::MethodName, Host_State::out_of_order, Host_State::received_packets, tw_lp::rng, RTO, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, Host_State::rtt_seq, Host_State::rtt_time, Host_State::sent_packets, Host_State::seq_num, Msg_Data::seq_num, Host_Info::size, Host_State::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, Host_State::start_time, TCP_SND_WND, TCP_TRANSFER_SIZE, tcp_util_event(), Host_State::timedout_packets, tw_event_data(), tw_rand_exponential(), tw_rand_integer(), tw_timer_init(), and Host_State::unack.
void tcp_host_statistics_collectStats (Host_State * SV, tw_lp * lp)
void tcp_host_timeout (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 512 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c1, tw_bf::c13, RC::cwnd, Host_State::cwnd, Msg_Data::dest, RC::dup_count, FORWARD, g_hosts_links, g_iss, g_mss, g_recv_wnd, g_routers, tw_lp::id, RC::lastsent, Host_State::lastsent, Host_State::len, Host_Link::link_speed, Msg_Data::MethodName, min, Msg_Data::RC, RTO, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, RC::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Msg_Data::source, Host_State::ssthresh, TCP_TRANSFER_SIZE, tcp_util_event(), Host_State::timedout_packets, tw_event_data(), tw_now(), tw_timer_init(), and Host_State::unack.
void tcp_host_timeout_rc (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 182 of file tcp-host-rc.c.
References Msg_Data::ack, tw_bf::c1, RC::cwnd, Host_State::cwnd, Msg_Data::dest, RC::dup_count, RC::lastsent, Host_State::lastsent, Msg_Data::RC, Host_State::rto, Host_State::rto_timer, RC::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, Host_State::ssthresh, Host_State::timedout_packets, and tw_timer_cancel().
Referenced by tcp_host_rc_EventHandler().
void tcp_host_update_cwnd (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 377 of file tcp-host.c.
References tw_bf::c3, tw_bf::c4, RC::cwnd, Host_State::cwnd, g_mss, g_recv_wnd, g_routers, tw_lp::id, Msg_Data::RC, Host_State::ssthresh, TCP_SND_WND, and tw_now().
void tcp_host_update_rtt (Host_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 405 of file tcp-host.c.
References Msg_Data::ack, tw_bf::c13, tw_bf::c5, tw_bf::c6, tw_bf::c7, Msg_Data::dest, Host_State::dev, RC::dev, g_frequency, g_routers, tw_lp::id, Host_State::len, Msg_Data::RC, tw_event::recv_ts, Host_State::rto, Host_State::rto_seq, Host_State::rto_timer, RC::rtt_seq, Host_State::rtt_seq, RC::rtt_time, Host_State::rtt_time, Host_State::seq_num, Msg_Data::seq_num, Host_State::smoothed_rtt, RC::smoothed_rtt, RC::timer_seq, RC::timer_ts, tw_event_data(), tw_now(), tw_timer_reset(), and Host_State::unack.
void tcp_init ()
void tcp_router_eventhandler (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
void tcp_router_forward (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 25 of file tcp-router.c.
References Msg_Data::ack, Router_Link::buffer_sz, tw_bf::c1, tw_bf::c2, Router_Link::delay, Msg_Data::dest, Router_State::dropped_packets, FORWARD, g_hosts_info, g_routers, g_routers_links, tw_lp::id, Router_State::lastsent, Router_Link::link_speed, Msg_Data::RC, RC::rtt_time, Msg_Data::seq_num, Msg_Data::source, TCP_HEADER_SIZE, TCP_TRANSFER_SIZE, tcp_util_event(), tcp_util_nexthop(), tcp_util_nexthop_link(), tw_now(), and tw_rand_unif.
Referenced by tcp_router_EventHandler().
void tcp_router_forward_rc (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 13 of file tcp-router-rc.c.
References tw_bf::c1, tw_bf::c2, Msg_Data::dest, Router_State::dropped_packets, tw_lp::id, Router_State::lastsent, Msg_Data::RC, RC::rtt_time, tcp_util_nexthop_link(), and tw_rand_reverse_unif.
Referenced by tcp_router_rc_EventHandler().
void tcp_router_rc_eventhandler (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
void tcp_router_startUp (Router_State * SV, tw_lp * lp)
void tcp_router_statistics_collectStats (Router_State * SV, tw_lp * lp)
void tcp_util_event (tw_lp * lp, int type, int source, int dest, int seq_num, int ack, double ts)
Definition at line 92 of file tcp-util.c.
References Msg_Data::ack, Msg_Data::dest, Msg_Data::MethodName, Msg_Data::seq_num, Msg_Data::source, tcp_util_nexthop(), tw_event_data(), tw_event_new(), and tw_event_send().
Referenced by tcp_host_process_ack(), tcp_host_process_data(), tcp_host_startup(), tcp_host_timeout(), and tcp_router_forward().
tw_lpid tcp_util_nexthop (tw_lp * lp, int dest)
Definition at line 13 of file tcp-util.c.
References Router_Link::connected, Host_Link::connected, CORE_ROUTERS, g_hosts_links, g_new_routing_table, g_num_links, g_routers, g_routers_links, g_routing_table, g_type, tw_lp::id, and tw_getlp().
Referenced by tcp_router_forward(), and tcp_util_event().
int tcp_util_nexthop_link (tw_lp * lp, int dest)
Definition at line 57 of file tcp-util.c.
References CORE_ROUTERS, g_new_routing_table, g_num_links, g_routers, g_routing_table, g_type, and tw_lp::id.
Referenced by tcp_router_forward(), and tcp_router_forward_rc().
Variable Documentation
int g_frequency
Definition at line 14 of file tcp-globals.c.
Referenced by tcp_host_process_ack(), tcp_host_startup(), tcp_host_Statistics_CollectStats(), and tcp_host_update_rtt().
int g_hosts
Definition at line 7 of file tcp-globals.c.
Host_Info* g_hosts_info
Definition at line 23 of file tcp-globals.c.
Referenced by tcp_host_process(), tcp_host_process_data(), tcp_host_process_rc(), tcp_host_startup(), and tcp_router_forward().
Host_Link* g_hosts_links
Definition at line 22 of file tcp-globals.c.
Referenced by tcp_host_process_ack(), tcp_host_process_data(), tcp_host_startup(), tcp_host_timeout(), and tcp_util_nexthop().
int g_iss
Definition at line 11 of file tcp-globals.c.
Referenced by tcp_host_process_ack(), and tcp_host_timeout().
int g_mss
Definition at line 13 of file tcp-globals.c.
Referenced by tcp_host_process_ack(), tcp_host_process_ack_rc(), tcp_host_process_data(), tcp_host_process_data_rc(), tcp_host_startup(), tcp_host_timeout(), and tcp_host_update_cwnd().
char** g_new_routing_table
Definition at line 18 of file tcp-globals.c.
Referenced by tcp_util_nexthop(), and tcp_util_nexthop_link().
int g_nkp
Definition at line 10 of file tcp-globals.c.
int g_npe
Definition at line 9 of file tcp-globals.c.
int g_num_links
Definition at line 16 of file tcp-globals.c.
Referenced by tcp_util_nexthop(), and tcp_util_nexthop_link().
int g_recv_wnd
Definition at line 12 of file tcp-globals.c.
Referenced by tcp_host_process_ack(), tcp_host_process_data(), tcp_host_process_data_rc(), tcp_host_startup(), tcp_host_timeout(), and tcp_host_update_cwnd().
int g_routers
Definition at line 8 of file tcp-globals.c.
int* g_routers_info
Definition at line 21 of file tcp-globals.c.
Referenced by tcp_router_StartUp().
Router_Link** g_routers_links
Definition at line 20 of file tcp-globals.c.
Referenced by tcp_router_forward(), and tcp_util_nexthop().
Routing_Table** g_routing_table
Definition at line 19 of file tcp-globals.c.
Referenced by tcp_util_nexthop(), and tcp_util_nexthop_link().
Tcp_Statistics g_tcp_stats
Definition at line 10 of file tcp-global.c.
int g_type
Definition at line 15 of file tcp-globals.c.
Referenced by tcp_util_nexthop(), and tcp_util_nexthop_link().
int number_of_nodes
Definition at line 7 of file tcp-init.c.
Referenced by main(), and read_rocketfuel_file().