ROSS: ross/hash-quadratic.c File Reference
hash-quadratic.c File Reference
#include <ross.h>
#include <assert.h>
#include "avl_tree.h"
Functions
static void rehash (tw_hash *hash_t, int pe)
static int find_empty (tw_event **hash_t, tw_event *event, int hash_size)
static int find_entry (tw_event **hash_t, tw_event *event, int hash_size, int pe)
static void insert (tw_event **hash_t, tw_event *event, int hash_size)
static tw_event ** allocate_table (int hash_size)
static int hash_ (tw_eventid event_id, int hash_size)
static int next_prime (int ptst)
static int is_prime (int ptst)
tw_event * hash_search (tw_event **hash_t, tw_event *evt, int size)
void hash_print (tw_hash *h)
void * tw_hash_create ()
void tw_hash_insert (void *h, tw_event *event, int pe)
tw_event * tw_hash_remove (void *h, tw_event *event, int pe)
Variables
AvlTree avl_tree = NULL
AvlTree avl_list = NULL
AvlTree avl_list_head = NULL
unsigned avl_tree_size
static unsigned int ncpu = 1
unsigned int g_tw_hash_size = 31
Function Documentation
tw_event ** allocate_table (int hash_size) static
Definition at line 202 of file hash-quadratic.c.
References tw_calloc(), and TW_LOC.
Referenced by rehash(), and tw_hash_create().
int find_empty (tw_event ** hash_t, tw_event * event, int hash_size) static
Definition at line 155 of file hash-quadratic.c.
References tw_event::event_id, hash_(), tw_error(), and TW_LOC.
Referenced by insert().
int find_entry (tw_event ** hash_t, tw_event * event, int hash_size, int pe) static
Definition at line 177 of file hash-quadratic.c.
References tw_event::event_id, hash_(), tw_error(), and TW_LOC.
Referenced by tw_hash_remove().
int hash_ (tw_eventid event_id, int hash_size) static
Definition at line 36 of file hash-quadratic.c.
Referenced by find_empty(), and find_entry().
void hash_print (tw_hash * h)
Definition at line 300 of file hash-quadratic.c.
References tw_hash::hash_sizes, tw_hash::incoming, ncpu, and tw_hash::num_stored.
tw_event * hash_search (tw_event ** hash_t, tw_event * evt, int size)
Definition at line 277 of file hash-quadratic.c.
References tw_event::event_id, and g_tw_mynode.
void insert (tw_event ** hash_t, tw_event * event, int hash_size) static
Definition at line 112 of file hash-quadratic.c.
References find_empty().
Referenced by rehash(), and tw_hash_insert().
int is_prime (int ptst) static
Definition at line 253 of file hash-quadratic.c.
Referenced by next_prime(), and tw_hash_create().
int next_prime (int ptst) static
Definition at line 233 of file hash-quadratic.c.
References is_prime().
Referenced by rehash(), and tw_hash_create().
void rehash (tw_hash * hash_t, int pe) static
Definition at line 121 of file hash-quadratic.c.
References allocate_table(), tw_hash::hash_sizes, tw_hash::incoming, insert(), next_prime(), tw_hash::num_stored, pe, tw_error(), and TW_LOC.
Referenced by tw_hash_insert().
void* tw_hash_create ()
Definition at line 42 of file hash-quadratic.c.
References allocate_table(), AVL_EMPTY, avl_tree_size, g_tw_hash_size, tw_hash::hash_sizes, tw_hash::incoming, is_prime(), ncpu, avlNode::next, next_prime(), tw_hash::num_stored, tw_calloc(), tw_error(), TW_LOC, and tw_nnodes().
Referenced by tw_net_start().
void tw_hash_insert (void * h, tw_event * event, int pe)
Definition at line 90 of file hash-quadratic.c.
References avl_tree_size, avlInsert(), tw_hash::hash_sizes, tw_hash::incoming, insert(), MAX_FRACTION, tw_hash::num_stored, pe, and rehash().
Referenced by recv_finish(), and tw_socket_read_event().
tw_event* tw_hash_remove (void * h, tw_event * event, int pe)
Definition at line 208 of file hash-quadratic.c.
References avl_tree_size, avlDelete(), find_entry(), tw_hash::hash_sizes, tw_hash::incoming, tw_hash::num_stored, pe, tw_error(), TW_LOC, and tw_nnodes().
Referenced by recv_finish(), tw_event_grab(), and tw_socket_read_event().
Variable Documentation
AvlTree avl_list = NULL
Definition at line 13 of file hash-quadratic.c.
AvlTree avl_list_head = NULL
Definition at line 14 of file hash-quadratic.c.
Referenced by avl_alloc().
AvlTree avl_tree = NULL
Definition at line 10 of file hash-quadratic.c.
unsigned avl_tree_size
Definition at line 16 of file hash-quadratic.c.
Referenced by gvt_print(), tw_hash_create(), tw_hash_insert(), and tw_hash_remove().
unsigned int g_tw_hash_size = 31
Definition at line 33 of file hash-quadratic.c.
Referenced by tw_hash_create().
unsigned int ncpu = 1 static
Definition at line 32 of file hash-quadratic.c.
Referenced by hash_print(), and tw_hash_create().