ROSS: ross/models/tcp-ip/ip-packet.c File Reference
ip-packet.c File Reference
#include <ip.h>
Functions
void ip_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-packet.c.
References tw_pe::abort_event, DOWNSTREAM, rn_message::dst, tw_lp::gid, tw_lp::id, tw_lp::pe, rn_message::port, rn_event_new(), ip_stats::s_ndropped, ip_stats::s_ndropped_source, rn_message::size, rn_message::src, ip_state::stats, and tw_event_free().
Referenced by getroute(), and ip_downstream_forward().
void ip_rc_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 18 of file ip-packet.c.
References DOWNSTREAM, rn_message::dst, tw_lp::gid, tw_lp::id, rn_reverse_event_send(), ip_stats::s_ndropped, ip_stats::s_ndropped_source, rn_message::size, rn_message::src, and ip_state::stats.
Referenced by ip_rc_downstream(), ip_rc_event_handler(), and rc_getroute().