ROSS: ross/models/epi/queue-heap.c File Reference
queue-heap.c File Reference
#include <epi.h>
Data Structures
struct CHeap
Macros
#define KEY(e) ((((epi_agent *) e)+1)->ts_next)
#define SWAP(heap, x, y, t)
Typedefs
typedef double KEY_TYPE
typedef struct CHeap CHeap
Functions
tw_memory * HeapPeekTop (CHeap *h)
void sift_down (CHeap *h, int i)
void percolate_up (CHeap *h, int i)
void pq_enqueue (void *pq, tw_memory *e)
void * pq_dequeue (void *pq)
void DumpBucket (void *pq, FILE *fp)
void pq_delete_any (void *pq, tw_memory **q)
void * pq_create (void)
tw_stime pq_minimum (void *pq)
void * pq_top (void *pq)
void pq_cleanup (void *h)
void * pq_next (void *h, int next)
unsigned int pq_get_size (void *pq)
Macro Definition Documentation
#define KEY (e) ((((epi_agent *) e)+1)->ts_next)
Definition at line 4 of file queue-heap.c.
Referenced by DumpBucket(), percolate_up(), pq_cleanup(), pq_delete_any(), pq_minimum(), and sift_down().
#define SWAP (heap, x, y, t)
Value:
{ \
    t = heap->elems[x]; \
    heap->elems[x] = heap->elems[y]; \
    heap->elems[y] = t; \
    heap->elems[x]->heap_index = x; \
    heap->elems[y]->heap_index = y; \
    }
Definition at line 15 of file queue-heap.c.
Referenced by percolate_up(), and sift_down().
Typedef Documentation
typedef struct CHeap CHeap
Definition at line 6 of file queue-heap.c.
typedef double KEY_TYPE
Definition at line 3 of file queue-heap.c.
Function Documentation
void DumpBucket (void * pq, FILE * fp)
Definition at line 110 of file queue-heap.c.
References CHeap::elems, KEY, and CHeap::nelems.
tw_memory* HeapPeekTop (CHeap * h) inline
Definition at line 24 of file queue-heap.c.
References CHeap::elems, and CHeap::nelems.
void percolate_up (CHeap * h, int i)
Definition at line 49 of file queue-heap.c.
References CHeap::elems, KEY, CHeap::nelems, p, and SWAP.
void pq_cleanup (void * h)
Definition at line 183 of file queue-heap.c.
References KEY, pq_delete_any(), pq_enqueue(), pq_get_size(), pq_minimum(), and pq_next().
Referenced by epi_event_handler().
void* pq_create (void)
Definition at line 151 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, and CHeap::nelems.
Referenced by epi_init_agent(), epi_init_agent_default(), and epi_xml().
void pq_delete_any (void * pq, tw_memory ** q)
Definition at line 125 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, KEY, CHeap::nelems, percolate_up(), and sift_down().
void* pq_dequeue (void * pq)
Definition at line 93 of file queue-heap.c.
References CHeap::elems, epi_agent::heap_index, CHeap::nelems, and sift_down().
Referenced by epi_agent_remove(), and epi_agent_stage_tran().
void pq_enqueue (void * pq, tw_memory * e)
Definition at line 70 of file queue-heap.c.
References CHeap::curr_max, CHeap::elems, CHeap::nelems, and percolate_up().
unsigned int pq_get_size (void * pq)
Definition at line 215 of file queue-heap.c.
Referenced by epi_agent_add(), epi_event_handler(), epi_init(), epi_seir_compute(), and pq_cleanup().
tw_stime pq_minimum (void * pq)
Definition at line 166 of file queue-heap.c.
References HeapPeekTop(), and KEY.
Referenced by pq_cleanup().
void* pq_next (void * h, int next)
Definition at line 209 of file queue-heap.c.
Referenced by epi_init(), epi_seir_compute(), and pq_cleanup().
void* pq_top (void * pq)
Definition at line 175 of file queue-heap.c.
References HeapPeekTop().
Referenced by epi_agent_remove(), epi_init(), epi_location_timer(), epi_num_check_report(), and timer_helper().
void sift_down (CHeap * h, int i)
Definition at line 30 of file queue-heap.c.
References CHeap::elems, KEY, CHeap::nelems, and SWAP.