ROSS: ross/models/epi/epi-num.c File Reference
epi-num.c File Reference
#include <epi.h>
Functions
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
Function Documentation
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 4 of file epi-num.c.
References g_epi_mod, g_epi_next_report_day, g_epi_nreport_days, g_epi_report_days, tw_lp::id, epi_agent::loc, epi_agent::num, rn_event_direct(), rn_event_send(), rn_message::ttl, tw_event_data(), tw_now(), and TWENTY_FOUR_HOURS.
Referenced by epi_agent_add_back(), and epi_event_handler().
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 53 of file epi-num.c.
References tw_lp::id, epi_agent::loc, epi_agent::num, rn_event_direct(), rn_event_send(), tw_event::state, rn_message::ttl, tw_error(), tw_event_data(), and TW_LOC.
Referenced by epi_agent_remove(), and epi_event_handler().