ROSS: ross/ross-extern.h File Reference
ross-extern.h File Reference
Macros
#define TW_LOC __FILE__,__LINE__
Functions
void tw_rand_init_streams (tw_lp *lp, unsigned int nstreams)
void tw_stats (tw_pe *me)
tw_pq * tw_pq_create (void)
void tw_pq_enqueue (tw_pq *, tw_event *)
tw_event * tw_pq_dequeue (tw_pq *)
tw_stime tw_pq_minimum (tw_pq *)
void tw_pq_delete_any (tw_pq *, tw_event *)
unsigned int tw_pq_get_size (tw_pq *)
unsigned int tw_pq_max_size (tw_pq *)
const tw_optdef * tw_clock_setup ()
void tw_clock_init (tw_pe *me)
tw_clock tw_clock_now (tw_pe *me)
tw_clock tw_clock_read ()
void tw_register_signals (void)
void tw_event_send (tw_event *event)
void tw_event_rollback (tw_event *event)
static void tw_event_free (tw_pe *, tw_event *)
static void tw_free_output_messages (tw_event *e, int print_message)
tw_lp * tw_lp_next_onpe (tw_lp *last, tw_pe *pe)
void tw_lp_settype (tw_lpid lp, const tw_lptype *type)
void tw_lp_onpe (tw_lpid index, tw_pe *pe, tw_lpid id)
void tw_lp_onkp (tw_lp *lp, tw_kp *kp)
void tw_init_lps (tw_pe *me)
void tw_kp_onpe (tw_kpid id, tw_pe *pe)
void kp_fossil_remote (tw_kp *kp)
tw_kp * tw_kp_next_onpe (tw_kp *last, tw_pe *pe)
void tw_init_kps (tw_pe *me)
tw_out * tw_kp_grab_output_buffer (tw_kp *kp)
void tw_kp_put_back_output_buffer (tw_out *out)
void tw_kp_rollback_event (tw_event *event)
void tw_kp_rollback_to (tw_kp *kp, tw_stime to)
void tw_kp_fossil_memoryq (tw_kp *me, tw_fd)
void tw_kp_fossil_memory (tw_kp *me)
tw_pe * tw_pe_next (tw_pe *last)
void tw_pe_settype (tw_pe *, const tw_petype *type)
void tw_pe_create (tw_peid npe)
void tw_pe_init (tw_peid id, tw_peid global)
void tw_pe_fossil_collect (tw_pe *me)
tw_fd tw_pe_memory_init (tw_pe *pe, size_t n_mem, size_t d_sz, tw_stime mult)
void tw_init (int *argc, char ***argv)
void tw_define_lps (tw_lpid nlp, size_t msg_sz, tw_seed *seed)
void tw_run (void)
void tw_end (void)
void tw_scheduler_sequential (tw_pe *me)
void tw_scheduler_conservative (tw_pe *me)
void tw_scheduler_optimistic (tw_pe *me)
void tw_scheduler_optimistic_debug (tw_pe *me)
void tw_sigsegv (int sig)
void tw_sigterm (int sig)
void tw_state_save (tw_lp *lp, tw_event *cevent)
void tw_state_rollback (tw_lp *lp, tw_event *revent)
void tw_state_alloc (tw_lp *lp, int nvect)
void tw_wall_now (tw_wtime *t)
void tw_wall_sub (tw_wtime *r, tw_wtime *a, tw_wtime *b)
double tw_wall_to_double (tw_wtime *t)
int tw_output (tw_lp *lp, const char *fmt,...)
void tw_error (const char *file, int line, const char *fmt,...) NORETURN
void tw_printf (const char *file, int line, const char *fmt,...)
void tw_exit (int rv)
void tw_calloc_stats (size_t *alloc, size_t *waste)
void * tw_calloc (const char *file, int line, const char *for_who, size_t e_sz, size_t n)
void * tw_unsafe_realloc (const char *file, int line, const char *for_who, void *addr, size_t len)
Variables
tw_synch g_tw_synchronization_protocol
map_local_f g_tw_custom_lp_global_to_local_map
map_custom_f g_tw_custom_initial_mapping
tw_lp_map g_tw_mapping
tw_lpid g_tw_nlp
tw_lpid g_tw_lp_offset
tw_kpid g_tw_nkp
tw_lp ** g_tw_lp
tw_kp ** g_tw_kp
int g_tw_sv_growcnt
int g_tw_fossil_attempts
unsigned int g_tw_nRNG_per_lp
tw_lpid g_tw_rng_default
size_t g_tw_rng_max
tw_seed * g_tw_rng_seed
unsigned int g_tw_mblock
unsigned int g_tw_gvt_interval
tw_stime g_tw_ts_end
unsigned int g_tw_sim_started
unsigned int g_tw_master
size_t g_tw_msg_sz
size_t g_tw_event_msg_sz
unsigned int g_tw_memory_nqueues
size_t g_tw_memory_sz
unsigned int g_tw_periodicity
tw_stime g_tw_lookahead
tw_stime g_tw_min_detected_offset
tw_peid g_tw_npe
tw_pe ** g_tw_pe
unsigned int g_tw_events_per_pe
unsigned int g_tw_events_per_pe_extra
unsigned int g_tw_gvt_threshold
unsigned int g_tw_gvt_done
unsigned int g_tw_net_device_size
tw_node g_tw_mynode
tw_node g_tw_masternode
FILE * g_tw_csv
tw_clock g_tw_cycles_gvt
tw_clock g_tw_cycles_ev_abort
tw_clock g_tw_cycles_ev_proc
tw_clock g_tw_cycles_ev_queue
tw_clock g_tw_cycles_rbs
tw_clock g_tw_cycles_cancel
tw_stime g_tw_clock_rate
Macro Definition Documentation
#define TW_LOC __FILE__,__LINE__
Definition at line 193 of file ross-extern.h.
Referenced by _rm_event_handler(), _rm_init(), _rm_rc_event_handler(), _tlm_event_handler(), _tlm_init(), _tlm_rc_event_handler(), agent_stage_tran(), allocate_table(), apply_opt(), avl_alloc(), avlDelete(), avlInsert(), bgp_event_handler(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_lsa_find(), bgp_main(), bgp_ospf_flush(), bgp_route_add(), bgp_route_copy(), bgp_route_free(), bgp_setup_ases(), bgp_setup_options(), bgp_update(), bgp_update_all(), bgp_update_send(), bgp_xml(), Cell_CompletionCall(), Cell_ComputeMove(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), CellMapping_to_local_index(), CellMapping_to_lp(), change_direction(), early_sanity_check(), epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_disease_init(), epi_event_handler(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), epi_location_timer(), epi_main(), epi_num_check_report(), epi_num_remove(), epi_seir_compute(), epi_setup_options(), epi_timer_cancel(), epi_timer_start(), epi_xml(), event_cancel(), find_empty(), find_entry(), forward(), ftp_event_handler(), ftp_rc_event_handler(), getlsa(), init_default_ic_stages(), init_default_profiles(), init_ic_stages_from_file(), init_nodes(), init_output_messages(), init_profiles_from_file(), init_q(), init_rib(), init_socket(), init_stream(), ip_downstream_forward(), ip_event_handler(), ip_init(), ip_md_final(), ip_md_init(), ip_rc_downstream(), ip_rc_event_handler(), late_sanity_check(), main(), main_setup_areas(), map_linear(), mem_alloc(), mem_event_handler(), mem_event_handler_rc(), mem_stats_print(), mem_verify(), neighbor_init(), network_spawn(), num_file_complete(), num_init(), num_init_scenario(), num_main(), num_rc_event_handler(), num_setup_options(), num_start(), num_timer_cancel(), num_timer_start(), num_update(), num_xml(), olsr_change_region(), olsr_custom_mapping(), olsr_departure_from_mpr(), olsr_grid_mapping(), olsr_map_to_local_index(), olsr_map_to_lp(), olsr_region_event_handler(), olsr_region_event_handler_rc(), olsr_region_init(), ospf_db_init(), ospf_db_read(), ospf_event_handler(), ospf_get_neighbor(), ospf_hello_packet(), ospf_hello_packet_rc(), ospf_interface_calc_dr(), ospf_interface_event_handler(), ospf_ip_route(), ospf_ls_request_recv(), ospf_lsa_allocate(), ospf_lsa_create(), ospf_lsa_find(), ospf_lsa_flood(), ospf_main(), ospf_nbr_event_handler(), ospf_nbr_neg_done(), ospf_nbr_reset_rc(), ospf_nbr_seqnum_mismatch(), ospf_nbr_two_way_recv(), ospf_rc_event_handler(), ospf_routing_init(), ospf_rt_timer(), ospf_setup_options(), ospf_startup(), ospf_xml(), pcs_grid_mapping(), phold_event_handler(), pm_event_handler(), pm_init(), pm_init_scenario(), pm_move(), pm_pe_final(), pm_rc_event_handler(), read_vector(), recv_begin(), recv_finish(), rehash(), rm_cell_handler(), rm_getlocation(), rm_grid_init(), rm_grid_terrain(), rm_initialize(), rm_initialize_terrain(), rm_move(), rm_particle_handler(), rm_particle_send(), rm_pe_final(), rm_pe_init(), rm_rc_cell_handler(), rm_run(), rm_wave_initiate(), rn_allocate_table(), rn_event_handler(), rn_event_send(), rn_find_entry(), rn_getstream(), rn_hash_create(), rn_hash_fetch(), rn_hash_insert(), rn_hash_remove(), rn_link_getstatus(), rn_map(), rn_message_setdirection(), rn_nextmachine_onsn(), rn_print_statistics(), rn_rc_event_handler(), rn_reverse_event_send(), rn_route(), rn_setup_layers(), rn_setup_mobility(), rn_setup_streams(), rn_xml_init(), rn_xml_model(), rn_xml_topology(), rng_gen_reverse_val(), rng_init(), router_setup(), routing_init_ft_read(), routing_init_ft_write(), routing_read(), routing_write(), rp_event_handler(), rp_init(), rp_md_init(), rp_move(), rp_rc_event_handler(), rw_event_handler(), rw_init(), rw_md_init(), rw_move(), rw_rc_event_handler(), send_begin(), send_finish(), setup_pes(), socket_accept(), start_transfer(), tcp_event_handler(), tcp_host_EventHandler(), tcp_host_process_data(), tcp_host_rc_EventHandler(), tcp_init(), tcp_layer_event_handler(), tcp_layer_process_data(), tcp_layer_rc_event_handler(), tcp_md_final(), tcp_md_init(), tcp_process_ack(), tcp_process_data(), tcp_rc_event_handler(), tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_router_EventHandler(), tcp_router_rc_EventHandler(), tcp_timer_cancel(), tcp_timer_reset(), terminal_init(), test_q(), tlm_cell_handler(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), tlm_particle_handler(), tlm_particle_send(), tlm_rc_cell_handler(), tlm_xml(), tmr_init(), torus_init(), traffic_grid_mapping(), tw_client_socket_create(), tw_define_lps(), tw_event_grab(), tw_event_send(), tw_eventq_alloc(), tw_eventq_debug(), tw_getkp(), tw_getlocal_lp(), tw_getlp(), tw_getpe(), tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), tw_hash_create(), tw_hash_remove(), tw_init(), tw_init_kps(), tw_init_lps(), tw_kp_onpe(), tw_kp_rollback_event(), tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_memory_alloc(), tw_memory_alloc_rc(), tw_memory_allocate(), tw_memory_free_rc(), tw_memory_init(), tw_memoryq_debug(), tw_memoryq_init(), tw_net_barrier(), tw_net_cancel(), tw_net_destlp(), tw_net_init(), tw_net_send(), tw_net_start(), tw_net_statistics(), tw_net_stop(), tw_opt_parse(), tw_output(), tw_pe_create(), tw_pe_init(), tw_pe_settype(), tw_pq_create(), tw_pq_delete_any(), tw_pq_dequeue(), tw_pq_enqueue(), tw_pq_minimum(), tw_rand_init_streams(), tw_rand_normal01(), tw_run(), tw_sched_batch(), tw_sched_cancel_q(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), tw_server_socket_create(), tw_sigsegv(), tw_sigterm(), tw_socket_create_onport(), tw_socket_read(), tw_socket_read_event(), tw_socket_send(), tw_socket_send_event(), tw_state_alloc(), tw_timer_cancel(), tw_timer_event_send(), tw_wall_now(), update_add(), verify_topology(), wifi_access_point_event_handler(), wifi_access_point_event_handler_rc(), and xml_link_topology().
Function Documentation
void kp_fossil_remote (tw_kp * kp)
void* tw_calloc (const char * file, int line, const char * for_who, size_t e_sz, size_t n)
Definition at line 170 of file tw-util.c.
References pool_alloc(), and tw_error().
Referenced by _rm_init(), _tlm_init(), allocate_table(), epi_disease_init(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), epi_main(), epi_setup_options(), epi_xml(), init_default_ic_stages(), init_default_profiles(), init_ic_stages_from_file(), init_nodes(), init_output_messages(), init_profiles_from_file(), init_q(), init_socket(), ip_init(), ip_md_init(), main(), num_init(), num_init_scenario(), num_main(), num_setup_options(), num_xml(), ospf_main(), ospf_routing_init(), ospf_setup_options(), ospf_startup(), pm_init(), read_vector(), rm_getlocation(), rm_grid_terrain(), rm_initialize(), rm_initialize_terrain(), rm_pe_init(), rn_allocate_table(), rn_hash_create(), rn_setup_mobility(), rn_setup_streams(), rn_xml_topology(), rng_init(), router_setup(), routing_init_ft_write(), routing_read(), rp_init(), rp_md_init(), rw_init(), rw_md_init(), tcp_init(), tcp_md_init(), terminal_init(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tmr_init(), torus_init(), tw_define_lps(), tw_eventq_alloc(), tw_hash_create(), tw_init_kps(), tw_kp_onpe(), tw_lp_onpe(), tw_memory_allocate(), tw_memoryq_init(), tw_net_start(), tw_net_statistics(), tw_pe_create(), tw_pe_init(), tw_pq_create(), tw_rand_init_streams(), tw_socket_create_onport(), and tw_state_alloc().
void tw_calloc_stats (size_t * alloc, size_t * waste)
Definition at line 113 of file tw-util.c.
References mem_pool::end_free, mem_pool::next_free, mem_pool::next_pool, p, and total_allocated.
Referenced by tw_stats().
void tw_clock_init (tw_pe * me)
Definition at line 29 of file clock-amd64.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
Referenced by tw_sched_init().
tw_clock tw_clock_now (tw_pe * me)
Definition at line 36 of file clock-amd64.c.
References tw_pe::clock_offset, tw_pe::clock_time, and tw_clock_read().
Referenced by tw_gvt_inprogress(), and tw_gvt_step1().
tw_clock tw_clock_read ()
Definition at line 16 of file clock-bgl.c.
const tw_optdef* tw_clock_setup ()
Definition at line 21 of file clock-amd64.c.
References clock_opts.
Referenced by tw_init().
void tw_define_lps (tw_lpid nlp, size_t msg_sz, tw_seed * seed)
IMPORTANT: This function sets the value for g_tw_nlp which is a rather important global variable. It is also set in (very few) other places, but mainly just here.
Definition at line 196 of file tw-setup.c.
References CUSTOM, early_sanity_check(), g_tw_custom_initial_mapping, g_tw_kp, g_tw_lp, g_tw_mapping, g_tw_memory_sz, g_tw_msg_sz, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_nRNG_per_lp, g_tw_rng_default, g_tw_rng_seed, LINEAR, map_linear(), map_round_robin(), nkp_per_pe, nlp, ROUND_ROBIN, seed, tw_calloc(), tw_error(), TW_LOC, tw_rand_init_streams(), and TW_TRUE.
Referenced by main(), and rm_initialize().
void tw_end (void)
Definition at line 390 of file tw-setup.c.
References g_tw_csv, tw_ismaster(), and tw_net_stop().
Referenced by main(), and rm_end().
void tw_error (const char * file, int line, const char * fmt, ...)
Definition at line 74 of file tw-util.c.
References g_tw_mynode, and tw_net_abort().
Referenced by _rm_event_handler(), _rm_init(), _rm_rc_event_handler(), _tlm_event_handler(), _tlm_init(), _tlm_rc_event_handler(), agent_stage_tran(), apply_opt(), avl_alloc(), avlDelete(), avlInsert(), bgp_event_handler(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_lsa_find(), bgp_main(), bgp_ospf_flush(), bgp_route_add(), bgp_route_copy(), bgp_route_free(), bgp_setup_ases(), bgp_setup_options(), bgp_update(), bgp_update_all(), bgp_update_send(), bgp_xml(), Cell_CompletionCall(), Cell_ComputeMove(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), CellMapping_to_local_index(), CellMapping_to_lp(), change_direction(), early_sanity_check(), epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_event_handler(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), epi_location_timer(), epi_main(), epi_num_check_report(), epi_num_remove(), epi_seir_compute(), epi_setup_options(), epi_timer_cancel(), epi_timer_start(), epi_xml(), event_cancel(), find_empty(), find_entry(), forward(), ftp_event_handler(), ftp_rc_event_handler(), getlsa(), init_ic_stages_from_file(), init_nodes(), init_profiles_from_file(), init_rib(), init_stream(), ip_downstream_forward(), ip_event_handler(), ip_md_final(), ip_md_init(), ip_rc_downstream(), ip_rc_event_handler(), late_sanity_check(), main(), main_setup_areas(), map_linear(), mem_alloc(), mem_event_handler(), mem_event_handler_rc(), mem_stats_print(), mem_verify(), neighbor_init(), network_spawn(), num_file_complete(), num_init_scenario(), num_rc_event_handler(), num_setup_options(), num_start(), num_timer_cancel(), num_timer_start(), num_update(), olsr_change_region(), olsr_custom_mapping(), olsr_departure_from_mpr(), olsr_grid_mapping(), olsr_map_to_local_index(), olsr_map_to_lp(), olsr_region_event_handler(), olsr_region_event_handler_rc(), olsr_region_init(), ospf_db_init(), ospf_db_read(), ospf_event_handler(), ospf_get_neighbor(), ospf_hello_packet(), ospf_hello_packet_rc(), ospf_interface_calc_dr(), ospf_interface_event_handler(), ospf_ip_route(), ospf_ls_request_recv(), ospf_lsa_allocate(), ospf_lsa_create(), ospf_lsa_find(), ospf_lsa_flood(), ospf_main(), ospf_nbr_event_handler(), ospf_nbr_neg_done(), ospf_nbr_reset_rc(), ospf_nbr_seqnum_mismatch(), ospf_nbr_two_way_recv(), ospf_rc_event_handler(), ospf_routing_init(), ospf_rt_timer(), ospf_setup_options(), ospf_xml(), pcs_grid_mapping(), phold_event_handler(), pm_event_handler(), pm_init(), pm_init_scenario(), pm_pe_final(), pm_rc_event_handler(), recv_begin(), recv_finish(), rehash(), rm_cell_handler(), rm_getlocation(), rm_grid_init(), rm_grid_terrain(), rm_initialize(), rm_move(), rm_particle_handler(), rm_particle_send(), rm_pe_final(), rm_pe_init(), rm_rc_cell_handler(), rm_run(), rm_wave_initiate(), rn_event_handler(), rn_event_send(), rn_find_entry(), rn_getstream(), rn_hash_create(), rn_hash_fetch(), rn_hash_insert(), rn_hash_remove(), rn_link_getstatus(), rn_map(), rn_message_setdirection(), rn_nextmachine_onsn(), rn_print_statistics(), rn_rc_event_handler(), rn_reverse_event_send(), rn_route(), rn_setup_layers(), rn_setup_streams(), rn_xml_init(), rn_xml_model(), rn_xml_topology(), rng_gen_reverse_val(), routing_init_ft_read(), routing_init_ft_write(), routing_read(), routing_write(), rp_event_handler(), rp_rc_event_handler(), rw_event_handler(), rw_rc_event_handler(), send_begin(), send_finish(), setup_pes(), socket_accept(), start_transfer(), tcp_event_handler(), tcp_host_EventHandler(), tcp_host_process_data(), tcp_host_rc_EventHandler(), tcp_layer_event_handler(), tcp_layer_process_data(), tcp_layer_rc_event_handler(), tcp_md_final(), tcp_md_init(), tcp_process_ack(), tcp_process_data(), tcp_rc_event_handler(), tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_router_EventHandler(), tcp_router_rc_EventHandler(), tcp_timer_cancel(), tcp_timer_reset(), test_q(), tlm_cell_handler(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), tlm_particle_handler(), tlm_particle_send(), tlm_rc_cell_handler(), tlm_xml(), tmr_init(), traffic_grid_mapping(), tw_calloc(), tw_client_socket_create(), tw_define_lps(), tw_event_send(), tw_eventq_alloc(), tw_eventq_debug(), tw_getkp(), tw_getlocal_lp(), tw_getlp(), tw_getpe(), tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), tw_hash_create(), tw_hash_remove(), tw_init(), tw_init_lps(), tw_kp_onpe(), tw_kp_rollback_event(), tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_memory_alloc(), tw_memory_alloc_rc(), tw_memory_allocate(), tw_memory_free_rc(), tw_memory_init(), tw_memoryq_debug(), tw_memoryq_init(), tw_net_barrier(), tw_net_cancel(), tw_net_destlp(), tw_net_init(), tw_net_send(), tw_net_start(), tw_net_statistics(), tw_net_stop(), tw_opt_parse(), tw_pe_init(), tw_pe_settype(), tw_pq_delete_any(), tw_pq_dequeue(), tw_pq_minimum(), tw_rand_init_streams(), tw_rand_normal01(), tw_run(), tw_sched_batch(), tw_sched_cancel_q(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), tw_server_socket_create(), tw_sigsegv(), tw_sigterm(), tw_socket_create_onport(), tw_socket_read(), tw_socket_read_event(), tw_socket_send(), tw_socket_send_event(), tw_timer_cancel(), tw_timer_event_send(), tw_unsafe_realloc(), tw_wall_now(), update_add(), verify_topology(), wifi_access_point_event_handler(), wifi_access_point_event_handler_rc(), and xml_link_topology().
static void tw_event_free (tw_pe * , tw_event *) inline static
Referenced by event_cancel(), ip_packet_drop(), recv_begin(), recv_finish(), send_finish(), tw_eventq_push_list(), tw_net_cancel(), tw_sched_cancel_q(), tw_scheduler_conservative(), tw_scheduler_sequential(), tw_socket_read_event(), and tw_timer_cancel().
void tw_event_rollback (tw_event * event)
Definition at line 158 of file tw-event.c.
References tw_event::cause_next, tw_event::caused_by_me, event_cancel(), tw_lp::kp, tw_kp::s_e_rbs, tw_free_output_messages(), and tw_state_rollback().
Referenced by tw_kp_rollback_event(), tw_kp_rollback_to(), and tw_sched_batch().
void tw_event_send (tw_event * event)
Definition at line 12 of file tw-event.c.
References tw_pe::abort_event, tw_pe::cev_abort, CONSERVATIVE, tw_pe::cur_event, tw_event::dest_lp, tw_pe::event_q, g_tw_lookahead, g_tw_mynode, g_tw_synchronization_protocol, g_tw_ts_end, tw_lp::kp, tw_kp::last_time, link_causality(), tw_lptype::map, min, tw_event::out_msgs, tw_lp::pe, tw_pe::pq, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_pe::stats, tw_pe::trans_msg_ts, tw_error(), tw_eventq_push(), tw_getlocal_lp(), tw_gvt_inprogress(), TW_LOC, TW_net_asend, tw_net_onnode(), tw_net_send(), tw_node_eq(), tw_now(), TW_pe_event_q, tw_pq_enqueue(), and tw_lp::type.
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_agent_send(), event_handler(), ForwardDefault(), ForwardPacket(), init(), insert_into_pq(), Intersection_EventHandler(), Intersection_StartUp(), ip_downstream_forward(), ip_downstream_source(), ip_upstream(), Link_DeQueue(), Link_EnQueue(), mem_event_handler(), mem_init(), mpi_init(), mpi_msg_send(), olsr_change_region(), olsr_departure_from_mpr(), olsr_event(), olsr_init(), olsr_region_init(), olsr_station_to_mpr(), ospf_flood_recv(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), phold_event_handler(), phold_init(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_controller_gen_send(), raid_disk_gen_send(), raid_io_gen_send(), ReadAgentAct(), ReadGroupOp(), rm_cell_gather(), rm_cell_scatter(), rm_particle_send(), rm_proximity_send(), rm_wave_initiate(), rn_event_handler(), rn_event_send(), rn_link_random_weight_changes(), rn_setup_links(), rn_timer_simple(), rngt_init(), route_packet(), Router_Arrival(), router_credit_send(), router_packet_receive(), router_packet_send(), Router_Recv(), router_reschedule_event(), rp_move(), rw_move(), sa_master_event(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), srw_event(), srw_init(), tcp_event_send(), tcp_util_event(), tlm_cell_gather(), tlm_cell_scatter(), tlm_particle_send(), tlm_proximity_send(), tlm_wave_initiate(), tmr_event_handler(), tmr_init(), wifi_access_point_arrival(), and wifi_station_arrival().
void tw_exit (int rv)
Definition at line 90 of file tw-util.c.
References tw_net_stop().
Referenced by AddExtPkt(), Cell_CompletionCall(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), ForwardPacket(), ForwardUnicastPkt(), GetExtPktRef(), GmccRcvInit(), GmccRcvPktHandler(), GmccRcvProcCtrlPkt(), GmccSrcInit(), GmccSrcPktHandler(), GmccSrcTimer(), McastEventHandler(), OrmccRcvInit(), OrmccRcvPktHandler(), OrmccRcvTimer(), OrmccSrcInit(), OrmccSrcPktHandler(), OrmccSrcTimer(), PassPktToUpperLayer(), PgmccRcvInit(), PgmccRcvPktHandler(), PgmccRcvSendPkt(), PgmccSrcInit(), PgmccSrcPktHandler(), PgmccSrcTimer(), RegisterAgent(), RegisterAgentCopy(), ScheduleTimer(), ScheduleTimerWithSn(), SetExtPktRef(), tcp_host_EventHandler(), tcp_host_rc_EventHandler(), tcp_router_EventHandler(), tcp_router_rc_EventHandler(), TfmccRcvAddPktToHistory(), TfmccRcvEstLoss(), TfmccRcvInit(), TfmccRcvPktHandler(), TfmccSrcInit(), and TfmccSrcPktHandler().
static void tw_free_output_messages (tw_event * e, int print_message) inline static
Referenced by tw_event_rollback(), and tw_eventq_push_list().
void tw_init (int * argc, char *** argv)
Definition at line 29 of file tw-setup.c.
References g_tw_csv, ROSS_VERSION, tw_clock_setup(), tw_error(), tw_gvt_setup(), tw_gvt_start(), tw_ismaster(), TW_LOC, tw_net_init(), tw_net_start(), tw_opt_add(), tw_opt_parse(), and tw_opt_print().
Referenced by main(), and rm_init().
void tw_init_kps (tw_pe * me)
Definition at line 116 of file tw-kp.c.
References g_tw_memory_nqueues, g_tw_nkp, g_tw_synchronization_protocol, tw_kp::id, init_output_messages(), OPTIMISTIC, tw_kp::output, tw_kp::pe, tw_kp::s_e_rbs, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_calloc(), tw_getkp(), and TW_LOC.
Referenced by tw_sched_init().
void tw_init_lps (tw_pe * me)
Definition at line 54 of file tw-lp.c.
References tw_pe::abort_event, tw_event::caused_by_me, tw_pe::cev_abort, tw_pe::cur_event, tw_lp::cur_state, g_tw_lp, g_tw_nlp, g_tw_sv_growcnt, tw_lptype::init, tw_lp::pe, tw_lptype::revent, tw_error(), TW_LOC, tw_state_alloc(), and tw_lp::type.
Referenced by tw_sched_init().
void tw_kp_fossil_memory (tw_kp * me)
Definition at line 233 of file tw-kp.c.
References g_tw_memory_nqueues, and tw_kp_fossil_memoryq().
Referenced by tw_pe_fossil_collect().
void tw_kp_fossil_memoryq (tw_kp * me, tw_fd)
Definition at line 173 of file tw-kp.c.
References tw_pe::GVT, tw_kp::id, tw_kp::pe, and tw_memoryq_push_list().
Referenced by tw_kp_fossil_memory(), and tw_memory_alloc().
tw_out* tw_kp_grab_output_buffer (tw_kp * kp)
Definition at line 145 of file tw-kp.c.
References tw_out::next, and tw_kp::output.
Referenced by tw_output().
tw_kp* tw_kp_next_onpe (tw_kp * last, tw_pe * pe)
void tw_kp_onpe (tw_kpid id, tw_pe * pe)
Definition at line 4 of file tw-kp.c.
References g_tw_kp, g_tw_nkp, tw_kp::id, pe, tw_kp::pe, tw_calloc(), tw_error(), and TW_LOC.
Referenced by dragonfly_mapping(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), torus_mapping(), and traffic_grid_mapping().
void tw_kp_put_back_output_buffer (tw_out * out)
Definition at line 158 of file tw-kp.c.
References tw_out::next, tw_kp::output, and tw_out::owner.
Referenced by tw_free_output_messages().
void tw_kp_rollback_event (tw_event * event)
Definition at line 58 of file tw-kp.c.
References tw_pe::GVT, tw_eventq::head, tw_kp::id, tw_pe::id, tw_kp::last_time, pe, tw_kp::pe, tw_kp::pevent_q, tw_pe::pq, tw_event::recv_ts, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_eventq::size, tw_error(), tw_event_rollback(), tw_eventq_shift(), TW_LOC, and tw_pq_enqueue().
Referenced by tw_sched_cancel_q().
void tw_kp_rollback_to (tw_kp * kp, tw_stime to)
Definition at line 19 of file tw-kp.c.
References tw_pe::GVT, tw_eventq::head, tw_kp::id, tw_pe::id, tw_kp::last_time, tw_kp::pe, tw_kp::pevent_q, tw_pe::pq, tw_event::recv_ts, tw_kp::s_rb_total, tw_eventq::size, tw_event_rollback(), tw_eventq_shift(), and tw_pq_enqueue().
Referenced by tw_sched_event_q(), and tw_scheduler_optimistic_debug().
tw_lp* tw_lp_next_onpe (tw_lp * last, tw_pe * pe)
void tw_lp_onkp (tw_lp * lp, tw_kp * kp)
Definition at line 45 of file tw-lp.c.
References tw_lp::kp, tw_error(), and TW_LOC.
Referenced by dragonfly_mapping(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), torus_mapping(), and traffic_grid_mapping().
void tw_lp_onpe (tw_lpid index, tw_pe * pe, tw_lpid id)
Definition at line 29 of file tw-lp.c.
References g_tw_lp, g_tw_nlp, tw_lp::gid, tw_lp::id, pe, tw_lp::pe, tw_calloc(), tw_error(), and TW_LOC.
Referenced by dragonfly_mapping(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), torus_mapping(), and traffic_grid_mapping().
void tw_lp_settype (tw_lpid id, const tw_lptype * type)
IMPORTANT: This function should be called after tw_define_lps. It copies the function pointers which define the LP to the appropriate location for each LP, i.e. you probably want to call this more than once.
Definition at line 15 of file tw-lp.c.
References g_tw_lp, g_tw_nlp, tw_lp::gid, tw_lp::pe, tw_error(), TW_LOC, and tw_lp::type.
Referenced by dragonfly_mapping(), main(), olsr_grid_mapping(), pcs_grid_mapping(), rm_initialize(), tcp_init(), tcp_layer_xml(), tlm_md_init(), torus_mapping(), and traffic_grid_mapping().
int tw_output (tw_lp * lp, const char * fmt, ...)
Rollback-aware printf, i.e. if the event gets rolled back, undo the printf. We can'd do that of course so we store the message in a buffer until GVT.
Definition at line 8 of file tw-util.c.
References tw_pe::cur_event, g_tw_synchronization_protocol, tw_kp::id, tw_lp::kp, tw_out::message, tw_out::next, OPTIMISTIC, tw_event::out_msgs, tw_lp::pe, tw_kp_grab_output_buffer(), TW_LOC, and tw_printf().
void tw_pe_create (tw_peid npe)
Definition at line 36 of file tw-pe.c.
References g_tw_npe, g_tw_pe, tw_calloc(), and TW_LOC.
Referenced by tw_net_start().
void tw_pe_fossil_collect (tw_pe * me)
Definition at line 80 of file tw-pe.c.
References g_tw_fossil_attempts, g_tw_nkp, tw_kp::pevent_q, tw_pe::sevent_q, tw_eventq_fossil_collect(), tw_getkp(), and tw_kp_fossil_memory().
Referenced by tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), and tw_gvt_wait().
void tw_pe_init (tw_peid id, tw_peid global)
Definition at line 49 of file tw-pe.c.
References g_tw_mynode, g_tw_npe, g_tw_nRNG_per_lp, g_tw_pe, g_tw_rng_default, g_tw_rng_max, tw_pe::gvt_status, tw_pe::id, tw_pe::node, pe, tw_pe::pe_next, tw_pe::rng, tw_pe::trans_msg_ts, tw_calloc(), tw_error(), TW_LOC, tw_pe_settype(), tw_rand_init(), and TW_TRUE.
Referenced by tw_net_start().
tw_fd tw_pe_memory_init (tw_pe * pe, size_t n_mem, size_t d_sz, tw_stime mult)
Referenced by tw_memory_init().
tw_pe* tw_pe_next (tw_pe * last)
Definition at line 26 of file tw-pe.c.
References g_tw_pe, and tw_pe::pe_next.
Referenced by map_linear(), olsr_custom_mapping(), tw_gvt_compute(), tw_sigsegv(), and tw_stats().
void tw_pe_settype (tw_pe * , const tw_petype * type)
Definition at line 8 of file tw-pe.c.
References copy_pef, dummy_pe_f(), tw_error(), and TW_LOC.
Referenced by main(), rm_initialize(), and tw_pe_init().
tw_pq* tw_pq_create (void)
Definition at line 425 of file queue-calendar.c.
References tw_pq::curr_max, tw_pq::elems, g_tw_events_per_pe, tw_pq::least, LocalInit(), MAX_EVENTS_PER_PE, tw_pq::nelems, tw_pq::nitems, tw_pq::OrigBucket, tw_pq::ResizeEnabled, tw_pq::root, tw_calloc(), TW_LOC, and tw_unsafe_realloc().
Referenced by setup_pes(), and test_pq().
void tw_pq_delete_any (tw_pq * , tw_event *)
Definition at line 542 of file queue-calendar.c.
References tw_pq::elems, KEY, tw_pq::least, LEFT, tw_pq::nelems, tw_event::next, tw_pq::nitems, tw_event::owner, p, percolate_up(), tw_event::prev, tw_pq::Qsize, RIGHT, tw_pq::root, sift_down(), splay(), tw_event::state, tw_error(), TW_LOC, tw_pq_dequeue(), and UP.
Referenced by event_cancel(), tw_sched_cancel_q(), tw_timer_cancel(), and tw_timer_reset().
tw_event* tw_pq_dequeue (tw_pq *)
Definition at line 40 of file queue-calendar.c.
References tw_pq::BottomThreshold, tw_pq::Bucket, tw_pq::BucketTop, Delete(), tw_pq::elems, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::least, LEFT, tw_pq::Nbuckets, tw_pq::nelems, tw_event_head::next, tw_pq::nitems, tw_event::owner, p, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, RIGHT, tw_pq::root, sift_down(), tw_event::state, tw_error(), TW_LOC, UP, and tw_pq::Width.
Referenced by NewWidth(), tw_pq_delete_any(), tw_sched_batch(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), and tw_scheduler_sequential().
void tw_pq_enqueue (tw_pq * , tw_event *)
Definition at line 142 of file queue-calendar.c.
References tw_pq::BucketTop, Insert(), KEY, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::least, LEFT, tw_pq::max_size, tw_pq::Nbuckets, tw_pq::nitems, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, RIGHT, tw_pq::root, splay(), tw_event::state, tw_pq::TopThreshold, TW_pe_pq, UP, and tw_pq::Width.
Referenced by NewWidth(), recv_finish(), ReSize(), test_pq(), tw_event_send(), tw_kp_rollback_event(), tw_kp_rollback_to(), tw_net_read(), tw_sched_batch(), tw_sched_event_q(), and tw_timer_event_send().
unsigned int tw_pq_get_size (tw_pq *)
Definition at line 555 of file queue-calendar.c.
References tw_pq::nelems, tw_pq::nitems, and tw_pq::Qsize.
Referenced by tw_stats().
unsigned int tw_pq_max_size (tw_pq *)
Definition at line 329 of file queue-splay.c.
References tw_pq::max_size.
Referenced by gvt_print().
tw_stime tw_pq_minimum (tw_pq *)
Definition at line 486 of file queue-calendar.c.
References tw_pq::Bucket, tw_pq::BucketTop, HeapPeekTop(), KEY, tw_pq::LastBucket, tw_pq::least, tw_pq::Nbuckets, tw_event_head::next, tw_pq::Qsize, tw_event::recv_ts, tw_error(), TW_LOC, and tw_pq::Width.
Referenced by test_pq(), tw_gvt_compute(), tw_gvt_step2(), tw_sched_batch(), tw_scheduler_conservative(), and tw_scheduler_sequential().
void tw_printf (const char * file, int line, const char * fmt, ...)
Definition at line 61 of file tw-util.c.
Referenced by avlInsert(), early_sanity_check(), epi_setup_options(), init_nodes(), ospf_ip_route(), pm_move(), rn_reverse_event_send(), rp_move(), rw_move(), tcp_process_data(), tw_event_grab(), tw_output(), and tw_sigsegv().
void tw_rand_init_streams (tw_lp * lp, unsigned int nstreams)
Definition at line 282 of file rand-clcg4.c.
References g_tw_rng_max, tw_lp::gid, tw_lp::rng, tw_calloc(), tw_error(), TW_LOC, and tw_rand_initial_seed().
Referenced by pm_init(), rp_init(), rw_init(), start_transfer(), and tw_define_lps().
void tw_register_signals (void)
Definition at line 5 of file signal-sigaction.c.
References tw_sigsegv(), and tw_sigterm().
void tw_run (void)
Definition at line 317 of file tw-setup.c.
References CONSERVATIVE, g_tw_synchronization_protocol, tw_pe::id, late_sanity_check(), OPTIMISTIC, OPTIMISTIC_DEBUG, SEQUENTIAL, setup_pes(), tw_error(), TW_LOC, tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), and tw_scheduler_sequential().
Referenced by main(), and rm_run().
void tw_scheduler_conservative (tw_pe * me)
Definition at line 326 of file tw-sched.c.
References tw_pe::cev_abort, tw_pe::cur_event, tw_lp::cur_state, tw_event::cv, tw_event::dest_lp, tw_pe::end_time, tw_lptype::event, tw_petype::final, tw_pe::free_q, g_tw_gvt_threshold, g_tw_lookahead, g_tw_masternode, g_tw_mblock, g_tw_mynode, g_tw_npe, g_tw_periodicity, g_tw_ts_end, tw_lp::gid, tw_pe::GVT, tw_lp::kp, tw_kp::last_time, tw_pe::local_master, tw_petype::periodic, tw_pe::pq, tw_event::recv_ts, tw_statistics::s_event_process, tw_statistics::s_net_read, tw_kp::s_nevent_processed, tw_statistics::s_pe_event_ties, tw_statistics::s_pq, tw_statistics::s_total, tw_eventq::size, tw_pe::start_time, tw_pe::stats, tw_clock_read(), tw_error(), tw_event_data(), tw_event_free(), tw_gvt_force_update(), tw_gvt_step1(), tw_gvt_step2(), TW_LOC, tw_net_barrier(), tw_net_read(), tw_nnodes(), tw_node_eq(), tw_pq_dequeue(), tw_pq_minimum(), tw_sched_event_q(), tw_sched_init(), tw_stats(), tw_wall_now(), tw_lp::type, and tw_pe::type.
Referenced by tw_run().
void tw_scheduler_optimistic (tw_pe * me)
Definition at line 430 of file tw-sched.c.
References tw_pe::end_time, tw_petype::final, g_tw_masternode, g_tw_mynode, g_tw_npe, g_tw_ts_end, tw_pe::GVT, tw_pe::local_master, tw_statistics::s_net_read, tw_statistics::s_total, tw_pe::start_time, tw_pe::stats, tw_clock_read(), tw_gvt_step1(), tw_gvt_step2(), tw_net_barrier(), tw_net_read(), tw_nnodes(), tw_node_eq(), tw_sched_batch(), tw_sched_cancel_q(), tw_sched_event_q(), tw_sched_init(), tw_stats(), tw_wall_now(), and tw_pe::type.
Referenced by tw_run().
void tw_scheduler_optimistic_debug (tw_pe * me)
Definition at line 478 of file tw-sched.c.
References tw_pe::cur_event, tw_lp::cur_state, tw_event::cv, tw_event::dest_lp, tw_pe::end_time, tw_lptype::event, tw_petype::final, tw_pe::free_q, g_tw_nkp, g_tw_rollback_time, tw_lp::kp, tw_kp::last_time, tw_event::owner, tw_kp::pevent_q, tw_pe::pq, tw_event::recv_ts, tw_kp::s_nevent_processed, tw_eventq::size, tw_pe::start_time, tw_event::state, tw_error(), tw_event_data(), tw_eventq_unshift(), TW_kp_pevent_q, tw_kp_rollback_to(), TW_LOC, tw_nnodes(), tw_pq_dequeue(), tw_sched_init(), tw_stats(), tw_wall_now(), tw_lp::type, and tw_pe::type.
Referenced by tw_run().
void tw_scheduler_sequential (tw_pe * me)
Definition at line 273 of file tw-sched.c.
References tw_pe::cev_abort, tw_pe::cur_event, tw_lp::cur_state, tw_event::cv, tw_event::dest_lp, tw_pe::end_time, tw_lptype::event, tw_petype::final, g_tw_masternode, g_tw_mynode, g_tw_ts_end, gvt_print(), tw_lp::kp, tw_kp::last_time, percent_complete, tw_pe::pq, tw_event::recv_ts, tw_kp::s_nevent_processed, tw_statistics::s_pe_event_ties, tw_pe::start_time, tw_pe::stats, tw_error(), tw_event_data(), tw_event_free(), TW_LOC, tw_nnodes(), tw_node_eq(), tw_pq_dequeue(), tw_pq_minimum(), tw_sched_init(), tw_stats(), tw_wall_now(), tw_lp::type, and tw_pe::type.
Referenced by tw_run().
void tw_sigsegv (int sig)
Definition at line 7 of file tw-signal.c.
References g_tw_sim_started, tw_pe::local_master, once, pe, tw_error(), TW_LOC, tw_net_abort(), tw_pe_next(), tw_printf(), and tw_stats().
Referenced by tw_register_signals().
void tw_sigterm (int sig)
Definition at line 42 of file tw-signal.c.
References tw_error(), TW_LOC, and tw_net_abort().
Referenced by tw_register_signals().
void tw_state_alloc (tw_lp * lp, int nvect)
Definition at line 59 of file tw-state.c.
References tw_lp::cur_state, tw_lp_state::next, tw_lp::state_qh, tw_lptype::state_sz, tw_calloc(), TW_LOC, and tw_lp::type.
Referenced by rn_setup_layers(), tw_init_lps(), and tw_state_save().
void tw_state_rollback (tw_lp * lp, tw_event * revent)
Definition at line 30 of file tw-state.c.
References tw_pe::cur_event, tw_lp::cur_state, tw_event::cv, tw_lp::kp, tw_kp::last_time, tw_lp_state::next, tw_lp::pe, tw_event::recv_ts, tw_lptype::revent, tw_lp::state_qh, tw_event_data(), and tw_lp::type.
Referenced by tw_event_rollback().
void tw_state_save (tw_lp * lp, tw_event * cevent)
Definition at line 4 of file tw-state.c.
References tw_lp::cur_state, g_tw_sv_growcnt, tw_lp_state::next, tw_lp::state_qh, tw_lptype::state_sz, tw_state_alloc(), and tw_lp::type.
void tw_stats (tw_pe * me)
Definition at line 35 of file tw-stats.c.
References CONSERVATIVE, tw_lp::cur_state, tw_pe::end_time, tw_lptype::final, g_tw_clock_rate, g_tw_csv, g_tw_events_per_pe, g_tw_fossil_attempts, g_tw_gvt_done, g_tw_min_detected_offset, g_tw_msg_sz, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_pe, g_tw_sim_started, g_tw_synchronization_protocol, max, pe, tw_pe::pq, tw_lp::rng, s, tw_statistics::s_avl, tw_statistics::s_cancel_q, tw_statistics::s_e_rbs, tw_kp::s_e_rbs, tw_statistics::s_event_abort, tw_statistics::s_event_process, tw_statistics::s_fc_attempts, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_statistics::s_max_run_time, tw_statistics::s_min_detected_offset, tw_statistics::s_net_events, tw_statistics::s_net_read, tw_statistics::s_nevent_abort, tw_statistics::s_nevent_processed, tw_kp::s_nevent_processed, tw_statistics::s_nread_network, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_statistics::s_nsend_network, tw_statistics::s_nsend_remote_rb, tw_statistics::s_pe_event_ties, tw_statistics::s_pq, tw_statistics::s_pq_qsize, tw_statistics::s_rb_primary, tw_statistics::s_rb_secondary, tw_kp::s_rb_secondary, tw_statistics::s_rb_total, tw_kp::s_rb_total, tw_statistics::s_rollback, tw_statistics::s_total, show_1f(), show_2f(), show_4f(), show_lld(), tw_pe::start_time, tw_lptype::state_sz, tw_pe::stats, tw_calloc_stats(), tw_getkp(), tw_getlp(), tw_gvt_stats(), tw_ismaster(), tw_net_statistics(), tw_nnodes(), tw_pe_next(), tw_pq_get_size(), tw_wall_sub(), tw_wall_to_double(), and tw_lp::type.
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), and tw_sigsegv().
void* tw_unsafe_realloc (const char * file, int line, const char * for_who, void * addr, size_t len)
Definition at line 213 of file tw-util.c.
References tw_error().
Referenced by tw_pq_create(), and tw_pq_enqueue().
void tw_wall_now (tw_wtime * t)
Definition at line 4 of file tw-timing.c.
References tw_error(), and TW_LOC.
Referenced by ospf_router_debug_rate(), rn_startup(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), and tw_scheduler_sequential().
void tw_wall_sub (tw_wtime * r, tw_wtime * a, tw_wtime * b)
Definition at line 11 of file tw-timing.c.
Referenced by ospf_router_debug_rate(), rn_startup(), and tw_stats().
double tw_wall_to_double (tw_wtime * t)
Definition at line 24 of file tw-timing.c.
Referenced by ospf_router_debug_rate(), rn_startup(), and tw_stats().
Variable Documentation
tw_stime g_tw_clock_rate
Definition at line 108 of file ross-global.c.
Referenced by tw_stats().
FILE* g_tw_csv
Definition at line 101 of file ross-global.c.
Referenced by setup_pes(), show_1f(), show_2f(), show_4f(), show_lld(), tw_end(), tw_init(), tw_opt_print(), and tw_stats().
map_custom_f g_tw_custom_initial_mapping
Definition at line 21 of file ross-global.c.
Referenced by main(), and tw_define_lps().
map_local_f g_tw_custom_lp_global_to_local_map
Definition at line 20 of file ross-global.c.
Referenced by main(), and tw_getlocal_lp().
tw_clock g_tw_cycles_cancel
tw_clock g_tw_cycles_ev_abort
tw_clock g_tw_cycles_ev_proc
tw_clock g_tw_cycles_ev_queue
tw_clock g_tw_cycles_gvt
tw_clock g_tw_cycles_rbs
size_t g_tw_event_msg_sz
Definition at line 45 of file ross-global.c.
Referenced by recv_finish(), send_begin(), and tw_eventq_alloc().
unsigned int g_tw_events_per_pe
Definition at line 83 of file ross-global.c.
Referenced by main(), rm_initialize(), setup_pes(), tlm_md_init(), tw_eventq_alloc(), tw_pq_create(), and tw_stats().
unsigned int g_tw_events_per_pe_extra
Number of extra events allocated per PE. Command-line customizable.
Definition at line 86 of file ross-global.c.
Referenced by setup_pes().
int g_tw_fossil_attempts
Definition at line 30 of file ross-global.c.
Referenced by tw_pe_fossil_collect(), and tw_stats().
unsigned int g_tw_gvt_done
Definition at line 89 of file ross-global.c.
Referenced by gvt_print(), tw_gvt_compute(), tw_gvt_set(), tw_gvt_stats(), tw_gvt_step2(), and tw_stats().
unsigned int g_tw_gvt_interval
Definition at line 72 of file ross-global.c.
unsigned int g_tw_gvt_threshold
Definition at line 88 of file ross-global.c.
Referenced by setup_pes(), tw_eventq_alloc(), tw_sched_batch(), and tw_scheduler_conservative().
tw_kp** g_tw_kp
Definition at line 28 of file ross-global.c.
Referenced by dragonfly_mapping(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), torus_mapping(), traffic_grid_mapping(), tw_define_lps(), tw_getkp(), and tw_kp_onpe().
tw_stime g_tw_lookahead
Definition at line 58 of file ross-global.c.
Referenced by ForwardDefault(), main(), olsr_event(), olsr_init(), qhold_event(), qhold_init(), tw_event_send(), and tw_scheduler_conservative().
tw_lp** g_tw_lp
Definition at line 27 of file ross-global.c.
Referenced by attach_node_to_lp(), CellMapping_to_lp(), dragonfly_mapping(), dragonfly_mapping_to_lp(), epi_init_agent_default(), late_sanity_check(), main_setup_areas(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), olsr_map_to_lp(), olsr_mapping_to_lp(), pcs_grid_mapping(), torus_mapping(), torus_mapping_to_lp(), traffic_grid_mapping(), tw_define_lps(), tw_getlocal_lp(), tw_getlp(), tw_init_lps(), tw_lp_onpe(), and tw_lp_settype().
tw_lpid g_tw_lp_offset
Definition at line 25 of file ross-global.c.
Referenced by map_linear(), map_round_robin(), olsr_custom_mapping(), and tw_getlocal_lp().
tw_lp_map g_tw_mapping
Definition at line 22 of file ross-global.c.
Referenced by main(), setup_pes(), and tw_define_lps().
unsigned int g_tw_master
Definition at line 84 of file ross-global.c.
Referenced by tw_net_start().
tw_node g_tw_masternode
Definition at line 99 of file ross-global.c.
Referenced by ip_md_final(), main(), mem_stats_print(), pm_pe_final(), rm_initialize(), rm_pe_final(), rm_run(), rn_print_statistics(), setup_pes(), tcp_md_final(), tw_gvt_compute(), tw_gvt_step2(), tw_ismaster(), tw_net_init(), tw_net_start(), tw_net_statistics(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_sequential().
unsigned int g_tw_mblock
Number of messages to process at once out of the PQ before returning back to handling things like GVT, message recption, etc. AKA the "batch" parameter to ROSS.
Definition at line 71 of file ross-global.c.
Referenced by main(), tw_gvt_stats(), tw_sched_batch(), and tw_scheduler_conservative().
unsigned int g_tw_memory_nqueues
Definition at line 41 of file ross-global.c.
Referenced by early_sanity_check(), main(), tw_init_kps(), and tw_kp_fossil_memory().
size_t g_tw_memory_sz
Definition at line 44 of file ross-global.c.
Referenced by tw_define_lps(), and tw_memory_getsize().
tw_stime g_tw_min_detected_offset
Definition at line 64 of file ross-global.c.
Referenced by tw_event_new(), and tw_stats().
size_t g_tw_msg_sz
Definition at line 36 of file ross-global.c.
Referenced by tw_define_lps(), tw_eventq_alloc(), tw_socket_read_event(), tw_socket_send_event(), and tw_stats().
tw_node g_tw_mynode
Definition at line 98 of file ross-global.c.
Referenced by _rm_init(), _tlm_init(), dragonfly_mapping(), dragonfly_mapping_to_lp(), get_inv_router_rem(), get_router_rem(), get_terminal_rem(), getRem(), hash_search(), main(), map_linear(), mapping(), olsr_custom_mapping(), olsr_event(), olsr_grid_mapping(), packet_send(), pcs_grid_mapping(), phold_main(), pm_event_handler(), pm_init(), pm_pe_final(), pm_stats_print(), rm_getelevation(), rm_getlocation(), rm_grid_terrain(), rm_initialize(), rm_run(), rn_event_send(), rp_event_handler(), rw_event_handler(), send_begin(), setup_pes(), tlm_getelevation(), tlm_getlocation(), tlm_grid_init(), torus_mapping(), torus_mapping_to_lp(), traffic_grid_mapping(), tw_error(), tw_event_send(), tw_gvt_set(), tw_gvt_step2(), tw_ismaster(), tw_memory_alloc(), tw_net_barrier(), tw_net_init(), tw_net_start(), tw_pe_init(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_sequential(), tw_socket_create_mesh(), and tw_socket_create_onport().
unsigned int g_tw_net_device_size
Definition at line 97 of file ross-global.c.
Referenced by tw_eventq_alloc(), tw_net_init(), and tw_net_start().
tw_kpid g_tw_nkp
Definition at line 26 of file ross-global.c.
Referenced by dragonfly_mapping(), early_sanity_check(), ip_main(), ip_md_init(), late_sanity_check(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), rp_md_init(), rw_md_init(), setup_pes(), tcp_main(), tcp_md_init(), torus_mapping(), traffic_grid_mapping(), tw_define_lps(), tw_getkp(), tw_init_kps(), tw_kp_onpe(), tw_pe_fossil_collect(), tw_scheduler_optimistic_debug(), and tw_stats().
tw_lpid g_tw_nlp
Definition at line 24 of file ross-global.c.
Referenced by Application_Map(), bgp_main(), CellMapping_to_local_index(), CellMapping_to_lp(), disksim_event_handler(), disksim_map(), early_sanity_check(), epi_final(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_map(), ip_rt_print(), late_sanity_check(), main(), map_linear(), map_round_robin(), mapping(), netdmf_srw_map(), olsr_custom_mapping(), olsr_grid_mapping(), olsr_map_to_local_index(), olsr_map_to_lp(), olsr_mapping_to_lp(), ospf_rt_print(), pcs_grid_mapping(), phold_event_handler(), phold_main(), phold_map(), qhold_map(), raid_mapping(), rm_initialize(), rn_map(), rn_startup(), rn_xml_topology(), rngt_map(), setup_pes(), srw_map(), tmr_map(), traffic_grid_mapping(), tw_define_lps(), tw_getlocal_lp(), tw_getlp(), tw_init_lps(), tw_lp_onpe(), tw_lp_settype(), tw_stats(), and wifi_map().
tw_peid g_tw_npe
Definition at line 81 of file ross-global.c.
Referenced by dragonfly_mapping(), early_sanity_check(), FindMostSquare(), init_socket(), main(), map_round_robin(), olsr_grid_mapping(), pcs_grid_mapping(), phold_main(), pm_stats_print(), rm_getelevation(), rm_grid_terrain(), rm_initialize(), setup_pes(), tlm_getelevation(), tlm_grid_init(), tlm_md_init(), torus_mapping(), traffic_grid_mapping(), tw_define_lps(), tw_getpe(), tw_gvt_inprogress(), tw_gvt_start(), tw_gvt_step1(), tw_memory_free(), tw_net_gvt_compute(), tw_net_send_lvt(), tw_net_start(), tw_pe_create(), tw_pe_init(), tw_sched_init(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_socket_create_mesh(), tw_socket_read_event(), and tw_stats().
unsigned int g_tw_nRNG_per_lp
Definition at line 31 of file ross-global.c.
Referenced by tw_define_lps(), and tw_pe_init().
tw_pe** g_tw_pe
Definition at line 82 of file ross-global.c.
Referenced by avl_alloc(), avl_free(), dragonfly_mapping(), gvt_print(), init_socket(), main(), olsr_grid_mapping(), ospf_router_debug_rate(), pcs_grid_mapping(), rm_initialize(), rn_print_statistics(), setup_pes(), torus_mapping(), traffic_grid_mapping(), tw_getpe(), tw_hash_create(), tw_hash_insert(), tw_hash_remove(), tw_net_gvt_compute(), tw_net_send_lvt(), tw_net_start(), tw_pe_create(), tw_pe_init(), tw_pe_next(), and tw_stats().
unsigned int g_tw_periodicity
Definition at line 52 of file ross-global.c.
Referenced by tw_scheduler_conservative().
tw_lpid g_tw_rng_default
Definition at line 32 of file ross-global.c.
Referenced by main(), rm_initialize(), start_transfer(), tw_define_lps(), and tw_pe_init().
size_t g_tw_rng_max
Definition at line 33 of file ross-global.c.
Referenced by tw_pe_init(), and tw_rand_init_streams().
tw_seed* g_tw_rng_seed
Definition at line 34 of file ross-global.c.
Referenced by rng_init(), and tw_define_lps().
unsigned int g_tw_sim_started
Definition at line 35 of file ross-global.c.
Referenced by tw_sched_init(), tw_sigsegv(), and tw_stats().
int g_tw_sv_growcnt
Definition at line 29 of file ross-global.c.
Referenced by tw_init_lps(), and tw_state_save().
tw_synch g_tw_synchronization_protocol
Definition at line 19 of file ross-global.c.
Referenced by main(), olsr_event(), olsr_event_reverse(), recv_finish(), sa_master_event(), sa_master_event_reverse(), send_finish(), tw_event_new(), tw_event_send(), tw_gvt_step2(), tw_init_kps(), tw_net_start(), tw_output(), tw_run(), tw_sched_init(), and tw_stats().
tw_stime g_tw_ts_end
Definition at line 73 of file ross-global.c.
Referenced by epi_stats_print(), forward(), ForwardPacket(), gvt_print(), main(), mpi_event_rc_handler(), mpi_msg_recv(), node_rc_handler(), num_main(), ospf_h_send(), ospf_random_weights(), packet_arrive(), packet_finish(), packet_send(), phold_init(), ReadAgentAct(), ReadGroupOp(), rm_init(), rm_setup_options(), rn_event_new(), rn_link_random_changes(), rn_link_random_weight_changes(), ScheduleTimer(), ScheduleTimerWithSn(), setup_pes(), start_transfer(), tcp_timeout(), terminal_rc_event_handler(), tlm_md_init(), tw_event_new(), tw_event_send(), tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_sequential(), tw_socket_read_event(), tw_timer_cancel(), tw_timer_event_new(), tw_timer_init(), and tw_timer_reset().