ROSS: ross/models/epi/epi-seir.c File Reference
epi-seir.c File Reference
#include <epi.h>
Functions
int agent_susceptible (epi_agent *a, int disease, tw_lp *lp)
void epi_seir_compute (epi_state *state, tw_bf *bf, int disease, tw_lp *lp)
Function Documentation
int agent_susceptible (epi_agent * a, int disease, tw_lp * lp)
Definition at line 12 of file epi-seir.c.
References EPI_SUSCEPTIBLE, g_epi_pathogen_fd, epi_pathogen::index, p, epi_agent::pathogens, epi_pathogen::stage, and tw_memory_free().
Referenced by epi_seir_compute().
void epi_seir_compute (epi_state * state, tw_bf * bf, int disease, tw_lp * lp)
Definition at line 54 of file epi-seir.c.
References agent_susceptible(), delta_t, epi_agent_infected(), EPI_SUSCEPTIBLE, g_epi_pathogen_fd, g_epi_pq, tw_lp::id, epi_pathogen::index, epi_ic_stage::ln_multiplier, epi_state::ncontagious, p, epi_agent::pathogens, pq_get_size(), pq_next(), tw_lp::rng, s, epi_pathogen::stage, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, epi_pathogen::ts_stage_tran, tw_error(), TW_LOC, tw_memory_alloc(), tw_now(), and tw_rand_unif.