ROSS: ross/models/tcp-ip/ip-downstream.c File Reference
ip-downstream.c File Reference
#include <ip.h>
Functions
ip_link * ip_getlink (ip_state *state, tw_lpid dst)
ip_link * getroute (ip_state *state, rn_message *msg, tw_lp *lp)
tw_event * forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void ip_downstream_forward (ip_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
Function Documentation
tw_event* forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 47 of file ip-downstream.c.
References ip_link::addr, ip_link::bandwidth, tw_bf::c31, ip_link::delay, DOWNSTREAM, rn_message::dst, g_ip_fd, g_tw_ts_end, getroute(), tw_lp::id, ip_link::last_sent, ip_message::rc_lastsent, ip_message::rc_link, tw_event::recv_ts, ip_stats::s_nforward, ip_stats::s_nnet_failures, rn_message::size, rn_message::src, tw_event::state, ip_state::stats, rn_message::ttl, tw_error(), tw_event_data(), tw_event_new(), tw_getlp(), TW_LOC, tw_memory_alloc(), tw_now(), and rn_message::type.
ip_link* getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 16 of file ip-downstream.c.
References rn_message::dst, tw_lp::id, ip_getlink(), ip_packet_drop(), ip_route(), ip_state::links, ip_state::nlinks, and rn_message::src.
void ip_downstream_forward (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 112 of file ip-downstream.c.
References rn_message::dst, forward(), ip_packet_drop(), tw_event::next, rn_message::port, rn_event_send(), ip_stats::s_ndropped_ttl, rn_message::size, rn_message::src, tw_event::state, ip_state::stats, rn_message::ttl, tw_error(), tw_event_data(), tw_event_send(), TW_LOC, and rn_message::type.
void ip_downstream_source (ip_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 101 of file ip-downstream.c.
References forward(), g_ip_header, rn_event_send(), rn_message::size, and tw_event_send().
ip_link* ip_getlink (ip_state * state, tw_lpid dst)
Definition at line 4 of file ip-downstream.c.
References ip_link::addr, ip_state::links, and ip_state::nlinks.
Referenced by getroute(), and rc_getroute().