ROSS: ross/models/epi/epi-agent.c File Reference
epi-agent.c File Reference
#include <epi.h>
Functions
void epi_agent_update_ts (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_agent_send (tw_lp *src, tw_memory *buf, tw_stime offset, tw_lpid dst)
epi_ic_stage * epi_agent_infected (epi_agent *a, int disease)
void agent_stage_tran (epi_state *state, tw_bf *bf, tw_memory *buf, epi_pathogen *p, tw_lp *lp)
void epi_agent_contagious (epi_state *state, tw_memory *buf, signed int offset)
int epi_agent_stage_tran (epi_state *state, tw_bf *bf, tw_memory *buf, tw_lp *lp)
void epi_agent_add (epi_state *state, tw_bf *bf, tw_memory *buf, tw_lp *lp)
void epi_agent_add_back (epi_state *state, tw_lp *lp, tw_memory *buf)
void epi_agent_remove (epi_state *state, tw_bf *bf, tw_lp *lp)
Function Documentation
void agent_stage_tran (epi_state * state, tw_bf * bf, tw_memory * buf, epi_pathogen * p, tw_lp * lp)
Definition at line 113 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::days_remaining, EPI_AGENT_DEAD, epi_agent_update_ts(), EPI_AGENT_WORK_WHILE_SICK, EPI_AGENT_WORRIED_WELL, EPSILON, g_epi_diseases, g_epi_hospital, g_epi_pq, g_epi_regions, tw_lp::gid, epi_state::hospital, epi_agent::id, tw_lp::id, epi_pathogen::index, epi_ic_stage::ln_multiplier, epi_ic_stage::max_duration, epi_ic_stage::min_duration, epi_ic_stage::mortality_rate, epi_state::ncontagious, epi_state::ncontagious_tot, epi_disease::nstages, pq_enqueue(), epi_agent::region, tw_lp::rng, s, epi_statistics::s_ndead, epi_statistics::s_ninfected, epi_pathogen::stage, epi_disease::stages, epi_state::stats, epi_pathogen::ts_stage_tran, tw_error(), TW_LOC, tw_now(), tw_rand_unif, and TWENTY_FOUR_HOURS.
Referenced by epi_agent_stage_tran().
void epi_agent_add (epi_state * state, tw_bf * bf, tw_memory * buf, tw_lp * lp)
Definition at line 261 of file epi-agent.c.
References epi_agent::behavior_flags, epi_agent::curr, epi_agent::days_remaining, epi_agent::dur, epi_agent_contagious(), epi_agent_update_ts(), EPI_AGENT_WORRIED_WELL, g_epi_hospital_ww, g_epi_pq, g_epi_ww_duration, g_epi_ww_threshold, tw_lp::gid, epi_state::hospital, epi_agent::id, tw_lp::id, epi_agent::loc, epi_state::max_queue_size, epi_state::ncontagious_tot, epi_agent::nloc, pq_enqueue(), pq_get_size(), epi_agent::ts_remove, tw_error(), TW_LOC, and tw_now().
void epi_agent_add_back (epi_state * state, tw_lp * lp, tw_memory * buf)
Definition at line 310 of file epi-agent.c.
References epi_agent::curr, epi_agent::dur, g_epi_pq, tw_lp::gid, epi_agent::id, tw_lp::id, epi_agent::nloc, p, epi_agent::pathogens, pq_enqueue(), epi_agent::ts_next, epi_agent::ts_remove, epi_pathogen::ts_stage_tran, and tw_now().
void epi_agent_contagious (epi_state * state, tw_memory * buf, signed int offset)
Definition at line 208 of file epi-agent.c.
References g_epi_diseases, epi_pathogen::index, epi_ic_stage::ln_multiplier, epi_state::ncontagious, epi_state::ncontagious_tot, p, epi_pathogen::stage, and epi_disease::stages.
Referenced by epi_agent_add(), and epi_agent_remove().
epi_ic_stage* epi_agent_infected (epi_agent * a, int disease)
Definition at line 79 of file epi-agent.c.
References g_epi_diseases, epi_pathogen::index, epi_ic_stage::ln_multiplier, p, epi_agent::pathogens, s, epi_pathogen::stage, and epi_disease::stages.
Referenced by epi_seir_compute().
void epi_agent_remove (epi_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 359 of file epi-agent.c.
References epi_agent::curr, epi_agent::days_remaining, epi_agent_add_back(), epi_agent_contagious(), epi_agent_send(), epi_agent_stage_tran(), epi_num_remove(), g_epi_pq, g_epi_stages, g_epi_stay_home, tw_lp::gid, epi_agent::id, tw_lp::id, epi_ic_stage::ln_multiplier, epi_agent::loc, epi_state::ncontagious, epi_agent::nloc, epi_state::pq, pq_dequeue(), pq_enqueue(), pq_top(), rn_event_direct(), rn_event_send(), epi_agent::stage, epi_agent::ts_next, epi_agent::ts_stage_tran, tw_error(), TW_LOC, tw_now(), and TWENTY_FOUR_HOURS.
void epi_agent_send (tw_lp * src, tw_memory * buf, tw_stime offset, tw_lpid dst)
Definition at line 50 of file epi-agent.c.
References epi_agent::curr, g_epi_fd, g_epi_pathogen_fd, tw_lp::id, epi_agent::loc, epi_agent::pathogens, tw_event_new(), tw_event_send(), and tw_now().
Referenced by epi_agent_remove().
int epi_agent_stage_tran (epi_state * state, tw_bf * bf, tw_memory * buf, tw_lp * lp)
Definition at line 230 of file epi-agent.c.
References agent_stage_tran(), p, epi_agent::pathogens, epi_pathogen::ts_stage_tran, and tw_now().
void epi_agent_update_ts (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 13 of file epi-agent.c.
References g_epi_diseases, g_epi_ndiseases, epi_pathogen::index, epi_ic_stage::ln_multiplier, min, p, epi_agent::pathogens, epi_pathogen::stage, epi_disease::stages, epi_agent::ts_next, epi_agent::ts_remove, epi_state::ts_seir, and epi_pathogen::ts_stage_tran.
Referenced by agent_stage_tran(), and epi_agent_add().