ROSS: core/ross-gvt.h File Reference
ross-gvt.h File Reference
Functions
const tw_optdef * tw_gvt_setup (void)
void tw_gvt_start (void)
void tw_gvt_step1 (tw_pe *)
void tw_gvt_step1_realtime (tw_pe *)
void tw_gvt_step2 (tw_pe *)
void tw_gvt_force_update (void)
void tw_gvt_force_update_realtime (void)
int tw_gvt_set (tw_pe *pe, tw_stime LVT)
static int tw_gvt_inprogress (tw_pe *pe)
void tw_gvt_stats (FILE *F)
Function Documentation
void tw_gvt_force_update (void)
Definition at line 40 of file mpi_allreduce.c.
References g_tw_gvt_interval, gvt_cnt, and gvt_force.
Referenced by tw_sched_batch(), and tw_scheduler_conservative().
void tw_gvt_force_update_realtime (void)
Definition at line 47 of file mpi_allreduce.c.
References g_tw_gvt_interval_start_cycles, and gvt_force.
Referenced by tw_sched_batch_realtime().
static int tw_gvt_inprogress (tw_pe * pe) inline static
int tw_gvt_set (tw_pe * pe, tw_stime LVT)
const tw_optdef* tw_gvt_setup (void)
Definition at line 27 of file mpi_allreduce.c.
References gvt_cnt, and gvt_opts.
Referenced by tw_init().
void tw_gvt_start (void)
Definition at line 35 of file mpi_allreduce.c.
Referenced by tw_init().
void tw_gvt_stats (FILE * F)
Definition at line 54 of file mpi_allreduce.c.
References all_reduce_cnt, g_tw_clock_rate, g_tw_gvt_done, g_tw_gvt_interval, g_tw_gvt_realtime_interval, g_tw_mblock, and gvt_force.
Referenced by tw_stats().
void tw_gvt_step1 (tw_pe *)
Definition at line 70 of file mpi_allreduce.c.
References g_tw_gvt_interval, g_tw_max_opt_lookahead, tw_pe::GVT, gvt_cnt, tw_pe::gvt_status, tw_pe::pq, TW_GVT_COMPUTE, tw_pq_minimum(), and TW_STIME_DBL.
Referenced by tw_scheduler_conservative(), and tw_scheduler_optimistic().
void tw_gvt_step1_realtime (tw_pe *)
Definition at line 80 of file mpi_allreduce.c.
References g_tw_gvt_interval_start_cycles, g_tw_gvt_realtime_interval, g_tw_max_opt_lookahead, tw_pe::GVT, tw_pe::gvt_status, tw_pe::pq, tw_clock_read(), TW_GVT_COMPUTE, tw_pq_minimum(), and TW_STIME_DBL.
Referenced by tw_scheduler_optimistic_realtime().
void tw_gvt_step2 (tw_pe *)
Definition at line 103 of file mpi_allreduce.c.
References all_reduce_cnt, ALL_STATS, g_st_engine_stats, g_st_model_stats, g_st_num_gvt, g_tw_clock_rate, g_tw_gvt_done, g_tw_gvt_interval_start_cycles, g_tw_gvt_max_no_change, g_tw_gvt_no_change, g_tw_masternode, g_tw_mynode, g_tw_synchronization_protocol, g_tw_ts_end, tw_pe::GVT, gvt_cnt, GVT_COL, tw_pe::GVT_prev, gvt_print(), GVT_STATS, tw_pe::gvt_status, tw_pe::id, MPI_COMM_ROSS, MPI_TYPE_TW_STIME, OPTIMISTIC, OPTIMISTIC_REALTIME, percent_complete, tw_pe::pq, RT_STATS, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_statistics::s_net_read, tw_pe::s_nwhite_recv, tw_pe::s_nwhite_sent, st_collect_engine_data(), st_collect_model_data(), st_inst_dump(), tw_pe::stats, tw_pe::trans_msg_ts, tw_clock_read(), tw_error(), TW_GVT_COMPUTE, TW_GVT_NORMAL, TW_LOC, tw_net_minimum(), tw_net_read(), tw_pe_fossil_collect(), tw_pq_minimum(), TW_STIME_CMP, TW_STIME_DBL, TW_STIME_MAX, and VT_STATS.
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_optimistic_realtime().