ROSS: ross/models/epi/epi-timer.c File Reference
epi-timer.c File Reference
#include <epi.h>
Functions
void epi_location_timer (epi_state *state, tw_lp *lp)
Function Documentation
void epi_location_timer (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-timer.c.
References tw_pe::cur_event, g_epi_pq, tw_lp::id, tw_lp::pe, epi_state::pq, pq_top(), rn_timer_init(), rn_timer_reset(), epi_state::tmr_remove, epi_agent::ts_next, tw_error(), TW_LOC, tw_timer_init(), and tw_timer_reset().
Referenced by epi_event_handler(), and epi_init().