ROSS: ross/ross-random.c File Reference
ross-random.c File Reference
#include <ross.h>
Functions
tw_rng * tw_rand_init (uint32_t v, uint32_t w)
long tw_rand_integer (tw_rng_stream *g, long low, long high)
unsigned long tw_rand_ulong (tw_rng_stream *g, unsigned long low, unsigned long high)
long tw_rand_binomial (tw_rng_stream *g, long N, double P)
double tw_rand_exponential (tw_rng_stream *g, double Lambda)
double tw_rand_pareto (tw_rng_stream *g, double shape, double scale)
double tw_rand_gamma (tw_rng_stream *g, double shape, double scale)
long tw_rand_geometric (tw_rng_stream *g, double P)
double tw_rand_normal01 (tw_rng_stream *g, unsigned int *rng_calls)
double tw_rand_normal_sd (tw_rng_stream *g, double Mu, double Sd, unsigned int *rng_calls)
long tw_rand_poisson (tw_rng_stream *g, double Lambda)
double tw_rand_lognormal (tw_rng_stream *g, double mean, double sd, unsigned int *rng_calls)
double tw_rand_weibull (tw_rng_stream *g, double mean, double shape)
Function Documentation
long tw_rand_binomial (tw_rng_stream * g, long N, double P)
Definition at line 53 of file ross-random.c.
References tw_rand_unif.
double tw_rand_exponential (tw_rng_stream * g, double Lambda)
Definition at line 69 of file ross-random.c.
References tw_rand_unif.
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), bgp_init(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_init_agent_default(), event_handler(), ftp_event_handler(), init(), Intersection_EventHandler(), Intersection_StartUp(), mem_event_handler(), mem_init(), mpi_init(), mpi_msg_send(), olsr_arrival_to_mpr(), olsr_change_region(), olsr_region_init(), olsr_station_to_mpr(), ospf_flood_recv(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), phold_event_handler(), phold_init(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_disk_fail_time(), router_credit_send(), router_packet_receive(), router_packet_send(), router_reschedule_event(), rp_init(), rp_move(), rw_init(), rw_move(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), srw_event(), srw_init(), tcp_host_startup(), tcp_lp_init(), tmr_event_handler(), tmr_init(), tw_rand_gamma(), wifi_access_point_arrival(), and wifi_station_arrival().
double tw_rand_gamma (tw_rng_stream * g, double shape, double scale)
Definition at line 81 of file ross-random.c.
References d, tw_rand_exponential(), and tw_rand_unif.
long tw_rand_geometric (tw_rng_stream * g, double P)
Definition at line 141 of file ross-random.c.
References tw_rand_unif.
Referenced by epi_seir_compute().
tw_rng* tw_rand_init (uint32_t v, uint32_t w)
Definition at line 7 of file ross-random.c.
References rng_init().
Referenced by tw_pe_init().
long tw_rand_integer (tw_rng_stream * g, long low, long high)
NOTE: Don't pass negative values to low!
Definition at line 21 of file ross-random.c.
References tw_rand_unif.
Referenced by Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), change_direction(), disksim_event_handler(), epi_init(), epi_init_agent_default(), epi_xml(), event_handler(), get_next_stop(), mem_event_handler(), mpi_msg_send(), olsr_change_region(), olsr_departure_from_mpr(), olsr_region_init(), olsr_station_to_mpr(), ospf_experiment_weights(), ospf_nbr_reset(), ospf_random_weights(), phold_event_handler(), pm_init(), raid_disk_fail_time(), rn_event_handler(), rn_link_random_changes(), rn_link_random_weight_changes(), rp_init(), rw_init(), srw_init(), start_transfer(), tcp_host_startup(), and tmr_event_handler().
double tw_rand_lognormal (tw_rng_stream * g, double mean, double sd, unsigned int * rng_calls)
Definition at line 209 of file ross-random.c.
References tw_rand_normal01().
double tw_rand_normal01 (tw_rng_stream * g, unsigned int * rng_calls)
Definition at line 152 of file ross-random.c.
References tw_error(), TW_LOC, tw_rng_stream::tw_normal_flipflop, tw_rng_stream::tw_normal_u1, tw_rng_stream::tw_normal_u2, tw_opi, and tw_rand_unif.
Referenced by tw_rand_lognormal(), and tw_rand_normal_sd().
double tw_rand_normal_sd (tw_rng_stream * g, double Mu, double Sd, unsigned int * rng_calls)
Definition at line 182 of file ross-random.c.
References tw_rand_normal01().
Referenced by raid_controller_eventhandler(), raid_disk_eventhandler(), raid_io_eventhandler(), wifi_access_point_arrival(), and wifi_station_arrival().
double tw_rand_pareto (tw_rng_stream * g, double shape, double scale)
Definition at line 75 of file ross-random.c.
References tw_rand_unif.
long tw_rand_poisson (tw_rng_stream * g, double Lambda)
Definition at line 188 of file ross-random.c.
References tw_rand_unif.
unsigned long tw_rand_ulong (tw_rng_stream * g, unsigned long low, unsigned long high)
Definition at line 37 of file ross-random.c.
References tw_rand_unif.
Referenced by qhold_event(), and qhold_init().
double tw_rand_weibull (tw_rng_stream * g, double mean, double shape)
Definition at line 215 of file ross-random.c.
References tw_rand_unif.
Referenced by disksim_event_handler(), and raid_disk_fail_time().