ROSS: ross/models/tcp-ip/tcp-extern.h File Reference
tcp-extern.h File Reference
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
tw_event * tcp_rc_timer_reset (tw_event *, tw_bf *bf, tcp_message *old, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
void tcp_init (tcp_state *, FILE *f, tw_lp *)
void tcp_main (int argc, char **argv, char **env)
void tcp_md_final ()
void tcp_lp_init (tcp_state *, tw_lp *)
void tcp_event_handler (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_event_handler (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_lp_final (tcp_state *, tw_lp *)
void tcp_process (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_cwnd (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_rtt (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_event_send (tcp_state *, int, tw_stime, int, int, int, int, tw_lp *)
Variables
tw_fd g_tcp_fd
tcp_statistics * g_tcp_stats
Function Documentation
void tcp_event_handler (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 66 of file tcp.c.
References tcp_state::connection, tw_lp::id, tcp_message::src, tcp_process_ack(), tcp_process_data(), tcp_timeout(), and tw_now().
void tcp_event_send (tcp_state * , int , tw_stime , int , int , int , int , tw_lp *)
Definition at line 4 of file tcp-util.c.
References tcp_message::ack, tcp_state::connection, tcp_message::dst, tw_lp::id, tcp_state::lastsent, tcp_message::seq_num, tcp_message::size, tcp_message::src, tw_event_data(), tw_event_new(), tw_event_send(), and tw_now().
void tcp_init (tcp_state * , FILE * f, tw_lp *)
Definition at line 4 of file tcp-init.c.
References tcp_state::mss, node::next, tcp_state::recv_wnd, TCP_LP_TYPE, tw_lp_settype(), and xml_getprop().
void tcp_lp_final (tcp_state * , tw_lp *)
Definition at line 127 of file tcp.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_state::connection, tcp_state::cwnd, tcp_statistics::dropped_packets, tcp_statistics::final_time, g_rn_logs_dir, g_tcp_stats, tw_lp::id, tcp_state::len, tcp_statistics::recv, tcp_statistics::sent, tcp_statistics::start_time, tcp_state::stats, tcp_statistics::throughput, tcp_statistics::tout, and tw_now().
void tcp_lp_init (tcp_state * , tw_lp *)
Definition at line 9 of file tcp.c.
References tcp_state::connection, tcp_state::cwnd, tw_lp::id, tcp_state::lastsent, tcp_state::len, tcp_state::mss, tw_event::recv_ts, tcp_state::rto, tcp_state::rtt_seq, tcp_state::rtt_time, tcp_statistics::sent, tcp_state::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, tcp_statistics::start_time, tcp_state::stats, tcp_event_send(), TCP_MTU, TCP_SND_WND, tcp_state::timer, tw_event_data(), tw_rand_exponential(), and tw_timer_init().
void tcp_main (int argc, char ** argv, char ** env)
Definition at line 12 of file tcp-main.c.
References g_tcp_fd, g_tcp_stats, g_tw_nkp, tcp_setup_options(), and tw_getkp().
Referenced by main().
void tcp_md_final ()
Definition at line 27 of file tcp-model.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_statistics::dropped_packets, g_tcp_f, g_tcp_stats, g_tw_masternode, tcp_statistics::recv, tcp_statistics::sent, stats, tcp_statistics::throughput, tcp_statistics::tout, tw_error(), tw_ismaster(), and TW_LOC.
void tcp_process (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
void tcp_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-process.c.
References tcp_message::ack, tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c9, tcp_state::connection, tcp_state::cwnd, RC::cwnd, tcp_message::dst, tcp_state::dup_count, RC::dup_count, tw_lp::gid, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tcp_state::recv_wnd, rn_event_new(), rn_event_send(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, RC::sent, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, RC::ssthresh, tcp_statistics::start_time, tcp_state::stats, tcp_event_send(), TCP_MTU, tcp_timer_reset(), tcp_update_cwnd(), tcp_update_rtt(), tcp_state::timer, tw_error(), TW_LOC, tw_now(), tcp_state::unack, RC::unack, and UPSTREAM.
void tcp_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 144 of file tcp-process.c.
References tcp_statistics::ack_sent, tw_bf::c16, tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::cwnd, RC::dup_count, g_tcp_rwd, tw_lp::gid, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, RC::out_of_order, tcp_message::RC, tcp_statistics::recv, tcp_state::recv_wnd, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::stats, TCP_DEBUG, tcp_event_send(), TCP_HEADER_SIZE, TCP_SND_WND, tw_error(), TW_LOC, and tw_printf().
void tcp_rc_event_handler (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 97 of file tcp.c.
References tcp_state::connection, tw_lp::id, tcp_message::src, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), and tw_now().
void tcp_rc_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-process.c.
References tcp_message::ack, tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tw_bf::c15, tw_bf::c16, tw_bf::c17, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c9, tcp_state::connection, tcp_state::cwnd, RC::cwnd, DOWNSTREAM, tcp_message::dst, tcp_state::dup_count, RC::dup_count, tw_lp::gid, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_message::RC, rn_reverse_event_send(), tcp_state::rto, RC::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, RC::sent, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_state::ssthresh, RC::ssthresh, tcp_state::stats, TCP_MTU, tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_state::timer, tw_error(), TW_LOC, tw_now(), tcp_state::unack, and RC::unack.
void tcp_rc_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 94 of file tcp-rc-process.c.
References tcp_statistics::ack_sent, tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::cwnd, DOWNSTREAM, RC::dup_count, g_tcp_rwd, tw_lp::gid, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, RC::out_of_order, tcp_message::RC, tcp_statistics::recv, tcp_state::recv_wnd, rn_reverse_event_send(), tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::stats, TCP_HEADER_SIZE, TCP_SND_WND, tw_error(), and TW_LOC.
void tcp_rc_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-timeout.c.
References tcp_message::ack, tw_bf::c1, tcp_state::connection, tcp_state::cwnd, RC::cwnd, DOWNSTREAM, tcp_message::dst, RC::dup_count, tcp_state::lastsent, RC::lastsent, tcp_message::RC, rn_reverse_event_send(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_state::ssthresh, RC::ssthresh, tcp_state::stats, TCP_MTU, tcp_rc_timer_reset(), tcp_state::timer, and tcp_statistics::tout.
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 135 of file tcp-timer.c.
References g_tcp_fd, tw_lp::gid, tcp_message::RC, tw_event::recv_ts, rn_timer_init(), tcp_message::src, RC::timer_ts, tw_error(), TW_LOC, tw_memory_free_rc(), and tw_now().
tw_event* tcp_rc_timer_reset (tw_event * , tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 61 of file tcp-timer.c.
References tw_bf::c13, tw_bf::c14, tw_bf::c17, g_tcp_fd, tw_lp::gid, tw_lp::id, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), rn_timer_init(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, tw_memory_alloc(), tw_memory_alloc_rc(), and tw_now().
void tcp_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 4 of file tcp-timeout.c.
References tcp_message::ack, tw_bf::c1, tcp_state::connection, tcp_state::cwnd, RC::cwnd, tcp_message::dst, RC::dup_count, g_tw_ts_end, tw_lp::gid, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::len, min, tcp_state::mss, tcp_message::RC, tw_event::recv_ts, tcp_state::recv_wnd, rn_event_new(), rn_event_send(), tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_message::src, tcp_state::ssthresh, RC::ssthresh, tcp_state::stats, tcp_event_send(), TCP_MTU, tcp_timer_reset(), tcp_state::timer, tcp_statistics::tout, tw_now(), tcp_state::unack, and UPSTREAM.
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 114 of file tcp-timer.c.
References tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), RC::timer_ts, tw_error(), TW_LOC, tw_memory_free(), and tw_now().
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
References tw_bf::c13, tw_bf::c14, tw_pe::cur_event, g_tcp_fd, tw_lp::gid, tw_lp::id, tw_lp::pe, tcp_message::RC, tw_event::recv_ts, rn_timer_init(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, and tw_memory_alloc().
void tcp_update_cwnd (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-update.c.
References tw_bf::c3, tw_bf::c4, tcp_state::cwnd, RC::cwnd, tcp_state::mss, tcp_message::RC, tcp_state::ssthresh, and TCP_SND_WND.
void tcp_update_rtt (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 25 of file tcp-update.c.
References tcp_message::ack, tw_bf::c15, tw_bf::c16, tw_bf::c17, tw_bf::c5, tw_bf::c6, tw_bf::c7, tcp_message::dst, tcp_statistics::final_time, tw_lp::id, tcp_state::len, min, tcp_message::RC, tw_event::recv_ts, tcp_state::rto, RC::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_state::stats, tcp_timer_cancel(), tcp_timer_reset(), tcp_state::timer, tw_now(), and tcp_state::unack.
Variable Documentation
tw_fd g_tcp_fd
Definition at line 9 of file tcp-global.c.
tcp_statistics* g_tcp_stats
Definition at line 10 of file tcp-global.c.