ROSS: ross/models/tcp-ip/tcp-update.c File Reference
tcp-update.c File Reference
#include <tcp.h>
Functions
void tcp_update_cwnd (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
void tcp_update_rtt (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
Function Documentation
void tcp_update_cwnd (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 7 of file tcp-update.c.
References tw_bf::c3, tw_bf::c4, tcp_state::cwnd, RC::cwnd, tcp_state::mss, tcp_message::RC, tcp_state::ssthresh, and TCP_SND_WND.
Referenced by tcp_host_process_ack(), and tcp_process_ack().
void tcp_update_rtt (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 25 of file tcp-update.c.
References tcp_message::ack, tw_bf::c15, tw_bf::c5, tw_bf::c6, tw_bf::c7, tcp_message::dst, tcp_statistics::final_time, tw_lp::id, tcp_state::len, min, tcp_message::RC, tw_event::recv_ts, tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_state::seq_num, tcp_state::stats, tcp_timer_cancel(), tcp_timer_reset(), tcp_state::timer, tw_now(), and tcp_state::unack.
Referenced by tcp_host_process_ack(), and tcp_process_ack().