ROSS: ross/ross-random.h File Reference
ross-random.h File Reference
Macros
#define tw_opi 6.28318530718
#define tw_rand_unif(G) rng_gen_val(G)
#define tw_rand_reverse_unif(G) rng_gen_reverse_val(G)
Typedefs
typedef struct tw_rng tw_rng
typedef struct tw_rng_stream tw_rng_stream
Functions
tw_rng * tw_rand_init (uint32_t v, uint32_t w)
void tw_rand_initial_seed (tw_rng_stream *g, tw_lpid id)
long tw_rand_integer (tw_rng_stream *g, long low, long high)
unsigned long tw_rand_ulong (tw_rng_stream *g, unsigned long low, unsigned long high)
long tw_rand_binomial (tw_rng_stream *g, long N, double P)
double tw_rand_exponential (tw_rng_stream *g, double Lambda)
double tw_rand_pareto (tw_rng_stream *g, double scale, double shape)
double tw_rand_gamma (tw_rng_stream *g, double shape, double scale)
long tw_rand_geometric (tw_rng_stream *g, double P)
double tw_rand_normal01 (tw_rng_stream *g, unsigned int *rng_calls)
double tw_rand_normal_sd (tw_rng_stream *g, double Mu, double Sd, unsigned int *rng_calls)
long tw_rand_poisson (tw_rng_stream *g, double Lambda)
double tw_rand_weibull (tw_rng_stream *g, double mean, double shape)
Macro Definition Documentation
#define tw_opi 6.28318530718
Definition at line 4 of file ross-random.h.
Referenced by tw_rand_normal01().
#define tw_rand_reverse_unif (G) rng_gen_reverse_val(G)
Definition at line 6 of file ross-random.h.
Referenced by Airport_RC_EventHandler(), disksim_event_handler_rc(), event_handler(), ftp_rc_event_handler(), Intersection_RC_EventHandler(), mem_event_handler_rc(), mpi_event_rc_handler(), mpi_rc_event_handler(), node_rc_handler(), olsr_arrival_to_mpr_rc(), olsr_change_region_rc(), olsr_departure_from_mpr_rc(), olsr_station_to_mpr_rc(), phold_event_handler_rc(), pm_rc_event_handler(), pm_rc_move(), qhold_event_reverse(), r_msg_keepalivetimer(), r_msg_open(), r_msg_update(), raid_controller_eventhandler_rc(), raid_disk_eventhandler_rc(), raid_io_eventhandler_rc(), raid_server_eventhandler_rc(), RC_Cell_CompletionCall(), RC_Cell_MoveCallIn(), RC_Cell_MoveCallOut(), RC_Cell_NextCall(), rc_event_handler(), router_rc_event_handler(), rp_rc_event_handler(), rp_rc_move(), rw_rc_event_handler(), rw_rc_move(), tcp_router_forward_rc(), terminal_rc_event_handler(), tmr_event_handler_rc(), wifi_access_point_arrival_rc(), and wifi_station_arrival_rc().
#define tw_rand_unif (G) rng_gen_val(G)
Definition at line 5 of file ross-random.h.
Referenced by agent_stage_tran(), epi_agent_stage_tran(), epi_init(), epi_seir_compute(), epi_xml(), event_handler(), ForwardDefault(), mem_event_handler(), num_start(), olsr_change_region(), olsr_departure_from_mpr(), olsr_event(), olsr_init(), olsr_region_init(), olsr_station_to_mpr(), phold_event_handler(), pm_event_handler(), rngt_event(), rp_event_handler(), rw_event_handler(), sa_master_event(), srw_init(), start_transfer(), tcp_router_forward(), tmr_event_handler(), tw_rand_binomial(), tw_rand_exponential(), tw_rand_gamma(), tw_rand_geometric(), tw_rand_integer(), tw_rand_normal01(), tw_rand_pareto(), tw_rand_poisson(), tw_rand_ulong(), and tw_rand_weibull().
Typedef Documentation
typedef struct tw_rng tw_rng
Definition at line 8 of file ross-random.h.
typedef struct tw_rng_stream tw_rng_stream
Definition at line 9 of file ross-random.h.
Function Documentation
long tw_rand_binomial (tw_rng_stream * g, long N, double P)
Definition at line 53 of file ross-random.c.
References tw_rand_unif.
double tw_rand_exponential (tw_rng_stream * g, double Lambda)
Definition at line 69 of file ross-random.c.
References tw_rand_unif.
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), bgp_init(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_init_agent_default(), event_handler(), ftp_event_handler(), init(), Intersection_EventHandler(), Intersection_StartUp(), mem_event_handler(), mem_init(), mpi_init(), mpi_msg_send(), olsr_arrival_to_mpr(), olsr_change_region(), olsr_region_init(), olsr_station_to_mpr(), ospf_flood_recv(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), phold_event_handler(), phold_init(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_disk_fail_time(), router_credit_send(), router_packet_receive(), router_packet_send(), router_reschedule_event(), rp_init(), rp_move(), rw_init(), rw_move(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), srw_event(), srw_init(), tcp_host_startup(), tcp_lp_init(), tmr_event_handler(), tmr_init(), tw_rand_gamma(), wifi_access_point_arrival(), and wifi_station_arrival().
double tw_rand_gamma (tw_rng_stream * g, double shape, double scale)
Definition at line 81 of file ross-random.c.
References d, tw_rand_exponential(), and tw_rand_unif.
long tw_rand_geometric (tw_rng_stream * g, double P)
Definition at line 141 of file ross-random.c.
References tw_rand_unif.
Referenced by epi_seir_compute().
tw_rng* tw_rand_init (uint32_t v, uint32_t w)
Definition at line 7 of file ross-random.c.
References rng_init().
Referenced by tw_pe_init().
void tw_rand_initial_seed (tw_rng_stream * g, tw_lpid id)
Definition at line 231 of file rand-clcg4.c.
References tw_rng::avw, tw_rng::m, MultModM(), and tw_rng::seed.
Referenced by tmr_init(), and tw_rand_init_streams().
long tw_rand_integer (tw_rng_stream * g, long low, long high)
NOTE: Don't pass negative values to low!
Definition at line 21 of file ross-random.c.
References tw_rand_unif.
Referenced by Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), change_direction(), disksim_event_handler(), epi_init(), epi_init_agent_default(), epi_xml(), event_handler(), get_next_stop(), mem_event_handler(), mpi_msg_send(), olsr_change_region(), olsr_departure_from_mpr(), olsr_region_init(), olsr_station_to_mpr(), ospf_experiment_weights(), ospf_nbr_reset(), ospf_random_weights(), phold_event_handler(), pm_init(), raid_disk_fail_time(), rn_event_handler(), rn_link_random_changes(), rn_link_random_weight_changes(), rp_init(), rw_init(), srw_init(), start_transfer(), tcp_host_startup(), and tmr_event_handler().
double tw_rand_normal01 (tw_rng_stream * g, unsigned int * rng_calls)
Definition at line 152 of file ross-random.c.
References tw_error(), TW_LOC, tw_rng_stream::tw_normal_flipflop, tw_rng_stream::tw_normal_u1, tw_rng_stream::tw_normal_u2, tw_opi, and tw_rand_unif.
Referenced by tw_rand_lognormal(), and tw_rand_normal_sd().
double tw_rand_normal_sd (tw_rng_stream * g, double Mu, double Sd, unsigned int * rng_calls)
Definition at line 182 of file ross-random.c.
References tw_rand_normal01().
Referenced by raid_controller_eventhandler(), raid_disk_eventhandler(), raid_io_eventhandler(), wifi_access_point_arrival(), and wifi_station_arrival().
double tw_rand_pareto (tw_rng_stream * g, double scale, double shape)
Definition at line 75 of file ross-random.c.
References tw_rand_unif.
long tw_rand_poisson (tw_rng_stream * g, double Lambda)
Definition at line 188 of file ross-random.c.
References tw_rand_unif.
unsigned long tw_rand_ulong (tw_rng_stream * g, unsigned long low, unsigned long high)
Definition at line 37 of file ross-random.c.
References tw_rand_unif.
Referenced by qhold_event(), and qhold_init().
double tw_rand_weibull (tw_rng_stream * g, double mean, double shape)
Definition at line 215 of file ross-random.c.
References tw_rand_unif.
Referenced by disksim_event_handler(), and raid_disk_fail_time().