ROSS: ross/ross-inline.h File Reference
ross-inline.h File Reference
Functions
static tw_event * tw_event_grab (tw_pe *pe)
static void tw_free_output_messages (tw_event *e, int print_message)
static tw_event * tw_event_new (tw_lpid dest_gid, tw_stime offset_ts, tw_lp *sender)
static void tw_event_free (tw_pe *pe, tw_event *e)
static void * tw_event_data (tw_event *event)
Function Documentation
static void* tw_event_data (tw_event * event) inline static
Definition at line 213 of file ross-inline.h.
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_num_add(), epi_num_check_report(), epi_num_remove(), event_handler(), forward(), ForwardDefault(), ForwardPacket(), init(), insert_into_pq(), Intersection_EventHandler(), Intersection_StartUp(), ip_downstream_forward(), ip_upstream(), Link_DeQueue(), Link_EnQueue(), mpi_init(), mpi_msg_send(), num_start(), olsr_arrival_to_mpr(), olsr_change_region(), olsr_departure_from_mpr(), olsr_event(), olsr_init(), olsr_region_init(), olsr_station_to_mpr(), ospf_event_send(), ospf_flood_recv(), ospf_ip_route(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_controller_gen_send(), raid_disk_gen_send(), raid_io_gen_send(), ReadAgentAct(), ReadGroupOp(), rm_cell_gather(), rm_cell_scatter(), rm_particle_send(), rm_proximity_send(), rm_wave_initiate(), rn_event_direct(), rn_event_handler(), rn_event_new(), rn_event_send(), rn_link_random_weight_changes(), rn_reverse_event_send(), rn_setup_links(), rn_timer_init(), rn_timer_reset(), rn_timer_simple(), route_packet(), Router_Arrival(), router_credit_send(), router_packet_receive(), router_packet_send(), Router_Recv(), router_reschedule_event(), sa_master_event(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), ScheduleTimer(), ScheduleTimerWithSn(), srw_event(), srw_init(), tcp_event_send(), tcp_host_process_ack(), tcp_host_process_ack_rc(), tcp_host_startup(), tcp_host_timeout(), tcp_host_update_rtt(), tcp_layer_init(), tcp_layer_process_ack(), tcp_layer_process_ack_rc(), tcp_layer_startup(), tcp_layer_timeout(), tcp_layer_update_rtt(), tcp_lp_init(), tcp_process_ack_rc(), tcp_util_event(), tlm_cell_gather(), tlm_cell_scatter(), tlm_particle_send(), tlm_proximity_send(), tlm_wave_initiate(), tmr_event_handler(), tw_sched_batch(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), tw_state_rollback(), wifi_access_point_arrival(), and wifi_station_arrival().
static void tw_event_free (tw_pe * pe, tw_event * e) inline static
Definition at line 86 of file ross-inline.h.
References tw_event::dest_lp, tw_pe::free_q, tw_event::next, tw_event::owner, tw_event::src_lp, tw_event::state, tw_eventq_unshift(), tw_free_output_messages(), tw_memory_unshift(), TW_net_outq, TW_pe_free_q, and TW_pe_sevent_q.
static tw_event* tw_event_grab (tw_pe * pe) inline static
Definition at line 5 of file ross-inline.h.
References tw_pe::abort_event, tw_event::cancel_next, tw_event::cause_next, tw_event::caused_by_me, tw_event::event_id, tw_pe::free_q, tw_event::next, tw_event::prev, tw_event::state, tw_eventq_pop(), TW_LOC, and tw_printf().
Referenced by recv_begin(), tw_event_new(), tw_socket_read_event(), and tw_timer_event_new().
static tw_event* tw_event_new (tw_lpid dest_gid, tw_stime offset_ts, tw_lp * sender) inline static
Bug:
There's a bug in this function. We put dest_gid, which is a 64-bit value, into dest_lp which may be a 32-bit pointer.
Definition at line 52 of file ross-inline.h.
References tw_pe::abort_event, CONSERVATIVE, tw_event::dest_lp, g_tw_min_detected_offset, g_tw_synchronization_protocol, g_tw_ts_end, tw_lp::pe, tw_event::recv_ts, tw_event::src_lp, tw_event_grab(), tw_free_output_messages(), and tw_now().
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_agent_send(), event_handler(), forward(), ForwardDefault(), ForwardPacket(), init(), insert_into_pq(), Intersection_EventHandler(), Intersection_StartUp(), ip_upstream(), Link_DeQueue(), Link_EnQueue(), mem_event_handler(), mem_init(), mpi_init(), mpi_msg_send(), olsr_arrival_to_mpr(), olsr_change_region(), olsr_departure_from_mpr(), olsr_event(), olsr_init(), olsr_region_init(), olsr_station_to_mpr(), ospf_flood_recv(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), phold_event_handler(), phold_init(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_controller_gen_send(), raid_disk_gen_send(), raid_io_gen_send(), ReadAgentAct(), ReadGroupOp(), rm_cell_gather(), rm_cell_scatter(), rm_particle_send(), rm_proximity_send(), rm_wave_initiate(), rn_event_direct(), rn_event_handler(), rn_event_new(), rn_link_random_weight_changes(), rn_setup_links(), rn_timer_simple(), rngt_init(), Router_Arrival(), router_credit_send(), router_packet_receive(), router_packet_send(), Router_Recv(), router_reschedule_event(), sa_master_event(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), srw_event(), srw_init(), tcp_event_send(), tcp_util_event(), tlm_cell_gather(), tlm_cell_scatter(), tlm_particle_send(), tlm_proximity_send(), tlm_wave_initiate(), tmr_event_handler(), tmr_init(), wifi_access_point_arrival(), and wifi_station_arrival().
static void tw_free_output_messages (tw_event * e, int print_message) inline static
Definition at line 35 of file ross-inline.h.
References tw_out::message, tw_out::next, tw_event::out_msgs, and tw_kp_put_back_output_buffer().
Referenced by tw_event_free(), and tw_event_new().