ROSS: ross/models/srw/rn-netdmf.c File Reference
rn-netdmf.c File Reference
NetDMF Support.
#include <ross.h>
#include "srw.h"
Functions
void rnNetDMFInit ()
void rn_netdmf_init ()
void rn_netdmf_topology ()
void attach_node_to_lp (long lpnum, long nodeId)
void insert_into_pq (srw_event_type ty, tw_stime time_offset, tw_lp *lp, long nodeid)
Detailed Description
The functions defined in this file will mostly just call corresponding functions in the rn-netdmf-wrapper.cpp file. This is necessary because the C++ compiler actually chokes on our ROSS code.
Definition in file rn-netdmf.c.
Function Documentation
void attach_node_to_lp (long lpnum, long nodeId)
Attach an srw_node_info struct to an LP.
Definition at line 43 of file rn-netdmf.c.
References tw_lp::cur_state, g_tw_lp, srw_node_info::node_id, srw_state::nodes, and srw_state::num_radios.
Referenced by parseNodes().
void insert_into_pq (srw_event_type ty, tw_stime time_offset, tw_lp * lp, long nodeid)
Insert a newly created event into our priority queue for this LP
Definition at line 56 of file rn-netdmf.c.
References COMMUNICATION, tw_lp::gid, GPS, MOVEMENT, srw_msg_data::node_id, tw_event_data(), tw_event_new(), tw_event_send(), and srw_msg_data::type.
void rn_netdmf_init ()
This function handles initialization of the NetDMF description language. It simply calls the rnNetDMFInit function which is declared extern "C". This function should use our global variable containing the filename of the configuration. Further, this function WILL be called via function pointer after the LPs are properly configured. We need to be called at that point so we can adjust data contained in the LP states/events.
Definition at line 26 of file rn-netdmf.c.
References rnNetDMFInit().
void rn_netdmf_topology ()
This function creates and setups the g_rn_machines global data structure of nodes.
Definition at line 36 of file rn-netdmf.c.
void rnNetDMFInit ()
This function handles initialization of the NetDMF description language. The function currently doesn't do much except demonstrate proper linkage.
This function handles initialization of the NetDMF description language.
Definition at line 51 of file rn-netdmf-wrapper.cpp.
References dom, g_rn_netdmf_config, netdmf_config, parseScenarios(), and root.
Referenced by rn_netdmf_init().