ROSS: ross/models/tcp-ip/tcp-rc-process.c File Reference
tcp-rc-process.c File Reference
#include "tcp.h"
Functions
void tcp_rc_process_ack (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
void tcp_rc_process_data (tcp_state *state, tw_bf *bf, tcp_message *in, tw_lp *lp)
Function Documentation
void tcp_rc_process_ack (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 7 of file tcp-rc-process.c.
References tcp_message::ack, tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tw_bf::c15, tw_bf::c2, tw_bf::c3, tw_bf::c4, tw_bf::c5, tw_bf::c6, tw_bf::c7, tw_bf::c9, tcp_state::cwnd, RC::cwnd, tcp_message::dst, tcp_state::dup_count, RC::dup_count, tw_lp::id, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_message::RC, tcp_state::rto, tcp_state::rto_seq, tcp_state::rtt_seq, RC::rtt_seq, tcp_state::rtt_time, RC::rtt_time, tcp_statistics::sent, tcp_state::seq_num, RC::seq_num, tcp_message::seq_num, tcp_state::ssthresh, tcp_state::stats, tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_state::timer, and tcp_state::unack.
Referenced by tcp_rc_event_handler().
void tcp_rc_process_data (tcp_state * state, tw_bf * bf, tcp_message * in, tw_lp * lp)
Definition at line 94 of file tcp-rc-process.c.
References tcp_statistics::ack_sent, tw_bf::c2, tw_bf::c3, tw_bf::c4, RC::dup_count, tcp_state::lastsent, RC::lastsent, tcp_state::mss, tcp_state::out_of_order, tcp_message::RC, tcp_statistics::recv, tcp_state::recv_wnd, tcp_state::seq_num, tcp_message::seq_num, tcp_state::stats, tw_error(), and TW_LOC.
Referenced by tcp_rc_event_handler().