ROSS: rnf/modules/network/multicast/Routing.c File Reference
Routing.c File Reference
#include "Routing.h"
Functions
void InitMRoute ()
int AddMRoute (int lpId, uint32 groupId, uint16 inPort)
int DelMRoute (int lpId, uint32 groupId, uint16 inPort)
MapUnitType * GetFwdPortMap (int lpId, uint32 groupId)
Link * GetFwdLink (int routerIdx, uint32 destAddr)
void AddGroup (uint32 groupId, int srcId)
int GetGroupSrcId (uint32 groupId)
void DelGroup (uint32 groupId)
uint32 AllocGroupAddr ()
void JoinGroup (int routerIdx, uint32 groupId)
void LeaveGroup (int routerIdx, uint32 groupId)
int IsBitSet (MapUnitType *map, uint16 pos)
void SetBit (MapUnitType *map, uint16 pos)
void ResetBit (MapUnitType *map, uint16 pos)
int IsEmptyMap (MapUnitType *map)
Variables
MRouteHash _mrouteTable [36677]
GroupInfoHash _groupTable [1009]
Function Documentation
void AddGroup (uint32 groupId, int srcId)
Definition at line 177 of file Routing.c.
References GroupInfoHashStruct::gi_, GROUP_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, GroupInfoHashStruct::head_, GroupInfoHashStruct::tail_, and GroupInfoStruct::used_.
Referenced by GmccSrcStart(), McastEventHandler(), and ReadGroupOp().
int AddMRoute (int lpId, uint32 groupId, uint16 inPort)
Definition at line 19 of file Routing.c.
References HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, MRouteHashStruct::head_, MROUTE_TABLE_SIZE, MRouteHashStruct::route_, SetBit(), MRouteHashStruct::tail_, and MRouteStruct::used_.
Referenced by JoinGroup().
uint32 AllocGroupAddr () inline
Definition at line 273 of file Routing.c.
References GetGroupSrcId().
Referenced by GmccSrcStart().
void DelGroup (uint32 groupId)
Definition at line 251 of file Routing.c.
References GroupInfoHashStruct::gi_, GROUP_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, GroupInfoHashStruct::head_, and GroupInfoHashStruct::tail_.
int DelMRoute (int lpId, uint32 groupId, uint16 inPort)
Definition at line 80 of file Routing.c.
References HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, MRouteHashStruct::head_, IsEmptyMap(), MROUTE_TABLE_SIZE, ResetBit(), MRouteHashStruct::route_, and MRouteHashStruct::tail_.
Referenced by LeaveGroup().
Link* GetFwdLink (int routerIdx, uint32 destAddr)
Definition at line 147 of file Routing.c.
References _nodeTable, LinkStruct::active_, NodeStruct::addr_, NodeStruct::firstLink_, NodeStruct::highAddr_, NodeStruct::link, LinkStruct::neighbour_, LinkStruct::next_, LinkStruct::route_, and NodeStruct::upLink_.
Referenced by ForwardUnicastPkt(), JoinGroup(), and LeaveGroup().
MapUnitType* GetFwdPortMap (int lpId, uint32 groupId)
Definition at line 123 of file Routing.c.
References HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, MRouteHashStruct::head_, MROUTE_TABLE_SIZE, MRouteStruct::portMap_, MRouteHashStruct::route_, and MRouteHashStruct::tail_.
Referenced by McastEventHandler(), SendExtPkt(), and SendPacket().
int GetGroupSrcId (uint32 groupId)
Definition at line 231 of file Routing.c.
References GroupInfoHashStruct::gi_, GROUP_TABLE_SIZE, HASH_BUCKET_DEPTH, HASH_DIST_FACTOR, GroupInfoHashStruct::head_, GroupInfoStruct::srcId_, and GroupInfoHashStruct::tail_.
Referenced by AllocGroupAddr(), JoinGroup(), and LeaveGroup().
void InitMRoute () inline
Definition at line 6 of file Routing.c.
References GROUP_TABLE_SIZE, and MROUTE_TABLE_SIZE.
int IsBitSet (MapUnitType * map, uint16 pos) inline
Definition at line 358 of file Routing.c.
References MAP_UNIT_SIZE, and PORT_MAP_SIZE.
Referenced by ForwardMulticastPkt().
int IsEmptyMap (MapUnitType * map) inline
Definition at line 404 of file Routing.c.
References MAP_UNIT_SIZE, and PORT_MAP_SIZE.
Referenced by DelMRoute(), and McastEventHandler().
void JoinGroup (int routerIdx, uint32 groupId)
Definition at line 292 of file Routing.c.
References _nodeTable, AddMRoute(), NodeStruct::addr_, GetFwdLink(), GetGroupSrcId(), GetGrpAddr4Print, HIGHEST_MAP_BIT_POS, LinkStruct::nbPort_, and LinkStruct::neighbour_.
Referenced by GmccRcvJump(), McastEventHandler(), and ReadGroupOp().
void LeaveGroup (int routerIdx, uint32 groupId)
Definition at line 325 of file Routing.c.
References _nodeTable, NodeStruct::addr_, DelMRoute(), GetFwdLink(), GetGroupSrcId(), GetGrpAddr4Print, HIGHEST_MAP_BIT_POS, LinkStruct::nbPort_, and LinkStruct::neighbour_.
Referenced by GmccRcvLeave(), McastEventHandler(), and ReadGroupOp().
void ResetBit (MapUnitType * map, uint16 pos) inline
Definition at line 386 of file Routing.c.
References MAP_UNIT_SIZE, and PORT_MAP_SIZE.
Referenced by DelMRoute().
void SetBit (MapUnitType * map, uint16 pos) inline
Definition at line 368 of file Routing.c.
References MAP_UNIT_SIZE, and PORT_MAP_SIZE.
Referenced by AddMRoute().
Variable Documentation
GroupInfoHash _groupTable[1009]
Definition at line 4 of file Routing.c.
MRouteHash _mrouteTable[36677]
Definition at line 3 of file Routing.c.