ROSS: rnf/modules/mobility/robot-physsym/rp-extern.h File Reference
rp-extern.h File Reference
Functions
void rp_xml (rp_state *, const xmlNodePtr node, tw_lp *)
void rp_md_opts ()
void rp_md_init (int argc, char **argv, char **env)
void rp_md_final ()
int rp_main (int argc, char **argv, char **env)
void rp_init (rp_state *, tw_lp *)
void rp_event_handler (rp_state *, tw_bf *, rn_message *, tw_lp *)
void rp_rc_event_handler (rp_state *, tw_bf *, rn_message *, tw_lp *)
void rp_final (rp_state *, tw_lp *)
rp_connection * rp_connect (rp_state *, tw_bf *, rp_message *, tw_lp *, int blk)
rp_connection * rp_disconnect (rp_state *, tw_bf *, rp_message *, tw_lp *, int)
void rp_move (rp_state *state, rp_message *m, tw_bf *bf, tw_lp *)
void rp_rc_move (rp_state *, rp_message *, tw_bf *, tw_lp *)
double rp_distance (double x0, double y0, double x1, double y1)
double rp_intercept (double x, double y, double slope)
double rp_slope (double x0, double y0, double x1, double y1)
void rp_sort (double *p)
Variables
tw_fd g_rp_fd
rp_statistics * g_rp_stats
int g_rp_plot
FILE * g_rp_position_f
unsigned int * g_rp_position_x
unsigned int * g_rp_position_y
unsigned int * g_rp_ids
unsigned int g_rp_mu
unsigned int g_rp_distr_sd
tw_stime percent_wave
Function Documentation
rp_connection* rp_connect (rp_state * , tw_bf * , rp_message * , tw_lp * , int blk)
rp_connection* rp_disconnect (rp_state * , tw_bf * , rp_message * , tw_lp * , int)
double rp_distance (double x0, double y0, double x1, double y1)
void rp_event_handler (rp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 88 of file rp.c.
References g_rp_fd, g_tw_mynode, tw_lp::gid, tw_lp::id, rp_state::pc_input, rp_state::pc_output, percent_wave, physSimControl(), rp_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rp_state::robot, rp_move(), RP_TIMESTEP, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, rp_state::stats, tlm_wave_initiate(), rp_state::transmit, tw_error(), TW_LOC, tw_memory_free(), tw_rand_unif, and rp_message::type.
void rp_final (rp_state * , tw_lp *)
Definition at line 186 of file rp.c.
References g_rp_stats, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, and rp_state::stats.
void rp_init (rp_state * , tw_lp *)
Definition at line 15 of file rp.c.
References rp_state::frequency, g_rp_distr_sd, g_rp_fd, g_rp_mu, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, rp_state::position, rp_state::prev_time, rp_state::range, rn_event_direct(), rn_event_send(), tw_lp::rng, RP_TIMESTEP, rp_state::stats, tlm_getelevation(), rp_state::transmit, tw_calloc(), TW_LOC, tw_memory_alloc(), tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), rp_message::type, and rp_state::velocity.
double rp_intercept (double x, double y, double slope)
int rp_main (int argc, char ** argv, char ** env)
void rp_md_final ()
Definition at line 38 of file rp-model.c.
References g_rp_stats, percent_wave, rp_statistics::s_move_ev, rp_statistics::s_nconnect, rp_statistics::s_ndisconnect, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, and tw_ismaster().
void rp_md_init (int argc, char ** argv, char ** env)
Definition at line 18 of file rp-model.c.
References g_rp_fd, g_rp_stats, g_tw_nkp, nbufs, tw_calloc(), tw_ismaster(), TW_LOC, and tw_memory_init().
void rp_md_opts ()
Definition at line 12 of file rp-model.c.
References tw_opt_add().
void rp_move (rp_state * state, rp_message * m, tw_bf * bf, tw_lp *)
Definition at line 104 of file rp-node.c.
References rp_state::change_dir, rp_message::change_dir, change_direction(), g_rp_fd, tw_lp::gid, tw_lp::id, new_location(), off_grid(), rp_state::position, rc_new_location(), rn_event_direct(), tw_lp::rng, RP_TIMESTEP, rp_state::theta, rp_message::theta, tlm_getelevation(), tw_event_send(), TW_LOC, tw_memory_alloc(), tw_now(), tw_printf(), tw_rand_exponential(), rp_message::type, rp_message::x_pos, and rp_message::y_pos.
Referenced by rp_event_handler().
void rp_rc_event_handler (rp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 144 of file rp.c.
References g_rp_fd, tw_lp::gid, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rp_rc_move(), RP_TIMESTEP, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, rp_state::stats, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, and rp_message::type.
void rp_rc_move (rp_state * , rp_message * , tw_bf * , tw_lp *)
Definition at line 164 of file rp-node.c.
References rp_state::change_dir, rp_message::change_dir, rp_state::position, tw_lp::rng, rp_state::theta, rp_message::theta, tw_rand_reverse_unif, rp_message::x_pos, and rp_message::y_pos.
Referenced by rp_rc_event_handler().
double rp_slope (double x0, double y0, double x1, double y1)
void rp_sort (double * p)
void rp_xml (rp_state * , const xmlNodePtr node, tw_lp *)
Definition at line 4 of file rp-xml.c.
Variable Documentation
unsigned int g_rp_distr_sd
Definition at line 27 of file rp-global.c.
Referenced by change_direction(), and rp_init().
tw_fd g_rp_fd
Definition at line 3 of file rp-global.c.
Referenced by rp_event_handler(), rp_init(), rp_md_init(), rp_move(), and rp_rc_event_handler().
unsigned int* g_rp_ids
Definition at line 23 of file rp-global.c.
unsigned int g_rp_mu
Definition at line 26 of file rp-global.c.
Referenced by change_direction(), and rp_init().
int g_rp_plot
Definition at line 13 of file rp-global.c.
FILE* g_rp_position_f
Definition at line 20 of file rp-global.c.
unsigned int* g_rp_position_x
Definition at line 21 of file rp-global.c.
unsigned int* g_rp_position_y
Definition at line 22 of file rp-global.c.
rp_statistics* g_rp_stats
Definition at line 15 of file rp-global.c.
Referenced by rp_final(), rp_md_final(), and rp_md_init().
tw_stime percent_wave
Definition at line 29 of file rw-global.c.