ROSS: rnf/modules/mobility/robot-physsym/rp-model.c File Reference
rp-model.c File Reference
#include <rp.h>
Functions
void rp_md_opts ()
void rp_md_init (int argc, char **argv, char **env)
void rp_md_final ()
Variables
static const tw_optdef rp_options []
Function Documentation
void rp_md_final ()
Definition at line 38 of file rp-model.c.
References g_rp_stats, percent_wave, rp_statistics::s_move_ev, rp_statistics::s_nconnect, rp_statistics::s_ndisconnect, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, and tw_ismaster().
void rp_md_init (int argc, char ** argv, char ** env)
Definition at line 18 of file rp-model.c.
References g_rp_fd, g_rp_stats, g_tw_nkp, nbufs, tw_calloc(), tw_ismaster(), TW_LOC, and tw_memory_init().
void rp_md_opts ()
Definition at line 12 of file rp-model.c.
References tw_opt_add().
Variable Documentation
const tw_optdef rp_options[] static
Initial value:
=
{
        TWOPT_UINT("rw-min", g_rp_mu, "random walk min change dir"),
        TWOPT_UINT("rw-max", g_rp_distr_sd, "random walk max change dir"),
        TWOPT_STIME("wave-percent", percent_wave, "percentage of waves per move"),
}
Definition at line 3 of file rp-model.c.