ROSS: rnf/modules/mobility/robot-physsym/rp-node.c File Reference
rp-node.c File Reference
#include <rp.h>
Functions
int off_grid (double *p)
void change_direction (rp_state *state, rp_message *m, tw_bf *bf, tw_lp *lp)
void new_location (rp_state *state, tw_bf *bf, tw_lp *lp)
void rc_new_location (rp_state *state, tw_bf *bf, tw_lp *lp)
void rp_move (rp_state *state, rp_message *m, tw_bf *bf, tw_lp *lp)
void rp_rc_move (rp_state *state, rp_message *m, tw_bf *bf, tw_lp *lp)
Function Documentation
void change_direction (rp_state * state, rp_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 24 of file rp-node.c.
References rp_state::change_dir, g_rp_distr_sd, g_rp_mu, g_tlm_spatial_d, tw_lp::rng, rp_state::theta, tw_error(), TW_LOC, tw_now(), tw_rand_integer(), and rp_state::velocity.
void new_location (rp_state * state, tw_bf * bf, tw_lp * lp) inline
Definition at line 87 of file rp-node.c.
References rp_state::position, and rp_state::velocity.
int off_grid (double * p)
Definition at line 4 of file rp-node.c.
References g_tlm_spatial_d, and g_tlm_spatial_grid.
void rc_new_location (rp_state * state, tw_bf * bf, tw_lp * lp) inline
Definition at line 94 of file rp-node.c.
References rp_state::position, and rp_state::velocity.
void rp_move (rp_state * state, rp_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 104 of file rp-node.c.
References rp_state::change_dir, rp_message::change_dir, change_direction(), g_rp_fd, tw_lp::gid, tw_lp::id, new_location(), off_grid(), rp_state::position, rc_new_location(), rn_event_direct(), tw_lp::rng, RP_TIMESTEP, rp_state::theta, rp_message::theta, tlm_getelevation(), tw_event_send(), TW_LOC, tw_memory_alloc(), tw_now(), tw_printf(), tw_rand_exponential(), rp_message::type, rp_message::x_pos, and rp_message::y_pos.
Referenced by rp_event_handler().
void rp_rc_move (rp_state * state, rp_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 164 of file rp-node.c.
References rp_state::change_dir, rp_message::change_dir, rp_state::position, tw_lp::rng, rp_state::theta, rp_message::theta, tw_rand_reverse_unif, rp_message::x_pos, and rp_message::y_pos.
Referenced by rp_rc_event_handler().