ROSS: rnf/modules/mobility/robot-physsym/rp.c File Reference
rp.c File Reference
#include <rp.h>
Functions
void rp_init (rp_state *state, tw_lp *lp)
void rp_event_handler (rp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rp_rc_event_handler (rp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rp_final (rp_state *state, tw_lp *lp)
Function Documentation
void rp_event_handler (rp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 88 of file rp.c.
References g_rp_fd, g_tw_mynode, tw_lp::gid, tw_lp::id, rp_state::pc_input, rp_state::pc_output, percent_wave, physSimControl(), rp_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rp_state::robot, rp_move(), RP_TIMESTEP, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, rp_state::stats, tlm_wave_initiate(), rp_state::transmit, tw_error(), TW_LOC, tw_memory_free(), tw_rand_unif, and rp_message::type.
void rp_final (rp_state * state, tw_lp * lp)
Definition at line 186 of file rp.c.
References g_rp_stats, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, and rp_state::stats.
void rp_init (rp_state * state, tw_lp * lp)
Definition at line 15 of file rp.c.
References rp_state::frequency, g_rp_distr_sd, g_rp_fd, g_rp_mu, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, rp_state::position, rp_state::prev_time, rp_state::range, rn_event_direct(), rn_event_send(), tw_lp::rng, RP_TIMESTEP, rp_state::stats, tlm_getelevation(), rp_state::transmit, tw_calloc(), TW_LOC, tw_memory_alloc(), tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), rp_message::type, and rp_state::velocity.
void rp_rc_event_handler (rp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 144 of file rp.c.
References g_rp_fd, tw_lp::gid, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rp_rc_move(), RP_TIMESTEP, rp_statistics::s_move_ev, rp_statistics::s_nwaves, rp_statistics::s_prox_ev, rp_statistics::s_recv_ev, rp_state::stats, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, and rp_message::type.