ROSS: rnf/modules/mobility/random-walk/rw-extern.h File Reference
rw-extern.h File Reference
Functions
void rw_xml (rw_state *, const xmlNodePtr node, tw_lp *)
void rw_md_opts ()
void rw_md_init (int argc, char **argv, char **env)
void rw_md_final ()
int rw_main (int argc, char **argv, char **env)
void rw_init (rw_state *, tw_lp *)
void rw_event_handler (rw_state *, tw_bf *, rn_message *, tw_lp *)
void rw_rc_event_handler (rw_state *, tw_bf *, rn_message *, tw_lp *)
void rw_final (rw_state *, tw_lp *)
rw_connection * rw_connect (rw_state *, tw_bf *, rw_message *, tw_lp *, int blk)
rw_connection * rw_disconnect (rw_state *, tw_bf *, rw_message *, tw_lp *, int)
void rw_move (rw_state *state, rw_message *m, tw_bf *bf, tw_lp *)
void rw_rc_move (rw_state *, rw_message *, tw_bf *, tw_lp *)
double rw_distance (double x0, double y0, double x1, double y1)
double rw_intercept (double x, double y, double slope)
double rw_slope (double x0, double y0, double x1, double y1)
void rw_sort (double *p)
Variables
tw_fd g_rw_fd
rw_statistics * g_rw_stats
int g_rw_plot
FILE * g_rw_position_f
unsigned int * g_rw_position_x
unsigned int * g_rw_position_y
unsigned int * g_rw_ids
unsigned int g_rw_mu
unsigned int g_rw_distr_sd
tw_stime percent_wave
Function Documentation
rw_connection* rw_connect (rw_state * , tw_bf * , rw_message * , tw_lp * , int blk)
rw_connection* rw_disconnect (rw_state * , tw_bf * , rw_message * , tw_lp * , int)
double rw_distance (double x0, double y0, double x1, double y1) inline
Definition at line 25 of file rw-helper.c.
void rw_event_handler (rw_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 88 of file rw.c.
References g_rw_fd, g_tw_mynode, tw_lp::gid, tw_lp::id, percent_wave, rw_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rw_move(), RW_TIMESTEP, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, rw_state::stats, tlm_wave_initiate(), rw_state::transmit, tw_error(), TW_LOC, tw_memory_free(), tw_rand_unif, and rw_message::type.
void rw_final (rw_state * , tw_lp *)
Definition at line 184 of file rw.c.
References g_rw_stats, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, and rw_state::stats.
void rw_init (rw_state * , tw_lp *)
Definition at line 15 of file rw.c.
References rw_state::frequency, g_rw_distr_sd, g_rw_fd, g_rw_mu, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, rw_state::position, rw_state::prev_time, rw_state::range, rn_event_direct(), rn_event_send(), tw_lp::rng, RW_TIMESTEP, rw_state::stats, tlm_getelevation(), rw_state::transmit, tw_calloc(), TW_LOC, tw_memory_alloc(), tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), rw_message::type, and rw_state::velocity.
double rw_intercept (double x, double y, double slope) inline
Definition at line 35 of file rw-helper.c.
int rw_main (int argc, char ** argv, char ** env)
void rw_md_final ()
Definition at line 38 of file rw-model.c.
References g_rw_stats, percent_wave, rw_statistics::s_move_ev, rw_statistics::s_nconnect, rw_statistics::s_ndisconnect, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, and tw_ismaster().
void rw_md_init (int argc, char ** argv, char ** env)
Definition at line 18 of file rw-model.c.
References g_rw_fd, g_rw_stats, g_tw_nkp, nbufs, tw_calloc(), tw_ismaster(), TW_LOC, and tw_memory_init().
void rw_md_opts ()
Definition at line 12 of file rw-model.c.
References tw_opt_add().
void rw_move (rw_state * state, rw_message * m, tw_bf * bf, tw_lp *)
Definition at line 104 of file rw-node.c.
References rw_state::change_dir, rw_message::change_dir, change_direction(), g_rw_fd, tw_lp::gid, tw_lp::id, new_location(), off_grid(), rw_state::position, rc_new_location(), rn_event_direct(), tw_lp::rng, RW_TIMESTEP, rw_state::theta, rw_message::theta, tlm_getelevation(), tw_event_send(), TW_LOC, tw_memory_alloc(), tw_now(), tw_printf(), tw_rand_exponential(), rw_message::type, rw_message::x_pos, and rw_message::y_pos.
Referenced by rw_event_handler().
void rw_rc_event_handler (rw_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 142 of file rw.c.
References g_rw_fd, tw_lp::gid, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rw_rc_move(), RW_TIMESTEP, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, rw_state::stats, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, and rw_message::type.
void rw_rc_move (rw_state * , rw_message * , tw_bf * , tw_lp *)
Definition at line 164 of file rw-node.c.
References rw_state::change_dir, rw_message::change_dir, rw_state::position, tw_lp::rng, rw_state::theta, rw_message::theta, tw_rand_reverse_unif, rw_message::x_pos, and rw_message::y_pos.
Referenced by rw_rc_event_handler().
double rw_slope (double x0, double y0, double x1, double y1) inline
Definition at line 45 of file rw-helper.c.
void rw_sort (double * p) inline
Definition at line 8 of file rw-helper.c.
void rw_xml (rw_state * , const xmlNodePtr node, tw_lp *)
Definition at line 4 of file rw-xml.c.
Variable Documentation
unsigned int g_rw_distr_sd
Definition at line 27 of file rw-global.c.
Referenced by change_direction(), and rw_init().
tw_fd g_rw_fd
Definition at line 3 of file rw-global.c.
Referenced by rw_event_handler(), rw_init(), rw_md_init(), rw_move(), and rw_rc_event_handler().
unsigned int* g_rw_ids
Definition at line 23 of file rw-global.c.
unsigned int g_rw_mu
Definition at line 26 of file rw-global.c.
Referenced by change_direction(), and rw_init().
int g_rw_plot
Definition at line 13 of file rw-global.c.
FILE* g_rw_position_f
Definition at line 20 of file rw-global.c.
unsigned int* g_rw_position_x
Definition at line 21 of file rw-global.c.
unsigned int* g_rw_position_y
Definition at line 22 of file rw-global.c.
rw_statistics* g_rw_stats
Definition at line 15 of file rw-global.c.
Referenced by rw_final(), rw_md_final(), and rw_md_init().
tw_stime percent_wave
Definition at line 29 of file rw-global.c.
Referenced by pm_event_handler(), pm_stats_print(), rp_event_handler(), rp_md_final(), rw_event_handler(), and rw_md_final().