ROSS: rnf/modules/mobility/random-walk/rw-model.c File Reference
rw-model.c File Reference
#include <rw.h>
Functions
void rw_md_opts ()
void rw_md_init (int argc, char **argv, char **env)
void rw_md_final ()
Variables
static const tw_optdef rw_options []
Function Documentation
void rw_md_final ()
Definition at line 38 of file rw-model.c.
References g_rw_stats, percent_wave, rw_statistics::s_move_ev, rw_statistics::s_nconnect, rw_statistics::s_ndisconnect, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, and tw_ismaster().
void rw_md_init (int argc, char ** argv, char ** env)
Definition at line 18 of file rw-model.c.
References g_rw_fd, g_rw_stats, g_tw_nkp, nbufs, tw_calloc(), tw_ismaster(), TW_LOC, and tw_memory_init().
void rw_md_opts ()
Definition at line 12 of file rw-model.c.
References tw_opt_add().
Variable Documentation
const tw_optdef rw_options[] static
Initial value:
=
{
        TWOPT_UINT("rw-min", g_rw_mu, "random walk min change dir"),
        TWOPT_UINT("rw-max", g_rw_distr_sd, "random walk max change dir"),
        TWOPT_STIME("wave-percent", percent_wave, "percentage of waves per move"),
}
Definition at line 3 of file rw-model.c.