ROSS: rnf/modules/mobility/random-walk/rw-node.c File Reference
rw-node.c File Reference
#include <rw.h>
Functions
int off_grid (double *p)
void change_direction (rw_state *state, rw_message *m, tw_bf *bf, tw_lp *lp)
void new_location (rw_state *state, tw_bf *bf, tw_lp *lp)
void rc_new_location (rw_state *state, tw_bf *bf, tw_lp *lp)
void rw_move (rw_state *state, rw_message *m, tw_bf *bf, tw_lp *lp)
void rw_rc_move (rw_state *state, rw_message *m, tw_bf *bf, tw_lp *lp)
Function Documentation
void change_direction (rw_state * state, rw_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 24 of file rw-node.c.
References rw_state::change_dir, g_rw_distr_sd, g_rw_mu, g_tlm_spatial_d, tw_lp::rng, rw_state::theta, tw_error(), TW_LOC, tw_now(), tw_rand_integer(), and rw_state::velocity.
Referenced by pm_move(), rp_move(), and rw_move().
void new_location (rw_state * state, tw_bf * bf, tw_lp * lp) inline
Definition at line 87 of file rw-node.c.
References rw_state::position, and rw_state::velocity.
Referenced by pm_move(), rp_move(), and rw_move().
int off_grid (double * p)
Definition at line 4 of file rw-node.c.
References g_tlm_spatial_d, and g_tlm_spatial_grid.
Referenced by pm_move(), rp_move(), and rw_move().
void rc_new_location (rw_state * state, tw_bf * bf, tw_lp * lp) inline
Definition at line 94 of file rw-node.c.
References rw_state::position, and rw_state::velocity.
Referenced by pm_move(), rp_move(), and rw_move().
void rw_move (rw_state * state, rw_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 104 of file rw-node.c.
References rw_state::change_dir, rw_message::change_dir, change_direction(), g_rw_fd, tw_lp::gid, tw_lp::id, new_location(), off_grid(), rw_state::position, rc_new_location(), rn_event_direct(), tw_lp::rng, RW_TIMESTEP, rw_state::theta, rw_message::theta, tlm_getelevation(), tw_event_send(), TW_LOC, tw_memory_alloc(), tw_now(), tw_printf(), tw_rand_exponential(), rw_message::type, rw_message::x_pos, and rw_message::y_pos.
Referenced by rw_event_handler().
void rw_rc_move (rw_state * state, rw_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 164 of file rw-node.c.
References rw_state::change_dir, rw_message::change_dir, rw_state::position, tw_lp::rng, rw_state::theta, rw_message::theta, tw_rand_reverse_unif, rw_message::x_pos, and rw_message::y_pos.
Referenced by rw_rc_event_handler().