ROSS: rnf/modules/mobility/random-walk/rw.c File Reference
rw.c File Reference
#include <rw.h>
Functions
void rw_init (rw_state *state, tw_lp *lp)
void rw_event_handler (rw_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rw_rc_event_handler (rw_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rw_final (rw_state *state, tw_lp *lp)
Function Documentation
void rw_event_handler (rw_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 88 of file rw.c.
References g_rw_fd, g_tw_mynode, tw_lp::gid, tw_lp::id, percent_wave, rw_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rw_move(), RW_TIMESTEP, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, rw_state::stats, tlm_wave_initiate(), rw_state::transmit, tw_error(), TW_LOC, tw_memory_free(), tw_rand_unif, and rw_message::type.
void rw_final (rw_state * state, tw_lp * lp)
Definition at line 184 of file rw.c.
References g_rw_stats, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, and rw_state::stats.
void rw_init (rw_state * state, tw_lp * lp)
Definition at line 15 of file rw.c.
References rw_state::frequency, g_rw_distr_sd, g_rw_fd, g_rw_mu, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, rw_state::position, rw_state::prev_time, rw_state::range, rn_event_direct(), rn_event_send(), tw_lp::rng, RW_TIMESTEP, rw_state::stats, tlm_getelevation(), rw_state::transmit, tw_calloc(), TW_LOC, tw_memory_alloc(), tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), rw_message::type, and rw_state::velocity.
void rw_rc_event_handler (rw_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 142 of file rw.c.
References g_rw_fd, tw_lp::gid, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, rw_rc_move(), RW_TIMESTEP, rw_statistics::s_move_ev, rw_statistics::s_nwaves, rw_statistics::s_prox_ev, rw_statistics::s_recv_ev, rw_state::stats, tw_error(), TW_LOC, tw_memory_free_rc(), tw_rand_reverse_unif, and rw_message::type.