ROSS: rnf/modules/network/ip/save/ip-model.c File Reference
ip-model.c File Reference
#include <ip.h>
Functions
void ip_md_init (int argc, char **argv, char **env)
void ip_md_final ()
Variables
const tw_optdef ip_opts []
Function Documentation
void ip_md_final ()
Definition at line 52 of file ip-model.c.
References g_ip_stats, ip_stats::s_avg_ttl, ip_stats::s_max_ttl, ip_stats::s_ncomplete, ip_stats::s_ndropped, ip_stats::s_ndropped_source, ip_stats::s_ndropped_ttl, ip_stats::s_nforward, ip_stats::s_nnet_failures, and tw_ismaster().
void ip_md_init (int argc, char ** argv, char ** env)
Definition at line 11 of file ip-model.c.
References g_ip_fd, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, g_ip_stats, g_rn_logs_dir, g_tw_nkp, ip_routing_init(), nbufs, tw_calloc(), tw_error(), tw_getkp(), tw_ismaster(), TW_LOC, tw_memory_init(), and tw_opt_add().
Variable Documentation
const tw_optdef ip_opts[]
Initial value:
=
{
        TWOPT_GROUP("IPv4 Model"),
        TWOPT_UINT("ip-log", g_ip_log_on, "turn on logging"),
}
Definition at line 3 of file ip-model.c.