ROSS: rnf/modules/application/num/save/num-extern.h File Reference
num-extern.h File Reference
Functions
void num_init (num_state *state, tw_lp *lp)
void num_event_handler (num_state *state, tw_bf *, rn_message *, tw_lp *lp)
void num_rc_event_handler (num_state *, tw_bf *, rn_message *, tw_lp *lp)
void num_final (num_state *state, tw_lp *lp)
void num_setup_options (int argc, char **argv)
void num_file_start (num_state *state, tw_bf *bf, unsigned int size, tw_lp *lp)
void num_file_stop (num_state *state, tw_bf *bf, tw_lp *lp)
void num_file_complete (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_report_levels (int)
void num_print ()
void num_init_scenario ()
char * get_tod (tw_stime)
void num_main (int argc, char **argv, char **env)
void num_xml (num_state *state, const xmlNodePtr node, tw_lp *lp)
void num_md_final ()
void num_timer_cancel (tw_event *timer, tw_lp *lp)
tw_event * num_timer_start (tw_event *timer, tw_stime ts, tw_lp *lp)
Variables
unsigned int * g_num_net_pop
unsigned int g_num_max_users
num_statistics * g_num_stats
unsigned int ** g_num_level
unsigned int * g_num_profile_cnts
int g_num_mod
int g_num_day
int g_num_debug
unsigned int g_num_debug_lp
unsigned int g_num_nprofiles
num_profile * g_num_profiles
char * g_num_profiles_fn
char * g_num_log_fn
FILE * g_num_log_f
Function Documentation
char* get_tod (tw_stime)
Definition at line 6 of file num-helper.c.
References d, s, tod, and TWENTY_FOUR_HOURS.
void num_event_handler (num_state * state, tw_bf * , rn_message * , tw_lp * lp)
Definition at line 185 of file num.c.
References num_state::file_size, num_file_complete(), num_file_start(), num_file_stop(), num_start(), num_update(), TIMER, rn_message::ttl, rn_message::type, and UPSTREAM.
void num_file_complete (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 55 of file num-file.c.
References num_profile::bitrate, DEBUG_LP, num_state::file_size, g_num_profiles, get_tod(), tw_lp::id, MAX_FILE_SIZE, MIN_FILE_SIZE, num_file_start(), QUIT_TIME, rn_timer_init(), num_statistics::s_nfailures, num_statistics::s_nfiles, num_statistics::s_total_kb, num_statistics::s_total_time, rn_message::size, num_state::start, num_state::stats, tw_error(), TW_LOC, tw_now(), TWENTY_FOUR_HOURS, TWO_MINUTES, and num_state::type.
void num_file_start (num_state * state, tw_bf * bf, unsigned int size, tw_lp * lp)
Definition at line 8 of file num-file.c.
References DEBUG_LP, DOWNSTREAM, num_state::file_size, get_tod(), tw_lp::gid, tw_lp::id, rn_event_new(), rn_event_send(), num_statistics::s_nstart, num_state::start, num_state::stats, tw_now(), and num_state::type.
void num_file_stop (num_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 24 of file num-file.c.
References DEBUG_LP, DOWNSTREAM, g_num_mod, g_num_nreport_days, get_tod(), tw_lp::gid, tw_lp::id, rn_event_new(), rn_event_send(), num_statistics::s_nstop, num_state::stats, tw_now(), and num_state::type.
void num_final (num_state * state, tw_lp * lp)
Definition at line 212 of file num.c.
References g_num_mod, g_num_stats, num_print(), num_report_levels(), num_statistics::s_nfiles, num_statistics::s_nstart, num_statistics::s_nstop, num_state::stats, tw_now(), and TWENTY_FOUR_HOURS.
void num_init (num_state * state, tw_lp * lp)
Definition at line 14 of file num.c.
References num_state::file_size, MIN_FILE_SIZE, num_state::stats, tw_calloc(), and TW_LOC.
void num_init_scenario ()
Definition at line 73 of file num-init.c.
References g_num_level, g_num_log_f, g_num_log_fn, g_num_mod, g_num_net_pop, g_num_nprofiles, g_num_profile_cnts, g_num_profiles_fn, init_default_profiles(), init_profiles_from_file(), NUM_LEVELS, tw_calloc(), tw_error(), and TW_LOC.
void num_main (int argc, char ** argv, char ** env)
Definition at line 14 of file num-main.c.
References g_num_stats, g_tw_ts_end, num_init_scenario(), num_setup_options(), tw_calloc(), and TW_LOC.
void num_md_final ()
Definition at line 33 of file num-main.c.
References g_num_log_f, g_num_max_users, g_num_stats, num_statistics::s_nfiles, num_statistics::s_nstart, and num_statistics::s_nstop.
void num_print ()
Definition at line 33 of file num-report.c.
References g_num_day, g_num_level, g_num_log_f, g_num_max_users, g_num_mod, g_num_net_pop, g_num_nprofiles, g_num_profile_cnts, and NUM_LEVELS.
void num_rc_event_handler (num_state * , tw_bf * , rn_message * , tw_lp * lp)
Definition at line 203 of file num.c.
References tw_error(), and TW_LOC.
void num_report_levels (int)
Definition at line 130 of file num-report.c.
References g_num_day, g_num_log_f, g_num_mod, g_num_next_report_day, g_num_nreport_days, g_num_report_days, and num_print().
void num_setup_options (int argc, char ** argv)
Definition at line 29 of file num-setup.c.
References g_num_day, g_num_debug, g_num_log_fn, g_num_mod, g_num_nreport_days, g_num_profiles_fn, g_num_report_days, g_rn_logs_dir, g_rn_tools_dir, MAX_REPORT_DAYS, tw_calloc(), tw_error(), and TW_LOC.
void num_timer_cancel (tw_event * timer, tw_lp * lp)
Definition at line 9 of file num-timer.c.
References rn_timer_cancel(), tw_error(), and TW_LOC.
tw_event* num_timer_start (tw_event * timer, tw_stime ts, tw_lp * lp)
Definition at line 18 of file num-timer.c.
References rn_timer_init(), rn_timer_reset(), tw_event::state, tw_error(), TW_LOC, and tw_now().
void num_xml (num_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 4 of file num-xml.c.
References g_num_profile_cnts, num_state::stats, tw_calloc(), TW_LOC, num_state::type, and xml_getprop().
Variable Documentation
int g_num_day
Definition at line 15 of file num-global.c.
int g_num_debug
Definition at line 16 of file num-global.c.
unsigned int g_num_debug_lp
Definition at line 17 of file num-global.c.
unsigned int** g_num_level
Definition at line 9 of file num-global.c.
FILE* g_num_log_f
Definition at line 26 of file num-global.c.
char* g_num_log_fn
Definition at line 20 of file num-global.c.
unsigned int g_num_max_users
Definition at line 12 of file num-global.c.
int g_num_mod
Definition at line 8 of file num-global.c.
unsigned int* g_num_net_pop
Definition at line 11 of file num-global.c.
unsigned int g_num_nprofiles
Definition at line 13 of file num-global.c.
unsigned int* g_num_profile_cnts
Definition at line 14 of file num-global.c.
num_profile* g_num_profiles
Definition at line 18 of file num-global.c.
char* g_num_profiles_fn
Definition at line 19 of file num-global.c.
num_statistics* g_num_stats
Definition at line 6 of file num-global.c.