ROSS: rnf/modules/application/num/save/num.c File Reference
num.c File Reference
#include <num.h>
Macros
#define ONE 0
#define DEBUG_LP 504065
Functions
void num_init (num_state *state, tw_lp *lp)
void num_update (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_start (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_event_handler (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_rc_event_handler (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_final (num_state *state, tw_lp *lp)
Macro Definition Documentation
#define DEBUG_LP 504065
Definition at line 7 of file num.c.
Referenced by num_start().
#define ONE 0
Definition at line 4 of file num.c.
Function Documentation
void num_event_handler (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 168 of file num.c.
References num_state::file_size, num_file_complete(), num_file_start(), num_file_stop(), num_start(), num_update(), TIMER, rn_message::ttl, rn_message::type, and UPSTREAM.
void num_final (num_state * state, tw_lp * lp)
Definition at line 195 of file num.c.
References g_num_mod, g_num_stats, num_print(), num_report_levels(), num_statistics::s_nfiles, num_statistics::s_nstart, num_statistics::s_nstop, num_state::stats, tw_now(), and TWENTY_FOUR_HOURS.
void num_init (num_state * state, tw_lp * lp)
Definition at line 13 of file num.c.
References num_state::file_size, MIN_FILE_SIZE, num_state::stats, tw_calloc(), and TW_LOC.
void num_rc_event_handler (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 186 of file num.c.
References tw_error(), and TW_LOC.
void num_start (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 73 of file num.c.
References DEBUG_LP, num_state::file_size, g_num_level, g_num_mod, g_num_net_pop, tw_lp::id, MIN_FILE_SIZE, NINE_OCLOCK, num_file_start(), NUM_LEVEL_0, num_report_levels(), ONE_MINUTE, QUIT_TIME, rn_timer_init(), num_statistics::s_nstart, num_state::stats, rn_message::ttl, tw_error(), tw_event_data(), TW_LOC, tw_now(), tw_rand_unif, TWENTY_FOUR_HOURS, and num_state::type.
void num_update (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 28 of file num.c.
References num_profile::bitrate, g_num_level, g_num_log_f, g_num_mod, g_num_profiles, NUM_LEVEL_0, NUM_LEVEL_1, num_statistics::s_nfailures, num_statistics::s_total_kb, num_statistics::s_total_time, num_state::stats, and num_state::type.