ROSS: rnf/modules/application/epi/save/epi-setup.c File Reference
epi-setup.c File Reference
#include <epi.h>
#include <getopt.h>
Functions
void epi_usage (void)
void epi_setup_options (int argc, char **argv)
Function Documentation
void epi_setup_options (int argc, char ** argv)
Definition at line 30 of file epi-setup.c.
References g_epi_hospital_f, g_epi_ic_fn, g_epi_log_f, g_epi_mod, g_epi_nsick, g_epi_position_f, g_epi_position_fn, g_epi_psick, g_epi_stay_home, g_epi_work_while_sick_p, g_epi_worried_well_duration, g_epi_worried_well_rate, g_epi_worried_well_threshold, g_rn_logs_dir, g_rn_tools_dir, tw_calloc(), tw_error(), TW_LOC, and tw_printf().
Referenced by epi_main().
void epi_usage (void)
Definition at line 12 of file epi-setup.c.