ROSS: rnf/modules/application/num/save/num-main.c File Reference
num-main.c File Reference
#include <num.h>
Functions
void num_main (int argc, char **argv, char **env)
void num_md_final ()
Function Documentation
void num_main (int argc, char ** argv, char ** env)
Definition at line 8 of file num-main.c.
References g_num_stats, g_tw_ts_end, num_init_scenario(), num_setup_options(), tw_calloc(), and TW_LOC.
void num_md_final ()
Definition at line 27 of file num-main.c.
References g_num_log_f, g_num_max_users, g_num_stats, num_statistics::s_nfiles, num_statistics::s_nstart, and num_statistics::s_nstop.