ROSS: ross/socket-tcp.c File Reference
socket-tcp.c File Reference
#include <ross.h>
Functions
tw_net_node * tw_socket_create_onport (tw_node src, tw_node dst, tw_port port, int blocking)
void tw_socket_create_mesh ()
int socket_connect (tw_net_node *node, int fd)
int socket_accept (tw_net_node *node, int num_of_clients)
int tw_socket_send_event (tw_event *event, tw_peid dest_peid)
tw_event * tw_socket_read_event (tw_pe *me)
int tw_socket_close (tw_net_node *n)
int tw_server_socket_create (tw_socket *socket_addr, tw_port port)
int tw_client_socket_create (char *server, tw_socket *socket_addr, tw_port port)
int tw_socket_read (int fd, char *buffer, int bytes, int tries)
int tw_socket_send (int fd, char *buffer, int bytes, int tries)
Function Documentation
int socket_accept (tw_net_node * node, int num_of_clients)
Definition at line 141 of file socket-tcp.c.
References tw_net_node::clients, tw_net_node::id, tw_net_node::socket, tw_net_node::socket_fd, tw_net_node::socket_sz, tw_error(), and TW_LOC.
Referenced by tw_net_start(), tw_socket_create_mesh(), and tw_socket_create_onport().
int socket_connect (tw_net_node * node, int fd)
Definition at line 124 of file socket-tcp.c.
References tw_net_node::socket.
Referenced by tw_socket_create_mesh(), and tw_socket_create_onport().
int tw_client_socket_create (char * server, tw_socket * socket_addr, tw_port port)
Definition at line 537 of file socket-tcp.c.
References tw_error(), and TW_LOC.
Referenced by tw_net_start(), tw_socket_create_mesh(), and tw_socket_create_onport().
int tw_server_socket_create (tw_socket * socket_addr, tw_port port)
Definition at line 509 of file socket-tcp.c.
References MAX_NODES, tw_error(), and TW_LOC.
Referenced by init_socket(), and tw_net_start().
int tw_socket_close (tw_net_node * n)
Definition at line 496 of file socket-tcp.c.
References tw_net_node::clients, nnodes, and tw_net_node::socket_fd.
Referenced by tw_net_stop().
void tw_socket_create_mesh ()
Definition at line 61 of file socket-tcp.c.
References tw_net_node::clients, g_tw_mynode, g_tw_net_node, g_tw_npe, tw_net_node::hostname, tw_net_node::id, nnet_nodes, tw_net_node::port, tw_net_node::servers, tw_net_node::socket, socket_accept(), socket_connect(), and tw_client_socket_create().
Referenced by tw_net_start().
tw_net_node* tw_socket_create_onport (tw_node src, tw_node dst, tw_port port, int blocking)
Definition at line 4 of file socket-tcp.c.
References tw_net_node::clients, g_tw_mynode, g_tw_net_node, tw_net_node::hostname, nnodes, tw_net_node::socket, socket_accept(), socket_connect(), tw_net_node::socket_fd, tw_net_node::socket_sz, tw_calloc(), tw_client_socket_create(), tw_error(), and TW_LOC.
Referenced by tw_net_start().
int tw_socket_read (int fd, char * buffer, int bytes, int tries)
Definition at line 559 of file socket-tcp.c.
References tw_error(), and TW_LOC.
Referenced by recv_stats(), tw_net_barrier(), tw_net_gvt_compute(), and tw_socket_read_event().
tw_event* tw_socket_read_event (tw_pe * me)
Definition at line 294 of file socket-tcp.c.
References tw_pe::abort_event, tw_event::cancel_next, tw_event::cancel_q, tw_pe::cancel_q, tw_event::cause_next, tw_event::caused_by_me, tw_net_node::clients, tw_event::dest_lp, tw_event::event_id, tw_pe::free_q, g_tw_msg_sz, g_tw_net_node, g_tw_npe, g_tw_ts_end, tw_pe::GVT, tw_pe::hash_t, tw_lp::id, tw_pe::id, tw_lptype::map, tw_event::next, nnet_nodes, tw_event::owner, tw_lp::pe, tw_event::prev, tw_event::recv_ts, tw_event::remote, tw_event::src_lp, tw_event::state, tw_error(), tw_event_free(), tw_event_grab(), tw_eventq_unshift(), tw_getlocal_lp(), tw_hash_insert(), tw_hash_remove(), TW_LOC, tw_memory_alloc(), TW_net_acancel, TW_pe_free_q, tw_socket_read(), and tw_lp::type.
Referenced by tw_net_read().
int tw_socket_send (int fd, char * buffer, int bytes, int tries)
Definition at line 599 of file socket-tcp.c.
References tw_error(), and TW_LOC.
Referenced by send_stats(), tw_net_barrier(), tw_net_gvt_compute(), tw_net_send_lvt(), and tw_socket_send_event().
int tw_socket_send_event (tw_event * event, tw_peid dest_peid)
Definition at line 162 of file socket-tcp.c.
References tw_event::cancel_q, tw_event::dest_lp, g_tw_msg_sz, g_tw_net_node, tw_lp::gid, tw_lp::id, tw_pe::id, tw_lp::kp, tw_lp::pe, tw_event::prev, tw_event::recv_ts, tw_net_node::servers, tw_event::src_lp, tw_event::state, tw_error(), TW_LOC, tw_memory_getsize(), tw_memory_unshift(), and tw_socket_send().
Referenced by tw_net_send().