ROSS: ross/models/srw/srw.c File Reference
srw.c File Reference
SRW module.
#include <ross.h>
#include "srw.h"
Macros
#define srw_main main
Functions
void srw_init (srw_state *s, tw_lp *lp)
void netdmf_srw_init (srw_state *s, tw_lp *lp)
void srw_event (srw_state *s, tw_bf *bf, srw_msg_data *m, tw_lp *lp)
void netdmf_srw_event (srw_state *s, tw_bf *bf, srw_msg_data *m, tw_lp *lp)
void srw_revent (srw_state *s, tw_bf *bf, srw_msg_data *m, tw_lp *lp)
void netdmf_srw_revent (srw_state *s, tw_bf *bf, srw_msg_data *m, tw_lp *lp)
void srw_final (srw_state *s, tw_lp *lp)
void netdmf_srw_final (srw_state *s, tw_lp *lp)
tw_peid srw_map (tw_lpid gid)
tw_peid netdmf_srw_map (tw_lpid gid)
int main (int argc, char *argv[])
Variables
int total_radios = 0
int total_movements = 0
int total_fail = 0
int total_comm = 0
static int top_node = 0
static int top_move = 0
tw_lptype srw_lps []
tw_lptype netdmf_srw_lps []
char netdmf_config [1024] = ""
const tw_optdef srw_opts []
Detailed Description
SRW module. Contains functions relevant / necessary for the functional requirements pertaining to the SRW waveform. NOTE: None of the netdmf_* event handlers below generate artificial data – we assume that the NetDMF file was read in and that no other data should be generated that was not in that file.
Definition in file srw.c.
Macro Definition Documentation
#define srw_main main
Definition at line 303 of file srw.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 305 of file srw.c.
References g_tw_nlp, g_tw_npe, g_tw_pe, netdmf_config, top_move, top_node, total_comm, total_fail, total_movements, total_radios, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_lp_settype(), tw_opt_add(), tw_pe_settype(), and tw_run().
void netdmf_srw_event (srw_state * s, tw_bf * bf, srw_msg_data * m, tw_lp * lp)
Forward event handler for SRW. Supported operations are currently:
GPS
MOVEMENT
COMMUNICATION
Definition at line 158 of file srw.c.
References srw_state::comm_try, COMMUNICATION, GPS, MOVEMENT, srw_state::movements, srw_msg_data::node_id, srw_state::nodes, and srw_msg_data::type.
void netdmf_srw_final (srw_state * s, tw_lp * lp)
Final function for SRW.
Definition at line 220 of file srw.c.
References srw_state::comm_fail, srw_state::comm_try, srw_state::movements, srw_state::nodes, srw_state::num_radios, top_move, top_node, total_comm, total_fail, total_movements, and total_radios.
void netdmf_srw_init (srw_state * s, tw_lp * lp)
Initializer function for SRW. Here we set all the necessary initial values we assume for the beginning of the simulation.
Definition at line 92 of file srw.c.
References srw_state::comm_fail, srw_state::comm_try, srw_state::movements, and srw_state::num_radios.
tw_peid netdmf_srw_map (tw_lpid gid)
Definition at line 244 of file srw.c.
References g_tw_nlp.
void netdmf_srw_revent (srw_state * s, tw_bf * bf, srw_msg_data * m, tw_lp * lp)
Reverse event handler for SRW.
Definition at line 187 of file srw.c.
void srw_event (srw_state * s, tw_bf * bf, srw_msg_data * m, tw_lp * lp)
Forward event handler for SRW. Supported operations are currently:
GPS
MOVEMENT
COMMUNICATION
Definition at line 107 of file srw.c.
References srw_state::comm_try, COMMUNICATION, tw_lp::gid, GPS, MOVEMENT, srw_state::movements, srw_msg_data::node_id, srw_state::nodes, tw_lp::rng, SRW_COMM_MEAN, SRW_GPS_RATE, SRW_MOVE_MEAN, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), and srw_msg_data::type.
void srw_final (srw_state * s, tw_lp * lp)
Final function for SRW.
Definition at line 198 of file srw.c.
References srw_state::comm_fail, srw_state::comm_try, srw_state::movements, srw_state::nodes, srw_state::num_radios, top_move, top_node, total_comm, total_fail, total_movements, and total_radios.
void srw_init (srw_state * s, tw_lp * lp)
Initializer function for SRW. Here we set all the necessary initial values we assume for the beginning of the simulation. We also bootstrap the event queue with some random data.
Definition at line 26 of file srw.c.
References srw_state::comm_fail, srw_state::comm_try, COMMUNICATION, tw_lp::gid, GPS, MOVEMENT, srw_state::movements, srw_msg_data::node_id, srw_state::nodes, srw_state::num_radios, tw_lp::rng, SRW_COMM_MEAN, SRW_GPS_RATE, SRW_MAX_GROUP_SIZE, SRW_MOVE_MEAN, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, and srw_msg_data::type.
tw_peid srw_map (tw_lpid gid)
Definition at line 239 of file srw.c.
References g_tw_nlp.
void srw_revent (srw_state * s, tw_bf * bf, srw_msg_data * m, tw_lp * lp)
Reverse event handler for SRW.
Definition at line 179 of file srw.c.
Variable Documentation
char netdmf_config[1024] = ""
Filename of [optional] NetDMF configuration
Definition at line 274 of file srw.c.
tw_lptype netdmf_srw_lps[]
Initial value:
= {
  {
    (init_f)   netdmf_srw_init,
    (event_f)  netdmf_srw_event,
    (revent_f) netdmf_srw_revent,
    (final_f)  netdmf_srw_final,
    (map_f)    netdmf_srw_map,
    sizeof    (srw_state)
  },
  {0},
}
Definition at line 261 of file srw.c.
tw_lptype srw_lps[]
Initial value:
= {
  {
    (init_f)   srw_init,
    (event_f)  srw_event,
    (revent_f) srw_revent,
    (final_f)  srw_final,
    (map_f)    srw_map,
    sizeof    (srw_state)
  },
  {0},
}
Definition at line 249 of file srw.c.
const tw_optdef srw_opts[]
Initial value:
= {
  TWOPT_GROUP("SRW Model"),
}
Various additional options for SRW
Definition at line 277 of file srw.c.
int top_move = 0 static
Definition at line 193 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().
int top_node = 0 static
Definition at line 192 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().
int total_comm = 0
Definition at line 18 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().
int total_fail = 0
Definition at line 17 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().
int total_movements = 0
Definition at line 16 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().
int total_radios = 0
Definition at line 15 of file srw.c.
Referenced by main(), netdmf_srw_final(), and srw_final().