ROSS: core/instrumentation/st-data-collection.c File Reference
st-data-collection.c File Reference
#include <ross.h>
#include <sys/stat.h>
#include <inttypes.h>
Macros
#define __STDC_FORMAT_MACROS 1
Functions
const tw_optdef * tw_stats_setup (void)
void st_stats_init ()
void st_gvt_log (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_gvt_log_pes (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_gvt_log_lps (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_collect_data (tw_pe *pe, tw_stime current_rt)
void st_collect_time_ahead_GVT (tw_pe *pe, char *data)
void st_collect_cycle_counters (tw_pe *pe, char *data)
void st_collect_event_counters_pes (tw_pe *pe, char *data)
void st_collect_event_counters_lps (tw_pe *pe, char *data)
Variables
char g_st_stats_out [MAX_LENGTH] = {0}
int g_st_stats_enabled = 0
long g_st_current_interval = 0
tw_clock g_st_real_time_samp = 0
tw_clock g_st_real_samp_start_cycles = 0
static tw_statistics last_stats = {0}
static tw_stat last_all_reduce_cnt = 0
int g_st_disable_out = 0
st_cycle_counters last_cycle_counters = {0}
st_event_counters last_event_counters = {0}
int g_st_granularity = 0
tw_clock g_st_stat_write_ctr = 0
tw_clock g_st_stat_comp_ctr = 0
static int num_gvt_vals = 10
static int num_gvt_vals_pe = 4
static int num_gvt_vals_kp = 2
static int num_gvt_vals_lp = 4
static int num_cycle_ctrs = 11
static int num_ev_ctrs = 12
static int num_ev_ctrs_pe = 5
static int num_ev_ctrs_kp = 2
static int num_ev_ctrs_lp = 4
static const tw_optdef stats_options []
Macro Definition Documentation
#define __STDC_FORMAT_MACROS 1
Definition at line 3 of file st-data-collection.c.
Function Documentation
void st_collect_cycle_counters (tw_pe * pe, char * data)
Definition at line 378 of file st-data-collection.c.
References g_tw_clock_rate, st_cycle_counters::s_avl, tw_statistics::s_avl, st_cycle_counters::s_buddy, tw_statistics::s_buddy, st_cycle_counters::s_cancel_q, tw_statistics::s_cancel_q, st_cycle_counters::s_event_abort, tw_statistics::s_event_abort, st_cycle_counters::s_event_process, tw_statistics::s_event_process, st_cycle_counters::s_fossil_collect, tw_statistics::s_fossil_collect, st_cycle_counters::s_gvt, tw_statistics::s_gvt, st_cycle_counters::s_lz4, tw_statistics::s_lz4, st_cycle_counters::s_net_read, tw_statistics::s_net_read, st_cycle_counters::s_pq, tw_statistics::s_pq, st_cycle_counters::s_rollback, tw_statistics::s_rollback, and tw_pe::stats.
Referenced by st_collect_data().
void st_collect_data (tw_pe * pe, tw_stime current_rt)
Definition at line 310 of file st-data-collection.c.
References g_st_buffer_rt, g_st_granularity, g_st_stat_comp_ctr, g_tw_nkp, g_tw_nlp, tw_pe::GVT, tw_pe::id, num_cycle_ctrs, num_ev_ctrs_kp, num_ev_ctrs_lp, num_ev_ctrs_pe, st_buffer_push(), st_collect_cycle_counters(), st_collect_event_counters_lps(), st_collect_event_counters_pes(), st_collect_time_ahead_GVT(), and tw_clock_read().
Referenced by tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_optimistic_realtime().
void st_collect_event_counters_lps (tw_pe * pe, char * data)
Definition at line 514 of file st-data-collection.c.
References tw_lp::event_counters, g_tw_fossil_attempts, g_tw_gvt_done, g_tw_nkp, g_tw_nlp, tw_kp::last_s_rb_secondary_rt, tw_kp::last_s_rb_total_rt, tw_pe::pq, tw_lp::prev_event_counters_rt, st_lp_counters::s_e_rbs, st_event_counters::s_fc_attempts, st_event_counters::s_nevent_abort, tw_statistics::s_nevent_abort, st_lp_counters::s_nevent_processed, st_event_counters::s_ngvts, st_lp_counters::s_nread_network, st_lp_counters::s_nsend_net_remote, st_lp_counters::s_nsend_network, st_event_counters::s_pe_event_ties, tw_statistics::s_pe_event_ties, st_event_counters::s_pq_qsize, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_pe::stats, tw_getkp(), tw_getlp(), and tw_pq_get_size().
Referenced by st_collect_data().
void st_collect_event_counters_pes (tw_pe * pe, char * data)
Definition at line 439 of file st-data-collection.c.
References g_tw_fossil_attempts, g_tw_gvt_done, g_tw_nkp, tw_pe::pq, st_event_counters::s_e_rbs, tw_kp::s_e_rbs, st_event_counters::s_fc_attempts, st_event_counters::s_nevent_abort, tw_statistics::s_nevent_abort, st_event_counters::s_nevent_processed, tw_kp::s_nevent_processed, st_event_counters::s_ngvts, st_event_counters::s_nread_network, tw_statistics::s_nread_network, st_event_counters::s_nsend_net_remote, tw_statistics::s_nsend_net_remote, st_event_counters::s_nsend_network, tw_statistics::s_nsend_network, st_event_counters::s_pe_event_ties, tw_statistics::s_pe_event_ties, st_event_counters::s_pq_qsize, st_event_counters::s_rb_secondary, tw_kp::s_rb_secondary, st_event_counters::s_rb_total, tw_kp::s_rb_total, tw_pe::stats, tw_getkp(), and tw_pq_get_size().
Referenced by st_collect_data().
void st_collect_time_ahead_GVT (tw_pe * pe, char * data)
Definition at line 359 of file st-data-collection.c.
References g_tw_nkp, g_tw_ts_end, tw_pe::GVT, tw_kp::last_time, and tw_getkp().
Referenced by st_collect_data().
void st_gvt_log (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 122 of file st-data-collection.c.
References g_st_granularity, st_gvt_log_lps(), and st_gvt_log_pes().
Referenced by tw_gvt_step2().
void st_gvt_log_lps (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 209 of file st-data-collection.c.
References all_reduce_cnt, tw_lp::event_counters, g_st_buffer_gvt, g_tw_mynode, g_tw_nkp, g_tw_nlp, last_all_reduce_cnt, tw_kp::last_s_rb_secondary_gvt, tw_kp::last_s_rb_total_gvt, num_gvt_vals_kp, num_gvt_vals_lp, num_gvt_vals_pe, tw_lp::prev_event_counters_gvt, st_lp_counters::s_e_rbs, tw_statistics::s_e_rbs, tw_statistics::s_fc_attempts, tw_statistics::s_net_events, tw_statistics::s_nevent_abort, st_lp_counters::s_nevent_processed, st_lp_counters::s_nread_network, st_lp_counters::s_nsend_net_remote, st_lp_counters::s_nsend_network, tw_statistics::s_pe_event_ties, tw_kp::s_rb_secondary, tw_kp::s_rb_total, st_buffer_push(), tw_error(), tw_getkp(), tw_getlp(), and TW_LOC.
Referenced by st_gvt_log().
void st_gvt_log_pes (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 131 of file st-data-collection.c.
References all_reduce_cnt, g_st_buffer_gvt, g_tw_mynode, last_all_reduce_cnt, num_gvt_vals, tw_statistics::s_e_rbs, tw_statistics::s_fc_attempts, tw_statistics::s_net_events, tw_statistics::s_nevent_abort, tw_statistics::s_nevent_processed, tw_statistics::s_nread_network, tw_statistics::s_nsend_net_remote, tw_statistics::s_nsend_network, tw_statistics::s_pe_event_ties, tw_statistics::s_rb_secondary, tw_statistics::s_rb_total, st_buffer_push(), tw_error(), and TW_LOC.
Referenced by st_gvt_log().
void st_stats_init ()
Definition at line 48 of file st-data-collection.c.
References g_st_directory, g_st_disable_out, g_st_granularity, g_st_real_time_samp, g_st_stats_enabled, g_st_stats_out, g_tw_mynode, g_tw_nkp, g_tw_nlp, MAX_LENGTH, nlp_per_pe, num_cycle_ctrs, num_ev_ctrs, num_ev_ctrs_kp, num_ev_ctrs_lp, num_ev_ctrs_pe, num_gvt_vals, num_gvt_vals_kp, num_gvt_vals_lp, num_gvt_vals_pe, ROSS_VERSION, tw_nnodes(), and tw_opt_settings().
Referenced by tw_run().
const tw_optdef* tw_stats_setup (void)
Definition at line 43 of file st-data-collection.c.
References stats_options.
Referenced by tw_init().
Variable Documentation
long g_st_current_interval = 0
Definition at line 8 of file st-data-collection.c.
int g_st_disable_out = 0
Definition at line 13 of file st-data-collection.c.
Referenced by st_buffer_finalize(), st_buffer_init(), st_buffer_push(), st_stats_init(), and tw_gvt_step2().
int g_st_granularity = 0
Definition at line 16 of file st-data-collection.c.
Referenced by st_collect_data(), st_gvt_log(), and st_stats_init().
tw_clock g_st_real_samp_start_cycles = 0
Definition at line 10 of file st-data-collection.c.
Referenced by tw_pe_init(), tw_sched_batch(), tw_sched_batch_realtime(), and tw_scheduler_conservative().
tw_clock g_st_real_time_samp = 0
Definition at line 9 of file st-data-collection.c.
Referenced by st_stats_init(), tw_gvt_step2(), tw_pe_init(), tw_run(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_optimistic_realtime().
tw_clock g_st_stat_comp_ctr = 0
Definition at line 18 of file st-data-collection.c.
Referenced by st_collect_data(), st_collect_event_data(), tw_gvt_step2(), and tw_net_statistics().
tw_clock g_st_stat_write_ctr = 0
Definition at line 17 of file st-data-collection.c.
Referenced by st_buffer_write(), and tw_net_statistics().
int g_st_stats_enabled = 0
Definition at line 7 of file st-data-collection.c.
Referenced by st_stats_init(), tw_gvt_step2(), tw_pe_init(), tw_run(), tw_scheduler_conservative(), tw_scheduler_optimistic(), and tw_scheduler_optimistic_realtime().
char g_st_stats_out[MAX_LENGTH] = {0}
Definition at line 6 of file st-data-collection.c.
Referenced by st_buffer_init(), and st_stats_init().
tw_stat last_all_reduce_cnt = 0 static
Definition at line 12 of file st-data-collection.c.
Referenced by st_gvt_log_lps(), and st_gvt_log_pes().
st_cycle_counters last_cycle_counters = {0}
Definition at line 14 of file st-data-collection.c.
st_event_counters last_event_counters = {0}
Definition at line 15 of file st-data-collection.c.
tw_statistics last_stats = {0} static
Definition at line 11 of file st-data-collection.c.
int num_cycle_ctrs = 11 static
Definition at line 24 of file st-data-collection.c.
Referenced by st_collect_data(), and st_stats_init().
int num_ev_ctrs = 12 static
Definition at line 25 of file st-data-collection.c.
Referenced by st_stats_init().
int num_ev_ctrs_kp = 2 static
Definition at line 27 of file st-data-collection.c.
Referenced by st_collect_data(), and st_stats_init().
int num_ev_ctrs_lp = 4 static
Definition at line 28 of file st-data-collection.c.
Referenced by st_collect_data(), and st_stats_init().
int num_ev_ctrs_pe = 5 static
Definition at line 26 of file st-data-collection.c.
Referenced by st_collect_data(), and st_stats_init().
int num_gvt_vals = 10 static
Definition at line 20 of file st-data-collection.c.
Referenced by st_gvt_log_pes(), and st_stats_init().
int num_gvt_vals_kp = 2 static
Definition at line 22 of file st-data-collection.c.
Referenced by st_gvt_log_lps(), and st_stats_init().
int num_gvt_vals_lp = 4 static
Definition at line 23 of file st-data-collection.c.
Referenced by st_gvt_log_lps(), and st_stats_init().
int num_gvt_vals_pe = 4 static
Definition at line 21 of file st-data-collection.c.
Referenced by st_gvt_log_lps(), and st_stats_init().
const tw_optdef stats_options[] static
Initial value:
= {
    TWOPT_GROUP("ROSS Stats"),
    TWOPT_UINT("enable-gvt-stats", g_st_stats_enabled, "Collect data after each GVT; 0 no stats, 1 for stats"),
    TWOPT_ULONGLONG("real-time-samp", g_st_real_time_samp, "real time sampling interval in ms"),
    TWOPT_UINT("granularity", g_st_granularity, "collect on PE basis only, or also KP/LP basis, 0 for PE, 1 for KP/LP"),
    TWOPT_UINT("event-trace", g_st_ev_trace, "collect detailed data on all events for specified LPs; 0, no trace, 1 full trace, 2 only events causing rollbacks"),
    TWOPT_CHAR("stats-filename", g_st_stats_out, "prefix for filename(s) for stats output"),
    TWOPT_UINT("buffer-size", g_st_buffer_size, "size of buffer in bytes for stats collection"),
    TWOPT_UINT("buffer-free", g_st_buffer_free_percent, "percentage of free space left in buffer before writing out at GVT"),
    TWOPT_UINT("disable-output", g_st_disable_out, "used for perturbation analysis; buffer never dumped to file when 1"),
}
Definition at line 30 of file st-data-collection.c.
Referenced by tw_stats_setup().