ROSS: core/instrumentation/st-event-collection.h File Reference
st-event-collection.h File Reference
#include <ross.h>
Data Structures
struct st_trace_type
Typedefs
typedef void(* rbev_trace_f)(void *msg, tw_lp *lp, char *buffer, int *collect_flag)
typedef void(* ev_trace_f)(void *msg, tw_lp *lp, char *buffer, int *collect_flag)
typedef struct st_trace_type st_trace_type
Functions
void st_evtrace_setup_types (tw_lp *lp)
void st_evtrace_settype (tw_lpid i, st_trace_type *event_types)
void st_collect_event_data (tw_event *cev, tw_stime recv_rt, tw_stime duration)
Variables
int g_st_ev_trace
st_trace_type * g_st_trace_types
int g_st_buf_size
Typedef Documentation
typedef void(* ev_trace_f)(void *msg, tw_lp *lp, char *buffer, int *collect_flag)
Definition at line 5 of file st-event-collection.h.
typedef void(* rbev_trace_f)(void *msg, tw_lp *lp, char *buffer, int *collect_flag)
Definition at line 4 of file st-event-collection.h.
typedef struct st_trace_type st_trace_type
Definition at line 6 of file st-event-collection.h.
Function Documentation
void st_collect_event_data (tw_event * cev, tw_stime recv_rt, tw_stime duration)
Definition at line 40 of file st-event-collection.c.
References tw_event::dest_lp, st_trace_type::ev_sz, st_trace_type::ev_trace, evtype_warned, FULL_TRACE, g_st_buf_size, g_st_buffer_evrb, g_st_disable_out, g_st_ev_trace, g_st_stat_comp_ctr, g_tw_masternode, g_tw_mynode, g_tw_synchronization_protocol, tw_lp::gid, RB_TRACE, st_trace_type::rbev_sz, st_trace_type::rbev_trace, tw_event::recv_ts, tw_event::send_lp, tw_event::send_ts, seq_ev_trace, SEQUENTIAL, st_buffer_push(), tw_lp::trace_types, tw_clock_read(), and tw_event_data().
Referenced by tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), and tw_scheduler_sequential().
void st_evtrace_settype (tw_lpid i, st_trace_type * event_types)
Definition at line 23 of file st-event-collection.c.
References evtype_warned, g_tw_lp, g_tw_masternode, g_tw_mynode, trace_types, and tw_lp::trace_types.
Referenced by main().
void st_evtrace_setup_types (tw_lp * lp)
Definition at line 12 of file st-event-collection.c.
References g_tw_lp_typemap, tw_lp::gid, tw_lp::trace_types, tw_error(), and TW_LOC.
Referenced by tw_lp_setup_types().
Variable Documentation
int g_st_buf_size
Definition at line 6 of file st-event-collection.c.
Referenced by st_buffer_init(), and st_collect_event_data().
int g_st_ev_trace
Definition at line 3 of file st-event-collection.c.
Referenced by st_buffer_init(), st_collect_event_data(), tw_gvt_step2(), tw_lp_setup_types(), tw_pe_init(), tw_run(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_realtime(), and tw_scheduler_sequential().
st_trace_type* g_st_trace_types
Definition at line 4 of file st-event-collection.c.