ROSS: core/instrumentation/st-event-trace.c File Reference
st-event-trace.c File Reference
#include <ross.h>
Functions
void st_collect_event_data (tw_event *cev, double recv_rt)
Variables
int g_st_ev_trace = 0
static short evtype_warned = 0
Function Documentation
st_collect_event_data()
void st_collect_event_data (tw_event * cev, double recv_rt)
Definition at line 9 of file st-event-trace.c.
References st_event_data::dest_lp, tw_event::dest_lp, st_model_types::ev_sz, EV_TRACE, st_model_types::ev_trace, evtype_warned, g_st_disable_out, g_tw_masternode, g_tw_mynode, g_tw_pe, g_tw_synchronization_protocol, tw_lp::gid, st_event_data::model_data_sz, tw_lp::model_types, st_event_data::real_ts, tw_event::recv_ts, st_event_data::recv_vts, tw_event::send_lp, tw_event::send_ts, st_event_data::send_vts, seq_ev_trace, SEQUENTIAL, st_event_data::src_lp, st_buffer_push(), tw_clock_read(), tw_event_data(), and TW_STIME_DBL.
Referenced by tw_eventq_push_list(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
Variable Documentation
evtype_warned
short evtype_warned = 0 static
Definition at line 5 of file st-event-trace.c.
Referenced by st_collect_event_data().
g_st_ev_trace
int g_st_ev_trace = 0
Definition at line 3 of file st-event-trace.c.
Referenced by st_buffer_allocate(), st_inst_dump(), st_inst_finalize(), st_inst_init(), tw_eventq_push_list(), tw_lp_setup_types(), tw_sched_batch(), tw_sched_batch_realtime(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().