ROSS: core/instrumentation/st-model-data.c File Reference
st-model-data.c File Reference
#include <ross.h>
Functions
void st_model_setup_types (tw_lp *lp)
void st_model_settype (tw_lpid i, st_model_types *model_types)
void st_collect_model_data (tw_pe *pe, double current_rt, int stats_type)
Variables
st_model_types * g_st_model_types = NULL
static int model_type_warned = 0
Function Documentation
st_collect_model_data()
void st_collect_model_data (tw_pe * pe, double current_rt, int stats_type)
Definition at line 45 of file st-model-data.c.
References tw_lp::cur_state, sample_metadata::flag, g_st_disable_out, g_tw_lp, g_tw_mynode, g_tw_nlp, g_tw_synchronization_protocol, tw_lp::gid, model_metadata::gvt, tw_kp::id, tw_lp::kp, model_metadata::kpid, model_metadata::lpid, MODEL_COL, st_model_types::model_stat_fn, model_metadata::model_sz, MODEL_TYPE, tw_lp::model_types, st_model_types::mstat_sz, pe, model_metadata::peid, sample_metadata::real_time, sample_metadata::sample_sz, seq_model, SEQUENTIAL, st_buffer_push(), model_metadata::stats_type, sample_metadata::ts, tw_clock_read(), tw_now(), and TW_STIME_DBL.
Referenced by tw_gvt_step2(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
st_model_settype()
void st_model_settype (tw_lpid i, st_model_types * model_types)
Definition at line 25 of file st-model-data.c.
References g_tw_lp, g_tw_masternode, g_tw_mynode, model_type_warned, model_types, and tw_lp::model_types.
Referenced by main().
st_model_setup_types()
void st_model_setup_types (tw_lp * lp)
Definition at line 10 of file st-model-data.c.
References g_st_model_types, g_tw_lp_typemap, g_tw_masternode, g_tw_mynode, tw_lp::gid, model_type_warned, and tw_lp::model_types.
Referenced by tw_lp_setup_types().
Variable Documentation
g_st_model_types
st_model_types* g_st_model_types = NULL
Definition at line 3 of file st-model-data.c.
Referenced by st_model_setup_types().
model_type_warned
int model_type_warned = 0 static
Definition at line 4 of file st-model-data.c.
Referenced by st_model_settype(), and st_model_setup_types().