ROSS: core/instrumentation/st-stats-buffer.c File Reference
st-stats-buffer.c File Reference
#include <ross.h>
#include <time.h>
#include <sys/stat.h>
Functions
void st_buffer_allocate ()
void st_buffer_init (int type)
void st_buffer_push (int type, char *data, int size)
void st_buffer_write (int end_of_sim, int type)
void st_buffer_finalize (int type)
Variables
static long missed_bytes = 0
static MPI_Offset * prev_offsets = NULL
static MPI_File * buffer_fh = NULL
char stats_directory [INST_MAX_LENGTH]
int g_st_buffer_size = 8000000
int g_st_buffer_free_percent = 15
static int buffer_overflow_warned = 0
static const char * file_suffix [NUM_COL_TYPES]
FILE * seq_ev_trace
FILE * seq_model
FILE * seq_analysis
static st_stats_buffer ** g_st_buffer
Function Documentation
void st_buffer_allocate ()
Definition at line 16 of file st-stats-buffer.c.
References buffer_fh, g_st_engine_stats, g_st_ev_trace, g_st_model_stats, g_st_stats_path, g_st_use_analysis_lps, g_tw_masternode, g_tw_mynode, INST_MAX_LENGTH, MPI_COMM_ROSS, NUM_COL_TYPES, prev_offsets, stats_directory, tw_calloc(), and TW_LOC.
Referenced by tw_define_lps().
void st_buffer_finalize (int type)
Definition at line 189 of file st-stats-buffer.c.
References buffer_fh, g_st_disable_out, g_tw_mynode, missed_bytes, and st_buffer_write().
Referenced by st_inst_finalize().
void st_buffer_init (int type)
Definition at line 62 of file st-stats-buffer.c.
References ANALYSIS_LP, st_stats_buffer::buffer, buffer_fh, st_stats_buffer::count, file_suffix, g_st_buffer_size, g_st_disable_out, g_st_stats_out, g_tw_synchronization_protocol, INST_MAX_LENGTH, MPI_COMM_ROSS, st_stats_buffer::read_pos, seq_analysis, seq_ev_trace, seq_model, SEQUENTIAL, st_stats_buffer::size, stats_directory, tw_calloc(), TW_LOC, and st_stats_buffer::write_pos.
Referenced by specialized_lp_setup(), and st_inst_init().
void st_buffer_push (int type, char * data, int size)
Definition at line 101 of file st-stats-buffer.c.
References buffer_overflow_warned, st_stats_buffer::count, g_st_disable_out, g_tw_lp, g_tw_mynode, missed_bytes, st_buffer_free_space, st_buffer_write_ptr, tw_now(), and st_stats_buffer::write_pos.
Referenced by analysis_commit(), st_collect_engine_data_kps(), st_collect_engine_data_lps(), st_collect_engine_data_pes(), st_collect_event_data(), and st_collect_model_data().
void st_buffer_write (int end_of_sim, int type)
Definition at line 138 of file st-stats-buffer.c.
References buffer_fh, buffer_overflow_warned, st_stats_buffer::count, g_st_buffer_free_percent, g_st_buffer_size, g_tw_mynode, g_tw_pe, MPI_COMM_ROSS, prev_offsets, st_stats_buffer::read_pos, tw_statistics::s_stat_comp, tw_statistics::s_stat_write, st_buffer_read_ptr, tw_pe::stats, tw_clock_read(), tw_nnodes(), and st_stats_buffer::write_pos.
Referenced by st_buffer_finalize(), and st_inst_dump().
Variable Documentation
MPI_File* buffer_fh = NULL static
Definition at line 7 of file st-stats-buffer.c.
Referenced by st_buffer_allocate(), st_buffer_finalize(), st_buffer_init(), and st_buffer_write().
int buffer_overflow_warned = 0 static
Definition at line 11 of file st-stats-buffer.c.
Referenced by st_buffer_push(), and st_buffer_write().
const char* file_suffix[NUM_COL_TYPES] static
Definition at line 12 of file st-stats-buffer.c.
Referenced by st_buffer_init().
st_stats_buffer** g_st_buffer static
Definition at line 14 of file st-stats-buffer.c.
int g_st_buffer_free_percent = 15
Definition at line 10 of file st-stats-buffer.c.
Referenced by st_buffer_write().
int g_st_buffer_size = 8000000
Definition at line 9 of file st-stats-buffer.c.
Referenced by st_buffer_init(), and st_buffer_write().
long missed_bytes = 0 static
Definition at line 5 of file st-stats-buffer.c.
Referenced by st_buffer_finalize(), and st_buffer_push().
MPI_Offset* prev_offsets = NULL static
Definition at line 6 of file st-stats-buffer.c.
Referenced by st_buffer_allocate(), and st_buffer_write().
FILE * seq_analysis
Definition at line 13 of file st-stats-buffer.c.
Referenced by analysis_commit(), and st_buffer_init().
FILE* seq_ev_trace
Definition at line 13 of file st-stats-buffer.c.
Referenced by st_buffer_init(), and st_collect_event_data().
FILE * seq_model
Definition at line 13 of file st-stats-buffer.c.
Referenced by st_buffer_init(), and st_collect_model_data().
char stats_directory[INST_MAX_LENGTH]
Definition at line 8 of file st-stats-buffer.c.
Referenced by st_buffer_allocate(), and st_buffer_init().