ROSS: core/instrumentation/st-sim-engine.c File Reference
st-sim-engine.c File Reference
#include <ross.h>
#include <sys/stat.h>
Macros
#define __STDC_FORMAT_MACROS 1
Functions
void print_sim_engine_metadata (FILE *file)
void st_gvt_log (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_gvt_log_pes (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_gvt_log_lps (tw_pe *me, tw_stime gvt, tw_statistics *s, tw_stat all_reduce_cnt)
void st_collect_data (tw_pe *pe, tw_stime current_rt)
void st_collect_time_ahead_GVT (tw_pe *pe, char *data)
void st_collect_cycle_counters (tw_pe *pe, char *data)
void st_collect_event_counters_pes (tw_pe *pe, char *data)
void st_collect_event_counters_lps (tw_pe *pe, char *data)
Variables
long g_st_current_interval = 0
tw_clock g_st_rt_samp_start_cycles = 0
static tw_statistics last_stats = {0}
static tw_stat last_all_reduce_cnt = 0
int g_st_disable_out = 0
st_cycle_counters last_cycle_counters = {0}
st_event_counters last_event_counters = {0}
int g_st_granularity = 0
tw_clock g_st_stat_write_ctr = 0
tw_clock g_st_stat_comp_ctr = 0
static int num_gvt_vals = 10
static int num_gvt_vals_pe = 4
static int num_gvt_vals_kp = 2
static int num_gvt_vals_lp = 4
static int num_cycle_ctrs = 11
static int num_ev_ctrs = 12
static int num_ev_ctrs_pe = 5
static int num_ev_ctrs_kp = 2
static int num_ev_ctrs_lp = 4
Macro Definition Documentation
#define __STDC_FORMAT_MACROS 1
Definition at line 3 of file st-sim-engine.c.
Function Documentation
void print_sim_engine_metadata (FILE * file)
Definition at line 26 of file st-sim-engine.c.
References g_st_engine_stats, g_st_granularity, g_st_gvt_sampling, g_st_rt_sampling, num_cycle_ctrs, num_ev_ctrs, num_ev_ctrs_kp, num_ev_ctrs_lp, num_ev_ctrs_pe, num_gvt_vals, num_gvt_vals_kp, num_gvt_vals_lp, and num_gvt_vals_pe.
Referenced by st_stats_init().
void st_collect_cycle_counters (tw_pe * pe, char * data)
Definition at line 325 of file st-sim-engine.c.
References g_tw_clock_rate, st_cycle_counters::s_avl, tw_statistics::s_avl, st_cycle_counters::s_buddy, tw_statistics::s_buddy, st_cycle_counters::s_cancel_q, tw_statistics::s_cancel_q, st_cycle_counters::s_event_abort, tw_statistics::s_event_abort, st_cycle_counters::s_event_process, tw_statistics::s_event_process, st_cycle_counters::s_fossil_collect, tw_statistics::s_fossil_collect, st_cycle_counters::s_gvt, tw_statistics::s_gvt, st_cycle_counters::s_lz4, tw_statistics::s_lz4, st_cycle_counters::s_net_read, tw_statistics::s_net_read, st_cycle_counters::s_pq, tw_statistics::s_pq, st_cycle_counters::s_rollback, tw_statistics::s_rollback, and tw_pe::stats.
Referenced by st_collect_data().
void st_collect_data (tw_pe * pe, tw_stime current_rt)
Definition at line 257 of file st-sim-engine.c.
References g_st_buffer, g_st_granularity, g_st_stat_comp_ctr, g_tw_nkp, g_tw_nlp, tw_pe::GVT, tw_pe::id, num_cycle_ctrs, num_ev_ctrs_kp, num_ev_ctrs_lp, num_ev_ctrs_pe, RT_COL, st_buffer_push(), st_collect_cycle_counters(), st_collect_event_counters_lps(), st_collect_event_counters_pes(), st_collect_time_ahead_GVT(), and tw_clock_read().
Referenced by st_inst_finalize(), tw_sched_batch(), tw_sched_batch_realtime(), and tw_scheduler_conservative().
void st_collect_event_counters_lps (tw_pe * pe, char * data)
Definition at line 461 of file st-sim-engine.c.
References tw_lp::event_counters, g_tw_fossil_attempts, g_tw_gvt_done, g_tw_nkp, g_tw_nlp, tw_kp::last_s_rb_secondary_rt, tw_kp::last_s_rb_total_rt, tw_pe::pq, tw_lp::prev_event_counters_rt, st_lp_counters::s_e_rbs, st_event_counters::s_fc_attempts, st_event_counters::s_nevent_abort, tw_statistics::s_nevent_abort, st_lp_counters::s_nevent_processed, st_event_counters::s_ngvts, st_lp_counters::s_nread_network, st_lp_counters::s_nsend_net_remote, st_lp_counters::s_nsend_network, st_event_counters::s_pe_event_ties, tw_statistics::s_pe_event_ties, st_event_counters::s_pq_qsize, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_pe::stats, tw_getkp(), tw_getlp(), and tw_pq_get_size().
Referenced by st_collect_data().
void st_collect_event_counters_pes (tw_pe * pe, char * data)
Definition at line 386 of file st-sim-engine.c.
References g_tw_fossil_attempts, g_tw_gvt_done, g_tw_nkp, tw_pe::pq, st_event_counters::s_e_rbs, tw_kp::s_e_rbs, st_event_counters::s_fc_attempts, st_event_counters::s_nevent_abort, tw_statistics::s_nevent_abort, st_event_counters::s_nevent_processed, tw_kp::s_nevent_processed, st_event_counters::s_ngvts, st_event_counters::s_nread_network, tw_statistics::s_nread_network, st_event_counters::s_nsend_net_remote, tw_statistics::s_nsend_net_remote, st_event_counters::s_nsend_network, tw_statistics::s_nsend_network, st_event_counters::s_pe_event_ties, tw_statistics::s_pe_event_ties, st_event_counters::s_pq_qsize, st_event_counters::s_rb_secondary, tw_kp::s_rb_secondary, st_event_counters::s_rb_total, tw_kp::s_rb_total, tw_pe::stats, tw_getkp(), and tw_pq_get_size().
Referenced by st_collect_data().
void st_collect_time_ahead_GVT (tw_pe * pe, char * data)
Definition at line 306 of file st-sim-engine.c.
References g_tw_nkp, g_tw_ts_end, tw_pe::GVT, tw_kp::last_time, and tw_getkp().
Referenced by st_collect_data().
void st_gvt_log (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 55 of file st-sim-engine.c.
References g_st_granularity, st_gvt_log_lps(), and st_gvt_log_pes().
Referenced by tw_gvt_step2().
void st_gvt_log_lps (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 147 of file st-sim-engine.c.
References all_reduce_cnt, tw_lp::event_counters, g_st_buffer, g_tw_clock_rate, g_tw_mynode, g_tw_nkp, g_tw_nlp, GVT_COL, last_all_reduce_cnt, tw_kp::last_s_rb_secondary_gvt, tw_kp::last_s_rb_total_gvt, num_gvt_vals_kp, num_gvt_vals_lp, num_gvt_vals_pe, tw_lp::prev_event_counters_gvt, st_lp_counters::s_e_rbs, tw_statistics::s_e_rbs, tw_statistics::s_fc_attempts, tw_statistics::s_net_events, tw_statistics::s_nevent_abort, st_lp_counters::s_nevent_processed, st_lp_counters::s_nread_network, st_lp_counters::s_nsend_net_remote, st_lp_counters::s_nsend_network, tw_statistics::s_pe_event_ties, tw_kp::s_rb_secondary, tw_kp::s_rb_total, st_buffer_push(), tw_clock_read(), tw_error(), tw_getkp(), tw_getlp(), and TW_LOC.
Referenced by st_gvt_log().
void st_gvt_log_pes (tw_pe * me, tw_stime gvt, tw_statistics * s, tw_stat all_reduce_cnt)
Definition at line 64 of file st-sim-engine.c.
References all_reduce_cnt, g_st_buffer, g_tw_clock_rate, g_tw_mynode, GVT_COL, last_all_reduce_cnt, num_gvt_vals, tw_statistics::s_e_rbs, tw_statistics::s_fc_attempts, tw_statistics::s_net_events, tw_statistics::s_nevent_abort, tw_statistics::s_nevent_processed, tw_statistics::s_nread_network, tw_statistics::s_nsend_net_remote, tw_statistics::s_nsend_network, tw_statistics::s_pe_event_ties, tw_statistics::s_rb_secondary, tw_statistics::s_rb_total, st_buffer_push(), tw_clock_read(), tw_error(), and TW_LOC.
Referenced by st_gvt_log().
Variable Documentation
long g_st_current_interval = 0
Definition at line 5 of file st-sim-engine.c.
int g_st_disable_out = 0
Definition at line 9 of file st-sim-engine.c.
Referenced by st_buffer_finalize(), st_buffer_init(), st_buffer_push(), st_collect_event_data(), st_collect_model_data(), st_inst_dump(), and st_stats_init().
int g_st_granularity = 0
Definition at line 12 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), st_collect_data(), st_gvt_log(), and st_stats_init().
tw_clock g_st_rt_samp_start_cycles = 0
Definition at line 6 of file st-sim-engine.c.
Referenced by st_inst_init(), tw_sched_batch(), tw_sched_batch_realtime(), tw_scheduler_conservative(), and tw_scheduler_sequential().
tw_clock g_st_stat_comp_ctr = 0
Definition at line 14 of file st-sim-engine.c.
Referenced by st_collect_data(), st_collect_event_data(), st_collect_model_data(), tw_gvt_step2(), and tw_net_statistics().
tw_clock g_st_stat_write_ctr = 0
Definition at line 13 of file st-sim-engine.c.
Referenced by st_buffer_write(), and tw_net_statistics().
tw_stat last_all_reduce_cnt = 0 static
Definition at line 8 of file st-sim-engine.c.
Referenced by st_gvt_log_lps(), and st_gvt_log_pes().
st_cycle_counters last_cycle_counters = {0}
Definition at line 10 of file st-sim-engine.c.
st_event_counters last_event_counters = {0}
Definition at line 11 of file st-sim-engine.c.
tw_statistics last_stats = {0} static
Definition at line 7 of file st-sim-engine.c.
int num_cycle_ctrs = 11 static
Definition at line 20 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_collect_data().
int num_ev_ctrs = 12 static
Definition at line 21 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata().
int num_ev_ctrs_kp = 2 static
Definition at line 23 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_collect_data().
int num_ev_ctrs_lp = 4 static
Definition at line 24 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_collect_data().
int num_ev_ctrs_pe = 5 static
Definition at line 22 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_collect_data().
int num_gvt_vals = 10 static
Definition at line 16 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_gvt_log_pes().
int num_gvt_vals_kp = 2 static
Definition at line 18 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_gvt_log_lps().
int num_gvt_vals_lp = 4 static
Definition at line 19 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_gvt_log_lps().
int num_gvt_vals_pe = 4 static
Definition at line 17 of file st-sim-engine.c.
Referenced by print_sim_engine_metadata(), and st_gvt_log_lps().