ROSS: TC Struct Reference
TC Struct Reference
#include <olsr.h>
Data Fields
uint16_t ansn
o_addr neighborAddresses [(16 *16)]
unsigned num_neighbors
Detailed Description
struct TC - Topology Control information.
The ns3 code is as follows:
struct Tc
{
    std::vector<Ipv4Address> neighborAddresses;
    uint16_t ansn;
    void Print (std::ostream &os) const;
    uint32_t GetSerializedSize (void) const;
    void Serialize (Buffer::Iterator start) const;
    uint32_t Deserialize (Buffer::Iterator start, uint32_t messageSize);
};
Definition at line 153 of file olsr.h.
Field Documentation
uint16_t TC::ansn
Definition at line 155 of file olsr.h.
Referenced by ForwardDefault(), and olsr_event().
o_addr TC::neighborAddresses[(16 *16)]
Definition at line 156 of file olsr.h.
Referenced by ForwardDefault(), olsr_event(), and printTC().
unsigned TC::num_neighbors
Definition at line 157 of file olsr.h.
Referenced by ForwardDefault(), olsr_event(), olsr_init(), and printTC().
The documentation for this struct was generated from the following file:
ross/models/olsr-j/olsr.h