ROSS: ross/models/tcp/tcp-router-rc.c File Reference
tcp-router-rc.c File Reference
#include "tcp.h"
Functions
void tcp_router_forward_rc (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_rc_EventHandler (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
Function Documentation
void tcp_router_forward_rc (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 13 of file tcp-router-rc.c.
References tw_bf::c1, tw_bf::c2, Msg_Data::dest, Router_State::dropped_packets, tw_lp::id, Router_State::lastsent, Msg_Data::RC, RC::rtt_time, tcp_util_nexthop_link(), and tw_rand_reverse_unif.
Referenced by tcp_router_rc_EventHandler().
void tcp_router_rc_EventHandler (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 62 of file tcp-router-rc.c.
References FORWARD, tw_lp::id, Msg_Data::MethodName, tcp_router_forward_rc(), tw_error(), tw_exit(), and TW_LOC.