ROSS: ross/models/tcp/tcp-main.c File Reference
tcp-main.c File Reference
#include "tcp.h"
Functions
int main (int argc, char **argv)
void tcp_finalize ()
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Tcp_Statistics stats
Function Documentation
int main (int argc, char ** argv)
Definition at line 39 of file tcp-main.c.
References g_phold_start_events, g_tw_events_per_pe, g_tw_gvt_interval, g_tw_lookahead, g_tw_mblock, g_tw_memory_nqueues, g_tw_mynode, g_tw_nkp, g_tw_nlp, g_tw_npe, g_tw_pe, g_tw_ts_end, lookahead, mean, mult, nlp_per_pe, offset_lpid, optimistic_memory, pe, tcp_finalize(), ttl_lps, tw_define_lps(), tw_end(), tw_error(), tw_init(), TW_LOC, tw_lp_settype(), tw_nnodes(), tw_opt_add(), tw_run(), and TWAppStats.
void tcp_finalize ()
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("TCP Model"),
        TWOPT_STIME("remote-link", percent_remote, "desired remote TCP connectionsevent rate"),
        TWOPT_UINT("network-bits", nlp_per_model, "number of 2^bits is number of LPs in whole system"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_STIME("lookahead", lookahead, "lookahead for links"),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 25 of file tcp-main.c.
tw_lptype mylps[]
Initial value:
=
{
        { 1 , sizeof(Host_State),
         (init_f) tcp_host_startup,
         (event_f) tcp_host_eventhandler,
         (revent_f) tcp_host_rc_eventhandler,
         (final_f) tcp_host_Statistics_CollectStats,
         (statecp_f) NULL},
        { 2 , sizeof(Router_State),
         (init_f) tcp_router_startup,
         (event_f) tcp_router_eventhandler,
         (revent_f) tcp_router_rc_eventhandler,
         (final_f) tcp_router_statistics_collectStats,
         (statecp_f) NULL},
        {0},
}
Definition at line 8 of file tcp-main.c.
Tcp_Statistics stats
Definition at line 97 of file tcp-main.c.
Referenced by ip_md_final(), mem_stats_print(), rn_print_statistics(), tcp_md_final(), tw_net_gvt_compute(), and tw_net_send_lvt().