ROSS: rnf/modules/transport/tcp/tcp-model.c File Reference
tcp-model.c File Reference
#include <tcp.h>
Functions
void tcp_md_opts ()
void tcp_md_init (int argc, char **argv, char **env)
void tcp_md_final ()
Variables
const tw_optdef tcp_opts []
Function Documentation
void tcp_md_final ()
Definition at line 35 of file tcp-model.c.
References tcp_statistics::ack_invalid, tcp_statistics::ack_recv, tcp_statistics::ack_sent, tcp_statistics::bad_msgs, tcp_statistics::dropped_packets, g_tcp_stats, g_tw_masternode, tcp_statistics::recv, tcp_statistics::sent, stats, tcp_statistics::throughput, tcp_statistics::tout, tw_error(), tw_ismaster(), and TW_LOC.
void tcp_md_init (int argc, char ** argv, char ** env)
Definition at line 16 of file tcp-model.c.
References g_tcp_f, g_tcp_fd, g_tcp_stats, g_tw_nkp, nbufs, tw_calloc(), tw_error(), tw_getkp(), tw_ismaster(), TW_LOC, and tw_memory_init().
void tcp_md_opts ()
Definition at line 10 of file tcp-model.c.
References tw_opt_add().
Variable Documentation
const tw_optdef tcp_opts[]
Initial value:
=
{
        TWOPT_GROUP("TCP Model"),
}
Definition at line 3 of file tcp-model.c.
Referenced by tw_net_init().