ROSS: rnf/modules/transport/tcp/tcp-rc-timer.c File Reference
tcp-rc-timer.c File Reference
#include <tcp.h>
Functions
tw_event * tcp_rc_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
Function Documentation
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 119 of file tcp-rc-timer.c.
References g_tcp_fd, tw_lp::gid, tcp_message::RC, tw_event::recv_ts, rn_timer_init(), RC::timer_ts, tw_error(), TW_LOC, tw_memory_free_rc(), and tw_now().
tw_event* tcp_rc_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 33 of file tcp-rc-timer.c.
References tw_bf::c13, tw_bf::c14, tw_bf::c17, g_tcp_fd, tw_lp::gid, tcp_message::RC, tw_event::recv_ts, rn_timer_cancel(), rn_timer_init(), rn_timer_reset(), tcp_message::seq_num, tcp_message::src, RC::timer, RC::timer_seq, RC::timer_ts, tw_error(), TW_LOC, tw_memory_alloc(), tw_memory_alloc_rc(), and tw_now().