ROSS: ross/models/tcp/tcp-router.c File Reference
tcp-router.c File Reference
#include "tcp.h"
Functions
void tcp_router_StartUp (Router_State *SV, tw_lp *lp)
void tcp_router_forward (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_EventHandler (Router_State *SV, tw_bf *CV, Msg_Data *M, tw_lp *lp)
void tcp_router_Statistics_CollectStats (Router_State *SV, tw_lp *lp)
Function Documentation
void tcp_router_EventHandler (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 116 of file tcp-router.c.
References FORWARD, tw_lp::id, Msg_Data::MethodName, tcp_router_forward(), tw_error(), tw_exit(), and TW_LOC.
void tcp_router_forward (Router_State * SV, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 25 of file tcp-router.c.
References Msg_Data::ack, Router_Link::buffer_sz, tw_bf::c1, tw_bf::c2, Router_Link::delay, Msg_Data::dest, Router_State::dropped_packets, FORWARD, g_hosts_info, g_routers, g_routers_links, tw_lp::id, Router_State::lastsent, Router_Link::link_speed, Msg_Data::RC, RC::rtt_time, Msg_Data::seq_num, Msg_Data::source, TCP_HEADER_SIZE, TCP_TRANSFER_SIZE, tcp_util_event(), tcp_util_nexthop(), tcp_util_nexthop_link(), tw_now(), and tw_rand_unif.
Referenced by tcp_router_EventHandler().
void tcp_router_StartUp (Router_State * SV, tw_lp * lp)
Definition at line 13 of file tcp-router.c.
References Router_State::dropped_packets, g_routers_info, tw_lp::id, and Router_State::lastsent.
void tcp_router_Statistics_CollectStats (Router_State * SV, tw_lp * lp)
Definition at line 141 of file tcp-router.c.
References Router_State::dropped_packets, and TWAppStats.