ROSS: ross/test/test_ross_pq_example_Runner.c File Reference
test_ross_pq_example_Runner.c File Reference
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
Macros
#define RUN_TEST(TestFunc, TestLineNum)
Functions
void setUp (void)
void tearDown (void)
void test_pizza (void)
void test_pq (void)
void resetTest ()
int main (void)
Macro Definition Documentation
#define RUN_TEST (TestFunc, TestLineNum)
Value:
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}
Definition at line 4 of file test_ross_pq_example_Runner.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 42 of file test_ross_pq_example_Runner.c.
References RUN_TEST, test_pizza(), test_pq(), _Unity::TestFile, Unity, UnityBegin(), and UnityEnd().
void resetTest ()
Definition at line 34 of file test_ross_pq_example_Runner.c.
References setUp(), and tearDown().
void setUp (void)
Definition at line 8 of file olsr-test.c.
void tearDown (void)
Definition at line 4 of file olsr-test.c.
void test_pizza (void)
Definition at line 12 of file test_ross_pq_example.c.
References TEST_ASSERT_EQUAL_STRING.
Referenced by main().
void test_pq (void)
Definition at line 17 of file test_ross_pq_example.c.
References tw_event::recv_ts, TEST_ASSERT_EQUAL_FLOAT, tw_pq_create(), tw_pq_enqueue(), and tw_pq_minimum().
Referenced by main().