ROSS: ross/test/test_ross_pq_example.c File Reference
test_ross_pq_example.c File Reference
#include <ross.h>
#include "unity.h"
Functions
void tearDown (void)
void setUp (void)
void test_pizza (void)
void test_pq (void)
Function Documentation
void setUp (void)
Definition at line 8 of file test_ross_pq_example.c.
void tearDown (void)
Definition at line 4 of file test_ross_pq_example.c.
void test_pizza (void)
Definition at line 12 of file test_ross_pq_example.c.
References TEST_ASSERT_EQUAL_STRING.
Referenced by main().
void test_pq (void)
Definition at line 17 of file test_ross_pq_example.c.
References tw_event::recv_ts, TEST_ASSERT_EQUAL_FLOAT, tw_pq_create(), tw_pq_enqueue(), and tw_pq_minimum().
Referenced by main().