ROSS: rnf/modules/network/multicast/tfmcc.h File Reference
tfmcc.h File Reference
#include "Transport.h"
#include <float.h>
#include <assert.h>
Data Structures
struct TfmccSrcInfoStruct
Macros
#define TRACE_TFMCC_THROUGHPUT 1
#define TFMCC_THROUGHPUT_SAMPLE_ITVL 0.1
#define Max(a, b) (((a) > (b)) ? (a) : (b))
#define Min(a, b) (((a) < (b)) ? (a) : (b))
#define TFMCC_SMALLFLOAT 0.0000001
#define TFMCC_SRC_DEC_NO_REPORT 10
#define TFMCC_SRC_G_FACTOR 0.1
#define TFMCC_MAX_ROUND_ID 1000000
#define TFMCC_SRC_MAX_RTT_DECAY 0.9
#define TFMCC_SRC_DATA_PKT_SIZE 1000
#define TFMCC_SRC_MIN_RATE TFMCC_SRC_DATA_PKT_SIZE
#define TFMCC_SRC_INIT_RTT 0.5
#define TFMCC_SRC_INIT_RATE
Typedefs
typedef struct TfmccSrcInfoStruct TfmccSrcInfo
Enumerations
enum { TFMCC_SRC_STATE_INIT_RATE = 0, TFMCC_SRC_STATE_SLOW_START = 1, TFMCC_SRC_STATE_CONG_AVOID = 2 }
enum { TFMCC_SRC_PRIO_FORCE = 4, TFMCC_SRC_PRIO_NO_RTT = 3, TFMCC_SRC_PRIO_RECV = 2, TFMCC_SRC_PRIO_CLR = 1 }
enum { TFMCC_SRC_TIMER_SEND_PKT, TFMCC_SRC_TIMER_NO_FDBK }
Functions
Agent * TfmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
void TfmccSrcStart (Agent *agent)
void TfmccSrcStop (Agent *agent)
void TfmccSrcPktHandler (Agent *agent, Packet *p)
void TfmccSrcSlowStart (Agent *agent)
void TfmccSrcIncrRate (Agent *agent)
void TfmccSrcDecrRate (Agent *agent)
void TfmccSrcSendPkt (Agent *agent)
void TfmccSrcTimer (Agent *agent, int timerId, int serial)
void TfmccSrcPrintStat (Agent *agent)
Macro Definition Documentation
#define Max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 16 of file tfmcc.h.
Referenced by TfmccSrcTimer().
#define Min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 20 of file tfmcc.h.
Referenced by TfmccSrcTimer().
#define TFMCC_MAX_ROUND_ID 1000000
Definition at line 37 of file tfmcc.h.
Referenced by TfmccRcvPktHandler(), and TfmccSrcTimer().
#define TFMCC_SMALLFLOAT 0.0000001
Definition at line 23 of file tfmcc.h.
Referenced by TfmccSrcIncrRate(), and TfmccSrcTimer().
#define TFMCC_SRC_DATA_PKT_SIZE 1000
Definition at line 55 of file tfmcc.h.
Referenced by TfmccRcvStart(), and TfmccSrcStart().
#define TFMCC_SRC_DEC_NO_REPORT 10
Definition at line 35 of file tfmcc.h.
Referenced by TfmccSrcPktHandler(), TfmccSrcStart(), and TfmccSrcTimer().
#define TFMCC_SRC_G_FACTOR 0.1
Definition at line 36 of file tfmcc.h.
Referenced by TfmccSrcPktHandler().
#define TFMCC_SRC_INIT_RATE
Value:
(2 * TFMCC_SRC_DATA_PKT_SIZE \
                                             / TFMCC_SRC_INIT_RTT)
Definition at line 59 of file tfmcc.h.
Referenced by TfmccSrcStart().
#define TFMCC_SRC_INIT_RTT 0.5
Definition at line 58 of file tfmcc.h.
Referenced by TfmccSrcStart().
#define TFMCC_SRC_MAX_RTT_DECAY 0.9
Definition at line 38 of file tfmcc.h.
Referenced by TfmccSrcTimer().
#define TFMCC_SRC_MIN_RATE TFMCC_SRC_DATA_PKT_SIZE
Definition at line 57 of file tfmcc.h.
Referenced by TfmccSrcPktHandler().
#define TFMCC_THROUGHPUT_SAMPLE_ITVL 0.1
Definition at line 11 of file tfmcc.h.
Referenced by TfmccSrcSendPkt().
#define TRACE_TFMCC_THROUGHPUT 1
Definition at line 8 of file tfmcc.h.
Typedef Documentation
typedef struct TfmccSrcInfoStruct TfmccSrcInfo
Enumeration Type Documentation
anonymous enum
Enumerator
TFMCC_SRC_STATE_INIT_RATE
TFMCC_SRC_STATE_SLOW_START
TFMCC_SRC_STATE_CONG_AVOID
Definition at line 27 of file tfmcc.h.
anonymous enum
Enumerator
TFMCC_SRC_PRIO_FORCE
TFMCC_SRC_PRIO_NO_RTT
TFMCC_SRC_PRIO_RECV
TFMCC_SRC_PRIO_CLR
Definition at line 40 of file tfmcc.h.
anonymous enum
Enumerator
TFMCC_SRC_TIMER_SEND_PKT
TFMCC_SRC_TIMER_NO_FDBK
Definition at line 49 of file tfmcc.h.
Function Documentation
void TfmccSrcDecrRate (Agent * agent) inline
Definition at line 297 of file tfmcc.c.
References TfmccSrcInfoStruct::expected_rate, AgentStruct::info_, TfmccSrcInfoStruct::last_change_, AgentStruct::nodeId_, TfmccSrcInfoStruct::oldrate_, TfmccSrcInfoStruct::rate_, tw_getlp(), and tw_now().
Referenced by TfmccSrcPktHandler().
void TfmccSrcIncrRate (Agent * agent) inline
Definition at line 270 of file tfmcc.c.
References TfmccSrcInfoStruct::expected_rate, TfmccSrcInfoStruct::fairsize_, AgentStruct::info_, TfmccSrcInfoStruct::inter_packet, TfmccSrcInfoStruct::last_change_, TfmccSrcInfoStruct::max_rtt_, mult, AgentStruct::nodeId_, TfmccSrcInfoStruct::pktSize_, TfmccSrcInfoStruct::rate_, ReschedTimer(), TfmccSrcInfoStruct::sendPktTimerEvnt_, TFMCC_SMALLFLOAT, TFMCC_SRC_TIMER_SEND_PKT, tw_getlp(), and tw_now().
Referenced by TfmccSrcPktHandler().
Agent* TfmccSrcInit (int nodeId, uint16 agentId, uint32 pktDstAddr, uint16 pktDstAgentId, int8 trackStat)
Definition at line 9 of file tfmcc.c.
References _nodeTable, GetAgent(), AgentStruct::info_, TfmccSrcInfoStruct::pktDstAddr_, TfmccSrcInfoStruct::pktDstAgentId_, RegisterAgent(), TfmccSrcPktHandler(), TfmccSrcPrintStat(), TfmccSrcStart(), TfmccSrcStop(), TfmccSrcTimer(), TfmccSrcInfoStruct::trackStat_, and tw_exit().
Referenced by ReadAgentAct().
void TfmccSrcPktHandler (Agent * agent, Packet * p)
Definition at line 114 of file tfmcc.c.
References TfmccSrcInfoStruct::active_, TfmccSrcInfoStruct::clr_id, TfmccSrcInfoStruct::clr_last_feedback, TfmccSrcInfoStruct::clr_timestamp, TfmccSrcInfoStruct::expected_rate, TfmccNakStruct::have_loss, TfmccNakStruct::have_rtt, AgentStruct::id_, AgentStruct::info_, TfmccSrcInfoStruct::max_rtt_, TfmccSrcInfoStruct::maxrate_, AgentStruct::nodeId_, TfmccSrcInfoStruct::noFdbkTimerEvnt_, TfmccSrcInfoStruct::oldrate_, TfmccNakStruct::rate, TfmccSrcInfoStruct::rate_, TfmccSrcInfoStruct::rate_change_, TfmccNakStruct::receiver_leave, ReschedTimer(), TfmccSrcInfoStruct::round_id, TfmccNakStruct::round_id, TfmccSrcInfoStruct::rtt_prio, TfmccSrcInfoStruct::rtt_rate, TfmccSrcInfoStruct::rtt_recv_id, TfmccSrcInfoStruct::rtt_recv_last_feedback, TfmccSrcInfoStruct::rtt_recv_timestamp, PacketStruct::srcAddr_, TfmccSrcInfoStruct::supp_rate_, TFMCC_NAK, TFMCC_SRC_DEC_NO_REPORT, TFMCC_SRC_G_FACTOR, TFMCC_SRC_MIN_RATE, TFMCC_SRC_PRIO_CLR, TFMCC_SRC_PRIO_FORCE, TFMCC_SRC_PRIO_NO_RTT, TFMCC_SRC_PRIO_RECV, TFMCC_SRC_STATE_CONG_AVOID, TFMCC_SRC_STATE_INIT_RATE, TFMCC_SRC_STATE_SLOW_START, TFMCC_SRC_TIMER_NO_FDBK, TfmccSrcDecrRate(), TfmccSrcIncrRate(), TfmccSrcSlowStart(), TfmccNakStruct::timestamp, TfmccNakStruct::timestamp_echo, TfmccNakStruct::timestamp_offset, PacketStruct::tn_, tw_exit(), tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by TfmccSrcInit().
void TfmccSrcPrintStat (Agent * agent)
Definition at line 443 of file tfmcc.c.
Referenced by TfmccSrcInit().
void TfmccSrcSendPkt (Agent * agent)
Definition at line 308 of file tfmcc.c.
References _nodeTable, TfmccSrcInfoStruct::active_, NodeStruct::addr_, TfmccSrcInfoStruct::clr_id, TfmccSrcInfoStruct::clr_last_feedback, TfmccSrcInfoStruct::clr_timestamp, PacketStruct::dstAddr_, PacketStruct::dstAgent_, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, TfmccDataStruct::is_clr, TfmccDataStruct::max_rtt, TfmccSrcInfoStruct::max_rtt_, TfmccSrcInfoStruct::ndatapack_, AgentStruct::nodeId_, p, TfmccSrcInfoStruct::pktDstAddr_, TfmccSrcInfoStruct::pktDstAgentId_, TfmccSrcInfoStruct::pktSize_, TfmccSrcInfoStruct::round_id, TfmccDataStruct::round_id, TfmccSrcInfoStruct::rtt_prio, TfmccSrcInfoStruct::rtt_recv_id, TfmccDataStruct::rtt_recv_id, TfmccSrcInfoStruct::rtt_recv_last_feedback, TfmccSrcInfoStruct::rtt_recv_timestamp, SendPacket(), TfmccDataStruct::seqno, TfmccSrcInfoStruct::seqno_, PacketStruct::size_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, TfmccDataStruct::supp_rate, TfmccSrcInfoStruct::supp_rate_, PacketStruct::td_, TFMCC_DATA, TFMCC_THROUGHPUT_SAMPLE_ITVL, TfmccSrcInfoStruct::thruSampleTime_, TfmccDataStruct::timestamp, TfmccDataStruct::timestamp_echo, TfmccDataStruct::timestamp_offset, TfmccSrcInfoStruct::totalSentBytes_, TfmccSrcInfoStruct::trackStat_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by TfmccSrcStart(), and TfmccSrcTimer().
void TfmccSrcSlowStart (Agent * agent)
Definition at line 224 of file tfmcc.c.
References TfmccSrcInfoStruct::delta_, TfmccSrcInfoStruct::fairsize_, AgentStruct::info_, TfmccSrcInfoStruct::last_change_, TfmccSrcInfoStruct::max_rtt_, TfmccSrcInfoStruct::maxrate_, AgentStruct::nodeId_, TfmccSrcInfoStruct::oldrate_, TfmccSrcInfoStruct::pktSize_, TfmccSrcInfoStruct::rate_, TfmccSrcInfoStruct::ssmult_, tw_getlp(), and tw_now().
Referenced by TfmccSrcPktHandler().
void TfmccSrcStart (Agent * agent)
Definition at line 41 of file tfmcc.c.
References TfmccSrcInfoStruct::active_, TfmccSrcInfoStruct::bval_, TfmccSrcInfoStruct::clr_id, TfmccSrcInfoStruct::clr_last_feedback, TfmccSrcInfoStruct::clr_timestamp, TfmccSrcInfoStruct::delta_, TfmccSrcInfoStruct::expected_rate, TfmccSrcInfoStruct::fairsize_, AgentStruct::info_, TfmccSrcInfoStruct::inter_packet, TfmccSrcInfoStruct::last_change_, TfmccSrcInfoStruct::max_rtt_, TfmccSrcInfoStruct::maxrate_, TfmccSrcInfoStruct::ndatapack_, AgentStruct::nodeId_, TfmccSrcInfoStruct::noFdbkTimerEvnt_, TfmccSrcInfoStruct::oldrate_, TfmccSrcInfoStruct::overhead_, TfmccSrcInfoStruct::pktSize_, TfmccSrcInfoStruct::rate_, TfmccSrcInfoStruct::rate_change_, TfmccSrcInfoStruct::round_begin_, TfmccSrcInfoStruct::round_id, TfmccSrcInfoStruct::rtt_prio, TfmccSrcInfoStruct::rtt_rate, TfmccSrcInfoStruct::rtt_recv_id, TfmccSrcInfoStruct::rtt_recv_last_feedback, TfmccSrcInfoStruct::rtt_recv_timestamp, ScheduleTimer(), TfmccSrcInfoStruct::sendPktTimerEvnt_, TfmccSrcInfoStruct::seqno_, TfmccSrcInfoStruct::ssmult_, TfmccSrcInfoStruct::supp_rate_, TfmccSrcInfoStruct::t_factor_, TFMCC_SRC_DATA_PKT_SIZE, TFMCC_SRC_DEC_NO_REPORT, TFMCC_SRC_INIT_RATE, TFMCC_SRC_INIT_RTT, TFMCC_SRC_STATE_INIT_RATE, TFMCC_SRC_TIMER_NO_FDBK, TFMCC_SRC_TIMER_SEND_PKT, TfmccSrcSendPkt(), TfmccSrcInfoStruct::thruSampleTime_, TfmccSrcInfoStruct::totalSentBytes_, tw_getlp(), and tw_now().
Referenced by TfmccSrcInit().
void TfmccSrcStop (Agent * agent)
Definition at line 101 of file tfmcc.c.
References TfmccSrcInfoStruct::active_, CancelTimer(), AgentStruct::info_, TfmccSrcInfoStruct::noFdbkTimerEvnt_, and TfmccSrcInfoStruct::sendPktTimerEvnt_.
Referenced by TfmccSrcInit().
void TfmccSrcTimer (Agent * agent, int timerId, int serial)
Definition at line 369 of file tfmcc.c.
References TfmccSrcInfoStruct::active_, TfmccSrcInfoStruct::clr_id, TfmccSrcInfoStruct::clr_last_feedback, TfmccSrcInfoStruct::delta_, AgentStruct::info_, TfmccSrcInfoStruct::inter_packet, Max, TfmccSrcInfoStruct::max_rtt_, Min, AgentStruct::nodeId_, TfmccSrcInfoStruct::noFdbkTimerEvnt_, TfmccSrcInfoStruct::oldrate_, TfmccSrcInfoStruct::pktSize_, TfmccSrcInfoStruct::rate_, TfmccSrcInfoStruct::rate_change_, ReschedTimer(), TfmccSrcInfoStruct::round_begin_, TfmccSrcInfoStruct::round_id, ScheduleTimer(), TfmccSrcInfoStruct::sendPktTimerEvnt_, TfmccSrcInfoStruct::supp_rate_, TfmccSrcInfoStruct::t_factor_, TFMCC_MAX_ROUND_ID, TFMCC_SMALLFLOAT, TFMCC_SRC_DEC_NO_REPORT, TFMCC_SRC_MAX_RTT_DECAY, TFMCC_SRC_STATE_SLOW_START, TFMCC_SRC_TIMER_NO_FDBK, TFMCC_SRC_TIMER_SEND_PKT, TfmccSrcSendPkt(), tw_getlp(), and tw_now().
Referenced by TfmccSrcInit().