ROSS: rnf/modules/network/multicast/tfmcc-sink.h File Reference
tfmcc-sink.h File Reference
#include "Transport.h"
Data Structures
struct TfmccRcvInfoStruct
Macros
#define LARGE_DOUBLE 9999999999.99
#define TFMCC_RCV_DEFAULT_NUMSAMPLES 8
#define TFMCC_RCV_MAX_NUM_RECVS 10000
#define TFMCC_RCV_NAK_PKT_SIZE 40
Typedefs
typedef struct TfmccRcvInfoStruct TfmccRcvInfo
Enumerations
enum { TFMCC_RCV_UNKNOWN = 0, TFMCC_RCV_RCVD = 1, TFMCC_RCV_LOST = 2, TFMCC_RCV_NOLOSS = 3 }
Functions
Agent * TfmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
void TfmccRcvStart (Agent *agent)
void TfmccRcvStop (Agent *agent)
void TfmccRcvPktHandler (Agent *agent, Packet *p)
void TfmccRcvSendPkt (Agent *agent, Packet *srcPkt)
void TfmccRcvTimer (Agent *agent, int timerId, int serial)
void TfmccRcvPrintStat (Agent *agent)
void TfmccRcvAddPktToHistory (Agent *agent, Packet *p)
double TfmccRcvEstLoss (Agent *agent)
double TfmccRcvWeightedAvg (Agent *agent, int start, int end, double factor, double *m, double *w, int *sample)
void TfmccRcvShiftArrayInt (int *a, int sz, int defval)
void TfmccRcvShiftArrayDbl (double *a, int sz, double defval)
void TfmccRcvMultArray (double *a, int sz, double multiplier)
double TfmccRcvEstThput (Agent *agent)
double TfmccRcvAdjustHistory (Agent *agent, double ts)
double TfmccRcvFdbkTime (Agent *agent, double rtt, int num_recv)
Macro Definition Documentation
#define LARGE_DOUBLE 9999999999.99
Definition at line 7 of file tfmcc-sink.h.
#define TFMCC_RCV_DEFAULT_NUMSAMPLES 8
Definition at line 17 of file tfmcc-sink.h.
Referenced by TfmccRcvPktHandler().
#define TFMCC_RCV_MAX_NUM_RECVS 10000
Definition at line 18 of file tfmcc-sink.h.
Referenced by TfmccRcvPktHandler().
#define TFMCC_RCV_NAK_PKT_SIZE 40
Definition at line 21 of file tfmcc-sink.h.
Referenced by TfmccRcvSendPkt().
Typedef Documentation
typedef struct TfmccRcvInfoStruct TfmccRcvInfo
Enumeration Type Documentation
anonymous enum
Enumerator
TFMCC_RCV_UNKNOWN
TFMCC_RCV_RCVD
TFMCC_RCV_LOST
TFMCC_RCV_NOLOSS
Definition at line 10 of file tfmcc-sink.h.
Function Documentation
void TfmccRcvAddPktToHistory (Agent * agent, Packet * p)
Definition at line 323 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::avgsize_, TfmccRcvInfoStruct::conservative_rtt, TfmccRcvInfoStruct::fairsize_, TfmccRcvInfoStruct::hsz, AgentStruct::info_, TfmccRcvInfoStruct::last_sample, TfmccRcvInfoStruct::last_timestamp_, TfmccRcvInfoStruct::lastloss, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::maxseq, AgentStruct::nodeId_, TfmccRcvInfoStruct::rtvec_, TfmccDataStruct::seqno, PacketStruct::size_, TfmccRcvInfoStruct::sizevec_, PacketStruct::td_, TFMCC_RCV_LOST, TFMCC_RCV_NOLOSS, TFMCC_RCV_RCVD, TFMCC_RCV_UNKNOWN, TfmccRcvInfoStruct::tsvec_, tw_exit(), tw_getlp(), tw_now(), and PacketStruct::type.
Referenced by TfmccRcvPktHandler().
double TfmccRcvAdjustHistory (Agent * agent, double ts)
Definition at line 602 of file tfmcc-sink.c.
References b_to_p(), TfmccRcvInfoStruct::bval_, TfmccRcvInfoStruct::conservative_rtt, TfmccRcvInfoStruct::fairsize_, TfmccRcvInfoStruct::false_sample, TfmccRcvInfoStruct::hsz, AgentStruct::info_, TfmccRcvInfoStruct::last_sample, TfmccRcvInfoStruct::lastloss, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::maxseq, p, TfmccRcvInfoStruct::rtt_lossinit, TfmccRcvInfoStruct::sample, TfmccRcvInfoStruct::sample_count, TFMCC_RCV_LOST, TFMCC_RCV_NOLOSS, and TfmccRcvEstThput().
Referenced by TfmccRcvPktHandler().
double TfmccRcvEstLoss (Agent * agent)
Definition at line 403 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::aggregate_loss_, TfmccRcvInfoStruct::aggregate_packets_, TfmccRcvInfoStruct::discount, factor, TfmccRcvInfoStruct::fairsize_, TfmccRcvInfoStruct::false_sample, TfmccRcvInfoStruct::hsz, AgentStruct::info_, TfmccRcvInfoStruct::last_sample, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::maxseq, TfmccRcvInfoStruct::mult, TfmccRcvInfoStruct::mult_factor_, TfmccRcvInfoStruct::numsamples, TfmccRcvInfoStruct::sample, TfmccRcvInfoStruct::sample_count, TfmccRcvInfoStruct::sizevec_, TfmccRcvInfoStruct::sum_lsize_, TfmccRcvInfoStruct::sum_psize_, TFMCC_RCV_LOST, TFMCC_RCV_NOLOSS, TfmccRcvMultArray(), TfmccRcvShiftArrayDbl(), TfmccRcvShiftArrayInt(), TfmccRcvWeightedAvg(), tw_exit(), and TfmccRcvInfoStruct::weights.
Referenced by TfmccRcvPktHandler().
double TfmccRcvEstThput (Agent * agent) inline
Definition at line 579 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::avgsize_, TfmccRcvInfoStruct::conservative_rtt, TfmccRcvInfoStruct::hsz, AgentStruct::info_, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::maxseq, TfmccRcvInfoStruct::rtvec_, and TFMCC_RCV_RCVD.
Referenced by TfmccRcvAdjustHistory(), and TfmccRcvPktHandler().
double TfmccRcvFdbkTime (Agent * agent, double rtt, int num_recv) inline
Definition at line 632 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::fbtime_mult_, AgentStruct::info_, and x.
Referenced by TfmccRcvPktHandler().
Agent* TfmccRcvInit (int nodeId, uint16 agentId, uint32 listenAddr)
Definition at line 12 of file tfmcc-sink.c.
References GetAgent(), AgentStruct::info_, IsMcastAddr, RegisterAgent(), TfmccRcvPktHandler(), TfmccRcvPrintStat(), TfmccRcvStart(), TfmccRcvStop(), TfmccRcvTimer(), and tw_exit().
Referenced by ReadAgentAct().
void TfmccRcvMultArray (double * a, int sz, double multiplier) inline
Definition at line 569 of file tfmcc-sink.c.
Referenced by TfmccRcvEstLoss().
void TfmccRcvPktHandler (Agent * agent, Packet * p)
Definition at line 130 of file tfmcc-sink.c.
References _addrToIdx, _nodeTable, TfmccRcvInfoStruct::active_, NodeStruct::addr_, TfmccRcvInfoStruct::adjust_history_after_ss, TfmccRcvInfoStruct::avgsize_, TfmccRcvInfoStruct::bval_, TfmccRcvInfoStruct::comparison_rate, TfmccRcvInfoStruct::conservative_rtt, TfmccRcvInfoStruct::constant_rate_, TfmccRcvInfoStruct::df_, TfmccRcvInfoStruct::fairsize_, TfmccRcvInfoStruct::false_sample, TfmccRcvInfoStruct::fb_time, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, TfmccDataStruct::is_clr, TfmccRcvInfoStruct::last_arrival_, TfmccRcvInfoStruct::last_report_sent, TfmccRcvInfoStruct::last_sample, TfmccRcvInfoStruct::last_timestamp_, TfmccRcvInfoStruct::loss_seen_yet, TfmccRcvInfoStruct::max_rtt, TfmccDataStruct::max_rtt, TfmccRcvInfoStruct::maxseq, TfmccRcvInfoStruct::mult, AgentStruct::nodeId_, TfmccRcvInfoStruct::numsamples, TfmccRcvInfoStruct::one_way_, p, p_to_b(), TfmccRcvInfoStruct::psize_, TfmccRcvInfoStruct::rate_, TfmccRcvInfoStruct::rcvd_since_last_report, TfmccRcvInfoStruct::representative, TfmccRcvInfoStruct::round_id, TfmccDataStruct::round_id, TfmccRcvInfoStruct::rtt_, TfmccRcvInfoStruct::rtt_est, TfmccRcvInfoStruct::rtt_lossinit, TfmccDataStruct::rtt_recv_id, TfmccRcvInfoStruct::sample, TfmccRcvInfoStruct::sample_count, TfmccDataStruct::seqno, PacketStruct::size_, TfmccRcvInfoStruct::smooth_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, TfmccDataStruct::supp_rate, TfmccRcvInfoStruct::suppression_rate, PacketStruct::td_, TFMCC_DATA, TFMCC_MAX_ROUND_ID, TFMCC_RCV_DEFAULT_NUMSAMPLES, TFMCC_RCV_MAX_NUM_RECVS, TfmccRcvAddPktToHistory(), TfmccRcvAdjustHistory(), TfmccRcvEstLoss(), TfmccRcvEstThput(), TfmccRcvFdbkTime(), TfmccRcvSendPkt(), TfmccRcvInfoStruct::tight_loop_, TfmccDataStruct::timestamp, TfmccDataStruct::timestamp_echo, TfmccDataStruct::timestamp_offset, tw_exit(), tw_getlp(), tw_now(), PacketStruct::type, PacketStruct::type_, and TfmccRcvInfoStruct::weights.
Referenced by TfmccRcvInit().
void TfmccRcvPrintStat (Agent * agent)
Definition at line 691 of file tfmcc-sink.c.
References _totalTfmccNak, GetGrpAddr4Print, AgentStruct::id_, AgentStruct::info_, TfmccRcvInfoStruct::nakSent_, and AgentStruct::nodeId_.
Referenced by TfmccRcvInit().
void TfmccRcvSendPkt (Agent * agent, Packet * srcPkt)
Definition at line 645 of file tfmcc-sink.c.
References _nodeTable, _totalTfmccNak, TfmccRcvInfoStruct::active_, NodeStruct::addr_, PacketStruct::dstAddr_, PacketStruct::dstAgent_, TfmccNakStruct::have_loss, TfmccNakStruct::have_rtt, AgentStruct::id_, AgentStruct::info_, PacketStruct::inPort_, IsMcastAddr, TfmccRcvInfoStruct::last_arrival_, TfmccRcvInfoStruct::last_report_sent, TfmccRcvInfoStruct::last_timestamp_, AgentStruct::listenAddr_, TfmccRcvInfoStruct::loss_seen_yet, TfmccRcvInfoStruct::nakSent_, AgentStruct::nodeId_, p, TfmccNakStruct::rate, TfmccRcvInfoStruct::rate_, TfmccRcvInfoStruct::rcvd_since_last_report, TfmccRcvInfoStruct::receiver_leave, TfmccNakStruct::receiver_leave, TfmccRcvInfoStruct::round_id, TfmccNakStruct::round_id, TfmccRcvInfoStruct::rtt_, SendPacket(), PacketStruct::size_, PacketStruct::srcAddr_, PacketStruct::srcAgent_, TFMCC_NAK, TFMCC_RCV_NAK_PKT_SIZE, TfmccNakStruct::timestamp, TfmccNakStruct::timestamp_echo, TfmccNakStruct::timestamp_offset, PacketStruct::tn_, tw_getlp(), tw_now(), PacketStruct::type, and PacketStruct::type_.
Referenced by TfmccRcvPktHandler().
void TfmccRcvShiftArrayDbl (double * a, int sz, double defval) inline
Definition at line 559 of file tfmcc-sink.c.
Referenced by TfmccRcvEstLoss().
void TfmccRcvShiftArrayInt (int * a, int sz, int defval) inline
Definition at line 549 of file tfmcc-sink.c.
Referenced by TfmccRcvEstLoss().
void TfmccRcvStart (Agent * agent)
Definition at line 48 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::active_, TfmccRcvInfoStruct::adjust_history_after_ss, TfmccRcvInfoStruct::aggregate_loss_, TfmccRcvInfoStruct::aggregate_packets_, TfmccRcvInfoStruct::avgsize_, TfmccRcvInfoStruct::bval_, TfmccRcvInfoStruct::comparison_rate, TfmccRcvInfoStruct::constant_rate_, TfmccRcvInfoStruct::df_, TfmccRcvInfoStruct::discount, TfmccRcvInfoStruct::fairsize_, TfmccRcvInfoStruct::false_sample, TfmccRcvInfoStruct::fb_time, TfmccRcvInfoStruct::fbtime_mult_, TfmccRcvInfoStruct::hsz, AgentStruct::info_, TfmccRcvInfoStruct::last_arrival_, TfmccRcvInfoStruct::last_report_sent, TfmccRcvInfoStruct::last_sample, TfmccRcvInfoStruct::last_timestamp_, TfmccRcvInfoStruct::lastloss, TfmccRcvInfoStruct::loss_seen_yet, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::maxseq, TfmccRcvInfoStruct::mult, TfmccRcvInfoStruct::mult_factor_, TfmccRcvInfoStruct::numsamples, TfmccRcvInfoStruct::one_way_, TfmccRcvInfoStruct::rate_, TfmccRcvInfoStruct::rcvd_since_last_report, TfmccRcvInfoStruct::receiver_leave, TfmccRcvInfoStruct::representative, TfmccRcvInfoStruct::round_id, TfmccRcvInfoStruct::rtt_, TfmccRcvInfoStruct::rtt_est, TfmccRcvInfoStruct::rtvec_, TfmccRcvInfoStruct::sample, TfmccRcvInfoStruct::sample_count, TfmccRcvInfoStruct::sizevec_, TfmccRcvInfoStruct::smooth_, TfmccRcvInfoStruct::sum_lsize_, TfmccRcvInfoStruct::sum_psize_, TfmccRcvInfoStruct::suppression_rate, TFMCC_SRC_DATA_PKT_SIZE, TfmccRcvInfoStruct::tight_loop_, TfmccRcvInfoStruct::tsvec_, and TfmccRcvInfoStruct::weights.
Referenced by TfmccRcvInit().
void TfmccRcvStop (Agent * agent)
Definition at line 104 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::active_, AgentStruct::info_, TfmccRcvInfoStruct::lossvec_, TfmccRcvInfoStruct::mult, TfmccRcvInfoStruct::rate_, TfmccRcvInfoStruct::receiver_leave, TfmccRcvInfoStruct::rtvec_, TfmccRcvInfoStruct::sample, TfmccRcvInfoStruct::sizevec_, TfmccRcvInfoStruct::tsvec_, and TfmccRcvInfoStruct::weights.
Referenced by TfmccRcvInit().
void TfmccRcvTimer (Agent * agent, int timerId, int serial)
Definition at line 683 of file tfmcc-sink.c.
References TfmccRcvInfoStruct::active_, and AgentStruct::info_.
Referenced by TfmccRcvInit().
double TfmccRcvWeightedAvg (Agent * agent, int start, int end, double factor, double * m, double * w, int * sample)
Definition at line 507 of file tfmcc-sink.c.
References AgentStruct::info_, TfmccRcvInfoStruct::numsamples, and TfmccRcvInfoStruct::smooth_.
Referenced by TfmccRcvEstLoss().