ROSS: rnf/modules/physical/tlm/tlm-model.c File Reference
tlm-model.c File Reference
#include <tlm.h>
Functions
void tlm_md_opts ()
void tlm_md_init (int argc, char **argv, char **env)
void tlm_md_final ()
Variables
static FILE * g_tlm_output_f = NULL
static const tw_optdef tlm_options []
Function Documentation
void tlm_md_final ()
Definition at line 143 of file tlm-model.c.
References g_rn_environment, g_tlm_output_f, g_tlm_stats, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_statistics::s_nparticles, and tw_ismaster().
void tlm_md_init (int argc, char ** argv, char ** env)
Definition at line 20 of file tlm-model.c.
References g_rn_environment, g_rn_nmachines, g_rn_tools_dir, g_tlm_fd, g_tlm_nodes_plt_f, g_tlm_optmem, g_tlm_output_f, g_tlm_parts_plt_f, g_tlm_scatter_ts, g_tlm_spatial_coeff, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_dir, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_ground_coeff, g_tlm_spatial_offset, g_tlm_spatial_offset_ts, g_tlm_spatial_terrain_fn, g_tlm_stats, g_tlm_wave_attenuation, g_tlm_wave_loss_coeff, g_tlm_wave_threshold, g_tlm_wave_velocity, g_tlm_waves_plt_f, g_tw_events_per_pe, g_tw_npe, g_tw_ts_end, ntlm_lp_per_pe, tlm_grid_init(), tw_calloc(), tw_error(), tw_ismaster(), TW_LOC, tw_lp_settype(), and tw_nnodes().
void tlm_md_opts ()
Definition at line 14 of file tlm-model.c.
References tw_opt_add().
Variable Documentation
FILE* g_tlm_output_f = NULL static
Definition at line 3 of file tlm-model.c.
Referenced by tlm_md_final(), and tlm_md_init().
const tw_optdef tlm_options[] static
Initial value:
=
{
        TWOPT_GROUP("Transmission Line Matrix Model"),
        TWOPT_UINT("memory", g_tlm_optmem, "Additional memory buffers"),
        TWOPT_STIME("threshold", g_tlm_wave_threshold, "Wave propagation threshold"),
}
Definition at line 5 of file tlm-model.c.