ROSS: rnf/modules/physical/tlm/tlm-grid.c File Reference
tlm-grid.c File Reference
#include <tlm.h>
Functions
tw_lpid tlm_grid_init ()
Function Documentation
tw_lpid tlm_grid_init ()
Definition at line 30 of file tlm-grid.c.
References f, g_tlm_scatter_ts, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_offset_ts, g_tlm_spatial_terrain_fn, g_tlm_wave_velocity, g_tlm_z_values, g_tw_mynode, g_tw_npe, min, nlp, npe, tw_calloc(), tw_error(), TW_LOC, tw_nnodes(), and x.
Referenced by tlm_md_init().