ROSS: rnf/modules/physical/tlm/tlm-particle.c File Reference
tlm-particle.c File Reference
#include <tlm.h>
Macros
#define VERIFY_PARTICLE 1
Functions
tw_event * tlm_particle_send (tw_lpid gid, tw_stime offset, tw_lp *src_lp)
void tlm_particle_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_rc_particle_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
Macro Definition Documentation
#define VERIFY_PARTICLE 1
Definition at line 3 of file tlm-particle.c.
Function Documentation
void tlm_particle_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 40 of file tlm-particle.c.
References tw_bf::c0, tw_bf::c1, g_tlm_fd, g_tlm_parts_plt_f, tw_lp::id, p, tlm_state::particles, tlm_getlocation(), tlm_proximity_send(), tw_error(), TW_LOC, tw_memory_free(), tw_memoryq_pop(), tw_memoryq_push(), tw_now(), and tlm_particle::user_lp.
Referenced by _tlm_event_handler().
tw_event* tlm_particle_send (tw_lpid gid, tw_stime offset, tw_lp * src_lp)
Definition at line 9 of file tlm-particle.c.
References g_tlm_fd, p, RM_PARTICLE, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_memory_alloc(), and tlm_message::type.
Referenced by tlm_move().
void tlm_rc_particle_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 112 of file tlm-particle.c.
References tw_bf::c0, tw_bf::c1, g_tlm_fd, tlm_state::particles, tw_memory_free_rc(), tw_memoryq_pop(), tw_memoryq_push(), and tw_now().
Referenced by _tlm_rc_event_handler().