ROSS: rnf/modules/physical/tlm/tlm-xml.c File Reference
tlm-xml.c File Reference
#include <tlm.h>
Functions
void read_vector (unsigned int **v, char *name, const xmlNodePtr node)
void tlm_xml (tlm_state *state, const xmlNodePtr node, tw_lp *lp)
Function Documentation
void read_vector (unsigned int ** v, char * name, const xmlNodePtr node)
Definition at line 4 of file tlm-xml.c.
References g_tlm_spatial_dim, tw_calloc(), and TW_LOC.
Referenced by tlm_xml().
void tlm_xml (tlm_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 24 of file tlm-xml.c.
References g_rn_env_nlps, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_z_max, nlp, read_vector(), tw_error(), TW_LOC, and xml_getprop().