ROSS: rnf/modules/physical/tlm/tlm-helper.c File Reference
tlm-helper.c File Reference
#include <tlm.h>
Macros
#define DEBUG 0
Functions
double tlm_getelevation (double *p)
tw_lpid tlm_getcell (double *position)
double * tlm_getlocation (tw_lp *lp)
Macro Definition Documentation
#define DEBUG 0
Definition at line 3 of file tlm-helper.c.
Function Documentation
tw_lpid tlm_getcell (double * position) inline
Definition at line 32 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid_i, g_tlm_spatial_offset, ntlm_lp_per_pe, and tlm_getelevation().
Referenced by _tlm_init(), tlm_getlocation(), tlm_move(), and tlm_wave_initiate().
double tlm_getelevation (double * p) inline
Definition at line 7 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_grid, g_tlm_z_values, g_tw_mynode, g_tw_npe, npe, and tw_nnodes().
Referenced by _tlm_init(), rp_init(), rp_move(), rw_init(), rw_move(), tlm_getcell(), tlm_getlocation(), and tlm_move().
double* tlm_getlocation (tw_lp * lp) inline
Definition at line 76 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_offset, g_tw_mynode, tw_lp::gid, tw_lp::id, rn_map(), tlm_getcell(), tlm_getelevation(), tw_calloc(), tw_error(), tw_getlocal_lp(), and TW_LOC.
Referenced by _tlm_init(), tlm_cell_scatter(), and tlm_particle_handler().