ROSS: rnf/modules/physical/tlm/tlm-proximity.c File Reference
tlm-proximity.c File Reference
#include <tlm.h>
Functions
void tlm_proximity_send (tlm_state *state, tw_memory *p, tw_memory *b, tw_lp *lp)
Function Documentation
void tlm_proximity_send (tlm_state * state, tw_memory * p, tw_memory * b, tw_lp * lp)
Definition at line 7 of file tlm-proximity.c.
References tw_lp::gid, RM_PROXIMITY_LP, tw_event_data(), tw_event_new(), tw_event_send(), tlm_message::type, and tlm_particle::user_lp.
Referenced by tlm_particle_handler().