ROSS: rnf/modules/physical/tlm/tlm-interface.c File Reference
tlm-interface.c File Reference
#include <tlm.h>
Macros
#define TOP 1
#define RIGHT 1
#define BOTTOM 1
#define LEFT 1
Functions
void tlm_wave_initiate (double *position, double signal, tw_lp *lp)
double tlm_move2 (double range, double position[], double velocity[], tw_lp *lp)
double tlm_move (double range, double position[], double velocity[], tw_lp *lp)
void tlm_rc_move (tw_lp *lp)
Macro Definition Documentation
#define BOTTOM 1
Definition at line 5 of file tlm-interface.c.
#define LEFT 1
Definition at line 6 of file tlm-interface.c.
#define RIGHT 1
Definition at line 4 of file tlm-interface.c.
#define TOP 1
Definition at line 3 of file tlm-interface.c.
Function Documentation
double tlm_move (double range, double position[], double velocity[], tw_lp * lp)
Definition at line 51 of file tlm-interface.c.
References tlm_state::displacement, g_tlm_nodes_plt_f, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, tlm_getcell(), tlm_getelevation(), tlm_particle_send(), tw_error(), TW_LOC, and x.
double tlm_move2 (double range, double position[], double velocity[], tw_lp * lp)
Definition at line 33 of file tlm-interface.c.
References tw_lp::gid, tlm_pe::move_log, tw_lp::pe, and tw_now().
void tlm_rc_move (tw_lp * lp)
Definition at line 164 of file tlm-interface.c.
void tlm_wave_initiate (double * position, double signal, tw_lp * lp)
Definition at line 15 of file tlm-interface.c.
References tlm_message::displacement, g_tlm_scatter_ts, tw_lp::gid, tlm_message::id, RM_WAVE_INIT, tlm_getcell(), tw_event_data(), tw_event_new(), tw_event_send(), and tlm_message::type.
Referenced by rp_event_handler(), and rw_event_handler().