ROSS: rnf/modules/physical/tlm/tlm-extern.h File Reference
tlm-extern.h File Reference
Functions
void tlm_xml (tlm_state *, const xmlNodePtr node, tw_lp *)
void tlm_md_opts ()
void tlm_md_init (int argc, char **argv, char **env)
void tlm_md_final ()
void tlm_pe_init (tw_pe *me)
void tlm_pe_post_init (tw_pe *me)
void tlm_pe_gvt (tw_pe *me)
void tlm_pe_final (tw_pe *me)
void tlm_cell_handler (tlm_state *, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_cell_gather (tlm_state *, tw_bf *bf, tlm_message *, tw_lp *lp)
void tlm_cell_scatter (tlm_state *, tlm_message *, tw_bf *bf, tw_lp *lp)
void tlm_rc_cell_handler (tlm_state *, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_rc_scatter (tlm_state *, tw_bf *bf, tlm_message *, tw_lp *)
void tlm_rc_gather (tlm_state *, tw_bf *bf, tlm_message *, tw_lp *)
tw_event * tlm_timer_cancel (tw_event *t, tw_lp *lp)
tw_event * tlm_timer_start (tw_event *t, int dim, tw_stime ts, tw_lp *lp)
void tlm_wave_initiate (double *position, double signal, tw_lp *lp)
void tlm_rc_wave_initiate (double *position, double signal)
double tlm_move (double, double[], double[], tw_lp *lp)
double tlm_move2 (double, double[], double[], tw_lp *lp)
void tlm_rc_move (tw_lp *lp)
tw_lpid tlm_grid_init ()
void _tlm_init (tlm_state *, tw_lp *lp)
void _tlm_event_handler (tlm_state *, tw_bf *, tlm_message *, tw_lp *lp)
void _tlm_rc_event_handler (tlm_state *, tw_bf *, tlm_message *, tw_lp *lp)
void _tlm_final (tlm_state *, tw_lp *lp)
int tlm_main (int argc, char **argv, char **env)
tw_event * tlm_particle_send (tw_lpid gid, tw_stime, tw_lp *)
void tlm_particle_handler (tlm_state *, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_rc_particle_handler (tlm_state *, tw_bf *, tlm_message *m, tw_lp *lp)
void tlm_proximity_send (tlm_state *, tw_memory *p, tw_memory *b, tw_lp *lp)
double tlm_getelevation (double *p)
tw_lpid tlm_getcell (double *position)
double * tlm_getlocation (tw_lp *lp)
Variables
unsigned int g_tlm_optmem
FILE * g_tlm_waves_plt_f
FILE * g_tlm_nodes_plt_f
FILE * g_tlm_parts_plt_f
tlm_statistics * g_tlm_stats
tw_lpid nlp_per_pe
tw_lpid ntlm_lp_per_pe
unsigned int * g_tlm_spatial_grid
unsigned int * g_tlm_spatial_grid_i
unsigned int * g_tlm_spatial_d
unsigned int g_tlm_spatial_dim
unsigned int g_tlm_spatial_dir
unsigned int g_tlm_spatial_offset
tw_stime * g_tlm_spatial_offset_ts
tw_stime g_tlm_scatter_ts
double g_tlm_spatial_coeff
double g_tlm_spatial_ground_coeff
int ** g_tlm_z_values
int g_tlm_z_max
char g_tlm_spatial_scenario_fn []
char g_tlm_spatial_terrain_fn []
char g_tlm_spatial_urban_fn []
char g_tlm_spatial_vegatation_fn []
double g_tlm_wave_threshold
double g_tlm_wave_attenuation
double g_tlm_wave_loss_coeff
double g_tlm_wave_velocity
tw_fd g_tlm_fd
Function Documentation
void _tlm_event_handler (tlm_state * , tw_bf * , tlm_message * , tw_lp * lp)
Definition at line 141 of file tlm.c.
References RM_GATHER, RM_PARTICLE, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_nparticles, tlm_state::stats, tlm_cell_handler(), tlm_particle_handler(), tw_error(), TW_LOC, and tlm_message::type.
void _tlm_final (tlm_state * , tw_lp * lp)
Definition at line 197 of file tlm.c.
References g_tlm_stats, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_statistics::s_nparticles, and tlm_state::stats.
void _tlm_init (tlm_state * , tw_lp * lp)
Definition at line 13 of file tlm.c.
References tlm_state::displacements, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_dir, g_tlm_spatial_grid, g_tlm_z_max, g_tw_mynode, tw_lp::gid, tlm_state::nbrs, tlm_state::particles, tlm_state::stats, tlm_getcell(), tlm_getelevation(), tlm_getlocation(), tw_calloc(), tw_error(), TW_LOC, and tw_memoryq_init().
void _tlm_rc_event_handler (tlm_state * , tw_bf * , tlm_message * , tw_lp * lp)
Definition at line 171 of file tlm.c.
References RM_GATHER, RM_PARTICLE, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_nparticles, tlm_state::stats, tlm_rc_cell_handler(), tlm_rc_particle_handler(), tw_error(), TW_LOC, and tlm_message::type.
void tlm_cell_gather (tlm_state * , tw_bf * bf, tlm_message * , tw_lp * lp)
Definition at line 130 of file tlm-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_message::displacement, tlm_state::displacements, g_tlm_scatter_ts, tw_lp::gid, tlm_message::id, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_event::recv_ts, RM_SCATTER, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and tlm_message::type.
Referenced by tlm_cell_handler().
void tlm_cell_handler (tlm_state * , tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 14 of file tlm-cell.c.
References RM_GATHER, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_state::stats, tlm_cell_gather(), tlm_cell_scatter(), tw_error(), TW_LOC, and tlm_message::type.
Referenced by _tlm_event_handler().
void tlm_cell_scatter (tlm_state * , tlm_message * , tw_bf * bf, tw_lp * lp)
Definition at line 50 of file tlm-cell.c.
References d, tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_message::displacement, tlm_state::displacements, g_tlm_scatter_ts, g_tlm_spatial_coeff, g_tlm_spatial_dir, g_tlm_spatial_ground_coeff, g_tlm_spatial_offset_ts, g_tlm_wave_loss_coeff, g_tlm_wave_threshold, tw_lp::gid, tlm_message::id, tw_lp::id, tw_pe::id, tlm_state::nbrs, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_event::recv_ts, RM_GATHER, tlm_getlocation(), tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tlm_message::type, and tlm_pe::wave_log.
Referenced by tlm_cell_handler().
tw_lpid tlm_getcell (double * position) inline
Definition at line 32 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid_i, g_tlm_spatial_offset, ntlm_lp_per_pe, and tlm_getelevation().
Referenced by _tlm_init(), tlm_getlocation(), tlm_move(), and tlm_wave_initiate().
double tlm_getelevation (double * p) inline
Definition at line 7 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_grid, g_tlm_z_values, g_tw_mynode, g_tw_npe, npe, and tw_nnodes().
Referenced by _tlm_init(), rp_init(), rp_move(), rw_init(), rw_move(), tlm_getcell(), tlm_getlocation(), and tlm_move().
double* tlm_getlocation (tw_lp * lp) inline
Definition at line 76 of file tlm-helper.c.
References g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_offset, g_tw_mynode, tw_lp::gid, tw_lp::id, rn_map(), tlm_getcell(), tlm_getelevation(), tw_calloc(), tw_error(), tw_getlocal_lp(), and TW_LOC.
Referenced by _tlm_init(), tlm_cell_scatter(), and tlm_particle_handler().
tw_lpid tlm_grid_init ()
Definition at line 30 of file tlm-grid.c.
References f, g_tlm_scatter_ts, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_offset_ts, g_tlm_spatial_terrain_fn, g_tlm_wave_velocity, g_tlm_z_values, g_tw_mynode, g_tw_npe, min, nlp, npe, tw_calloc(), tw_error(), TW_LOC, tw_nnodes(), and x.
Referenced by tlm_md_init().
int tlm_main (int argc, char ** argv, char ** env)
void tlm_md_final ()
Definition at line 143 of file tlm-model.c.
References g_rn_environment, g_tlm_output_f, g_tlm_stats, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_statistics::s_nparticles, and tw_ismaster().
void tlm_md_init (int argc, char ** argv, char ** env)
Definition at line 20 of file tlm-model.c.
References g_rn_environment, g_rn_nmachines, g_rn_tools_dir, g_tlm_fd, g_tlm_nodes_plt_f, g_tlm_optmem, g_tlm_output_f, g_tlm_parts_plt_f, g_tlm_scatter_ts, g_tlm_spatial_coeff, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_dir, g_tlm_spatial_grid, g_tlm_spatial_grid_i, g_tlm_spatial_ground_coeff, g_tlm_spatial_offset, g_tlm_spatial_offset_ts, g_tlm_spatial_terrain_fn, g_tlm_stats, g_tlm_wave_attenuation, g_tlm_wave_loss_coeff, g_tlm_wave_threshold, g_tlm_wave_velocity, g_tlm_waves_plt_f, g_tw_events_per_pe, g_tw_npe, g_tw_ts_end, ntlm_lp_per_pe, tlm_grid_init(), tw_calloc(), tw_error(), tw_ismaster(), TW_LOC, tw_lp_settype(), and tw_nnodes().
void tlm_md_opts ()
Definition at line 14 of file tlm-model.c.
References tw_opt_add().
double tlm_move (double , double [], double [], tw_lp * lp)
Definition at line 51 of file tlm-interface.c.
References tlm_state::displacement, g_tlm_nodes_plt_f, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, tw_lp::gid, tlm_getcell(), tlm_getelevation(), tlm_particle_send(), tw_error(), TW_LOC, and x.
double tlm_move2 (double , double [], double [], tw_lp * lp)
Definition at line 33 of file tlm-interface.c.
References tw_lp::gid, tlm_pe::move_log, tw_lp::pe, and tw_now().
void tlm_particle_handler (tlm_state * , tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 40 of file tlm-particle.c.
References tw_bf::c0, tw_bf::c1, g_tlm_fd, g_tlm_parts_plt_f, tw_lp::id, p, tlm_state::particles, tlm_getlocation(), tlm_proximity_send(), tw_error(), TW_LOC, tw_memory_free(), tw_memoryq_pop(), tw_memoryq_push(), tw_now(), and tlm_particle::user_lp.
Referenced by _tlm_event_handler().
tw_event* tlm_particle_send (tw_lpid gid, tw_stime , tw_lp *)
Definition at line 9 of file tlm-particle.c.
References g_tlm_fd, p, RM_PARTICLE, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_memory_alloc(), and tlm_message::type.
Referenced by tlm_move().
void tlm_pe_final (tw_pe * me)
void tlm_pe_gvt (tw_pe * me)
void tlm_pe_init (tw_pe * me)
void tlm_pe_post_init (tw_pe * me)
void tlm_proximity_send (tlm_state * , tw_memory * p, tw_memory * b, tw_lp * lp)
Definition at line 7 of file tlm-proximity.c.
References tw_lp::gid, RM_PROXIMITY_LP, tw_event_data(), tw_event_new(), tw_event_send(), tlm_message::type, and tlm_particle::user_lp.
Referenced by tlm_particle_handler().
void tlm_rc_cell_handler (tlm_state * , tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 12 of file tlm-rc-cell.c.
References RM_GATHER, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_state::stats, tlm_rc_gather(), tlm_rc_scatter(), tw_error(), TW_LOC, and tlm_message::type.
Referenced by _tlm_rc_event_handler().
void tlm_rc_gather (tlm_state * , tw_bf * bf, tlm_message * , tw_lp *)
Definition at line 53 of file tlm-rc-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_state::displacements, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, and tw_now().
Referenced by tlm_rc_cell_handler().
void tlm_rc_move (tw_lp * lp)
Definition at line 164 of file tlm-interface.c.
void tlm_rc_particle_handler (tlm_state * , tw_bf * , tlm_message * m, tw_lp * lp)
Definition at line 112 of file tlm-particle.c.
References tw_bf::c0, tw_bf::c1, g_tlm_fd, tlm_state::particles, tw_memory_free_rc(), tw_memoryq_pop(), tw_memoryq_push(), and tw_now().
Referenced by _tlm_rc_event_handler().
void tlm_rc_scatter (tlm_state * , tw_bf * bf, tlm_message * , tw_lp *)
Definition at line 37 of file tlm-rc-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_state::displacements, g_tlm_spatial_dir, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_now(), and VERIFY_RM_CELL.
Referenced by tlm_rc_cell_handler().
void tlm_rc_wave_initiate (double * position, double signal)
tw_event* tlm_timer_cancel (tw_event * t, tw_lp * lp)
tw_event* tlm_timer_start (tw_event * t, int dim, tw_stime ts, tw_lp * lp)
void tlm_wave_initiate (double * position, double signal, tw_lp * lp)
Definition at line 15 of file tlm-interface.c.
References tlm_message::displacement, g_tlm_scatter_ts, tw_lp::gid, tlm_message::id, RM_WAVE_INIT, tlm_getcell(), tw_event_data(), tw_event_new(), tw_event_send(), and tlm_message::type.
Referenced by rp_event_handler(), and rw_event_handler().
void tlm_xml (tlm_state * , const xmlNodePtr node, tw_lp *)
Definition at line 24 of file tlm-xml.c.
References g_rn_env_nlps, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_grid, g_tlm_z_max, nlp, read_vector(), tw_error(), TW_LOC, and xml_getprop().
Variable Documentation
tw_fd g_tlm_fd
Referenced by tlm_md_init(), tlm_particle_handler(), tlm_particle_send(), and tlm_rc_particle_handler().
FILE* g_tlm_nodes_plt_f
Definition at line 6 of file tlm-global.c.
Referenced by tlm_md_init(), and tlm_move().
unsigned int g_tlm_optmem
Definition at line 3 of file tlm-global.c.
Referenced by tlm_md_init().
FILE* g_tlm_parts_plt_f
Definition at line 7 of file tlm-global.c.
Referenced by tlm_md_init(), and tlm_particle_handler().
tw_stime g_tlm_scatter_ts
Definition at line 43 of file tlm-global.c.
Referenced by tlm_cell_gather(), tlm_cell_scatter(), tlm_grid_init(), tlm_md_init(), and tlm_wave_initiate().
double g_tlm_spatial_coeff
Definition at line 44 of file tlm-global.c.
Referenced by tlm_cell_scatter(), and tlm_md_init().
unsigned int* g_tlm_spatial_d
Definition at line 38 of file tlm-global.c.
Referenced by _tlm_init(), change_direction(), off_grid(), rp_init(), rw_init(), tlm_getcell(), tlm_getelevation(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), and tlm_xml().
unsigned int g_tlm_spatial_dim
Definition at line 39 of file tlm-global.c.
Referenced by _tlm_init(), read_vector(), rp_init(), rw_init(), tlm_getcell(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), and tlm_xml().
unsigned int g_tlm_spatial_dir
Definition at line 40 of file tlm-global.c.
Referenced by _tlm_init(), state_copy(), tlm_cell_scatter(), tlm_md_init(), and tlm_rc_scatter().
unsigned int* g_tlm_spatial_grid
Definition at line 36 of file tlm-global.c.
Referenced by _tlm_init(), off_grid(), rp_init(), rw_init(), tlm_getelevation(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), and tlm_xml().
unsigned int* g_tlm_spatial_grid_i
Definition at line 37 of file tlm-global.c.
Referenced by tlm_getcell(), tlm_getlocation(), tlm_grid_init(), and tlm_md_init().
double g_tlm_spatial_ground_coeff
Definition at line 45 of file tlm-global.c.
Referenced by tlm_cell_scatter(), and tlm_md_init().
unsigned int g_tlm_spatial_offset
Definition at line 41 of file tlm-global.c.
Referenced by tlm_getcell(), tlm_getlocation(), and tlm_md_init().
tw_stime* g_tlm_spatial_offset_ts
Definition at line 42 of file tlm-global.c.
Referenced by tlm_cell_scatter(), tlm_grid_init(), and tlm_md_init().
char g_tlm_spatial_scenario_fn[]
Definition at line 49 of file tlm-global.c.
char g_tlm_spatial_terrain_fn[]
Definition at line 50 of file tlm-global.c.
Referenced by tlm_grid_init(), and tlm_md_init().
char g_tlm_spatial_urban_fn[]
Definition at line 51 of file tlm-global.c.
char g_tlm_spatial_vegatation_fn[]
Definition at line 52 of file tlm-global.c.
tlm_statistics* g_tlm_stats
Definition at line 9 of file tlm-global.c.
Referenced by _tlm_final(), tlm_md_final(), and tlm_md_init().
double g_tlm_wave_attenuation
Definition at line 65 of file tlm-global.c.
Referenced by tlm_md_init().
double g_tlm_wave_loss_coeff
Definition at line 66 of file tlm-global.c.
Referenced by tlm_cell_scatter(), and tlm_md_init().
double g_tlm_wave_threshold
Definition at line 64 of file tlm-global.c.
Referenced by tlm_cell_scatter(), and tlm_md_init().
double g_tlm_wave_velocity
Definition at line 67 of file tlm-global.c.
Referenced by tlm_grid_init(), and tlm_md_init().
FILE* g_tlm_waves_plt_f
Definition at line 5 of file tlm-global.c.
Referenced by tlm_md_init().
int g_tlm_z_max
Definition at line 47 of file tlm-global.c.
Referenced by _tlm_init(), and tlm_xml().
int** g_tlm_z_values
Definition at line 46 of file tlm-global.c.
Referenced by tlm_getelevation(), and tlm_grid_init().
tw_lpid nlp_per_pe
Definition at line 22 of file olsr-driver.c.
Referenced by _rm_map(), final(), main(), mapping(), mem_map(), olsr_grid_mapping(), pcs_grid_mapping(), pm_map(), qhold_init(), rm_initialize(), sa_master_event(), and traffic_grid_mapping().
tw_lpid ntlm_lp_per_pe
Definition at line 16 of file tlm-global.c.
Referenced by tlm_getcell(), and tlm_md_init().