ROSS: rnf/modules/physical/tlm/tlm-cell.c File Reference
tlm-cell.c File Reference
#include <tlm.h>
Macros
#define PLOT 0
#define VERIFY_RM_CELL 0
Functions
void tlm_cell_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_cell_scatter (tlm_state *state, tlm_message *m, tw_bf *bf, tw_lp *lp)
void tlm_cell_gather (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
Macro Definition Documentation
#define PLOT 0
Definition at line 3 of file tlm-cell.c.
#define VERIFY_RM_CELL 0
Definition at line 4 of file tlm-cell.c.
Function Documentation
void tlm_cell_gather (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 130 of file tlm-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_message::displacement, tlm_state::displacements, g_tlm_scatter_ts, tw_lp::gid, tlm_message::id, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_event::recv_ts, RM_SCATTER, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and tlm_message::type.
Referenced by tlm_cell_handler().
void tlm_cell_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 14 of file tlm-cell.c.
References RM_GATHER, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_state::stats, tlm_cell_gather(), tlm_cell_scatter(), tw_error(), TW_LOC, and tlm_message::type.
Referenced by _tlm_event_handler().
void tlm_cell_scatter (tlm_state * state, tlm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 50 of file tlm-cell.c.
References d, tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_message::displacement, tlm_state::displacements, g_tlm_scatter_ts, g_tlm_spatial_coeff, g_tlm_spatial_dir, g_tlm_spatial_ground_coeff, g_tlm_spatial_offset_ts, g_tlm_wave_loss_coeff, g_tlm_wave_threshold, tw_lp::gid, tlm_message::id, tw_lp::id, tw_pe::id, tlm_state::nbrs, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_event::recv_ts, RM_GATHER, tlm_getlocation(), tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tlm_message::type, and tlm_pe::wave_log.
Referenced by tlm_cell_handler().