ROSS: rnf/modules/physical/tlm/tlm-rc-cell.c File Reference
tlm-rc-cell.c File Reference
#include <tlm.h>
Macros
#define VERIFY_RM_CELL 0
Functions
void tlm_rc_cell_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_rc_scatter (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void tlm_rc_gather (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
Macro Definition Documentation
#define VERIFY_RM_CELL 0
Definition at line 3 of file tlm-rc-cell.c.
Referenced by tlm_rc_scatter().
Function Documentation
void tlm_rc_cell_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 12 of file tlm-rc-cell.c.
References RM_GATHER, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_state::stats, tlm_rc_gather(), tlm_rc_scatter(), tw_error(), TW_LOC, and tlm_message::type.
Referenced by _tlm_rc_event_handler().
void tlm_rc_gather (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 53 of file tlm-rc-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_state::displacements, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, and tw_now().
Referenced by tlm_rc_cell_handler().
void tlm_rc_scatter (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 37 of file tlm-rc-cell.c.
References tlm_message::direction, tlm_message::disp, tlm_message::displ, tlm_state::displacement, tlm_state::displacements, g_tlm_spatial_dir, tw_lp::id, tw_pe::id, tlm_state::next_time, tw_lp::pe, tlm_message::prev_time, tw_now(), and VERIFY_RM_CELL.
Referenced by tlm_rc_cell_handler().