ROSS: ross/models/tlm/rm/rm-particle.c File Reference
rm-particle.c File Reference
#include <rm.h>
Macros
#define VERIFY_PARTICLE 1
Functions
tw_event * rm_particle_send (tw_lpid gid, tw_stime offset, tw_lp *src_lp)
void rm_particle_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_rc_particle_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
Macro Definition Documentation
#define VERIFY_PARTICLE 1
Definition at line 3 of file rm-particle.c.
Function Documentation
void rm_particle_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 40 of file rm-particle.c.
References tw_bf::c0, tw_bf::c1, g_rm_fd, g_rm_parts_plt_f, tw_lp::id, p, rm_state::particles, rm_getlocation(), rm_proximity_send(), tw_error(), TW_LOC, tw_memory_free(), tw_memoryq_pop(), tw_memoryq_push(), tw_now(), and rm_particle::user_lp.
Referenced by _rm_event_handler().
tw_event* rm_particle_send (tw_lpid gid, tw_stime offset, tw_lp * src_lp)
Definition at line 9 of file rm-particle.c.
References g_rm_fd, p, RM_PARTICLE, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_memory_alloc(), and rm_message::type.
Referenced by rm_move().
void rm_rc_particle_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 112 of file rm-particle.c.
References tw_bf::c0, tw_bf::c1, g_rm_fd, rm_state::particles, tw_memory_free_rc(), tw_memoryq_pop(), tw_memoryq_push(), and tw_now().
Referenced by _rm_rc_event_handler().