ROSS: ross/models/tlm/rm/rm-extern.h File Reference
rm-extern.h File Reference
Functions
void rm_pe_init (tw_pe *me)
void rm_pe_post_init (tw_pe *me)
void rm_pe_gvt (tw_pe *me)
void rm_pe_final (tw_pe *me)
void rm_cell_handler (rm_state *, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_cell_gather (rm_state *, tw_bf *bf, rm_message *, tw_lp *lp)
void rm_cell_scatter (rm_state *, rm_message *, tw_bf *bf, tw_lp *lp)
void rm_rc_cell_handler (rm_state *, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_rc_scatter (rm_state *, tw_bf *bf, rm_message *, tw_lp *)
void rm_rc_gather (rm_state *, tw_bf *bf, rm_message *, tw_lp *)
tw_event * rm_timer_cancel (tw_event *t, tw_lp *lp)
tw_event * rm_timer_start (tw_event *t, int dim, tw_stime ts, tw_lp *lp)
void rm_init (int *argc, char ***argv)
void rm_setup_options (int argc, char **argv)
void rm_initialize_terrain (double *grid, double *spacing, int)
int rm_grid_initialize (char *filename)
void rm_wave_initiate (double *position, double signal, tw_lp *lp)
void rm_rc_wave_initiate (double *position, double signal)
double rm_move (double, double[], double[], tw_lp *lp)
double rm_move2 (double, double[], double[], tw_lp *lp)
void rm_rc_move (tw_lp *lp)
int rm_initialize (tw_petype *, tw_lptype *, tw_peid, tw_kpid, tw_lpid, size_t)
void rm_run (char **argv)
void rm_end (void)
tw_peid _rm_map (tw_lpid gid)
void _rm_init (rm_state *, tw_lp *lp)
void _rm_event_handler (rm_state *, tw_bf *, rm_message *, tw_lp *lp)
void _rm_rc_event_handler (rm_state *, tw_bf *, rm_message *, tw_lp *lp)
void _rm_final (rm_state *, tw_lp *lp)
tw_event * rm_particle_send (tw_lpid gid, tw_stime, tw_lp *)
void rm_particle_handler (rm_state *, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_rc_particle_handler (rm_state *, tw_bf *, rm_message *m, tw_lp *lp)
void rm_proximity_send (rm_state *, tw_memory *p, tw_memory *b, tw_lp *lp)
double rm_getelevation (double *p)
tw_lpid rm_getcell (double *position)
double * rm_getlocation (tw_lp *lp)
Variables
FILE * g_rm_waves_plt_f
FILE * g_rm_nodes_plt_f
FILE * g_rm_parts_plt_f
rm_statistics * g_rm_stats
tw_lpid nlp_per_pe
tw_lpid nrmlp_per_pe
tw_pe g_rm_pe
unsigned int * g_rm_spatial_grid
unsigned int * g_rm_spatial_grid_i
double * g_rm_spatial_d
unsigned int g_rm_spatial_dim
unsigned int g_rm_spatial_dir
unsigned int g_rm_spatial_offset
tw_stime * g_rm_spatial_offset_ts
tw_stime g_rm_scatter_ts
double g_rm_spatial_coeff
double g_rm_spatial_ground_coeff
int ** g_rm_z_values
int g_rm_z_max
char g_rm_spatial_scenario_fn []
char g_rm_spatial_terrain_fn []
char g_rm_spatial_urban_fn []
char g_rm_spatial_vegatation_fn []
double g_rm_wave_threshold
double g_rm_wave_attenuation
double g_rm_wave_loss_coeff
double g_rm_wave_velocity
tw_fd g_rm_fd
Function Documentation
void _rm_event_handler (rm_state * , tw_bf * , rm_message * , tw_lp * lp)
Definition at line 147 of file rm.c.
References tw_lp::gid, rm_message::id, rm_cell_handler(), RM_GATHER, RM_PARTICLE, rm_particle_handler(), RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_nparticles, rm_state::stats, tw_error(), TW_LOC, tw_now(), and rm_message::type.
void _rm_final (rm_state * , tw_lp * lp)
Definition at line 205 of file rm.c.
References g_rm_stats, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_statistics::s_nparticles, and rm_state::stats.
void _rm_init (rm_state * , tw_lp * lp)
Definition at line 19 of file rm.c.
References rm_state::displacements, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_dir, g_rm_spatial_grid, g_rm_z_max, g_tw_mynode, tw_lp::gid, rm_state::nbrs, rm_state::particles, rm_getcell(), rm_getelevation(), rm_getlocation(), rm_state::stats, tw_calloc(), tw_error(), TW_LOC, and tw_memoryq_init().
tw_peid _rm_map (tw_lpid gid)
Definition at line 4 of file rm.c.
References nlp_per_pe.
void _rm_rc_event_handler (rm_state * , tw_bf * , rm_message * , tw_lp * lp)
Definition at line 179 of file rm.c.
References RM_GATHER, RM_PARTICLE, rm_rc_cell_handler(), rm_rc_particle_handler(), RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_nparticles, rm_state::stats, tw_error(), TW_LOC, and rm_message::type.
void rm_cell_gather (rm_state * , tw_bf * bf, rm_message * , tw_lp * lp)
Definition at line 128 of file rm-cell.c.
References rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_message::displacement, rm_state::displacements, g_rm_scatter_ts, tw_lp::gid, rm_message::id, tw_lp::id, tw_pe::id, rm_state::next_time, tw_lp::pe, rm_message::prev_time, tw_event::recv_ts, RM_SCATTER, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and rm_message::type.
Referenced by rm_cell_handler().
void rm_cell_handler (rm_state * , tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 14 of file rm-cell.c.
References rm_cell_gather(), rm_cell_scatter(), RM_GATHER, RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_state::stats, tw_error(), TW_LOC, and rm_message::type.
Referenced by _rm_event_handler().
void rm_cell_scatter (rm_state * , rm_message * , tw_bf * bf, tw_lp * lp)
Definition at line 49 of file rm-cell.c.
References d, rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_message::displacement, rm_state::displacements, g_rm_scatter_ts, g_rm_spatial_coeff, g_rm_spatial_dir, g_rm_spatial_ground_coeff, g_rm_spatial_offset_ts, g_rm_wave_loss_coeff, g_rm_wave_threshold, tw_lp::gid, rm_message::id, tw_lp::id, tw_pe::id, rm_state::nbrs, rm_state::next_time, tw_lp::pe, rm_message::prev_time, tw_event::recv_ts, RM_GATHER, rm_getlocation(), tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), rm_message::type, and rm_pe::wave_log.
Referenced by rm_cell_handler().
void rm_end (void)
Definition at line 422 of file rm-interface.c.
References tw_end().
tw_lpid rm_getcell (double * position) inline
Definition at line 32 of file rm-helper.c.
References g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid_i, g_rm_spatial_offset, nrmlp_per_pe, and rm_getelevation().
double rm_getelevation (double * p) inline
Definition at line 7 of file rm-helper.c.
References g_rm_spatial_d, g_rm_spatial_grid, g_rm_z_values, g_tw_mynode, g_tw_npe, npe, and tw_nnodes().
double* rm_getlocation (tw_lp * lp) inline
Definition at line 76 of file rm-helper.c.
References _rm_map(), g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_grid_i, g_rm_spatial_offset, g_tw_mynode, tw_lp::gid, tw_lp::id, lpid, rm_getcell(), rm_getelevation(), tw_calloc(), tw_error(), tw_getlocal_lp(), and TW_LOC.
int rm_grid_initialize (char * filename)
void rm_init (int * argc, char *** argv)
Definition at line 43 of file rm-interface.c.
References g_rm_spatial_scenario_fn, g_rm_spatial_terrain_fn, g_rm_spatial_urban_fn, g_rm_spatial_vegatation_fn, g_tw_ts_end, tw_init(), and tw_opt_add().
int rm_initialize (tw_petype * , tw_lptype * , tw_peid , tw_kpid , tw_lpid , size_t)
Definition at line 249 of file rm-interface.c.
References g_rm_nodes_plt_f, g_rm_parts_plt_f, g_rm_pe, g_rm_spatial_coeff, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_dir, g_rm_spatial_grid_i, g_rm_spatial_ground_coeff, g_rm_spatial_offset, g_rm_spatial_offset_ts, g_rm_stats, g_rm_wave_attenuation, g_rm_wave_loss_coeff, g_rm_wave_velocity, g_rm_waves_plt_f, g_tw_events_per_pe, g_tw_masternode, g_tw_mynode, g_tw_nlp, g_tw_npe, g_tw_pe, g_tw_rng_default, nlp_per_pe, nrmlp_per_pe, optimistic_memory, rm_grid_init(), rm_grid_terrain(), tw_lptype::state_sz, tw_calloc(), tw_define_lps(), tw_error(), TW_FALSE, TW_LOC, tw_lp_settype(), tw_nnodes(), tw_node_eq(), and tw_pe_settype().
void rm_initialize_terrain (double * grid, double * spacing, int)
Definition at line 27 of file rm-grid.c.
References g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_z_max, tw_calloc(), and TW_LOC.
double rm_move (double , double [], double [], tw_lp * lp)
Definition at line 121 of file rm-interface.c.
References rm_state::displacement, g_rm_nodes_plt_f, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, tw_lp::id, rm_getcell(), rm_getelevation(), rm_particle_send(), tw_error(), TW_LOC, and x.
double rm_move2 (double , double [], double [], tw_lp * lp)
Definition at line 103 of file rm-interface.c.
References tw_lp::gid, rm_pe::move_log, tw_lp::pe, and tw_now().
void rm_particle_handler (rm_state * , tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 40 of file rm-particle.c.
References tw_bf::c0, tw_bf::c1, g_rm_fd, g_rm_parts_plt_f, tw_lp::id, p, rm_state::particles, rm_getlocation(), rm_proximity_send(), tw_error(), TW_LOC, tw_memory_free(), tw_memoryq_pop(), tw_memoryq_push(), tw_now(), and rm_particle::user_lp.
tw_event* rm_particle_send (tw_lpid gid, tw_stime , tw_lp *)
Definition at line 9 of file rm-particle.c.
References g_rm_fd, p, RM_PARTICLE, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_memory_alloc(), and rm_message::type.
void rm_pe_final (tw_pe * me)
Definition at line 40 of file tlm-pe.c.
References tw_petype::final, g_rm_pe, g_rm_stats, g_tw_masternode, rm_pe::move_log, rm_statistics::s_nparticles, tw_error(), TW_LOC, tw_pe::type, and rm_pe::wave_log.
void rm_pe_gvt (tw_pe * me)
Definition at line 35 of file tlm-pe.c.
void rm_pe_init (tw_pe * me)
Definition at line 5 of file tlm-pe.c.
References tw_pe::id, rm_pe::move_log, tw_calloc(), tw_error(), TW_LOC, tw_net_onnode(), and rm_pe::wave_log.
void rm_pe_post_init (tw_pe * me)
Definition at line 30 of file tlm-pe.c.
void rm_proximity_send (rm_state * , tw_memory * p, tw_memory * b, tw_lp * lp)
Definition at line 7 of file rm-proximity.c.
References tw_lp::gid, RM_PROXIMITY_LP, tw_event_data(), tw_event_new(), tw_event_send(), rm_message::type, and rm_particle::user_lp.
void rm_rc_cell_handler (rm_state * , tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 12 of file rc-rm-cell.c.
References RM_GATHER, rm_rc_gather(), rm_rc_scatter(), RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_state::stats, tw_error(), TW_LOC, and rm_message::type.
Referenced by _rm_rc_event_handler().
void rm_rc_gather (rm_state * , tw_bf * bf, rm_message * , tw_lp *)
Definition at line 53 of file rc-rm-cell.c.
References rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_state::displacements, tw_lp::id, tw_pe::id, rm_state::next_time, tw_lp::pe, rm_message::prev_time, and tw_now().
Referenced by rm_rc_cell_handler().
void rm_rc_move (tw_lp * lp)
Definition at line 234 of file rm-interface.c.
void rm_rc_particle_handler (rm_state * , tw_bf * , rm_message * m, tw_lp * lp)
Definition at line 112 of file rm-particle.c.
References tw_bf::c0, tw_bf::c1, g_rm_fd, rm_state::particles, tw_memory_free_rc(), tw_memoryq_pop(), tw_memoryq_push(), and tw_now().
void rm_rc_scatter (rm_state * , tw_bf * bf, rm_message * , tw_lp *)
Definition at line 37 of file rc-rm-cell.c.
References rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_state::displacements, g_rm_spatial_dir, tw_lp::id, tw_pe::id, rm_state::next_time, tw_lp::pe, rm_message::prev_time, tw_now(), and VERIFY_RM_CELL.
Referenced by rm_rc_cell_handler().
void rm_rc_wave_initiate (double * position, double signal)
void rm_run (char ** argv)
Definition at line 350 of file rm-interface.c.
References g_rm_scatter_ts, g_rm_spatial_coeff, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_offset_ts, g_rm_stats, g_rm_wave_loss_coeff, g_rm_wave_threshold, g_rm_wave_velocity, g_tw_masternode, g_tw_mynode, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_statistics::s_nparticles, tw_error(), TW_LOC, tw_node_eq(), and tw_run().
void rm_setup_options (int argc, char ** argv)
Definition at line 17 of file rm-setup.c.
References g_rm_spatial_scenario_fn, g_rm_spatial_terrain_fn, g_rm_spatial_urban_fn, g_rm_spatial_vegatation_fn, g_tw_ts_end, and tw_opt_add().
tw_event* rm_timer_cancel (tw_event * t, tw_lp * lp)
tw_event* rm_timer_start (tw_event * t, int dim, tw_stime ts, tw_lp * lp)
void rm_wave_initiate (double * position, double signal, tw_lp * lp)
Definition at line 78 of file rm-interface.c.
References rm_message::displacement, g_rm_scatter_ts, tw_lp::gid, rm_message::id, tw_lp::id, rm_getcell(), rm_getelevation(), RM_WAVE_INIT, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, and rm_message::type.
Variable Documentation
tw_fd g_rm_fd
Definition at line 58 of file rm-global.c.
FILE* g_rm_nodes_plt_f
Definition at line 4 of file rm-global.c.
FILE* g_rm_parts_plt_f
Definition at line 5 of file rm-global.c.
tw_pe g_rm_pe
Definition at line 20 of file rm-global.c.
tw_stime g_rm_scatter_ts
Definition at line 47 of file rm-global.c.
double g_rm_spatial_coeff
Definition at line 48 of file rm-global.c.
double* g_rm_spatial_d
Definition at line 42 of file rm-global.c.
unsigned int g_rm_spatial_dim
Definition at line 43 of file rm-global.c.
unsigned int g_rm_spatial_dir
Definition at line 44 of file rm-global.c.
unsigned int* g_rm_spatial_grid
Definition at line 40 of file rm-global.c.
unsigned int* g_rm_spatial_grid_i
Definition at line 41 of file rm-global.c.
double g_rm_spatial_ground_coeff
Definition at line 49 of file rm-global.c.
unsigned int g_rm_spatial_offset
Definition at line 45 of file rm-global.c.
tw_stime* g_rm_spatial_offset_ts
Definition at line 46 of file rm-global.c.
char g_rm_spatial_scenario_fn[]
Definition at line 53 of file rm-global.c.
char g_rm_spatial_terrain_fn[]
Definition at line 54 of file rm-global.c.
char g_rm_spatial_urban_fn[]
Definition at line 55 of file rm-global.c.
char g_rm_spatial_vegatation_fn[]
Definition at line 56 of file rm-global.c.
rm_statistics* g_rm_stats
Definition at line 7 of file rm-global.c.
double g_rm_wave_attenuation
Definition at line 71 of file rm-global.c.
double g_rm_wave_loss_coeff
Definition at line 72 of file rm-global.c.
double g_rm_wave_threshold
Definition at line 70 of file rm-global.c.
double g_rm_wave_velocity
Definition at line 73 of file rm-global.c.
FILE* g_rm_waves_plt_f
Definition at line 3 of file rm-global.c.
int g_rm_z_max
Definition at line 51 of file rm-global.c.
int** g_rm_z_values
Definition at line 50 of file rm-global.c.
tw_lpid nlp_per_pe
Definition at line 22 of file olsr-driver.c.
tw_lpid nrmlp_per_pe
Definition at line 18 of file rm-global.c.