ROSS: ross/models/tlm/pm/pm-node.c File Reference
pm-node.c File Reference
#include <pm.h>
Functions
int off_grid (double *p)
void change_direction (pm_state *state, pm_message *m, tw_bf *bf, tw_lp *lp)
void new_location (pm_state *state, tw_bf *bf, tw_lp *lp)
void rc_new_location (pm_state *state, tw_bf *bf, tw_lp *lp)
void pm_move (pm_state *state, pm_message *m, tw_bf *bf, tw_lp *lp)
void pm_rc_move (pm_state *state, pm_message *m, tw_bf *bf, tw_lp *lp)
Function Documentation
void change_direction (pm_state * state, pm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 25 of file pm-node.c.
References pm_state::change_dir, g_pm_distr_sd, g_pm_mu, g_rm_spatial_d, tw_lp::rng, pm_state::theta, tw_error(), TW_LOC, tw_now(), tw_rand_integer(), and pm_state::velocity.
void new_location (pm_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 88 of file pm-node.c.
References pm_state::position, and pm_state::velocity.
int off_grid (double * p)
Definition at line 4 of file pm-node.c.
References g_rm_spatial_d, and g_rm_spatial_grid.
void pm_move (pm_state * state, pm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 105 of file pm-node.c.
References pm_state::change_dir, pm_message::change_dir, change_direction(), pm_message::from, tw_lp::gid, tw_lp::id, new_location(), off_grid(), PM_TIMESTEP, pm_state::position, pm_state::range, rc_new_location(), rm_getelevation(), rm_move2(), tw_lp::rng, pm_state::theta, pm_message::theta, tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_printf(), tw_rand_exponential(), pm_message::type, pm_state::velocity, pm_message::x_pos, and pm_message::y_pos.
Referenced by pm_event_handler().
void pm_rc_move (pm_state * state, pm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 163 of file pm-node.c.
References pm_state::change_dir, pm_message::change_dir, pm_state::position, tw_lp::rng, pm_state::theta, pm_message::theta, tw_rand_reverse_unif, pm_message::x_pos, and pm_message::y_pos.
Referenced by pm_rc_event_handler().
void rc_new_location (pm_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 95 of file pm-node.c.
References pm_state::position, and pm_state::velocity.