ROSS: ross/models/tlm/rm/rm-interface.c File Reference
rm-interface.c File Reference
#include <rm.h>
Macros
#define PLOT 0
#define RM_RANGE_PARTICLES 1
#define TOP 1
#define RIGHT 1
#define BOTTOM 1
#define LEFT 1
Functions
void rm_init (int *argc, char ***argv)
void rm_wave_initiate (double *position, double signal, tw_lp *lp)
double rm_move2 (double range, double position[], double velocity[], tw_lp *lp)
double rm_move (double range, double position[], double velocity[], tw_lp *lp)
void rm_rc_move (tw_lp *lp)
int rm_initialize (tw_petype *ptypes, tw_lptype *types, tw_peid npe, tw_kpid nkp, tw_lpid nradios, size_t msg_sz)
void rm_run (char **argv)
void rm_end (void)
Variables
tw_petype rm_pes []
tw_lptype rm_lps []
static unsigned int optimistic_memory = 0
static const tw_optdef rm_options []
Macro Definition Documentation
#define BOTTOM 1
Definition at line 8 of file rm-interface.c.
#define LEFT 1
Definition at line 9 of file rm-interface.c.
#define PLOT 0
Definition at line 3 of file rm-interface.c.
#define RIGHT 1
Definition at line 7 of file rm-interface.c.
#define RM_RANGE_PARTICLES 1
Definition at line 5 of file rm-interface.c.
#define TOP 1
Definition at line 6 of file rm-interface.c.
Function Documentation
void rm_end (void)
Definition at line 423 of file rm-interface.c.
References tw_end().
Referenced by main().
void rm_init (int * argc, char *** argv)
Definition at line 44 of file rm-interface.c.
References g_rm_spatial_scenario_fn, g_rm_spatial_terrain_fn, g_rm_spatial_urban_fn, g_rm_spatial_vegatation_fn, g_tw_ts_end, tw_init(), and tw_opt_add().
Referenced by main().
int rm_initialize (tw_petype * ptypes, tw_lptype * types, tw_peid npe, tw_kpid nkp, tw_lpid nradios, size_t msg_sz)
Definition at line 250 of file rm-interface.c.
References g_rm_nodes_plt_f, g_rm_parts_plt_f, g_rm_pe, g_rm_spatial_coeff, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_dir, g_rm_spatial_grid_i, g_rm_spatial_ground_coeff, g_rm_spatial_offset, g_rm_spatial_offset_ts, g_rm_stats, g_rm_wave_attenuation, g_rm_wave_loss_coeff, g_rm_wave_velocity, g_rm_waves_plt_f, g_tw_events_per_pe, g_tw_masternode, g_tw_mynode, g_tw_nlp, g_tw_npe, g_tw_pe, g_tw_rng_default, nlp_per_pe, nrmlp_per_pe, optimistic_memory, rm_grid_init(), rm_grid_terrain(), tw_lptype::state_sz, tw_calloc(), tw_define_lps(), tw_error(), TW_FALSE, TW_LOC, tw_lp_settype(), tw_nnodes(), tw_node_eq(), and tw_pe_settype().
Referenced by main().
double rm_move (double range, double position[], double velocity[], tw_lp * lp)
Definition at line 122 of file rm-interface.c.
References rm_state::displacement, g_rm_nodes_plt_f, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, tw_lp::id, rm_getcell(), rm_getelevation(), rm_particle_send(), tw_error(), TW_LOC, and x.
double rm_move2 (double range, double position[], double velocity[], tw_lp * lp)
Definition at line 104 of file rm-interface.c.
References tw_lp::gid, rm_pe::move_log, tw_lp::pe, and tw_now().
Referenced by pm_init(), and pm_move().
void rm_rc_move (tw_lp * lp)
Definition at line 235 of file rm-interface.c.
void rm_run (char ** argv)
Definition at line 351 of file rm-interface.c.
References g_rm_scatter_ts, g_rm_spatial_coeff, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_offset_ts, g_rm_stats, g_rm_wave_loss_coeff, g_rm_wave_threshold, g_rm_wave_velocity, g_tw_masternode, g_tw_mynode, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_statistics::s_nparticles, tw_error(), TW_LOC, tw_node_eq(), and tw_run().
Referenced by main().
void rm_wave_initiate (double * position, double signal, tw_lp * lp)
Definition at line 79 of file rm-interface.c.
References rm_message::displacement, g_rm_scatter_ts, tw_lp::gid, rm_message::id, tw_lp::id, rm_getcell(), rm_getelevation(), RM_WAVE_INIT, tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, and rm_message::type.
Referenced by pm_event_handler().
Variable Documentation
unsigned int optimistic_memory = 0 static
Definition at line 33 of file rm-interface.c.
tw_lptype rm_lps[]
Initial value:
= {
{
         (init_f) _rm_init,
         (event_f) _rm_event_handler,
         (revent_f) _rm_rc_event_handler,
         (final_f) _rm_final,
         (map_f) _rm_map,
         sizeof(rm_state)},
        {0},
}
Definition at line 22 of file rm-interface.c.
const tw_optdef rm_options[] static
Initial value:
=
{
        TWOPT_UINT("memory", optimistic_memory, "Additional memory buffers"),
        TWOPT_STIME("threshold", g_rm_wave_threshold, "Wave propagation threshold"),
        TWOPT_CHAR("scenario", g_rm_spatial_scenario_fn, "Path to scenario files"),
}
Definition at line 35 of file rm-interface.c.
tw_petype rm_pes[]
Initial value:
= {
        {
                (pe_init_f) rm_pe_init,
                (pe_init_f) rm_pe_post_init,
                (pe_gvt_f) rm_pe_gvt,
                (pe_final_f) rm_pe_final,
                (pe_periodic_f) 0
        },
        {0},
}
Definition at line 11 of file rm-interface.c.