ROSS: ross/models/tlm/pm/pm-extern.h File Reference
pm-extern.h File Reference
Functions
void pm_pe_init (tw_pe *me)
void pm_pe_post_init (tw_pe *me)
void pm_pe_gvt (tw_pe *me)
void pm_pe_final (tw_pe *me)
void pm_init_scenario ()
void pm_init (pm_state *, tw_lp *)
void pm_event_handler (pm_state *, tw_bf *, pm_message *, tw_lp *)
void pm_rc_event_handler (pm_state *, tw_bf *, pm_message *, tw_lp *)
void pm_final (pm_state *, tw_lp *)
void pm_stats_print ()
pm_connection * pm_connect (pm_state *, tw_bf *, pm_message *, tw_lp *, int blk)
pm_connection * pm_disconnect (pm_state *, tw_bf *, pm_message *, tw_lp *, int)
void pm_move (pm_state *state, pm_message *m, tw_bf *bf, tw_lp *)
void pm_rc_move (pm_state *, pm_message *, tw_bf *, tw_lp *)
double pm_distance (double x0, double y0, double x1, double y1)
double pm_intercept (double x, double y, double slope)
double pm_slope (double x0, double y0, double x1, double y1)
void pm_sort (double *p)
Variables
int the_one
unsigned int g_pm_dimensions
unsigned int g_pm_nnodes
double g_pm_runtime
pm_statistics * g_pm_stats
int g_pm_plot
FILE * g_pm_position_f
unsigned int * g_pm_position_x
unsigned int * g_pm_position_y
unsigned int * g_pm_ids
unsigned int g_pm_mu
unsigned int g_pm_distr_sd
tw_stime percent_wave
char run_id [1024]
double grid [3]
double spacing [3]
Function Documentation
pm_connection* pm_connect (pm_state * , tw_bf * , pm_message * , tw_lp * , int blk)
pm_connection* pm_disconnect (pm_state * , tw_bf * , pm_message * , tw_lp * , int)
double pm_distance (double x0, double y0, double x1, double y1) inline
Definition at line 25 of file pm-helper.c.
void pm_event_handler (pm_state * , tw_bf * , pm_message * , tw_lp *)
Definition at line 98 of file pm.c.
References g_tw_mynode, tw_lp::gid, tw_lp::id, percent_wave, pm_move(), PM_TIMESTEP, pm_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, rm_wave_initiate(), tw_lp::rng, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, pm_state::stats, pm_state::transmit, tw_error(), TW_LOC, tw_rand_unif, and pm_message::type.
void pm_final (pm_state * , tw_lp *)
Definition at line 172 of file pm.c.
References g_pm_stats, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, and pm_state::stats.
void pm_init (pm_state * , tw_lp *)
Definition at line 21 of file pm.c.
References pm_state::frequency, g_pm_distr_sd, g_pm_mu, g_rm_spatial_dim, g_tw_mynode, tw_lp::gid, grid, PM_TIMESTEP, pm_state::position, pm_state::prev_time, pm_state::range, rm_getelevation(), rm_move2(), tw_lp::rng, spacing, pm_state::stats, the_one, pm_state::transmit, tw_calloc(), tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), pm_message::type, pm_state::velocity, and x.
void pm_init_scenario ()
Definition at line 68 of file pm-init.c.
References g_rm_spatial_scenario_fn, init_nodes(), tw_error(), and TW_LOC.
double pm_intercept (double x, double y, double slope) inline
Definition at line 35 of file pm-helper.c.
void pm_move (pm_state * state, pm_message * m, tw_bf * bf, tw_lp *)
Definition at line 105 of file pm-node.c.
References pm_state::change_dir, pm_message::change_dir, change_direction(), pm_message::from, tw_lp::gid, tw_lp::id, new_location(), off_grid(), PM_TIMESTEP, pm_state::position, pm_state::range, rc_new_location(), rm_getelevation(), rm_move2(), tw_lp::rng, pm_state::theta, pm_message::theta, tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_now(), tw_printf(), tw_rand_exponential(), pm_message::type, pm_state::velocity, pm_message::x_pos, and pm_message::y_pos.
void pm_pe_final (tw_pe * me)
Definition at line 8 of file pm-pe.c.
References g_pm_stats, g_rm_stats, g_tw_masternode, g_tw_mynode, pm_statistics::s_move_ev, tw_error(), and TW_LOC.
void pm_pe_gvt (tw_pe * me)
Definition at line 5 of file pm-pe.c.
void pm_pe_init (tw_pe * me)
Definition at line 3 of file pm-pe.c.
void pm_pe_post_init (tw_pe * me)
Definition at line 4 of file pm-pe.c.
void pm_rc_event_handler (pm_state * , tw_bf * , pm_message * , tw_lp *)
Definition at line 141 of file pm.c.
References pm_rc_move(), PM_TIMESTEP, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, pm_state::stats, tw_error(), TW_LOC, tw_rand_reverse_unif, and pm_message::type.
void pm_rc_move (pm_state * , pm_message * , tw_bf * , tw_lp *)
Definition at line 163 of file pm-node.c.
References pm_state::change_dir, pm_message::change_dir, pm_state::position, tw_lp::rng, pm_state::theta, pm_message::theta, tw_rand_reverse_unif, pm_message::x_pos, and pm_message::y_pos.
double pm_slope (double x0, double y0, double x1, double y1) inline
Definition at line 45 of file pm-helper.c.
void pm_sort (double * p) inline
Definition at line 8 of file pm-helper.c.
void pm_stats_print ()
Definition at line 4 of file pm-stats.c.
References g_pm_nnodes, g_pm_stats, g_tw_mynode, g_tw_npe, percent_wave, pm_statistics::s_move_ev, pm_statistics::s_nconnect, pm_statistics::s_ndisconnect, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, and tw_nnodes().
Variable Documentation
unsigned int g_pm_dimensions
Definition at line 7 of file pm-global.c.
unsigned int g_pm_distr_sd
Definition at line 29 of file pm-global.c.
unsigned int* g_pm_ids
Definition at line 25 of file pm-global.c.
unsigned int g_pm_mu
Definition at line 28 of file pm-global.c.
unsigned int g_pm_nnodes
Definition at line 14 of file pm-global.c.
int g_pm_plot
Definition at line 15 of file pm-global.c.
FILE* g_pm_position_f
Definition at line 22 of file pm-global.c.
unsigned int* g_pm_position_x
Definition at line 23 of file pm-global.c.
unsigned int* g_pm_position_y
Definition at line 24 of file pm-global.c.
double g_pm_runtime
Definition at line 13 of file pm-global.c.
pm_statistics* g_pm_stats
Definition at line 17 of file pm-global.c.
double grid[3]
Definition at line 40 of file pm-global.c.
tw_stime percent_wave
Definition at line 29 of file rw-global.c.
char run_id[1024]
Definition at line 32 of file pm-global.c.
double spacing[3]
Definition at line 41 of file pm-global.c.
int the_one
Definition at line 2 of file pm-global.c.