ROSS: ross/models/tlm/rm/rm-helper.c File Reference
rm-helper.c File Reference
#include <rm.h>
Functions
double rm_getelevation (double *p)
tw_lpid rm_getcell (double *position)
double * rm_getlocation (tw_lp *lp)
Variables
static tw_lpid lpid
Function Documentation
tw_lpid rm_getcell (double * position) inline
Definition at line 32 of file rm-helper.c.
References g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid_i, g_rm_spatial_offset, nrmlp_per_pe, and rm_getelevation().
Referenced by _rm_init(), rm_getlocation(), rm_move(), and rm_wave_initiate().
double rm_getelevation (double * p) inline
Definition at line 7 of file rm-helper.c.
References g_rm_spatial_d, g_rm_spatial_grid, g_rm_z_values, g_tw_mynode, g_tw_npe, npe, and tw_nnodes().
Referenced by _rm_init(), pm_init(), pm_move(), rm_getcell(), rm_getlocation(), rm_move(), and rm_wave_initiate().
double* rm_getlocation (tw_lp * lp) inline
Definition at line 76 of file rm-helper.c.
References _rm_map(), g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_grid_i, g_rm_spatial_offset, g_tw_mynode, tw_lp::gid, tw_lp::id, lpid, rm_getcell(), rm_getelevation(), tw_calloc(), tw_error(), tw_getlocal_lp(), and TW_LOC.
Referenced by _rm_init(), rm_cell_scatter(), and rm_particle_handler().
Variable Documentation
tw_lpid lpid static
Definition at line 3 of file rm-helper.c.
Referenced by rm_getlocation().