ROSS: ross/models/tlm/pm/pm-init.c File Reference
pm-init.c File Reference
#include <pm.h>
Functions
void init_nodes ()
void init_topology ()
void pm_init_scenario ()
Function Documentation
void init_nodes ()
Definition at line 4 of file pm-init.c.
References f, g_pm_ids, g_pm_nnodes, g_pm_position_x, g_pm_position_y, g_rm_spatial_scenario_fn, tw_calloc(), tw_error(), TW_LOC, tw_printf(), and x.
void init_topology ()
Definition at line 63 of file pm-init.c.
void pm_init_scenario ()
Definition at line 68 of file pm-init.c.
References g_rm_spatial_scenario_fn, init_nodes(), tw_error(), and TW_LOC.
Referenced by main().