ROSS: ross/models/tlm/rm/rm-proximity.c File Reference
rm-proximity.c File Reference
#include <rm.h>
Functions
void rm_proximity_send (rm_state *state, tw_memory *p, tw_memory *b, tw_lp *lp)
Function Documentation
void rm_proximity_send (rm_state * state, tw_memory * p, tw_memory * b, tw_lp * lp)
Definition at line 7 of file rm-proximity.c.
References tw_lp::gid, RM_PROXIMITY_LP, tw_event_data(), tw_event_new(), tw_event_send(), rm_message::type, and rm_particle::user_lp.
Referenced by rm_particle_handler().