ROSS: rnf/modules/physical/tlm/tlm.c File Reference
tlm.c File Reference
#include <tlm.h>
Functions
void _tlm_init (tlm_state *state, tw_lp *lp)
void state_copy (tlm_state *a, tlm_state *b, double *d)
void _tlm_event_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void _tlm_rc_event_handler (tlm_state *state, tw_bf *bf, tlm_message *m, tw_lp *lp)
void _tlm_final (tlm_state *state, tw_lp *lp)
Function Documentation
void _tlm_event_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 141 of file tlm.c.
References RM_GATHER, RM_PARTICLE, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_nparticles, tlm_state::stats, tlm_cell_handler(), tlm_particle_handler(), tw_error(), TW_LOC, and tlm_message::type.
void _tlm_final (tlm_state * state, tw_lp * lp)
Definition at line 197 of file tlm.c.
References g_tlm_stats, tlm_statistics::s_ncell_gather, tlm_statistics::s_ncell_initiate, tlm_statistics::s_ncell_scatter, tlm_statistics::s_nparticles, and tlm_state::stats.
void _tlm_init (tlm_state * state, tw_lp * lp)
Definition at line 13 of file tlm.c.
References tlm_state::displacements, g_tlm_spatial_d, g_tlm_spatial_dim, g_tlm_spatial_dir, g_tlm_spatial_grid, g_tlm_z_max, g_tw_mynode, tw_lp::gid, tlm_state::nbrs, tlm_state::particles, tlm_state::stats, tlm_getcell(), tlm_getelevation(), tlm_getlocation(), tw_calloc(), tw_error(), TW_LOC, and tw_memoryq_init().
void _tlm_rc_event_handler (tlm_state * state, tw_bf * bf, tlm_message * m, tw_lp * lp)
Definition at line 171 of file tlm.c.
References RM_GATHER, RM_PARTICLE, RM_SCATTER, RM_WAVE_INIT, tlm_statistics::s_nparticles, tlm_state::stats, tlm_rc_cell_handler(), tlm_rc_particle_handler(), tw_error(), TW_LOC, and tlm_message::type.
void state_copy (tlm_state * a, tlm_state * b, double * d)
Definition at line 129 of file tlm.c.
References tlm_state::displacement, tlm_state::displacements, g_tlm_spatial_dir, and tlm_state::next_time.