ROSS: ross/models/tlm/rm/rm-grid.c File Reference
rm-grid.c File Reference
#include <rm.h>
Functions
void rm_initialize_terrain (double *grid, double *spacing, int ndim)
void rm_grid_terrain ()
tw_lpid rm_grid_init ()
Function Documentation
tw_lpid rm_grid_init ()
Definition at line 141 of file rm-grid.c.
References g_rm_scatter_ts, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_grid_i, g_rm_spatial_offset_ts, g_rm_wave_velocity, min, nlp, tw_error(), and TW_LOC.
void rm_grid_terrain ()
Definition at line 48 of file rm-grid.c.
References f, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_spatial_terrain_fn, g_rm_z_values, g_tw_mynode, g_tw_npe, npe, tw_calloc(), tw_error(), TW_LOC, tw_nnodes(), and x.
void rm_initialize_terrain (double * grid, double * spacing, int ndim)
Definition at line 27 of file rm-grid.c.
References g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_grid, g_rm_z_max, tw_calloc(), and TW_LOC.
Referenced by main().