ROSS: ross/models/tlm/rm/rm-pe.c File Reference
rm-pe.c File Reference
#include <rm.h>
Macros
#define PLOT 0
Functions
void rm_pe_init (tw_pe *pe)
void rm_pe_post_init (tw_pe *pe)
void rm_pe_gvt (tw_pe *pe)
void rm_pe_final (tw_pe *pe)
Macro Definition Documentation
#define PLOT 0
Definition at line 3 of file rm-pe.c.
Function Documentation
void rm_pe_final (tw_pe * pe)
Definition at line 41 of file rm-pe.c.
References tw_petype::final, g_rm_pe, g_rm_stats, g_tw_masternode, rm_pe::move_log, rm_statistics::s_nparticles, tw_error(), TW_LOC, tw_pe::type, and rm_pe::wave_log.
void rm_pe_gvt (tw_pe * pe)
Definition at line 36 of file rm-pe.c.
void rm_pe_init (tw_pe * pe)
Definition at line 6 of file rm-pe.c.
References tw_pe::id, rm_pe::move_log, tw_calloc(), tw_error(), TW_LOC, tw_net_onnode(), and rm_pe::wave_log.
void rm_pe_post_init (tw_pe * pe)
Definition at line 31 of file rm-pe.c.