ROSS: ross/models/tlm/rm/rm-cell.c File Reference
rm-cell.c File Reference
#include <rm.h>
Macros
#define PLOT 0
#define VERIFY_RM_CELL 0
Functions
void rm_cell_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void rm_cell_scatter (rm_state *state, rm_message *m, tw_bf *bf, tw_lp *lp)
void rm_cell_gather (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
Macro Definition Documentation
#define PLOT 0
Definition at line 3 of file rm-cell.c.
#define VERIFY_RM_CELL 0
Definition at line 4 of file rm-cell.c.
Function Documentation
void rm_cell_gather (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 128 of file rm-cell.c.
References rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_message::displacement, rm_state::displacements, g_rm_scatter_ts, tw_lp::gid, rm_message::id, tw_lp::id, tw_pe::id, rm_state::next_time, tw_lp::pe, rm_message::prev_time, tw_event::recv_ts, RM_SCATTER, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and rm_message::type.
void rm_cell_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 14 of file rm-cell.c.
References rm_cell_gather(), rm_cell_scatter(), RM_GATHER, RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_state::stats, tw_error(), TW_LOC, and rm_message::type.
void rm_cell_scatter (rm_state * state, rm_message * m, tw_bf * bf, tw_lp * lp)
Definition at line 49 of file rm-cell.c.
References d, rm_message::direction, rm_message::disp, rm_message::displ, rm_state::displacement, rm_message::displacement, rm_state::displacements, g_rm_scatter_ts, g_rm_spatial_coeff, g_rm_spatial_dir, g_rm_spatial_ground_coeff, g_rm_spatial_offset_ts, g_rm_wave_loss_coeff, g_rm_wave_threshold, tw_lp::gid, rm_message::id, tw_lp::id, tw_pe::id, rm_state::nbrs, rm_state::next_time, tw_lp::pe, rm_message::prev_time, tw_event::recv_ts, RM_GATHER, rm_getlocation(), tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), rm_message::type, and rm_pe::wave_log.