ROSS: ross/models/tlm/pm/pm.c File Reference
pm.c File Reference
#include <pm.h>
Functions
tw_peid pm_map (tw_lpid gid)
void pm_init (pm_state *state, tw_lp *lp)
void pm_event_handler (pm_state *state, tw_bf *bf, pm_message *m, tw_lp *lp)
void pm_rc_event_handler (pm_state *state, tw_bf *bf, pm_message *m, tw_lp *lp)
void pm_final (pm_state *state, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_petype my_pes []
tw_lptype my_lps []
static const tw_optdef pm_options []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 221 of file pm.c.
References g_pm_dimensions, g_pm_nnodes, g_pm_stats, g_tw_nkp, g_tw_npe, grid, pm_init_scenario(), pm_stats_print(), rm_end(), rm_init(), rm_initialize(), rm_initialize_terrain(), rm_run(), spacing, tw_calloc(), tw_error(), TW_LOC, and tw_opt_add().
void pm_event_handler (pm_state * state, tw_bf * bf, pm_message * m, tw_lp * lp)
Definition at line 98 of file pm.c.
References g_tw_mynode, tw_lp::gid, tw_lp::id, percent_wave, pm_move(), PM_TIMESTEP, pm_state::position, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, rm_wave_initiate(), tw_lp::rng, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, pm_state::stats, pm_state::transmit, tw_error(), TW_LOC, tw_rand_unif, and pm_message::type.
void pm_final (pm_state * state, tw_lp * lp)
Definition at line 172 of file pm.c.
References g_pm_stats, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, and pm_state::stats.
void pm_init (pm_state * state, tw_lp * lp)
Definition at line 21 of file pm.c.
References pm_state::frequency, g_pm_distr_sd, g_pm_mu, g_rm_spatial_dim, g_tw_mynode, tw_lp::gid, grid, PM_TIMESTEP, pm_state::position, pm_state::prev_time, pm_state::range, rm_getelevation(), rm_move2(), tw_lp::rng, spacing, pm_state::stats, the_one, pm_state::transmit, tw_calloc(), tw_error(), tw_event_data(), tw_event_new(), tw_event_send(), TW_LOC, tw_rand_exponential(), tw_rand_init_streams(), tw_rand_integer(), pm_message::type, pm_state::velocity, and x.
tw_peid pm_map (tw_lpid gid)
Definition at line 4 of file pm.c.
References nlp_per_pe.
void pm_rc_event_handler (pm_state * state, tw_bf * bf, pm_message * m, tw_lp * lp)
Definition at line 141 of file pm.c.
References pm_rc_move(), PM_TIMESTEP, RM_PROXIMITY_ENV, RM_PROXIMITY_LP, tw_lp::rng, pm_statistics::s_move_ev, pm_statistics::s_nwaves, pm_statistics::s_prox_ev, pm_statistics::s_recv_ev, pm_state::stats, tw_error(), TW_LOC, tw_rand_reverse_unif, and pm_message::type.
Variable Documentation
tw_lptype my_lps[]
Initial value:
=
{
        {
                (init_f) pm_init,
                (event_f) pm_event_handler,
                (revent_f) pm_rc_event_handler,
                (final_f) pm_final,
                (map_f) pm_map,
                sizeof(pm_state)
        },
        {0},
}
Definition at line 192 of file pm.c.
tw_petype my_pes[]
Initial value:
=
{
        {
                (pe_init_f) pm_pe_init,
                (pe_init_f) pm_pe_post_init,
                (pe_gvt_f) pm_pe_gvt,
                (pe_final_f) pm_pe_final,
                (pe_periodic_f) 0
        },
        {0},
}
Definition at line 180 of file pm.c.
const tw_optdef pm_options[] static
Initial value:
=
{
        TWOPT_UINT("the-one", the_one, "single radio to model"),
        TWOPT_UINT("nradios", g_pm_nnodes, "number of radios"),
        TWOPT_UINT("rw-min", g_pm_mu, "random walk min change dir"),
        TWOPT_UINT("rw-max", g_pm_distr_sd, "random walk max change dir"),
        TWOPT_STIME("wave-percent", percent_wave, "percentage of waves per move"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
}
Definition at line 205 of file pm.c.