ROSS: ross/models/tlm/rm/rm.c File Reference
rm.c File Reference
#include <rm.h>
Functions
tw_peid _rm_map (tw_lpid gid)
void _rm_init (rm_state *state, tw_lp *lp)
void state_copy (rm_state *a, rm_state *b, double *d)
void _rm_event_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void _rm_rc_event_handler (rm_state *state, tw_bf *bf, rm_message *m, tw_lp *lp)
void _rm_final (rm_state *state, tw_lp *lp)
Function Documentation
void _rm_event_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 147 of file rm.c.
References tw_lp::gid, rm_message::id, rm_cell_handler(), RM_GATHER, RM_PARTICLE, rm_particle_handler(), RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_nparticles, rm_state::stats, tw_error(), TW_LOC, tw_now(), and rm_message::type.
void _rm_final (rm_state * state, tw_lp * lp)
Definition at line 205 of file rm.c.
References g_rm_stats, rm_statistics::s_ncell_gather, rm_statistics::s_ncell_initiate, rm_statistics::s_ncell_scatter, rm_statistics::s_nparticles, and rm_state::stats.
void _rm_init (rm_state * state, tw_lp * lp)
Definition at line 19 of file rm.c.
References rm_state::displacements, g_rm_spatial_d, g_rm_spatial_dim, g_rm_spatial_dir, g_rm_spatial_grid, g_rm_z_max, g_tw_mynode, tw_lp::gid, rm_state::nbrs, rm_state::particles, rm_getcell(), rm_getelevation(), rm_getlocation(), rm_state::stats, tw_calloc(), tw_error(), TW_LOC, and tw_memoryq_init().
tw_peid _rm_map (tw_lpid gid)
Definition at line 4 of file rm.c.
References nlp_per_pe.
Referenced by rm_getlocation().
void _rm_rc_event_handler (rm_state * state, tw_bf * bf, rm_message * m, tw_lp * lp)
Definition at line 179 of file rm.c.
References RM_GATHER, RM_PARTICLE, rm_rc_cell_handler(), rm_rc_particle_handler(), RM_SCATTER, RM_WAVE_INIT, rm_statistics::s_nparticles, rm_state::stats, tw_error(), TW_LOC, and rm_message::type.
void state_copy (rm_state * a, rm_state * b, double * d)
Definition at line 135 of file rm.c.
References rm_state::displacement, rm_state::displacements, g_rm_spatial_dir, and rm_state::next_time.