ROSS: ross/models/timers/tmr.c File Reference
tmr.c File Reference
#include "tmr.h"
Functions
tw_peid tmr_map (tw_lpid gid)
void tmr_init (tmr_state *s, tw_lp *lp)
void tmr_event_handler (tmr_state *s, tw_bf *bf, tmr_message *m, tw_lp *lp)
void tmr_event_handler_rc (tmr_state *s, tw_bf *bf, tmr_message *m, tw_lp *lp)
void tmr_finish (tmr_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 164 of file tmr.c.
References f, g_tmr_start_events, g_tw_events_per_pe, g_tw_kp, g_tw_memory_nqueues, g_tw_mynode, g_tw_nlp, g_tw_npe, mult, nlp_per_pe, offset_lpid, optimistic_memory, ttl_lps, tw_define_lps(), tw_end(), tw_init(), tw_lp_settype(), tw_nnodes(), tw_opt_add(), tw_run(), and verbose.
void tmr_event_handler (tmr_state * s, tw_bf * bf, tmr_message * m, tw_lp * lp)
Definition at line 34 of file tmr.c.
References tw_bf::c1, tw_bf::c2, tw_bf::c3, f, tw_lp::gid, mean, offset_lpid, tmr_message::old_time, tmr_message::old_timer, percent_remote, tw_event::recv_ts, tw_lp::rng, tmr_state::timer, ttl_lps, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), tw_rand_unif, and tw_timer_reset().
void tmr_event_handler_rc (tmr_state * s, tw_bf * bf, tmr_message * m, tw_lp * lp)
Definition at line 92 of file tmr.c.
References tw_bf::c1, tw_bf::c2, tw_bf::c3, f, tw_lp::gid, tmr_message::old_time, tmr_message::old_timer, tw_event::recv_ts, tw_lp::rng, tmr_state::timer, tw_now(), tw_rand_reverse_unif, tw_timer_init(), and tw_timer_reset().
void tmr_finish (tmr_state * s, tw_lp * lp)
Definition at line 133 of file tmr.c.
void tmr_init (tmr_state * s, tw_lp * lp)
Definition at line 10 of file tmr.c.
References g_tmr_start_events, tw_lp::gid, mean, tw_lp::pe, tw_lp::rng, tw_pe::rng, tmr_state::timer, tw_calloc(), tw_error(), tw_event_new(), tw_event_send(), TW_LOC, tw_rand_exponential(), tw_rand_initial_seed(), and tw_timer_init().
tw_peid tmr_map (tw_lpid gid)
Definition at line 4 of file tmr.c.
References g_tw_nlp.
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("TIMER Model"),
        TWOPT_STIME("remote", percent_remote, "desired remote event rate"),
        TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
        TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
        TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
        TWOPT_UINT("start-events", g_tmr_start_events, "number of initial messages per LP"),
        TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
        TWOPT_CHAR("run", run_id, "user supplied run name"),
        TWOPT_CHAR("verbose", verbose, "verbose statements"),
}
Definition at line 149 of file tmr.c.
tw_lptype mylps[]
Initial value:
= {
        {
         (init_f) tmr_init,
         (event_f) tmr_event_handler,
         (revent_f) tmr_event_handler_rc,
         (final_f) tmr_finish,
         (map_f) tmr_map,
         sizeof(tmr_state)
        },
        {0},
}
Definition at line 137 of file tmr.c.