ROSS: ross/models/torus/torus.c File Reference
torus.c File Reference
#include "torus.h"
Functions
int getRem ()
int getProcID (tw_lpid lpid)
tw_peid mapping (tw_lpid gid)
void torus_init (nodes_state *s, tw_lp *lp)
void mpi_init (mpi_process *p, tw_lp *lp)
void dimension_order_routing (nodes_state *s, tw_lpid *dst_lp, int *dim, int *dir)
void packet_generate (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void credit_send (nodes_state *s, tw_bf *bf, tw_lp *lp, nodes_message *msg)
void update_waiting_list (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void packet_send (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void waiting_packet_free (nodes_state *s, int loc)
void packet_arrive (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void mpi_msg_send (mpi_process *p, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void mpi_msg_recv (mpi_process *p, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void mpi_event_handler (mpi_process *p, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void mpi_event_rc_handler (mpi_process *p, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void final (nodes_state *s, tw_lp *lp)
tw_lp * torus_mapping_to_lp (tw_lpid lpid)
void packet_buffer_process (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void node_rc_handler (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void event_handler (nodes_state *s, tw_bf *bf, nodes_message *msg, tw_lp *lp)
void torus_mapping (void)
int main (int argc, char **argv, char **env)
Variables
tw_lptype nodes_lps []
const tw_optdef app_opt []
Function Documentation
void credit_send (nodes_state * s, tw_bf * bf, tw_lp * lp, nodes_message * msg)
Definition at line 401 of file torus.c.
References CREDIT, credit_delay, max, nodes_state::next_credit_available_time, tw_lp::rng, nodes_message::saved_available_time, nodes_message::sender_lp, nodes_message::source_dim, nodes_message::source_direction, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), and nodes_message::type.
Referenced by packet_arrive().
void dimension_order_routing (nodes_state * s, tw_lpid * dst_lp, int * dim, int * dir)
Definition at line 231 of file torus.c.
References dim_length, nodes_state::dim_position, half_length, N_dims, nodes_state::neighbour_minus_lpID, and nodes_state::neighbour_plus_lpID.
Referenced by packet_generate(), and packet_send().
void event_handler (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 984 of file torus.c.
References ARRIVAL, CREDIT, GENERATE, packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), SEND, nodes_message::type, update_waiting_list(), and WAIT.
void final (nodes_state * s, tw_lp * lp)
Definition at line 844 of file torus.c.
int getProcID (tw_lpid lpid)
Definition at line 15 of file torus.c.
References N_nodes.
int getRem ()
Definition at line 5 of file torus.c.
References g_tw_mynode, and node_rem.
Referenced by torus_mapping(), and torus_mapping_to_lp().
int main (int argc, char ** argv, char ** env)
Definition at line 1073 of file torus.c.
References chunk_size, credit_delay, CUSTOM, DIAGONAL, dim_length, g_tw_custom_initial_mapping, g_tw_custom_lp_global_to_local_map, g_tw_events_per_pe, g_tw_mapping, g_tw_mynode, g_tw_nlp, g_tw_npe, g_tw_ts_end, head_delay, injection_interval, injection_limit, link_bandwidth, max_latency, MEAN_INTERVAL, mem_factor, mpi_message_size, N_COLLECT_POINTS, N_dims, N_finished_msgs, N_finished_packets, N_finished_storage, N_generated_storage, N_mpi_procs, N_nodes, N_num_hops, N_queue_depth, NEAREST_NEIGHBOR, nlp_mpi_procs_per_pe, nlp_nodes_per_pe, node_rem, num_buf_slots, num_chunks, num_cols, num_packets, num_rows, opt_mem, packet_offset, PACKET_SIZE, torus_mapping(), torus_mapping_to_lp(), total_hops, total_lps, total_time, TRAFFIC, traffic_str, tw_define_lps(), tw_end(), tw_init(), tw_ismaster(), tw_nnodes(), tw_opt_add(), tw_run(), UNIFORM_RANDOM, and vc_size.
tw_peid mapping (tw_lpid gid)
Definition at line 22 of file torus.c.
References g_tw_mynode, getProcID(), N_nodes, nlp_mpi_procs_per_pe, nlp_nodes_per_pe, node_rem, and tw_nnodes().
void mpi_event_handler (mpi_process * p, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 775 of file torus.c.
References mpi_msg_recv(), mpi_msg_send(), MPI_RECV, MPI_SEND, and nodes_message::type.
void mpi_event_rc_handler (mpi_process * p, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 798 of file torus.c.
References mpi_process::available_time, tw_bf::c3, tw_bf::c4, g_tw_ts_end, max_latency, mpi_process::message_counter, MPI_RECV, MPI_SEND, nodes_message::my_N_hop, N_COLLECT_POINTS, N_finished_msgs, N_finished_packets, N_finished_storage, N_num_hops, num_packets, tw_lp::rng, nodes_message::saved_available_time, total_hops, total_time, nodes_message::travel_start_time, tw_now(), tw_rand_reverse_unif, and nodes_message::type.
void mpi_init (mpi_process * p, tw_lp * lp)
Definition at line 211 of file torus.c.
References mpi_process::available_time, tw_lp::gid, MEAN_INTERVAL, mpi_process::message_counter, MPI_SEND, tw_lp::rng, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), and nodes_message::type.
void mpi_msg_recv (mpi_process * p, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 751 of file torus.c.
References tw_bf::c3, g_tw_ts_end, max_latency, nodes_message::my_N_hop, N_COLLECT_POINTS, N_finished_msgs, N_finished_packets, N_finished_storage, N_num_hops, nodes_message::saved_available_time, total_hops, total_time, nodes_message::travel_start_time, and tw_now().
void mpi_msg_send (mpi_process * p, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 657 of file torus.c.
References mpi_process::available_time, tw_bf::c3, tw_bf::c4, nodes_message::dest_lp, DIAGONAL, GENERATE, getProcID(), tw_lp::gid, injection_limit, max, MEAN_INTERVAL, MEAN_PROCESS, mpi_process::message_counter, MPI_SEND, N_dims_sim, N_nodes, NEAREST_NEIGHBOR, nodes_message::next_stop, num_mpi_msgs, num_packets, nodes_message::packet_ID, packet_offset, tw_lp::rng, nodes_message::saved_available_time, TRAFFIC, nodes_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), tw_rand_integer(), nodes_message::type, and UNIFORM_RANDOM.
void node_rc_handler (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 894 of file torus.c.
References ARRIVAL, nodes_state::buffer, tw_bf::c1, tw_bf::c2, tw_bf::c3, CREDIT, waiting_packet::dim, waiting_packet::dir, g_tw_ts_end, GENERATE, nodes_message::my_N_hop, N_COLLECT_POINTS, N_dims, N_generated_storage, N_queue_depth, nodes_state::next_credit_available_time, nodes_state::next_link_available_time, num_chunks, waiting_packet::packet, tw_lp::rng, nodes_message::saved_available_time, nodes_message::saved_src_dim, nodes_message::saved_src_dir, SEND, nodes_message::source_dim, nodes_message::source_direction, tw_now(), tw_rand_reverse_unif, nodes_message::type, WAIT, nodes_state::wait_count, nodes_message::wait_loc, nodes_state::waiting_list, and WAITING_PACK_COUNT.
void packet_arrive (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 587 of file torus.c.
References nodes_state::buffer, tw_bf::c2, nodes_message::chunk_id, credit_send(), nodes_message::dest, nodes_message::dest_lp, g_tw_ts_end, tw_lp::gid, MEAN_INTERVAL, MPI_RECV, nodes_message::my_N_hop, N_COLLECT_POINTS, N_dims, N_nodes, N_queue_depth, nodes_message::next_stop, num_chunks, nodes_message::packet_ID, tw_lp::rng, SEND, nodes_message::sender_lp, nodes_message::source_dim, nodes_message::source_direction, nodes_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), and nodes_message::type.
void packet_buffer_process (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 861 of file torus.c.
References nodes_state::buffer, tw_bf::c3, CREDIT, waiting_packet::dim, waiting_packet::dir, tw_lp::gid, MEAN_INTERVAL, waiting_packet::packet, tw_lp::rng, SEND, nodes_message::source_dim, nodes_message::source_direction, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), nodes_message::type, nodes_state::wait_count, nodes_message::wait_loc, nodes_state::waiting_list, and waiting_packet_free().
Referenced by event_handler().
void packet_generate (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 284 of file torus.c.
References nodes_state::buffer, nodes_message::chunk_id, nodes_message::dest, nodes_message::dest_lp, DIAGONAL, dim_length, dim_length_sim, nodes_state::dim_position_sim, dimension_order_routing(), factor_sim, tw_lp::gid, MEAN_INTERVAL, nodes_message::my_N_hop, N_dims, N_dims_sim, NEAREST_NEIGHBOR, nodes_state::neighbour_minus_lpID_sim, nodes_state::neighbour_plus_lpID_sim, nodes_message::next_stop, num_buf_slots, num_chunks, nodes_message::packet_ID, tw_lp::rng, SEND, nodes_message::sender_lp, nodes_message::source_dim, nodes_message::source_direction, TRACK_LP, TRAFFIC, nodes_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), nodes_message::type, and nodes_message::wait_type.
void packet_send (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 457 of file torus.c.
References ARRIVAL, nodes_state::buffer, tw_bf::c1, tw_bf::c3, nodes_message::chunk_id, nodes_message::dest, nodes_message::dest_lp, dimension_order_routing(), g_tw_ts_end, tw_lp::gid, head_delay, max, MEAN_INTERVAL, nodes_message::my_N_hop, N_COLLECT_POINTS, N_dims, N_generated_storage, nodes_state::next_link_available_time, nodes_message::next_stop, num_buf_slots, num_chunks, nodes_message::packet_ID, tw_lp::rng, nodes_message::saved_available_time, nodes_message::saved_src_dim, nodes_message::saved_src_dir, SEND, nodes_message::sender_lp, nodes_message::source_dim, nodes_message::source_direction, nodes_message::travel_start_time, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), tw_rand_exponential(), nodes_message::type, WAIT, nodes_message::wait_dim, nodes_message::wait_dir, and nodes_message::wait_type.
void torus_init (nodes_state * s, tw_lp * lp)
Definition at line 61 of file torus.c.
References nodes_state::buffer, waiting_packet::dim, dim_length, dim_length_sim, nodes_state::dim_position, nodes_state::dim_position_sim, waiting_packet::dir, factor, factor_sim, tw_lp::gid, half_length, half_length_sim, nodes_state::head, N_dims, N_dims_sim, nodes_state::neighbour_minus_lpID, nodes_state::neighbour_minus_lpID_sim, nodes_state::neighbour_plus_lpID, nodes_state::neighbour_plus_lpID_sim, waiting_packet::next, nodes_state::next_link_available_time, NUM_VC, waiting_packet::packet, nodes_state::packet_counter, TRACK_LP, tw_calloc(), TW_LOC, nodes_state::wait_count, nodes_state::waiting_list, and WAITING_PACK_COUNT.
void torus_mapping (void)
Definition at line 1030 of file torus.c.
References g_tw_kp, g_tw_lp, g_tw_mynode, g_tw_nkp, g_tw_npe, g_tw_pe, getRem(), N_nodes, nkp_per_pe, nlp_mpi_procs_per_pe, nlp_nodes_per_pe, pe, tw_getpe(), tw_kp_onpe(), tw_lp_onkp(), tw_lp_onpe(), and tw_lp_settype().
Referenced by main().
tw_lp* torus_mapping_to_lp (tw_lpid lpid)
Definition at line 849 of file torus.c.
References g_tw_lp, g_tw_mynode, getRem(), N_nodes, nlp_mpi_procs_per_pe, and nlp_nodes_per_pe.
Referenced by main().
void update_waiting_list (nodes_state * s, tw_bf * bf, nodes_message * msg, tw_lp * lp)
Definition at line 432 of file torus.c.
References waiting_packet::dim, waiting_packet::dir, waiting_packet::packet, nodes_state::wait_count, nodes_message::wait_dim, nodes_message::wait_dir, nodes_state::waiting_list, and WAITING_PACK_COUNT.
Referenced by event_handler().
void waiting_packet_free (nodes_state * s, int loc)
Definition at line 570 of file torus.c.
References waiting_packet::dim, waiting_packet::dir, waiting_packet::packet, nodes_state::wait_count, and nodes_state::waiting_list.
Referenced by packet_buffer_process().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
{
        TWOPT_GROUP("Nodes Model"),
        TWOPT_UINT("memory", opt_mem, "optimistic memory"),
        TWOPT_UINT("vc_size", vc_size, "VC size"),
        TWOPT_ULONG("mpi-message-size", mpi_message_size, "mpi-message-size"),
        TWOPT_UINT("mem_factor", mem_factor, "mem_factor"),
        TWOPT_CHAR("traffic", traffic_str, "uniform, nearest, diagonal"),
        TWOPT_STIME("injection_interval", injection_interval, "messages are injected during this interval only "),
        TWOPT_STIME("link_bandwidth", link_bandwidth, " link bandwidth per channel "),
        TWOPT_STIME("arrive_rate", MEAN_INTERVAL, "packet arrive rate"),
}
Definition at line 1057 of file torus.c.
tw_lptype nodes_lps[]
Initial value:
=
{
        {
                (init_f) torus_init,
                (event_f) event_handler,
                (revent_f) node_rc_handler,
                (final_f) final,
                (map_f) mapping,
                sizeof(nodes_state),
        },
        {
               (init_f) mpi_init,
               (event_f) mpi_event_handler,
               (revent_f) mpi_event_rc_handler,
               (final_f) final,
               (map_f) mapping,
               sizeof(mpi_process),
        },
        {0},
}
Definition at line 1009 of file torus.c.