ROSS: rnf/modules/network/multicast/Transport.h File Reference
Transport.h File Reference
#include "Multicast.h"
Macros
#define SIM_RELAX_TIME 0.00000000001
#define DATA_PACKET_SIZE 1000
#define CTRL_PACKET_SIZE 40
Functions
void SendPacket (tw_lp *lp, Packet *p)
void SendExtPkt (tw_lp *lp, Packet *p, void *ext, int extSize)
void ReadAgentAct (char *fileName)
void CancelTimer (Agent *a, tw_event **e)
void ReschedTimer (Agent *a, int timerId, double offset, tw_event **e)
tw_event * ScheduleTimer (Agent *a, int timerId, double offset)
void ReschedTimerWithSn (Agent *a, int timerId, int serial, double offset, tw_event **e)
tw_event * ScheduleTimerWithSn (Agent *a, int timerId, int serial, double offset)
Variables
char * _AgentActFileName
Macro Definition Documentation
#define CTRL_PACKET_SIZE 40
Definition at line 8 of file Transport.h.
#define DATA_PACKET_SIZE 1000
Definition at line 7 of file Transport.h.
Referenced by olsr_change_region(), olsr_departure_from_mpr(), and olsr_region_init().
#define SIM_RELAX_TIME 0.00000000001
Definition at line 6 of file Transport.h.
Referenced by ReadAgentAct(), ScheduleTimer(), and ScheduleTimerWithSn().
Function Documentation
void CancelTimer (Agent * a, tw_event ** e) inline
Definition at line 193 of file Transport.c.
References AgentStruct::nodeId_, tw_getlp(), and tw_timer_cancel().
Referenced by OrmccRcvStop(), PgmccSrcStop(), and TfmccSrcStop().
void ReadAgentAct (char * fileName)
Definition at line 12 of file Transport.c.
References _nodeTable, NodeStruct::addr_, StatAgentListStruct::agent_, EventMsgStruct::agent_, EventMsgStruct::content_, g_tw_ts_end, GmccRcvInit(), GmccSrcInit(), MAX_LINE_LEN, StatAgentListStruct::next_, OrmccRcvInit(), OrmccSrcInit(), PgmccRcvInit(), PgmccSrcInit(), ReadLine(), SetGrpAddr4Prog, SIM_RELAX_TIME, START_AGENT, statAgentListHead_, statAgentListTail_, STOP_AGENT, TfmccRcvInit(), TfmccSrcInit(), tw_event_data(), tw_event_new(), tw_event_send(), tw_getlp(), and EventMsgStruct::type_.
Referenced by McastStartUp().
void ReschedTimer (Agent * a, int timerId, double offset, tw_event ** e) inline
Definition at line 199 of file Transport.c.
References AgentStruct::nodeId_, ScheduleTimer(), tw_getlp(), and tw_timer_cancel().
Referenced by PgmccSrcAckProc(), TfmccSrcIncrRate(), TfmccSrcPktHandler(), and TfmccSrcTimer().
void ReschedTimerWithSn (Agent * a, int timerId, int serial, double offset, tw_event ** e) inline
Definition at line 236 of file Transport.c.
References AgentStruct::nodeId_, ScheduleTimerWithSn(), tw_getlp(), and tw_timer_cancel().
Referenced by GmccSrcPktHandler(), and GmccSrcTimer().
tw_event* ScheduleTimer (Agent * a, int timerId, double offset) inline
Definition at line 207 of file Transport.c.
References TimeOutStruct::agent_, AGENT_TIMER, EventMsgStruct::content_, g_tw_ts_end, AgentStruct::nodeId_, SIM_RELAX_TIME, EventMsgStruct::timeOut_, TimeOutStruct::timerId_, tw_event_data(), tw_exit(), tw_getlp(), tw_now(), tw_timer_init(), and EventMsgStruct::type_.
Referenced by OrmccRcvPktHandler(), OrmccSrcPktHandler(), OrmccSrcStart(), OrmccSrcTimer(), PgmccSrcStall(), PgmccSrcStart(), ReschedTimer(), TfmccSrcStart(), and TfmccSrcTimer().
tw_event* ScheduleTimerWithSn (Agent * a, int timerId, int serial, double offset) inline
Definition at line 246 of file Transport.c.
References TimeOutStruct::agent_, AGENT_TIMER, EventMsgStruct::content_, g_tw_ts_end, AgentStruct::nodeId_, TimeOutStruct::serial_, SIM_RELAX_TIME, EventMsgStruct::timeOut_, TimeOutStruct::timerId_, tw_event_data(), tw_exit(), tw_getlp(), tw_now(), tw_timer_init(), and EventMsgStruct::type_.
Referenced by GmccSrcPktHandler(), GmccSrcStart(), GmccSrcTimer(), and ReschedTimerWithSn().
void SendExtPkt (tw_lp * lp, Packet * p, void * ext, int extSize) inline
Definition at line 172 of file Transport.c.
References AddExtPkt(), PacketStruct::dstAddr_, ForwardMulticastPkt(), ForwardUnicastPkt(), GetFwdPortMap(), tw_lp::id, PacketStruct::id_, IsMcastAddr, PacketStruct::srcAddr_, and PacketStruct::srcAgent_.
Referenced by GmccSrcSendCtrlPkt().
void SendPacket (tw_lp * lp, Packet * p) inline
Definition at line 156 of file Transport.c.
References PacketStruct::dstAddr_, ForwardMulticastPkt(), ForwardUnicastPkt(), GetFwdPortMap(), tw_lp::id, PacketStruct::id_, and IsMcastAddr.
Referenced by GmccRcvSendCiPkt(), GmccSrcSendDataPkt(), OrmccRcvSendPkt(), OrmccSrcSendPkt(), PgmccRcvSendPkt(), PgmccSrcSendPkt(), TfmccRcvSendPkt(), and TfmccSrcSendPkt().
Variable Documentation
char* _AgentActFileName
Definition at line 9 of file Transport.c.
Referenced by McastStartUp().