ROSS: ross/tw-event.c File Reference
tw-event.c File Reference
#include <ross.h>
#include <assert.h>
Functions
static void link_causality (tw_event *nev, tw_event *cev)
void tw_event_send (tw_event *event)
static void local_cancel (tw_pe *d, tw_event *event)
static void event_cancel (tw_event *event)
void tw_event_rollback (tw_event *event)
Function Documentation
static void event_cancel (tw_event * event) inline static
Definition at line 94 of file tw-event.c.
References tw_event::dest_lp, tw_pe::id, local_cancel(), min, tw_pe::node, tw_event::owner, tw_lp::pe, tw_pe::pq, tw_event::recv_ts, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_event::state, tw_pe::stats, tw_pe::trans_msg_ts, tw_error(), tw_event_free(), tw_gvt_inprogress(), TW_kp_pevent_q, TW_LOC, TW_net_asend, tw_net_cancel(), tw_net_onnode(), tw_node_eq(), TW_pe_event_q, TW_pe_pq, TW_pe_sevent_q, and tw_pq_delete_any().
Referenced by tw_event_rollback().
static void link_causality (tw_event * nev, tw_event * cev) inline static
Definition at line 5 of file tw-event.c.
References tw_event::cause_next, and tw_event::caused_by_me.
Referenced by tw_event_send().
static void local_cancel (tw_pe * d, tw_event * event) inline static
Definition at line 85 of file tw-event.c.
References tw_pe::cancel_q.
Referenced by event_cancel().
void tw_event_rollback (tw_event * event)
Definition at line 158 of file tw-event.c.
References tw_event::cause_next, tw_event::caused_by_me, event_cancel(), tw_lp::kp, tw_kp::s_e_rbs, tw_free_output_messages(), and tw_state_rollback().
Referenced by tw_kp_rollback_event(), tw_kp_rollback_to(), and tw_sched_batch().
void tw_event_send (tw_event * event)
Definition at line 12 of file tw-event.c.
References tw_pe::abort_event, tw_pe::cev_abort, CONSERVATIVE, tw_pe::cur_event, tw_event::dest_lp, tw_pe::event_q, g_tw_lookahead, g_tw_mynode, g_tw_synchronization_protocol, g_tw_ts_end, tw_lp::kp, tw_kp::last_time, link_causality(), tw_lptype::map, min, tw_event::out_msgs, tw_lp::pe, tw_pe::pq, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_pe::stats, tw_pe::trans_msg_ts, tw_error(), tw_eventq_push(), tw_getlocal_lp(), tw_gvt_inprogress(), TW_LOC, TW_net_asend, tw_net_onnode(), tw_net_send(), tw_node_eq(), tw_now(), TW_pe_event_q, tw_pq_enqueue(), and tw_lp::type.
Referenced by Airport_EventHandler(), Airport_StartUp(), Application_Next_Burst(), Cell_CompletionCall(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), credit_send(), disksim_event_handler(), epi_agent_send(), event_handler(), ForwardDefault(), ForwardPacket(), init(), insert_into_pq(), Intersection_EventHandler(), Intersection_StartUp(), ip_downstream_forward(), ip_downstream_source(), ip_upstream(), Link_DeQueue(), Link_EnQueue(), mem_event_handler(), mem_init(), mpi_init(), mpi_msg_send(), olsr_change_region(), olsr_departure_from_mpr(), olsr_event(), olsr_init(), olsr_region_init(), olsr_station_to_mpr(), ospf_flood_recv(), ospf_retrans_timed_out(), packet_arrive(), packet_buffer_process(), packet_generate(), packet_send(), phold_event_handler(), phold_init(), pm_init(), pm_move(), qhold_event(), qhold_init(), raid_controller_gen_send(), raid_disk_gen_send(), raid_io_gen_send(), ReadAgentAct(), ReadGroupOp(), rm_cell_gather(), rm_cell_scatter(), rm_particle_send(), rm_proximity_send(), rm_wave_initiate(), rn_event_handler(), rn_event_send(), rn_link_random_weight_changes(), rn_setup_links(), rn_timer_simple(), rngt_init(), route_packet(), Router_Arrival(), router_credit_send(), router_packet_receive(), router_packet_send(), Router_Recv(), router_reschedule_event(), rp_move(), rw_move(), sa_master_event(), schedule_router_waiting_msg(), schedule_terminal_waiting_msg(), srw_event(), srw_init(), tcp_event_send(), tcp_util_event(), tlm_cell_gather(), tlm_cell_scatter(), tlm_particle_send(), tlm_proximity_send(), tlm_wave_initiate(), tmr_event_handler(), tmr_init(), wifi_access_point_arrival(), and wifi_station_arrival().