ROSS: ross/tw-kp.c File Reference
tw-kp.c File Reference
#include <ross.h>
Macros
#define NUM_OUT_MESG 2000
Functions
void tw_kp_onpe (tw_kpid id, tw_pe *pe)
void tw_kp_rollback_to (tw_kp *kp, tw_stime to)
void tw_kp_rollback_event (tw_event *event)
static tw_out * init_output_messages (tw_kp *kp)
void tw_init_kps (tw_pe *me)
tw_out * tw_kp_grab_output_buffer (tw_kp *kp)
void tw_kp_put_back_output_buffer (tw_out *out)
void tw_kp_fossil_memoryq (tw_kp *kp, tw_fd fd)
void tw_kp_fossil_memory (tw_kp *kp)
Macro Definition Documentation
#define NUM_OUT_MESG 2000
Definition at line 96 of file tw-kp.c.
Referenced by init_output_messages().
Function Documentation
static tw_out* init_output_messages (tw_kp * kp) static
Definition at line 99 of file tw-kp.c.
References tw_out::next, NUM_OUT_MESG, tw_out::owner, tw_calloc(), and TW_LOC.
Referenced by tw_init_kps().
void tw_init_kps (tw_pe * me)
Definition at line 116 of file tw-kp.c.
References g_tw_memory_nqueues, g_tw_nkp, g_tw_synchronization_protocol, tw_kp::id, init_output_messages(), OPTIMISTIC, tw_kp::output, tw_kp::pe, tw_kp::s_e_rbs, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_calloc(), tw_getkp(), and TW_LOC.
Referenced by tw_sched_init().
void tw_kp_fossil_memory (tw_kp * kp)
Definition at line 233 of file tw-kp.c.
References g_tw_memory_nqueues, and tw_kp_fossil_memoryq().
Referenced by tw_pe_fossil_collect().
void tw_kp_fossil_memoryq (tw_kp * kp, tw_fd fd)
Definition at line 173 of file tw-kp.c.
References tw_pe::GVT, tw_kp::id, tw_kp::pe, and tw_memoryq_push_list().
Referenced by tw_kp_fossil_memory(), and tw_memory_alloc().
tw_out* tw_kp_grab_output_buffer (tw_kp * kp)
Definition at line 145 of file tw-kp.c.
References tw_out::next, and tw_kp::output.
Referenced by tw_output().
void tw_kp_onpe (tw_kpid id, tw_pe * pe)
Definition at line 4 of file tw-kp.c.
References g_tw_kp, g_tw_nkp, tw_kp::id, pe, tw_kp::pe, tw_calloc(), tw_error(), and TW_LOC.
Referenced by dragonfly_mapping(), main(), map_linear(), map_round_robin(), olsr_custom_mapping(), olsr_grid_mapping(), pcs_grid_mapping(), torus_mapping(), and traffic_grid_mapping().
void tw_kp_put_back_output_buffer (tw_out * out)
Definition at line 158 of file tw-kp.c.
References tw_out::next, tw_kp::output, and tw_out::owner.
Referenced by tw_free_output_messages().
void tw_kp_rollback_event (tw_event * event)
Definition at line 58 of file tw-kp.c.
References tw_pe::GVT, tw_eventq::head, tw_kp::id, tw_pe::id, tw_kp::last_time, pe, tw_kp::pe, tw_kp::pevent_q, tw_pe::pq, tw_event::recv_ts, tw_kp::s_rb_secondary, tw_kp::s_rb_total, tw_eventq::size, tw_error(), tw_event_rollback(), tw_eventq_shift(), TW_LOC, and tw_pq_enqueue().
Referenced by tw_sched_cancel_q().
void tw_kp_rollback_to (tw_kp * kp, tw_stime to)
Definition at line 19 of file tw-kp.c.
References tw_pe::GVT, tw_eventq::head, tw_kp::id, tw_pe::id, tw_kp::last_time, tw_kp::pe, tw_kp::pevent_q, tw_pe::pq, tw_event::recv_ts, tw_kp::s_rb_total, tw_eventq::size, tw_event_rollback(), tw_eventq_shift(), and tw_pq_enqueue().
Referenced by tw_sched_event_q(), and tw_scheduler_optimistic_debug().