ROSS: ross/tw-memory.h File Reference
tw-memory.h File Reference
Macros
#define TW_MEMORY_BUFFER_SIZE 500
Functions
static tw_memory * tw_memory_alloc (tw_lp *lp, tw_fd fd)
static void tw_memory_alloc_rc (tw_lp *lp, tw_memory *m, tw_fd fd)
static void tw_memory_free (tw_lp *lp, tw_memory *m, tw_fd fd)
static tw_memory * tw_memory_free_rc (tw_lp *lp, tw_fd fd)
static void tw_memory_unshift (tw_lp *lp, tw_memory *m, tw_fd fd)
static size_t tw_memory_getsize (tw_pe *pe, int fd)
static tw_fd tw_memory_init (size_t n_mem, size_t d_sz, tw_stime mult)
Macro Definition Documentation
#define TW_MEMORY_BUFFER_SIZE 500
Definition at line 4 of file tw-memory.h.
Referenced by init_q(), send_begin(), and tw_eventq_alloc().
Function Documentation
static tw_memory* tw_memory_alloc (tw_lp * lp, tw_fd fd) inline static
Definition at line 10 of file tw-memory.h.
References g_tw_mynode, tw_lp::kp, pe, tw_lp::pe, tw_statistics::s_mem_buffers_used, tw_pe::stats, tw_error(), tw_kp_fossil_memoryq(), TW_LOC, tw_memory_allocate(), and tw_memoryq_pop().
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_notify_send(), bgp_open_send(), bgp_route_copy(), bgp_route_new(), bgp_timer_start(), bgp_update_send(), dd_exchange(), epi_init(), epi_init_agent_default(), epi_seir_compute(), forward(), ftp_event_handler(), ftp_init(), init_rib(), main_setup_areas(), mem_alloc(), ospf_db_read(), ospf_dd_copy(), ospf_event_send(), ospf_h_send(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_allocate(), ospf_lsa_find(), ospf_lsa_flush(), ospf_lsa_link_allocate(), ospf_lsa_start_flood(), ospf_nbr_neg_done(), ospf_nbr_two_way_recv(), ospf_random_weights(), ospf_timer_start(), process_lsa_recv(), recv_finish(), rm_particle_send(), rp_init(), rp_move(), rw_init(), rw_move(), start_transfer(), tcp_event_send(), tcp_host_process_ack(), tcp_host_timeout(), tcp_host_update_rtt(), tcp_rc_timer_reset(), tcp_timer_reset(), tlm_particle_send(), and tw_socket_read_event().
static void tw_memory_alloc_rc (tw_lp * lp, tw_memory * m, tw_fd fd) inline static
Definition at line 55 of file tw-memory.h.
References tw_lp::pe, tw_error(), TW_LOC, and tw_memoryq_push().
Referenced by ip_rc_downstream(), and tcp_rc_timer_reset().
static void tw_memory_free (tw_lp * lp, tw_memory * m, tw_fd fd) inline static
Definition at line 64 of file tw-memory.h.
References g_tw_npe, tw_lp::kp, tw_lp::pe, tw_memoryq_push(), tw_nnodes(), and tw_now().
Referenced by agent_susceptible(), bgp_event_handler(), bgp_route_free(), bgp_timer_cancel(), dd_process(), epi_timer_cancel(), ftp_event_handler(), ip_event_handler(), ls_update_process(), mem_event_handler(), ospf_ack_process(), ospf_dd_event_handler(), ospf_event_handler(), ospf_hello_packet(), ospf_ls_request_recv(), ospf_ls_update_recv(), ospf_timer_cancel(), rm_particle_handler(), rp_event_handler(), rw_event_handler(), stop_transfer(), tcp_event_handler(), tcp_timer_cancel(), and tlm_particle_handler().
static tw_memory* tw_memory_free_rc (tw_lp * lp, tw_fd fd) inline static
Definition at line 84 of file tw-memory.h.
References tw_pe::GVT, tw_lp::kp, tw_lp::pe, tw_error(), TW_LOC, and tw_memoryq_pop().
Referenced by ftp_rc_event_handler(), ip_rc_event_handler(), mem_event_handler_rc(), r_deal_with_timed_out_bgp_routers(), r_msg_update(), rm_rc_particle_handler(), rp_rc_event_handler(), rw_rc_event_handler(), tcp_rc_event_handler(), tcp_rc_timer_cancel(), and tlm_rc_particle_handler().
static size_t tw_memory_getsize (tw_pe * pe, int fd) inline static
Definition at line 108 of file tw-memory.h.
References g_tw_memory_sz.
Referenced by send_begin(), and tw_socket_send_event().
static tw_fd tw_memory_init (size_t n_mem, size_t d_sz, tw_stime mult) inline static
Definition at line 114 of file tw-memory.h.
References tw_error(), tw_getpe(), TW_LOC, and tw_pe_memory_init().
Referenced by bgp_main(), ip_md_init(), main(), ospf_main(), rp_md_init(), rw_md_init(), and tcp_md_init().
static void tw_memory_unshift (tw_lp * lp, tw_memory * m, tw_fd fd) inline static
Definition at line 99 of file tw-memory.h.
References tw_lp::pe, and tw_memoryq_push().
Referenced by send_begin(), tw_event_free(), and tw_socket_send_event().