ROSS: ross/tw-memoryq.h File Reference
tw-memoryq.h File Reference
Functions
static tw_memoryq * tw_memoryq_init ()
static void tw_memoryq_debug (tw_memoryq *q)
static void tw_memoryq_push (tw_memoryq *q, tw_memory *buf)
static void tw_memoryq_push_list (tw_memoryq *q, tw_memory *h, tw_memory *t, int cnt)
static tw_memory * tw_memoryq_pop (tw_memoryq *q)
static tw_memory * tw_memoryq_pop_list (tw_memoryq *q)
static void tw_memoryq_splice (tw_memoryq *q, tw_memory *h, tw_memory *t, int cnt)
static void tw_memoryq_delete_any (tw_memoryq *q, tw_memory *buf)
Function Documentation
static void tw_memoryq_debug (tw_memoryq * q) inline static
Definition at line 20 of file tw-memoryq.h.
References tw_error(), and TW_LOC.
Referenced by tw_memoryq_delete_any(), tw_memoryq_pop(), tw_memoryq_pop_list(), tw_memoryq_push(), tw_memoryq_push_list(), and tw_memoryq_splice().
static void tw_memoryq_delete_any (tw_memoryq * q, tw_memory * buf) inline static
Definition at line 180 of file tw-memoryq.h.
References tw_memoryq_debug().
Referenced by r_msg_update().
static tw_memoryq* tw_memoryq_init () inline static
Definition at line 5 of file tw-memoryq.h.
References tw_calloc(), tw_error(), and TW_LOC.
Referenced by _rm_init(), _tlm_init(), ip_init(), and main_setup_areas().
static tw_memory* tw_memoryq_pop (tw_memoryq * q) inline static
Definition at line 102 of file tw-memoryq.h.
References tw_memoryq_debug().
Referenced by bgp_route_free(), ip_rc_downstream(), main_setup_areas(), r_msg_update(), rm_particle_handler(), rm_rc_particle_handler(), tlm_particle_handler(), tlm_rc_particle_handler(), tw_memory_alloc(), and tw_memory_free_rc().
static tw_memory* tw_memoryq_pop_list (tw_memoryq * q) inline static
Definition at line 130 of file tw-memoryq.h.
References tw_memoryq_debug().
static void tw_memoryq_push (tw_memoryq * q, tw_memory * buf) inline static
Definition at line 53 of file tw-memoryq.h.
References tw_memoryq_debug().
Referenced by bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_route_copy(), forward(), main_setup_areas(), ospf_db_read(), ospf_lsa_find(), ospf_lsa_link_allocate(), r_deal_with_timed_out_bgp_routers(), r_msg_update(), rm_particle_handler(), rm_rc_particle_handler(), tlm_particle_handler(), tlm_rc_particle_handler(), tw_memory_alloc_rc(), tw_memory_free(), and tw_memory_unshift().
static void tw_memoryq_push_list (tw_memoryq * q, tw_memory * h, tw_memory * t, int cnt) inline static
Definition at line 77 of file tw-memoryq.h.
References tw_memoryq_debug().
Referenced by tw_kp_fossil_memoryq().
static void tw_memoryq_splice (tw_memoryq * q, tw_memory * h, tw_memory * t, int cnt) inline static
Definition at line 153 of file tw-memoryq.h.
References tw_memoryq_debug().