ROSS: ross/tw-memory.c File Reference
tw-memory.c File Reference
#include <ross.h>
Functions
size_t tw_memory_allocate (tw_memoryq *q)
Function Documentation
size_t tw_memory_allocate (tw_memoryq * q)
Definition at line 4 of file tw-memory.c.
References d, max, tw_calloc(), tw_error(), and TW_LOC.
Referenced by epi_init_agent(), main_setup_areas(), and tw_memory_alloc().