ROSS: ross/tw-pe.c File Reference
tw-pe.c File Reference
#include <ross.h>
Macros
#define copy_pef(f, d) pe->type.f = type->f ? type->f : d
Functions
static void dummy_pe_f (tw_pe *pe)
void tw_pe_settype (tw_pe *pe, const tw_petype *type)
tw_pe * tw_pe_next (tw_pe *last)
void tw_pe_create (tw_peid id)
void tw_pe_init (tw_peid id, tw_peid gid)
void tw_pe_fossil_collect (tw_pe *me)
Macro Definition Documentation
#define copy_pef (f, d) pe->type.f = type->f ? type->f : d
Referenced by tw_pe_settype().
Function Documentation
static void dummy_pe_f (tw_pe * pe) static
Definition at line 3 of file tw-pe.c.
Referenced by tw_pe_settype().
void tw_pe_create (tw_peid id)
Definition at line 36 of file tw-pe.c.
References g_tw_npe, g_tw_pe, tw_calloc(), and TW_LOC.
Referenced by tw_net_start().
void tw_pe_fossil_collect (tw_pe * me)
Definition at line 80 of file tw-pe.c.
References g_tw_fossil_attempts, g_tw_nkp, tw_kp::pevent_q, tw_pe::sevent_q, tw_eventq_fossil_collect(), tw_getkp(), and tw_kp_fossil_memory().
Referenced by tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), and tw_gvt_wait().
void tw_pe_init (tw_peid id, tw_peid gid)
Definition at line 49 of file tw-pe.c.
References g_tw_mynode, g_tw_npe, g_tw_nRNG_per_lp, g_tw_pe, g_tw_rng_default, g_tw_rng_max, tw_pe::gvt_status, tw_pe::id, tw_pe::node, pe, tw_pe::pe_next, tw_pe::rng, tw_pe::trans_msg_ts, tw_calloc(), tw_error(), TW_LOC, tw_pe_settype(), tw_rand_init(), and TW_TRUE.
Referenced by tw_net_start().
tw_pe* tw_pe_next (tw_pe * last)
Definition at line 26 of file tw-pe.c.
References g_tw_pe, and tw_pe::pe_next.
Referenced by map_linear(), olsr_custom_mapping(), tw_gvt_compute(), tw_sigsegv(), and tw_stats().
void tw_pe_settype (tw_pe * pe, const tw_petype * type)
Definition at line 8 of file tw-pe.c.
References copy_pef, dummy_pe_f(), tw_error(), and TW_LOC.
Referenced by main(), rm_initialize(), and tw_pe_init().