ROSS: core/queue/tw-queue.h File Reference
core/queue/tw-queue.h File Reference
#include <ross.h>
Functions
tw_pq * tw_pq_create (void)
void tw_pq_enqueue (tw_pq *, tw_event *)
tw_event * tw_pq_dequeue (tw_pq *)
tw_stime tw_pq_minimum (tw_pq *)
void tw_pq_delete_any (tw_pq *, tw_event *)
unsigned int tw_pq_get_size (tw_pq *)
unsigned int tw_pq_max_size (tw_pq *)
Function Documentation
tw_pq* tw_pq_create (void)
Definition at line 425 of file calendar.c.
References tw_pq::curr_max, tw_pq::elems, g_tw_events_per_pe, tw_pq::least, tw_eventpq::least, LocalInit(), MAX_EVENTS_PER_PE, tw_pq::nelems, tw_pq::nitems, tw_eventpq::nitems, tw_pq::OrigBucket, tw_pq::ResizeEnabled, tw_pq::root, tw_eventpq::root, tw_calloc(), TW_LOC, and tw_unsafe_realloc().
Referenced by setup_pes().
void tw_pq_delete_any (tw_pq * , tw_event *)
Definition at line 542 of file calendar.c.
References tw_event::dest_lp, tw_pq::elems, KEY, tw_lp::kp, tw_pq::nelems, tw_event::next, tw_event::owner, percolate_up(), tw_event::prev, tw_pq::Qsize, sift_down(), tw_event::state, tw_eventpq_delete_any(), tw_kp_pq_delete_any(), and tw_kp_pq_enqueue().
Referenced by event_cancel(), and tw_sched_cancel_q().
tw_event* tw_pq_dequeue (tw_pq *)
Definition at line 40 of file calendar.c.
References tw_pq::BottomThreshold, tw_pq::Bucket, tw_pq::BucketTop, Delete(), tw_pq::elems, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Nbuckets, tw_pq::nelems, tw_event_head::next, tw_pq::nitems, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, sift_down(), tw_event::state, tw_error(), tw_eventpq_dequeue(), tw_kp_pq_dequeue(), tw_kp_pq_enqueue(), TW_LOC, and tw_pq::Width.
Referenced by NewWidth(), tw_pq_delete_any(), tw_sched_batch(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), and tw_scheduler_sequential().
void tw_pq_enqueue (tw_pq * , tw_event *)
Definition at line 142 of file calendar.c.
References tw_pq::BucketTop, tw_event::dest_lp, Insert(), tw_lp::kp, tw_pq::LastBucket, tw_pq::LastPriority, tw_pq::Nbuckets, tw_event::owner, tw_pq::Qsize, tw_event::recv_ts, ReSize(), tw_pq::ResizeEnabled, tw_event::state, tw_pq::TopThreshold, tw_eventpq_enqueue(), tw_kp_pq_delete_any(), tw_kp_pq_enqueue(), TW_pe_pq, and tw_pq::Width.
Referenced by NewWidth(), recv_finish(), ReSize(), tw_event_send(), tw_kp_rollback_event(), tw_kp_rollback_to(), tw_sched_batch(), and tw_sched_event_q().
unsigned int tw_pq_get_size (tw_pq *)
Definition at line 555 of file calendar.c.
References tw_pq::nelems, tw_pq::nitems, and tw_pq::Qsize.
Referenced by tw_stats().
unsigned int tw_pq_max_size (tw_pq *)
Definition at line 606 of file kp_splay.c.
References tw_pq::max_size.
Referenced by gvt_print().
tw_stime tw_pq_minimum (tw_pq *)
Definition at line 486 of file calendar.c.
References tw_pq::Bucket, tw_pq::BucketTop, HeapPeekTop(), KEY, tw_pq::LastBucket, tw_pq::least, tw_pq::Nbuckets, tw_event_head::next, tw_pq::Qsize, tw_event::recv_ts, tw_error(), TW_LOC, and tw_pq::Width.
Referenced by tw_gvt_compute(), tw_gvt_step2(), tw_sched_batch(), tw_scheduler_conservative(), and tw_scheduler_sequential().