ROSS: core/tw-signal.c File Reference
core/tw-signal.c File Reference
#include <ross.h>
#include <signal.h>
Functions
void tw_sigsegv (int sig)
void tw_sigterm (int sig)
Variables
static unsigned int once = 1
Function Documentation
void tw_sigsegv (int sig)
Definition at line 7 of file tw-signal.c.
References g_tw_sim_started, tw_pe::local_master, once, pe, tw_error(), TW_LOC, tw_net_abort(), tw_pe_next(), tw_printf(), and tw_stats().
void tw_sigterm (int sig)
Definition at line 42 of file tw-signal.c.
References tw_error(), TW_LOC, and tw_net_abort().
Variable Documentation
unsigned int once = 1 [static]
Definition at line 4 of file tw-signal.c.
Referenced by tw_sigsegv().