ROSS: core/tw-stats.c File Reference
tw-stats.c File Reference
#include <ross.h>
#include <sys/stat.h>
Functions
static void show_lld (const char *name, tw_stat v)
static void show_2f (const char *name, double v)
static void show_1f (const char *name, double v)
static void show_4f (const char *name, double v)
void tw_get_stats (tw_pe *pe, tw_statistics *s)
void st_print_analysis_LP_stats (tw_statistics *s)
void tw_stats (tw_pe *me)
void tw_all_lp_stats (tw_pe *me)
Function Documentation
show_1f()
void show_1f (const char * name, double v) static
Definition at line 20 of file tw-stats.c.
References g_tw_csv.
Referenced by tw_stats().
show_2f()
void show_2f (const char * name, double v) static
Definition at line 13 of file tw-stats.c.
References g_tw_csv.
Referenced by st_print_analysis_LP_stats(), and tw_stats().
show_4f()
void show_4f (const char * name, double v) static
Definition at line 27 of file tw-stats.c.
References g_tw_csv.
Referenced by tw_stats().
show_lld()
void show_lld (const char * name, tw_stat v) static
Definition at line 6 of file tw-stats.c.
References g_tw_csv.
Referenced by st_print_analysis_LP_stats(), and tw_stats().
st_print_analysis_LP_stats()
void st_print_analysis_LP_stats (tw_statistics * s)
Definition at line 104 of file tw-stats.c.
References tw_statistics::s_alp_e_rbs, tw_statistics::s_alp_nevent_processed, tw_statistics::s_e_rbs, tw_statistics::s_nevent_processed, show_2f(), and show_lld().
Referenced by tw_stats().
tw_all_lp_stats()
void tw_all_lp_stats (tw_pe * me)
Definition at line 248 of file tw-stats.c.
References g_st_analysis_nlp, g_tw_clock_rate, g_tw_nlp, tw_lp::gid, tw_pe::id, tw_lp::lp_stats, st_lp_stats::s_nevent_processed, st_lp_stats::s_process_event, tw_getlp(), and tw_net_barrier().
Referenced by tw_scheduler_optimistic(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
tw_get_stats()
void tw_get_stats (tw_pe * pe, tw_statistics * s)
Definition at line 36 of file tw-stats.c.
References g_tw_fossil_attempts, g_tw_min_detected_offset, g_tw_nkp, g_tw_pe, g_tw_sim_started, pe, ROSS_MAX, tw_statistics::s_alp_e_rbs, tw_statistics::s_alp_nevent_processed, tw_statistics::s_avl, tw_statistics::s_buddy, tw_statistics::s_cancel_q, tw_kp::s_e_rbs, tw_statistics::s_e_rbs, tw_statistics::s_event_abort, tw_statistics::s_event_process, tw_statistics::s_events_past_end, tw_statistics::s_fc_attempts, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_statistics::s_init, tw_statistics::s_lz4, tw_statistics::s_max_run_time, tw_statistics::s_min_detected_offset, tw_statistics::s_net_events, tw_statistics::s_net_other, tw_statistics::s_net_read, tw_statistics::s_nevent_abort, tw_kp::s_nevent_processed, tw_statistics::s_nevent_processed, tw_statistics::s_nread_network, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_statistics::s_nsend_network, tw_statistics::s_nsend_remote_rb, tw_statistics::s_pe_event_ties, tw_statistics::s_pq, tw_statistics::s_pq_qsize, tw_statistics::s_rb_primary, tw_kp::s_rb_secondary, tw_statistics::s_rb_secondary, tw_kp::s_rb_total, tw_statistics::s_rb_total, tw_statistics::s_rollback, tw_statistics::s_stat_comp, tw_statistics::s_stat_write, tw_statistics::s_total, tw_getkp(), tw_pq_get_size(), tw_wall_sub(), and tw_wall_to_double().
Referenced by st_collect_engine_data(), and tw_stats().
tw_stats()
void tw_stats (tw_pe * me)
Definition at line 126 of file tw-stats.c.
References CONSERVATIVE, tw_lp::cur_state, tw_lptype::final, g_st_analysis_nlp, g_st_use_analysis_lps, g_tw_clock_rate, g_tw_csv, g_tw_events_per_pe, g_tw_events_per_pe_extra, g_tw_gvt_done, g_tw_msg_sz, g_tw_nlp, g_tw_synchronization_protocol, tw_lp::rng, tw_statistics::s_avl, tw_statistics::s_buddy, tw_statistics::s_cancel_q, tw_statistics::s_e_rbs, tw_statistics::s_event_abort, tw_statistics::s_event_process, tw_statistics::s_events_past_end, tw_statistics::s_fc_attempts, tw_statistics::s_fossil_collect, tw_statistics::s_gvt, tw_statistics::s_init, tw_statistics::s_lz4, tw_statistics::s_max_run_time, tw_statistics::s_min_detected_offset, tw_statistics::s_net_events, tw_statistics::s_net_other, tw_statistics::s_net_read, tw_statistics::s_nevent_abort, tw_statistics::s_nevent_processed, tw_statistics::s_nread_network, tw_statistics::s_nsend_loc_remote, tw_statistics::s_nsend_net_remote, tw_statistics::s_nsend_network, tw_statistics::s_pe_event_ties, tw_statistics::s_pq, tw_statistics::s_rb_primary, tw_statistics::s_rb_secondary, tw_statistics::s_rb_total, tw_statistics::s_rollback, tw_statistics::s_stat_comp, tw_statistics::s_stat_write, tw_statistics::s_total, show_1f(), show_2f(), show_4f(), show_lld(), st_print_analysis_LP_stats(), tw_lptype::state_sz, tw_calloc_stats(), tw_get_stats(), tw_getlp(), tw_gvt_stats(), tw_ismaster(), tw_net_statistics(), tw_nnodes(), and tw_lp::type.
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), tw_scheduler_optimistic_realtime(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().