ROSS: ross/tw-timer.c File Reference
tw-timer.c File Reference
#include <ross.h>
#include <tw-timer.h>
Functions
tw_timer tw_timer_event_new (tw_lp *dest, tw_stime recv_ts, tw_lp *src)
void tw_timer_event_send (tw_timer event)
tw_timer tw_timer_init (tw_lp *lp, tw_stime ts)
void tw_timer_cancel (tw_lp *lp, tw_timer *e)
void tw_timer_reset (tw_lp *lp, tw_timer *e, tw_stime ts)
Function Documentation
void tw_timer_cancel (tw_lp * lp, tw_timer * e)
Definition at line 79 of file tw-timer.c.
References tw_pe::abort_event, g_tw_ts_end, tw_lp::pe, tw_error(), tw_event_free(), TW_LOC, TW_pe_pq, and tw_pq_delete_any().
Referenced by CancelTimer(), GmccSrcPktHandler(), GmccSrcResetLayer(), GmccSrcStop(), GmccSrcTimer(), OrmccRcvPktHandler(), OrmccSrcPktHandler(), OrmccSrcStop(), ReschedTimer(), ReschedTimerWithSn(), rn_timer_cancel(), tcp_host_timeout_rc(), tcp_layer_timeout_rc(), tcp_timeout_rc(), and tw_timer_reset().
tw_timer tw_timer_event_new (tw_lp * dest, tw_stime recv_ts, tw_lp * src)
Definition at line 6 of file tw-timer.c.
References tw_pe::abort_event, tw_event::cancel_next, tw_event::caused_by_me, tw_event::dest_lp, g_tw_ts_end, tw_event::next, tw_event::owner, tw_lp::pe, tw_event::prev, tw_event::recv_ts, tw_event::src_lp, tw_event::state, and tw_event_grab().
Referenced by tw_timer_init().
void tw_timer_event_send (tw_timer event)
Definition at line 36 of file tw-timer.c.
References tw_pe::abort_event, tw_event::dest_lp, tw_lp::kp, tw_kp::last_time, tw_pe::pq, tw_error(), TW_LOC, and tw_pq_enqueue().
Referenced by tw_timer_init(), and tw_timer_reset().
tw_timer tw_timer_init (tw_lp * lp, tw_stime ts)
Definition at line 65 of file tw-timer.c.
References g_tw_ts_end, tw_timer_event_new(), and tw_timer_event_send().
Referenced by epi_location_timer(), rn_timer_init(), ScheduleTimer(), ScheduleTimerWithSn(), tcp_host_process_ack_rc(), tcp_host_startup(), tcp_host_timeout(), tcp_layer_process_ack_rc(), tcp_lp_init(), tcp_process_ack_rc(), tmr_event_handler_rc(), tmr_init(), and tw_timer_reset().
void tw_timer_reset (tw_lp * lp, tw_timer * e, tw_stime ts)
Definition at line 105 of file tw-timer.c.
References tw_pe::cur_event, g_tw_ts_end, tw_lp::pe, TW_pe_pq, tw_pq_delete_any(), tw_timer_cancel(), tw_timer_event_send(), and tw_timer_init().
Referenced by epi_location_timer(), rn_timer_reset(), tcp_host_process_ack(), tcp_host_process_ack_rc(), tcp_host_update_rtt(), tcp_layer_process_ack_rc(), tcp_process_ack_rc(), tmr_event_handler(), and tmr_event_handler_rc().