ROSS: core/tw-timing.c File Reference
tw-timing.c File Reference
#include "tw-timing.h"
#include "ross-extern.h"
#include <string.h>
#include <sys/time.h>
Functions
void tw_wall_now (tw_wtime *t)
void tw_wall_sub (tw_wtime *r, tw_wtime *a, tw_wtime *b)
double tw_wall_to_double (tw_wtime *t)
Function Documentation
tw_wall_now()
void tw_wall_now (tw_wtime * t)
Definition at line 7 of file tw-timing.c.
References tw_error(), and TW_LOC.
Referenced by tw_scheduler_conservative(), tw_scheduler_optimistic(), tw_scheduler_optimistic_debug(), tw_scheduler_optimistic_realtime(), tw_scheduler_sequential(), and tw_scheduler_sequential_rollback_check().
tw_wall_sub()
void tw_wall_sub (tw_wtime * r, tw_wtime * a, tw_wtime * b)
Definition at line 14 of file tw-timing.c.
Referenced by tw_get_stats().
tw_wall_to_double()
double tw_wall_to_double (tw_wtime * t)
Definition at line 27 of file tw-timing.c.
Referenced by tw_get_stats().