ROSS: ross/tw-util.c File Reference
tw-util.c File Reference
#include <ross.h>
Data Structures
struct mem_pool
Functions
int tw_output (tw_lp *lp, const char *fmt,...)
void tw_printf (const char *file, int line, const char *fmt,...)
void tw_error (const char *file, int line, const char *fmt,...)
void tw_exit (int rv)
static void * my_malloc (size_t len)
void tw_calloc_stats (size_t *bytes_alloc, size_t *bytes_wasted)
static void * pool_alloc (size_t len)
void * tw_calloc (const char *file, int line, const char *for_who, size_t e_sz, size_t n)
void * tw_unsafe_realloc (const char *file, int line, const char *for_who, void *addr, size_t len)
Variables
static struct mem_pool * main_pool
static const size_t pool_size = (512 * 1024) - 32
static const size_t pool_align = ((sizeof(double)) > (sizeof(void*)) ? (sizeof(double)) : (sizeof(void*)))
static size_t total_allocated
static unsigned malloc_calls
Function Documentation
static void * my_malloc (size_t len) static
Definition at line 205 of file tw-util.c.
Referenced by pool_alloc().
static void* pool_alloc (size_t len) static
Definition at line 127 of file tw-util.c.
References mem_pool::end_free, main_pool, my_malloc(), mem_pool::next_free, mem_pool::next_pool, p, and pool_size.
Referenced by tw_calloc().
void* tw_calloc (const char * file, int line, const char * for_who, size_t e_sz, size_t n)
Definition at line 170 of file tw-util.c.
References pool_alloc(), and tw_error().
Referenced by _rm_init(), _tlm_init(), allocate_table(), epi_disease_init(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), epi_main(), epi_setup_options(), epi_xml(), init_default_ic_stages(), init_default_profiles(), init_ic_stages_from_file(), init_nodes(), init_output_messages(), init_profiles_from_file(), init_q(), init_socket(), ip_init(), ip_md_init(), main(), num_init(), num_init_scenario(), num_main(), num_setup_options(), num_xml(), ospf_main(), ospf_routing_init(), ospf_setup_options(), ospf_startup(), pm_init(), read_vector(), rm_getlocation(), rm_grid_terrain(), rm_initialize(), rm_initialize_terrain(), rm_pe_init(), rn_allocate_table(), rn_hash_create(), rn_setup_mobility(), rn_setup_streams(), rn_xml_topology(), rng_init(), routing_init_ft_write(), routing_read(), rp_init(), rp_md_init(), rw_init(), rw_md_init(), tcp_init(), tcp_md_init(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tmr_init(), tw_define_lps(), tw_eventq_alloc(), tw_hash_create(), tw_init_kps(), tw_kp_onpe(), tw_lp_onpe(), tw_memory_allocate(), tw_memoryq_init(), tw_net_start(), tw_net_statistics(), tw_pe_create(), tw_pe_init(), tw_pq_create(), tw_rand_init_streams(), tw_socket_create_onport(), and tw_state_alloc().
void tw_calloc_stats (size_t * bytes_alloc, size_t * bytes_wasted)
Definition at line 113 of file tw-util.c.
References mem_pool::end_free, mem_pool::next_free, mem_pool::next_pool, p, and total_allocated.
Referenced by tw_stats().
void tw_error (const char * file, int line, const char * fmt, ...)
Definition at line 74 of file tw-util.c.
References g_tw_mynode, and tw_net_abort().
Referenced by _rm_event_handler(), _rm_init(), _rm_rc_event_handler(), _tlm_event_handler(), _tlm_init(), _tlm_rc_event_handler(), agent_stage_tran(), apply_opt(), avl_alloc(), avlDelete(), avlInsert(), bgp_event_handler(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_lsa_find(), bgp_main(), bgp_ospf_flush(), bgp_route_add(), bgp_route_copy(), bgp_route_free(), bgp_setup_ases(), bgp_setup_options(), bgp_update(), bgp_update_all(), bgp_update_send(), bgp_xml(), Cell_CompletionCall(), Cell_ComputeMove(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), Cell_NextCall(), Cell_StartUp(), CellMapping_to_local_index(), CellMapping_to_lp(), change_direction(), early_sanity_check(), epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_event_handler(), epi_init(), epi_init_agent(), epi_init_agent_default(), epi_init_disease(), epi_init_disease_default(), epi_init_hospital(), epi_location_timer(), epi_main(), epi_num_check_report(), epi_num_remove(), epi_seir_compute(), epi_setup_options(), epi_timer_cancel(), epi_timer_start(), epi_xml(), event_cancel(), find_empty(), find_entry(), forward(), ftp_event_handler(), ftp_rc_event_handler(), getlsa(), init_ic_stages_from_file(), init_nodes(), init_profiles_from_file(), init_rib(), init_stream(), ip_downstream_forward(), ip_event_handler(), ip_md_final(), ip_md_init(), ip_rc_downstream(), ip_rc_event_handler(), late_sanity_check(), main(), main_setup_areas(), map_linear(), mem_alloc(), mem_event_handler(), mem_event_handler_rc(), mem_stats_print(), mem_verify(), neighbor_init(), network_spawn(), num_file_complete(), num_init_scenario(), num_rc_event_handler(), num_setup_options(), num_start(), num_timer_cancel(), num_timer_start(), num_update(), olsr_change_region(), olsr_custom_mapping(), olsr_departure_from_mpr(), olsr_grid_mapping(), olsr_map_to_local_index(), olsr_map_to_lp(), olsr_region_event_handler(), olsr_region_event_handler_rc(), olsr_region_init(), ospf_db_init(), ospf_db_read(), ospf_event_handler(), ospf_get_neighbor(), ospf_hello_packet(), ospf_hello_packet_rc(), ospf_interface_calc_dr(), ospf_interface_event_handler(), ospf_ip_route(), ospf_ls_request_recv(), ospf_lsa_allocate(), ospf_lsa_create(), ospf_lsa_find(), ospf_lsa_flood(), ospf_main(), ospf_nbr_event_handler(), ospf_nbr_neg_done(), ospf_nbr_reset_rc(), ospf_nbr_seqnum_mismatch(), ospf_nbr_two_way_recv(), ospf_rc_event_handler(), ospf_routing_init(), ospf_rt_timer(), ospf_setup_options(), ospf_xml(), pcs_grid_mapping(), phold_event_handler(), pm_event_handler(), pm_init(), pm_init_scenario(), pm_pe_final(), pm_rc_event_handler(), recv_begin(), recv_finish(), rehash(), rm_cell_handler(), rm_getlocation(), rm_grid_init(), rm_grid_terrain(), rm_initialize(), rm_move(), rm_particle_handler(), rm_particle_send(), rm_pe_final(), rm_pe_init(), rm_rc_cell_handler(), rm_run(), rm_wave_initiate(), rn_event_handler(), rn_event_send(), rn_find_entry(), rn_getstream(), rn_hash_create(), rn_hash_fetch(), rn_hash_insert(), rn_hash_remove(), rn_link_getstatus(), rn_map(), rn_message_setdirection(), rn_nextmachine_onsn(), rn_print_statistics(), rn_rc_event_handler(), rn_reverse_event_send(), rn_route(), rn_setup_layers(), rn_setup_streams(), rn_xml_init(), rn_xml_model(), rn_xml_topology(), rng_gen_reverse_val(), routing_init_ft_read(), routing_init_ft_write(), routing_read(), routing_write(), rp_event_handler(), rp_rc_event_handler(), rw_event_handler(), rw_rc_event_handler(), send_begin(), send_finish(), setup_pes(), socket_accept(), start_transfer(), tcp_event_handler(), tcp_host_EventHandler(), tcp_host_process_data(), tcp_host_rc_EventHandler(), tcp_layer_event_handler(), tcp_layer_process_data(), tcp_layer_rc_event_handler(), tcp_md_final(), tcp_md_init(), tcp_process_ack(), tcp_process_data(), tcp_rc_event_handler(), tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_router_EventHandler(), tcp_router_rc_EventHandler(), tcp_timer_cancel(), tcp_timer_reset(), test_q(), tlm_cell_handler(), tlm_getlocation(), tlm_grid_init(), tlm_md_init(), tlm_move(), tlm_particle_handler(), tlm_particle_send(), tlm_rc_cell_handler(), tlm_xml(), tmr_init(), traffic_grid_mapping(), tw_calloc(), tw_client_socket_create(), tw_define_lps(), tw_event_send(), tw_eventq_alloc(), tw_eventq_debug(), tw_getkp(), tw_getlocal_lp(), tw_getlp(), tw_getpe(), tw_gvt_compute(), tw_gvt_set(), tw_gvt_step2(), tw_hash_create(), tw_hash_remove(), tw_init(), tw_init_lps(), tw_kp_onpe(), tw_kp_rollback_event(), tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_memory_alloc(), tw_memory_alloc_rc(), tw_memory_allocate(), tw_memory_free_rc(), tw_memory_init(), tw_memoryq_debug(), tw_memoryq_init(), tw_net_barrier(), tw_net_cancel(), tw_net_destlp(), tw_net_init(), tw_net_send(), tw_net_start(), tw_net_statistics(), tw_net_stop(), tw_opt_parse(), tw_pe_init(), tw_pe_settype(), tw_pq_delete_any(), tw_pq_dequeue(), tw_pq_minimum(), tw_rand_init_streams(), tw_rand_normal01(), tw_run(), tw_sched_batch(), tw_sched_cancel_q(), tw_sched_event_q(), tw_scheduler_conservative(), tw_scheduler_optimistic_debug(), tw_scheduler_sequential(), tw_server_socket_create(), tw_sigsegv(), tw_sigterm(), tw_socket_create_onport(), tw_socket_read(), tw_socket_read_event(), tw_socket_send(), tw_socket_send_event(), tw_timer_cancel(), tw_timer_event_send(), tw_unsafe_realloc(), tw_wall_now(), update_add(), verify_topology(), wifi_access_point_event_handler(), wifi_access_point_event_handler_rc(), and xml_link_topology().
void tw_exit (int rv)
Definition at line 90 of file tw-util.c.
References tw_net_stop().
Referenced by AddExtPkt(), Cell_CompletionCall(), Cell_EventHandler(), Cell_MoveCallIn(), Cell_MoveCallOut(), ForwardPacket(), ForwardUnicastPkt(), GetExtPktRef(), GmccRcvInit(), GmccRcvPktHandler(), GmccRcvProcCtrlPkt(), GmccSrcInit(), GmccSrcPktHandler(), GmccSrcTimer(), McastEventHandler(), OrmccRcvInit(), OrmccRcvPktHandler(), OrmccRcvTimer(), OrmccSrcInit(), OrmccSrcPktHandler(), OrmccSrcTimer(), PassPktToUpperLayer(), PgmccRcvInit(), PgmccRcvPktHandler(), PgmccRcvSendPkt(), PgmccSrcInit(), PgmccSrcPktHandler(), PgmccSrcTimer(), RegisterAgent(), RegisterAgentCopy(), ScheduleTimer(), ScheduleTimerWithSn(), SetExtPktRef(), tcp_host_EventHandler(), tcp_host_rc_EventHandler(), tcp_router_EventHandler(), tcp_router_rc_EventHandler(), TfmccRcvAddPktToHistory(), TfmccRcvEstLoss(), TfmccRcvInit(), TfmccRcvPktHandler(), TfmccSrcInit(), and TfmccSrcPktHandler().
int tw_output (tw_lp * lp, const char * fmt, ...)
Rollback-aware printf, i.e. if the event gets rolled back, undo the printf. We can'd do that of course so we store the message in a buffer until GVT.
Definition at line 8 of file tw-util.c.
References tw_pe::cur_event, g_tw_synchronization_protocol, tw_kp::id, tw_lp::kp, tw_out::message, tw_out::next, OPTIMISTIC, tw_event::out_msgs, tw_lp::pe, tw_kp_grab_output_buffer(), TW_LOC, and tw_printf().
void tw_printf (const char * file, int line, const char * fmt, ...)
Definition at line 61 of file tw-util.c.
Referenced by early_sanity_check(), epi_setup_options(), init_nodes(), ospf_ip_route(), pm_move(), rn_reverse_event_send(), rp_move(), rw_move(), tcp_process_data(), tw_event_grab(), tw_output(), and tw_sigsegv().
void* tw_unsafe_realloc (const char * file, int line, const char * for_who, void * addr, size_t len)
Definition at line 213 of file tw-util.c.
References tw_error().
Referenced by tw_pq_create(), and tw_pq_enqueue().
Variable Documentation
struct mem_pool* main_pool static
Definition at line 103 of file tw-util.c.
Referenced by pool_alloc().
unsigned malloc_calls static
Definition at line 109 of file tw-util.c.
const size_t pool_align = ((sizeof(double)) > (sizeof(void*)) ? (sizeof(double)) : (sizeof(void*))) static
Definition at line 107 of file tw-util.c.
const size_t pool_size = (512 * 1024) - 32 static
Definition at line 106 of file tw-util.c.
Referenced by pool_alloc().
size_t total_allocated static
Definition at line 108 of file tw-util.c.
Referenced by tw_calloc_stats().