ROSS: ross/models/udp/udp-pareto.c File Reference
udp-pareto.c File Reference
#include <ross.h>
Data Structures
struct Application_State
struct Link_State
struct Router_State
struct State
struct Packet_Data
struct Network_Statistics
Macros
#define APPLICATION_NEXT_BURST 100
#define APPLICATION_RECV 110
#define LINK_ENQUEUE 1000
#define LINK_DEQUEUE 1100
#define ROUTER_ARRIVAL 10000
#define ROUTER_RECV 11000
#define TW_APPLICATION 1
#define TW_LINK 2
#define TW_ROUTER 3
Functions
void Application_Init (struct State *SV, tw_lp *lp)
void Application_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_Next_Burst (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_Recv (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void RC_Not_Supported_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_CollectStats (struct State *SV, tw_lp *lp)
void Link_Init (struct State *SV, tw_lp *lp)
void Link_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_EnQueue (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_DeQueue (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_CollectStats (struct State *SV, tw_lp *lp)
void Router_Init (struct State *SV, tw_lp *lp)
void Router_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_Arrival (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_Recv (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_CollectStats (struct State *SV, tw_lp *lp)
int main (int argc, char **argv)
Variables
int number_of_applications = 1024
int packet_size = 500
double burst_time = 500.0
double idle_time = 100.0
double packet_rate = 200000.0
double pareto_shape = 1.5
double pareto_interval = 0
double pareto_p1 = 0.0
double pareto_p2 = 0.0
double link_bandwidth = 10000000
double link_delay = 10.0
int router_zero_lp_id
int router_one_lp_id
int link_lp_id
struct Network_Statistics NetStats
tw_lptype mylps []
Macro Definition Documentation
#define APPLICATION_NEXT_BURST 100
Definition at line 6 of file udp-pareto.c.
#define APPLICATION_RECV 110
Definition at line 7 of file udp-pareto.c.
#define LINK_DEQUEUE 1100
Definition at line 10 of file udp-pareto.c.
#define LINK_ENQUEUE 1000
Definition at line 9 of file udp-pareto.c.
#define ROUTER_ARRIVAL 10000
Definition at line 12 of file udp-pareto.c.
#define ROUTER_RECV 11000
Definition at line 13 of file udp-pareto.c.
#define TW_APPLICATION 1
Definition at line 15 of file udp-pareto.c.
Referenced by main().
#define TW_LINK 2
Definition at line 16 of file udp-pareto.c.
Referenced by main().
#define TW_ROUTER 3
Definition at line 17 of file udp-pareto.c.
Referenced by main().
Function Documentation
void Application_CollectStats (struct State * SV, tw_lp * lp)
void Application_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Application_Init (struct State * SV, tw_lp * lp)
void Application_Next_Burst (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Application_Recv (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Link_CollectStats (struct State * SV, tw_lp * lp)
void Link_DeQueue (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Link_EnQueue (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Link_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Link_Init (struct State * SV, tw_lp * lp)
int main (int argc, char ** argv)
Definition at line 421 of file udp-pareto.c.
References Application_State::burst_time, g_tw_events_per_pe, g_tw_gvt_interval, g_tw_mblock, g_tw_ts_end, idle_time, link_bandwidth, link_delay, link_lp_id, NetStats, number_of_applications, packet_rate, packet_size, pareto_interval, pareto_p1, pareto_p2, pareto_shape, pe, router_one_lp_id, router_zero_lp_id, Network_Statistics::total_packets_recved, Network_Statistics::total_packets_sent, TW_APPLICATION, tw_getkp(), tw_getlp(), tw_getpe(), tw_init(), tw_kp_onpe(), TW_LINK, tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), TW_ROUTER, and tw_run().
void RC_Not_Supported_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Router_Arrival (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Router_CollectStats (struct State * SV, tw_lp * lp)
void Router_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
void Router_Init (struct State * SV, tw_lp * lp)
void Router_Recv (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Variable Documentation
double burst_time = 500.0
Definition at line 26 of file udp-pareto.c.
double idle_time = 100.0
Definition at line 27 of file udp-pareto.c.
double link_bandwidth = 10000000
Definition at line 35 of file udp-pareto.c.
double link_delay = 10.0
Definition at line 36 of file udp-pareto.c.
int link_lp_id
Definition at line 40 of file udp-pareto.c.
tw_lptype mylps[]
Initial value:
=
{
        { 1 , sizeof(struct Application_State),
         (init_f) Application_Init,
         (event_f) Application_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Application_CollectStats,
         (statecp_f) NULL},
        { 2 , sizeof(struct Link_State),
         (init_f) Link_Init,
         (event_f) Link_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Link_CollectStats,
         (statecp_f) NULL},
        { 3 , sizeof(struct Router_State),
         (init_f) Router_Init,
         (event_f) Router_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Router_CollectStats,
         (statecp_f) NULL},
        {0}
}
Definition at line 392 of file udp-pareto.c.
struct Network_Statistics NetStats
int number_of_applications = 1024
Definition at line 23 of file udp-pareto.c.
double packet_rate = 200000.0
Definition at line 29 of file udp-pareto.c.
int packet_size = 500
Definition at line 25 of file udp-pareto.c.
double pareto_interval = 0
Definition at line 31 of file udp-pareto.c.
Referenced by main().
double pareto_p1 = 0.0
Definition at line 32 of file udp-pareto.c.
Referenced by main().
double pareto_p2 = 0.0
Definition at line 33 of file udp-pareto.c.
Referenced by main().
double pareto_shape = 1.5
Definition at line 30 of file udp-pareto.c.
int router_one_lp_id
Definition at line 39 of file udp-pareto.c.
int router_zero_lp_id
Definition at line 38 of file udp-pareto.c.