ROSS: ross/models/udp/udp-exp.c File Reference
udp-exp.c File Reference
#include <ross.h>
Data Structures
struct Application_State
struct Link_State
struct Router_State
struct State
struct Packet_Data
struct Network_Statistics
Macros
#define APPLICATION_NEXT_BURST 100
#define APPLICATION_RECV 110
#define LINK_ENQUEUE 1000
#define LINK_DEQUEUE 1100
#define ROUTER_ARRIVAL 10000
#define ROUTER_RECV 11000
#define TW_APPLICATION 1
#define TW_LINK 2
#define TW_ROUTER 3
Functions
tw_peid Application_Map (tw_lpid gid)
void Application_Init (struct State *SV, tw_lp *lp)
void Application_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_Next_Burst (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_Recv (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void RC_Not_Supported_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Application_CollectStats (struct State *SV, tw_lp *lp)
void Link_Init (struct State *SV, tw_lp *lp)
void Link_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_EnQueue (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_DeQueue (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Link_CollectStats (struct State *SV, tw_lp *lp)
void Router_Init (struct State *SV, tw_lp *lp)
void Router_Event_Handler (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_Arrival (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_Recv (struct State *SV, tw_bf *CV, struct Packet_Data *M, tw_lp *lp)
void Router_CollectStats (struct State *SV, tw_lp *lp)
int main (int argc, char **argv)
Variables
int number_of_applications = 100000
int packet_size = 500
double burst_time = 500.0
double idle_time = 100.0
double packet_rate = 2.0
double pareto_shape = 1.5
double link_bandwidth = 10000000
double link_delay = 10.0
int router_zero_lp_id
int router_one_lp_id
int link_lp_id
struct Network_Statistics NetStats
tw_lptype mylps []
Macro Definition Documentation
#define APPLICATION_NEXT_BURST 100
Definition at line 6 of file udp-exp.c.
Referenced by Application_Event_Handler(), and Application_Next_Burst().
#define APPLICATION_RECV 110
Definition at line 7 of file udp-exp.c.
Referenced by Application_Event_Handler(), and Router_Recv().
#define LINK_DEQUEUE 1100
Definition at line 10 of file udp-exp.c.
Referenced by Link_EnQueue(), and Link_Event_Handler().
#define LINK_ENQUEUE 1000
Definition at line 9 of file udp-exp.c.
Referenced by Link_Event_Handler(), and Router_Arrival().
#define ROUTER_ARRIVAL 10000
Definition at line 12 of file udp-exp.c.
Referenced by Application_Next_Burst(), and Router_Event_Handler().
#define ROUTER_RECV 11000
Definition at line 13 of file udp-exp.c.
Referenced by Link_DeQueue(), and Router_Event_Handler().
#define TW_APPLICATION 1
Definition at line 15 of file udp-exp.c.
#define TW_LINK 2
Definition at line 16 of file udp-exp.c.
#define TW_ROUTER 3
Definition at line 17 of file udp-exp.c.
Function Documentation
void Application_CollectStats (struct State * SV, tw_lp * lp)
Definition at line 228 of file udp-exp.c.
References State::application, NetStats, Application_State::packets_recved, Application_State::packets_sent, Network_Statistics::total_packets_recved, Network_Statistics::total_packets_sent, and State::u.
void Application_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 138 of file udp-exp.c.
References APPLICATION_NEXT_BURST, Application_Next_Burst(), APPLICATION_RECV, Application_Recv(), and Packet_Data::method_name.
void Application_Init (struct State * SV, tw_lp * lp)
Definition at line 122 of file udp-exp.c.
References State::application, Application_Next_Burst(), Application_State::burst_time, tw_lp::id, number_of_applications, Application_State::packets_recved, Application_State::packets_sent, Application_State::packets_sent_in_burst, Application_State::router, router_one_lp_id, router_zero_lp_id, Application_State::sequence_number, tw_getlp(), and State::u.
tw_peid Application_Map (tw_lpid gid)
Definition at line 116 of file udp-exp.c.
References g_tw_nlp.
void Application_Next_Burst (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 152 of file udp-exp.c.
References State::application, APPLICATION_NEXT_BURST, burst_time, Application_State::burst_time, Packet_Data::destination, tw_lp::gid, tw_lp::id, idle_time, Packet_Data::method_name, number_of_applications, packet_rate, Application_State::packets_sent, Application_State::packets_sent_in_burst, tw_lp::rng, Application_State::router, ROUTER_ARRIVAL, Application_State::sequence_number, Packet_Data::sequence_number, tw_event_data(), tw_event_new(), tw_event_send(), tw_getlp(), tw_now(), tw_rand_exponential(), tw_rand_integer(), and State::u.
Referenced by Application_Event_Handler(), and Application_Init().
void Application_Recv (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 210 of file udp-exp.c.
References State::application, Packet_Data::destination, tw_lp::id, Application_State::packets_recved, Packet_Data::sequence_number, tw_now(), and State::u.
Referenced by Application_Event_Handler().
void Link_CollectStats (struct State * SV, tw_lp * lp)
Definition at line 314 of file udp-exp.c.
References Link_State::dropped_packets, tw_lp::gid, State::link, and State::u.
void Link_DeQueue (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 276 of file udp-exp.c.
References Link_State::data_in_transit, Packet_Data::destination, tw_lp::id, State::link, Packet_Data::method_name, number_of_applications, packet_size, router_one_lp_id, ROUTER_RECV, router_zero_lp_id, Packet_Data::sequence_number, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and State::u.
Referenced by Link_Event_Handler().
void Link_EnQueue (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 245 of file udp-exp.c.
References Link_State::data_in_transit, Packet_Data::destination, Link_State::dropped_packets, tw_lp::gid, tw_lp::id, State::link, link_delay, LINK_DEQUEUE, Link_State::max_data_in_transit, Packet_Data::method_name, packet_size, Packet_Data::sequence_number, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and State::u.
Referenced by Link_Event_Handler().
void Link_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 300 of file udp-exp.c.
References LINK_DEQUEUE, Link_DeQueue(), LINK_ENQUEUE, Link_EnQueue(), and Packet_Data::method_name.
void Link_Init (struct State * SV, tw_lp * lp)
Definition at line 238 of file udp-exp.c.
References Link_State::data_in_transit, Link_State::dropped_packets, State::link, link_bandwidth, link_delay, Link_State::max_data_in_transit, and State::u.
int main (int argc, char ** argv)
Definition at line 428 of file udp-exp.c.
References g_tw_events_per_pe, g_tw_nkp, g_tw_npe, g_tw_ts_end, link_lp_id, NetStats, number_of_applications, router_one_lp_id, router_zero_lp_id, Network_Statistics::total_packets_recved, Network_Statistics::total_packets_sent, tw_define_lps(), tw_getkp(), tw_getpe(), tw_init(), tw_kp_onpe(), tw_lp_onkp(), tw_lp_onpe(), tw_lp_settype(), tw_nnodes(), and tw_run().
void RC_Not_Supported_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 221 of file udp-exp.c.
void Router_Arrival (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 341 of file udp-exp.c.
References Packet_Data::destination, tw_lp::id, LINK_ENQUEUE, link_lp_id, Packet_Data::method_name, Router_State::packets_sent, State::router, Packet_Data::sequence_number, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and State::u.
Referenced by Router_Event_Handler().
void Router_CollectStats (struct State * SV, tw_lp * lp)
Definition at line 384 of file udp-exp.c.
void Router_Event_Handler (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 327 of file udp-exp.c.
References Packet_Data::method_name, ROUTER_ARRIVAL, Router_Arrival(), ROUTER_RECV, and Router_Recv().
void Router_Init (struct State * SV, tw_lp * lp)
Definition at line 320 of file udp-exp.c.
References Router_State::packets_recved, Router_State::packets_sent, State::router, and State::u.
void Router_Recv (struct State * SV, tw_bf * CV, struct Packet_Data * M, tw_lp * lp)
Definition at line 363 of file udp-exp.c.
References APPLICATION_RECV, Packet_Data::destination, tw_lp::gid, tw_lp::id, Packet_Data::method_name, Router_State::packets_sent, State::router, Packet_Data::sequence_number, tw_event_data(), tw_event_new(), tw_event_send(), tw_now(), and State::u.
Referenced by Router_Event_Handler().
Variable Documentation
double burst_time = 500.0
Definition at line 26 of file udp-exp.c.
Referenced by Application_Next_Burst().
double idle_time = 100.0
Definition at line 27 of file udp-exp.c.
Referenced by Application_Next_Burst(), and main().
double link_bandwidth = 10000000
Definition at line 32 of file udp-exp.c.
Referenced by Link_Init(), and main().
double link_delay = 10.0
Definition at line 33 of file udp-exp.c.
Referenced by Link_EnQueue(), Link_Init(), and main().
int link_lp_id
Definition at line 37 of file udp-exp.c.
Referenced by main(), and Router_Arrival().
tw_lptype mylps[]
Initial value:
=
{
        {
         (init_f) Application_Init,
         (event_f) Application_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Application_CollectStats,
         (map_f) Application_Map,
         sizeof(struct Application_State),
        },
        {
         (init_f) Link_Init,
         (event_f) Link_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Link_CollectStats,
         (map_f) Application_Map,
          sizeof(struct Link_State),
        },
        {
         (init_f) Router_Init,
         (event_f) Router_Event_Handler,
         (revent_f) RC_Not_Supported_Handler,
         (final_f) Router_CollectStats,
         (map_f) Application_Map,
         sizeof(struct Router_State),
        },
        {0}
}
Definition at line 393 of file udp-exp.c.
struct Network_Statistics NetStats
Referenced by Application_CollectStats(), and main().
int number_of_applications = 100000
Definition at line 23 of file udp-exp.c.
Referenced by Application_Init(), Application_Next_Burst(), Link_DeQueue(), and main().
double packet_rate = 2.0
Definition at line 29 of file udp-exp.c.
Referenced by Application_Next_Burst(), and main().
int packet_size = 500
Definition at line 25 of file udp-exp.c.
Referenced by Link_DeQueue(), Link_EnQueue(), and main().
double pareto_shape = 1.5
Definition at line 30 of file udp-exp.c.
Referenced by main().
int router_one_lp_id
Definition at line 36 of file udp-exp.c.
Referenced by Application_Init(), Link_DeQueue(), and main().
int router_zero_lp_id
Definition at line 35 of file udp-exp.c.
Referenced by Application_Init(), Link_DeQueue(), and main().