ROSS: test/unity.c File Reference
unity.c File Reference
#include "unity.h"
#include <stdio.h>
#include <string.h>
Macros
#define UNITY_FAIL_AND_BAIL { Unity.CurrentTestFailed = 1; UNITY_OUTPUT_CHAR('\n'); longjmp(Unity.AbortFrame, 1); }
#define UNITY_IGNORE_AND_BAIL { Unity.CurrentTestIgnored = 1; UNITY_OUTPUT_CHAR('\n'); longjmp(Unity.AbortFrame, 1); }
#define UNITY_SKIP_EXECUTION { if ((Unity.CurrentTestFailed != 0) || (Unity.CurrentTestIgnored != 0)) {return;} }
return prematurely if we are already in failure or ignore state
#define UNITY_PRINT_EOL { UNITY_OUTPUT_CHAR('\n'); }
Functions
void UnityPrint (const char *string)
void UnityPrintNumberByStyle (const _U_SINT number, const UNITY_DISPLAY_STYLE_T style)
void UnityPrintNumber (const _U_SINT number_to_print)
basically do an itoa using as little ram as possible
void UnityPrintNumberUnsigned (const _U_UINT number)
basically do an itoa using as little ram as possible
void UnityPrintNumberHex (const _U_UINT number, const char nibbles_to_print)
void UnityPrintMask (const _U_UINT mask, const _U_UINT number)
void UnityTestResultsBegin (const char *file, const unsigned short line)
void UnityTestResultsFailBegin (const unsigned short line)
void UnityConcludeTest (void)
void UnityAddMsgIfSpecified (const char *msg)
void UnityPrintExpectedAndActualStrings (const char *expected, const char *actual)
int UnityCheckArraysForNull (const void *expected, const void *actual, const unsigned short lineNumber, const char *msg)
void UnityAssertBits (const _U_SINT mask, const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualNumber (const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertEqualIntArray (const _U_SINT *expected, const _U_SINT *actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertEqualFloatArray (const _UF *expected, const _UF *actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber)
void UnityAssertFloatsWithin (const _UF delta, const _UF expected, const _UF actual, const char *msg, const unsigned short lineNumber)
void UnityAssertNumbersWithin (const _U_SINT delta, const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertEqualString (const char *expected, const char *actual, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualStringArray (const char **expected, const char **actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualMemory (const void *expected, const void *actual, _UU32 length, _UU32 num_elements, const char *msg, const unsigned short lineNumber)
void UnityFail (const char *msg, const unsigned short line)
void UnityIgnore (const char *msg, const unsigned short line)
void setUp (void)
void tearDown (void)
void UnityDefaultTestRun (UnityTestFunction Func, const char *FuncName, const int FuncLineNum)
void UnityBegin (void)
int UnityEnd (void)
Variables
struct _Unity Unity = { 0 }
const char * UnityStrNull = "NULL"
const char * UnityStrSpacer = ". "
const char * UnityStrExpected = " Expected "
const char * UnityStrWas = " Was "
const char * UnityStrTo = " To "
const char * UnityStrElement = " Element "
const char * UnityStrByte = " Byte "
const char * UnityStrMemory = " Memory Mismatch."
const char * UnityStrDelta = " Values Not Within Delta "
const char * UnityStrPointless = " You Asked Me To Compare Nothing, Which Was Pointless."
const char * UnityStrNullPointerForExpected = " Expected pointer to be NULL"
const char * UnityStrNullPointerForActual = " Actual pointer was NULL"
const _U_UINT UnitySizeMask []
Macro Definition Documentation
#define UNITY_FAIL_AND_BAIL { Unity.CurrentTestFailed = 1; UNITY_OUTPUT_CHAR('\n'); longjmp(Unity.AbortFrame, 1); }
Definition at line 11 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), UnityCheckArraysForNull(), and UnityFail().
#define UNITY_IGNORE_AND_BAIL { Unity.CurrentTestIgnored = 1; UNITY_OUTPUT_CHAR('\n'); longjmp(Unity.AbortFrame, 1); }
Definition at line 12 of file unity.c.
Referenced by UnityIgnore().
#define UNITY_PRINT_EOL { UNITY_OUTPUT_CHAR('\n'); }
Definition at line 15 of file unity.c.
Referenced by UnityConcludeTest(), and UnityEnd().
#define UNITY_SKIP_EXECUTION { if ((Unity.CurrentTestFailed != 0) || (Unity.CurrentTestIgnored != 0)) {return;} }
Definition at line 14 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), UnityFail(), and UnityIgnore().
Function Documentation
void setUp (void)
Definition at line 8 of file olsr-test.c.
Referenced by resetTest(), and UnityDefaultTestRun().
void tearDown (void)
Definition at line 4 of file olsr-test.c.
Referenced by resetTest(), and UnityDefaultTestRun().
void UnityAddMsgIfSpecified (const char * msg)
Definition at line 263 of file unity.c.
References UnityPrint(), and UnityStrSpacer.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), and UnityCheckArraysForNull().
void UnityAssertBits (const _U_SINT mask, const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber)
Definition at line 335 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintMask(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualFloatArray (const _UF * expected, const _UF * actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 492 of file unity.c.
References UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_PRECISION, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrDelta, UnityStrElement, UnityStrExpected, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualIntArray (const _U_SINT * expected, const _U_SINT * actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 377 of file unity.c.
References UNITY_DISPLAY_STYLE_HEX16, UNITY_DISPLAY_STYLE_HEX8, UNITY_DISPLAY_STYLE_INT16, UNITY_DISPLAY_STYLE_INT8, UNITY_DISPLAY_STYLE_UINT, UNITY_DISPLAY_STYLE_UINT16, UNITY_DISPLAY_STYLE_UINT8, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrElement, UnityStrExpected, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualMemory (const void * expected, const void * actual, _UU32 length, _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 817 of file unity.c.
References UNITY_DISPLAY_STYLE_HEX8, UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrByte, UnityStrElement, UnityStrExpected, UnityStrMemory, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualNumber (const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 356 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualString (const char * expected, const char * actual, const char * msg, const unsigned short lineNumber)
Definition at line 718 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrintExpectedAndActualStrings(), and UnityTestResultsFailBegin().
void UnityAssertEqualStringArray (const char ** expected, const char ** actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 757 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintExpectedAndActualStrings(), UnityPrintNumberByStyle(), UnityStrElement, UnityStrPointless, and UnityTestResultsFailBegin().
void UnityAssertFloatsWithin (const _UF delta, const _UF expected, const _UF actual, const char * msg, const unsigned short lineNumber)
Definition at line 546 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityStrDelta, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertNumbersWithin (const _U_SINT delta, const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 679 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_DISPLAY_RANGE_INT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrDelta, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityBegin (void)
Definition at line 933 of file unity.c.
References _Unity::NumberOfTests.
Referenced by main().
int UnityCheckArraysForNull (const void * expected, const void * actual, const unsigned short lineNumber, const char * msg)
Definition at line 303 of file unity.c.
References UNITY_FAIL_AND_BAIL, UnityAddMsgIfSpecified(), UnityPrint(), UnityStrNullPointerForActual, UnityStrNullPointerForExpected, and UnityTestResultsFailBegin().
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), and UnityAssertEqualStringArray().
void UnityConcludeTest (void)
Definition at line 241 of file unity.c.
References _Unity::CurrentTestFailed, _Unity::CurrentTestIgnored, _Unity::CurrentTestLineNumber, _Unity::TestFailures, _Unity::TestFile, _Unity::TestIgnores, UNITY_PRINT_EOL, UnityPrint(), and UnityTestResultsBegin().
Referenced by UnityDefaultTestRun().
void UnityDefaultTestRun (UnityTestFunction Func, const char * FuncName, const int FuncLineNum)
Definition at line 915 of file unity.c.
References _Unity::CurrentTestIgnored, _Unity::CurrentTestLineNumber, _Unity::CurrentTestName, _Unity::NumberOfTests, setUp(), tearDown(), TEST_PROTECT, and UnityConcludeTest().
int UnityEnd (void)
Definition at line 939 of file unity.c.
References _Unity::NumberOfTests, _Unity::TestFailures, _Unity::TestIgnores, UNITY_PRINT_EOL, UnityPrint(), and UnityPrintNumber().
Referenced by main().
void UnityFail (const char * msg, const unsigned short line)
Definition at line 878 of file unity.c.
References _Unity::TestFile, UNITY_FAIL_AND_BAIL, UNITY_OUTPUT_CHAR, UNITY_SKIP_EXECUTION, UnityPrint(), and UnityTestResultsBegin().
void UnityIgnore (const char * msg, const unsigned short line)
Definition at line 897 of file unity.c.
References _Unity::TestFile, UNITY_IGNORE_AND_BAIL, UNITY_OUTPUT_CHAR, UNITY_SKIP_EXECUTION, UnityPrint(), and UnityTestResultsBegin().
void UnityPrint (const char * string)
Definition at line 51 of file unity.c.
References UNITY_OUTPUT_CHAR, and UnityPrintNumberHex().
Referenced by UnityAddMsgIfSpecified(), UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), UnityCheckArraysForNull(), UnityConcludeTest(), UnityEnd(), UnityFail(), UnityIgnore(), UnityPrintExpectedAndActualStrings(), UnityTestResultsBegin(), and UnityTestResultsFailBegin().
void UnityPrintExpectedAndActualStrings (const char * expected, const char * actual)
Definition at line 273 of file unity.c.
References UNITY_OUTPUT_CHAR, UnityPrint(), UnityStrExpected, UnityStrNull, and UnityStrWas.
Referenced by UnityAssertEqualString(), and UnityAssertEqualStringArray().
void UnityPrintMask (const _U_UINT mask, const _U_UINT number)
Definition at line 186 of file unity.c.
References UNITY_INT_WIDTH, and UNITY_OUTPUT_CHAR.
Referenced by UnityAssertBits().
void UnityPrintNumber (const _U_SINT number_to_print)
Definition at line 106 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityEnd(), UnityPrintNumberByStyle(), and UnityTestResultsBegin().
void UnityPrintNumberByStyle (const _U_SINT number, const UNITY_DISPLAY_STYLE_T style)
Definition at line 88 of file unity.c.
References UNITY_DISPLAY_RANGE_INT, UNITY_DISPLAY_RANGE_UINT, UnityPrintNumber(), UnityPrintNumberHex(), UnityPrintNumberUnsigned(), and UnitySizeMask.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualStringArray(), and UnityAssertNumbersWithin().
void UnityPrintNumberHex (const _U_UINT number, const char nibbles_to_print)
Definition at line 164 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityPrint(), and UnityPrintNumberByStyle().
void UnityPrintNumberUnsigned (const _U_UINT number)
Definition at line 139 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityPrintNumberByStyle().
void UnityTestResultsBegin (const char * file, const unsigned short line)
Definition at line 223 of file unity.c.
References _Unity::CurrentTestName, UNITY_OUTPUT_CHAR, UnityPrint(), and UnityPrintNumber().
Referenced by UnityConcludeTest(), UnityFail(), UnityIgnore(), and UnityTestResultsFailBegin().
void UnityTestResultsFailBegin (const unsigned short line)
Definition at line 234 of file unity.c.
References _Unity::TestFile, UnityPrint(), and UnityTestResultsBegin().
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualString(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), and UnityCheckArraysForNull().
Variable Documentation
struct _Unity Unity = { 0 }
Definition at line 17 of file unity.c.
Referenced by main().
const _U_UINT UnitySizeMask[]
Initial value:
=
{
    255u,
    65535u,
    65535u,
    4294967295u,
    4294967295u,
    4294967295u,
    4294967295u
}
Definition at line 33 of file unity.c.
Referenced by UnityPrintNumberByStyle().
const char* UnityStrByte = " Byte "
Definition at line 25 of file unity.c.
Referenced by UnityAssertEqualMemory().
const char* UnityStrDelta = " Values Not Within Delta "
Definition at line 27 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), UnityAssertFloatsWithin(), and UnityAssertNumbersWithin().
const char* UnityStrElement = " Element "
Definition at line 24 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), and UnityAssertEqualStringArray().
const char* UnityStrExpected = " Expected "
Definition at line 21 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), and UnityPrintExpectedAndActualStrings().
const char* UnityStrMemory = " Memory Mismatch."
Definition at line 26 of file unity.c.
Referenced by UnityAssertEqualMemory().
const char* UnityStrNull = "NULL"
Definition at line 19 of file unity.c.
Referenced by UnityPrintExpectedAndActualStrings().
const char* UnityStrNullPointerForActual = " Actual pointer was NULL"
Definition at line 30 of file unity.c.
Referenced by UnityCheckArraysForNull().
const char* UnityStrNullPointerForExpected = " Expected pointer to be NULL"
Definition at line 29 of file unity.c.
Referenced by UnityCheckArraysForNull().
const char* UnityStrPointless = " You Asked Me To Compare Nothing, Which Was Pointless."
Definition at line 28 of file unity.c.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), and UnityAssertEqualStringArray().
const char* UnityStrSpacer = ". "
Definition at line 20 of file unity.c.
Referenced by UnityAddMsgIfSpecified().
const char* UnityStrTo = " To "
Definition at line 23 of file unity.c.
const char* UnityStrWas = " Was "
Definition at line 22 of file unity.c.
Referenced by UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), and UnityPrintExpectedAndActualStrings().