ROSS: test/unity_internals.h File Reference
unity_internals.h File Reference
#include <stdio.h>
#include <setjmp.h>
Data Structures
struct _Unity
Macros
#define UNITY_INT_WIDTH (32)
#define UNITY_LONG_WIDTH (32)
#define UNITY_POINTER_WIDTH (32)
#define UNITY_DISPLAY_STYLE_POINTER UNITY_DISPLAY_STYLE_HEX32
#define UNITY_FLOAT_PRECISION (0.00001f)
#define UNITY_FLOAT_TYPE float
#define UNITY_EXCLUDE_DOUBLE
#define UNITY_OUTPUT_CHAR(a) putchar(a)
#define UNITY_LINE_TYPE unsigned short
#define UNITY_COUNTER_TYPE unsigned short
#define UNITY_DISPLAY_RANGE_INT (0x10)
#define UNITY_DISPLAY_RANGE_UINT (0x20)
#define UNITY_DISPLAY_RANGE_HEX (0x40)
#define UNITY_DISPLAY_RANGE_AUTO (0x80)
#define UNITY_TEST_FAIL(line, message) UnityFail((message), (UNITY_LINE_TYPE)line);
#define UNITY_TEST_IGNORE(line, message) UnityIgnore((message), (UNITY_LINE_TYPE)line);
#define UNITY_TEST_ASSERT(condition, line, message) if (condition) {} else {UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, message);}
#define UNITY_TEST_ASSERT_NULL(pointer, line, message) UNITY_TEST_ASSERT(((pointer) == NULL), (UNITY_LINE_TYPE)line, message)
#define UNITY_TEST_ASSERT_NOT_NULL(pointer, line, message) UNITY_TEST_ASSERT(((pointer) != NULL), (UNITY_LINE_TYPE)line, message)
#define UNITY_TEST_ASSERT_EQUAL_INT(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_EQUAL_INT8(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_EQUAL_INT16(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_EQUAL_INT32(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_EQUAL_UINT(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_EQUAL_UINT8(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_EQUAL_UINT16(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_EQUAL_UINT32(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_EQUAL_HEX8(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
#define UNITY_TEST_ASSERT_EQUAL_HEX16(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
#define UNITY_TEST_ASSERT_EQUAL_HEX32(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
#define UNITY_TEST_ASSERT_BITS(mask, expected, actual, line, message) UnityAssertBits((_U_SINT)(mask), (_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_INT_WITHIN(delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(delta), (_U_SINT)(expected), (_U_SINT)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_UINT_WITHIN(delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(delta), (_U_SINT)(expected), (_U_SINT)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_HEX8_WITHIN(delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU8)(delta), (_U_SINT)(_U_UINT)(_UU8)(expected), (_U_SINT)(_U_UINT)(_UU8)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
#define UNITY_TEST_ASSERT_HEX16_WITHIN(delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU16)(delta), (_U_SINT)(_U_UINT)(_UU16)(expected), (_U_SINT)(_U_UINT)(_UU16)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
#define UNITY_TEST_ASSERT_HEX32_WITHIN(delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU32)(delta), (_U_SINT)(_U_UINT)(_UU32)(expected), (_U_SINT)(_U_UINT)(_UU32)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
#define UNITY_TEST_ASSERT_EQUAL_PTR(expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_UP)(expected), (_U_SINT)(_UP)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_POINTER)
#define UNITY_TEST_ASSERT_EQUAL_STRING(expected, actual, line, message) UnityAssertEqualString((const char*)(expected), (const char*)(actual), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_EQUAL_MEMORY(expected, actual, len, line, message) UnityAssertEqualMemory((void*)(expected), (void*)(actual), (_UU32)(len), 1, (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
#define UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT8)
#define UNITY_TEST_ASSERT_EQUAL_INT16_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT16)
#define UNITY_TEST_ASSERT_EQUAL_INT32_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT32)
#define UNITY_TEST_ASSERT_EQUAL_UINT_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
#define UNITY_TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT8)
#define UNITY_TEST_ASSERT_EQUAL_UINT16_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT16)
#define UNITY_TEST_ASSERT_EQUAL_UINT32_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT32)
#define UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
#define UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
#define UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
#define UNITY_TEST_ASSERT_EQUAL_PTR_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(_UP*)(expected), (const _U_SINT*)(_UP*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_POINTER)
#define UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualStringArray((const char**)(expected), (const char**)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY(expected, actual, len, num_elements, line, message) UnityAssertEqualMemory((void*)(expected), (void*)(actual), (_UU32)(len), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_FLOAT_WITHIN(delta, expected, actual, line, message) UnityAssertFloatsWithin((_UF)(delta), (_UF)(expected), (_UF)(actual), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_EQUAL_FLOAT(expected, actual, line, message) UNITY_TEST_ASSERT_FLOAT_WITHIN((_UF)(expected) * (_UF)UNITY_FLOAT_PRECISION, (_UF)expected, (_UF)actual, (UNITY_LINE_TYPE)line, message)
#define UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY(expected, actual, num_elements, line, message) UnityAssertEqualFloatArray((_UF*)(expected), (_UF*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
#define UNITY_TEST_ASSERT_DOUBLE_WITHIN(delta, expected, actual, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
#define UNITY_TEST_ASSERT_EQUAL_DOUBLE(expected, actual, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
#define UNITY_TEST_ASSERT_EQUAL_DOUBLE_ARRAY(expected, actual, num_elements, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
Typedefs
typedef unsigned char _UU8
typedef unsigned short _UU16
typedef unsigned int _UU32
typedef signed char _US8
typedef signed short _US16
typedef signed int _US32
typedef _UU32 _U_UINT
typedef _US32 _U_SINT
typedef _UU32 _UP
typedef float _UF
typedef void(* UnityTestFunction)(void)
Enumerations
enum UNITY_DISPLAY_STYLE_T {
UNITY_DISPLAY_STYLE_INT = 4 + (0x10) + (0x80), UNITY_DISPLAY_STYLE_INT8 = 1 + (0x10), UNITY_DISPLAY_STYLE_INT16 = 2 + (0x10), UNITY_DISPLAY_STYLE_INT32 = 4 + (0x10),
UNITY_DISPLAY_STYLE_UINT = 4 + (0x20) + (0x80), UNITY_DISPLAY_STYLE_UINT8 = 1 + (0x20), UNITY_DISPLAY_STYLE_UINT16 = 2 + (0x20), UNITY_DISPLAY_STYLE_UINT32 = 4 + (0x20),
UNITY_DISPLAY_STYLE_HEX8 = 1 + (0x40), UNITY_DISPLAY_STYLE_HEX16 = 2 + (0x40), UNITY_DISPLAY_STYLE_HEX32 = 4 + (0x40)
}
Functions
void UnityBegin (void)
int UnityEnd (void)
void UnityConcludeTest (void)
void UnityDefaultTestRun (UnityTestFunction Func, const char *FuncName, const int FuncLineNum)
void UnityPrint (const char *string)
void UnityPrintMask (const _U_UINT mask, const _U_UINT number)
void UnityPrintNumberByStyle (const _U_SINT number, const UNITY_DISPLAY_STYLE_T style)
void UnityPrintNumber (const _U_SINT number)
basically do an itoa using as little ram as possible
void UnityPrintNumberUnsigned (const _U_UINT number)
basically do an itoa using as little ram as possible
void UnityPrintNumberHex (const _U_UINT number, const char nibbles)
void UnityAssertEqualNumber (const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertEqualIntArray (const _U_SINT *expected, const _U_SINT *actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityAssertBits (const _U_SINT mask, const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualString (const char *expected, const char *actual, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualStringArray (const char **expected, const char **actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualMemory (const void *expected, const void *actual, const _UU32 length, const _UU32 num_elements, const char *msg, const unsigned short lineNumber)
void UnityAssertNumbersWithin (const _U_SINT delta, const _U_SINT expected, const _U_SINT actual, const char *msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
void UnityFail (const char *message, const unsigned short line)
void UnityIgnore (const char *message, const unsigned short line)
void UnityAssertFloatsWithin (const _UF delta, const _UF expected, const _UF actual, const char *msg, const unsigned short lineNumber)
void UnityAssertEqualFloatArray (const _UF *expected, const _UF *actual, const _UU32 num_elements, const char *msg, const unsigned short lineNumber)
Variables
struct _Unity Unity
Macro Definition Documentation
#define UNITY_COUNTER_TYPE unsigned short
Definition at line 170 of file unity_internals.h.
#define UNITY_DISPLAY_RANGE_AUTO (0x80)
Definition at line 182 of file unity_internals.h.
#define UNITY_DISPLAY_RANGE_HEX (0x40)
Definition at line 181 of file unity_internals.h.
#define UNITY_DISPLAY_RANGE_INT (0x10)
Definition at line 179 of file unity_internals.h.
Referenced by UnityAssertNumbersWithin(), and UnityPrintNumberByStyle().
#define UNITY_DISPLAY_RANGE_UINT (0x20)
Definition at line 180 of file unity_internals.h.
Referenced by UnityPrintNumberByStyle().
#define UNITY_DISPLAY_STYLE_POINTER UNITY_DISPLAY_STYLE_HEX32
Definition at line 80 of file unity_internals.h.
#define UNITY_EXCLUDE_DOUBLE
Definition at line 125 of file unity_internals.h.
#define UNITY_FLOAT_PRECISION (0.00001f)
Definition at line 109 of file unity_internals.h.
Referenced by UnityAssertEqualFloatArray().
#define UNITY_FLOAT_TYPE float
Definition at line 112 of file unity_internals.h.
#define UNITY_INT_WIDTH (32)
Definition at line 18 of file unity_internals.h.
Referenced by UnityPrintMask().
#define UNITY_LINE_TYPE unsigned short
Definition at line 166 of file unity_internals.h.
#define UNITY_LONG_WIDTH (32)
Definition at line 22 of file unity_internals.h.
#define UNITY_OUTPUT_CHAR (a) putchar(a)
Definition at line 155 of file unity_internals.h.
Referenced by UnityFail(), UnityIgnore(), UnityPrint(), UnityPrintExpectedAndActualStrings(), UnityPrintMask(), UnityPrintNumber(), UnityPrintNumberHex(), UnityPrintNumberUnsigned(), and UnityTestResultsBegin().
#define UNITY_POINTER_WIDTH (32)
Definition at line 75 of file unity_internals.h.
#define UNITY_TEST_ASSERT (condition, line, message) if (condition) {} else {UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, message);}
Definition at line 342 of file unity_internals.h.
#define UNITY_TEST_ASSERT_BITS (mask, expected, actual, line, message) UnityAssertBits((_U_SINT)(mask), (_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line)
Definition at line 357 of file unity_internals.h.
#define UNITY_TEST_ASSERT_DOUBLE_WITHIN (delta, expected, actual, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
Definition at line 405 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_DOUBLE (expected, actual, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
Definition at line 406 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_DOUBLE_ARRAY (expected, actual, num_elements, line, message) UNITY_TEST_FAIL((UNITY_LINE_TYPE)line, "Unity Double Precision Disabled")
Definition at line 407 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_FLOAT (expected, actual, line, message) UNITY_TEST_ASSERT_FLOAT_WITHIN((_UF)(expected) * (_UF)UNITY_FLOAT_PRECISION, (_UF)expected, (_UF)actual, (UNITY_LINE_TYPE)line, message)
Definition at line 400 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualFloatArray((_UF*)(expected), (_UF*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
Definition at line 401 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX16 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
Definition at line 355 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
Definition at line 378 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX32 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
Definition at line 356 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
Definition at line 379 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX8 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
Definition at line 354 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
Definition at line 377 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 346 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT16 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 348 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT16_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT16)
Definition at line 371 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT32 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 349 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT32_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT32)
Definition at line 372 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT8 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 347 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT8)
Definition at line 370 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_INT_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 369 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_MEMORY (expected, actual, len, line, message) UnityAssertEqualMemory((void*)(expected), (void*)(actual), (_UU32)(len), 1, (message), (UNITY_LINE_TYPE)line)
Definition at line 367 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY (expected, actual, len, num_elements, line, message) UnityAssertEqualMemory((void*)(expected), (void*)(actual), (_UU32)(len), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
Definition at line 382 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_PTR (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_UP)(expected), (_U_SINT)(_UP)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_POINTER)
Definition at line 365 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_PTR_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(_UP*)(expected), (const _U_SINT*)(_UP*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_POINTER)
Definition at line 380 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_STRING (expected, actual, line, message) UnityAssertEqualString((const char*)(expected), (const char*)(actual), (message), (UNITY_LINE_TYPE)line)
Definition at line 366 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualStringArray((const char**)(expected), (const char**)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line)
Definition at line 381 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(expected), (_U_SINT)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 350 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT16 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US16)(expected), (_U_SINT)(_US16)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 352 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT16_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT16)
Definition at line 375 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT32 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US32)(expected), (_U_SINT)(_US32)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 353 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT32_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT32)
Definition at line 376 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT8 (expected, actual, line, message) UnityAssertEqualNumber((_U_SINT)(_US8)(expected), (_U_SINT)(_US8)(actual), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 351 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT8_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT8)
Definition at line 374 of file unity_internals.h.
#define UNITY_TEST_ASSERT_EQUAL_UINT_ARRAY (expected, actual, num_elements, line, message) UnityAssertEqualIntArray((const _U_SINT*)(expected), (const _U_SINT*)(actual), (_UU32)(num_elements), (message), (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 373 of file unity_internals.h.
#define UNITY_TEST_ASSERT_FLOAT_WITHIN (delta, expected, actual, line, message) UnityAssertFloatsWithin((_UF)(delta), (_UF)(expected), (_UF)(actual), (message), (UNITY_LINE_TYPE)line)
Definition at line 399 of file unity_internals.h.
#define UNITY_TEST_ASSERT_HEX16_WITHIN (delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU16)(delta), (_U_SINT)(_U_UINT)(_UU16)(expected), (_U_SINT)(_U_UINT)(_UU16)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX16)
Definition at line 362 of file unity_internals.h.
#define UNITY_TEST_ASSERT_HEX32_WITHIN (delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU32)(delta), (_U_SINT)(_U_UINT)(_UU32)(expected), (_U_SINT)(_U_UINT)(_UU32)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX32)
Definition at line 363 of file unity_internals.h.
#define UNITY_TEST_ASSERT_HEX8_WITHIN (delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(_U_UINT)(_UU8)(delta), (_U_SINT)(_U_UINT)(_UU8)(expected), (_U_SINT)(_U_UINT)(_UU8)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_HEX8)
Definition at line 361 of file unity_internals.h.
#define UNITY_TEST_ASSERT_INT_WITHIN (delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(delta), (_U_SINT)(expected), (_U_SINT)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_INT)
Definition at line 359 of file unity_internals.h.
#define UNITY_TEST_ASSERT_NOT_NULL (pointer, line, message) UNITY_TEST_ASSERT(((pointer) != NULL), (UNITY_LINE_TYPE)line, message)
Definition at line 344 of file unity_internals.h.
#define UNITY_TEST_ASSERT_NULL (pointer, line, message) UNITY_TEST_ASSERT(((pointer) == NULL), (UNITY_LINE_TYPE)line, message)
Definition at line 343 of file unity_internals.h.
#define UNITY_TEST_ASSERT_UINT_WITHIN (delta, expected, actual, line, message) UnityAssertNumbersWithin((_U_SINT)(delta), (_U_SINT)(expected), (_U_SINT)(actual), NULL, (UNITY_LINE_TYPE)line, UNITY_DISPLAY_STYLE_UINT)
Definition at line 360 of file unity_internals.h.
#define UNITY_TEST_FAIL (line, message) UnityFail((message), (UNITY_LINE_TYPE)line);
Definition at line 335 of file unity_internals.h.
#define UNITY_TEST_IGNORE (line, message) UnityIgnore((message), (UNITY_LINE_TYPE)line);
Definition at line 336 of file unity_internals.h.
Typedef Documentation
typedef _US32 _U_SINT
Definition at line 51 of file unity_internals.h.
typedef _UU32 _U_UINT
Definition at line 50 of file unity_internals.h.
typedef float _UF
Definition at line 114 of file unity_internals.h.
typedef _UU32 _UP
Definition at line 79 of file unity_internals.h.
typedef signed short _US16
Definition at line 30 of file unity_internals.h.
typedef signed int _US32
Definition at line 31 of file unity_internals.h.
typedef signed char _US8
Definition at line 29 of file unity_internals.h.
typedef unsigned short _UU16
Definition at line 27 of file unity_internals.h.
typedef unsigned int _UU32
Definition at line 28 of file unity_internals.h.
typedef unsigned char _UU8
Definition at line 26 of file unity_internals.h.
typedef void(* UnityTestFunction)(void)
Definition at line 177 of file unity_internals.h.
Enumeration Type Documentation
enum UNITY_DISPLAY_STYLE_T
Enumerator
UNITY_DISPLAY_STYLE_INT
UNITY_DISPLAY_STYLE_INT8
UNITY_DISPLAY_STYLE_INT16
UNITY_DISPLAY_STYLE_INT32
UNITY_DISPLAY_STYLE_UINT
UNITY_DISPLAY_STYLE_UINT8
UNITY_DISPLAY_STYLE_UINT16
UNITY_DISPLAY_STYLE_UINT32
UNITY_DISPLAY_STYLE_HEX8
UNITY_DISPLAY_STYLE_HEX16
UNITY_DISPLAY_STYLE_HEX32
Definition at line 184 of file unity_internals.h.
Function Documentation
void UnityAssertBits (const _U_SINT mask, const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber)
Definition at line 335 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintMask(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualFloatArray (const _UF * expected, const _UF * actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 492 of file unity.c.
References UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_FLOAT_PRECISION, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrDelta, UnityStrElement, UnityStrExpected, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualIntArray (const _U_SINT * expected, const _U_SINT * actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 377 of file unity.c.
References UNITY_DISPLAY_STYLE_HEX16, UNITY_DISPLAY_STYLE_HEX8, UNITY_DISPLAY_STYLE_INT16, UNITY_DISPLAY_STYLE_INT8, UNITY_DISPLAY_STYLE_UINT, UNITY_DISPLAY_STYLE_UINT16, UNITY_DISPLAY_STYLE_UINT8, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrElement, UnityStrExpected, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualMemory (const void * expected, const void * actual, const _UU32 length, const _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 817 of file unity.c.
References UNITY_DISPLAY_STYLE_HEX8, UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrByte, UnityStrElement, UnityStrExpected, UnityStrMemory, UnityStrPointless, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualNumber (const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 356 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertEqualString (const char * expected, const char * actual, const char * msg, const unsigned short lineNumber)
Definition at line 718 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrintExpectedAndActualStrings(), and UnityTestResultsFailBegin().
void UnityAssertEqualStringArray (const char ** expected, const char ** actual, const _UU32 num_elements, const char * msg, const unsigned short lineNumber)
Definition at line 757 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_DISPLAY_STYLE_UINT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityCheckArraysForNull(), UnityPrint(), UnityPrintExpectedAndActualStrings(), UnityPrintNumberByStyle(), UnityStrElement, UnityStrPointless, and UnityTestResultsFailBegin().
void UnityAssertFloatsWithin (const _UF delta, const _UF expected, const _UF actual, const char * msg, const unsigned short lineNumber)
Definition at line 546 of file unity.c.
References UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityStrDelta, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityAssertNumbersWithin (const _U_SINT delta, const _U_SINT expected, const _U_SINT actual, const char * msg, const unsigned short lineNumber, const UNITY_DISPLAY_STYLE_T style)
Definition at line 679 of file unity.c.
References _Unity::CurrentTestFailed, UNITY_DISPLAY_RANGE_INT, UNITY_FAIL_AND_BAIL, UNITY_SKIP_EXECUTION, UnityAddMsgIfSpecified(), UnityPrint(), UnityPrintNumberByStyle(), UnityStrDelta, UnityStrExpected, UnityStrWas, and UnityTestResultsFailBegin().
void UnityBegin (void)
Definition at line 933 of file unity.c.
References _Unity::NumberOfTests.
Referenced by main().
void UnityConcludeTest (void)
Definition at line 241 of file unity.c.
References _Unity::CurrentTestFailed, _Unity::CurrentTestIgnored, _Unity::CurrentTestLineNumber, _Unity::TestFailures, _Unity::TestFile, _Unity::TestIgnores, UNITY_PRINT_EOL, UnityPrint(), and UnityTestResultsBegin().
Referenced by UnityDefaultTestRun().
void UnityDefaultTestRun (UnityTestFunction Func, const char * FuncName, const int FuncLineNum)
Definition at line 915 of file unity.c.
References _Unity::CurrentTestIgnored, _Unity::CurrentTestLineNumber, _Unity::CurrentTestName, _Unity::NumberOfTests, setUp(), tearDown(), TEST_PROTECT, and UnityConcludeTest().
int UnityEnd (void)
Definition at line 939 of file unity.c.
References _Unity::NumberOfTests, _Unity::TestFailures, _Unity::TestIgnores, UNITY_PRINT_EOL, UnityPrint(), and UnityPrintNumber().
Referenced by main().
void UnityFail (const char * message, const unsigned short line)
Definition at line 878 of file unity.c.
References _Unity::TestFile, UNITY_FAIL_AND_BAIL, UNITY_OUTPUT_CHAR, UNITY_SKIP_EXECUTION, UnityPrint(), and UnityTestResultsBegin().
void UnityIgnore (const char * message, const unsigned short line)
Definition at line 897 of file unity.c.
References _Unity::TestFile, UNITY_IGNORE_AND_BAIL, UNITY_OUTPUT_CHAR, UNITY_SKIP_EXECUTION, UnityPrint(), and UnityTestResultsBegin().
void UnityPrint (const char * string)
Definition at line 51 of file unity.c.
References UNITY_OUTPUT_CHAR, and UnityPrintNumberHex().
Referenced by UnityAddMsgIfSpecified(), UnityAssertBits(), UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualStringArray(), UnityAssertFloatsWithin(), UnityAssertNumbersWithin(), UnityCheckArraysForNull(), UnityConcludeTest(), UnityEnd(), UnityFail(), UnityIgnore(), UnityPrintExpectedAndActualStrings(), UnityTestResultsBegin(), and UnityTestResultsFailBegin().
void UnityPrintMask (const _U_UINT mask, const _U_UINT number)
Definition at line 186 of file unity.c.
References UNITY_INT_WIDTH, and UNITY_OUTPUT_CHAR.
Referenced by UnityAssertBits().
void UnityPrintNumber (const _U_SINT number)
Definition at line 106 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityEnd(), UnityPrintNumberByStyle(), and UnityTestResultsBegin().
void UnityPrintNumberByStyle (const _U_SINT number, const UNITY_DISPLAY_STYLE_T style)
Definition at line 88 of file unity.c.
References UNITY_DISPLAY_RANGE_INT, UNITY_DISPLAY_RANGE_UINT, UnityPrintNumber(), UnityPrintNumberHex(), UnityPrintNumberUnsigned(), and UnitySizeMask.
Referenced by UnityAssertEqualFloatArray(), UnityAssertEqualIntArray(), UnityAssertEqualMemory(), UnityAssertEqualNumber(), UnityAssertEqualStringArray(), and UnityAssertNumbersWithin().
void UnityPrintNumberHex (const _U_UINT number, const char nibbles)
Definition at line 164 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityPrint(), and UnityPrintNumberByStyle().
void UnityPrintNumberUnsigned (const _U_UINT number)
Definition at line 139 of file unity.c.
References UNITY_OUTPUT_CHAR.
Referenced by UnityPrintNumberByStyle().
Variable Documentation
struct _Unity Unity
Definition at line 17 of file unity.c.
Referenced by main().