ROSS: rnf/modules/network/multicast/Util.c File Reference
Util.c File Reference
#include "Util.h"
Functions
int ReadLine (int fd, char *buf)
Function Documentation
int ReadLine (int fd, char * buf)
Definition at line 7 of file Util.c.
References MAX_LINE_LEN.
Referenced by ReadAgentAct(), ReadGroupOp(), and ReadTopo().