ROSS: rnf/modules/network/multicast/Util.h File Reference
Util.h File Reference
#include <unistd.h>
#include <string.h>
Macros
#define MAX_LINE_LEN 256
Functions
int ReadLine (int fd, char *buf)
Macro Definition Documentation
#define MAX_LINE_LEN 256
Definition at line 7 of file Util.h.
Referenced by ReadAgentAct(), ReadGroupOp(), ReadLine(), and ReadTopo().
Function Documentation
int ReadLine (int fd, char * buf)
Definition at line 7 of file Util.c.
References MAX_LINE_LEN.
Referenced by ReadAgentAct(), ReadGroupOp(), and ReadTopo().