ROSS: ross/models/wifi/wifi.c File Reference
wifi.c File Reference
#include "wifi.h"
Functions
tw_peid wifi_map (tw_lpid gid)
void wifi_access_point_init (wifi_access_point_state *s, tw_lp *lp)
void wifi_access_point_event_handler (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_access_point_event_handler_rc (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_access_point_arrival (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_station_arrival (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_access_point_arrival_rc (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_station_arrival_rc (wifi_access_point_state *s, tw_bf *bf, wifi_message *m, tw_lp *lp)
void wifi_access_point_finish (wifi_access_point_state *s, tw_lp *lp)
int main (int argc, char **argv, char **env)
Variables
tw_lptype mylps []
const tw_optdef app_opt []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 202 of file wifi.c.
References g_tw_events_per_pe, g_tw_lookahead, g_tw_memory_nqueues, g_tw_mynode, g_tw_nlp, g_tw_npe, g_wifi_start_events, lookahead, mult, nlp_per_pe, offset_lpid, optimistic_memory, ttl_lps, tw_define_lps(), tw_end(), tw_init(), tw_lp_settype(), tw_nnodes(), tw_opt_add(), and tw_run().
void wifi_access_point_arrival (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 50 of file wifi.c.
References wifi_station_state::access_point_snr, wifi_station_state::access_point_success_rate, tw_bf::c1, wifi_access_point_state::failed_packets, tw_lp::gid, num_of_bits, tw_lp::rng, wifi_message::station, wifi_access_point_state::stations, wifi_access_point_state::total_packets, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), tw_rand_normal_sd(), wifi_message::type, WiFi_80211b_DsssDqpskCck11_SuccessRate(), and WIFI_PACKET_ARRIVAL_AT_STATION.
Referenced by wifi_access_point_event_handler().
void wifi_access_point_arrival_rc (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 80 of file wifi.c.
References tw_bf::c1, wifi_access_point_state::failed_packets, tw_lp::rng, wifi_access_point_state::total_packets, and tw_rand_reverse_unif.
Referenced by wifi_access_point_event_handler_rc().
void wifi_access_point_event_handler (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 135 of file wifi.c.
References tw_error(), TW_LOC, wifi_message::type, wifi_access_point_arrival(), WIFI_PACKET_ARRIVAL_AT_ACCESS_POINT, WIFI_PACKET_ARRIVAL_AT_STATION, and wifi_station_arrival().
Referenced by wifi_access_point_init().
void wifi_access_point_event_handler_rc (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 153 of file wifi.c.
References tw_error(), TW_LOC, wifi_message::type, wifi_access_point_arrival_rc(), WIFI_PACKET_ARRIVAL_AT_ACCESS_POINT, WIFI_PACKET_ARRIVAL_AT_STATION, and wifi_station_arrival_rc().
void wifi_access_point_finish (wifi_access_point_state * s, tw_lp * lp)
Definition at line 171 of file wifi.c.
References wifi_station_state::failed_packets, wifi_access_point_state::failed_packets, tw_lp::gid, wifi_access_point_state::stations, wifi_station_state::total_packets, wifi_access_point_state::total_packets, and WIFI_MAX_STATIONS_PER_ACCESS_POINT.
void wifi_access_point_init (wifi_access_point_state * s, tw_lp * lp)
Definition at line 32 of file wifi.c.
References wifi_access_point_state::failed_packets, wifi_message::station, wifi_access_point_state::total_packets, wifi_message::type, wifi_access_point_event_handler(), WIFI_MAX_STATIONS_PER_ACCESS_POINT, and WIFI_PACKET_ARRIVAL_AT_ACCESS_POINT.
tw_peid wifi_map (tw_lpid gid)
Definition at line 28 of file wifi.c.
References g_tw_nlp.
void wifi_station_arrival (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 95 of file wifi.c.
References tw_bf::c1, wifi_station_state::failed_packets, tw_lp::gid, num_of_bits, tw_lp::rng, wifi_message::station, wifi_station_state::station_snr, wifi_station_state::station_success_rate, wifi_access_point_state::stations, wifi_station_state::total_packets, tw_event_data(), tw_event_new(), tw_event_send(), tw_rand_exponential(), tw_rand_normal_sd(), wifi_message::type, WiFi_80211b_DsssDqpskCck11_SuccessRate(), and WIFI_PACKET_ARRIVAL_AT_ACCESS_POINT.
Referenced by wifi_access_point_event_handler().
void wifi_station_arrival_rc (wifi_access_point_state * s, tw_bf * bf, wifi_message * m, tw_lp * lp)
Definition at line 123 of file wifi.c.
References tw_bf::c1, wifi_station_state::failed_packets, tw_lp::rng, wifi_message::station, wifi_access_point_state::stations, and tw_rand_reverse_unif.
Referenced by wifi_access_point_event_handler_rc().
Variable Documentation
const tw_optdef app_opt[]
Initial value:
=
  {
    TWOPT_GROUP("802.11b Model"),
    TWOPT_UINT("nlp", nlp_per_pe, "number of LPs per processor"),
    TWOPT_STIME("mean", mean, "exponential distribution mean for timestamps"),
    TWOPT_STIME("mult", mult, "multiplier for event memory allocation"),
    TWOPT_STIME("lookahead", lookahead, "lookahead for events"),
    TWOPT_UINT("start-events", g_wifi_start_events, "number of initial messages per LP"),
    TWOPT_UINT("memory", optimistic_memory, "additional memory buffers"),
    TWOPT_CHAR("run", run_id, "user supplied run name"),
  }
Definition at line 188 of file wifi.c.
tw_lptype mylps[]
Initial value:
=
{
    {   (init_f) wifi_access_point_init,
        (event_f) wifi_access_point_event_handler,
        (revent_f) wifi_access_point_event_handler_rc,
        (final_f) wifi_access_point_finish,
        (map_f) wifi_map,
        sizeof(wifi_access_point_state)},
    {0},
}
Definition at line 17 of file wifi.c.